DMRITool: ThirdParty/Spams/include/cblas_alt_template.h File Reference
cblas_alt_template.h File Reference
#include <stddef.h>
#include <cblas_defvar.h>
Typedefs
typedef int INTT
Functions
template<typename T >
T cblas_asum (INTT n, T *X, INTT incX)
template<>
double cblas_asum< double > (INTT n, double *X, INTT incX)
template<>
float cblas_asum< float > (INTT n, float *X, INTT incX)
template<typename T >
void cblas_axpy (INTT n, T a, T *X, INTT incX, T *Y, INTT incY)
template<>
void cblas_axpy< bool > (INTT n, bool a, bool *X, INTT incX, bool *Y, INTT incY)
template<>
void cblas_axpy< double > (INTT n, double a, double *X, INTT incX, double *Y, INTT incY)
template<>
void cblas_axpy< float > (INTT n, float a, float *X, INTT incX, float *Y, INTT incY)
template<>
void cblas_axpy< int > (INTT n, int a, int *X, INTT incX, int *Y, INTT incY)
template<typename T >
void cblas_copy (INTT n, T *X, INTT incX, T *Y, INTT incY)
template<>
void cblas_copy< bool > (INTT n, bool *X, INTT incX, bool *Y, INTT incY)
template<>
void cblas_copy< double > (INTT n, double *X, INTT incX, double *Y, INTT incY)
template<>
void cblas_copy< float > (INTT n, float *X, INTT incX, float *Y, INTT incY)
template<>
void cblas_copy< int > (INTT n, int *X, INTT incX, int *Y, INTT incY)
template<typename T >
T cblas_dot (INTT n, T *X, INTT incX, T *Y, INTT incY)
template<>
bool cblas_dot< bool > (INTT n, bool *X, INTT incX, bool *Y, INTT incY)
template<>
double cblas_dot< double > (INTT n, double *X, INTT incX, double *Y, INTT incY)
template<>
float cblas_dot< float > (INTT n, float *X, INTT incX, float *Y, INTT incY)
template<>
int cblas_dot< int > (INTT n, int *X, INTT incX, int *Y, INTT incY)
template<typename T >
void cblas_gemm (CBLAS_ORDER order, CBLAS_TRANSPOSE TransA, CBLAS_TRANSPOSE TransB, INTT M, INTT N, INTT K, T alpha, T *A, INTT lda, T *B, INTT ldb, T beta, T *C, INTT ldc)
template<>
void cblas_gemm< bool > (CBLAS_ORDER order, CBLAS_TRANSPOSE TransA, CBLAS_TRANSPOSE TransB, INTT M, INTT N, INTT K, bool alpha, bool *A, INTT lda, bool *B, INTT ldb, bool beta, bool *C, INTT ldc)
template<>
void cblas_gemm< double > (CBLAS_ORDER order, CBLAS_TRANSPOSE TransA, CBLAS_TRANSPOSE TransB, INTT M, INTT N, INTT K, double alpha, double *A, INTT lda, double *B, INTT ldb, double beta, double *C, INTT ldc)
template<>
void cblas_gemm< float > (CBLAS_ORDER order, CBLAS_TRANSPOSE TransA, CBLAS_TRANSPOSE TransB, INTT M, INTT N, INTT K, float alpha, float *A, INTT lda, float *B, INTT ldb, float beta, float *C, INTT ldc)
template<>
void cblas_gemm< int > (CBLAS_ORDER order, CBLAS_TRANSPOSE TransA, CBLAS_TRANSPOSE TransB, INTT M, INTT N, INTT K, int alpha, int *A, INTT lda, int *B, INTT ldb, int beta, int *C, INTT ldc)
template<typename T >
void cblas_gemv (CBLAS_ORDER order, CBLAS_TRANSPOSE TransA, INTT M, INTT N, T alpha, T *A, INTT lda, T *X, INTT incX, T beta, T *Y, INTT incY)
template<>
void cblas_gemv< bool > (CBLAS_ORDER order, CBLAS_TRANSPOSE TransA, INTT M, INTT N, bool alpha, bool *A, INTT lda, bool *X, INTT incX, bool beta, bool *Y, INTT incY)
template<>
void cblas_gemv< double > (CBLAS_ORDER order, CBLAS_TRANSPOSE TransA, INTT M, INTT N, double alpha, double *A, INTT lda, double *X, INTT incX, double beta, double *Y, INTT incY)
template<>
void cblas_gemv< float > (CBLAS_ORDER order, CBLAS_TRANSPOSE TransA, INTT M, INTT N, float alpha, float *A, INTT lda, float *X, INTT incX, float beta, float *Y, INTT incY)
template<>
void cblas_gemv< int > (CBLAS_ORDER order, CBLAS_TRANSPOSE TransA, INTT M, INTT N, int alpha, int *A, INTT lda, int *X, INTT incX, int beta, int *Y, INTT incY)
template<typename T >
void cblas_ger (CBLAS_ORDER order, INTT M, INTT N, T alpha, T *X, INTT incX, T *Y, INTT incY, T *A, INTT lda)
template<>
void cblas_ger< double > (CBLAS_ORDER order, INTT M, INTT N, double alpha, double *X, INTT incX, double *Y, INTT incY, double *A, INTT lda)
template<>
void cblas_ger< float > (CBLAS_ORDER order, INTT M, INTT N, float alpha, float *X, INTT incX, float *Y, INTT incY, float *A, INTT lda)
template<typename T >
int cblas_iamax (INTT n, T *X, INTT incX)
template<>
int cblas_iamax< double > (INTT n, double *X, INTT incX)
template<>
int cblas_iamax< float > (INTT n, float *X, INTT incX)
template<typename T >
int cblas_iamin (INTT n, T *X, INTT incX)
vcl_size_t cblas_idamin (int n, double *X, int incX)
vcl_size_t cblas_isamin (int n, float *X, int incX)
template<typename T >
T cblas_nrm2 (INTT n, T *X, INTT incX)
template<>
double cblas_nrm2< double > (INTT n, double *X, INTT incX)
template<>
float cblas_nrm2< float > (INTT n, float *X, INTT incX)
template<typename T >
void cblas_scal (INTT n, T a, T *X, INTT incX)
template<>
void cblas_scal< bool > (INTT n, bool a, bool *X, INTT incX)
template<>
void cblas_scal< double > (INTT n, double a, double *X, INTT incX)
template<>
void cblas_scal< float > (INTT n, float a, float *X, INTT incX)
template<>
void cblas_scal< int > (INTT n, int a, int *X, INTT incX)
template<typename T >
void cblas_symv (CBLAS_ORDER order, CBLAS_UPLO Uplo, INTT N, T alpha, T *A, INTT lda, T *X, INTT incX, T beta, T *Y, INTT incY)
template<>
void cblas_symv (CBLAS_ORDER order, CBLAS_UPLO Uplo, INTT N, float alpha, float *A, INTT lda, float *X, INTT incX, float beta, float *Y, INTT incY)
template<>
void cblas_symv (CBLAS_ORDER order, CBLAS_UPLO Uplo, INTT N, double alpha, double *A, INTT lda, double *X, INTT incX, double beta, double *Y, INTT incY)
template<typename T >
void cblas_syr (CBLAS_ORDER order, CBLAS_UPLO Uplo, INTT N, T alpha, T *X, INTT incX, T *A, INTT lda)
template<>
void cblas_syr (CBLAS_ORDER order, CBLAS_UPLO Uplo, INTT N, double alpha, double *X, INTT incX, double *A, INTT lda)
template<>
void cblas_syr (CBLAS_ORDER order, CBLAS_UPLO Uplo, INTT N, float alpha, float *X, INTT incX, float *A, INTT lda)
template<typename T >
void cblas_syrk (CBLAS_ORDER order, CBLAS_UPLO Uplo, CBLAS_TRANSPOSE Trans, INTT N, INTT K, T alpha, T *A, INTT lda, T beta, T *C, INTT ldc)
template<>
void cblas_syrk< bool > (CBLAS_ORDER order, CBLAS_UPLO Uplo, CBLAS_TRANSPOSE Trans, INTT N, INTT K, bool alpha, bool *A, INTT lda, bool beta, bool *C, INTT ldc)
template<>
void cblas_syrk< double > (CBLAS_ORDER order, CBLAS_UPLO Uplo, CBLAS_TRANSPOSE Trans, INTT N, INTT K, double alpha, double *A, INTT lda, double beta, double *C, INTT ldc)
template<>
void cblas_syrk< float > (CBLAS_ORDER order, CBLAS_UPLO Uplo, CBLAS_TRANSPOSE Trans, INTT N, INTT K, float alpha, float *A, INTT lda, float beta, float *C, INTT ldc)
template<>
void cblas_syrk< int > (CBLAS_ORDER order, CBLAS_UPLO Uplo, CBLAS_TRANSPOSE Trans, INTT N, INTT K, int alpha, int *A, INTT lda, int beta, int *C, INTT ldc)
template<typename T >
void cblas_trmm (CBLAS_ORDER order, CBLAS_SIDE Side, CBLAS_UPLO Uplo, CBLAS_TRANSPOSE TransA, CBLAS_DIAG Diag, INTT M, INTT N, T alpha, T *A, INTT lda, T *B, INTT ldb)
template<>
void cblas_trmm< double > (CBLAS_ORDER order, CBLAS_SIDE Side, CBLAS_UPLO Uplo, CBLAS_TRANSPOSE TransA, CBLAS_DIAG Diag, INTT M, INTT N, double alpha, double *A, INTT lda, double *B, INTT ldb)
template<>
void cblas_trmm< float > (CBLAS_ORDER order, CBLAS_SIDE Side, CBLAS_UPLO Uplo, CBLAS_TRANSPOSE TransA, CBLAS_DIAG Diag, INTT M, INTT N, float alpha, float *A, INTT lda, float *B, INTT ldb)
template<typename T >
void cblas_trmv (CBLAS_ORDER order, CBLAS_UPLO Uplo, CBLAS_TRANSPOSE TransA, CBLAS_DIAG Diag, INTT N, T *A, INTT lda, T *X, INTT incX)
template<>
void cblas_trmv< double > (CBLAS_ORDER order, CBLAS_UPLO Uplo, CBLAS_TRANSPOSE TransA, CBLAS_DIAG Diag, INTT N, double *A, INTT lda, double *X, INTT incX)
template<>
void cblas_trmv< float > (CBLAS_ORDER order, CBLAS_UPLO Uplo, CBLAS_TRANSPOSE TransA, CBLAS_DIAG Diag, INTT N, float *A, INTT lda, float *X, INTT incX)
double dasum_ (INTT *n, double *x, INTT *incX)
void daxpy_ (INTT *n, double *a, double *x, INTT *incX, double *y, INTT *incY)
void dcopy_ (INTT *n, double *x, INTT *incX, double *y, INTT *incY)
double ddot_ (INTT *n, double *x, INTT *incX, double *y, INTT *incY)
void dgemm_ (char *transa, char *transb, INTT *m, INTT *n, INTT *k, double *alpha, double *a, INTT *lda, double *b, INTT *ldb, double *beta, double *c, INTT *ldc)
void dgemv_ (char *trans, INTT *m, INTT *n, double *alpha, double *a, INTT *lda, double *x, INTT *incx, double *beta, double *y, INTT *incy)
void dger_ (INTT *m, INTT *n, double *alpha, double *x, INTT *incx, double *y, INTT *incy, double *a, INTT *lda)
void dgesvd_ (char *jobu, char *jobvt, INTT *m, INTT *n, double *a, INTT *lda, double *s, double *u, INTT *ldu, double *vt, INTT *ldvt, double *work, INTT *lwork, INTT *info)
void dlasrt_ (char *id, INTT *n, double *d, INTT *info)
double dnrm2_ (INTT *n, double *x, INTT *incX)
void dscal_ (INTT *n, double *a, double *x, INTT *incX)
void dsyev_ (char *jobz, char *uplo, INTT *n, double *a, INTT *lda, double *w, double *work, INTT *lwork, INTT *info)
void dsymv_ (char *uplo, INTT *n, double *alpha, double *a, INTT *lda, double *x, INTT *incx, double *beta, double *y, INTT *incy)
void dsyr_ (char *uplo, INTT *n, double *alpha, double *x, INTT *incx, double *a, INTT *lda)
void dsyrk_ (char *uplo, char *trans, INTT *n, INTT *k, double *alpha, double *a, INTT *lda, double *beta, double *c, INTT *ldc)
void dsytrf_ (char *uplo, INTT *n, double *a, INTT *lda, INTT *ipiv, double *work, INTT *lwork, INTT *info)
void dsytri_ (char *uplo, INTT *n, double *a, INTT *lda, INTT *ipiv, double *work, INTT *info)
void dtrmm_ (char *side, char *uplo, char *transa, char *diag, INTT *m, INTT *n, double *alpha, double *a, INTT *lda, double *b, INTT *ldb)
void dtrmv_ (char *uplo, char *trans, char *diag, INTT *n, double *a, INTT *lda, double *x, INTT *incx)
void dtrtri_ (char *uplo, char *diag, INTT *n, double *a, INTT *lda, INTT *info)
template<typename T >
void gesvd (char &jobu, char &jobvt, INTT m, INTT n, T *a, INTT lda, T *s, T *u, INTT ldu, T *vt, INTT ldvt)
template<>
void gesvd (char &jobu, char &jobvt, INTT m, INTT n, double *a, INTT lda, double *s, double *u, INTT ldu, double *vt, INTT ldvt)
template<>
void gesvd (char &jobu, char &jobvt, INTT m, INTT n, float *a, INTT lda, float *s, float *u, INTT ldu, float *vt, INTT ldvt)
INTT idamax_ (INTT *n, double *dx, INTT *incx)
INTT isamax_ (INTT *n, float *dx, INTT *incx)
template<typename T >
void lasrt (char &id, INTT n, T *d)
template<>
void lasrt (char &id, INTT n, double *d)
template<>
void lasrt (char &id, INTT n, float *d)
float sasum_ (INTT *n, float *x, INTT *incX)
void saxpy_ (INTT *n, float *a, float *x, INTT *incX, float *y, INTT *incY)
void scopy_ (INTT *n, float *x, INTT *incX, float *y, INTT *incY)
float sdot_ (INTT *n, float *x, INTT *incX, float *y, INTT *incY)
void sgemm_ (char *transa, char *transb, INTT *m, INTT *n, INTT *k, float *alpha, float *a, INTT *lda, float *b, INTT *ldb, float *beta, float *c, INTT *ldc)
void sgemv_ (char *trans, INTT *m, INTT *n, float *alpha, float *a, INTT *lda, float *x, INTT *incx, float *beta, float *y, INTT *incy)
void sger_ (INTT *m, INTT *n, float *alpha, float *x, INTT *incx, float *y, INTT *incy, float *a, INTT *lda)
void sgesvd_ (char *jobu, char *jobvt, INTT *m, INTT *n, float *a, INTT *lda, float *s, float *u, INTT *ldu, float *vt, INTT *ldvt, float *work, INTT *lwork, INTT *info)
void slasrt_ (char *id, INTT *n, float *d, INTT *info)
float snrm2_ (INTT *n, float *x, INTT *incX)
void sscal_ (INTT *n, float *a, float *x, INTT *incX)
void ssyev_ (char *jobz, char *uplo, INTT *n, float *a, INTT *lda, float *w, float *work, INTT *lwork, INTT *info)
void ssymv_ (char *uplo, INTT *n, float *alpha, float *a, INTT *lda, float *x, INTT *incx, float *beta, float *y, INTT *incy)
void ssyr_ (char *uplo, INTT *n, float *alpha, float *x, INTT *incx, float *a, INTT *lda)
void ssyrk_ (char *uplo, char *trans, INTT *n, INTT *k, float *alpha, float *a, INTT *lda, float *beta, float *c, INTT *ldc)
void ssytrf_ (char *uplo, INTT *n, float *a, INTT *lda, INTT *ipiv, float *work, INTT *lwork, INTT *info)
void ssytri_ (char *uplo, INTT *n, float *a, INTT *lda, INTT *ipiv, float *work, INTT *info)
void strmm_ (char *side, char *uplo, char *transa, char *diag, INTT *m, INTT *n, float *alpha, float *a, INTT *lda, float *b, INTT *ldb)
void strmv_ (char *uplo, char *trans, char *diag, INTT *n, float *a, INTT *lda, float *x, INTT *incx)
void strtri_ (char *uplo, char *diag, INTT *n, float *a, INTT *lda, INTT *info)
template<typename T >
void syev (char &jobz, char &uplo, INTT n, T *a, INTT lda, T *w)
template<>
void syev (char &jobz, char &uplo, INTT n, float *a, INTT lda, float *w)
template<>
void syev (char &jobz, char &uplo, INTT n, double *a, INTT lda, double *w)
template<typename T >
void sytri (char &uplo, INTT n, T *a, INTT lda)
template<>
void sytri< double > (char &uplo, INTT n, double *a, INTT lda)
template<>
void sytri< float > (char &uplo, INTT n, float *a, INTT lda)
template<typename T >
void trtri (char &uplo, char &diag, INTT n, T *a, INTT lda)
template<>
void trtri< double > (char &uplo, char &diag, INTT n, double *a, INTT lda)
template<>
void trtri< float > (char &uplo, char &diag, INTT n, float *a, INTT lda)
template<typename T >
void vAbs (int n, T *vecIn, T *vecOut)
template<typename T >
void vAdd (int n, T *vecIn, T *vecIn2, T *vecOut)
template<typename T >
void vDiv (int n, T *vecIn, T *vecIn2, T *vecOut)
template<typename T >
void vExp (int n, T *vecIn, T *vecOut)
template<typename T >
void vInv (int n, T *vecIn, T *vecOut)
template<typename T >
void vInvSqrt (int n, T *vecIn, T *vecOut)
template<typename T >
void vMul (int n, T *vecIn, T *vecIn2, T *vecOut)
template<typename T >
void vSqr (int n, T *vecIn, T *vecOut)
template<typename T >
void vSqrt (int n, T *vecIn, T *vecOut)
template<typename T >
void vSub (int n, T *vecIn, T *vecIn2, T *vecOut)
Variables
static char all ='A'
static char allV ='V'
static char decr ='D'
static char incr ='I'
static INTT info =0
static char low ='l'
static char lower ='L'
static char no ='N'
static char nonUnit ='n'
static char reduced ='S'
static char upper ='u'
Typedef Documentation
typedef int INTT
Definition at line 16 of file cblas_alt_template.h.
Function Documentation
template<typename T > T cblas_asum (INTT n, T * X, INTT incX)
INTTerface to cblas_*asum.
template<> double cblas_asum< double > (INTT n, double * X, INTT incX) inline
Implementation of the INTTerface for cblas_dasum.
Definition at line 396 of file cblas_alt_template.h.
References dasum_().
template<> float cblas_asum< float > (INTT n, float * X, INTT incX) inline
Implementation of the INTTerface for cblas_sasum.
Definition at line 401 of file cblas_alt_template.h.
References sasum_().
template<typename T > void cblas_axpy (INTT n, T a, T * X, INTT incX, T * Y, INTT incY)
INTTerface to cblas_*axpy.
template<> void cblas_axpy< bool > (INTT n, bool a, bool * X, INTT incX, bool * Y, INTT incY) inline
Implementation of the INTTerface for cblas_saxpy.
Definition at line 365 of file cblas_alt_template.h.
template<> void cblas_axpy< double > (INTT n, double a, double * X, INTT incX, double * Y, INTT incY) inline
Implementation of the INTTerface for cblas_daxpy.
Definition at line 345 of file cblas_alt_template.h.
References daxpy_().
template<> void cblas_axpy< float > (INTT n, float a, float * X, INTT incX, float * Y, INTT incY) inline
Implementation of the INTTerface for cblas_saxpy.
Definition at line 351 of file cblas_alt_template.h.
References saxpy_().
template<> void cblas_axpy< int > (INTT n, int a, int * X, INTT incX, int * Y, INTT incY) inline
Implementation of the INTTerface for cblas_saxpy.
Definition at line 358 of file cblas_alt_template.h.
template<typename T > void cblas_copy (INTT n, T * X, INTT incX, T * Y, INTT incY)
INTTerface to cblas_*copy.
template<> void cblas_copy< bool > (INTT n, bool * X, INTT incX, bool * Y, INTT incY) inline
Implementation of the INTTerface for cblas_scopy.
Definition at line 338 of file cblas_alt_template.h.
template<> void cblas_copy< double > (INTT n, double * X, INTT incX, double * Y, INTT incY) inline
Implementation of the INTTerface for cblas_dcopy.
Definition at line 320 of file cblas_alt_template.h.
References dcopy_().
template<> void cblas_copy< float > (INTT n, float * X, INTT incX, float * Y, INTT incY) inline
Implementation of the INTTerface for cblas_scopy.
Definition at line 326 of file cblas_alt_template.h.
References scopy_().
template<> void cblas_copy< int > (INTT n, int * X, INTT incX, int * Y, INTT incY) inline
Implementation of the INTTerface for cblas_scopy.
Definition at line 332 of file cblas_alt_template.h.
template<typename T > T cblas_dot (INTT n, T * X, INTT incX, T * Y, INTT incY)
INTTerface to cblas_*adot.
template<> bool cblas_dot< bool > (INTT n, bool * X, INTT incX, bool * Y, INTT incY) inline
Implementation of the INTTerface for cblas_sdot.
not implemented
Definition at line 430 of file cblas_alt_template.h.
template<> double cblas_dot< double > (INTT n, double * X, INTT incX, double * Y, INTT incY) inline
Implementation of the INTTerface for cblas_ddot.
Definition at line 406 of file cblas_alt_template.h.
References ddot_().
template<> float cblas_dot< float > (INTT n, float * X, INTT incX, float * Y, INTT incY) inline
Implementation of the INTTerface for cblas_sdot.
Definition at line 412 of file cblas_alt_template.h.
References sdot_().
template<> int cblas_dot< int > (INTT n, int * X, INTT incX, int * Y, INTT incY) inline
Definition at line 417 of file cblas_alt_template.h.
template<typename T > void cblas_gemm (CBLAS_ORDER order, CBLAS_TRANSPOSE TransA, CBLAS_TRANSPOSE TransB, INTT M, INTT N, INTT K, T alpha, T * A, INTT lda, T * B, INTT ldb, T beta, T * C, INTT ldc)
INTTerface to cblas_*gemm.
template<> void cblas_gemm< bool > (CBLAS_ORDER order, CBLAS_TRANSPOSE TransA, CBLAS_TRANSPOSE TransB, INTT M, INTT N, INTT K, bool alpha, bool * A, INTT lda, bool * B, INTT ldb, bool beta, bool * C, INTT ldc) inline
Implementation of the INTTerface for cblas_sgemm.
not implemented
Definition at line 561 of file cblas_alt_template.h.
template<> void cblas_gemm< double > (CBLAS_ORDER order, CBLAS_TRANSPOSE TransA, CBLAS_TRANSPOSE TransB, INTT M, INTT N, INTT K, double alpha, double * A, INTT lda, double * B, INTT ldb, double beta, double * C, INTT ldc) inline
Implementation of the INTTerface for cblas_dgemm.
Definition at line 536 of file cblas_alt_template.h.
References cblas_transpose(), and dgemm_().
template<> void cblas_gemm< float > (CBLAS_ORDER order, CBLAS_TRANSPOSE TransA, CBLAS_TRANSPOSE TransB, INTT M, INTT N, INTT K, float alpha, float * A, INTT lda, float * B, INTT ldb, float beta, float * C, INTT ldc) inline
Implementation of the INTTerface for cblas_sgemm.
Definition at line 545 of file cblas_alt_template.h.
References cblas_transpose(), and sgemm_().
template<> void cblas_gemm< int > (CBLAS_ORDER order, CBLAS_TRANSPOSE TransA, CBLAS_TRANSPOSE TransB, INTT M, INTT N, INTT K, int alpha, int * A, INTT lda, int * B, INTT ldb, int beta, int * C, INTT ldc) inline
not implemented
Definition at line 553 of file cblas_alt_template.h.
template<typename T > void cblas_gemv (CBLAS_ORDER order, CBLAS_TRANSPOSE TransA, INTT M, INTT N, T alpha, T * A, INTT lda, T * X, INTT incX, T beta, T * Y, INTT incY)
INTTerface to cblas_*gemv.
template<> void cblas_gemv< bool > (CBLAS_ORDER order, CBLAS_TRANSPOSE TransA, INTT M, INTT N, bool alpha, bool * A, INTT lda, bool * X, INTT incX, bool beta, bool * Y, INTT incY) inline
Implementation of the INTTerface for cblas_sgemv.
not implemented
Definition at line 464 of file cblas_alt_template.h.
template<> void cblas_gemv< double > (CBLAS_ORDER order, CBLAS_TRANSPOSE TransA, INTT M, INTT N, double alpha, double * A, INTT lda, double * X, INTT incX, double beta, double * Y, INTT incY) inline
Implementation of the INTTerface for cblas_dgemv.
Definition at line 438 of file cblas_alt_template.h.
References cblas_transpose(), and dgemv_().
template<> void cblas_gemv< float > (CBLAS_ORDER order, CBLAS_TRANSPOSE TransA, INTT M, INTT N, float alpha, float * A, INTT lda, float * X, INTT incX, float beta, float * Y, INTT incY) inline
Implementation of the INTTerface for cblas_sgemv.
Definition at line 447 of file cblas_alt_template.h.
References cblas_transpose(), and sgemv_().
template<> void cblas_gemv< int > (CBLAS_ORDER order, CBLAS_TRANSPOSE TransA, INTT M, INTT N, int alpha, int * A, INTT lda, int * X, INTT incX, int beta, int * Y, INTT incY) inline
Implementation of the INTTerface for cblas_sgemv.
not implemented
Definition at line 456 of file cblas_alt_template.h.
template<typename T > void cblas_ger (CBLAS_ORDER order, INTT M, INTT N, T alpha, T * X, INTT incX, T * Y, INTT incY, T * A, INTT lda)
INTTerface to cblas_*ger.
template<> void cblas_ger< double > (CBLAS_ORDER order, INTT M, INTT N, double alpha, double * X, INTT incX, double * Y, INTT incY, double * A, INTT lda) inline
Implementation of the INTTerface for cblas_dger.
Definition at line 473 of file cblas_alt_template.h.
References dger_().
template<> void cblas_ger< float > (CBLAS_ORDER order, INTT M, INTT N, float alpha, float * X, INTT incX, float * Y, INTT incY, float * A, INTT lda) inline
Implementation of the INTTerface for cblas_sger.
Definition at line 480 of file cblas_alt_template.h.
References sger_().
template<typename T > int cblas_iamax (INTT n, T * X, INTT incX)
interface to cblas_i*amax
template<> int cblas_iamax< double > (INTT n, double * X, INTT incX) inline
Implementation of the interface for cblas_idamax.
Definition at line 619 of file cblas_alt_template.h.
References idamax_().
template<> int cblas_iamax< float > (INTT n, float * X, INTT incX) inline
Implementation of the interface for cblas_isamax.
Definition at line 625 of file cblas_alt_template.h.
References isamax_().
template<typename T > int cblas_iamin (INTT n, T * X, INTT incX) inline
interface to cblas_i*amin
Slow implementation of cblas_idamin and cblas_isamin.
Definition at line 920 of file cblas_alt_template.h.
References utl::min().
vcl_size_t cblas_idamin (int n, double * X, int incX)
external functions
Referenced by utl::cblas_iamax< std::complex< float > >(), and syev().
vcl_size_t cblas_isamin (int n, float * X, int incX)
Referenced by utl::cblas_iamax< std::complex< float > >(), and syev().
template<typename T > T cblas_nrm2 (INTT n, T * X, INTT incX)
INTTerface to cblas_*nrm2.
template<> double cblas_nrm2< double > (INTT n, double * X, INTT incX) inline
Implementation of the INTTerface for cblas_dnrm2.
Definition at line 308 of file cblas_alt_template.h.
References dnrm2_().
template<> float cblas_nrm2< float > (INTT n, float * X, INTT incX) inline
Implementation of the INTTerface for cblas_snrm2.
Definition at line 314 of file cblas_alt_template.h.
References snrm2_().
template<typename T > void cblas_scal (INTT n, T a, T * X, INTT incX)
INTTerface to cblas_*scal.
template<> void cblas_scal< bool > (INTT n, bool a, bool * X, INTT incX) inline
Implementation of the INTTerface for cblas_sscal.
not implemented
Definition at line 390 of file cblas_alt_template.h.
template<> void cblas_scal< double > (INTT n, double a, double * X, INTT incX) inline
Implementation of the INTTerface for cblas_dscal.
Definition at line 373 of file cblas_alt_template.h.
References dscal_().
template<> void cblas_scal< float > (INTT n, float a, float * X, INTT incX) inline
Implementation of the INTTerface for cblas_sscal.
Definition at line 379 of file cblas_alt_template.h.
References sscal_().
template<> void cblas_scal< int > (INTT n, int a, int * X, INTT incX) inline
Implementation of the INTTerface for cblas_sscal.
Definition at line 385 of file cblas_alt_template.h.
template<typename T > void cblas_symv (CBLAS_ORDER order, CBLAS_UPLO Uplo, INTT N, T alpha, T * A, INTT lda, T * X, INTT incX, T beta, T * Y, INTT incY) inline
INTTerface to cblas_*symv.
template<> void cblas_symv (CBLAS_ORDER order, CBLAS_UPLO Uplo, INTT N, float alpha, float * A, INTT lda, float * X, INTT incX, float beta, float * Y, INTT incY) inline
Implementation of cblas_ssymv.
Definition at line 517 of file cblas_alt_template.h.
References cblas_uplo(), and ssymv_().
template<> void cblas_symv (CBLAS_ORDER order, CBLAS_UPLO Uplo, INTT N, double alpha, double * A, INTT lda, double * X, INTT incX, double beta, double * Y, INTT incY) inline
Implementation of cblas_dsymv.
Definition at line 525 of file cblas_alt_template.h.
References cblas_uplo(), and dsymv_().
template<typename T > void cblas_syr (CBLAS_ORDER order, CBLAS_UPLO Uplo, INTT N, T alpha, T * X, INTT incX, T * A, INTT lda) inline
INTTerface to cblas_*syr.
template<> void cblas_syr (CBLAS_ORDER order, CBLAS_UPLO Uplo, INTT N, double alpha, double * X, INTT incX, double * A, INTT lda) inline
Implementation of cblas_dsyr.
Definition at line 501 of file cblas_alt_template.h.
References cblas_uplo(), and dsyr_().
template<> void cblas_syr (CBLAS_ORDER order, CBLAS_UPLO Uplo, INTT N, float alpha, float * X, INTT incX, float * A, INTT lda) inline
Implementation of cblas_ssyr.
Definition at line 509 of file cblas_alt_template.h.
References cblas_uplo(), and ssyr_().
template<typename T > void cblas_syrk (CBLAS_ORDER order, CBLAS_UPLO Uplo, CBLAS_TRANSPOSE Trans, INTT N, INTT K, T alpha, T * A, INTT lda, T beta, T * C, INTT ldc)
INTTerface to cblas_*syrk.
template<> void cblas_syrk< bool > (CBLAS_ORDER order, CBLAS_UPLO Uplo, CBLAS_TRANSPOSE Trans, INTT N, INTT K, bool alpha, bool * A, INTT lda, bool beta, bool * C, INTT ldc) inline
Implementation of the INTTerface for cblas_ssyrk.
not implemented
Definition at line 593 of file cblas_alt_template.h.
template<> void cblas_syrk< double > (CBLAS_ORDER order, CBLAS_UPLO Uplo, CBLAS_TRANSPOSE Trans, INTT N, INTT K, double alpha, double * A, INTT lda, double beta, double * C, INTT ldc) inline
Implementation of the INTTerface for cblas_dsyrk.
Definition at line 570 of file cblas_alt_template.h.
References cblas_transpose(), cblas_uplo(), and dsyrk_().
template<> void cblas_syrk< float > (CBLAS_ORDER order, CBLAS_UPLO Uplo, CBLAS_TRANSPOSE Trans, INTT N, INTT K, float alpha, float * A, INTT lda, float beta, float * C, INTT ldc) inline
Implementation of the INTTerface for cblas_ssyrk.
Definition at line 578 of file cblas_alt_template.h.
References cblas_transpose(), cblas_uplo(), and ssyrk_().
template<> void cblas_syrk< int > (CBLAS_ORDER order, CBLAS_UPLO Uplo, CBLAS_TRANSPOSE Trans, INTT N, INTT K, int alpha, int * A, INTT lda, int beta, int * C, INTT ldc) inline
Implementation of the INTTerface for cblas_ssyrk.
not implemented
Definition at line 586 of file cblas_alt_template.h.
template<typename T > void cblas_trmm (CBLAS_ORDER order, CBLAS_SIDE Side, CBLAS_UPLO Uplo, CBLAS_TRANSPOSE TransA, CBLAS_DIAG Diag, INTT M, INTT N, T alpha, T * A, INTT lda, T * B, INTT ldb)
INTTerface to cblas_*trmm.
template<> void cblas_trmm< double > (CBLAS_ORDER order, CBLAS_SIDE Side, CBLAS_UPLO Uplo, CBLAS_TRANSPOSE TransA, CBLAS_DIAG Diag, INTT M, INTT N, double alpha, double * A, INTT lda, double * B, INTT ldb) inline
Implementation of the INTTerface for cblas_dtrmm.
Definition at line 601 of file cblas_alt_template.h.
References cblas_diag(), cblas_side(), cblas_transpose(), cblas_uplo(), and dtrmm_().
template<> void cblas_trmm< float > (CBLAS_ORDER order, CBLAS_SIDE Side, CBLAS_UPLO Uplo, CBLAS_TRANSPOSE TransA, CBLAS_DIAG Diag, INTT M, INTT N, float alpha, float * A, INTT lda, float * B, INTT ldb) inline
Implementation of the INTTerface for cblas_strmm.
Definition at line 610 of file cblas_alt_template.h.
References cblas_diag(), cblas_side(), cblas_transpose(), cblas_uplo(), and strmm_().
template<typename T > void cblas_trmv (CBLAS_ORDER order, CBLAS_UPLO Uplo, CBLAS_TRANSPOSE TransA, CBLAS_DIAG Diag, INTT N, T * A, INTT lda, T * X, INTT incX) inline
INTTerface to cblas_*trmv.
template<> void cblas_trmv< double > (CBLAS_ORDER order, CBLAS_UPLO Uplo, CBLAS_TRANSPOSE TransA, CBLAS_DIAG Diag, INTT N, double * A, INTT lda, double * X, INTT incX) inline
Implementation of the INTTerface for cblas_dtrmv.
Definition at line 487 of file cblas_alt_template.h.
References cblas_diag(), cblas_transpose(), cblas_uplo(), and dtrmv_().
template<> void cblas_trmv< float > (CBLAS_ORDER order, CBLAS_UPLO Uplo, CBLAS_TRANSPOSE TransA, CBLAS_DIAG Diag, INTT N, float * A, INTT lda, float * X, INTT incX) inline
Implementation of the INTTerface for cblas_strmv.
Definition at line 494 of file cblas_alt_template.h.
References cblas_diag(), cblas_transpose(), cblas_uplo(), and strmv_().
double dasum_ (INTT * n, double * x, INTT * incX)
Referenced by cblas_asum< double >().
void daxpy_ (INTT * n, double * a, double * x, INTT * incX, double * y, INTT * incY)
Referenced by cblas_axpy< double >().
void dcopy_ (INTT * n, double * x, INTT * incX, double * y, INTT * incY)
Referenced by cblas_copy< double >().
double ddot_ (INTT * n, double * x, INTT * incX, double * y, INTT * incY)
Referenced by cblas_dot< double >().
void dgemm_ (char * transa, char * transb, INTT * m, INTT * n, INTT * k, double * alpha, double * a, INTT * lda, double * b, INTT * ldb, double * beta, double * c, INTT * ldc)
Referenced by cblas_gemm< double >().
void dgemv_ (char * trans, INTT * m, INTT * n, double * alpha, double * a, INTT * lda, double * x, INTT * incx, double * beta, double * y, INTT * incy)
Referenced by cblas_gemv< double >().
void dger_ (INTT * m, INTT * n, double * alpha, double * x, INTT * incx, double * y, INTT * incy, double * a, INTT * lda)
Referenced by cblas_ger< double >().
void dgesvd_ (char * jobu, char * jobvt, INTT * m, INTT * n, double * a, INTT * lda, double * s, double * u, INTT * ldu, double * vt, INTT * ldvt, double * work, INTT * lwork, INTT * info)
Referenced by gesvd().
void dlasrt_ (char * id, INTT * n, double * d, INTT * info)
Referenced by lasrt().
double dnrm2_ (INTT * n, double * x, INTT * incX)
Referenced by cblas_nrm2< double >().
void dscal_ (INTT * n, double * a, double * x, INTT * incX)
Referenced by cblas_scal< double >().
void dsyev_ (char * jobz, char * uplo, INTT * n, double * a, INTT * lda, double * w, double * work, INTT * lwork, INTT * info)
Referenced by syev().
void dsymv_ (char * uplo, INTT * n, double * alpha, double * a, INTT * lda, double * x, INTT * incx, double * beta, double * y, INTT * incy)
Referenced by cblas_symv().
void dsyr_ (char * uplo, INTT * n, double * alpha, double * x, INTT * incx, double * a, INTT * lda)
Referenced by cblas_syr().
void dsyrk_ (char * uplo, char * trans, INTT * n, INTT * k, double * alpha, double * a, INTT * lda, double * beta, double * c, INTT * ldc)
Referenced by cblas_syrk< double >().
void dsytrf_ (char * uplo, INTT * n, double * a, INTT * lda, INTT * ipiv, double * work, INTT * lwork, INTT * info)
Referenced by sytri< double >().
void dsytri_ (char * uplo, INTT * n, double * a, INTT * lda, INTT * ipiv, double * work, INTT * info)
Referenced by sytri< double >().
void dtrmm_ (char * side, char * uplo, char * transa, char * diag, INTT * m, INTT * n, double * alpha, double * a, INTT * lda, double * b, INTT * ldb)
Referenced by cblas_trmm< double >().
void dtrmv_ (char * uplo, char * trans, char * diag, INTT * n, double * a, INTT * lda, double * x, INTT * incx)
Referenced by cblas_trmv< double >().
void dtrtri_ (char * uplo, char * diag, INTT * n, double * a, INTT * lda, INTT * info)
Referenced by trtri< double >().
template<typename T > void gesvd (char & jobu, char & jobvt, INTT m, INTT n, T * a, INTT lda, T * s, T * u, INTT ldu, T * vt, INTT ldvt)
template<> void gesvd (char & jobu, char & jobvt, INTT m, INTT n, double * a, INTT lda, double * s, double * u, INTT ldu, double * vt, INTT ldvt) inline
Definition at line 700 of file cblas_alt_template.h.
References dgesvd_(), and info.
template<> void gesvd (char & jobu, char & jobvt, INTT m, INTT n, float * a, INTT lda, float * s, float * u, INTT ldu, float * vt, INTT ldvt) inline
Definition at line 714 of file cblas_alt_template.h.
References info, and sgesvd_().
INTT idamax_ (INTT * n, double * dx, INTT * incx)
Referenced by cblas_iamax< double >().
INTT isamax_ (INTT * n, float * dx, INTT * incx)
Referenced by cblas_iamax< float >().
template<typename T > void lasrt (char & id, INTT n, T * d)
interaface to *lasrt
template<> void lasrt (char & id, INTT n, double * d) inline
interaface to *lasrt
Definition at line 682 of file cblas_alt_template.h.
References dlasrt_(), and info.
template<> void lasrt (char & id, INTT n, float * d) inline
interaface to *lasrt
Definition at line 687 of file cblas_alt_template.h.
References info, and slasrt_().
float sasum_ (INTT * n, float * x, INTT * incX)
Referenced by cblas_asum< float >().
void saxpy_ (INTT * n, float * a, float * x, INTT * incX, float * y, INTT * incY)
Referenced by cblas_axpy< float >().
void scopy_ (INTT * n, float * x, INTT * incX, float * y, INTT * incY)
Referenced by cblas_copy< float >().
float sdot_ (INTT * n, float * x, INTT * incX, float * y, INTT * incY)
Referenced by cblas_dot< float >().
void sgemm_ (char * transa, char * transb, INTT * m, INTT * n, INTT * k, float * alpha, float * a, INTT * lda, float * b, INTT * ldb, float * beta, float * c, INTT * ldc)
Referenced by cblas_gemm< float >().
void sgemv_ (char * trans, INTT * m, INTT * n, float * alpha, float * a, INTT * lda, float * x, INTT * incx, float * beta, float * y, INTT * incy)
Referenced by cblas_gemv< float >().
void sger_ (INTT * m, INTT * n, float * alpha, float * x, INTT * incx, float * y, INTT * incy, float * a, INTT * lda)
Referenced by cblas_ger< float >().
void sgesvd_ (char * jobu, char * jobvt, INTT * m, INTT * n, float * a, INTT * lda, float * s, float * u, INTT * ldu, float * vt, INTT * ldvt, float * work, INTT * lwork, INTT * info)
Referenced by gesvd().
void slasrt_ (char * id, INTT * n, float * d, INTT * info)
Referenced by lasrt().
float snrm2_ (INTT * n, float * x, INTT * incX)
Referenced by cblas_nrm2< float >().
void sscal_ (INTT * n, float * a, float * x, INTT * incX)
Referenced by cblas_scal< float >().
void ssyev_ (char * jobz, char * uplo, INTT * n, float * a, INTT * lda, float * w, float * work, INTT * lwork, INTT * info)
Referenced by syev().
void ssymv_ (char * uplo, INTT * n, float * alpha, float * a, INTT * lda, float * x, INTT * incx, float * beta, float * y, INTT * incy)
Referenced by cblas_symv().
void ssyr_ (char * uplo, INTT * n, float * alpha, float * x, INTT * incx, float * a, INTT * lda)
Referenced by cblas_syr().
void ssyrk_ (char * uplo, char * trans, INTT * n, INTT * k, float * alpha, float * a, INTT * lda, float * beta, float * c, INTT * ldc)
Referenced by cblas_syrk< float >().
void ssytrf_ (char * uplo, INTT * n, float * a, INTT * lda, INTT * ipiv, float * work, INTT * lwork, INTT * info)
Referenced by sytri< float >().
void ssytri_ (char * uplo, INTT * n, float * a, INTT * lda, INTT * ipiv, float * work, INTT * info)
Referenced by sytri< float >().
void strmm_ (char * side, char * uplo, char * transa, char * diag, INTT * m, INTT * n, float * alpha, float * a, INTT * lda, float * b, INTT * ldb)
Referenced by cblas_trmm< float >().
void strmv_ (char * uplo, char * trans, char * diag, INTT * n, float * a, INTT * lda, float * x, INTT * incx)
Referenced by cblas_trmv< float >().
void strtri_ (char * uplo, char * diag, INTT * n, float * a, INTT * lda, INTT * info)
Referenced by trtri< float >().
template<typename T > void syev (char & jobz, char & uplo, INTT n, T * a, INTT lda, T * w)
template<> void syev (char & jobz, char & uplo, INTT n, float * a, INTT lda, float * w) inline
Definition at line 729 of file cblas_alt_template.h.
References info, and ssyev_().
template<> void syev (char & jobz, char & uplo, INTT n, double * a, INTT lda, double * w) inline
Definition at line 741 of file cblas_alt_template.h.
References cblas_idamin(), cblas_isamin(), dsyev_(), info, vAbs(), and vSqr().
template<typename T > void sytri (char & uplo, INTT n, T * a, INTT lda)
interface to *sytri // call sytrf
template<> void sytri< double > (char & uplo, INTT n, double * a, INTT lda) inline
Implemenation of the interface for dsytri.
Definition at line 646 of file cblas_alt_template.h.
References dsytrf_(), dsytri_(), and info.
template<> void sytri< float > (char & uplo, INTT n, float * a, INTT lda) inline
Implemenation of the interface for ssytri.
Definition at line 665 of file cblas_alt_template.h.
References info, ssytrf_(), and ssytri_().
template<typename T > void trtri (char & uplo, char & diag, INTT n, T * a, INTT lda)
interface to *trtri
template<> void trtri< double > (char & uplo, char & diag, INTT n, double * a, INTT lda) inline
Implemenation of the interface for dtrtri.
Definition at line 633 of file cblas_alt_template.h.
References dtrtri_(), and info.
template<> void trtri< float > (char & uplo, char & diag, INTT n, float * a, INTT lda) inline
Implemenation of the interface for strtri.
Definition at line 639 of file cblas_alt_template.h.
References info, and strtri_().
template<typename T > void vAbs (int n, T * vecIn, T * vecOut) inline
interface to v*Abs
Slow implementation of vAbs.
Definition at line 914 of file cblas_alt_template.h.
Referenced by syev().
template<typename T > void vAdd (int n, T * vecIn, T * vecIn2, T * vecOut) inline
interface to v*Add
Slow implementation of vdAdd and vsAdd.
Definition at line 899 of file cblas_alt_template.h.
template<typename T > void vDiv (int n, T * vecIn, T * vecIn2, T * vecOut) inline
interface to v*Div
Slow implementation of vdDiv and vsDiv.
Definition at line 909 of file cblas_alt_template.h.
template<typename T > void vExp (int n, T * vecIn, T * vecOut) inline
interface to v*Exp
Slow implementation of vdExp and vsExp.
Definition at line 895 of file cblas_alt_template.h.
template<typename T > void vInv (int n, T * vecIn, T * vecOut) inline
interface to v*Inv
Slow implementation of vdInv and vsInv.
Definition at line 891 of file cblas_alt_template.h.
template<typename T > void vInvSqrt (int n, T * vecIn, T * vecOut) inline
interface to v*Sqr
Definition at line 881 of file cblas_alt_template.h.
template<typename T > void vMul (int n, T * vecIn, T * vecIn2, T * vecOut) inline
interface to v*Mul
Slow implementation of vdMul and vsMul.
Definition at line 904 of file cblas_alt_template.h.
template<typename T > void vSqr (int n, T * vecIn, T * vecOut) inline
interface to v*Sqr
If the MKL is not present, a slow implementation is used instead.
Slow implementation of vdSqr and vsSqr
Definition at line 875 of file cblas_alt_template.h.
Referenced by syev().
template<typename T > void vSqrt (int n, T * vecIn, T * vecOut) inline
interface to v*Sqr
Definition at line 878 of file cblas_alt_template.h.
template<typename T > void vSub (int n, T * vecIn, T * vecIn2, T * vecOut) inline
interface to v*Sub
Slow implementation of vdSub and vsSub.
Definition at line 886 of file cblas_alt_template.h.
Variable Documentation
char all ='A' static
Definition at line 27 of file cblas_alt_template.h.
char allV ='V' static
Definition at line 30 of file cblas_alt_template.h.
Referenced by spams::Matrix< T >::svd().
char decr ='D' static
Definition at line 26 of file cblas_alt_template.h.
Referenced by spams::Vector< T >::sort().
char incr ='I' static
Definition at line 25 of file cblas_alt_template.h.
Referenced by spams::Vector< T >::sort().
INTT info =0 static
Definition at line 24 of file cblas_alt_template.h.
Referenced by gesvd(), lasrt(), syev(), sytri< double >(), sytri< float >(), trtri< double >(), and trtri< float >().
char low ='l' static
a few static variables for lapack
Definition at line 20 of file cblas_alt_template.h.
Referenced by spams::downDateLasso().
char lower ='L' static
Definition at line 21 of file cblas_alt_template.h.
Referenced by spams::Matrix< T >::singularValues(), and spams::Matrix< T >::svd().
char no ='N' static
Definition at line 28 of file cblas_alt_template.h.
Referenced by spams::Matrix< T >::singularValues().
char nonUnit ='n' static
Definition at line 22 of file cblas_alt_template.h.
Referenced by spams::downDateLasso().
char reduced ='S' static
Definition at line 29 of file cblas_alt_template.h.
Referenced by spams::Matrix< T >::svd().
char upper ='u' static
Definition at line 23 of file cblas_alt_template.h.
Referenced by spams::Matrix< T >::invSym().