DMRITool: ThirdParty/Spams/include/cblas_defvar.h File Reference
cblas_defvar.h File Reference
#include <stddef.h>
Macros
#define CBLAS_ENUM_DEFINED_H
#define CBLAS_INDEX size_t /* this may vary between platforms */
Enumerations
enum CBLAS_DIAG {
CblasNonUnit =131,
CblasUnit =132,
CblasNonUnit =131,
CblasUnit =132
}
enum CBLAS_ORDER {
CblasRowMajor =101,
CblasColMajor =102,
CblasRowMajor =101,
CblasColMajor =102
}
enum CBLAS_SIDE {
CblasLeft =141,
CblasRight =142,
CblasLeft =141,
CblasRight =142
}
enum CBLAS_TRANSPOSE {
CblasNoTrans =111,
CblasTrans =112,
CblasConjTrans =113,
AtlasConj =114,
CblasNoTrans =111,
CblasTrans =112,
CblasConjTrans =113,
AtlasConj =114
}
enum CBLAS_UPLO {
CblasUpper =121,
CblasLower =122,
CblasUpper =121,
CblasLower =122
}
Functions
char * cblas_diag (CBLAS_DIAG Diag)
char * cblas_side (CBLAS_SIDE Side)
char * cblas_transpose (CBLAS_TRANSPOSE TransA)
char * cblas_uplo (CBLAS_UPLO Uplo)
Variables
static char CBLAS_DIAG_CHAR [] = {'N', 'U'}
static char CBLAS_SIDE_CHAR [] = {'L', 'R'}
static char CBLAS_TRANSPOSE_CHAR [] = {'N', 'T', 'C', 'N'}
static char CBLAS_UPLO_CHAR [] = {'U', 'L'}
Macro Definition Documentation
#define CBLAS_ENUM_DEFINED_H
Definition at line 10 of file cblas_defvar.h.
#define CBLAS_INDEX size_t /* this may vary between platforms */
Definition at line 9 of file cblas_defvar.h.
Enumeration Type Documentation
enum CBLAS_DIAG
Enumerator
CblasNonUnit
CblasUnit
CblasNonUnit
CblasUnit
Definition at line 15 of file cblas_defvar.h.
enum CBLAS_ORDER
Enumerator
CblasRowMajor
CblasColMajor
CblasRowMajor
CblasColMajor
Definition at line 12 of file cblas_defvar.h.
enum CBLAS_SIDE
Enumerator
CblasLeft
CblasRight
CblasLeft
CblasRight
Definition at line 16 of file cblas_defvar.h.
enum CBLAS_TRANSPOSE
Enumerator
CblasNoTrans
CblasTrans
CblasConjTrans
AtlasConj
CblasNoTrans
CblasTrans
CblasConjTrans
AtlasConj
Definition at line 13 of file cblas_defvar.h.
enum CBLAS_UPLO
Enumerator
CblasUpper
CblasLower
CblasUpper
CblasLower
Definition at line 14 of file cblas_defvar.h.
Function Documentation
char* cblas_diag (CBLAS_DIAG Diag) inline
Definition at line 48 of file cblas_defvar.h.
References CBLAS_DIAG_CHAR.
Referenced by cblas_trmm< double >(), cblas_trmm< float >(), cblas_trmv< double >(), and cblas_trmv< float >().
char* cblas_side (CBLAS_SIDE Side) inline
Definition at line 59 of file cblas_defvar.h.
References CBLAS_SIDE_CHAR.
Referenced by cblas_trmm< double >(), and cblas_trmm< float >().
char* cblas_transpose (CBLAS_TRANSPOSE TransA) inline
Definition at line 22 of file cblas_defvar.h.
References CBLAS_TRANSPOSE_CHAR.
Referenced by cblas_gemm< double >(), cblas_gemm< float >(), cblas_gemv< double >(), cblas_gemv< float >(), cblas_syrk< double >(), cblas_syrk< float >(), cblas_trmm< double >(), cblas_trmm< float >(), cblas_trmv< double >(), and cblas_trmv< float >().
char* cblas_uplo (CBLAS_UPLO Uplo) inline
Definition at line 37 of file cblas_defvar.h.
References CBLAS_UPLO_CHAR.
Referenced by cblas_symv(), cblas_syr(), cblas_syrk< double >(), cblas_syrk< float >(), cblas_trmm< double >(), cblas_trmm< float >(), cblas_trmv< double >(), and cblas_trmv< float >().
Variable Documentation
char CBLAS_DIAG_CHAR[] = {'N', 'U'} static
Definition at line 47 of file cblas_defvar.h.
Referenced by cblas_diag().
char CBLAS_SIDE_CHAR[] = {'L', 'R'} static
Definition at line 58 of file cblas_defvar.h.
Referenced by cblas_side().
char CBLAS_TRANSPOSE_CHAR[] = {'N', 'T', 'C', 'N'} static
Definition at line 21 of file cblas_defvar.h.
Referenced by cblas_transpose().
char CBLAS_UPLO_CHAR[] = {'U', 'L'} static
Definition at line 36 of file cblas_defvar.h.
Referenced by cblas_uplo().