DMRITool: itk::VariableLengthVectorImageFileWriter< TInputImage > Class Template Reference
itk::VariableLengthVectorImageFileWriter< TInputImage > Class Template Reference
#include <itkVariableLengthVectorImageFileWriter.h>
Detailed Description
template<class TInputImage>
class itk::VariableLengthVectorImageFileWriter< TInputImage >
Writes variable length vector image data. std::vector is used to store the variable length vector.
Definition at line 31 of file itkVariableLengthVectorImageFileWriter.h.
Public Types
typedef SmartPointer< const Self > ConstPointer
typedef InputImageType::DirectionType InputImageDirectionType
typedef InputImageType::PixelContainer::Pointer InputImagePixelContainerPointerType
typedef InputImageType::PixelContainer InputImagePixelContainerType
typedef InputImageType::PixelType InputImagePixelType
typedef InputImageType::Pointer InputImagePointer
typedef InputImageType::PointType InputImagePointType
typedef InputImageType::RegionType InputImageRegionType
typedef InputImageType::SizeType InputImageSizeType
typedef InputImageType::SpacingType InputImageSpacingType
typedef TInputImage InputImageType
typedef InputImageType::ValueType InputImageValueType
typedef SmartPointer< Self > Pointer
typedef VariableLengthVectorImageFileWriter Self
typedef ProcessObject Superclass
Public Member Functions
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual const char * GetFileName () const
const InputImageType * GetInput (void)
const InputImageType * GetInput (unsigned int idx)
virtual const char * GetNameOfClass () const
virtual const bool & GetUseCompression ()
virtual void SetFileName (const char *_arg)
void SetInput (const InputImageType *input)
virtual void SetUseCompression (bool _arg)
virtual void Update ()
virtual void UseCompressionOff ()
virtual void UseCompressionOn ()
virtual void Write (void)
Static Public Member Functions
static Pointer New ()
Static Public Attributes
static const unsigned int ImageDimension = TInputImage::ImageDimension
Protected Types
typedef itk::ImageFileWriter< LengthImageType > LengthImageFileWriterType
typedef LengthImageType::Pointer LengthImagePointer
typedef Image< LengthType, ImageDimension > LengthImageType
typedef unsigned int LengthType
typedef itk::ImageFileWriter< ValueImageType > ValueImageFileWriterType
typedef ValueImageType::Pointer ValueImagePointer
typedef Image< typename InputImagePixelType::ValueType, 1 > ValueImageType
Protected Member Functions
void GenerateData (void)
void PrintSelf (std::ostream &os, Indent indent) const
VariableLengthVectorImageFileWriter ()
~VariableLengthVectorImageFileWriter ()
Protected Attributes
LengthImagePointer m_LengthImage
LengthImageFileWriterType::Pointer m_LengthImageFileWriter
ValueImagePointer m_ValueImage
ValueImageFileWriterType::Pointer m_ValueImageFileWriter
Private Member Functions
void operator= (const Self &)
VariableLengthVectorImageFileWriter (const Self &)
Private Attributes
std::string m_FileName
bool m_UseCompression
Member Typedef Documentation
template<class TInputImage> typedef SmartPointer<const Self> itk::VariableLengthVectorImageFileWriter< TInputImage >::ConstPointer
Definition at line 38 of file itkVariableLengthVectorImageFileWriter.h.
template<class TInputImage> typedef InputImageType::DirectionType itk::VariableLengthVectorImageFileWriter< TInputImage >::InputImageDirectionType
Definition at line 56 of file itkVariableLengthVectorImageFileWriter.h.
template<class TInputImage> typedef InputImageType::PixelContainer::Pointer itk::VariableLengthVectorImageFileWriter< TInputImage >::InputImagePixelContainerPointerType
Definition at line 60 of file itkVariableLengthVectorImageFileWriter.h.
template<class TInputImage> typedef InputImageType::PixelContainer itk::VariableLengthVectorImageFileWriter< TInputImage >::InputImagePixelContainerType
Definition at line 59 of file itkVariableLengthVectorImageFileWriter.h.
template<class TInputImage> typedef InputImageType::PixelType itk::VariableLengthVectorImageFileWriter< TInputImage >::InputImagePixelType
Definition at line 57 of file itkVariableLengthVectorImageFileWriter.h.
template<class TInputImage> typedef InputImageType::Pointer itk::VariableLengthVectorImageFileWriter< TInputImage >::InputImagePointer
Definition at line 51 of file itkVariableLengthVectorImageFileWriter.h.
template<class TInputImage> typedef InputImageType::PointType itk::VariableLengthVectorImageFileWriter< TInputImage >::InputImagePointType
Definition at line 55 of file itkVariableLengthVectorImageFileWriter.h.
template<class TInputImage> typedef InputImageType::RegionType itk::VariableLengthVectorImageFileWriter< TInputImage >::InputImageRegionType
Definition at line 52 of file itkVariableLengthVectorImageFileWriter.h.
template<class TInputImage> typedef InputImageType::SizeType itk::VariableLengthVectorImageFileWriter< TInputImage >::InputImageSizeType
Definition at line 53 of file itkVariableLengthVectorImageFileWriter.h.
template<class TInputImage> typedef InputImageType::SpacingType itk::VariableLengthVectorImageFileWriter< TInputImage >::InputImageSpacingType
Definition at line 54 of file itkVariableLengthVectorImageFileWriter.h.
template<class TInputImage> typedef TInputImage itk::VariableLengthVectorImageFileWriter< TInputImage >::InputImageType
Some convenient typedefs.
Definition at line 50 of file itkVariableLengthVectorImageFileWriter.h.
template<class TInputImage> typedef InputImageType::ValueType itk::VariableLengthVectorImageFileWriter< TInputImage >::InputImageValueType
Definition at line 58 of file itkVariableLengthVectorImageFileWriter.h.
template<class TInputImage> typedef itk::ImageFileWriter<LengthImageType> itk::VariableLengthVectorImageFileWriter< TInputImage >::LengthImageFileWriterType protected
Definition at line 120 of file itkVariableLengthVectorImageFileWriter.h.
template<class TInputImage> typedef LengthImageType::Pointer itk::VariableLengthVectorImageFileWriter< TInputImage >::LengthImagePointer protected
Definition at line 114 of file itkVariableLengthVectorImageFileWriter.h.
template<class TInputImage> typedef Image<LengthType, ImageDimension> itk::VariableLengthVectorImageFileWriter< TInputImage >::LengthImageType protected
Definition at line 112 of file itkVariableLengthVectorImageFileWriter.h.
template<class TInputImage> typedef unsigned int itk::VariableLengthVectorImageFileWriter< TInputImage >::LengthType protected
Definition at line 111 of file itkVariableLengthVectorImageFileWriter.h.
template<class TInputImage> typedef SmartPointer<Self> itk::VariableLengthVectorImageFileWriter< TInputImage >::Pointer
Definition at line 37 of file itkVariableLengthVectorImageFileWriter.h.
template<class TInputImage> typedef VariableLengthVectorImageFileWriter itk::VariableLengthVectorImageFileWriter< TInputImage >::Self
Standard class typedefs.
Definition at line 35 of file itkVariableLengthVectorImageFileWriter.h.
template<class TInputImage> typedef ProcessObject itk::VariableLengthVectorImageFileWriter< TInputImage >::Superclass
Definition at line 36 of file itkVariableLengthVectorImageFileWriter.h.
template<class TInputImage> typedef itk::ImageFileWriter<ValueImageType> itk::VariableLengthVectorImageFileWriter< TInputImage >::ValueImageFileWriterType protected
Definition at line 121 of file itkVariableLengthVectorImageFileWriter.h.
template<class TInputImage> typedef ValueImageType::Pointer itk::VariableLengthVectorImageFileWriter< TInputImage >::ValueImagePointer protected
Definition at line 115 of file itkVariableLengthVectorImageFileWriter.h.
template<class TInputImage> typedef Image<typename InputImagePixelType::ValueType, 1> itk::VariableLengthVectorImageFileWriter< TInputImage >::ValueImageType protected
Definition at line 113 of file itkVariableLengthVectorImageFileWriter.h.
Constructor & Destructor Documentation
template<class TInputImage > itk::VariableLengthVectorImageFileWriter< TInputImage >::VariableLengthVectorImageFileWriter () protected
By default the MetaDataDictionary is taken from the input image and passed to the ImageIO. In some cases, however, a user may prefer to introduce her/his own MetaDataDictionary. This is often the case of the ImageSeriesWriter. This flag defined whether the MetaDataDictionary to use will be the one from the input image or the one already set in the ImageIO object.
Definition at line 30 of file itkVariableLengthVectorImageFileWriter.hxx.
References itk::VariableLengthVectorImageFileWriter< TInputImage >::~VariableLengthVectorImageFileWriter().
template<class TInputImage > itk::VariableLengthVectorImageFileWriter< TInputImage >::~VariableLengthVectorImageFileWriter () protected
Definition at line 40 of file itkVariableLengthVectorImageFileWriter.hxx.
References itk::VariableLengthVectorImageFileWriter< TInputImage >::SetInput().
Referenced by itk::VariableLengthVectorImageFileWriter< TInputImage >::VariableLengthVectorImageFileWriter().
template<class TInputImage> itk::VariableLengthVectorImageFileWriter< TInputImage >::VariableLengthVectorImageFileWriter (const Self &) private
Member Function Documentation
template<class TInputImage> virtual::itk::LightObject::Pointer itk::VariableLengthVectorImageFileWriter< TInputImage >::CreateAnother (void) const
template<class TInputImage > void itk::VariableLengthVectorImageFileWriter< TInputImage >::GenerateData (void) protected
Does the actual work.
Definition at line 110 of file itkVariableLengthVectorImageFileWriter.hxx.
References itk::VariableLengthVectorImageFileWriter< TInputImage >::PrintSelf().
Referenced by itk::VariableLengthVectorImageFileWriter< TInputImage >::Write().
template<class TInputImage> virtual const char* itk::VariableLengthVectorImageFileWriter< TInputImage >::GetFileName () const virtual
template<class TInputImage > const VariableLengthVectorImageFileWriter< TInputImage >::InputImageType * itk::VariableLengthVectorImageFileWriter< TInputImage >::GetInput (void)
Definition at line 60 of file itkVariableLengthVectorImageFileWriter.hxx.
Referenced by itk::VariableLengthVectorImageFileWriter< TInputImage >::SetInput().
template<class TInputImage > const VariableLengthVectorImageFileWriter< TInputImage >::InputImageType * itk::VariableLengthVectorImageFileWriter< TInputImage >::GetInput (unsigned int idx)
Definition at line 75 of file itkVariableLengthVectorImageFileWriter.hxx.
References itk::VariableLengthVectorImageFileWriter< TInputImage >::Write().
template<class TInputImage> virtual const char* itk::VariableLengthVectorImageFileWriter< TInputImage >::GetNameOfClass () const virtual
Run-time type information (and related methods).
template<class TInputImage> virtual const bool& itk::VariableLengthVectorImageFileWriter< TInputImage >::GetUseCompression () virtual
template<class TInputImage> static Pointer itk::VariableLengthVectorImageFileWriter< TInputImage >::New () static
Method for creation through the object factory.
template<class TInputImage> void itk::VariableLengthVectorImageFileWriter< TInputImage >::operator= (const Self &) private
template<class TInputImage > void itk::VariableLengthVectorImageFileWriter< TInputImage >::PrintSelf (std::ostream & os, Indent indent) const protected
Definition at line 293 of file itkVariableLengthVectorImageFileWriter.hxx.
Referenced by itk::VariableLengthVectorImageFileWriter< TInputImage >::GenerateData().
template<class TInputImage> virtual void itk::VariableLengthVectorImageFileWriter< TInputImage >::SetFileName (const char * _arg) virtual
Specify the names of the output files to write.
template<class TInputImage > void itk::VariableLengthVectorImageFileWriter< TInputImage >::SetInput (const InputImageType * input)
Definition at line 48 of file itkVariableLengthVectorImageFileWriter.hxx.
References itk::VariableLengthVectorImageFileWriter< TInputImage >::GetInput().
Referenced by itk::VariableLengthVectorImageFileWriter< TInputImage >::~VariableLengthVectorImageFileWriter().
template<class TInputImage> virtual void itk::VariableLengthVectorImageFileWriter< TInputImage >::SetUseCompression (bool _arg) virtual
Set the compression On or Off
template<class TInputImage> virtual void itk::VariableLengthVectorImageFileWriter< TInputImage >::Update () inline virtual
Aliased to the Write() method to be consistent with the rest of the pipeline.
Definition at line 85 of file itkVariableLengthVectorImageFileWriter.h.
template<class TInputImage> virtual void itk::VariableLengthVectorImageFileWriter< TInputImage >::UseCompressionOff () virtual
template<class TInputImage> virtual void itk::VariableLengthVectorImageFileWriter< TInputImage >::UseCompressionOn () virtual
template<class TInputImage > void itk::VariableLengthVectorImageFileWriter< TInputImage >::Write (void) virtual
A special version of the Update() method for writers. It invokes start and end events and handles releasing data. It eventually calls GenerateData() which does the actual writing. Note: the write method will write data specified by the IORegion. If not set, then then the whole image is written. Note that the region will be cropped to fit the input image's LargestPossibleRegion.
Definition at line 84 of file itkVariableLengthVectorImageFileWriter.hxx.
References itk::VariableLengthVectorImageFileWriter< TInputImage >::GenerateData().
Referenced by itk::VariableLengthVectorImageFileWriter< TInputImage >::GetInput().
Member Data Documentation
template<class TInputImage> const unsigned int itk::VariableLengthVectorImageFileWriter< TInputImage >::ImageDimension = TInputImage::ImageDimension static
The dimensionality of the input and output images.
Definition at line 47 of file itkVariableLengthVectorImageFileWriter.h.
template<class TInputImage> std::string itk::VariableLengthVectorImageFileWriter< TInputImage >::m_FileName private
Definition at line 134 of file itkVariableLengthVectorImageFileWriter.h.
template<class TInputImage> LengthImagePointer itk::VariableLengthVectorImageFileWriter< TInputImage >::m_LengthImage protected
Definition at line 117 of file itkVariableLengthVectorImageFileWriter.h.
template<class TInputImage> LengthImageFileWriterType::Pointer itk::VariableLengthVectorImageFileWriter< TInputImage >::m_LengthImageFileWriter protected
Definition at line 123 of file itkVariableLengthVectorImageFileWriter.h.
template<class TInputImage> bool itk::VariableLengthVectorImageFileWriter< TInputImage >::m_UseCompression private
Definition at line 136 of file itkVariableLengthVectorImageFileWriter.h.
template<class TInputImage> ValueImagePointer itk::VariableLengthVectorImageFileWriter< TInputImage >::m_ValueImage protected
Definition at line 118 of file itkVariableLengthVectorImageFileWriter.h.
template<class TInputImage> ValueImageFileWriterType::Pointer itk::VariableLengthVectorImageFileWriter< TInputImage >::m_ValueImageFileWriter protected
Definition at line 124 of file itkVariableLengthVectorImageFileWriter.h.
The documentation for this class was generated from the following files:
ThirdParty/VariableLengthVectorImage/include/itkVariableLengthVectorImageFileWriter.h
ThirdParty/VariableLengthVectorImage/include/itkVariableLengthVectorImageFileWriter.hxx