DMRITool: itk::DWISingleVoxelGenerator< TOutputImage, TScalarImage > Class Template Reference
itk::DWISingleVoxelGenerator< TOutputImage, TScalarImage > Class Template Reference
DWIProcessing
#include <itkDWISingleVoxelGenerator.h>
Detailed Description
template<class TOutputImage, class TScalarImage = Image<float,3>>
class itk::DWISingleVoxelGenerator< TOutputImage, TScalarImage >
Generate DWI data with the same diffusion parameter set for all voxels. If random mode is used, the diffusion parameters are randomly rotated.
Author
Jian Cheng (jian..nosp@m.chen.nosp@m.g.198.nosp@m.3@gm.nosp@m.ail.c.nosp@m.om)
Definition at line 35 of file itkDWISingleVoxelGenerator.h.
Public Types
typedef Superclass::DiffusionParameterContainerType DiffusionParameterContainerType
typedef Superclass::DiffusionParameterValuesType DiffusionParameterValuesType
typedef Superclass::MatrixPointer MatrixPointer
typedef Superclass::MatrixType MatrixType
typedef Superclass::OutputImageDirectionType OutputImageDirectionType
typedef Superclass::OutputImageIndexType OutputImageIndexType
typedef Superclass::OutputImageInternalPixelType OutputImageInternalPixelType
typedef Superclass::OutputImagePixelType OutputImagePixelType
typedef Superclass::OutputImagePointer OutputImagePointer
typedef Superclass::OutputImagePointType OutputImagePointType
typedef Superclass::OutputImageRegionType OutputImageRegionType
typedef Superclass::OutputImageSizeType OutputImageSizeType
typedef Superclass::OutputImageSpacingType OutputImageSpacingType
typedef Superclass::OutputImageType OutputImageType
typedef SmartPointer< Self > Pointer
typedef Superclass::PrecisionType PrecisionType
enum RandomType {
FIXED =0,
UNIFORM
}
typedef Superclass::ScalarImagePointer ScalarImagePointer
typedef Superclass::ScalarImageType ScalarImageType
typedef DWISingleVoxelGenerator Self
typedef Superclass::STDVectorPointer STDVectorPointer
typedef Superclass::STDVectorType STDVectorType
typedef DWIGeneratorBase< TOutputImage, TScalarImage > Superclass
Public Types inherited from itk::DWIGeneratorBase< TOutputImage, TScalarImage >
typedef CylinderModelType::Pointer CylinderModelPointer
typedef CylinderModelGenerator< double > CylinderModelType
typedef std::vector< DiffusionParameterValuesType > DiffusionParameterContainerType
typedef std::vector< double > DiffusionParameterValuesType
typedef utl_shared_ptr< MatrixType > MatrixPointer
typedef utl::NDArray< PrecisionType, 2 > MatrixType
enum ModelType {
SYMMETRICAL_TENSOR_IN_CARTESIAN_COORDS =0,
SYMMETRICAL_TENSOR_IN_SPHERICAL_COORDS,
TENSOR_IN_EULER_ANGLES,
CYLINDER_SPHERICAL_MODEL
}
typedef OutputImageType::DirectionType OutputImageDirectionType
typedef OutputImageType::IndexType OutputImageIndexType
typedef OutputImageType::InternalPixelType OutputImageInternalPixelType
typedef OutputImageType::PixelType OutputImagePixelType
typedef OutputImageType::Pointer OutputImagePointer
typedef OutputImageType::PointType OutputImagePointType
typedef OutputImageType::RegionType OutputImageRegionType
typedef OutputImageType::SizeType OutputImageSizeType
typedef OutputImageType::SpacingType OutputImageSpacingType
typedef TOutputImage OutputImageType
typedef SmartPointer< Self > Pointer
typedef double PrecisionType
typedef SamplingSchemeQSpaceType::Pointer SamplingSchemeQSpacePointer
typedef SamplingSchemeQSpace< double > SamplingSchemeQSpaceType
typedef SamplingSchemeRSpaceType::Pointer SamplingSchemeRSpacePointer
typedef SamplingScheme3D< double > SamplingSchemeRSpaceType
typedef ScalarImageType::Pointer ScalarImagePointer
typedef TScalarImage ScalarImageType
typedef DWIGeneratorBase Self
typedef utl_shared_ptr< STDVectorType > STDVectorPointer
typedef std::vector< PrecisionType > STDVectorType
typedef ImageSource< TOutputImage > Superclass
typedef utl::NDArray< PrecisionType, 1 > VectorType
Public Member Functions
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual DiffusionParameterValuesType GetDiffusionParameterValues ()
virtual const char * GetNameOfClass () const
virtual RandomType GetRandomType ()
virtual MatrixPointer GetStoredOrientationMatrix ()
virtual void SetDiffusionParameterValues (DiffusionParameterValuesType _arg)
virtual void SetRandomType (RandomType _arg)
virtual void SetStoredOrientationMatrix (MatrixPointer _arg)
void SetUniformFromElectrostaticEnergy (const int num)
void SetUniformFromTessellation (const int num)
Public Member Functions inherited from itk::DWIGeneratorBase< TOutputImage, TScalarImage >
ScalarImageType * GetB0Image ()
virtual double GetB0Scale ()
OutputImageType * GetDWIImage ()
OutputImageType * GetEAPImage ()
virtual int GetMaxNumberOfPeaks ()
virtual ModelType GetModelType () const
ScalarImageType * GetMSDImage ()
virtual double GetNoiseSigma ()
unsigned int GetNumberOfQSpaceSamples () const
unsigned int GetNumberOfRSpaceSamples () const
OutputImageType * GetODFImage ()
virtual unsigned int GetODFOrder ()
virtual OutputImageSizeType GetOutputSize ()
OutputImageType * GetPeakImage ()
virtual PeakType GetPeakType ()
ScalarImageType * GetRTOImage ()
virtual double GetSNR ()
itkGetObjectMacro (SamplingSchemeQSpace, SamplingSchemeQSpaceType)
itkGetObjectMacro (SamplingSchemeRSpace, SamplingSchemeRSpaceType)
itkGetObjectMacro (CylinderModel, CylinderModelType)
itkSetGetBooleanMacro (IsOutputDWI)
itkSetGetBooleanMacro (IsOutputEAP)
itkSetGetBooleanMacro (IsOutputODF)
itkSetGetBooleanMacro (IsOutputRTO)
itkSetGetBooleanMacro (IsOutputMSD)
virtual void SetB0Scale (double _arg)
virtual void SetCylinderModel (CylinderModelType *_arg)
virtual void SetMaxNumberOfPeaks (int _arg)
virtual void SetModelType (const ModelType _arg)
virtual void SetNoiseSigma (double _arg)
virtual void SetODFOrder (unsigned int _arg)
virtual void SetOutputSize (OutputImageSizeType _arg)
virtual void SetPeakType (PeakType _arg)
virtual void SetSamplingSchemeQSpace (SamplingSchemeQSpaceType *_arg)
virtual void SetSamplingSchemeRSpace (SamplingSchemeRSpaceType *_arg)
virtual void SetSNR (double _arg)
Static Public Member Functions
static Pointer New ()
Static Public Attributes
static const unsigned int OutputImageDimension = OutputImageType::ImageDimension
Static Public Attributes inherited from itk::DWIGeneratorBase< TOutputImage, TScalarImage >
static const unsigned int OutputImageDimension = OutputImageType::ImageDimension
Protected Member Functions
DWISingleVoxelGenerator ()
void GenerateData ()
void Initialization ()
LightObject::Pointer InternalClone () const
void PrintSelf (std::ostream &os, Indent indent) const
~DWISingleVoxelGenerator ()
Protected Member Functions inherited from itk::DWIGeneratorBase< TOutputImage, TScalarImage >
virtual void AllocateOutputs () ITK_OVERRIDE
DWIGeneratorBase ()
LightObject::Pointer InternalClone () const ITK_OVERRIDE
void PrintSelf (std::ostream &os, Indent indent) const ITK_OVERRIDE
~DWIGeneratorBase ()
Protected Attributes
DiffusionParameterValuesType m_DiffusionParameterValues
RandomType m_RandomType
MatrixPointer m_StoredOrientationMatrix
Protected Attributes inherited from itk::DWIGeneratorBase< TOutputImage, TScalarImage >
double m_B0Scale
CylinderModelPointer m_CylinderModel
bool m_IsOutputDWI
bool m_IsOutputEAP
bool m_IsOutputMSD
bool m_IsOutputODF
bool m_IsOutputRTO
int m_MaxNumberOfPeaks
ModelType m_ModelType
double m_NoiseSigma
unsigned int m_ODFOrder
OutputImageDirectionType m_OutputDirection
OutputImagePointType m_OutputOrigin
OutputImageSizeType m_OutputSize
OutputImageSpacingType m_OutputSpacing
PeakType m_PeakType
SamplingSchemeQSpacePointer m_SamplingSchemeQSpace
SamplingSchemeRSpacePointer m_SamplingSchemeRSpace
double m_SNR
Private Member Functions
DWISingleVoxelGenerator (const Self &)
void operator= (const Self &)
Member Typedef Documentation
template<class TOutputImage , class TScalarImage = Image<float,3>> typedef Superclass::DiffusionParameterContainerType itk::DWISingleVoxelGenerator< TOutputImage, TScalarImage >::DiffusionParameterContainerType
Definition at line 77 of file itkDWISingleVoxelGenerator.h.
template<class TOutputImage , class TScalarImage = Image<float,3>> typedef Superclass::DiffusionParameterValuesType itk::DWISingleVoxelGenerator< TOutputImage, TScalarImage >::DiffusionParameterValuesType
Some convenient typedefs for diffusion parameters.
Definition at line 76 of file itkDWISingleVoxelGenerator.h.
template<class TOutputImage , class TScalarImage = Image<float,3>> typedef Superclass::MatrixPointer itk::DWISingleVoxelGenerator< TOutputImage, TScalarImage >::MatrixPointer
Definition at line 71 of file itkDWISingleVoxelGenerator.h.
template<class TOutputImage , class TScalarImage = Image<float,3>> typedef Superclass::MatrixType itk::DWISingleVoxelGenerator< TOutputImage, TScalarImage >::MatrixType
Definition at line 70 of file itkDWISingleVoxelGenerator.h.
template<class TOutputImage , class TScalarImage = Image<float,3>> typedef Superclass::OutputImageDirectionType itk::DWISingleVoxelGenerator< TOutputImage, TScalarImage >::OutputImageDirectionType
Definition at line 56 of file itkDWISingleVoxelGenerator.h.
template<class TOutputImage , class TScalarImage = Image<float,3>> typedef Superclass::OutputImageIndexType itk::DWISingleVoxelGenerator< TOutputImage, TScalarImage >::OutputImageIndexType
Definition at line 54 of file itkDWISingleVoxelGenerator.h.
template<class TOutputImage , class TScalarImage = Image<float,3>> typedef Superclass::OutputImageInternalPixelType itk::DWISingleVoxelGenerator< TOutputImage, TScalarImage >::OutputImageInternalPixelType
Definition at line 59 of file itkDWISingleVoxelGenerator.h.
template<class TOutputImage , class TScalarImage = Image<float,3>> typedef Superclass::OutputImagePixelType itk::DWISingleVoxelGenerator< TOutputImage, TScalarImage >::OutputImagePixelType
Definition at line 58 of file itkDWISingleVoxelGenerator.h.
template<class TOutputImage , class TScalarImage = Image<float,3>> typedef Superclass::OutputImagePointer itk::DWISingleVoxelGenerator< TOutputImage, TScalarImage >::OutputImagePointer
Definition at line 51 of file itkDWISingleVoxelGenerator.h.
template<class TOutputImage , class TScalarImage = Image<float,3>> typedef Superclass::OutputImagePointType itk::DWISingleVoxelGenerator< TOutputImage, TScalarImage >::OutputImagePointType
Definition at line 55 of file itkDWISingleVoxelGenerator.h.
template<class TOutputImage , class TScalarImage = Image<float,3>> typedef Superclass::OutputImageRegionType itk::DWISingleVoxelGenerator< TOutputImage, TScalarImage >::OutputImageRegionType
Definition at line 57 of file itkDWISingleVoxelGenerator.h.
template<class TOutputImage , class TScalarImage = Image<float,3>> typedef Superclass::OutputImageSizeType itk::DWISingleVoxelGenerator< TOutputImage, TScalarImage >::OutputImageSizeType
Definition at line 52 of file itkDWISingleVoxelGenerator.h.
template<class TOutputImage , class TScalarImage = Image<float,3>> typedef Superclass::OutputImageSpacingType itk::DWISingleVoxelGenerator< TOutputImage, TScalarImage >::OutputImageSpacingType
Definition at line 53 of file itkDWISingleVoxelGenerator.h.
template<class TOutputImage , class TScalarImage = Image<float,3>> typedef Superclass::OutputImageType itk::DWISingleVoxelGenerator< TOutputImage, TScalarImage >::OutputImageType
Some convenient typedefs.
Definition at line 47 of file itkDWISingleVoxelGenerator.h.
template<class TOutputImage , class TScalarImage = Image<float,3>> typedef SmartPointer<Self> itk::DWISingleVoxelGenerator< TOutputImage, TScalarImage >::Pointer
Definition at line 41 of file itkDWISingleVoxelGenerator.h.
template<class TOutputImage , class TScalarImage = Image<float,3>> typedef Superclass::PrecisionType itk::DWISingleVoxelGenerator< TOutputImage, TScalarImage >::PrecisionType
Orientation Matrice Type
Definition at line 69 of file itkDWISingleVoxelGenerator.h.
template<class TOutputImage , class TScalarImage = Image<float,3>> typedef Superclass::ScalarImagePointer itk::DWISingleVoxelGenerator< TOutputImage, TScalarImage >::ScalarImagePointer
Definition at line 66 of file itkDWISingleVoxelGenerator.h.
template<class TOutputImage , class TScalarImage = Image<float,3>> typedef Superclass::ScalarImageType itk::DWISingleVoxelGenerator< TOutputImage, TScalarImage >::ScalarImageType
B0 Image
Definition at line 65 of file itkDWISingleVoxelGenerator.h.
template<class TOutputImage , class TScalarImage = Image<float,3>> typedef DWISingleVoxelGenerator itk::DWISingleVoxelGenerator< TOutputImage, TScalarImage >::Self
Standard class typedefs.
Definition at line 39 of file itkDWISingleVoxelGenerator.h.
template<class TOutputImage , class TScalarImage = Image<float,3>> typedef Superclass::STDVectorPointer itk::DWISingleVoxelGenerator< TOutputImage, TScalarImage >::STDVectorPointer
Definition at line 73 of file itkDWISingleVoxelGenerator.h.
template<class TOutputImage , class TScalarImage = Image<float,3>> typedef Superclass::STDVectorType itk::DWISingleVoxelGenerator< TOutputImage, TScalarImage >::STDVectorType
Definition at line 72 of file itkDWISingleVoxelGenerator.h.
template<class TOutputImage , class TScalarImage = Image<float,3>> typedef DWIGeneratorBase<TOutputImage, TScalarImage> itk::DWISingleVoxelGenerator< TOutputImage, TScalarImage >::Superclass
Definition at line 40 of file itkDWISingleVoxelGenerator.h.
Member Enumeration Documentation
template<class TOutputImage , class TScalarImage = Image<float,3>> enum itk::DWISingleVoxelGenerator::RandomType
Parameters
FIXED fixed fiber configuration for all voxels.
UNIFORM If m_StoredOrientationMatrix is not set, then rotate the fiber configruation using a uniformly random rotation matrix. Otherwise, rotate the fiber configruation using the stored m_StoredOrientationMatrix, and m_OutputSize is overridden by the number of stored orienrations.
GAUSSIAN rotate the fiber configruation using a random rotation matrix generated by a Riemannian Gaussian distribution.
Enumerator
FIXED
UNIFORM
Definition at line 84 of file itkDWISingleVoxelGenerator.h.
Constructor & Destructor Documentation
template<class TOutputImage , class TScalarImage > itk::DWISingleVoxelGenerator< TOutputImage, TScalarImage >::DWISingleVoxelGenerator () protected
Definition at line 30 of file itkDWISingleVoxelGenerator.hxx.
References itk::DWISingleVoxelGenerator< TOutputImage, TScalarImage >::PrintSelf().
template<class TOutputImage , class TScalarImage = Image<float,3>> itk::DWISingleVoxelGenerator< TOutputImage, TScalarImage >::~DWISingleVoxelGenerator () inline protected
Definition at line 115 of file itkDWISingleVoxelGenerator.h.
template<class TOutputImage , class TScalarImage = Image<float,3>> itk::DWISingleVoxelGenerator< TOutputImage, TScalarImage >::DWISingleVoxelGenerator (const Self &) private
Member Function Documentation
template<class TOutputImage , class TScalarImage = Image<float,3>> virtual::itk::LightObject::Pointer itk::DWISingleVoxelGenerator< TOutputImage, TScalarImage >::CreateAnother (void) const
template<class TOutputImage , class TScalarImage > void itk::DWISingleVoxelGenerator< TOutputImage, TScalarImage >::GenerateData (void) protected virtual
Does the real work.
Implements itk::DWIGeneratorBase< TOutputImage, TScalarImage >.
Definition at line 81 of file itkDWISingleVoxelGenerator.hxx.
References itk::PeakContainerHelper::GetDimension(), itk::DiffusionTensor< TPrecision >::GetDWISamples(), itk::DiffusionTensor< TPrecision >::GetEAPSamples(), itk::DiffusionTensor< TPrecision >::GetMeanSquaredDisplacement(), itk::PeakContainerHelper::GetNumberOfPeaks(), itk::DiffusionTensor< TPrecision >::GetODFSamples(), itk::PeakContainerHelper::GetPeak(), itk::DiffusionTensor< TPrecision >::GetReturnToOrigin(), utl::IsInt(), itk::NXYZ, itk::NXYZV, utl::RandomPointInSphere(), itk::DiffusionTensor< TPrecision >::Rotate(), itk::DiffusionTensor< TPrecision >::SetEigenValues(), spams::sort(), utl::spherical2Cartesian(), utl::StdVectorToVnlVector(), utlGlobalException, utlSAException, utlSAGlobalException, utlShowPosition, and itk::XYZV.
Referenced by itk::DWISingleVoxelGenerator< TOutputImage, TScalarImage >::Initialization().
template<class TOutputImage , class TScalarImage = Image<float,3>> virtual DiffusionParameterValuesType itk::DWISingleVoxelGenerator< TOutputImage, TScalarImage >::GetDiffusionParameterValues () virtual
template<class TOutputImage , class TScalarImage = Image<float,3>> virtual const char* itk::DWISingleVoxelGenerator< TOutputImage, TScalarImage >::GetNameOfClass () const virtual
Run-time type information (and related methods).
Reimplemented from itk::DWIGeneratorBase< TOutputImage, TScalarImage >.
template<class TOutputImage , class TScalarImage = Image<float,3>> virtual RandomType itk::DWISingleVoxelGenerator< TOutputImage, TScalarImage >::GetRandomType () virtual
template<class TOutputImage , class TScalarImage = Image<float,3>> virtual MatrixPointer itk::DWISingleVoxelGenerator< TOutputImage, TScalarImage >::GetStoredOrientationMatrix () virtual
template<class TOutputImage , class TScalarImage > void itk::DWISingleVoxelGenerator< TOutputImage, TScalarImage >::Initialization () protected virtual
initialization, test
Reimplemented from itk::DWIGeneratorBase< TOutputImage, TScalarImage >.
Definition at line 68 of file itkDWISingleVoxelGenerator.hxx.
References itk::DWISingleVoxelGenerator< TOutputImage, TScalarImage >::GenerateData().
Referenced by itk::DWISingleVoxelGenerator< TOutputImage, TScalarImage >::InternalClone().
template<class TOutputImage , class TScalarImage > LightObject::Pointer itk::DWISingleVoxelGenerator< TOutputImage, TScalarImage >::InternalClone () const protected
Definition at line 50 of file itkDWISingleVoxelGenerator.hxx.
References itk::DWISingleVoxelGenerator< TOutputImage, TScalarImage >::Initialization().
Referenced by itk::DWISingleVoxelGenerator< TOutputImage, TScalarImage >::PrintSelf().
template<class TOutputImage , class TScalarImage = Image<float,3>> static Pointer itk::DWISingleVoxelGenerator< TOutputImage, TScalarImage >::New () static
Method for creation through the object factory.
template<class TOutputImage , class TScalarImage = Image<float,3>> void itk::DWISingleVoxelGenerator< TOutputImage, TScalarImage >::operator= (const Self &) private
template<class TOutputImage , class TScalarImage > void itk::DWISingleVoxelGenerator< TOutputImage, TScalarImage >::PrintSelf (std::ostream & os, Indent indent) const protected
Definition at line 39 of file itkDWISingleVoxelGenerator.hxx.
References itk::DWISingleVoxelGenerator< TOutputImage, TScalarImage >::InternalClone(), utl::PrintUtlMatrix(), and PrintVar1.
Referenced by itk::DWISingleVoxelGenerator< TOutputImage, TScalarImage >::DWISingleVoxelGenerator().
template<class TOutputImage , class TScalarImage = Image<float,3>> virtual void itk::DWISingleVoxelGenerator< TOutputImage, TScalarImage >::SetDiffusionParameterValues (DiffusionParameterValuesType _arg) virtual
diffusion parameters for all voxels
template<class TOutputImage , class TScalarImage = Image<float,3>> virtual void itk::DWISingleVoxelGenerator< TOutputImage, TScalarImage >::SetRandomType (RandomType _arg) virtual
template<class TOutputImage , class TScalarImage = Image<float,3>> virtual void itk::DWISingleVoxelGenerator< TOutputImage, TScalarImage >::SetStoredOrientationMatrix (MatrixPointer _arg) virtual
template<class TOutputImage , class TScalarImage = Image<float,3>> void itk::DWISingleVoxelGenerator< TOutputImage, TScalarImage >::SetUniformFromElectrostaticEnergy (const int num) inline
Definition at line 93 of file itkDWISingleVoxelGenerator.h.
References CARTESIAN_TO_CARTESIAN, DIRECTION_NODUPLICATE, and DIRECTION_NOFLIP.
template<class TOutputImage , class TScalarImage = Image<float,3>> void itk::DWISingleVoxelGenerator< TOutputImage, TScalarImage >::SetUniformFromTessellation (const int num) inline
Definition at line 98 of file itkDWISingleVoxelGenerator.h.
References CARTESIAN_TO_CARTESIAN, DIRECTION_NODUPLICATE, and DIRECTION_NOFLIP.
Member Data Documentation
template<class TOutputImage , class TScalarImage = Image<float,3>> DiffusionParameterValuesType itk::DWISingleVoxelGenerator< TOutputImage, TScalarImage >::m_DiffusionParameterValues protected
Definition at line 125 of file itkDWISingleVoxelGenerator.h.
template<class TOutputImage , class TScalarImage = Image<float,3>> RandomType itk::DWISingleVoxelGenerator< TOutputImage, TScalarImage >::m_RandomType protected
Definition at line 127 of file itkDWISingleVoxelGenerator.h.
template<class TOutputImage , class TScalarImage = Image<float,3>> MatrixPointer itk::DWISingleVoxelGenerator< TOutputImage, TScalarImage >::m_StoredOrientationMatrix protected
Definition at line 129 of file itkDWISingleVoxelGenerator.h.
template<class TOutputImage , class TScalarImage = Image<float,3>> const unsigned int itk::DWISingleVoxelGenerator< TOutputImage, TScalarImage >::OutputImageDimension = OutputImageType::ImageDimension static
Output image dimension
Definition at line 62 of file itkDWISingleVoxelGenerator.h.
The documentation for this class was generated from the following files:
Modules/DWIProcessing/include/itkDWISingleVoxelGenerator.h
Modules/DWIProcessing/include/itkDWISingleVoxelGenerator.hxx