DMRITool: itk::Functor::SHCoefficientsFit< T > Class Template Reference
itk::Functor::SHCoefficientsFit< T > Class Template Reference
Math
#include <itkSHCoefficientsFit.h>
Detailed Description
template<class T = double>
class itk::Functor::SHCoefficientsFit< T >
fit SH coefficients from spherical function samples.
Author
Jian Cheng (JC), jian..nosp@m.chen.nosp@m.g.198.nosp@m.3@gm.nosp@m.ail.c.nosp@m.om
Definition at line 34 of file itkSHCoefficientsFit.h.
Public Types
typedef SmartPointer< const Self > ConstPointer
typedef utl_shared_ptr< MatrixType > MatrixPointer
typedef utl::NDArray< double, 2 > MatrixType
typedef SmartPointer< Self > Pointer
typedef T PreciseType
typedef SHCoefficientsFit Self
typedef utl::Functor::VectorFunctorBase< utl::Vector< T > > Superclass
typedef utl::NDArray< double, 1 > VectorType
Public Types inherited from utl::Functor::VectorFunctorBase< utl::Vector< T > >
typedef VectorFunctorBase Self
Public Member Functions
int GetOutputDimension (const int) const
void Initialize ()
bool operator!= (const Self &other) const
VectorType operator() (const VectorType &sf) const
Self & operator= (const Self &other)
bool operator== (const Self &other) const
void Print (std::ostream &os=std::cout) const
SHCoefficientsFit ()
SHCoefficientsFit (const Self &other)
utlGetMacro (BasisSHMatrix, MatrixPointer)
utlGetMacro (BasisSHMatrixPInv, MatrixPointer)
utlSetGetMacro (SHRank, int)
utlSetGetMacro (Lambda, double)
utlSetGetMacro (Power, double)
utlSetGetMacro (Orientations, MatrixPointer)
void VerifyInputParameters (const int inputVecSize=-1) const
virtual ~SHCoefficientsFit ()
Public Member Functions inherited from utl::Functor::VectorFunctorBase< utl::Vector< T > >
virtual int GetLogLevel () const
int GetOutputDimension (const int inputSize) const
int GetOutputDimension (const std::vector< int > &sizeVec) const
void Initialize ()
bool operator!= (const Self &other) const
Self & operator= (const Self &other)
bool operator== (const Self &other) const
void Print (std::ostream &os=std::cout) const
virtual void SetLogLevel (const int _arg)
void VerifyInputParameters (const int inputSize=-1) const
Protected Attributes
MatrixPointer m_BasisSHMatrix
MatrixPointer m_BasisSHMatrixPInv
double m_Lambda =0
MatrixPointer m_Orientations
double m_Power =1.0
int m_SHRank =-1
Protected Attributes inherited from utl::Functor::VectorFunctorBase< utl::Vector< T > >
int m_LogLevel
Member Typedef Documentation
template<class T = double> typedef SmartPointer<const Self> itk::Functor::SHCoefficientsFit< T >::ConstPointer
Definition at line 42 of file itkSHCoefficientsFit.h.
template<class T = double> typedef utl_shared_ptr<MatrixType> itk::Functor::SHCoefficientsFit< T >::MatrixPointer
Definition at line 49 of file itkSHCoefficientsFit.h.
template<class T = double> typedef utl::NDArray<double,2> itk::Functor::SHCoefficientsFit< T >::MatrixType
Definition at line 48 of file itkSHCoefficientsFit.h.
template<class T = double> typedef SmartPointer<Self> itk::Functor::SHCoefficientsFit< T >::Pointer
Definition at line 41 of file itkSHCoefficientsFit.h.
template<class T = double> typedef T itk::Functor::SHCoefficientsFit< T >::PreciseType
Definition at line 45 of file itkSHCoefficientsFit.h.
template<class T = double> typedef SHCoefficientsFit itk::Functor::SHCoefficientsFit< T >::Self
Standard class typedefs.
Definition at line 39 of file itkSHCoefficientsFit.h.
template<class T = double> typedef utl::Functor::VectorFunctorBase<utl::Vector<T> > itk::Functor::SHCoefficientsFit< T >::Superclass
Definition at line 40 of file itkSHCoefficientsFit.h.
template<class T = double> typedef utl::NDArray<double,1> itk::Functor::SHCoefficientsFit< T >::VectorType
Definition at line 47 of file itkSHCoefficientsFit.h.
Constructor & Destructor Documentation
template<class T = double> itk::Functor::SHCoefficientsFit< T >::SHCoefficientsFit () inline
Definition at line 51 of file itkSHCoefficientsFit.h.
template<class T = double> virtual itk::Functor::SHCoefficientsFit< T >::~SHCoefficientsFit () inline virtual
Definition at line 57 of file itkSHCoefficientsFit.h.
template<class T = double> itk::Functor::SHCoefficientsFit< T >::SHCoefficientsFit (const Self & other) inline
Definition at line 65 of file itkSHCoefficientsFit.h.
Member Function Documentation
template<class T = double> int itk::Functor::SHCoefficientsFit< T >::GetOutputDimension (const int) const inline
Definition at line 152 of file itkSHCoefficientsFit.h.
References utl::RankToDimSH(), and utlSAException.
template<class T = double> void itk::Functor::SHCoefficientsFit< T >::Initialize () inline
Definition at line 108 of file itkSHCoefficientsFit.h.
References CARTESIAN_TO_SPHERICAL, utl::ComputeSHMatrix(), utl::GetIndexSHlm(), utl::InverseSymmericMatrix(), utl::IsLogDebug(), LOG_DEBUG, utl::PrintUtlMatrix(), and utlVLogPosition.
template<class T = double> bool itk::Functor::SHCoefficientsFit< T >::operator!= (const Self & other) const inline
Definition at line 61 of file itkSHCoefficientsFit.h.
template<class T = double> VectorType itk::Functor::SHCoefficientsFit< T >::operator() (const VectorType & sf) const inline
Definition at line 141 of file itkSHCoefficientsFit.h.
References utl::Pow().
template<class T = double> Self& itk::Functor::SHCoefficientsFit< T >::operator= (const Self & other) inline
Definition at line 70 of file itkSHCoefficientsFit.h.
References itk::Functor::SHCoefficientsFit< T >::m_BasisSHMatrix, itk::Functor::SHCoefficientsFit< T >::m_BasisSHMatrixPInv, itk::Functor::SHCoefficientsFit< T >::m_Lambda, itk::Functor::SHCoefficientsFit< T >::m_Orientations, itk::Functor::SHCoefficientsFit< T >::m_Power, itk::Functor::SHCoefficientsFit< T >::m_SHRank, utlGetMacro, and utlSetGetMacro.
template<class T = double> bool itk::Functor::SHCoefficientsFit< T >::operator== (const Self & other) const inline
Definition at line 59 of file itkSHCoefficientsFit.h.
template<class T = double> void itk::Functor::SHCoefficientsFit< T >::Print (std::ostream & os = std::cout) const inline
Definition at line 158 of file itkSHCoefficientsFit.h.
References utl::Print(), utl::PrintUtlMatrix(), and utlLogOSVar.
template<class T = double> itk::Functor::SHCoefficientsFit< T >::utlGetMacro (BasisSHMatrix , MatrixPointer)
template<class T = double> itk::Functor::SHCoefficientsFit< T >::utlGetMacro (BasisSHMatrixPInv , MatrixPointer)
template<class T = double> itk::Functor::SHCoefficientsFit< T >::utlSetGetMacro (SHRank , int)
template<class T = double> itk::Functor::SHCoefficientsFit< T >::utlSetGetMacro (Lambda , double)
template<class T = double> itk::Functor::SHCoefficientsFit< T >::utlSetGetMacro (Power , double)
template<class T = double> itk::Functor::SHCoefficientsFit< T >::utlSetGetMacro (Orientations , MatrixPointer)
template<class T = double> void itk::Functor::SHCoefficientsFit< T >::VerifyInputParameters (const int inputVecSize = -1) const inline
Definition at line 94 of file itkSHCoefficientsFit.h.
References LOG_DEBUG, utlGlobalException, utlSAGlobalException, and utlVLogPosition.
Member Data Documentation
template<class T = double> MatrixPointer itk::Functor::SHCoefficientsFit< T >::m_BasisSHMatrix protected
SH basis matrix
Definition at line 183 of file itkSHCoefficientsFit.h.
Referenced by itk::Functor::SHCoefficientsFit< T >::operator=().
template<class T = double> MatrixPointer itk::Functor::SHCoefficientsFit< T >::m_BasisSHMatrixPInv protected
pseudoinverse of m_BasisSHMatrix, considering L2 regularization using m_Lambda
Definition at line 185 of file itkSHCoefficientsFit.h.
Referenced by itk::Functor::SHCoefficientsFit< T >::operator=().
template<class T = double> double itk::Functor::SHCoefficientsFit< T >::m_Lambda =0 protected
L2 regularization parameter.
Definition at line 175 of file itkSHCoefficientsFit.h.
Referenced by itk::Functor::SHCoefficientsFit< T >::operator=().
template<class T = double> MatrixPointer itk::Functor::SHCoefficientsFit< T >::m_Orientations protected
Orientation matrix in Cartesian format
Definition at line 180 of file itkSHCoefficientsFit.h.
Referenced by itk::Functor::SHCoefficientsFit< T >::operator=().
template<class T = double> double itk::Functor::SHCoefficientsFit< T >::m_Power =1.0 protected
Definition at line 177 of file itkSHCoefficientsFit.h.
Referenced by itk::Functor::SHCoefficientsFit< T >::operator=().
template<class T = double> int itk::Functor::SHCoefficientsFit< T >::m_SHRank =-1 protected
rank for SH basis
Definition at line 172 of file itkSHCoefficientsFit.h.
Referenced by itk::Functor::SHCoefficientsFit< T >::operator=().
The documentation for this class was generated from the following file:
Modules/Math/include/itkSHCoefficientsFit.h