DMRITool: itk::VariableLengthVectorImageFileReader< TOutputImage > Class Template Reference
itk::VariableLengthVectorImageFileReader< TOutputImage > Class Template Reference
#include <itkVariableLengthVectorImageFileReader.h>
Detailed Description
template<class TOutputImage>
class itk::VariableLengthVectorImageFileReader< TOutputImage >
Reads variable length vector image data.
Definition at line 61 of file itkVariableLengthVectorImageFileReader.h.
Public Types
typedef OutputImageType::DirectionType OutputImageDirectionType
typedef OutputImageType::IndexType OutputImageIndexType
typedef OutputImageType::PixelContainer::Pointer OutputImagePixelContainerPointerType
typedef OutputImageType::PixelContainer OutputImagePixelContainerType
typedef OutputImageType::PixelType OutputImagePixelType
typedef OutputImageType::Pointer OutputImagePointer
typedef OutputImageType::PointType OutputImagePointType
typedef OutputImageType::RegionType OutputImageRegionType
typedef OutputImageType::SizeType OutputImageSizeType
typedef OutputImageType::SpacingType OutputImageSpacingType
typedef TOutputImage OutputImageType
typedef SmartPointer< Self > Pointer
typedef VariableLengthVectorImageFileReader Self
typedef ImageSource< TOutputImage > Superclass
Public Member Functions
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual const char * GetFileName () const
virtual const char * GetNameOfClass () const
virtual const bool & GetUseStreaming ()
itkGetObjectMacro (ImageIO, ImageIOBase)
virtual void SetFileName (const char *_arg)
virtual void SetUseStreaming (bool _arg)
virtual void UseStreamingOff ()
virtual void UseStreamingOn ()
Static Public Member Functions
static Pointer New ()
Static Public Attributes
static const unsigned int ImageDimension = Superclass::OutputImageDimension
Protected Types
typedef itk::ImageFileReader< LengthImageType > LengthImageFileReaderType
typedef Image< LengthType, ImageDimension > LengthImageType
typedef unsigned int LengthType
typedef itk::ImageFileReader< ValueImageType > ValueImageFileReaderType
typedef Image< typename OutputImagePixelType::ValueType, 1 > ValueImageType
Protected Member Functions
virtual void GenerateData () ITK_OVERRIDE
void PrintSelf (std::ostream &os, Indent indent) const ITK_OVERRIDE
VariableLengthVectorImageFileReader ()
~VariableLengthVectorImageFileReader ()
Protected Attributes
std::string m_FileName
ImageIOBase::Pointer m_ImageIO
LengthImageType::Pointer m_LengthImage
LengthImageFileReaderType::Pointer m_LengthImageFileReader
bool m_UseStreaming
ValueImageType::Pointer m_ValueImage
ValueImageFileReaderType::Pointer m_ValueImageFileReader
Private Member Functions
void operator= (const Self &)
VariableLengthVectorImageFileReader (const Self &)
Private Attributes
std::string m_ExceptionMessage
Member Typedef Documentation
template<class TOutputImage > typedef itk::ImageFileReader<LengthImageType> itk::VariableLengthVectorImageFileReader< TOutputImage >::LengthImageFileReaderType protected
Definition at line 127 of file itkVariableLengthVectorImageFileReader.h.
template<class TOutputImage > typedef Image<LengthType, ImageDimension> itk::VariableLengthVectorImageFileReader< TOutputImage >::LengthImageType protected
Definition at line 121 of file itkVariableLengthVectorImageFileReader.h.
template<class TOutputImage > typedef unsigned int itk::VariableLengthVectorImageFileReader< TOutputImage >::LengthType protected
Convert a block of pixels from one type to another. Test whether the given filename exist and it is readable, this is intended to be called before attempting to use ImageIO classes for actually reading the file. If the file doesn't exist or it is not readable, and exception with an approriate message will be thrown.
Definition at line 120 of file itkVariableLengthVectorImageFileReader.h.
template<class TOutputImage > typedef OutputImageType::DirectionType itk::VariableLengthVectorImageFileReader< TOutputImage >::OutputImageDirectionType
Definition at line 85 of file itkVariableLengthVectorImageFileReader.h.
template<class TOutputImage > typedef OutputImageType::IndexType itk::VariableLengthVectorImageFileReader< TOutputImage >::OutputImageIndexType
Definition at line 83 of file itkVariableLengthVectorImageFileReader.h.
template<class TOutputImage > typedef OutputImageType::PixelContainer::Pointer itk::VariableLengthVectorImageFileReader< TOutputImage >::OutputImagePixelContainerPointerType
Definition at line 89 of file itkVariableLengthVectorImageFileReader.h.
template<class TOutputImage > typedef OutputImageType::PixelContainer itk::VariableLengthVectorImageFileReader< TOutputImage >::OutputImagePixelContainerType
Definition at line 88 of file itkVariableLengthVectorImageFileReader.h.
template<class TOutputImage > typedef OutputImageType::PixelType itk::VariableLengthVectorImageFileReader< TOutputImage >::OutputImagePixelType
Definition at line 87 of file itkVariableLengthVectorImageFileReader.h.
template<class TOutputImage > typedef OutputImageType::Pointer itk::VariableLengthVectorImageFileReader< TOutputImage >::OutputImagePointer
Definition at line 80 of file itkVariableLengthVectorImageFileReader.h.
template<class TOutputImage > typedef OutputImageType::PointType itk::VariableLengthVectorImageFileReader< TOutputImage >::OutputImagePointType
Definition at line 84 of file itkVariableLengthVectorImageFileReader.h.
template<class TOutputImage > typedef OutputImageType::RegionType itk::VariableLengthVectorImageFileReader< TOutputImage >::OutputImageRegionType
Definition at line 86 of file itkVariableLengthVectorImageFileReader.h.
template<class TOutputImage > typedef OutputImageType::SizeType itk::VariableLengthVectorImageFileReader< TOutputImage >::OutputImageSizeType
Definition at line 81 of file itkVariableLengthVectorImageFileReader.h.
template<class TOutputImage > typedef OutputImageType::SpacingType itk::VariableLengthVectorImageFileReader< TOutputImage >::OutputImageSpacingType
Definition at line 82 of file itkVariableLengthVectorImageFileReader.h.
template<class TOutputImage > typedef TOutputImage itk::VariableLengthVectorImageFileReader< TOutputImage >::OutputImageType
Some convenient typedefs.
Definition at line 79 of file itkVariableLengthVectorImageFileReader.h.
template<class TOutputImage > typedef SmartPointer<Self> itk::VariableLengthVectorImageFileReader< TOutputImage >::Pointer
Definition at line 67 of file itkVariableLengthVectorImageFileReader.h.
template<class TOutputImage > typedef VariableLengthVectorImageFileReader itk::VariableLengthVectorImageFileReader< TOutputImage >::Self
Standard class typedefs.
Definition at line 65 of file itkVariableLengthVectorImageFileReader.h.
template<class TOutputImage > typedef ImageSource<TOutputImage> itk::VariableLengthVectorImageFileReader< TOutputImage >::Superclass
Definition at line 66 of file itkVariableLengthVectorImageFileReader.h.
template<class TOutputImage > typedef itk::ImageFileReader<ValueImageType> itk::VariableLengthVectorImageFileReader< TOutputImage >::ValueImageFileReaderType protected
Definition at line 128 of file itkVariableLengthVectorImageFileReader.h.
template<class TOutputImage > typedef Image<typename OutputImagePixelType::ValueType, 1> itk::VariableLengthVectorImageFileReader< TOutputImage >::ValueImageType protected
Definition at line 122 of file itkVariableLengthVectorImageFileReader.h.
Constructor & Destructor Documentation
template<class TOutputImage > itk::VariableLengthVectorImageFileReader< TOutputImage >::VariableLengthVectorImageFileReader () protected
Definition at line 26 of file itkVariableLengthVectorImageFileReader.hxx.
References itk::VariableLengthVectorImageFileReader< TOutputImage >::~VariableLengthVectorImageFileReader().
template<class TOutputImage > itk::VariableLengthVectorImageFileReader< TOutputImage >::~VariableLengthVectorImageFileReader () protected
Definition at line 35 of file itkVariableLengthVectorImageFileReader.hxx.
References itk::VariableLengthVectorImageFileReader< TOutputImage >::PrintSelf().
Referenced by itk::VariableLengthVectorImageFileReader< TOutputImage >::VariableLengthVectorImageFileReader().
template<class TOutputImage > itk::VariableLengthVectorImageFileReader< TOutputImage >::VariableLengthVectorImageFileReader (const Self &) private
Member Function Documentation
template<class TOutputImage > virtual::itk::LightObject::Pointer itk::VariableLengthVectorImageFileReader< TOutputImage >::CreateAnother (void) const
template<class TOutputImage > void itk::VariableLengthVectorImageFileReader< TOutputImage >::GenerateData (void) protected virtual
Does the real work.
Definition at line 61 of file itkVariableLengthVectorImageFileReader.hxx.
Referenced by itk::VariableLengthVectorImageFileReader< TOutputImage >::PrintSelf().
template<class TOutputImage > virtual const char* itk::VariableLengthVectorImageFileReader< TOutputImage >::GetFileName () const virtual
template<class TOutputImage > virtual const char* itk::VariableLengthVectorImageFileReader< TOutputImage >::GetNameOfClass () const virtual
Run-time type information (and related methods).
template<class TOutputImage > virtual const bool& itk::VariableLengthVectorImageFileReader< TOutputImage >::GetUseStreaming () virtual
template<class TOutputImage > itk::VariableLengthVectorImageFileReader< TOutputImage >::itkGetObjectMacro (ImageIO , ImageIOBase)
Set/Get the ImageIO helper class
template<class TOutputImage > static Pointer itk::VariableLengthVectorImageFileReader< TOutputImage >::New () static
Method for creation through the object factory.
template<class TOutputImage > void itk::VariableLengthVectorImageFileReader< TOutputImage >::operator= (const Self &) private
template<class TOutputImage > void itk::VariableLengthVectorImageFileReader< TOutputImage >::PrintSelf (std::ostream & os, Indent indent) const protected
Definition at line 41 of file itkVariableLengthVectorImageFileReader.hxx.
References itk::VariableLengthVectorImageFileReader< TOutputImage >::GenerateData().
Referenced by itk::VariableLengthVectorImageFileReader< TOutputImage >::~VariableLengthVectorImageFileReader().
template<class TOutputImage > virtual void itk::VariableLengthVectorImageFileReader< TOutputImage >::SetFileName (const char * _arg) virtual
Specify the files to read. This is forwarded to the IO instance.
template<class TOutputImage > virtual void itk::VariableLengthVectorImageFileReader< TOutputImage >::SetUseStreaming (bool _arg) virtual
Set the stream On or Off
template<class TOutputImage > virtual void itk::VariableLengthVectorImageFileReader< TOutputImage >::UseStreamingOff () virtual
template<class TOutputImage > virtual void itk::VariableLengthVectorImageFileReader< TOutputImage >::UseStreamingOn () virtual
Member Data Documentation
template<class TOutputImage > const unsigned int itk::VariableLengthVectorImageFileReader< TOutputImage >::ImageDimension = Superclass::OutputImageDimension static
The dimensionality of the input and output images.
Definition at line 76 of file itkVariableLengthVectorImageFileReader.h.
template<class TOutputImage > std::string itk::VariableLengthVectorImageFileReader< TOutputImage >::m_ExceptionMessage private
Definition at line 144 of file itkVariableLengthVectorImageFileReader.h.
template<class TOutputImage > std::string itk::VariableLengthVectorImageFileReader< TOutputImage >::m_FileName protected
Definition at line 136 of file itkVariableLengthVectorImageFileReader.h.
template<class TOutputImage > ImageIOBase::Pointer itk::VariableLengthVectorImageFileReader< TOutputImage >::m_ImageIO protected
Definition at line 138 of file itkVariableLengthVectorImageFileReader.h.
template<class TOutputImage > LengthImageType::Pointer itk::VariableLengthVectorImageFileReader< TOutputImage >::m_LengthImage protected
Definition at line 124 of file itkVariableLengthVectorImageFileReader.h.
template<class TOutputImage > LengthImageFileReaderType::Pointer itk::VariableLengthVectorImageFileReader< TOutputImage >::m_LengthImageFileReader protected
Definition at line 130 of file itkVariableLengthVectorImageFileReader.h.
template<class TOutputImage > bool itk::VariableLengthVectorImageFileReader< TOutputImage >::m_UseStreaming protected
Definition at line 137 of file itkVariableLengthVectorImageFileReader.h.
template<class TOutputImage > ValueImageType::Pointer itk::VariableLengthVectorImageFileReader< TOutputImage >::m_ValueImage protected
Definition at line 125 of file itkVariableLengthVectorImageFileReader.h.
template<class TOutputImage > ValueImageFileReaderType::Pointer itk::VariableLengthVectorImageFileReader< TOutputImage >::m_ValueImageFileReader protected
Definition at line 131 of file itkVariableLengthVectorImageFileReader.h.
The documentation for this class was generated from the following files:
ThirdParty/VariableLengthVectorImage/include/itkVariableLengthVectorImageFileReader.h
ThirdParty/VariableLengthVectorImage/include/itkVariableLengthVectorImageFileReader.hxx