DMRITool: itk::SphericalPolarFourierRadialGenerator< PreciseType > Class Template Reference
itk::SphericalPolarFourierRadialGenerator< PreciseType > Class Template Reference
Math
#include <itkSphericalPolarFourierGenerator.h>
Detailed Description
template<class PreciseType = double>
class itk::SphericalPolarFourierRadialGenerator< PreciseType >
radial part of general SPF basis
Author
Jian Cheng
Definition at line 37 of file itkSphericalPolarFourierGenerator.h.
Public Types
typedef SmartPointer< const Self > ConstPointer
typedef SmartPointer< Self > Pointer
typedef SphericalPolarFourierRadialGenerator Self
enum SPFType {
SPF =0,
DSPF,
SHORE
}
typedef Object Superclass
Public Member Functions
virtual ::itk::LightObject::Pointer CreateAnother (void) const
PreciseType Evaluate (const PreciseType qrValue, const bool isFourier=false) const
virtual int GetL ()
virtual int GetN ()
virtual const char * GetNameOfClass () const
PreciseType GetNormalizeFacotr (const bool isFourier=false) const
virtual double GetScale ()
virtual SPFType GetSPFType ()
virtual void SetL (int _arg)
virtual void SetN (int _arg)
void SetNLSPF (const int n, const int l, const SPFType spf)
virtual void SetScale (double _arg)
virtual void SetSPFType (SPFType _arg)
Static Public Member Functions
static Pointer New ()
Protected Member Functions
SphericalPolarFourierRadialGenerator ()
virtual ~SphericalPolarFourierRadialGenerator ()
Protected Attributes
int m_L
int m_N
double m_Scale
SPFType m_SPFType
Private Member Functions
void operator= (const Self &)
SphericalPolarFourierRadialGenerator (const Self &)
Member Typedef Documentation
template<class PreciseType = double> typedef SmartPointer<const Self> itk::SphericalPolarFourierRadialGenerator< PreciseType >::ConstPointer
Definition at line 44 of file itkSphericalPolarFourierGenerator.h.
template<class PreciseType = double> typedef SmartPointer<Self> itk::SphericalPolarFourierRadialGenerator< PreciseType >::Pointer
Definition at line 43 of file itkSphericalPolarFourierGenerator.h.
template<class PreciseType = double> typedef SphericalPolarFourierRadialGenerator itk::SphericalPolarFourierRadialGenerator< PreciseType >::Self
Standard class typedefs.
Definition at line 41 of file itkSphericalPolarFourierGenerator.h.
template<class PreciseType = double> typedef Object itk::SphericalPolarFourierRadialGenerator< PreciseType >::Superclass
Definition at line 42 of file itkSphericalPolarFourierGenerator.h.
Member Enumeration Documentation
template<class PreciseType = double> enum itk::SphericalPolarFourierRadialGenerator::SPFType
Enumerator
SPF
DSPF
SHORE
Definition at line 52 of file itkSphericalPolarFourierGenerator.h.
Constructor & Destructor Documentation
template<class PreciseType > itk::SphericalPolarFourierRadialGenerator< PreciseType >::SphericalPolarFourierRadialGenerator () protected
SphericalPolarFourierRadialGenerator constructor
Definition at line 35 of file itkSphericalPolarFourierGenerator.hxx.
References itk::SphericalPolarFourierRadialGenerator< PreciseType >::GetNormalizeFacotr().
template<class PreciseType = double> virtual itk::SphericalPolarFourierRadialGenerator< PreciseType >::~SphericalPolarFourierRadialGenerator () inline protected virtual
Definition at line 85 of file itkSphericalPolarFourierGenerator.h.
template<class PreciseType = double> itk::SphericalPolarFourierRadialGenerator< PreciseType >::SphericalPolarFourierRadialGenerator (const Self &) private
Member Function Documentation
template<class PreciseType = double> virtual::itk::LightObject::Pointer itk::SphericalPolarFourierRadialGenerator< PreciseType >::CreateAnother (void) const
template<class PreciseType > PreciseType itk::SphericalPolarFourierRadialGenerator< PreciseType >::Evaluate (const PreciseType qrValue, const bool isFourier = false) const
Definition at line 100 of file itkSphericalPolarFourierGenerator.hxx.
References itk::SphericalPolarFourierGenerator< PreciseType >::Evaluate(), utl::Factorial(), utl::GammaHalfInteger(), utl::GetCoefLaguerre(), utl::Hyperg1F1(), utl::Lagurre(), M_PI, itk::SphericalPolarFourierRadialGenerator< PreciseType >::New(), utl::PowHalfInteger(), utl::sign(), utlException, utlPrintVar3, utlPrintVar4, utlPrintVar5, and utlShowPosition.
Referenced by itk::SphericalPolarFourierRadialGenerator< PreciseType >::GetNormalizeFacotr().
template<class PreciseType = double> virtual int itk::SphericalPolarFourierRadialGenerator< PreciseType >::GetL () virtual
template<class PreciseType = double> virtual int itk::SphericalPolarFourierRadialGenerator< PreciseType >::GetN () virtual
template<class PreciseType = double> virtual const char* itk::SphericalPolarFourierRadialGenerator< PreciseType >::GetNameOfClass () const virtual
Standard part of every itk Object.
template<class PreciseType > PreciseType itk::SphericalPolarFourierRadialGenerator< PreciseType >::GetNormalizeFacotr (const bool isFourier = false) const
Definition at line 46 of file itkSphericalPolarFourierGenerator.hxx.
References itk::SphericalPolarFourierRadialGenerator< PreciseType >::Evaluate(), utl::Factorial(), utl::GammaHalfInteger(), itk::SphericalPolarFourierRadialGenerator< PreciseType >::GetNormalizeFacotr(), M_PI, itk::SphericalPolarFourierRadialGenerator< PreciseType >::New(), utl::PowHalfInteger(), itk::SphericalPolarFourierRadialGenerator< PreciseType >::SetNLSPF(), itk::SphericalPolarFourierRadialGenerator< PreciseType >::SetScale(), utl::sign(), utlException, and utlShowPosition.
Referenced by itk::SphericalPolarFourierRadialGenerator< PreciseType >::GetNormalizeFacotr(), and itk::SphericalPolarFourierRadialGenerator< PreciseType >::SphericalPolarFourierRadialGenerator().
template<class PreciseType = double> virtual double itk::SphericalPolarFourierRadialGenerator< PreciseType >::GetScale () virtual
template<class PreciseType = double> virtual SPFType itk::SphericalPolarFourierRadialGenerator< PreciseType >::GetSPFType () virtual
template<class PreciseType = double> static Pointer itk::SphericalPolarFourierRadialGenerator< PreciseType >::New () static
Method for creation through the object factory.
Referenced by itk::SphericalPolarFourierRadialGenerator< PreciseType >::Evaluate(), and itk::SphericalPolarFourierRadialGenerator< PreciseType >::GetNormalizeFacotr().
template<class PreciseType = double> void itk::SphericalPolarFourierRadialGenerator< PreciseType >::operator= (const Self &) private
template<class PreciseType = double> virtual void itk::SphericalPolarFourierRadialGenerator< PreciseType >::SetL (int _arg) virtual
template<class PreciseType = double> virtual void itk::SphericalPolarFourierRadialGenerator< PreciseType >::SetN (int _arg) virtual
template<class PreciseType = double> void itk::SphericalPolarFourierRadialGenerator< PreciseType >::SetNLSPF (const int n, const int l, const SPFType spf) inline
Definition at line 72 of file itkSphericalPolarFourierGenerator.h.
Referenced by itk::SphericalPolarFourierRadialGenerator< PreciseType >::GetNormalizeFacotr().
template<class PreciseType = double> virtual void itk::SphericalPolarFourierRadialGenerator< PreciseType >::SetScale (double _arg) virtual
Referenced by itk::SphericalPolarFourierRadialGenerator< PreciseType >::GetNormalizeFacotr().
template<class PreciseType = double> virtual void itk::SphericalPolarFourierRadialGenerator< PreciseType >::SetSPFType (SPFType _arg) virtual
Member Data Documentation
template<class PreciseType = double> int itk::SphericalPolarFourierRadialGenerator< PreciseType >::m_L protected
Definition at line 90 of file itkSphericalPolarFourierGenerator.h.
template<class PreciseType = double> int itk::SphericalPolarFourierRadialGenerator< PreciseType >::m_N protected
Definition at line 89 of file itkSphericalPolarFourierGenerator.h.
template<class PreciseType = double> double itk::SphericalPolarFourierRadialGenerator< PreciseType >::m_Scale protected
Definition at line 92 of file itkSphericalPolarFourierGenerator.h.
template<class PreciseType = double> SPFType itk::SphericalPolarFourierRadialGenerator< PreciseType >::m_SPFType protected
Definition at line 91 of file itkSphericalPolarFourierGenerator.h.
The documentation for this class was generated from the following files:
Modules/Math/include/itkSphericalPolarFourierGenerator.h
Modules/Math/include/itkSphericalPolarFourierGenerator.hxx