DMRITool: itk::VectorImageRegionIteratorWithIndex< Image< TPixel, VImageDimension > > Class Template Reference
itk::VectorImageRegionIteratorWithIndex< Image< TPixel, VImageDimension > > Class Template Reference
#include <itkVectorImageRegionIteratorWithIndex.h>
Detailed Description
template<typename TPixel, unsigned int VImageDimension>
class itk::VectorImageRegionIteratorWithIndex< Image< TPixel, VImageDimension > >
For Image<TPixel, 4>
Definition at line 351 of file itkVectorImageRegionIteratorWithIndex.h.
Public Types
typedef Superclass::AccessorType AccessorType
typedef Superclass::ImageType ImageType
typedef Superclass::IndexType IndexType
typedef Superclass::InternalPixelType InternalPixelType
typedef ImageRegion< VImageDimension > NDImageRegionType
typedef Superclass::OffsetType OffsetType
typedef Superclass::PixelContainer PixelContainer
typedef Superclass::PixelContainerPointer PixelContainerPointer
typedef Superclass::PixelType PixelType
typedef VariableLengthVector< InternalPixelType > PixelVectorType
typedef Superclass::RegionType RegionType
typedef VectorImageRegionIteratorWithIndex Self
typedef Superclass::SizeType SizeType
typedef ImageRegionIteratorWithIndex< Image< TPixel, VImageDimension > > Superclass
typedef ImageRegion< VImageDimension-1 > VectorImageRegionType
Public Member Functions
void GetVector (PixelVectorType &vec, const int offIndex=0) const
Self & operator= (const Self &it)
void SetVector (const PixelVectorType &value, const int offIndex=0)
typedef (itk::Concept::SameType< ImageType, Image< InternalPixelType, VImageDimension > >) SameTypeCheck
VectorImageRegionIteratorWithIndex ()
VectorImageRegionIteratorWithIndex (const Self &it)
VectorImageRegionIteratorWithIndex (ImageType *ptr, const RegionType &regionInput, int vectorAxis=-1)
~VectorImageRegionIteratorWithIndex ()
Static Public Attributes
static const unsigned int ImageIteratorDimension = VImageDimension
Protected Member Functions
void Initialize (ImageType *ptr, const RegionType &regionInput, int vectorAxis=-1)
Self & operator= (const ImageRegionIteratorWithIndex< ImageType > &it)
VectorImageRegionIteratorWithIndex (const ImageRegionIteratorWithIndex< ImageType > &it)
Protected Attributes
int m_VectorAxis
int m_VectorSize
OffsetValueType m_VectorStride
OffsetValueType m_VolumeSize
Member Typedef Documentation
template<typename TPixel , unsigned int VImageDimension> typedef Superclass::AccessorType itk::VectorImageRegionIteratorWithIndex< Image< TPixel, VImageDimension > >::AccessorType
Definition at line 378 of file itkVectorImageRegionIteratorWithIndex.h.
template<typename TPixel , unsigned int VImageDimension> typedef Superclass::ImageType itk::VectorImageRegionIteratorWithIndex< Image< TPixel, VImageDimension > >::ImageType
Definition at line 373 of file itkVectorImageRegionIteratorWithIndex.h.
template<typename TPixel , unsigned int VImageDimension> typedef Superclass::IndexType itk::VectorImageRegionIteratorWithIndex< Image< TPixel, VImageDimension > >::IndexType
Inherit types from the superclass
Definition at line 369 of file itkVectorImageRegionIteratorWithIndex.h.
template<typename TPixel , unsigned int VImageDimension> typedef Superclass::InternalPixelType itk::VectorImageRegionIteratorWithIndex< Image< TPixel, VImageDimension > >::InternalPixelType
Definition at line 376 of file itkVectorImageRegionIteratorWithIndex.h.
template<typename TPixel , unsigned int VImageDimension> typedef ImageRegion<VImageDimension> itk::VectorImageRegionIteratorWithIndex< Image< TPixel, VImageDimension > >::NDImageRegionType
Definition at line 380 of file itkVectorImageRegionIteratorWithIndex.h.
template<typename TPixel , unsigned int VImageDimension> typedef Superclass::OffsetType itk::VectorImageRegionIteratorWithIndex< Image< TPixel, VImageDimension > >::OffsetType
Definition at line 371 of file itkVectorImageRegionIteratorWithIndex.h.
template<typename TPixel , unsigned int VImageDimension> typedef Superclass::PixelContainer itk::VectorImageRegionIteratorWithIndex< Image< TPixel, VImageDimension > >::PixelContainer
Definition at line 374 of file itkVectorImageRegionIteratorWithIndex.h.
template<typename TPixel , unsigned int VImageDimension> typedef Superclass::PixelContainerPointer itk::VectorImageRegionIteratorWithIndex< Image< TPixel, VImageDimension > >::PixelContainerPointer
Definition at line 375 of file itkVectorImageRegionIteratorWithIndex.h.
template<typename TPixel , unsigned int VImageDimension> typedef Superclass::PixelType itk::VectorImageRegionIteratorWithIndex< Image< TPixel, VImageDimension > >::PixelType
Definition at line 377 of file itkVectorImageRegionIteratorWithIndex.h.
template<typename TPixel , unsigned int VImageDimension> typedef VariableLengthVector< InternalPixelType > itk::VectorImageRegionIteratorWithIndex< Image< TPixel, VImageDimension > >::PixelVectorType
Definition at line 383 of file itkVectorImageRegionIteratorWithIndex.h.
template<typename TPixel , unsigned int VImageDimension> typedef Superclass::RegionType itk::VectorImageRegionIteratorWithIndex< Image< TPixel, VImageDimension > >::RegionType
Definition at line 372 of file itkVectorImageRegionIteratorWithIndex.h.
template<typename TPixel , unsigned int VImageDimension> typedef VectorImageRegionIteratorWithIndex itk::VectorImageRegionIteratorWithIndex< Image< TPixel, VImageDimension > >::Self
Standard class typedefs.
Definition at line 355 of file itkVectorImageRegionIteratorWithIndex.h.
template<typename TPixel , unsigned int VImageDimension> typedef Superclass::SizeType itk::VectorImageRegionIteratorWithIndex< Image< TPixel, VImageDimension > >::SizeType
Definition at line 370 of file itkVectorImageRegionIteratorWithIndex.h.
template<typename TPixel , unsigned int VImageDimension> typedef ImageRegionIteratorWithIndex< Image<TPixel, VImageDimension> > itk::VectorImageRegionIteratorWithIndex< Image< TPixel, VImageDimension > >::Superclass
Define the superclass
Definition at line 366 of file itkVectorImageRegionIteratorWithIndex.h.
template<typename TPixel , unsigned int VImageDimension> typedef ImageRegion<VImageDimension-1> itk::VectorImageRegionIteratorWithIndex< Image< TPixel, VImageDimension > >::VectorImageRegionType
Definition at line 381 of file itkVectorImageRegionIteratorWithIndex.h.
Constructor & Destructor Documentation
template<typename TPixel , unsigned int VImageDimension> itk::VectorImageRegionIteratorWithIndex< Image< TPixel, VImageDimension > >::VectorImageRegionIteratorWithIndex () inline
Default Constructor. Need to provide a default constructor since we provide a copy constructor.
Definition at line 392 of file itkVectorImageRegionIteratorWithIndex.h.
References itk::VectorImageRegionIteratorWithIndex< TImage >::ImageIteratorDimension, itk::VectorImageRegionIteratorWithIndex< TImage >::m_VectorAxis, itk::VectorImageRegionIteratorWithIndex< TImage >::m_VectorSize, and itk::VectorImageRegionIteratorWithIndex< TImage >::m_VectorStride.
template<typename TPixel , unsigned int VImageDimension> itk::VectorImageRegionIteratorWithIndex< Image< TPixel, VImageDimension > >::~VectorImageRegionIteratorWithIndex () inline
Default Destructor
Definition at line 401 of file itkVectorImageRegionIteratorWithIndex.h.
template<typename TPixel , unsigned int VImageDimension> itk::VectorImageRegionIteratorWithIndex< Image< TPixel, VImageDimension > >::VectorImageRegionIteratorWithIndex (const Self & it) inline
Copy Constructor. The copy constructor is provided to make sure the handle to the image is properly reference counted.
Definition at line 405 of file itkVectorImageRegionIteratorWithIndex.h.
References itk::VectorImageRegionIteratorWithIndex< TImage >::m_VectorAxis, itk::VectorImageRegionIteratorWithIndex< TImage >::m_VectorSize, and itk::VectorImageRegionIteratorWithIndex< TImage >::m_VectorStride.
template<typename TPixel , unsigned int VImageDimension> itk::VectorImageRegionIteratorWithIndex< Image< TPixel, VImageDimension > >::VectorImageRegionIteratorWithIndex (ImageType * ptr, const RegionType & regionInput, int vectorAxis = -1) inline
Constructor establishes an iterator to walk a particular image and a particular region of that image.
Definition at line 415 of file itkVectorImageRegionIteratorWithIndex.h.
References itk::VectorImageRegionIteratorWithIndex< TImage >::Initialize().
template<typename TPixel , unsigned int VImageDimension> itk::VectorImageRegionIteratorWithIndex< Image< TPixel, VImageDimension > >::VectorImageRegionIteratorWithIndex (const ImageRegionIteratorWithIndex< ImageType > & it) protected
This constructor is declared protected in order to enforce const-correctness
Member Function Documentation
template<typename TPixel , unsigned int VImageDimension> void itk::VectorImageRegionIteratorWithIndex< Image< TPixel, VImageDimension > >::GetVector (PixelVectorType & vec, const int offIndex = 0) const inline
Get the pixel value. offindex is the coordinate in t-axis, it is only used when m_VectorAxis!=ImageIteratorDimension-1.
Definition at line 453 of file itkVectorImageRegionIteratorWithIndex.h.
References itk::VectorImageRegionIteratorWithIndex< TImage >::m_VectorSize, and itk::VectorImageRegionIteratorWithIndex< TImage >::m_VectorStride.
template<typename TPixel , unsigned int VImageDimension> void itk::VectorImageRegionIteratorWithIndex< Image< TPixel, VImageDimension > >::Initialize (ImageType * ptr, const RegionType & regionInput, int vectorAxis = -1) inline protected
Definition at line 467 of file itkVectorImageRegionIteratorWithIndex.h.
References itk::VectorImageRegionIteratorWithIndex< TImage >::ImageIteratorDimension, itk::VectorImageRegionIteratorWithIndex< TImage >::m_VectorAxis, itk::VectorImageRegionIteratorWithIndex< TImage >::m_VectorSize, itk::VectorImageRegionIteratorWithIndex< TImage >::m_VectorStride, itk::VectorImageRegionIteratorWithIndex< TImage >::operator=(), and itk::VectorImageRegionIteratorWithIndex< TImage >::VectorImageRegionIteratorWithIndex().
template<typename TPixel , unsigned int VImageDimension> Self& itk::VectorImageRegionIteratorWithIndex< Image< TPixel, VImageDimension > >::operator= (const Self & it) inline
operator= is provided to make sure the handle to the image is properly reference counted.
Definition at line 429 of file itkVectorImageRegionIteratorWithIndex.h.
References itk::VectorImageRegionIteratorWithIndex< TImage >::m_VectorAxis, itk::VectorImageRegionIteratorWithIndex< TImage >::m_VectorSize, and itk::VectorImageRegionIteratorWithIndex< TImage >::m_VectorStride.
template<typename TPixel , unsigned int VImageDimension> Self& itk::VectorImageRegionIteratorWithIndex< Image< TPixel, VImageDimension > >::operator= (const ImageRegionIteratorWithIndex< ImageType > & it) protected
template<typename TPixel , unsigned int VImageDimension> void itk::VectorImageRegionIteratorWithIndex< Image< TPixel, VImageDimension > >::SetVector (const PixelVectorType & value, const int offIndex = 0) inline
Set the pixel value. offindex is the coordinate in t-axis, it is only used when m_VectorAxis!=ImageIteratorDimension-1.
Definition at line 441 of file itkVectorImageRegionIteratorWithIndex.h.
References itk::VectorImageRegionIteratorWithIndex< TImage >::m_VectorSize, and itk::VectorImageRegionIteratorWithIndex< TImage >::m_VectorStride.
template<typename TPixel , unsigned int VImageDimension> itk::VectorImageRegionIteratorWithIndex< Image< TPixel, VImageDimension > >::typedef (itk::Concept::SameType< ImageType, Image< InternalPixelType, VImageDimension > >)
This class requires SameTypeCheck in the form of (itk::Concept::SameType< ImageType, Image<InternalPixelType, VImageDimension> >)
Member Data Documentation
template<typename TPixel , unsigned int VImageDimension> const unsigned int itk::VectorImageRegionIteratorWithIndex< Image< TPixel, VImageDimension > >::ImageIteratorDimension = VImageDimension static
Dimension of the image the iterator walks. This constant is needed so functions that are templated over image iterator type (as opposed to being templated over pixel type and dimension) can have compile time access to the dimension of the image that the iterator walks.
Definition at line 363 of file itkVectorImageRegionIteratorWithIndex.h.
template<typename TPixel , unsigned int VImageDimension> int itk::VectorImageRegionIteratorWithIndex< Image< TPixel, VImageDimension > >::m_VectorAxis protected
Definition at line 576 of file itkVectorImageRegionIteratorWithIndex.h.
template<typename TPixel , unsigned int VImageDimension> int itk::VectorImageRegionIteratorWithIndex< Image< TPixel, VImageDimension > >::m_VectorSize protected
Definition at line 575 of file itkVectorImageRegionIteratorWithIndex.h.
template<typename TPixel , unsigned int VImageDimension> OffsetValueType itk::VectorImageRegionIteratorWithIndex< Image< TPixel, VImageDimension > >::m_VectorStride protected
Definition at line 574 of file itkVectorImageRegionIteratorWithIndex.h.
template<typename TPixel , unsigned int VImageDimension> OffsetValueType itk::VectorImageRegionIteratorWithIndex< Image< TPixel, VImageDimension > >::m_VolumeSize protected
Definition at line 573 of file itkVectorImageRegionIteratorWithIndex.h.
The documentation for this class was generated from the following file:
Modules/Common/include/itkVectorImageRegionIteratorWithIndex.h