DMRITool: utl::NDArray< T, 1 > Class Template Reference
utl::NDArray< T, 1 > Class Template Reference
Utl » UtlNDArray | Math
#include <utlVector.h>
Detailed Description
template<class T>
class utl::NDArray< T, 1 >
NDArray<T,1> is a vector class which uses blas mkl.
Author
Jian Cheng
Date
08-22-2014
Definition at line 36 of file utlVector.h.
Public Types
typedef Superclass::ConstIterator ConstIterator
typedef Superclass::ConstPointer ConstPointer
typedef Superclass::ConstReference ConstReference
typedef Superclass::Iterator Iterator
typedef Superclass::Pointer Pointer
typedef Superclass::Reference Reference
typedef Superclass::ScalarValueType ScalarValueType
typedef NDArray Self
typedef Superclass::ShapeType ShapeType
typedef Superclass::SizeType SizeType
typedef NDArrayBase< T, 1 > Superclass
typedef Superclass::ValueType ValueType
Public Types inherited from utl::NDArrayBase< T, 1 >
enum
typedef const ValueType * ConstIterator
typedef const ValueType * ConstPointer
typedef const ValueType & ConstReference
typedef ValueType * Iterator
typedef ValueType * Pointer
typedef ValueType & Reference
typedef utl::remove_complex_t< T > ScalarValueType
typedef NDArrayBase Self
typedef Superclass::ShapeType ShapeType
typedef Superclass::SizeType SizeType
typedef Expr< NDArrayBase< T, Dim >, T > Superclass
typedef T ValueType
Public Types inherited from utl::Expr< NDArrayBase< T, Dim >, T >
typedef SizeType const * ShapeType
typedef unsigned int SizeType
typedef T ValueType
Public Member Functions
void CopyData (T *const data, const SizeType size)
void GetDiagonalMatrix (NDArray< T, 2 > &mat) const
NDArray< T, 2 > GetDiagonalMatrix () const
NDArray< T, 1 > GetRotateAxis (const double alpha, const NDArray< T, 1 > &axis)
void GetSubVector (const std::vector< int > &indexVec, NDArray< T, 1 > &vec) const
NDArray< T, 1 > GetSubVector (const std::vector< int > &indexVec) const
NDArray ()
NDArray (const unsigned int size)
NDArray (const int size)
NDArray (const std::vcl_size_t size)
NDArray (const long size)
NDArray (const NDArray< T, 1 > &vec)
NDArray (NDArray< T, 1 > &&vec)
NDArray (const std::initializer_list< T > &r)
template<typename EType >
NDArray (const Expr< EType, typename EType::ValueType > &expr)
NDArray (const T *vec, const SizeType size)
NDArray (const SizeType size, const T r)
template<typename TVectorValueType >
NDArray (const NDArray< TVectorValueType, 1 > &r)
NDArray (const ShapeType &shape)
NDArray (const T *vec, const ShapeType &shape)
NDArray (const ShapeType &shape, const T r)
Reference operator() (unsigned long index)
ConstReference operator() (unsigned long index) const
Reference operator() (long index)
ConstReference operator() (long index) const
Reference operator() (int index)
ConstReference operator() (int index) const
Reference operator() (unsigned int index)
ConstReference operator() (unsigned int index) const
NDArray< T, 1 > & operator= (NDArray< T, 1 > &r)
NDArray< T, 1 > & operator= (NDArray< T, 1 > &&r)
void PostMultiply (const NDArray< T, 2 > &mat, NDArray< T, 1 > &vec)
void PreMultiply (const NDArray< T, 2 > &mat, NDArray< T, 1 > &vec)
bool ReSize (const SizeType size)
void RotateAxis (const double alpha, const NDArray< T, 1 > &axis)
void SetData (T *const data, const SizeType size)
NDArray< T, 1 > & SetSubVector (const std::vector< int > indexVec, const NDArray< T, 1 > &vec)
Public Member Functions inherited from utl::NDArrayBase< T, 1 >
__Array_Saver_Scalar (+=) __Array_Saver_Scalar(-
T AbsoluteMaxValue () const
T AbsoluteMinValue () const
void Apply (const FuncT &func, NDArrayBase< T, Dim > &vec) const
void Apply (T(*f)(T), NDArrayBase< T, Dim > &vec) const
void Apply (T(*f)(T const &), NDArrayBase< T, Dim > &vec) const
unsigned ArgAbsoluteMax () const
unsigned ArgAbsoluteMin () const
unsigned ArgMax () const
unsigned ArgMin () const
Reference Back ()
ConstReference Back () const
Iterator Begin ()
ConstIterator Begin () const
ConstIterator cBegin () const
ConstIterator cEnd () const
void Clear ()
void CopyData (T *const data, const ShapeType &shape)
NDArrayBase< T, Dim > & CopyIn (T const *ptr, const int size, const int start=0)
void CopyOut (T *ptr, const int size, const int start=0) const
ConstReverseIterator crBegin () const
ConstReverseIterator crEnd () const
NDArrayBase< T, Dim > & ElementAbsolute (T *outVec=NULL)
NDArrayBase< T, Dim > & ElementAbsolute (NDArrayBase< T, Dim > &vec)
NDArrayBase< T, Dim > & ElementAdd (T *const vec, T *outVec=NULL)
NDArrayBase< T, Dim > & ElementAxpby (T *const vec, const T alpha, const T beta)
NDArrayBase< T, Dim > & ElementCos (T *outVec=NULL)
NDArrayBase< T, Dim > & ElementCos (NDArrayBase< T, Dim > &vec)
NDArrayBase< T, Dim > & ElementDivide (T *const vec, T *outVec=NULL)
NDArrayBase< T, Dim > & ElementExp (T *outVec=NULL)
NDArrayBase< T, Dim > & ElementExp (NDArrayBase< T, Dim > &vec)
NDArrayBase< T, Dim > & ElementInverse (T *outVec=NULL)
NDArrayBase< T, Dim > & ElementInverse (NDArrayBase< T, Dim > &vec)
NDArrayBase< T, Dim > & ElementMultiply (T *const vec, T *outVec=NULL)
NDArrayBase< T, Dim > & ElementSin (T *outVec=NULL)
NDArrayBase< T, Dim > & ElementSin (NDArrayBase< T, Dim > &vec)
NDArrayBase< T, Dim > & ElementSqrt (T *outVec=NULL)
NDArrayBase< T, Dim > & ElementSqrt (NDArrayBase< T, Dim > &vec)
NDArrayBase< T, Dim > & ElementSquare (T *outVec=NULL)
NDArrayBase< T, Dim > & ElementSquare (NDArrayBase< T, Dim > &vec)
NDArrayBase< T, Dim > & ElementSubstract (T *const vec, T *outVec=NULL)
Iterator End ()
ConstIterator End () const
T Eval (int i) const
void Fill (const T &value)
NDArrayBase< T, Dim > & Flip ()
T * GetData ()
const T * GetData () const
ConstReference GetElement (unsigned short index) const
NDArrayBase< T, Dim > GetElementAbsolute () const
NDArrayBase< T, Dim > GetElementCos () const
NDArrayBase< T, Dim > GetElementExp () const
NDArrayBase< T, Dim > GetElementInverse () const
NDArrayBase< T, Dim > GetElementSin () const
NDArrayBase< T, Dim > GetElementSqrt () const
NDArrayBase< T, Dim > GetElementSquare () const
void GetIndex (const SizeType offset, SizeType index[Dimension]) const
double GetInfNorm () const
bool GetIsShared () const
T GetMean () const
T GetMedian () const
SizeType GetOffset (const ShapeType &shapeIndex) const
const SizeType * GetOffSetTable () const
double GetOneNorm () const
NDArray< T, SubDimension > GetRefSubArray (const int i) const
NDArray< T, Dim > GetRefSubArray (const int istart, const int iend) const
double GetRootMeanSquares () const
const ShapeType GetShape () const
SizeType GetSize () const
double GetSquaredTwoNorm () const
T GetSum () const
double GetTwoNorm () const
int GetZeroNorm (const double eps=1e-10) const
void HardThreshold (const double threshold)
ValueType InnerProduct (const NDArrayBase< T, Dim > &vec) const
bool IsEmpty () const
bool IsEqual (const NDArrayBase< T, Dim > &r, const double eps) const
bool IsSameShape (const EType &src) const
bool IsSameShape (const ShapeType &shape) const
bool IsSameSize (const ShapeType &shape) const
bool IsSameValues (const NDArrayBase< T, Dim > &r, const double eps) const
bool IsZero () const
T MaxValue () const
T MinValue () const
NDArrayBase ()
NDArrayBase (const ShapeType &shape)
NDArrayBase (const NDArrayBase< T, Dim > &vec)
NDArrayBase (NDArrayBase< T, Dim > &&vec)
NDArrayBase (const Expr< EType, typename EType::ValueType > &expr)
NDArrayBase (const T *vec, const ShapeType &shape)
NDArrayBase (const ShapeType &shape, const T r)
NDArrayBase (const NDArrayBase< TValue, Dim > &r)
int NNZ (const double eps=1e-10) const
NDArrayBase< T, Dim > & operator saver (const T val)
bool operator!= (const NDArrayBase< T, Dim > &r) const
NDArrayBase< T, Dim > & operator%= (const Expr< EType, typename EType::ValueType > &src)
NDArrayBase< T, Dim > & operator%= (const NDArrayBase< T, Dim > &vec)
NDArrayBase< T, Dim > & operator%= (const T val)
Reference operator() (const ShapeType &shape)
ConstReference operator() (const ShapeType &shape) const
NDArrayBase< T, Dim > & operator+= (const Expr< EType, typename EType::ValueType > &src)
NDArrayBase< T, Dim > & operator+= (const NDArrayBase< T, Dim > &vec)
NDArrayBase< T, Dim > & operator-= (const Expr< EType, typename EType::ValueType > &src)
NDArrayBase< T, Dim > & operator-= (const NDArrayBase< T, Dim > &vec)
NDArrayBase< T, Dim > & operator/= (const Expr< EType, typename EType::ValueType > &src)
NDArrayBase< T, Dim > & operator/= (const NDArrayBase< T, Dim > &vec)
NDArrayBase< T, Dim > & operator/= (const T val)
NDArrayBase< T, Dim > & operator= (const Expr< EType, typename EType::ValueType > &src)
Dim & operator= (const NDArrayBase< T, Dim > &r)
NDArrayBase< T, Dim > & operator= (NDArrayBase< T, Dim > &&r)
NDArrayBase< T, Dim > & operator= (const NDArrayBase< TValueType, Dim > &r)
NDArrayBase< T, Dim > & operator= (const std::initializer_list< T > &r)
NDArrayBase< T, Dim > & operator= (const std::vector< T > &r)
NDArrayBase< T, Dim > & operator= (const T r)
bool operator== (const NDArrayBase< T, Dim > &r) const
Reference operator[] (short index)
ConstReference operator[] (short index) const
Reference operator[] (unsigned short index)
ConstReference operator[] (unsigned short index) const
Reference operator[] (int index)
ConstReference operator[] (int index) const
Reference operator[] (unsigned int index)
ConstReference operator[] (unsigned int index) const
Reference operator[] (long index)
ConstReference operator[] (long index) const
Reference operator[] (unsigned long index)
ConstReference operator[] (unsigned long index) const
Reference operator[] (long long index)
ConstReference operator[] (long long index) const
Reference operator[] (unsigned long long index)
ConstReference operator[] (unsigned long long index) const
void Print (std::ostream &os, const char *separate=" ") const
void PrintInfo (std::ostream &os, const char *separate=" ") const
void PrintWithIndex (std::ostream &os, const char *separate=" ") const
ReverseIterator rBegin ()
ConstReverseIterator rBegin () const
ReverseIterator rEnd ()
ConstReverseIterator rEnd () const
NDArrayBase< T, Dim > & ReShape (const ShapeType &shape)
bool ReSize (const ShapeType &shape)
NDArrayBase< T, Dim > & Scale (const T a)
void SetData (T *const data, const ShapeType &shape)
void SetElement (unsigned short index, ConstReference value)
SizeType Size () const
void SoftThreshold (const double threshold)
void Swap (NDArrayBase< T, Dim > &vec)
~NDArrayBase ()
Public Member Functions inherited from utl::Expr< NDArrayBase< T, Dim >, T >
const NDArrayBase< T, Dim > & ConstRef (void) const
const ShapeType GetShape () const
NDArrayBase< T, Dim > & Ref (void)
Additional Inherited Members
Static Public Member Functions inherited from utl::NDArrayBase< T, 1 >
static constexpr SizeType GetDimension ()
Static Public Member Functions inherited from utl::Expr< NDArrayBase< T, Dim >, T >
static SizeType GetDimension ()
Static Public Attributes inherited from utl::NDArrayBase< T, 1 >
static constexpr SizeType SubDimension
Protected Member Functions inherited from utl::NDArrayBase< T, 1 >
void ClearData ()
void ClearShape ()
void ComputeOffSetTable ()
Protected Attributes inherited from utl::NDArrayBase< T, 1 >
T * m_Data
bool m_IsShared
SizeType m_OffSetTable [Dimension]
SizeType m_Shape [Dimension]
Member Typedef Documentation
template<class T> typedef Superclass::ConstIterator utl::NDArray< T, 1 >::ConstIterator
Definition at line 51 of file utlVector.h.
template<class T> typedef Superclass::ConstPointer utl::NDArray< T, 1 >::ConstPointer
Definition at line 53 of file utlVector.h.
template<class T> typedef Superclass::ConstReference utl::NDArray< T, 1 >::ConstReference
Definition at line 55 of file utlVector.h.
template<class T> typedef Superclass::Iterator utl::NDArray< T, 1 >::Iterator
Definition at line 50 of file utlVector.h.
template<class T> typedef Superclass::Pointer utl::NDArray< T, 1 >::Pointer
Definition at line 52 of file utlVector.h.
template<class T> typedef Superclass::Reference utl::NDArray< T, 1 >::Reference
Definition at line 54 of file utlVector.h.
template<class T> typedef Superclass::ScalarValueType utl::NDArray< T, 1 >::ScalarValueType
Definition at line 45 of file utlVector.h.
template<class T> typedef NDArray utl::NDArray< T, 1 >::Self
Definition at line 41 of file utlVector.h.
template<class T> typedef Superclass::ShapeType utl::NDArray< T, 1 >::ShapeType
Definition at line 48 of file utlVector.h.
template<class T> typedef Superclass::SizeType utl::NDArray< T, 1 >::SizeType
Definition at line 47 of file utlVector.h.
template<class T> typedef NDArrayBase<T,1> utl::NDArray< T, 1 >::Superclass
Definition at line 42 of file utlVector.h.
template<class T> typedef Superclass::ValueType utl::NDArray< T, 1 >::ValueType
Definition at line 44 of file utlVector.h.
Constructor & Destructor Documentation
template<class T> utl::NDArray< T, 1 >::NDArray () inline
Default constructor uses compiler's default initialization of memory. For efficiency, no initialization to zero is done.
Definition at line 76 of file utlVector.h.
template<class T> utl::NDArray< T, 1 >::NDArray (const unsigned int size) inline explicit
Definition at line 87 of file utlVector.h.
template<class T> utl::NDArray< T, 1 >::NDArray (const int size) inline explicit
Definition at line 88 of file utlVector.h.
template<class T> utl::NDArray< T, 1 >::NDArray (const std::vcl_size_t size) inline explicit
Definition at line 89 of file utlVector.h.
template<class T> utl::NDArray< T, 1 >::NDArray (const long size) inline explicit
Definition at line 90 of file utlVector.h.
template<class T> utl::NDArray< T, 1 >::NDArray (const NDArray< T, 1 > & vec) inline
Definition at line 94 of file utlVector.h.
template<class T> utl::NDArray< T, 1 >::NDArray (NDArray< T, 1 > && vec) inline
Definition at line 96 of file utlVector.h.
References utl::NDArray< T, Dim >::operator=().
template<class T> utl::NDArray< T, 1 >::NDArray (const std::initializer_list< T > & r) inline
Definition at line 101 of file utlVector.h.
References utl::cblas_copy(), utl::NDArrayBase< T, Dim >::m_Data, utl::NDArrayBase< T, Dim >::ReSize(), and utl::NDArrayBase< T, Dim >::Size().
template<class T> template<typename EType > utl::NDArray< T, 1 >::NDArray (const Expr< EType, typename EType::ValueType > & expr) inline
Definition at line 108 of file utlVector.h.
template<class T> utl::NDArray< T, 1 >::NDArray (const T * vec, const SizeType size) inline
Constructor assumes input points to array of correct size. Values are copied individually instead of with a binary copy. This allows the T's assignment operator to be executed.
Definition at line 117 of file utlVector.h.
References __utl_ndarray_alloc_blah, utl::NDArrayBase< T, Dim >::m_Data, and utl::NDArrayBase< T, Dim >::Size().
template<class T> utl::NDArray< T, 1 >::NDArray (const SizeType size, const T r) inline
Constructor to initialize entire array to one value.
Definition at line 128 of file utlVector.h.
References __utl_ndarray_alloc_blah, and utl::NDArrayBase< T, Dim >::Fill().
template<class T> template<typename TVectorValueType > utl::NDArray< T, 1 >::NDArray (const NDArray< TVectorValueType, 1 > & r) inline
Definition at line 137 of file utlVector.h.
template<class T> utl::NDArray< T, 1 >::NDArray (const ShapeType & shape) inline explicit
Definition at line 141 of file utlVector.h.
template<class T> utl::NDArray< T, 1 >::NDArray (const T * vec, const ShapeType & shape) inline
Definition at line 143 of file utlVector.h.
template<class T> utl::NDArray< T, 1 >::NDArray (const ShapeType & shape, const T r) inline
Constructor to initialize entire array to one value.
Definition at line 148 of file utlVector.h.
Member Function Documentation
template<class T> void utl::NDArray< T, 1 >::CopyData (T *const data, const SizeType size) inline
copy m_Data from data
Definition at line 160 of file utlVector.h.
References utl::NDArrayBase< T, Dim >::CopyData().
template<class T> void utl::NDArray< T, 1 >::GetDiagonalMatrix (NDArray< T, 2 > & mat) const inline
Definition at line 264 of file utlVector.h.
References utl::NDArrayBase< T, Dim >::Fill(), utl::NDArray< T, 2 >::ReSize(), utl::NDArray< T, 2 >::SetDiagonal(), and utl::NDArrayBase< T, Dim >::Size().
Referenced by utl::NDArray< T, 2 >::ExpM(), and utl::NDArray< T, 2 >::LogM().
template<class T> NDArray<T,2> utl::NDArray< T, 1 >::GetDiagonalMatrix () const inline
Definition at line 270 of file utlVector.h.
References utl::GetDiagonalMatrix(), and utl::NDArrayBase< T, Dim >::Size().
template<class T> NDArray<T,1> utl::NDArray< T, 1 >::GetRotateAxis (const double alpha, const NDArray< T, 1 > & axis) inline
rotate *this about axis by angle alpha anticlockwise in 3d space. https://en.wikipedia.org/wiki/Rodrigues'_rotation_formula
Definition at line 233 of file utlVector.h.
References utl::CrossProduct(), utl::DotProduct(), utl::NDArrayBase< T, Dim >::Scale(), utl::NDArrayBase< T, Dim >::Size(), and utlException.
template<class T> void utl::NDArray< T, 1 >::GetSubVector (const std::vector< int > & indexVec, NDArray< T, 1 > & vec) const inline
Definition at line 277 of file utlVector.h.
References utl::NDArrayBase< T, Dim >::m_Data, and ReSize().
template<class T> NDArray<T,1> utl::NDArray< T, 1 >::GetSubVector (const std::vector< int > & indexVec) const inline
Definition at line 283 of file utlVector.h.
template<class T> Reference utl::NDArray< T, 1 >::operator() (unsigned long index) inline
Note
The separate versions are a work-around to avoid ambiguity for operator()(const ShapeType& shape), when converting an integer number is needed.
Definition at line 201 of file utlVector.h.
References utl::NDArrayBase< T, Dim >::m_Data.
template<class T> ConstReference utl::NDArray< T, 1 >::operator() (unsigned long index) const inline
Definition at line 202 of file utlVector.h.
References utl::NDArrayBase< T, Dim >::m_Data.
template<class T> Reference utl::NDArray< T, 1 >::operator() (long index) inline
Definition at line 203 of file utlVector.h.
References utl::NDArrayBase< T, Dim >::m_Data.
template<class T> ConstReference utl::NDArray< T, 1 >::operator() (long index) const inline
Definition at line 204 of file utlVector.h.
References utl::NDArrayBase< T, Dim >::m_Data.
template<class T> Reference utl::NDArray< T, 1 >::operator() (int index) inline
Definition at line 205 of file utlVector.h.
References utl::NDArrayBase< T, Dim >::m_Data.
template<class T> ConstReference utl::NDArray< T, 1 >::operator() (int index) const inline
Definition at line 206 of file utlVector.h.
References utl::NDArrayBase< T, Dim >::m_Data.
template<class T> Reference utl::NDArray< T, 1 >::operator() (unsigned int index) inline
Definition at line 207 of file utlVector.h.
References utl::NDArrayBase< T, Dim >::m_Data.
template<class T> ConstReference utl::NDArray< T, 1 >::operator() (unsigned int index) const inline
Definition at line 208 of file utlVector.h.
References utl::NDArrayBase< T, Dim >::m_Data.
template<class T> NDArray<T,1>& utl::NDArray< T, 1 >::operator= (NDArray< T, 1 > & r) inline
Definition at line 214 of file utlVector.h.
References utl::NDArrayBase< T, Dim >::operator=().
template<class T> NDArray<T,1>& utl::NDArray< T, 1 >::operator= (NDArray< T, 1 > && r) inline
Definition at line 220 of file utlVector.h.
References utl::NDArrayBase< T, Dim >::Clear(), and utl::NDArrayBase< T, Dim >::Swap().
template<class T> void utl::NDArray< T, 1 >::PostMultiply (const NDArray< T, 2 > & mat, NDArray< T, 1 > & vec) inline
Definition at line 259 of file utlVector.h.
References utl::ProductUtlvM().
template<class T> void utl::NDArray< T, 1 >::PreMultiply (const NDArray< T, 2 > & mat, NDArray< T, 1 > & vec) inline
vec = mat * (*this), considering *this is a column vector.
Definition at line 254 of file utlVector.h.
References utl::ProductUtlMv().
template<class T> bool utl::NDArray< T, 1 >::ReSize (const SizeType size) inline
Definition at line 167 of file utlVector.h.
References utl::NDArrayBase< T, Dim >::ReSize().
Referenced by utl::Convert2To1Tensor(), utl::gesvd_UtlMatrix(), utl::NDArray< T, 2 >::GetDiagonal(), GetSubVector(), utl::GetUtlVectorFromMXArray(), utl::RotationMatrixToAxisAngle(), utl::syev_UtlMatrix(), utl::syevd_UtlMatrix(), and spams::VectorToUtlVector().
template<class T> void utl::NDArray< T, 1 >::RotateAxis (const double alpha, const NDArray< T, 1 > & axis) inline
Definition at line 247 of file utlVector.h.
template<class T> void utl::NDArray< T, 1 >::SetData (T *const data, const SizeType size) inline
set m_Data from data, the ownership is in data.
Definition at line 152 of file utlVector.h.
References utl::NDArrayBase< T, Dim >::SetData().
template<class T> NDArray<T,1>& utl::NDArray< T, 1 >::SetSubVector (const std::vector< int > indexVec, const NDArray< T, 1 > & vec) inline
Definition at line 290 of file utlVector.h.
References utl::NDArrayBase< T, Dim >::m_Data.
The documentation for this class was generated from the following file:
Modules/HelperFunctions/include/utlVector.h