DMRITool: itk::MultiVolumeImageToVectorImageFilter< TInputPixelType, TOutputPixelType, VImageDimension > Class Template Reference
itk::MultiVolumeImageToVectorImageFilter< TInputPixelType, TOutputPixelType, VImageDimension > Class Template Reference
#include <itkMultiVolumeImageToVectorImageFilter.h>
Detailed Description
template<class TInputPixelType, class TOutputPixelType, unsigned int VImageDimension = 3>
class itk::MultiVolumeImageToVectorImageFilter< TInputPixelType, TOutputPixelType, VImageDimension >
convert Image<TInputPixelType, VImageDimension+1> to VectorImage<TOutputPixelType, VImageDimension>
Author
Jian Cheng (JC), jian..nosp@m.chen.nosp@m.g.198.nosp@m.3@gm.nosp@m.ail.c.nosp@m.om
Definition at line 34 of file itkMultiVolumeImageToVectorImageFilter.h.
Public Types
typedef SmartPointer< const Self > ConstPointer
typedef InputImageType::ConstPointer InputImageConstPointer
typedef InputImageType::PixelType InputImagePixelType
typedef InputImageType::Pointer InputImagePointer
typedef InputImageType::RegionType InputImageRegionType
typedef Image< TInputPixelType, MultiVolumeImageDimension > InputImageType
typedef OutputImageType::PixelType OutputImagePixelType
typedef OutputImageType::Pointer OutputImagePointer
typedef VectorImage< TOutputPixelType, VectorImageDimension > OutputImageType
typedef SmartPointer< Self > Pointer
typedef MultiVolumeImageToVectorImageFilter Self
typedef ImageToImageFilter< InputImageType, OutputImageType > Superclass
Public Member Functions
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual const char * GetNameOfClass () const
Static Public Member Functions
static Pointer New ()
Static Public Attributes
static const unsigned int MultiVolumeImageDimension = VImageDimension+1
static const unsigned int VectorImageDimension = VImageDimension
Protected Member Functions
virtual void GenerateData () ITK_OVERRIDE
virtual void GenerateOutputInformation () ITK_OVERRIDE
MultiVolumeImageToVectorImageFilter ()
void PrintSelf (std::ostream &os, Indent indent) const ITK_OVERRIDE
virtual ~MultiVolumeImageToVectorImageFilter ()
Private Member Functions
MultiVolumeImageToVectorImageFilter (const Self &)
void operator= (const Self &)
Member Typedef Documentation
template<class TInputPixelType , class TOutputPixelType , unsigned int VImageDimension = 3> typedef SmartPointer<const Self> itk::MultiVolumeImageToVectorImageFilter< TInputPixelType, TOutputPixelType, VImageDimension >::ConstPointer
Definition at line 50 of file itkMultiVolumeImageToVectorImageFilter.h.
template<class TInputPixelType , class TOutputPixelType , unsigned int VImageDimension = 3> typedef InputImageType::ConstPointer itk::MultiVolumeImageToVectorImageFilter< TInputPixelType, TOutputPixelType, VImageDimension >::InputImageConstPointer
Definition at line 60 of file itkMultiVolumeImageToVectorImageFilter.h.
template<class TInputPixelType , class TOutputPixelType , unsigned int VImageDimension = 3> typedef InputImageType::PixelType itk::MultiVolumeImageToVectorImageFilter< TInputPixelType, TOutputPixelType, VImageDimension >::InputImagePixelType
Definition at line 62 of file itkMultiVolumeImageToVectorImageFilter.h.
template<class TInputPixelType , class TOutputPixelType , unsigned int VImageDimension = 3> typedef InputImageType::Pointer itk::MultiVolumeImageToVectorImageFilter< TInputPixelType, TOutputPixelType, VImageDimension >::InputImagePointer
Definition at line 56 of file itkMultiVolumeImageToVectorImageFilter.h.
template<class TInputPixelType , class TOutputPixelType , unsigned int VImageDimension = 3> typedef InputImageType::RegionType itk::MultiVolumeImageToVectorImageFilter< TInputPixelType, TOutputPixelType, VImageDimension >::InputImageRegionType
Definition at line 61 of file itkMultiVolumeImageToVectorImageFilter.h.
template<class TInputPixelType , class TOutputPixelType , unsigned int VImageDimension = 3> typedef Image<TInputPixelType,MultiVolumeImageDimension> itk::MultiVolumeImageToVectorImageFilter< TInputPixelType, TOutputPixelType, VImageDimension >::InputImageType
Definition at line 43 of file itkMultiVolumeImageToVectorImageFilter.h.
template<class TInputPixelType , class TOutputPixelType , unsigned int VImageDimension = 3> typedef OutputImageType::PixelType itk::MultiVolumeImageToVectorImageFilter< TInputPixelType, TOutputPixelType, VImageDimension >::OutputImagePixelType
Definition at line 65 of file itkMultiVolumeImageToVectorImageFilter.h.
template<class TInputPixelType , class TOutputPixelType , unsigned int VImageDimension = 3> typedef OutputImageType::Pointer itk::MultiVolumeImageToVectorImageFilter< TInputPixelType, TOutputPixelType, VImageDimension >::OutputImagePointer
Definition at line 64 of file itkMultiVolumeImageToVectorImageFilter.h.
template<class TInputPixelType , class TOutputPixelType , unsigned int VImageDimension = 3> typedef VectorImage<TOutputPixelType,VectorImageDimension> itk::MultiVolumeImageToVectorImageFilter< TInputPixelType, TOutputPixelType, VImageDimension >::OutputImageType
Definition at line 44 of file itkMultiVolumeImageToVectorImageFilter.h.
template<class TInputPixelType , class TOutputPixelType , unsigned int VImageDimension = 3> typedef SmartPointer<Self> itk::MultiVolumeImageToVectorImageFilter< TInputPixelType, TOutputPixelType, VImageDimension >::Pointer
Definition at line 49 of file itkMultiVolumeImageToVectorImageFilter.h.
template<class TInputPixelType , class TOutputPixelType , unsigned int VImageDimension = 3> typedef MultiVolumeImageToVectorImageFilter itk::MultiVolumeImageToVectorImageFilter< TInputPixelType, TOutputPixelType, VImageDimension >::Self
Standard class typedefs.
Definition at line 47 of file itkMultiVolumeImageToVectorImageFilter.h.
template<class TInputPixelType , class TOutputPixelType , unsigned int VImageDimension = 3> typedef ImageToImageFilter<InputImageType,OutputImageType> itk::MultiVolumeImageToVectorImageFilter< TInputPixelType, TOutputPixelType, VImageDimension >::Superclass
Definition at line 48 of file itkMultiVolumeImageToVectorImageFilter.h.
Constructor & Destructor Documentation
template<class TInputPixelType , class TOutputPixelType , unsigned int VImageDimension = 3> itk::MultiVolumeImageToVectorImageFilter< TInputPixelType, TOutputPixelType, VImageDimension >::MultiVolumeImageToVectorImageFilter () inline protected
Definition at line 68 of file itkMultiVolumeImageToVectorImageFilter.h.
template<class TInputPixelType , class TOutputPixelType , unsigned int VImageDimension = 3> virtual itk::MultiVolumeImageToVectorImageFilter< TInputPixelType, TOutputPixelType, VImageDimension >::~MultiVolumeImageToVectorImageFilter () inline protected virtual
Definition at line 69 of file itkMultiVolumeImageToVectorImageFilter.h.
References ITK_OVERRIDE.
template<class TInputPixelType , class TOutputPixelType , unsigned int VImageDimension = 3> itk::MultiVolumeImageToVectorImageFilter< TInputPixelType, TOutputPixelType, VImageDimension >::MultiVolumeImageToVectorImageFilter (const Self &) private
Member Function Documentation
template<class TInputPixelType , class TOutputPixelType , unsigned int VImageDimension = 3> virtual::itk::LightObject::Pointer itk::MultiVolumeImageToVectorImageFilter< TInputPixelType, TOutputPixelType, VImageDimension >::CreateAnother (void) const
template<class TInputPixelType , class TOutputPixelType , unsigned int VImageDimension> void itk::MultiVolumeImageToVectorImageFilter< TInputPixelType, TOutputPixelType, VImageDimension >::GenerateData (void) protected virtual
Does the real work.
Definition at line 44 of file itkMultiVolumeImageToVectorImageFilter.hxx.
References itk::MultiVolumeImageToVectorImageFilter< TInputPixelType, TOutputPixelType, VImageDimension >::PrintSelf().
Referenced by itk::MultiVolumeImageToVectorImageFilter< TInputPixelType, TOutputPixelType, VImageDimension >::GenerateOutputInformation().
template<class TInputPixelType , class TOutputPixelType , unsigned int VImageDimension> void itk::MultiVolumeImageToVectorImageFilter< TInputPixelType, TOutputPixelType, VImageDimension >::GenerateOutputInformation (void) protected virtual
Definition at line 32 of file itkMultiVolumeImageToVectorImageFilter.hxx.
References itk::MultiVolumeImageToVectorImageFilter< TInputPixelType, TOutputPixelType, VImageDimension >::GenerateData().
template<class TInputPixelType , class TOutputPixelType , unsigned int VImageDimension = 3> virtual const char* itk::MultiVolumeImageToVectorImageFilter< TInputPixelType, TOutputPixelType, VImageDimension >::GetNameOfClass () const virtual
Run-time type information (and related methods)
template<class TInputPixelType , class TOutputPixelType , unsigned int VImageDimension = 3> static Pointer itk::MultiVolumeImageToVectorImageFilter< TInputPixelType, TOutputPixelType, VImageDimension >::New () static
Method for creation through the object factory.
template<class TInputPixelType , class TOutputPixelType , unsigned int VImageDimension = 3> void itk::MultiVolumeImageToVectorImageFilter< TInputPixelType, TOutputPixelType, VImageDimension >::operator= (const Self &) private
template<class TInputPixelType , class TOutputPixelType , unsigned int VImageDimension> void itk::MultiVolumeImageToVectorImageFilter< TInputPixelType, TOutputPixelType, VImageDimension >::PrintSelf (std::ostream & os, Indent indent) const protected
Definition at line 79 of file itkMultiVolumeImageToVectorImageFilter.hxx.
References PrintVar1.
Referenced by itk::MultiVolumeImageToVectorImageFilter< TInputPixelType, TOutputPixelType, VImageDimension >::GenerateData().
Member Data Documentation
template<class TInputPixelType , class TOutputPixelType , unsigned int VImageDimension = 3> const unsigned int itk::MultiVolumeImageToVectorImageFilter< TInputPixelType, TOutputPixelType, VImageDimension >::MultiVolumeImageDimension = VImageDimension+1 static
Definition at line 41 of file itkMultiVolumeImageToVectorImageFilter.h.
template<class TInputPixelType , class TOutputPixelType , unsigned int VImageDimension = 3> const unsigned int itk::MultiVolumeImageToVectorImageFilter< TInputPixelType, TOutputPixelType, VImageDimension >::VectorImageDimension = VImageDimension static
Definition at line 40 of file itkMultiVolumeImageToVectorImageFilter.h.
The documentation for this class was generated from the following files:
Modules/Common/include/itkMultiVolumeImageToVectorImageFilter.h
Modules/Common/include/itkMultiVolumeImageToVectorImageFilter.hxx