DMRITool: spams::FISTA::SqLossMat< T > Class Template Reference
spams::FISTA::SqLossMat< T > Class Template Reference
#include <fista.h>
Detailed Description
template<typename T>
class spams::FISTA::SqLossMat< T >
Definition at line 852 of file fista.h.
Public Member Functions
T eval (const Matrix< T > &alpha) const
virtual T fenchel (const Matrix< T > &input) const
void grad (const Matrix< T > &alpha, Matrix< T > &grad) const
virtual void init (const Matrix< T > &x)
SqLossMat (const AbstractMatrixB< T > &D)
SqLossMat (const AbstractMatrixB< T > &D, const Matrix< T > &G)
virtual bool test_backtracking (const Matrix< T > &y, const Matrix< T > &grad, const Matrix< T > &prox, const T L) const
virtual void var_fenchel (const Matrix< T > &x, Matrix< T > &grad1, Matrix< T > &grad2, const bool intercept) const
virtual ~SqLossMat ()
Public Member Functions inherited from spams::FISTA::Loss< T, Matrix< T >, Matrix< T > >
virtual bool is_fenchel () const
Loss ()
virtual ~Loss ()
Private Member Functions
SqLossMat< T > & operator= (const SqLossMat< T > &dict)
SqLossMat (const SqLossMat< T > &dict)
Private Attributes
bool _compute_gram
const AbstractMatrixB< T > * _D
Matrix< T > _DtX
const Matrix< T > * _G
Matrix< T > _x
Constructor & Destructor Documentation
template<typename T> spams::FISTA::SqLossMat< T >::SqLossMat (const AbstractMatrixB< T > & D) inline
Definition at line 854 of file fista.h.
template<typename T> spams::FISTA::SqLossMat< T >::SqLossMat (const AbstractMatrixB< T > & D, const Matrix< T > & G) inline
Definition at line 855 of file fista.h.
template<typename T> virtual spams::FISTA::SqLossMat< T >::~SqLossMat () inline virtual
Definition at line 857 of file fista.h.
template<typename T> spams::FISTA::SqLossMat< T >::SqLossMat (const SqLossMat< T > & dict) explicit private
Member Function Documentation
template<typename T> T spams::FISTA::SqLossMat< T >::eval (const Matrix< T > & alpha) const inline virtual
Implements spams::FISTA::Loss< T, Matrix< T >, Matrix< T > >.
Definition at line 866 of file fista.h.
References spams::Matrix< T >::copy(), spams::Matrix< T >::normFsq(), and spams::Matrix< T >::toSparse().
template<typename T> virtual T spams::FISTA::SqLossMat< T >::fenchel (const Matrix< T > & input) const inline virtual
Implements spams::FISTA::Loss< T, Matrix< T >, Matrix< T > >.
Definition at line 907 of file fista.h.
References spams::Matrix< T >::dot(), and spams::Matrix< T >::normFsq().
template<typename T> void spams::FISTA::SqLossMat< T >::grad (const Matrix< T > & alpha, Matrix< T > & grad) const inline virtual
Implements spams::FISTA::Loss< T, Matrix< T >, Matrix< T > >.
Definition at line 874 of file fista.h.
References spams::Matrix< T >::copy(), and spams::Matrix< T >::toSparse().
template<typename T> virtual void spams::FISTA::SqLossMat< T >::init (const Matrix< T > & x) inline virtual
Implements spams::FISTA::Loss< T, Matrix< T >, Matrix< T > >.
Definition at line 859 of file fista.h.
template<typename T> SqLossMat<T>& spams::FISTA::SqLossMat< T >::operator= (const SqLossMat< T > & dict) private
template<typename T> virtual bool spams::FISTA::SqLossMat< T >::test_backtracking (const Matrix< T > & y, const Matrix< T > & grad, const Matrix< T > & prox, const T L) const inline virtual
Reimplemented from spams::FISTA::Loss< T, Matrix< T >, Matrix< T > >.
Definition at line 887 of file fista.h.
References spams::Matrix< T >::copy(), spams::Matrix< T >::mult(), spams::SpMatrix< T >::n(), spams::Matrix< T >::normFsq(), spams::SpMatrix< T >::normFsq(), spams::SpMatrix< T >::refCol(), spams::Matrix< T >::sub(), and spams::Matrix< T >::toSparse().
template<typename T> virtual void spams::FISTA::SqLossMat< T >::var_fenchel (const Matrix< T > & x, Matrix< T > & grad1, Matrix< T > & grad2, const bool intercept) const inline virtual
Implements spams::FISTA::Loss< T, Matrix< T >, Matrix< T > >.
Definition at line 910 of file fista.h.
References spams::Matrix< T >::center(), spams::Matrix< T >::copy(), and spams::Matrix< T >::toSparse().
Member Data Documentation
template<typename T> bool spams::FISTA::SqLossMat< T >::_compute_gram private
Definition at line 925 of file fista.h.
template<typename T> const AbstractMatrixB<T>* spams::FISTA::SqLossMat< T >::_D private
Definition at line 923 of file fista.h.
template<typename T> Matrix<T> spams::FISTA::SqLossMat< T >::_DtX private
Definition at line 927 of file fista.h.
template<typename T> const Matrix<T>* spams::FISTA::SqLossMat< T >::_G private
Definition at line 926 of file fista.h.
template<typename T> Matrix<T> spams::FISTA::SqLossMat< T >::_x private
Definition at line 924 of file fista.h.
The documentation for this class was generated from the following file:
ThirdParty/Spams/include/fista.h