DMRITool: itk::SpatiallyDenseSparseVectorImageFileReader< TOutputImage > Class Template Reference
itk::SpatiallyDenseSparseVectorImageFileReader< TOutputImage > Class Template Reference
#include <itkSpatiallyDenseSparseVectorImageFileReader.h>
Detailed Description
template<class TOutputImage>
class itk::SpatiallyDenseSparseVectorImageFileReader< TOutputImage >
Reads sparse image data from key and value files.
Author
Pew-Thian Yap (ptyap.nosp@m.@med.nosp@m..unc..nosp@m.edu)
Definition at line 67 of file itkSpatiallyDenseSparseVectorImageFileReader.h.
Public Types
typedef ImageFileReader< KeyImageType > KeyImageFileReaderType
typedef Image< OutputImageKeyType, 1 > KeyImageType
typedef OutputImageType::DirectionType OutputImageDirectionType
typedef OutputImageType::IndexType OutputImageIndexType
typedef OutputImageType::InternalPixelType OutputImageInternalPixelType
typedef OutputImageType::KeyType OutputImageKeyType
typedef OutputImageType::PixelContainerConstPointer OutputImagePixelContainerConstPointerType
typedef OutputImageType::PixelContainer OutputImagePixelContainerType
typedef OutputImageType::PixelMapConstIterator OutputImagePixelMapConstIteratorType
typedef OutputImageType::PixelMapType OutputImagePixelPixelMapType
typedef OutputImageType::PixelType OutputImagePixelType
typedef OutputImageType::Pointer OutputImagePointer
typedef OutputImageType::PointType OutputImagePointType
typedef OutputImageType::RegionType OutputImageRegionType
typedef OutputImageType::SizeType OutputImageSizeType
typedef OutputImageType::SpacingType OutputImageSpacingType
typedef TOutputImage OutputImageType
typedef OutputImageType::ValueType OutputImageValueType
typedef SmartPointer< Self > Pointer
typedef SpatiallyDenseSparseVectorImageFileReader Self
typedef ImageSource< TOutputImage > Superclass
typedef ImageFileReader< ValueImageType > ValueImageFileReaderType
typedef Image< OutputImageValueType, 1 > ValueImageType
Public Member Functions
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual const char * GetFileName () const
virtual const char * GetNameOfClass () const
virtual const bool & GetUseStreaming ()
itkGetObjectMacro (ImageIO, ImageIOBase)
virtual void SetFileName (const char *_arg)
virtual void SetUseStreaming (bool _arg)
virtual void UseStreamingOff ()
virtual void UseStreamingOn ()
Static Public Member Functions
static Pointer New ()
Static Public Attributes
static const unsigned int ImageDimension = Superclass::OutputImageDimension
Protected Member Functions
virtual void GenerateData () ITK_OVERRIDE
void PrintSelf (std::ostream &os, Indent indent) const ITK_OVERRIDE
SpatiallyDenseSparseVectorImageFileReader ()
~SpatiallyDenseSparseVectorImageFileReader ()
Protected Attributes
std::string m_FileName
ImageIOBase::Pointer m_ImageIO
KeyImageType::Pointer m_KeyImage
KeyImageFileReaderType::Pointer m_KeyImageFileReader
bool m_UseStreaming
ValueImageType::Pointer m_ValueImage
ValueImageFileReaderType::Pointer m_ValueImageFileReader
Private Member Functions
void operator= (const Self &)
SpatiallyDenseSparseVectorImageFileReader (const Self &)
Private Attributes
std::string m_ExceptionMessage
Member Typedef Documentation
template<class TOutputImage > typedef ImageFileReader<KeyImageType> itk::SpatiallyDenseSparseVectorImageFileReader< TOutputImage >::KeyImageFileReaderType
Definition at line 105 of file itkSpatiallyDenseSparseVectorImageFileReader.h.
template<class TOutputImage > typedef Image<OutputImageKeyType, 1> itk::SpatiallyDenseSparseVectorImageFileReader< TOutputImage >::KeyImageType
Definition at line 102 of file itkSpatiallyDenseSparseVectorImageFileReader.h.
template<class TOutputImage > typedef OutputImageType::DirectionType itk::SpatiallyDenseSparseVectorImageFileReader< TOutputImage >::OutputImageDirectionType
Definition at line 91 of file itkSpatiallyDenseSparseVectorImageFileReader.h.
template<class TOutputImage > typedef OutputImageType::IndexType itk::SpatiallyDenseSparseVectorImageFileReader< TOutputImage >::OutputImageIndexType
Definition at line 89 of file itkSpatiallyDenseSparseVectorImageFileReader.h.
template<class TOutputImage > typedef OutputImageType::InternalPixelType itk::SpatiallyDenseSparseVectorImageFileReader< TOutputImage >::OutputImageInternalPixelType
Definition at line 94 of file itkSpatiallyDenseSparseVectorImageFileReader.h.
template<class TOutputImage > typedef OutputImageType::KeyType itk::SpatiallyDenseSparseVectorImageFileReader< TOutputImage >::OutputImageKeyType
Definition at line 96 of file itkSpatiallyDenseSparseVectorImageFileReader.h.
template<class TOutputImage > typedef OutputImageType::PixelContainerConstPointer itk::SpatiallyDenseSparseVectorImageFileReader< TOutputImage >::OutputImagePixelContainerConstPointerType
Definition at line 98 of file itkSpatiallyDenseSparseVectorImageFileReader.h.
template<class TOutputImage > typedef OutputImageType::PixelContainer itk::SpatiallyDenseSparseVectorImageFileReader< TOutputImage >::OutputImagePixelContainerType
Definition at line 97 of file itkSpatiallyDenseSparseVectorImageFileReader.h.
template<class TOutputImage > typedef OutputImageType::PixelMapConstIterator itk::SpatiallyDenseSparseVectorImageFileReader< TOutputImage >::OutputImagePixelMapConstIteratorType
Definition at line 100 of file itkSpatiallyDenseSparseVectorImageFileReader.h.
template<class TOutputImage > typedef OutputImageType::PixelMapType itk::SpatiallyDenseSparseVectorImageFileReader< TOutputImage >::OutputImagePixelPixelMapType
Definition at line 99 of file itkSpatiallyDenseSparseVectorImageFileReader.h.
template<class TOutputImage > typedef OutputImageType::PixelType itk::SpatiallyDenseSparseVectorImageFileReader< TOutputImage >::OutputImagePixelType
Definition at line 93 of file itkSpatiallyDenseSparseVectorImageFileReader.h.
template<class TOutputImage > typedef OutputImageType::Pointer itk::SpatiallyDenseSparseVectorImageFileReader< TOutputImage >::OutputImagePointer
Definition at line 86 of file itkSpatiallyDenseSparseVectorImageFileReader.h.
template<class TOutputImage > typedef OutputImageType::PointType itk::SpatiallyDenseSparseVectorImageFileReader< TOutputImage >::OutputImagePointType
Definition at line 90 of file itkSpatiallyDenseSparseVectorImageFileReader.h.
template<class TOutputImage > typedef OutputImageType::RegionType itk::SpatiallyDenseSparseVectorImageFileReader< TOutputImage >::OutputImageRegionType
Definition at line 92 of file itkSpatiallyDenseSparseVectorImageFileReader.h.
template<class TOutputImage > typedef OutputImageType::SizeType itk::SpatiallyDenseSparseVectorImageFileReader< TOutputImage >::OutputImageSizeType
Definition at line 87 of file itkSpatiallyDenseSparseVectorImageFileReader.h.
template<class TOutputImage > typedef OutputImageType::SpacingType itk::SpatiallyDenseSparseVectorImageFileReader< TOutputImage >::OutputImageSpacingType
Definition at line 88 of file itkSpatiallyDenseSparseVectorImageFileReader.h.
template<class TOutputImage > typedef TOutputImage itk::SpatiallyDenseSparseVectorImageFileReader< TOutputImage >::OutputImageType
Some convenient typedefs.
Definition at line 85 of file itkSpatiallyDenseSparseVectorImageFileReader.h.
template<class TOutputImage > typedef OutputImageType::ValueType itk::SpatiallyDenseSparseVectorImageFileReader< TOutputImage >::OutputImageValueType
Definition at line 95 of file itkSpatiallyDenseSparseVectorImageFileReader.h.
template<class TOutputImage > typedef SmartPointer<Self> itk::SpatiallyDenseSparseVectorImageFileReader< TOutputImage >::Pointer
Definition at line 73 of file itkSpatiallyDenseSparseVectorImageFileReader.h.
template<class TOutputImage > typedef SpatiallyDenseSparseVectorImageFileReader itk::SpatiallyDenseSparseVectorImageFileReader< TOutputImage >::Self
Standard class typedefs.
Definition at line 71 of file itkSpatiallyDenseSparseVectorImageFileReader.h.
template<class TOutputImage > typedef ImageSource<TOutputImage> itk::SpatiallyDenseSparseVectorImageFileReader< TOutputImage >::Superclass
Definition at line 72 of file itkSpatiallyDenseSparseVectorImageFileReader.h.
template<class TOutputImage > typedef ImageFileReader<ValueImageType> itk::SpatiallyDenseSparseVectorImageFileReader< TOutputImage >::ValueImageFileReaderType
Definition at line 106 of file itkSpatiallyDenseSparseVectorImageFileReader.h.
template<class TOutputImage > typedef Image<OutputImageValueType, 1> itk::SpatiallyDenseSparseVectorImageFileReader< TOutputImage >::ValueImageType
Definition at line 103 of file itkSpatiallyDenseSparseVectorImageFileReader.h.
Constructor & Destructor Documentation
template<class TOutputImage > itk::SpatiallyDenseSparseVectorImageFileReader< TOutputImage >::SpatiallyDenseSparseVectorImageFileReader () protected
Definition at line 27 of file itkSpatiallyDenseSparseVectorImageFileReader.hxx.
References itk::SpatiallyDenseSparseVectorImageFileReader< TOutputImage >::~SpatiallyDenseSparseVectorImageFileReader().
template<class TOutputImage > itk::SpatiallyDenseSparseVectorImageFileReader< TOutputImage >::~SpatiallyDenseSparseVectorImageFileReader () protected
Definition at line 36 of file itkSpatiallyDenseSparseVectorImageFileReader.hxx.
References itk::SpatiallyDenseSparseVectorImageFileReader< TOutputImage >::PrintSelf().
Referenced by itk::SpatiallyDenseSparseVectorImageFileReader< TOutputImage >::SpatiallyDenseSparseVectorImageFileReader().
template<class TOutputImage > itk::SpatiallyDenseSparseVectorImageFileReader< TOutputImage >::SpatiallyDenseSparseVectorImageFileReader (const Self &) private
Member Function Documentation
template<class TOutputImage > virtual::itk::LightObject::Pointer itk::SpatiallyDenseSparseVectorImageFileReader< TOutputImage >::CreateAnother (void) const
template<class TOutputImage > void itk::SpatiallyDenseSparseVectorImageFileReader< TOutputImage >::GenerateData (void) protected virtual
Does the real work.
Definition at line 62 of file itkSpatiallyDenseSparseVectorImageFileReader.hxx.
Referenced by itk::SpatiallyDenseSparseVectorImageFileReader< TOutputImage >::PrintSelf().
template<class TOutputImage > virtual const char* itk::SpatiallyDenseSparseVectorImageFileReader< TOutputImage >::GetFileName () const virtual
template<class TOutputImage > virtual const char* itk::SpatiallyDenseSparseVectorImageFileReader< TOutputImage >::GetNameOfClass () const virtual
Run-time type information (and related methods).
template<class TOutputImage > virtual const bool& itk::SpatiallyDenseSparseVectorImageFileReader< TOutputImage >::GetUseStreaming () virtual
template<class TOutputImage > itk::SpatiallyDenseSparseVectorImageFileReader< TOutputImage >::itkGetObjectMacro (ImageIO , ImageIOBase)
Set/Get the ImageIO helper class
template<class TOutputImage > static Pointer itk::SpatiallyDenseSparseVectorImageFileReader< TOutputImage >::New () static
Method for creation through the object factory.
template<class TOutputImage > void itk::SpatiallyDenseSparseVectorImageFileReader< TOutputImage >::operator= (const Self &) private
template<class TOutputImage > void itk::SpatiallyDenseSparseVectorImageFileReader< TOutputImage >::PrintSelf (std::ostream & os, Indent indent) const protected
Definition at line 42 of file itkSpatiallyDenseSparseVectorImageFileReader.hxx.
References itk::SpatiallyDenseSparseVectorImageFileReader< TOutputImage >::GenerateData().
Referenced by itk::SpatiallyDenseSparseVectorImageFileReader< TOutputImage >::~SpatiallyDenseSparseVectorImageFileReader().
template<class TOutputImage > virtual void itk::SpatiallyDenseSparseVectorImageFileReader< TOutputImage >::SetFileName (const char * _arg) virtual
Specify the files to read. This is forwarded to the IO instance.
template<class TOutputImage > virtual void itk::SpatiallyDenseSparseVectorImageFileReader< TOutputImage >::SetUseStreaming (bool _arg) virtual
Set the stream On or Off
template<class TOutputImage > virtual void itk::SpatiallyDenseSparseVectorImageFileReader< TOutputImage >::UseStreamingOff () virtual
template<class TOutputImage > virtual void itk::SpatiallyDenseSparseVectorImageFileReader< TOutputImage >::UseStreamingOn () virtual
Member Data Documentation
template<class TOutputImage > const unsigned int itk::SpatiallyDenseSparseVectorImageFileReader< TOutputImage >::ImageDimension = Superclass::OutputImageDimension static
Dimension of image.
Definition at line 82 of file itkSpatiallyDenseSparseVectorImageFileReader.h.
template<class TOutputImage > std::string itk::SpatiallyDenseSparseVectorImageFileReader< TOutputImage >::m_ExceptionMessage private
Definition at line 152 of file itkSpatiallyDenseSparseVectorImageFileReader.h.
template<class TOutputImage > std::string itk::SpatiallyDenseSparseVectorImageFileReader< TOutputImage >::m_FileName protected
Definition at line 144 of file itkSpatiallyDenseSparseVectorImageFileReader.h.
template<class TOutputImage > ImageIOBase::Pointer itk::SpatiallyDenseSparseVectorImageFileReader< TOutputImage >::m_ImageIO protected
Definition at line 146 of file itkSpatiallyDenseSparseVectorImageFileReader.h.
template<class TOutputImage > KeyImageType::Pointer itk::SpatiallyDenseSparseVectorImageFileReader< TOutputImage >::m_KeyImage protected
Convert a block of pixels from one type to another. Test whether the given filename exist and it is readable, this is intended to be called before attempting to use ImageIO classes for actually reading the file. If the file doesn't exist or it is not readable, and exception with an approriate message will be thrown.
Definition at line 135 of file itkSpatiallyDenseSparseVectorImageFileReader.h.
template<class TOutputImage > KeyImageFileReaderType::Pointer itk::SpatiallyDenseSparseVectorImageFileReader< TOutputImage >::m_KeyImageFileReader protected
Definition at line 138 of file itkSpatiallyDenseSparseVectorImageFileReader.h.
template<class TOutputImage > bool itk::SpatiallyDenseSparseVectorImageFileReader< TOutputImage >::m_UseStreaming protected
Definition at line 145 of file itkSpatiallyDenseSparseVectorImageFileReader.h.
template<class TOutputImage > ValueImageType::Pointer itk::SpatiallyDenseSparseVectorImageFileReader< TOutputImage >::m_ValueImage protected
Definition at line 136 of file itkSpatiallyDenseSparseVectorImageFileReader.h.
template<class TOutputImage > ValueImageFileReaderType::Pointer itk::SpatiallyDenseSparseVectorImageFileReader< TOutputImage >::m_ValueImageFileReader protected
Definition at line 139 of file itkSpatiallyDenseSparseVectorImageFileReader.h.
The documentation for this class was generated from the following files:
ThirdParty/SpatiallyDenseSparseVectorImage/include/itkSpatiallyDenseSparseVectorImageFileReader.h
ThirdParty/SpatiallyDenseSparseVectorImage/include/itkSpatiallyDenseSparseVectorImageFileReader.hxx