DMRITool: itk::VectorImageRegionIterator< Image< TPixel, VImageDimension > > Class Template Reference
itk::VectorImageRegionIterator< Image< TPixel, VImageDimension > > Class Template Reference
#include <itkVectorImageRegionIterator.h>
Detailed Description
template<typename TPixel, unsigned int VImageDimension>
class itk::VectorImageRegionIterator< Image< TPixel, VImageDimension > >
Definition at line 245 of file itkVectorImageRegionIterator.h.
Public Types
typedef Superclass::AccessorType AccessorType
typedef Superclass::ImageType ImageType
typedef Superclass::IndexType IndexType
typedef Superclass::InternalPixelType InternalPixelType
typedef Superclass::OffsetType OffsetType
typedef Superclass::PixelContainer PixelContainer
typedef Superclass::PixelContainerPointer PixelContainerPointer
typedef Superclass::PixelType PixelType
typedef VariableLengthVector< InternalPixelType > PixelVectorType
typedef Superclass::RegionType RegionType
typedef VectorImageRegionIterator Self
typedef Superclass::SizeType SizeType
typedef ImageRegionIterator< Image< TPixel, VImageDimension > > Superclass
Public Member Functions
void GetVector (PixelVectorType &vec, const int offIndex=0) const
Self & operator= (const Self &it)
void SetRegion (const RegionType &regionInput)
void SetVector (const PixelVectorType &value, const int offIndex=0)
typedef (itk::Concept::SameType< ImageType, Image< InternalPixelType, VImageDimension > >) SameTypeCheck
VectorImageRegionIterator ()
VectorImageRegionIterator (const Self &it)
VectorImageRegionIterator (ImageType *ptr, const RegionType &region, int vectorAxis=-1)
~VectorImageRegionIterator ()
Static Public Attributes
static const unsigned int ImageIteratorDimension = VImageDimension
Protected Member Functions
Self & operator= (const ImageRegionIterator< ImageType > &it)
VectorImageRegionIterator (const ImageRegionIterator< ImageType > &it)
Protected Attributes
int m_VectorAxis
int m_VectorSize
OffsetValueType m_VectorStride
OffsetValueType m_VolumeSize
Member Typedef Documentation
template<typename TPixel , unsigned int VImageDimension> typedef Superclass::AccessorType itk::VectorImageRegionIterator< Image< TPixel, VImageDimension > >::AccessorType
Definition at line 272 of file itkVectorImageRegionIterator.h.
template<typename TPixel , unsigned int VImageDimension> typedef Superclass::ImageType itk::VectorImageRegionIterator< Image< TPixel, VImageDimension > >::ImageType
Definition at line 267 of file itkVectorImageRegionIterator.h.
template<typename TPixel , unsigned int VImageDimension> typedef Superclass::IndexType itk::VectorImageRegionIterator< Image< TPixel, VImageDimension > >::IndexType
Inherit types from the superclass
Definition at line 263 of file itkVectorImageRegionIterator.h.
template<typename TPixel , unsigned int VImageDimension> typedef Superclass::InternalPixelType itk::VectorImageRegionIterator< Image< TPixel, VImageDimension > >::InternalPixelType
Definition at line 270 of file itkVectorImageRegionIterator.h.
template<typename TPixel , unsigned int VImageDimension> typedef Superclass::OffsetType itk::VectorImageRegionIterator< Image< TPixel, VImageDimension > >::OffsetType
Definition at line 265 of file itkVectorImageRegionIterator.h.
template<typename TPixel , unsigned int VImageDimension> typedef Superclass::PixelContainer itk::VectorImageRegionIterator< Image< TPixel, VImageDimension > >::PixelContainer
Definition at line 268 of file itkVectorImageRegionIterator.h.
template<typename TPixel , unsigned int VImageDimension> typedef Superclass::PixelContainerPointer itk::VectorImageRegionIterator< Image< TPixel, VImageDimension > >::PixelContainerPointer
Definition at line 269 of file itkVectorImageRegionIterator.h.
template<typename TPixel , unsigned int VImageDimension> typedef Superclass::PixelType itk::VectorImageRegionIterator< Image< TPixel, VImageDimension > >::PixelType
Definition at line 271 of file itkVectorImageRegionIterator.h.
template<typename TPixel , unsigned int VImageDimension> typedef VariableLengthVector< InternalPixelType > itk::VectorImageRegionIterator< Image< TPixel, VImageDimension > >::PixelVectorType
Definition at line 274 of file itkVectorImageRegionIterator.h.
template<typename TPixel , unsigned int VImageDimension> typedef Superclass::RegionType itk::VectorImageRegionIterator< Image< TPixel, VImageDimension > >::RegionType
Definition at line 266 of file itkVectorImageRegionIterator.h.
template<typename TPixel , unsigned int VImageDimension> typedef VectorImageRegionIterator itk::VectorImageRegionIterator< Image< TPixel, VImageDimension > >::Self
Standard class typedefs.
Definition at line 249 of file itkVectorImageRegionIterator.h.
template<typename TPixel , unsigned int VImageDimension> typedef Superclass::SizeType itk::VectorImageRegionIterator< Image< TPixel, VImageDimension > >::SizeType
Definition at line 264 of file itkVectorImageRegionIterator.h.
template<typename TPixel , unsigned int VImageDimension> typedef ImageRegionIterator< Image<TPixel, VImageDimension> > itk::VectorImageRegionIterator< Image< TPixel, VImageDimension > >::Superclass
Define the superclass
Definition at line 260 of file itkVectorImageRegionIterator.h.
Constructor & Destructor Documentation
template<typename TPixel , unsigned int VImageDimension> itk::VectorImageRegionIterator< Image< TPixel, VImageDimension > >::VectorImageRegionIterator () inline
Default Constructor. Need to provide a default constructor since we provide a copy constructor.
Definition at line 283 of file itkVectorImageRegionIterator.h.
References itk::VectorImageRegionIterator< TImage >::ImageIteratorDimension, itk::VectorImageRegionIterator< TImage >::m_VectorAxis, itk::VectorImageRegionIterator< TImage >::m_VectorSize, and itk::VectorImageRegionIterator< TImage >::m_VectorStride.
template<typename TPixel , unsigned int VImageDimension> itk::VectorImageRegionIterator< Image< TPixel, VImageDimension > >::~VectorImageRegionIterator () inline
Default Destructor
Definition at line 292 of file itkVectorImageRegionIterator.h.
template<typename TPixel , unsigned int VImageDimension> itk::VectorImageRegionIterator< Image< TPixel, VImageDimension > >::VectorImageRegionIterator (const Self & it) inline
Copy Constructor. The copy constructor is provided to make sure the handle to the image is properly reference counted.
Definition at line 296 of file itkVectorImageRegionIterator.h.
References itk::VectorImageRegionIterator< TImage >::m_VectorAxis, itk::VectorImageRegionIterator< TImage >::m_VectorSize, and itk::VectorImageRegionIterator< TImage >::m_VectorStride.
template<typename TPixel , unsigned int VImageDimension> itk::VectorImageRegionIterator< Image< TPixel, VImageDimension > >::VectorImageRegionIterator (ImageType * ptr, const RegionType & region, int vectorAxis = -1) inline
Constructor establishes an iterator to walk a particular image and a particular region of that image.
Definition at line 306 of file itkVectorImageRegionIterator.h.
References itk::VectorImageRegionIterator< TImage >::ImageIteratorDimension, itk::VectorImageRegionIterator< TImage >::m_VectorAxis, itk::VectorImageRegionIterator< TImage >::m_VectorSize, itk::VectorImageRegionIterator< TImage >::m_VectorStride, and itk::VectorImageRegionIterator< TImage >::SetRegion().
template<typename TPixel , unsigned int VImageDimension> itk::VectorImageRegionIterator< Image< TPixel, VImageDimension > >::VectorImageRegionIterator (const ImageRegionIterator< ImageType > & it) protected
This constructor is declared protected in order to enforce const-correctness
Member Function Documentation
template<typename TPixel , unsigned int VImageDimension> void itk::VectorImageRegionIterator< Image< TPixel, VImageDimension > >::GetVector (PixelVectorType & vec, const int offIndex = 0) const inline
Get the pixel value
Definition at line 400 of file itkVectorImageRegionIterator.h.
References itk::VectorImageRegionIterator< TImage >::m_VectorSize, itk::VectorImageRegionIterator< TImage >::m_VectorStride, itk::VectorImageRegionIterator< TImage >::operator=(), and itk::VectorImageRegionIterator< TImage >::VectorImageRegionIterator().
template<typename TPixel , unsigned int VImageDimension> Self& itk::VectorImageRegionIterator< Image< TPixel, VImageDimension > >::operator= (const Self & it) inline
operator= is provided to make sure the handle to the image is properly reference counted.
Definition at line 325 of file itkVectorImageRegionIterator.h.
References itk::VectorImageRegionIterator< TImage >::m_VectorAxis, itk::VectorImageRegionIterator< TImage >::m_VectorSize, and itk::VectorImageRegionIterator< TImage >::m_VectorStride.
template<typename TPixel , unsigned int VImageDimension> Self& itk::VectorImageRegionIterator< Image< TPixel, VImageDimension > >::operator= (const ImageRegionIterator< ImageType > & it) protected
template<typename TPixel , unsigned int VImageDimension> void itk::VectorImageRegionIterator< Image< TPixel, VImageDimension > >::SetRegion (const RegionType & regionInput) inline
Set the region of the image to iterate over.
Definition at line 335 of file itkVectorImageRegionIterator.h.
References itk::VectorImageRegionIterator< TImage >::m_VectorAxis.
template<typename TPixel , unsigned int VImageDimension> void itk::VectorImageRegionIterator< Image< TPixel, VImageDimension > >::SetVector (const PixelVectorType & value, const int offIndex = 0) inline
Set the pixel value
Definition at line 388 of file itkVectorImageRegionIterator.h.
References itk::VectorImageRegionIterator< TImage >::m_VectorSize, and itk::VectorImageRegionIterator< TImage >::m_VectorStride.
template<typename TPixel , unsigned int VImageDimension> itk::VectorImageRegionIterator< Image< TPixel, VImageDimension > >::typedef (itk::Concept::SameType< ImageType, Image< InternalPixelType, VImageDimension > >)
This class requires SameTypeCheck in the form of (itk::Concept::SameType< ImageType, Image<InternalPixelType, VImageDimension> >)
Member Data Documentation
template<typename TPixel , unsigned int VImageDimension> const unsigned int itk::VectorImageRegionIterator< Image< TPixel, VImageDimension > >::ImageIteratorDimension = VImageDimension static
Dimension of the image the iterator walks. This constant is needed so functions that are templated over image iterator type (as opposed to being templated over pixel type and dimension) can have compile time access to the dimension of the image that the iterator walks.
Definition at line 257 of file itkVectorImageRegionIterator.h.
template<typename TPixel , unsigned int VImageDimension> int itk::VectorImageRegionIterator< Image< TPixel, VImageDimension > >::m_VectorAxis protected
Definition at line 424 of file itkVectorImageRegionIterator.h.
template<typename TPixel , unsigned int VImageDimension> int itk::VectorImageRegionIterator< Image< TPixel, VImageDimension > >::m_VectorSize protected
Definition at line 423 of file itkVectorImageRegionIterator.h.
template<typename TPixel , unsigned int VImageDimension> OffsetValueType itk::VectorImageRegionIterator< Image< TPixel, VImageDimension > >::m_VectorStride protected
Definition at line 422 of file itkVectorImageRegionIterator.h.
template<typename TPixel , unsigned int VImageDimension> OffsetValueType itk::VectorImageRegionIterator< Image< TPixel, VImageDimension > >::m_VolumeSize protected
Definition at line 421 of file itkVectorImageRegionIterator.h.
The documentation for this class was generated from the following file:
Modules/Common/include/itkVectorImageRegionIterator.h