DMRITool: spams::FISTA::RegMat< T, Reg > Class Template Reference
spams::FISTA::RegMat< T, Reg > Class Template Reference
#include <fista.h>
Detailed Description
template<typename T, typename Reg>
class spams::FISTA::RegMat< T, Reg >
Definition at line 2157 of file fista.h.
Public Member Functions
T eval (const Matrix< T > &x) const
void fenchel (const Matrix< T > &input, T &val, T &scal) const
virtual bool is_fenchel () const
virtual bool is_subgrad () const
void prox (const Matrix< T > &x, Matrix< T > &y, const T lambda)
RegMat (const ParamReg< T > &param)
void reset ()
void sub_grad (const Matrix< T > &x, Matrix< T > &y) const
virtual ~RegMat ()
Public Member Functions inherited from spams::FISTA::Regularizer< T, Matrix< T > >
virtual T eval_dual_norm (const Matrix< T > &x) const
virtual T eval_dual_norm_paths (const Matrix< T > &x, SpMatrix< T > &path) const
virtual T eval_paths (const Matrix< T > &x, SpMatrix< T > &paths_mat) const
virtual bool is_intercept () const
Regularizer ()
Regularizer (const ParamReg< T > &param)
virtual ~Regularizer ()
Protected Attributes
int _N
Reg ** _regs
bool _transpose
Protected Attributes inherited from spams::FISTA::Regularizer< T, Matrix< T > >
bool _intercept
bool _pos
Constructor & Destructor Documentation
template<typename T , typename Reg > spams::FISTA::RegMat< T, Reg >::RegMat (const ParamReg< T > & param) inline
Definition at line 2159 of file fista.h.
References spams::FISTA::ParamReg< T >::num_cols, and spams::FISTA::ParamReg< T >::transpose.
template<typename T , typename Reg > virtual spams::FISTA::RegMat< T, Reg >::~RegMat () inline virtual
Definition at line 2167 of file fista.h.
Member Function Documentation
template<typename T , typename Reg > T spams::FISTA::RegMat< T, Reg >::eval (const Matrix< T > & x) const inline virtual
Implements spams::FISTA::Regularizer< T, Matrix< T > >.
Definition at line 2221 of file fista.h.
References spams::Matrix< T >::copyRow(), and spams::Matrix< T >::refCol().
template<typename T , typename Reg > void spams::FISTA::RegMat< T, Reg >::fenchel (const Matrix< T > & input, T & val, T & scal) const inline virtual
returns phi^star(input) and ouput=input if the fenchel is unconstrained returns 0 and scale input such that phi^star(output)=0 otherwise
Implements spams::FISTA::Regularizer< T, Matrix< T > >.
Definition at line 2237 of file fista.h.
References spams::Matrix< T >::copyRow(), MIN, and spams::Matrix< T >::refCol().
template<typename T , typename Reg > virtual bool spams::FISTA::RegMat< T, Reg >::is_fenchel () const inline virtual
Reimplemented from spams::FISTA::Regularizer< T, Matrix< T > >.
Definition at line 2254 of file fista.h.
template<typename T , typename Reg > virtual bool spams::FISTA::RegMat< T, Reg >::is_subgrad () const inline virtual
Reimplemented from spams::FISTA::Regularizer< T, Matrix< T > >.
Definition at line 2198 of file fista.h.
template<typename T , typename Reg > void spams::FISTA::RegMat< T, Reg >::prox (const Matrix< T > & x, Matrix< T > & y, const T lambda) inline virtual
Implements spams::FISTA::Regularizer< T, Matrix< T > >.
Definition at line 2177 of file fista.h.
References spams::Matrix< T >::copy(), spams::Matrix< T >::copyRow(), spams::Matrix< T >::refCol(), and spams::Matrix< T >::setRow().
template<typename T , typename Reg > void spams::FISTA::RegMat< T, Reg >::reset () inline virtual
Reimplemented from spams::FISTA::Regularizer< T, Matrix< T > >.
Definition at line 2174 of file fista.h.
template<typename T , typename Reg > void spams::FISTA::RegMat< T, Reg >::sub_grad (const Matrix< T > & x, Matrix< T > & y) const inline virtual
Reimplemented from spams::FISTA::Regularizer< T, Matrix< T > >.
Definition at line 2204 of file fista.h.
References spams::Matrix< T >::copyRow(), spams::Matrix< T >::m(), spams::Matrix< T >::n(), spams::Matrix< T >::refCol(), spams::Matrix< T >::resize(), and spams::Matrix< T >::setRow().
Member Data Documentation
template<typename T , typename Reg > int spams::FISTA::RegMat< T, Reg >::_N protected
Definition at line 2259 of file fista.h.
template<typename T , typename Reg > Reg** spams::FISTA::RegMat< T, Reg >::_regs protected
Definition at line 2263 of file fista.h.
template<typename T , typename Reg > bool spams::FISTA::RegMat< T, Reg >::_transpose protected
Definition at line 2264 of file fista.h.
The documentation for this class was generated from the following file:
ThirdParty/Spams/include/fista.h