DMRITool: itk::SphericalPolarFourierGenerator< PreciseType > Class Template Reference
itk::SphericalPolarFourierGenerator< PreciseType > Class Template Reference
Math
#include <itkSphericalPolarFourierGenerator.h>
Detailed Description
template<class PreciseType = double>
class itk::SphericalPolarFourierGenerator< PreciseType >
general SPF basis in radial part, SH basis in spherical part
Author
Jian Cheng
Definition at line 106 of file itkSphericalPolarFourierGenerator.h.
Public Types
typedef SmartPointer< const Self > ConstPointer
typedef SmartPointer< Self > Pointer
typedef RadialType::Pointer RadialPointer
typedef SphericalPolarFourierRadialGenerator< PreciseType > RadialType
typedef SphericalPolarFourierGenerator Self
typedef RadialType::SPFType SPFType
typedef Object Superclass
Public Member Functions
virtual ::itk::LightObject::Pointer CreateAnother (void) const
PreciseType Evaluate (const PreciseType qrValue, const PreciseType theta, const PreciseType phi, const bool isFourier=false) const
PreciseType EvaluateRadial (const PreciseType qrValue, const bool isFourier=false) const
int GetL () const
virtual int GetM ()
int GetN () const
virtual const char * GetNameOfClass () const
PreciseType GetNormalizeFacotr (const bool isFourier=false) const
double GetScale () const
RadialType::SPFType GetSPFType () const
void SetL (const int l)
virtual void SetM (int _arg)
void SetN (const int n)
void SetNLM (const int n, const int l, const int m)
void SetScale (const double scale)
void SetSPFType (const SPFType model)
Static Public Member Functions
static Pointer New ()
Protected Member Functions
void PrintSelf (std::ostream &os, Indent indent) const
SphericalPolarFourierGenerator ()
virtual ~SphericalPolarFourierGenerator ()
Protected Attributes
int m_M
RadialPointer m_Radial
Private Member Functions
void operator= (const Self &)
SphericalPolarFourierGenerator (const Self &)
Member Typedef Documentation
template<class PreciseType = double> typedef SmartPointer<const Self> itk::SphericalPolarFourierGenerator< PreciseType >::ConstPointer
Definition at line 113 of file itkSphericalPolarFourierGenerator.h.
template<class PreciseType = double> typedef SmartPointer<Self> itk::SphericalPolarFourierGenerator< PreciseType >::Pointer
Definition at line 112 of file itkSphericalPolarFourierGenerator.h.
template<class PreciseType = double> typedef RadialType::Pointer itk::SphericalPolarFourierGenerator< PreciseType >::RadialPointer
Definition at line 122 of file itkSphericalPolarFourierGenerator.h.
template<class PreciseType = double> typedef SphericalPolarFourierRadialGenerator<PreciseType> itk::SphericalPolarFourierGenerator< PreciseType >::RadialType
Definition at line 119 of file itkSphericalPolarFourierGenerator.h.
template<class PreciseType = double> typedef SphericalPolarFourierGenerator itk::SphericalPolarFourierGenerator< PreciseType >::Self
Standard class typedefs.
Definition at line 110 of file itkSphericalPolarFourierGenerator.h.
template<class PreciseType = double> typedef RadialType::SPFType itk::SphericalPolarFourierGenerator< PreciseType >::SPFType
Definition at line 123 of file itkSphericalPolarFourierGenerator.h.
template<class PreciseType = double> typedef Object itk::SphericalPolarFourierGenerator< PreciseType >::Superclass
Definition at line 111 of file itkSphericalPolarFourierGenerator.h.
Constructor & Destructor Documentation
template<class PreciseType = double> itk::SphericalPolarFourierGenerator< PreciseType >::SphericalPolarFourierGenerator () inline protected
SphericalPolarFourierGenerator constructor
Definition at line 190 of file itkSphericalPolarFourierGenerator.h.
template<class PreciseType = double> virtual itk::SphericalPolarFourierGenerator< PreciseType >::~SphericalPolarFourierGenerator () inline protected virtual
Definition at line 196 of file itkSphericalPolarFourierGenerator.h.
template<class PreciseType = double> itk::SphericalPolarFourierGenerator< PreciseType >::SphericalPolarFourierGenerator (const Self &) private
Member Function Documentation
template<class PreciseType = double> virtual::itk::LightObject::Pointer itk::SphericalPolarFourierGenerator< PreciseType >::CreateAnother (void) const
template<class PreciseType > PreciseType itk::SphericalPolarFourierGenerator< PreciseType >::Evaluate (const PreciseType qrValue, const PreciseType theta, const PreciseType phi, const bool isFourier = false) const
Definition at line 218 of file itkSphericalPolarFourierGenerator.hxx.
References itk::SphericalPolarFourierGenerator< PreciseType >::EvaluateRadial(), itk::SphericalHarmonicsGenerator< PreciseType >::RealSH(), utlPrintVar2, and utlShowPosition.
Referenced by itk::SphericalPolarFourierRadialGenerator< PreciseType >::Evaluate().
template<class PreciseType > PreciseType itk::SphericalPolarFourierGenerator< PreciseType >::EvaluateRadial (const PreciseType qrValue, const bool isFourier = false) const
Definition at line 231 of file itkSphericalPolarFourierGenerator.hxx.
References itk::SphericalPolarFourierGenerator< PreciseType >::PrintSelf().
Referenced by itk::SphericalPolarFourierGenerator< PreciseType >::Evaluate().
template<class PreciseType = double> int itk::SphericalPolarFourierGenerator< PreciseType >::GetL () const inline
Definition at line 147 of file itkSphericalPolarFourierGenerator.h.
template<class PreciseType = double> virtual int itk::SphericalPolarFourierGenerator< PreciseType >::GetM () virtual
template<class PreciseType = double> int itk::SphericalPolarFourierGenerator< PreciseType >::GetN () const inline
Definition at line 146 of file itkSphericalPolarFourierGenerator.h.
template<class PreciseType = double> virtual const char* itk::SphericalPolarFourierGenerator< PreciseType >::GetNameOfClass () const virtual
Standard part of every itk Object.
template<class PreciseType = double> PreciseType itk::SphericalPolarFourierGenerator< PreciseType >::GetNormalizeFacotr (const bool isFourier = false) const inline
Definition at line 183 of file itkSphericalPolarFourierGenerator.h.
template<class PreciseType = double> double itk::SphericalPolarFourierGenerator< PreciseType >::GetScale () const inline
Definition at line 167 of file itkSphericalPolarFourierGenerator.h.
template<class PreciseType = double> RadialType::SPFType itk::SphericalPolarFourierGenerator< PreciseType >::GetSPFType () const inline
Definition at line 177 of file itkSphericalPolarFourierGenerator.h.
template<class PreciseType = double> static Pointer itk::SphericalPolarFourierGenerator< PreciseType >::New () static
Method for creation through the object factory.
template<class PreciseType = double> void itk::SphericalPolarFourierGenerator< PreciseType >::operator= (const Self &) private
template<class PreciseType > void itk::SphericalPolarFourierGenerator< PreciseType >::PrintSelf (std::ostream & os, Indent indent) const protected
Definition at line 239 of file itkSphericalPolarFourierGenerator.hxx.
References utlException.
Referenced by itk::SphericalPolarFourierGenerator< PreciseType >::EvaluateRadial().
template<class PreciseType = double> void itk::SphericalPolarFourierGenerator< PreciseType >::SetL (const int l) inline
Definition at line 137 of file itkSphericalPolarFourierGenerator.h.
template<class PreciseType = double> virtual void itk::SphericalPolarFourierGenerator< PreciseType >::SetM (int _arg) virtual
template<class PreciseType = double> void itk::SphericalPolarFourierGenerator< PreciseType >::SetN (const int n) inline
Definition at line 129 of file itkSphericalPolarFourierGenerator.h.
template<class PreciseType = double> void itk::SphericalPolarFourierGenerator< PreciseType >::SetNLM (const int n, const int l, const int m) inline
Definition at line 152 of file itkSphericalPolarFourierGenerator.h.
template<class PreciseType = double> void itk::SphericalPolarFourierGenerator< PreciseType >::SetScale (const double scale) inline
Definition at line 159 of file itkSphericalPolarFourierGenerator.h.
template<class PreciseType = double> void itk::SphericalPolarFourierGenerator< PreciseType >::SetSPFType (const SPFType model) inline
Definition at line 169 of file itkSphericalPolarFourierGenerator.h.
Member Data Documentation
template<class PreciseType = double> int itk::SphericalPolarFourierGenerator< PreciseType >::m_M protected
Definition at line 203 of file itkSphericalPolarFourierGenerator.h.
template<class PreciseType = double> RadialPointer itk::SphericalPolarFourierGenerator< PreciseType >::m_Radial protected
Definition at line 202 of file itkSphericalPolarFourierGenerator.h.
The documentation for this class was generated from the following files:
Modules/Math/include/itkSphericalPolarFourierGenerator.h
Modules/Math/include/itkSphericalPolarFourierGenerator.hxx