DMRITool: itk::PeakContainerHelper Class Reference
itk::PeakContainerHelper Class Reference
DiffusionModels
#include <itkPeakContainerHelper.h>
Detailed Description
a VariableLengthVector to contain peaks with different storing types
Author
Jian Cheng (JC), jian..nosp@m.chen.nosp@m.g.198.nosp@m.3@gm.nosp@m.ail.c.nosp@m.om
Definition at line 47 of file itkPeakContainerHelper.h.
Static Public Member Functions
static int GetDimension (const PeakType peakType, const int numberOfPeaks)
static int GetDimensionPerPeak (const PeakType peakType)
static int GetNumberOfPeaks (const PeakType peakType, const int dimension)
template<class ContainerType >
static int GetNumberOfPeaks (const PeakType peakType, const int dimension, const ContainerType &vec)
template<class VectorType = std::vector<double>, class ContainerType >
static VectorType GetPeak (const ContainerType &vec, const int index, const PeakType peakType)
static PeakType GetPeakType (const std::string &str)
template<class ContainerType >
static double GetPeakValue (const ContainerType &vec, const int index, const PeakType peakType)
static std::string GetString (const PeakType peakType)
template<class VectorType , class ContainerType >
static void SetPeak (const VectorType &peak, ContainerType &vec, const int index, const PeakType peakType)
template<class ContainerType >
static void SetPeakValue (const double peakValue, ContainerType &vec, const int index, const PeakType peakType)
Member Function Documentation
static int itk::PeakContainerHelper::GetDimension (const PeakType peakType, const int numberOfPeaks) inline static
Definition at line 96 of file itkPeakContainerHelper.h.
References GetDimensionPerPeak(), itk::NXYZ, itk::NXYZV, utlGlobalException, itk::XYZ, and itk::XYZV.
Referenced by itk::DWIGeneratorBase< TOutputImage, TScalarImage >::AllocateOutputs(), itk::DWIGenerator< TOutputImage, TScalarImage >::GenerateData(), and itk::DWISingleVoxelGenerator< TOutputImage, TScalarImage >::GenerateData().
static int itk::PeakContainerHelper::GetDimensionPerPeak (const PeakType peakType) inline static
Definition at line 83 of file itkPeakContainerHelper.h.
References itk::NXYZ, itk::NXYZV, utlGlobalException, itk::XYZ, and itk::XYZV.
Referenced by itk::MeshFromPeaksImageFilter< TInputImage, TOutputMesh >::GenerateData(), GetDimension(), GetNumberOfPeaks(), GetPeak(), GetPeakValue(), SetPeak(), and SetPeakValue().
static int itk::PeakContainerHelper::GetNumberOfPeaks (const PeakType peakType, const int dimension) inline static
Definition at line 110 of file itkPeakContainerHelper.h.
References GetDimensionPerPeak(), utl::IsInt(), itk::NXYZ, itk::NXYZV, utlGlobalException, utlSAException, itk::XYZ, and itk::XYZV.
Referenced by itk::MeshFromPeaksImageFilter< TInputImage, TOutputMesh >::GenerateData(), itk::DWISingleVoxelGenerator< TOutputImage, TScalarImage >::GenerateData(), and GetNumberOfPeaks().
template<class ContainerType > static int itk::PeakContainerHelper::GetNumberOfPeaks (const PeakType peakType, const int dimension, const ContainerType & vec) inline static
Definition at line 128 of file itkPeakContainerHelper.h.
References GetNumberOfPeaks(), and GetPeak().
template<class VectorType = std::vector<double>, class ContainerType > static VectorType itk::PeakContainerHelper::GetPeak (const ContainerType & vec, const int index, const PeakType peakType) inline static
Definition at line 142 of file itkPeakContainerHelper.h.
References GetDimensionPerPeak(), itk::NXYZ, itk::NXYZV, utlException, itk::XYZ, and itk::XYZV.
Referenced by itk::MeshFromPeaksImageFilter< TInputImage, TOutputMesh >::GenerateData(), itk::DWISingleVoxelGenerator< TOutputImage, TScalarImage >::GenerateData(), and GetNumberOfPeaks().
static PeakType itk::PeakContainerHelper::GetPeakType (const std::string & str) inline static
Definition at line 67 of file itkPeakContainerHelper.h.
References itk::NXYZ, itk::NXYZV, utlGlobalException, itk::XYZ, and itk::XYZV.
Referenced by main().
template<class ContainerType > static double itk::PeakContainerHelper::GetPeakValue (const ContainerType & vec, const int index, const PeakType peakType) inline static
Definition at line 178 of file itkPeakContainerHelper.h.
References GetDimensionPerPeak(), itk::NXYZ, itk::NXYZV, utlException, itk::XYZ, and itk::XYZV.
static std::string itk::PeakContainerHelper::GetString (const PeakType peakType) inline static
Definition at line 51 of file itkPeakContainerHelper.h.
References itk::NXYZ, itk::NXYZV, utlGlobalException, itk::XYZ, and itk::XYZV.
Referenced by itk::MeshFromPeaksImageFilter< TInputImage, TOutputMesh >::PrintSelf(), and itk::DWIGeneratorBase< TOutputImage, TScalarImage >::PrintSelf().
template<class VectorType , class ContainerType > static void itk::PeakContainerHelper::SetPeak (const VectorType & peak, ContainerType & vec, const int index, const PeakType peakType) inline static
Definition at line 161 of file itkPeakContainerHelper.h.
References GetDimensionPerPeak(), itk::NXYZ, itk::NXYZV, utlException, itk::XYZ, and itk::XYZV.
template<class ContainerType > static void itk::PeakContainerHelper::SetPeakValue (const double peakValue, ContainerType & vec, const int index, const PeakType peakType) inline static
Definition at line 194 of file itkPeakContainerHelper.h.
References GetDimensionPerPeak(), itk::NXYZ, itk::NXYZV, utlException, itk::XYZ, and itk::XYZV.
The documentation for this class was generated from the following file:
Modules/DiffusionModels/include/itkPeakContainerHelper.h