DMRITool: itk::SamplingSchemeQSpace1OptEstimationFilter< TSamplingType > Class Template Reference
itk::SamplingSchemeQSpace1OptEstimationFilter< TSamplingType > Class Template Reference
SamplingScheme
#include <itkSamplingSchemeQSpace1OptEstimationFilter.h>
Detailed Description
template<class TSamplingType>
class itk::SamplingSchemeQSpace1OptEstimationFilter< TSamplingType >
incremental estimation of single/multi-shell orientations
Author
Jian Cheng (JC), jian..nosp@m.chen.nosp@m.g.198.nosp@m.3@gm.nosp@m.ail.c.nosp@m.om
Definition at line 30 of file itkSamplingSchemeQSpace1OptEstimationFilter.h.
Public Types
typedef SmartPointer< const Self > ConstPointer
typedef Superclass::Index2DVectorPointer Index2DVectorPointer
typedef Superclass::Index2DVectorType Index2DVectorType
typedef Superclass::IndexVectorType IndexVectorType
typedef Superclass::MatrixPointer MatrixPointer
typedef Superclass::MatrixType MatrixType
typedef SmartPointer< Self > Pointer
typedef TSamplingType::PointType PointType
typedef SamplingType::Pointer SamplingPointer
typedef TSamplingType SamplingType
typedef SamplingSchemeQSpace1OptEstimationFilter Self
typedef Superclass::STDVectorPointer STDVectorPointer
typedef Superclass::STDVectorType STDVectorType
typedef SamplingSchemeQSpaceEstimationFilter< TSamplingType > Superclass
typedef Superclass::ValueType ValueType
Public Types inherited from itk::SamplingSchemeQSpaceEstimationFilter< TSamplingType >
typedef SmartPointer< const Self > ConstPointer
enum CriteriaType {
DISTANCE =0,
ELECTROSTATIC
}
typedef SamplingType::Index2DVectorPointer Index2DVectorPointer
typedef SamplingType::Index2DVectorType Index2DVectorType
typedef SamplingType::IndexVectorType IndexVectorType
typedef SamplingType::MatrixPointer MatrixPointer
typedef SamplingType::MatrixType MatrixType
typedef SmartPointer< Self > Pointer
typedef SamplingType::ConstPointer SamplingConstPointer
typedef SamplingType::Pointer SamplingPointer
typedef TSamplingType SamplingType
typedef SamplingSchemeQSpaceEstimationFilter Self
typedef SamplingType::STDVectorPointer STDVectorPointer
typedef SamplingType::STDVectorType STDVectorType
typedef LightProcessObject Superclass
typedef SamplingType::ValueType ValueType
Public Member Functions
virtual ::itk::LightObject::Pointer CreateAnother (void) const
void GenerateData () ITK_OVERRIDE
virtual const char * GetNameOfClass () const
itkSetGetMacro (TessellationOrder, unsigned int)
itkSetGetMacro (FineOrientations, MatrixPointer)
Public Member Functions inherited from itk::SamplingSchemeQSpaceEstimationFilter< TSamplingType >
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual CriteriaType GetCriteriaType ()
virtual double GetElectrostaticOrder ()
virtual IndexVectorType GetNumbersInShell ()
virtual const SamplingType * GetOutputOrientations () const
virtual double GetWeightForSingleShell ()
bool IsSetInitialization () const
itkGetObjectMacro (InitialOrientations, SamplingType)
itkGetObjectMacro (OutputOrientations, SamplingType)
itkSetNDebugMacro (NumbersInShell, IndexVectorType)
virtual void SetCriteriaType (CriteriaType _arg)
virtual void SetElectrostaticOrder (double _arg)
virtual void SetInitialOrientations (SamplingType *_arg)
virtual void SetWeightForSingleShell (double _arg)
Static Public Member Functions
static Pointer New ()
Static Public Member Functions inherited from itk::SamplingSchemeQSpaceEstimationFilter< TSamplingType >
static Pointer New ()
Protected Member Functions
void Initialization () ITK_OVERRIDE
SamplingSchemeQSpace1OptEstimationFilter ()
~SamplingSchemeQSpace1OptEstimationFilter ()
Protected Member Functions inherited from itk::SamplingSchemeQSpaceEstimationFilter< TSamplingType >
SamplingSchemeQSpaceEstimationFilter ()
~SamplingSchemeQSpaceEstimationFilter ()
Protected Attributes
MatrixPointer m_FineOrientations
SamplingPointer m_FineScheme
unsigned int m_TessellationOrder
Protected Attributes inherited from itk::SamplingSchemeQSpaceEstimationFilter< TSamplingType >
CriteriaType m_CriteriaType
double m_ElectrostaticOrder
SamplingPointer m_InitialOrientations
IndexVectorType m_NumbersInShell
SamplingPointer m_OutputOrientations
double m_WeightForSingleShell
Private Member Functions
void operator= (const Self &)
SamplingSchemeQSpace1OptEstimationFilter (const Self &)
Member Typedef Documentation
template<class TSamplingType > typedef SmartPointer< const Self > itk::SamplingSchemeQSpace1OptEstimationFilter< TSamplingType >::ConstPointer
Definition at line 39 of file itkSamplingSchemeQSpace1OptEstimationFilter.h.
template<class TSamplingType > typedef Superclass::Index2DVectorPointer itk::SamplingSchemeQSpace1OptEstimationFilter< TSamplingType >::Index2DVectorPointer
Definition at line 52 of file itkSamplingSchemeQSpace1OptEstimationFilter.h.
template<class TSamplingType > typedef Superclass::Index2DVectorType itk::SamplingSchemeQSpace1OptEstimationFilter< TSamplingType >::Index2DVectorType
Definition at line 51 of file itkSamplingSchemeQSpace1OptEstimationFilter.h.
template<class TSamplingType > typedef Superclass::IndexVectorType itk::SamplingSchemeQSpace1OptEstimationFilter< TSamplingType >::IndexVectorType
Definition at line 50 of file itkSamplingSchemeQSpace1OptEstimationFilter.h.
template<class TSamplingType > typedef Superclass::MatrixPointer itk::SamplingSchemeQSpace1OptEstimationFilter< TSamplingType >::MatrixPointer
Definition at line 47 of file itkSamplingSchemeQSpace1OptEstimationFilter.h.
template<class TSamplingType > typedef Superclass::MatrixType itk::SamplingSchemeQSpace1OptEstimationFilter< TSamplingType >::MatrixType
Definition at line 46 of file itkSamplingSchemeQSpace1OptEstimationFilter.h.
template<class TSamplingType > typedef SmartPointer< Self > itk::SamplingSchemeQSpace1OptEstimationFilter< TSamplingType >::Pointer
Definition at line 38 of file itkSamplingSchemeQSpace1OptEstimationFilter.h.
template<class TSamplingType > typedef TSamplingType::PointType itk::SamplingSchemeQSpace1OptEstimationFilter< TSamplingType >::PointType
Definition at line 43 of file itkSamplingSchemeQSpace1OptEstimationFilter.h.
template<class TSamplingType > typedef SamplingType::Pointer itk::SamplingSchemeQSpace1OptEstimationFilter< TSamplingType >::SamplingPointer
Definition at line 42 of file itkSamplingSchemeQSpace1OptEstimationFilter.h.
template<class TSamplingType > typedef TSamplingType itk::SamplingSchemeQSpace1OptEstimationFilter< TSamplingType >::SamplingType
Definition at line 41 of file itkSamplingSchemeQSpace1OptEstimationFilter.h.
template<class TSamplingType > typedef SamplingSchemeQSpace1OptEstimationFilter itk::SamplingSchemeQSpace1OptEstimationFilter< TSamplingType >::Self
Standard class typedefs.
Definition at line 36 of file itkSamplingSchemeQSpace1OptEstimationFilter.h.
template<class TSamplingType > typedef Superclass::STDVectorPointer itk::SamplingSchemeQSpace1OptEstimationFilter< TSamplingType >::STDVectorPointer
Definition at line 49 of file itkSamplingSchemeQSpace1OptEstimationFilter.h.
template<class TSamplingType > typedef Superclass::STDVectorType itk::SamplingSchemeQSpace1OptEstimationFilter< TSamplingType >::STDVectorType
Definition at line 48 of file itkSamplingSchemeQSpace1OptEstimationFilter.h.
template<class TSamplingType > typedef SamplingSchemeQSpaceEstimationFilter<TSamplingType> itk::SamplingSchemeQSpace1OptEstimationFilter< TSamplingType >::Superclass
Definition at line 37 of file itkSamplingSchemeQSpace1OptEstimationFilter.h.
template<class TSamplingType > typedef Superclass::ValueType itk::SamplingSchemeQSpace1OptEstimationFilter< TSamplingType >::ValueType
Definition at line 45 of file itkSamplingSchemeQSpace1OptEstimationFilter.h.
Constructor & Destructor Documentation
template<class TSamplingType > itk::SamplingSchemeQSpace1OptEstimationFilter< TSamplingType >::SamplingSchemeQSpace1OptEstimationFilter () protected
Definition at line 24 of file itkSamplingSchemeQSpace1OptEstimationFilter.hxx.
References itk::SamplingSchemeQSpace1OptEstimationFilter< TSamplingType >::Initialization().
template<class TSamplingType > itk::SamplingSchemeQSpace1OptEstimationFilter< TSamplingType >::~SamplingSchemeQSpace1OptEstimationFilter () inline protected
Definition at line 66 of file itkSamplingSchemeQSpace1OptEstimationFilter.h.
References ITK_OVERRIDE.
template<class TSamplingType > itk::SamplingSchemeQSpace1OptEstimationFilter< TSamplingType >::SamplingSchemeQSpace1OptEstimationFilter (const Self &) private
Member Function Documentation
template<class TSamplingType > virtual::itk::LightObject::Pointer itk::SamplingSchemeQSpace1OptEstimationFilter< TSamplingType >::CreateAnother (void) const
template<class TSamplingType > void itk::SamplingSchemeQSpace1OptEstimationFilter< TSamplingType >::GenerateData (void) virtual
Reimplemented from itk::SamplingSchemeQSpaceEstimationFilter< TSamplingType >.
Definition at line 61 of file itkSamplingSchemeQSpace1OptEstimationFilter.hxx.
References utl::Abs(), utl::argmax2(), utl::IsLogDebug(), utl::ProductUtlMMt(), utl::NDArrayBase< T, 1 >::Size(), and utlPrintVar.
Referenced by itk::SamplingSchemeQSpace1OptEstimationFilter< TSamplingType >::Initialization().
template<class TSamplingType > virtual const char* itk::SamplingSchemeQSpace1OptEstimationFilter< TSamplingType >::GetNameOfClass () const virtual
Standard Macros
Reimplemented from itk::SamplingSchemeQSpaceEstimationFilter< TSamplingType >.
template<class TSamplingType > void itk::SamplingSchemeQSpace1OptEstimationFilter< TSamplingType >::Initialization () protected virtual
Reimplemented from itk::SamplingSchemeQSpaceEstimationFilter< TSamplingType >.
Definition at line 35 of file itkSamplingSchemeQSpace1OptEstimationFilter.hxx.
References CARTESIAN_TO_CARTESIAN, DIRECTION_NODUPLICATE, itk::SamplingSchemeQSpace1OptEstimationFilter< TSamplingType >::GenerateData(), and utlGlobalException.
Referenced by itk::SamplingSchemeQSpace1OptEstimationFilter< TSamplingType >::SamplingSchemeQSpace1OptEstimationFilter().
template<class TSamplingType > itk::SamplingSchemeQSpace1OptEstimationFilter< TSamplingType >::itkSetGetMacro (TessellationOrder , unsigned int)
template<class TSamplingType > itk::SamplingSchemeQSpace1OptEstimationFilter< TSamplingType >::itkSetGetMacro (FineOrientations , MatrixPointer)
template<class TSamplingType > static Pointer itk::SamplingSchemeQSpace1OptEstimationFilter< TSamplingType >::New () static
template<class TSamplingType > void itk::SamplingSchemeQSpace1OptEstimationFilter< TSamplingType >::operator= (const Self &) private
Member Data Documentation
template<class TSamplingType > MatrixPointer itk::SamplingSchemeQSpace1OptEstimationFilter< TSamplingType >::m_FineOrientations protected
It is the input data or generated from m_TessellationOrder
Definition at line 74 of file itkSamplingSchemeQSpace1OptEstimationFilter.h.
template<class TSamplingType > SamplingPointer itk::SamplingSchemeQSpace1OptEstimationFilter< TSamplingType >::m_FineScheme protected
Definition at line 76 of file itkSamplingSchemeQSpace1OptEstimationFilter.h.
template<class TSamplingType > unsigned int itk::SamplingSchemeQSpace1OptEstimationFilter< TSamplingType >::m_TessellationOrder protected
the order of tessellation for the orignal fine mesh
Definition at line 71 of file itkSamplingSchemeQSpace1OptEstimationFilter.h.
The documentation for this class was generated from the following files:
Modules/SamplingScheme/include/itkSamplingSchemeQSpace1OptEstimationFilter.h
Modules/SamplingScheme/include/itkSamplingSchemeQSpace1OptEstimationFilter.hxx