DMRITool: itk::BasisMatrixGenerator< TElement > Class Template Reference
itk::BasisMatrixGenerator< TElement > Class Template Reference
DiffusionModels
#include <itkBasisMatrixGenerator.h>
Detailed Description
template<typename TElement = double>
class itk::BasisMatrixGenerator< TElement >
Generate basis matrix.
Author
Jian Cheng (jian..nosp@m.chen.nosp@m.g.198.nosp@m.3@gm.nosp@m.ail.c.nosp@m.om)
Definition at line 40 of file itkBasisMatrixGenerator.h.
Public Types
typedef SmartPointer< const Self > ConstPointer
typedef utl_shared_ptr< MatrixType > MatrixPointer
typedef utl::NDArray< double, 2 > MatrixType
enum OutputType {
DWI =0,
EAP,
ODF
}
typedef SmartPointer< Self > Pointer
typedef SamplingSchemeQSpaceType::Pointer SamplingSchemeQSpacePointer
typedef SamplingSchemeQSpace< double > SamplingSchemeQSpaceType
typedef SamplingSchemeRSpaceType::Pointer SamplingSchemeRSpacePointer
typedef SamplingScheme3D< double > SamplingSchemeRSpaceType
typedef BasisMatrixGenerator Self
typedef utl_shared_ptr< STDVectorType > STDVectorPointer
typedef std::vector< double > STDVectorType
typedef Object Superclass
typedef utl_shared_ptr< VectorType > VectorPointer
typedef utl::NDArray< double, 1 > VectorType
Public Member Functions
virtual void ComputeBasisMatrix ()
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual void Flip (const int flipx, const int flipy, const int flipz)
virtual MatrixPointer GetBasisMatrix () const
virtual double GetMD0 ()
virtual const char * GetNameOfClass () const
virtual int GetNumberOfBasis () const
virtual int GetNumberOfSamples () const
virtual int GetODFOrder ()
virtual OutputType GetOutputType ()
virtual MatrixPointer GetQBasisMatrixForDWI ()
virtual MatrixPointer GetRBasisMatrixForEAP ()
virtual MatrixPointer GetRBasisMatrixForODF ()
itkGetObjectMacro (SamplingSchemeQSpace, SamplingSchemeQSpaceType)
itkGetObjectMacro (SamplingSchemeRSpace, SamplingSchemeRSpaceType)
virtual void SetMD0 (double _arg)
virtual void SetODFOrder (int _arg)
virtual void SetOutputType (OutputType _arg)
virtual void SetSamplingSchemeQSpace (SamplingSchemeQSpaceType *_arg)
virtual void SetSamplingSchemeRSpace (SamplingSchemeRSpaceType *_arg)
Static Public Member Functions
static Pointer New ()
Protected Member Functions
BasisMatrixGenerator ()
LightObject::Pointer InternalClone () const ITK_OVERRIDE
void PrintSelf (std::ostream &os, Indent indent) const ITK_OVERRIDE
virtual void VerifyInputParameters () const
virtual ~BasisMatrixGenerator ()
Protected Attributes
double m_MD0
int m_ODFOrder
OutputType m_OutputType
MatrixPointer m_QBasisMatrixForDWI
MatrixPointer m_RBasisMatrixForEAP
MatrixPointer m_RBasisMatrixForODF
SamplingSchemeQSpacePointer m_SamplingSchemeQSpace
SamplingSchemeRSpacePointer m_SamplingSchemeRSpace
Private Member Functions
BasisMatrixGenerator (const Self &)
void operator= (const Self &)
Member Typedef Documentation
template<typename TElement = double> typedef SmartPointer<const Self> itk::BasisMatrixGenerator< TElement >::ConstPointer
Definition at line 47 of file itkBasisMatrixGenerator.h.
template<typename TElement = double> typedef utl_shared_ptr<MatrixType> itk::BasisMatrixGenerator< TElement >::MatrixPointer
Definition at line 58 of file itkBasisMatrixGenerator.h.
template<typename TElement = double> typedef utl::NDArray<double,2> itk::BasisMatrixGenerator< TElement >::MatrixType
Save the template parameters.
Definition at line 53 of file itkBasisMatrixGenerator.h.
template<typename TElement = double> typedef SmartPointer<Self> itk::BasisMatrixGenerator< TElement >::Pointer
Definition at line 46 of file itkBasisMatrixGenerator.h.
template<typename TElement = double> typedef SamplingSchemeQSpaceType::Pointer itk::BasisMatrixGenerator< TElement >::SamplingSchemeQSpacePointer
Definition at line 64 of file itkBasisMatrixGenerator.h.
template<typename TElement = double> typedef SamplingSchemeQSpace<double> itk::BasisMatrixGenerator< TElement >::SamplingSchemeQSpaceType
Definition at line 63 of file itkBasisMatrixGenerator.h.
template<typename TElement = double> typedef SamplingSchemeRSpaceType::Pointer itk::BasisMatrixGenerator< TElement >::SamplingSchemeRSpacePointer
Definition at line 67 of file itkBasisMatrixGenerator.h.
template<typename TElement = double> typedef SamplingScheme3D<double> itk::BasisMatrixGenerator< TElement >::SamplingSchemeRSpaceType
Definition at line 66 of file itkBasisMatrixGenerator.h.
template<typename TElement = double> typedef BasisMatrixGenerator itk::BasisMatrixGenerator< TElement >::Self
Standard class typedefs.
Definition at line 44 of file itkBasisMatrixGenerator.h.
template<typename TElement = double> typedef utl_shared_ptr<STDVectorType > itk::BasisMatrixGenerator< TElement >::STDVectorPointer
Definition at line 61 of file itkBasisMatrixGenerator.h.
template<typename TElement = double> typedef std::vector<double> itk::BasisMatrixGenerator< TElement >::STDVectorType
Definition at line 60 of file itkBasisMatrixGenerator.h.
template<typename TElement = double> typedef Object itk::BasisMatrixGenerator< TElement >::Superclass
Definition at line 45 of file itkBasisMatrixGenerator.h.
template<typename TElement = double> typedef utl_shared_ptr<VectorType> itk::BasisMatrixGenerator< TElement >::VectorPointer
Definition at line 59 of file itkBasisMatrixGenerator.h.
template<typename TElement = double> typedef utl::NDArray<double,1> itk::BasisMatrixGenerator< TElement >::VectorType
Definition at line 57 of file itkBasisMatrixGenerator.h.
Member Enumeration Documentation
template<typename TElement = double> enum itk::BasisMatrixGenerator::OutputType
Enumerator
DWI
EAP
ODF
Definition at line 75 of file itkBasisMatrixGenerator.h.
Constructor & Destructor Documentation
template<typename TElement > itk::BasisMatrixGenerator< TElement >::BasisMatrixGenerator () protected
Definition at line 28 of file itkBasisMatrixGenerator.hxx.
References itk::BasisMatrixGenerator< TElement >::InternalClone().
template<typename TElement = double> virtual itk::BasisMatrixGenerator< TElement >::~BasisMatrixGenerator () inline protected virtual
Definition at line 138 of file itkBasisMatrixGenerator.h.
References ITK_OVERRIDE.
template<typename TElement = double> itk::BasisMatrixGenerator< TElement >::BasisMatrixGenerator (const Self &) private
Member Function Documentation
template<typename TElement = double> virtual void itk::BasisMatrixGenerator< TElement >::ComputeBasisMatrix () inline virtual
Reimplemented in itk::TensorBasisMatrixGenerator< TElement >.
Definition at line 98 of file itkBasisMatrixGenerator.h.
template<typename TElement = double> virtual::itk::LightObject::Pointer itk::BasisMatrixGenerator< TElement >::CreateAnother (void) const
template<typename TElement = double> virtual void itk::BasisMatrixGenerator< TElement >::Flip (const int flipx, const int flipy, const int flipz) inline virtual
Reimplemented in itk::DiscreteBasisMatrixGenerator< TElement >.
Definition at line 102 of file itkBasisMatrixGenerator.h.
template<typename TElement = double> virtual MatrixPointer itk::BasisMatrixGenerator< TElement >::GetBasisMatrix () const inline virtual
Definition at line 124 of file itkBasisMatrixGenerator.h.
template<typename TElement = double> virtual double itk::BasisMatrixGenerator< TElement >::GetMD0 () virtual
template<typename TElement = double> virtual const char* itk::BasisMatrixGenerator< TElement >::GetNameOfClass () const virtual
Standard part of every itk Object.
Reimplemented in itk::TensorBasisMatrixGenerator< TElement >, and itk::DiscreteBasisMatrixGenerator< TElement >.
template<typename TElement = double> virtual int itk::BasisMatrixGenerator< TElement >::GetNumberOfBasis () const inline virtual
Reimplemented in itk::DiscreteBasisMatrixGenerator< TElement >.
Definition at line 120 of file itkBasisMatrixGenerator.h.
template<typename TElement = double> virtual int itk::BasisMatrixGenerator< TElement >::GetNumberOfSamples () const inline virtual
Definition at line 116 of file itkBasisMatrixGenerator.h.
template<typename TElement = double> virtual int itk::BasisMatrixGenerator< TElement >::GetODFOrder () virtual
template<typename TElement = double> virtual OutputType itk::BasisMatrixGenerator< TElement >::GetOutputType () virtual
template<typename TElement = double> virtual MatrixPointer itk::BasisMatrixGenerator< TElement >::GetQBasisMatrixForDWI () virtual
template<typename TElement = double> virtual MatrixPointer itk::BasisMatrixGenerator< TElement >::GetRBasisMatrixForEAP () virtual
template<typename TElement = double> virtual MatrixPointer itk::BasisMatrixGenerator< TElement >::GetRBasisMatrixForODF () virtual
template<typename TElement > LightObject::Pointer itk::BasisMatrixGenerator< TElement >::InternalClone () const protected
Definition at line 44 of file itkBasisMatrixGenerator.hxx.
References itk::BasisMatrixGenerator< TElement >::PrintSelf(), and utlShowPosition.
Referenced by itk::BasisMatrixGenerator< TElement >::BasisMatrixGenerator().
template<typename TElement = double> itk::BasisMatrixGenerator< TElement >::itkGetObjectMacro (SamplingSchemeQSpace , SamplingSchemeQSpaceType)
template<typename TElement = double> itk::BasisMatrixGenerator< TElement >::itkGetObjectMacro (SamplingSchemeRSpace , SamplingSchemeRSpaceType)
template<typename TElement = double> static Pointer itk::BasisMatrixGenerator< TElement >::New () static
Method for creation through the object factory.
template<typename TElement = double> void itk::BasisMatrixGenerator< TElement >::operator= (const Self &) private
template<typename TElement > void itk::BasisMatrixGenerator< TElement >::PrintSelf (std::ostream & os, Indent indent) const protected
Definition at line 73 of file itkBasisMatrixGenerator.hxx.
References PrintEnum3, utl::PrintUtlMatrix(), PrintVar2, and itk::BasisMatrixGenerator< TElement >::VerifyInputParameters().
Referenced by itk::BasisMatrixGenerator< TElement >::InternalClone().
template<typename TElement = double> virtual void itk::BasisMatrixGenerator< TElement >::SetMD0 (double _arg) virtual
template<typename TElement = double> virtual void itk::BasisMatrixGenerator< TElement >::SetODFOrder (int _arg) virtual
template<typename TElement = double> virtual void itk::BasisMatrixGenerator< TElement >::SetOutputType (OutputType _arg) virtual
template<typename TElement = double> virtual void itk::BasisMatrixGenerator< TElement >::SetSamplingSchemeQSpace (SamplingSchemeQSpaceType * _arg) virtual
template<typename TElement = double> virtual void itk::BasisMatrixGenerator< TElement >::SetSamplingSchemeRSpace (SamplingSchemeRSpaceType * _arg) virtual
template<typename TElement > void itk::BasisMatrixGenerator< TElement >::VerifyInputParameters () const protected virtual
Reimplemented in itk::DiscreteBasisMatrixGenerator< TElement >, and itk::TensorBasisMatrixGenerator< TElement >.
Definition at line 90 of file itkBasisMatrixGenerator.hxx.
References utlGlobalException, and utlSAGlobalException.
Referenced by itk::BasisMatrixGenerator< TElement >::PrintSelf().
Member Data Documentation
template<typename TElement = double> double itk::BasisMatrixGenerator< TElement >::m_MD0 protected
typical MD value for typical scale
Definition at line 158 of file itkBasisMatrixGenerator.h.
template<typename TElement = double> int itk::BasisMatrixGenerator< TElement >::m_ODFOrder protected
for ODF
Definition at line 161 of file itkBasisMatrixGenerator.h.
template<typename TElement = double> OutputType itk::BasisMatrixGenerator< TElement >::m_OutputType protected
Definition at line 163 of file itkBasisMatrixGenerator.h.
template<typename TElement = double> MatrixPointer itk::BasisMatrixGenerator< TElement >::m_QBasisMatrixForDWI protected
Definition at line 152 of file itkBasisMatrixGenerator.h.
template<typename TElement = double> MatrixPointer itk::BasisMatrixGenerator< TElement >::m_RBasisMatrixForEAP protected
Definition at line 154 of file itkBasisMatrixGenerator.h.
template<typename TElement = double> MatrixPointer itk::BasisMatrixGenerator< TElement >::m_RBasisMatrixForODF protected
Definition at line 155 of file itkBasisMatrixGenerator.h.
template<typename TElement = double> SamplingSchemeQSpacePointer itk::BasisMatrixGenerator< TElement >::m_SamplingSchemeQSpace protected
Sampling Scheme in q-space
Definition at line 147 of file itkBasisMatrixGenerator.h.
template<typename TElement = double> SamplingSchemeRSpacePointer itk::BasisMatrixGenerator< TElement >::m_SamplingSchemeRSpace protected
Sampling Scheme in r-space
Definition at line 150 of file itkBasisMatrixGenerator.h.
The documentation for this class was generated from the following files:
Modules/DiffusionModels/include/itkBasisMatrixGenerator.h
Modules/DiffusionModels/include/itkBasisMatrixGenerator.hxx