DMRITool: itk::MeshFromTensorImageFilter< TInputImage, TOutputMesh > Class Template Reference
itk::MeshFromTensorImageFilter< TInputImage, TOutputMesh > Class Template Reference
Visualization
#include <itkMeshFromTensorImageFilter.h>
Detailed Description
template<class TInputImage, class TOutputMesh = vtkPolyData>
class itk::MeshFromTensorImageFilter< TInputImage, TOutputMesh >
Compute mesh from a tensor image.
The tensors are assumed to be stored in TENSOR_UPPER_TRIANGULAR format [xx, xy, xz, yy, yz, zz].
Author
Jian Cheng (jian..nosp@m.chen.nosp@m.g.198.nosp@m.3@gm.nosp@m.ail.c.nosp@m.om)
Definition at line 34 of file itkMeshFromTensorImageFilter.h.
Public Types
typedef SmartPointer< const Self > ConstPointer
enum GlyphShapeType {
GLYPH_LINE =0,
GLYPH_ARROW,
GLYPH_DISK,
GLYPH_CYLINDER,
GLYPH_CUBE,
GLYPH_SPHERE,
GLYPH_SUPERQUADRIC
}
typedef InputImageType::ConstPointer InputImageConstPointer
typedef InputImageType::IndexType InputImageIndexType
typedef InputImageType::PixelType InputImagePixelType
typedef InputImageType::Pointer InputImagePointer
typedef InputImageType::PointType InputImagePointType
typedef InputImageType::RegionType InputImageRegionType
typedef InputImageType::SizeType InputImageSizeType
typedef InputImageType::SizeValueType InputImageSizeValueType
typedef InputImageType::SpacingType InputImageSpacingType
typedef TInputImage InputImageType
typedef Superclass::MatrixPointer MatrixPointer
typedef Superclass::MatrixType MatrixType
typedef Superclass::OutputMeshCellArrayType OutputMeshCellArrayType
typedef Superclass::OutputMeshPointsType OutputMeshPointsType
typedef Superclass::OutputMeshPolyDataPointer OutputMeshPolyDataPointer
typedef TOutputMesh OutputMeshPolyDataType
typedef Superclass::OutputMeshRGBType OutputMeshRGBType
typedef Superclass::OutputMeshScalarType OutputMeshScalarType
typedef SmartPointer< Self > Pointer
typedef ScalarImageType::Pointer ScalarImagePointer
typedef Image< double, 3 > ScalarImageType
typedef MeshFromTensorImageFilter Self
typedef Superclass::STDVectorPointer STDVectorPointer
typedef Superclass::STDVectorType STDVectorType
typedef MeshFromImageImageFilter< TInputImage, TOutputMesh > Superclass
enum TensorColorSchemeType {
COLOR_NONE =0,
COLOR_BY_DIRECTION,
COLOR_BY_FA,
COLOR_BY_MD,
COLOR_BY_IMAGE
}
typedef vtkTensorGlyph TensorGlyphType
typedef Superclass::VectorPointer VectorPointer
typedef Superclass::VectorType VectorType
Public Types inherited from itk::MeshFromImageImageFilter< TInputImage, TOutputMesh >
enum ColorSchemeType {
UNKNOWN =0,
FIXED,
DIRECTION,
MAGNITUDE
}
typedef SmartPointer< const Self > ConstPointer
typedef InputImageType::ConstPointer InputImageConstPointer
typedef InputImageType::IndexType InputImageIndexType
typedef InputImageType::PixelType InputImagePixelType
typedef InputImageType::Pointer InputImagePointer
typedef InputImageType::PointType InputImagePointType
typedef InputImageType::RegionType InputImageRegionType
typedef InputImageType::SizeType InputImageSizeType
typedef InputImageType::SizeValueType InputImageSizeValueType
typedef InputImageType::SpacingType InputImageSpacingType
typedef TInputImage InputImageType
typedef utl_shared_ptr< MatrixType > MatrixPointer
typedef utl::NDArray< double, 2 > MatrixType
typedef vtkCellArray OutputMeshCellArrayType
typedef vtkPoints OutputMeshPointsType
typedef vtkSmartPointer< OutputMeshPolyDataType > OutputMeshPolyDataPointer
typedef TOutputMesh OutputMeshPolyDataType
typedef vtkUnsignedCharArray OutputMeshRGBType
typedef vtkDoubleArray OutputMeshScalarType
typedef SmartPointer< Self > Pointer
typedef MeshFromImageImageFilter Self
typedef utl_shared_ptr< STDVectorType > STDVectorPointer
typedef std::vector< double > STDVectorType
typedef MaskedImageToImageFilter< TInputImage, TInputImage > Superclass
typedef utl_shared_ptr< VectorType > VectorPointer
typedef utl::NDArray< double, 1 > VectorType
Public Types inherited from itk::MaskedImageToImageFilter< TInputImage, TInputImage >
typedef SmartPointer< const Self > ConstPointer
typedef InputImageType::ConstPointer InputImageConstPointer
typedef InputImageType::IndexType InputImageIndexType
typedef InputImageType::PixelType InputImagePixelType
typedef InputImageType::Pointer InputImagePointer
typedef InputImageType::RegionType InputImageRegionType
typedef InputImageType::SizeType InputImageSizeType
typedef InputImageType::SpacingType InputImageSpacingType
typedef TInputImage InputImageType
typedef LoggerType::Pointer LoggerPointer
typedef ThreadLogger LoggerType
typedef utl_shared_ptr< LoggerVectorType > LoggerVectorPointer
typedef std::vector< LoggerPointer > LoggerVectorType
typedef MaskImageType::Pointer MaskImagePointer
typedef Image< double, 3 > MaskImageType
typedef OutputImageType::IndexType OutputImageIndexType
typedef OutputImageType::PixelType OutputImagePixelType
typedef OutputImageType::Pointer OutputImagePointer
typedef OutputImageType::RegionType OutputImageRegionType
typedef OutputImageType::SizeType OutputImageSizeType
typedef OutputImageType::SpacingType OutputImageSpacingType
typedef TInputImage OutputImageType
typedef SmartPointer< Self > Pointer
typedef MaskedImageToImageFilter Self
typedef ImageToImageFilter< TInputImage, TInputImage > Superclass
Public Member Functions
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual int GetGlyphResolution ()
virtual const char * GetNameOfClass () const
itkSetGetMacro (ScalarImage, ScalarImagePointer)
itkSetGetMacro (TensorColorScheme, TensorColorSchemeType)
itkSetGetMacro (ShapeMode, GlyphShapeType)
void SetGlyphResolution (int res)
void SetGlyphShape (GlyphShapeType i)
void SetGlyphShapeToArrow ()
void SetGlyphShapeToCube ()
void SetGlyphShapeToCylinder ()
void SetGlyphShapeToDisk ()
void SetGlyphShapeToLine ()
void SetGlyphShapeToSphere ()
void SetGlyphShapeToSuperquadric ()
Public Member Functions inherited from itk::MeshFromImageImageFilter< TInputImage, TOutputMesh >
virtual ::itk::LightObject::Pointer CreateAnother (void) const
std::vector< int > GetBoxView () const
virtual ColorSchemeType GetColorScheme ()
std::vector< int > GetFlip () const
OutputMeshPolyDataPointer GetOutput ()
virtual double GetScale ()
std::vector< int > GetSliceView () const
void SetBoxView (const int x0, const int x1, const int y0, const int y1, const int z0, const int z1)
virtual void SetColorScheme (ColorSchemeType _arg)
void SetFlip (const int flipx, const int flipy, const int flipz)
virtual void SetScale (double _arg)
void SetSliceView (const int coronal, const int sagittal, const int transverse)
Public Member Functions inherited from itk::MaskedImageToImageFilter< TInputImage, TInputImage >
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual const LoggerType * GetLogger () const
virtual const MaskImageType * GetMaskImage () const
bool IsMaskUsed ()
itkGetObjectMacro (MaskImage, MaskImageType)
itkGetObjectMacro (Logger, LoggerType)
itkSetGetMacro (LogLevel, int)
virtual void SetLogger (LoggerType *_arg)
virtual void SetMaskImage (MaskImageType *_arg)
void SetMaskImage (const std::string &file)
Static Public Member Functions
static double GetScalarCodeFromTensor (const DiffusionTensor< double > &tensor, TensorColorSchemeType colorScheme)
static Pointer New ()
Static Public Member Functions inherited from itk::MeshFromImageImageFilter< TInputImage, TOutputMesh >
static Pointer New ()
Static Public Member Functions inherited from itk::MaskedImageToImageFilter< TInputImage, TInputImage >
static Pointer New ()
Protected Member Functions
virtual void GenerateData () ITK_OVERRIDE
LightObject::Pointer InternalClone () const ITK_OVERRIDE
MeshFromTensorImageFilter ()
void PrintSelf (std::ostream &os, Indent indent) const ITK_OVERRIDE
void VerifyInputParameters () const ITK_OVERRIDE
~MeshFromTensorImageFilter ()
Protected Member Functions inherited from itk::MeshFromImageImageFilter< TInputImage, TOutputMesh >
virtual void AllocateOutputs () ITK_OVERRIDE
virtual void GenerateOutputInformation () ITK_OVERRIDE
LightObject::Pointer InternalClone () const ITK_OVERRIDE
virtual bool IsPixelIndexVisible (const InputImageIndexType &index)
MeshFromImageImageFilter ()
~MeshFromImageImageFilter ()
Protected Member Functions inherited from itk::MaskedImageToImageFilter< TInputImage, TInputImage >
void CreateLoggerVector ()
virtual void InitializeThreadedLibraries ()
LightObject::Pointer InternalClone () const ITK_OVERRIDE
MaskedImageToImageFilter ()
std::string ThreadIDToString () const
virtual void VerifyMaskInformation () const
void WriteLogger (const std::string &str, const LoggerBase::PriorityLevelType level=LoggerBase::DEBUG) const
virtual ~MaskedImageToImageFilter ()
Protected Attributes
vtkSmartPointer< TensorGlyphType > m_Glyph = TensorGlyphType::New()
int m_GlyphResolution =10
ScalarImagePointer m_ScalarImage = ScalarImageType::New()
vtkSmartPointer< vtkPolyDataAlgorithm > m_Shape = vtkPolyDataAlgorithm::New()
GlyphShapeType m_ShapeMode = GLYPH_SPHERE
TensorColorSchemeType m_TensorColorScheme =COLOR_BY_DIRECTION
Protected Attributes inherited from itk::MeshFromImageImageFilter< TInputImage, TOutputMesh >
std::vector< int > m_BoxView = std::vector<int>(6,-1)
ColorSchemeType m_ColorScheme =UNKNOWN
std::vector< int > m_Flip = std::vector<int>(3, 0)
OutputMeshPolyDataPointer m_Mesh = OutputMeshPolyDataType::New()
double m_Scale =1.0
std::vector< int > m_SliceView = std::vector<int>(3,-1)
Protected Attributes inherited from itk::MaskedImageToImageFilter< TInputImage, TInputImage >
LoggerPointer m_Logger
LoggerVectorPointer m_LoggerVector
int m_LogLevel
MaskImagePointer m_MaskImage
int m_ThreadID
Private Member Functions
MeshFromTensorImageFilter (const Self &)
void operator= (const Self &)
Additional Inherited Members
Static Public Attributes inherited from itk::MeshFromImageImageFilter< TInputImage, TOutputMesh >
static const unsigned int OrientationDimension = 3
Static Public Attributes inherited from itk::MaskedImageToImageFilter< TInputImage, TInputImage >
static const unsigned int InputImageDimension
static const unsigned int OutputImageDimension
Member Typedef Documentation
template<class TInputImage , class TOutputMesh = vtkPolyData> typedef SmartPointer<const Self> itk::MeshFromTensorImageFilter< TInputImage, TOutputMesh >::ConstPointer
Definition at line 42 of file itkMeshFromTensorImageFilter.h.
template<class TInputImage , class TOutputMesh = vtkPolyData> typedef InputImageType::ConstPointer itk::MeshFromTensorImageFilter< TInputImage, TOutputMesh >::InputImageConstPointer
Definition at line 53 of file itkMeshFromTensorImageFilter.h.
template<class TInputImage , class TOutputMesh = vtkPolyData> typedef InputImageType::IndexType itk::MeshFromTensorImageFilter< TInputImage, TOutputMesh >::InputImageIndexType
Definition at line 54 of file itkMeshFromTensorImageFilter.h.
template<class TInputImage , class TOutputMesh = vtkPolyData> typedef InputImageType::PixelType itk::MeshFromTensorImageFilter< TInputImage, TOutputMesh >::InputImagePixelType
Definition at line 58 of file itkMeshFromTensorImageFilter.h.
template<class TInputImage , class TOutputMesh = vtkPolyData> typedef InputImageType::Pointer itk::MeshFromTensorImageFilter< TInputImage, TOutputMesh >::InputImagePointer
Definition at line 52 of file itkMeshFromTensorImageFilter.h.
template<class TInputImage , class TOutputMesh = vtkPolyData> typedef InputImageType::PointType itk::MeshFromTensorImageFilter< TInputImage, TOutputMesh >::InputImagePointType
Definition at line 60 of file itkMeshFromTensorImageFilter.h.
template<class TInputImage , class TOutputMesh = vtkPolyData> typedef InputImageType::RegionType itk::MeshFromTensorImageFilter< TInputImage, TOutputMesh >::InputImageRegionType
Definition at line 59 of file itkMeshFromTensorImageFilter.h.
template<class TInputImage , class TOutputMesh = vtkPolyData> typedef InputImageType::SizeType itk::MeshFromTensorImageFilter< TInputImage, TOutputMesh >::InputImageSizeType
Definition at line 55 of file itkMeshFromTensorImageFilter.h.
template<class TInputImage , class TOutputMesh = vtkPolyData> typedef InputImageType::SizeValueType itk::MeshFromTensorImageFilter< TInputImage, TOutputMesh >::InputImageSizeValueType
Definition at line 56 of file itkMeshFromTensorImageFilter.h.
template<class TInputImage , class TOutputMesh = vtkPolyData> typedef InputImageType::SpacingType itk::MeshFromTensorImageFilter< TInputImage, TOutputMesh >::InputImageSpacingType
Definition at line 57 of file itkMeshFromTensorImageFilter.h.
template<class TInputImage , class TOutputMesh = vtkPolyData> typedef TInputImage itk::MeshFromTensorImageFilter< TInputImage, TOutputMesh >::InputImageType
Definition at line 48 of file itkMeshFromTensorImageFilter.h.
template<class TInputImage , class TOutputMesh = vtkPolyData> typedef Superclass::MatrixPointer itk::MeshFromTensorImageFilter< TInputImage, TOutputMesh >::MatrixPointer
Definition at line 73 of file itkMeshFromTensorImageFilter.h.
template<class TInputImage , class TOutputMesh = vtkPolyData> typedef Superclass::MatrixType itk::MeshFromTensorImageFilter< TInputImage, TOutputMesh >::MatrixType
Orientation Matrices
Definition at line 72 of file itkMeshFromTensorImageFilter.h.
template<class TInputImage , class TOutputMesh = vtkPolyData> typedef Superclass::OutputMeshCellArrayType itk::MeshFromTensorImageFilter< TInputImage, TOutputMesh >::OutputMeshCellArrayType
Definition at line 65 of file itkMeshFromTensorImageFilter.h.
template<class TInputImage , class TOutputMesh = vtkPolyData> typedef Superclass::OutputMeshPointsType itk::MeshFromTensorImageFilter< TInputImage, TOutputMesh >::OutputMeshPointsType
Definition at line 64 of file itkMeshFromTensorImageFilter.h.
template<class TInputImage , class TOutputMesh = vtkPolyData> typedef Superclass::OutputMeshPolyDataPointer itk::MeshFromTensorImageFilter< TInputImage, TOutputMesh >::OutputMeshPolyDataPointer
Definition at line 66 of file itkMeshFromTensorImageFilter.h.
template<class TInputImage , class TOutputMesh = vtkPolyData> typedef TOutputMesh itk::MeshFromTensorImageFilter< TInputImage, TOutputMesh >::OutputMeshPolyDataType
Definition at line 62 of file itkMeshFromTensorImageFilter.h.
template<class TInputImage , class TOutputMesh = vtkPolyData> typedef Superclass::OutputMeshRGBType itk::MeshFromTensorImageFilter< TInputImage, TOutputMesh >::OutputMeshRGBType
Definition at line 68 of file itkMeshFromTensorImageFilter.h.
template<class TInputImage , class TOutputMesh = vtkPolyData> typedef Superclass::OutputMeshScalarType itk::MeshFromTensorImageFilter< TInputImage, TOutputMesh >::OutputMeshScalarType
Definition at line 67 of file itkMeshFromTensorImageFilter.h.
template<class TInputImage , class TOutputMesh = vtkPolyData> typedef SmartPointer<Self> itk::MeshFromTensorImageFilter< TInputImage, TOutputMesh >::Pointer
Definition at line 41 of file itkMeshFromTensorImageFilter.h.
template<class TInputImage , class TOutputMesh = vtkPolyData> typedef ScalarImageType::Pointer itk::MeshFromTensorImageFilter< TInputImage, TOutputMesh >::ScalarImagePointer
Definition at line 80 of file itkMeshFromTensorImageFilter.h.
template<class TInputImage , class TOutputMesh = vtkPolyData> typedef Image<double,3> itk::MeshFromTensorImageFilter< TInputImage, TOutputMesh >::ScalarImageType
Definition at line 79 of file itkMeshFromTensorImageFilter.h.
template<class TInputImage , class TOutputMesh = vtkPolyData> typedef MeshFromTensorImageFilter itk::MeshFromTensorImageFilter< TInputImage, TOutputMesh >::Self
Standard class typedefs.
Definition at line 39 of file itkMeshFromTensorImageFilter.h.
template<class TInputImage , class TOutputMesh = vtkPolyData> typedef Superclass::STDVectorPointer itk::MeshFromTensorImageFilter< TInputImage, TOutputMesh >::STDVectorPointer
Definition at line 77 of file itkMeshFromTensorImageFilter.h.
template<class TInputImage , class TOutputMesh = vtkPolyData> typedef Superclass::STDVectorType itk::MeshFromTensorImageFilter< TInputImage, TOutputMesh >::STDVectorType
Definition at line 76 of file itkMeshFromTensorImageFilter.h.
template<class TInputImage , class TOutputMesh = vtkPolyData> typedef MeshFromImageImageFilter<TInputImage, TOutputMesh> itk::MeshFromTensorImageFilter< TInputImage, TOutputMesh >::Superclass
Definition at line 40 of file itkMeshFromTensorImageFilter.h.
template<class TInputImage , class TOutputMesh = vtkPolyData> typedef vtkTensorGlyph itk::MeshFromTensorImageFilter< TInputImage, TOutputMesh >::TensorGlyphType
Definition at line 82 of file itkMeshFromTensorImageFilter.h.
template<class TInputImage , class TOutputMesh = vtkPolyData> typedef Superclass::VectorPointer itk::MeshFromTensorImageFilter< TInputImage, TOutputMesh >::VectorPointer
Definition at line 75 of file itkMeshFromTensorImageFilter.h.
template<class TInputImage , class TOutputMesh = vtkPolyData> typedef Superclass::VectorType itk::MeshFromTensorImageFilter< TInputImage, TOutputMesh >::VectorType
Definition at line 74 of file itkMeshFromTensorImageFilter.h.
Member Enumeration Documentation
template<class TInputImage , class TOutputMesh = vtkPolyData> enum itk::MeshFromTensorImageFilter::GlyphShapeType
enum of the possible shapes for the glyphs
Enumerator
GLYPH_LINE
GLYPH_ARROW
GLYPH_DISK
GLYPH_CYLINDER
GLYPH_CUBE
GLYPH_SPHERE
ellipsoild
GLYPH_SUPERQUADRIC
superquadric
Definition at line 85 of file itkMeshFromTensorImageFilter.h.
template<class TInputImage , class TOutputMesh = vtkPolyData> enum itk::MeshFromTensorImageFilter::TensorColorSchemeType
Enumerator
COLOR_NONE
default color
COLOR_BY_DIRECTION
by principal direction
COLOR_BY_FA
by fa
COLOR_BY_MD
by md
COLOR_BY_IMAGE
by input scalar image
Definition at line 99 of file itkMeshFromTensorImageFilter.h.
Constructor & Destructor Documentation
template<class TInputImage , class TOutputMesh > itk::MeshFromTensorImageFilter< TInputImage, TOutputMesh >::MeshFromTensorImageFilter () protected
Definition at line 41 of file itkMeshFromTensorImageFilter.hxx.
References itk::MeshFromTensorImageFilter< TInputImage, TOutputMesh >::SetGlyphShape().
template<class TInputImage , class TOutputMesh = vtkPolyData> itk::MeshFromTensorImageFilter< TInputImage, TOutputMesh >::~MeshFromTensorImageFilter () inline protected
Definition at line 154 of file itkMeshFromTensorImageFilter.h.
References ITK_OVERRIDE.
template<class TInputImage , class TOutputMesh = vtkPolyData> itk::MeshFromTensorImageFilter< TInputImage, TOutputMesh >::MeshFromTensorImageFilter (const Self &) private
Member Function Documentation
template<class TInputImage , class TOutputMesh = vtkPolyData> virtual::itk::LightObject::Pointer itk::MeshFromTensorImageFilter< TInputImage, TOutputMesh >::CreateAnother (void) const
template<class TInputImage , class TOutputMesh > void itk::MeshFromTensorImageFilter< TInputImage, TOutputMesh >::GenerateData (void) protected virtual
Definition at line 360 of file itkMeshFromTensorImageFilter.hxx.
References utl::ConvertTensor6DTo9D(), itk::DiffusionTensor< TPrecision >::Flip(), itk::GetVectorImage3DVolumeSize(), itk::IsImageEmpty(), itk::PrintVariableLengthVector(), TENSOR_UPPER_TRIANGULAR, utlPrintVar, and utlShowPosition.
Referenced by itk::MeshFromTensorImageFilter< TInputImage, TOutputMesh >::GetScalarCodeFromTensor().
template<class TInputImage , class TOutputMesh = vtkPolyData> virtual int itk::MeshFromTensorImageFilter< TInputImage, TOutputMesh >::GetGlyphResolution () virtual
template<class TInputImage , class TOutputMesh = vtkPolyData> virtual const char* itk::MeshFromTensorImageFilter< TInputImage, TOutputMesh >::GetNameOfClass () const virtual
Run-time type information (and related methods)
Reimplemented from itk::MeshFromImageImageFilter< TInputImage, TOutputMesh >.
template<class TInputImage , class TOutputMesh > double itk::MeshFromTensorImageFilter< TInputImage, TOutputMesh >::GetScalarCodeFromTensor (const DiffusionTensor< double > & tensor, TensorColorSchemeType colorScheme) static
Definition at line 257 of file itkMeshFromTensorImageFilter.hxx.
References itk::MeshFromTensorImageFilter< TInputImage, TOutputMesh >::GenerateData(), itk::DiffusionTensor< TPrecision >::GetEigenValuesVectorsAnalytic(), itk::DiffusionTensor< TPrecision >::GetFA(), itk::DiffusionTensor< TPrecision >::GetMD(), utl::RGBToIndex(), and utlGlobalException.
Referenced by itk::MeshFromTensorImageFilter< TInputImage, TOutputMesh >::SetGlyphResolution().
template<class TInputImage , class TOutputMesh = vtkPolyData> LightObject::Pointer itk::MeshFromTensorImageFilter< TInputImage, TOutputMesh >::InternalClone () const inline protected
Definition at line 163 of file itkMeshFromTensorImageFilter.h.
template<class TInputImage , class TOutputMesh = vtkPolyData> itk::MeshFromTensorImageFilter< TInputImage, TOutputMesh >::itkSetGetMacro (ScalarImage , ScalarImagePointer)
template<class TInputImage , class TOutputMesh = vtkPolyData> itk::MeshFromTensorImageFilter< TInputImage, TOutputMesh >::itkSetGetMacro (TensorColorScheme , TensorColorSchemeType)
template<class TInputImage , class TOutputMesh = vtkPolyData> itk::MeshFromTensorImageFilter< TInputImage, TOutputMesh >::itkSetGetMacro (ShapeMode , GlyphShapeType)
template<class TInputImage , class TOutputMesh = vtkPolyData> static Pointer itk::MeshFromTensorImageFilter< TInputImage, TOutputMesh >::New () static
Method for creation through the object factory.
template<class TInputImage , class TOutputMesh = vtkPolyData> void itk::MeshFromTensorImageFilter< TInputImage, TOutputMesh >::operator= (const Self &) private
template<class TInputImage , class TOutputMesh = vtkPolyData> void itk::MeshFromTensorImageFilter< TInputImage, TOutputMesh >::PrintSelf (std::ostream & os, Indent indent) const inline protected virtual
Reimplemented from itk::MeshFromImageImageFilter< TInputImage, TOutputMesh >.
Definition at line 159 of file itkMeshFromTensorImageFilter.h.
template<class TInputImage , class TOutputMesh > void itk::MeshFromTensorImageFilter< TInputImage, TOutputMesh >::SetGlyphResolution (int res)
Definition at line 189 of file itkMeshFromTensorImageFilter.hxx.
References itk::MeshFromTensorImageFilter< TInputImage, TOutputMesh >::GetScalarCodeFromTensor().
Referenced by itk::MeshFromTensorImageFilter< TInputImage, TOutputMesh >::SetGlyphShapeToSuperquadric().
template<class TInputImage , class TOutputMesh > void itk::MeshFromTensorImageFilter< TInputImage, TOutputMesh >::SetGlyphShape (GlyphShapeType i)
Definition at line 59 of file itkMeshFromTensorImageFilter.hxx.
References itk::MeshFromTensorImageFilter< TInputImage, TOutputMesh >::SetGlyphShapeToLine(), and utlGlobalException.
Referenced by itk::MeshFromTensorImageFilter< TInputImage, TOutputMesh >::MeshFromTensorImageFilter().
template<class TInputImage , class TOutputMesh > void itk::MeshFromTensorImageFilter< TInputImage, TOutputMesh >::SetGlyphShapeToArrow ()
Set a specific glyph shape
Definition at line 127 of file itkMeshFromTensorImageFilter.hxx.
References itk::MeshFromTensorImageFilter< TInputImage, TOutputMesh >::SetGlyphShapeToCube().
Referenced by itk::MeshFromTensorImageFilter< TInputImage, TOutputMesh >::SetGlyphShapeToDisk().
template<class TInputImage , class TOutputMesh > void itk::MeshFromTensorImageFilter< TInputImage, TOutputMesh >::SetGlyphShapeToCube ()
Set a specific glyph shape
Definition at line 143 of file itkMeshFromTensorImageFilter.hxx.
References itk::MeshFromTensorImageFilter< TInputImage, TOutputMesh >::SetGlyphShapeToCylinder().
Referenced by itk::MeshFromTensorImageFilter< TInputImage, TOutputMesh >::SetGlyphShapeToArrow().
template<class TInputImage , class TOutputMesh > void itk::MeshFromTensorImageFilter< TInputImage, TOutputMesh >::SetGlyphShapeToCylinder ()
Set a specific glyph shape
Definition at line 154 of file itkMeshFromTensorImageFilter.hxx.
References itk::MeshFromTensorImageFilter< TInputImage, TOutputMesh >::SetGlyphShapeToSphere().
Referenced by itk::MeshFromTensorImageFilter< TInputImage, TOutputMesh >::SetGlyphShapeToCube().
template<class TInputImage , class TOutputMesh > void itk::MeshFromTensorImageFilter< TInputImage, TOutputMesh >::SetGlyphShapeToDisk ()
Set a specific glyph shape
Definition at line 114 of file itkMeshFromTensorImageFilter.hxx.
References itk::MeshFromTensorImageFilter< TInputImage, TOutputMesh >::SetGlyphShapeToArrow().
Referenced by itk::MeshFromTensorImageFilter< TInputImage, TOutputMesh >::SetGlyphShapeToLine().
template<class TInputImage , class TOutputMesh > void itk::MeshFromTensorImageFilter< TInputImage, TOutputMesh >::SetGlyphShapeToLine ()
Set a specific glyph shape
Definition at line 103 of file itkMeshFromTensorImageFilter.hxx.
References itk::MeshFromTensorImageFilter< TInputImage, TOutputMesh >::SetGlyphShapeToDisk().
Referenced by itk::MeshFromTensorImageFilter< TInputImage, TOutputMesh >::SetGlyphShape().
template<class TInputImage , class TOutputMesh > void itk::MeshFromTensorImageFilter< TInputImage, TOutputMesh >::SetGlyphShapeToSphere ()
Set a specific glyph shape
Definition at line 165 of file itkMeshFromTensorImageFilter.hxx.
References itk::MeshFromTensorImageFilter< TInputImage, TOutputMesh >::SetGlyphShapeToSuperquadric().
Referenced by itk::MeshFromTensorImageFilter< TInputImage, TOutputMesh >::SetGlyphShapeToCylinder().
template<class TInputImage , class TOutputMesh > void itk::MeshFromTensorImageFilter< TInputImage, TOutputMesh >::SetGlyphShapeToSuperquadric ()
Set a specific glyph shape
Definition at line 176 of file itkMeshFromTensorImageFilter.hxx.
References itk::MeshFromTensorImageFilter< TInputImage, TOutputMesh >::SetGlyphResolution().
Referenced by itk::MeshFromTensorImageFilter< TInputImage, TOutputMesh >::SetGlyphShapeToSphere().
template<class TInputImage , class TOutputMesh = vtkPolyData> void itk::MeshFromTensorImageFilter< TInputImage, TOutputMesh >::VerifyInputParameters () const inline protected virtual
Reimplemented from itk::MeshFromImageImageFilter< TInputImage, TOutputMesh >.
Definition at line 178 of file itkMeshFromTensorImageFilter.h.
References itk::IsImageEmpty(), utlSAGlobalException, and itk::VerifyImageSize().
Member Data Documentation
template<class TInputImage , class TOutputMesh = vtkPolyData> vtkSmartPointer<TensorGlyphType> itk::MeshFromTensorImageFilter< TInputImage, TOutputMesh >::m_Glyph = TensorGlyphType::New() protected
Definition at line 197 of file itkMeshFromTensorImageFilter.h.
template<class TInputImage , class TOutputMesh = vtkPolyData> int itk::MeshFromTensorImageFilter< TInputImage, TOutputMesh >::m_GlyphResolution =10 protected
resolution for glyphs
Definition at line 202 of file itkMeshFromTensorImageFilter.h.
template<class TInputImage , class TOutputMesh = vtkPolyData> ScalarImagePointer itk::MeshFromTensorImageFilter< TInputImage, TOutputMesh >::m_ScalarImage = ScalarImageType::New() protected
Definition at line 204 of file itkMeshFromTensorImageFilter.h.
template<class TInputImage , class TOutputMesh = vtkPolyData> vtkSmartPointer<vtkPolyDataAlgorithm> itk::MeshFromTensorImageFilter< TInputImage, TOutputMesh >::m_Shape = vtkPolyDataAlgorithm::New() protected
Definition at line 195 of file itkMeshFromTensorImageFilter.h.
template<class TInputImage , class TOutputMesh = vtkPolyData> GlyphShapeType itk::MeshFromTensorImageFilter< TInputImage, TOutputMesh >::m_ShapeMode = GLYPH_SPHERE protected
Definition at line 193 of file itkMeshFromTensorImageFilter.h.
template<class TInputImage , class TOutputMesh = vtkPolyData> TensorColorSchemeType itk::MeshFromTensorImageFilter< TInputImage, TOutputMesh >::m_TensorColorScheme =COLOR_BY_DIRECTION protected
Definition at line 191 of file itkMeshFromTensorImageFilter.h.
The documentation for this class was generated from the following files:
Modules/Visualization/include/itkMeshFromTensorImageFilter.h
Modules/Visualization/include/itkMeshFromTensorImageFilter.hxx