DMRITool: smart_assert::assert_context Class Reference
smart_assert::assert_context Class Reference
#include <utlSmartAssert.h>
Detailed Description
Definition at line 98 of file utlSmartAssert.h.
Public Types
typedef std::pair< string, string > val_and_str
typedef std::vector< val_and_str > vals_array
Public Member Functions
void add_val (const string &val, const string &str)
assert_context ()
int get_condition () const
const string & get_context_file () const
const string & get_context_func () const
int get_context_line () const
const string & get_expr () const
int get_level () const
const string & get_level_msg () const
const vals_array & get_vals_array () const
void set_condition (int cond)
void set_expr (const string &str)
void set_file_line (const char *file, int line)
void set_file_line_func_cond (const char *file, int line, const char *func, int cond)
void set_level (int nLevel)
void set_level_msg (const char *strMsg)
Private Types
typedef std::string string
Private Attributes
int condition_
string expr_
string file_
string func_
int level_
int line_
string msg_
vals_array vals_
Member Typedef Documentation
typedef std::string smart_assert::assert_context::string private
Definition at line 99 of file utlSmartAssert.h.
typedef std::pair< string, string> smart_assert::assert_context::val_and_str
Definition at line 123 of file utlSmartAssert.h.
typedef std::vector< val_and_str> smart_assert::assert_context::vals_array
Definition at line 124 of file utlSmartAssert.h.
Constructor & Destructor Documentation
smart_assert::assert_context::assert_context () inline
Definition at line 101 of file utlSmartAssert.h.
Member Function Documentation
void smart_assert::assert_context::add_val (const string & val, const string & str) inline
Definition at line 129 of file utlSmartAssert.h.
References vals_.
int smart_assert::assert_context::get_condition () const inline
Definition at line 138 of file utlSmartAssert.h.
References condition_.
Referenced by smart_assert::dump_context_detail(), smart_assert::dump_context_log_detail(), and smart_assert::dump_context_summary().
const string& smart_assert::assert_context::get_context_file () const inline
Definition at line 115 of file utlSmartAssert.h.
References file_.
Referenced by smart_assert::default_debug_handler(), smart_assert::dump_context_detail(), smart_assert::dump_context_log_detail(), and smart_assert::dump_context_summary().
const string& smart_assert::assert_context::get_context_func () const inline
Definition at line 116 of file utlSmartAssert.h.
References func_.
Referenced by smart_assert::dump_context_detail(), smart_assert::dump_context_log_detail(), and smart_assert::dump_context_summary().
int smart_assert::assert_context::get_context_line () const inline
Definition at line 117 of file utlSmartAssert.h.
References line_.
Referenced by smart_assert::default_debug_handler(), smart_assert::dump_context_detail(), smart_assert::dump_context_log_detail(), and smart_assert::dump_context_summary().
const string& smart_assert::assert_context::get_expr () const inline
Definition at line 121 of file utlSmartAssert.h.
References expr_.
Referenced by smart_assert::dump_context_detail(), smart_assert::dump_context_log_detail(), and smart_assert::dump_context_summary().
int smart_assert::assert_context::get_level () const inline
Definition at line 135 of file utlSmartAssert.h.
References level_.
Referenced by smart_assert::dump_context_detail(), smart_assert::dump_context_log_detail(), and smart_assert::dump_context_summary().
const string& smart_assert::assert_context::get_level_msg () const inline
Definition at line 147 of file utlSmartAssert.h.
References msg_.
Referenced by smart_assert::dump_context_detail(), smart_assert::dump_context_log_detail(), and smart_assert::dump_context_summary().
const vals_array& smart_assert::assert_context::get_vals_array () const inline
Definition at line 127 of file utlSmartAssert.h.
References vals_.
Referenced by smart_assert::dump_context_detail(), and smart_assert::dump_context_log_detail().
void smart_assert::assert_context::set_condition (int cond) inline
Definition at line 137 of file utlSmartAssert.h.
References condition_.
void smart_assert::assert_context::set_expr (const string & str) inline
Definition at line 120 of file utlSmartAssert.h.
References expr_.
void smart_assert::assert_context::set_file_line (const char * file, int line) inline
Definition at line 105 of file utlSmartAssert.h.
References file_, and line_.
void smart_assert::assert_context::set_file_line_func_cond (const char * file, int line, const char * func, int cond) inline
Definition at line 109 of file utlSmartAssert.h.
References condition_, file_, func_, and line_.
void smart_assert::assert_context::set_level (int nLevel) inline
Definition at line 134 of file utlSmartAssert.h.
References level_.
void smart_assert::assert_context::set_level_msg (const char * strMsg) inline
Definition at line 141 of file utlSmartAssert.h.
References msg_.
Member Data Documentation
int smart_assert::assert_context::condition_ private
Definition at line 161 of file utlSmartAssert.h.
Referenced by get_condition(), set_condition(), and set_file_line_func_cond().
string smart_assert::assert_context::expr_ private
Definition at line 156 of file utlSmartAssert.h.
Referenced by get_expr(), and set_expr().
string smart_assert::assert_context::file_ private
Definition at line 151 of file utlSmartAssert.h.
Referenced by get_context_file(), set_file_line(), and set_file_line_func_cond().
string smart_assert::assert_context::func_ private
Definition at line 152 of file utlSmartAssert.h.
Referenced by get_context_func(), and set_file_line_func_cond().
int smart_assert::assert_context::level_ private
Definition at line 160 of file utlSmartAssert.h.
Referenced by get_level(), and set_level().
int smart_assert::assert_context::line_ private
Definition at line 153 of file utlSmartAssert.h.
Referenced by get_context_line(), set_file_line(), and set_file_line_func_cond().
string smart_assert::assert_context::msg_ private
Definition at line 162 of file utlSmartAssert.h.
Referenced by get_level_msg(), and set_level_msg().
vals_array smart_assert::assert_context::vals_ private
Definition at line 157 of file utlSmartAssert.h.
Referenced by add_val(), and get_vals_array().
The documentation for this class was generated from the following file:
Modules/HelperFunctions/include/utlSmartAssert.h