DMRITool: spams::FISTA::Rank< T > Class Template Reference
spams::FISTA::Rank< T > Class Template Reference
#include <fista.h>
Detailed Description
template<typename T>
class spams::FISTA::Rank< T >
Definition at line 1987 of file fista.h.
Public Member Functions
T eval (const Matrix< T > &x) const
void fenchel (const Matrix< T > &input, T &val, T &scal) const
virtual bool is_fenchel () const
void prox (const Matrix< T > &x, Matrix< T > &y, const T lambda)
Rank (const ParamReg< T > &param)
virtual ~Rank ()
Public Member Functions inherited from spams::FISTA::Regularizer< T, Matrix< T > >
virtual T eval_dual_norm (const Matrix< T > &x) const
virtual T eval_dual_norm_paths (const Matrix< T > &x, SpMatrix< T > &path) const
virtual T eval_paths (const Matrix< T > &x, SpMatrix< T > &paths_mat) const
virtual bool is_intercept () const
virtual bool is_subgrad () const
Regularizer ()
Regularizer (const ParamReg< T > &param)
virtual void reset ()
virtual void sub_grad (const Matrix< T > &input, Matrix< T > &output) const
virtual ~Regularizer ()
Additional Inherited Members
Protected Attributes inherited from spams::FISTA::Regularizer< T, Matrix< T > >
bool _intercept
bool _pos
Constructor & Destructor Documentation
template<typename T > spams::FISTA::Rank< T >::Rank (const ParamReg< T > & param) inline
Definition at line 1989 of file fista.h.
References spams::FISTA::ParamReg< T >::intercept, and spams::FISTA::ParamReg< T >::pos.
template<typename T > virtual spams::FISTA::Rank< T >::~Rank () inline virtual
Definition at line 1998 of file fista.h.
Member Function Documentation
template<typename T > T spams::FISTA::Rank< T >::eval (const Matrix< T > & x) const inline virtual
Implements spams::FISTA::Regularizer< T, Matrix< T > >.
Definition at line 2016 of file fista.h.
References spams::Matrix< T >::eigLargestMagnSym(), spams::Matrix< T >::m(), spams::Matrix< T >::n(), spams::Matrix< T >::rank1Update(), spams::Vector< T >::setAleat(), spams::Matrix< T >::XtX(), and spams::Matrix< T >::XXt().
template<typename T > void spams::FISTA::Rank< T >::fenchel (const Matrix< T > & input, T & val, T & scal) const inline virtual
returns phi^star(input) and ouput=input if the fenchel is unconstrained returns 0 and scale input such that phi^star(output)=0 otherwise
Implements spams::FISTA::Regularizer< T, Matrix< T > >.
Definition at line 2035 of file fista.h.
template<typename T > virtual bool spams::FISTA::Rank< T >::is_fenchel () const inline virtual
Reimplemented from spams::FISTA::Regularizer< T, Matrix< T > >.
Definition at line 2034 of file fista.h.
template<typename T > void spams::FISTA::Rank< T >::prox (const Matrix< T > & x, Matrix< T > & y, const T lambda) inline virtual
Implements spams::FISTA::Regularizer< T, Matrix< T > >.
Definition at line 2000 of file fista.h.
References spams::Matrix< T >::copy(), spams::Matrix< T >::m(), MIN, spams::Matrix< T >::n(), spams::Vector< T >::nrm2(), spams::Matrix< T >::rank1Update(), spams::Matrix< T >::resize(), spams::Matrix< T >::setZeros(), spams::Vector< T >::setZeros(), and spams::Matrix< T >::svdRankOne().
The documentation for this class was generated from the following file:
ThirdParty/Spams/include/fista.h