DMRITool: itk::SPFScaleFromMeanDiffusivityImageFilter< TInputImage, TOutputImage > Class Template Reference
itk::SPFScaleFromMeanDiffusivityImageFilter< TInputImage, TOutputImage > Class Template Reference
DiffusionModels
#include <itkSPFScaleFromMeanDiffusivityImageFilter.h>
Detailed Description
template<class TInputImage, class TOutputImage>
class itk::SPFScaleFromMeanDiffusivityImageFilter< TInputImage, TOutputImage >
Compute SPF scale from mean diffusivity.
This filter is templated over the input image type and the output image type.
Author
Jian Cheng, jian..nosp@m.chen.nosp@m.g.198.nosp@m.3@gm.nosp@m.ail.c.nosp@m.om
See also
UnaryFunctorImageFilter
Definition at line 86 of file itkSPFScaleFromMeanDiffusivityImageFilter.h.
Public Types
typedef SmartPointer< const Self > ConstPointer
typedef SmartPointer< Self > Pointer
typedef SPFScaleFromMeanDiffusivityImageFilter Self
typedef UnaryFunctorImageFilter< TInputImage, TOutputImage, Functor::SPFScaleFromMeanDiffusivity< typename TInputImage::PixelType, typename TOutputImage::PixelType > > Superclass
Public Member Functions
virtual ::itk::LightObject::Pointer CreateAnother (void) const
const bool & GetIsOriginalBasis () const
const double & GetMD0 () const
virtual const char * GetNameOfClass () const
const double & GetTau () const
void SetIsOriginalBasis (const bool isSPF)
void SetMD0 (const double md0)
void SetTau (const double tau)
Static Public Member Functions
static Pointer New ()
Protected Member Functions
void PrintSelf (std::ostream &os, Indent indent) const ITK_OVERRIDE
SPFScaleFromMeanDiffusivityImageFilter ()
virtual ~SPFScaleFromMeanDiffusivityImageFilter ()
Private Member Functions
void operator= (const Self &)
SPFScaleFromMeanDiffusivityImageFilter (const Self &)
Member Typedef Documentation
template<class TInputImage , class TOutputImage > typedef SmartPointer<const Self> itk::SPFScaleFromMeanDiffusivityImageFilter< TInputImage, TOutputImage >::ConstPointer
Definition at line 103 of file itkSPFScaleFromMeanDiffusivityImageFilter.h.
template<class TInputImage , class TOutputImage > typedef SmartPointer<Self> itk::SPFScaleFromMeanDiffusivityImageFilter< TInputImage, TOutputImage >::Pointer
Definition at line 102 of file itkSPFScaleFromMeanDiffusivityImageFilter.h.
template<class TInputImage , class TOutputImage > typedef SPFScaleFromMeanDiffusivityImageFilter itk::SPFScaleFromMeanDiffusivityImageFilter< TInputImage, TOutputImage >::Self
Standard class typedefs.
Definition at line 95 of file itkSPFScaleFromMeanDiffusivityImageFilter.h.
template<class TInputImage , class TOutputImage > typedef UnaryFunctorImageFilter< TInputImage,TOutputImage, Functor::SPFScaleFromMeanDiffusivity< typename TInputImage::PixelType, typename TOutputImage::PixelType> > itk::SPFScaleFromMeanDiffusivityImageFilter< TInputImage, TOutputImage >::Superclass
Definition at line 100 of file itkSPFScaleFromMeanDiffusivityImageFilter.h.
Constructor & Destructor Documentation
template<class TInputImage , class TOutputImage > itk::SPFScaleFromMeanDiffusivityImageFilter< TInputImage, TOutputImage >::SPFScaleFromMeanDiffusivityImageFilter () inline protected
Definition at line 151 of file itkSPFScaleFromMeanDiffusivityImageFilter.h.
template<class TInputImage , class TOutputImage > virtual itk::SPFScaleFromMeanDiffusivityImageFilter< TInputImage, TOutputImage >::~SPFScaleFromMeanDiffusivityImageFilter () inline protected virtual
Definition at line 152 of file itkSPFScaleFromMeanDiffusivityImageFilter.h.
template<class TInputImage , class TOutputImage > itk::SPFScaleFromMeanDiffusivityImageFilter< TInputImage, TOutputImage >::SPFScaleFromMeanDiffusivityImageFilter (const Self &) private
Member Function Documentation
template<class TInputImage , class TOutputImage > virtual::itk::LightObject::Pointer itk::SPFScaleFromMeanDiffusivityImageFilter< TInputImage, TOutputImage >::CreateAnother (void) const
template<class TInputImage , class TOutputImage > const bool& itk::SPFScaleFromMeanDiffusivityImageFilter< TInputImage, TOutputImage >::GetIsOriginalBasis () const inline
Definition at line 145 of file itkSPFScaleFromMeanDiffusivityImageFilter.h.
template<class TInputImage , class TOutputImage > const double& itk::SPFScaleFromMeanDiffusivityImageFilter< TInputImage, TOutputImage >::GetMD0 () const inline
Definition at line 119 of file itkSPFScaleFromMeanDiffusivityImageFilter.h.
template<class TInputImage , class TOutputImage > virtual const char* itk::SPFScaleFromMeanDiffusivityImageFilter< TInputImage, TOutputImage >::GetNameOfClass () const virtual
Run-time type information (and related methods).
template<class TInputImage , class TOutputImage > const double& itk::SPFScaleFromMeanDiffusivityImageFilter< TInputImage, TOutputImage >::GetTau () const inline
Definition at line 132 of file itkSPFScaleFromMeanDiffusivityImageFilter.h.
template<class TInputImage , class TOutputImage > static Pointer itk::SPFScaleFromMeanDiffusivityImageFilter< TInputImage, TOutputImage >::New () static
Method for creation through the object factory.
template<class TInputImage , class TOutputImage > void itk::SPFScaleFromMeanDiffusivityImageFilter< TInputImage, TOutputImage >::operator= (const Self &) private
template<class TInputImage , class TOutputImage > void itk::SPFScaleFromMeanDiffusivityImageFilter< TInputImage, TOutputImage >::PrintSelf (std::ostream & os, Indent indent) const inline protected
Definition at line 154 of file itkSPFScaleFromMeanDiffusivityImageFilter.h.
References itk::Functor::SPFScaleFromMeanDiffusivity< TInput, TOutput >::GetMD0(), and itk::Functor::SPFScaleFromMeanDiffusivity< TInput, TOutput >::GetTau().
template<class TInputImage , class TOutputImage > void itk::SPFScaleFromMeanDiffusivityImageFilter< TInputImage, TOutputImage >::SetIsOriginalBasis (const bool isSPF) inline
Definition at line 137 of file itkSPFScaleFromMeanDiffusivityImageFilter.h.
References itk::Functor::SPFScaleFromMeanDiffusivity< TInput, TOutput >::GetIsOriginalBasis().
template<class TInputImage , class TOutputImage > void itk::SPFScaleFromMeanDiffusivityImageFilter< TInputImage, TOutputImage >::SetMD0 (const double md0) inline
Definition at line 111 of file itkSPFScaleFromMeanDiffusivityImageFilter.h.
References itk::Functor::SPFScaleFromMeanDiffusivity< TInput, TOutput >::GetMD0().
template<class TInputImage , class TOutputImage > void itk::SPFScaleFromMeanDiffusivityImageFilter< TInputImage, TOutputImage >::SetTau (const double tau) inline
Definition at line 124 of file itkSPFScaleFromMeanDiffusivityImageFilter.h.
References itk::Functor::SPFScaleFromMeanDiffusivity< TInput, TOutput >::GetTau().
The documentation for this class was generated from the following file:
Modules/DiffusionModels/include/itkSPFScaleFromMeanDiffusivityImageFilter.h