DMRITool: spams::FISTA::normLINF< T > Class Template Reference
spams::FISTA::normLINF< T > Class Template Reference
#include <fista.h>
Detailed Description
template<typename T>
class spams::FISTA::normLINF< T >
Definition at line 1263 of file fista.h.
Public Member Functions
T eval (const Vector< T > &x) const
void fenchel (const Vector< T > &input, T &val, T &scal) const
normLINF (const ParamReg< T > &param)
void prox (const Vector< T > &x, Vector< T > &y, const T lambda)
virtual ~normLINF ()
Public Member Functions inherited from spams::FISTA::Regularizer< T >
virtual T eval_dual_norm (const Vector< T > &x) const
virtual T eval_dual_norm_paths (const Vector< T > &x, SpMatrix< T > &path) const
virtual T eval_paths (const Vector< T > &x, SpMatrix< T > &paths_mat) const
virtual bool is_fenchel () const
virtual bool is_intercept () const
virtual bool is_subgrad () const
Regularizer ()
Regularizer (const ParamReg< T > &param)
virtual void reset ()
virtual void sub_grad (const Vector< T > &input, Vector< T > &output) const
virtual ~Regularizer ()
Additional Inherited Members
Protected Attributes inherited from spams::FISTA::Regularizer< T >
bool _intercept
bool _pos
Constructor & Destructor Documentation
template<typename T > spams::FISTA::normLINF< T >::normLINF (const ParamReg< T > & param) inline
Definition at line 1265 of file fista.h.
template<typename T > virtual spams::FISTA::normLINF< T >::~normLINF () inline virtual
Definition at line 1266 of file fista.h.
Member Function Documentation
template<typename T > T spams::FISTA::normLINF< T >::eval (const Vector< T > & x) const inline virtual
Implements spams::FISTA::Regularizer< T >.
Definition at line 1278 of file fista.h.
References spams::Vector< T >::fmaxval(), spams::Vector< T >::n(), and spams::Vector< T >::rawX().
template<typename T > void spams::FISTA::normLINF< T >::fenchel (const Vector< T > & input, T & val, T & scal) const inline virtual
TODO add subgradient.
Implements spams::FISTA::Regularizer< T >.
Definition at line 1283 of file fista.h.
References spams::Vector< T >::asum(), spams::Vector< T >::copy(), EPSILON, INFINITY, spams::Vector< T >::n(), and spams::Vector< T >::thrsPos().
template<typename T > void spams::FISTA::normLINF< T >::prox (const Vector< T > & x, Vector< T > & y, const T lambda) inline virtual
Implements spams::FISTA::Regularizer< T >.
Definition at line 1268 of file fista.h.
References spams::Vector< T >::copy(), spams::Vector< T >::l1project(), spams::Vector< T >::n(), spams::Vector< T >::rawX(), and spams::Vector< T >::thrsPos().
The documentation for this class was generated from the following file:
ThirdParty/Spams/include/fista.h