DMRITool: spams::FISTA::TraceNorm< T > Class Template Reference
spams::FISTA::TraceNorm< T > Class Template Reference
#include <fista.h>
Detailed Description
template<typename T>
class spams::FISTA::TraceNorm< T >
Definition at line 1915 of file fista.h.
Public Member Functions
T eval (const Matrix< T > &x) const
void fenchel (const Matrix< T > &input, T &val, T &scal) const
void prox (const Matrix< T > &x, Matrix< T > &y, const T lambda)
TraceNorm (const ParamReg< T > &param)
virtual ~TraceNorm ()
Public Member Functions inherited from spams::FISTA::Regularizer< T, Matrix< T > >
virtual T eval_dual_norm (const Matrix< T > &x) const
virtual T eval_dual_norm_paths (const Matrix< T > &x, SpMatrix< T > &path) const
virtual T eval_paths (const Matrix< T > &x, SpMatrix< T > &paths_mat) const
virtual bool is_fenchel () const
virtual bool is_intercept () const
virtual bool is_subgrad () const
Regularizer ()
Regularizer (const ParamReg< T > &param)
virtual void reset ()
virtual void sub_grad (const Matrix< T > &input, Matrix< T > &output) const
virtual ~Regularizer ()
Additional Inherited Members
Protected Attributes inherited from spams::FISTA::Regularizer< T, Matrix< T > >
bool _intercept
bool _pos
Constructor & Destructor Documentation
template<typename T > spams::FISTA::TraceNorm< T >::TraceNorm (const ParamReg< T > & param) inline
Definition at line 1917 of file fista.h.
References spams::FISTA::ParamReg< T >::intercept, and spams::FISTA::ParamReg< T >::pos.
template<typename T > virtual spams::FISTA::TraceNorm< T >::~TraceNorm () inline virtual
Definition at line 1926 of file fista.h.
Member Function Documentation
template<typename T > T spams::FISTA::TraceNorm< T >::eval (const Matrix< T > & x) const inline virtual
Implements spams::FISTA::Regularizer< T, Matrix< T > >.
Definition at line 1949 of file fista.h.
References spams::Matrix< T >::singularValues(), and spams::Vector< T >::sum().
template<typename T > void spams::FISTA::TraceNorm< T >::fenchel (const Matrix< T > & input, T & val, T & scal) const inline virtual
returns phi^star(input) and ouput=input if the fenchel is unconstrained returns 0 and scale input such that phi^star(output)=0 otherwise
Implements spams::FISTA::Regularizer< T, Matrix< T > >.
Definition at line 1971 of file fista.h.
References spams::Vector< T >::fmaxval(), and spams::Matrix< T >::singularValues().
template<typename T > void spams::FISTA::TraceNorm< T >::prox (const Matrix< T > & x, Matrix< T > & y, const T lambda) inline virtual
Implements spams::FISTA::Regularizer< T, Matrix< T > >.
Definition at line 1928 of file fista.h.
References spams::Matrix< T >::mult(), spams::Matrix< T >::multDiagRight(), spams::Vector< T >::softThrshold(), and spams::Matrix< T >::svd().
The documentation for this class was generated from the following file:
ThirdParty/Spams/include/fista.h