DMRITool: itk::FeaturesFromSPFImageFilter< TInputImage, TOutputImage > Class Template Reference
itk::FeaturesFromSPFImageFilter< TInputImage, TOutputImage > Class Template Reference
DiffusionModels
#include <itkFeaturesFromSPFImageFilter.h>
Detailed Description
template<class TInputImage, class TOutputImage>
class itk::FeaturesFromSPFImageFilter< TInputImage, TOutputImage >
Compute some features (DWI/EAP profile, ODFs, scalar indices) from SPF coefficients.
This filter is templated over the input image type and the output image type.
Author
Jian Cheng (JC), jian..nosp@m.chen.nosp@m.g.198.nosp@m.3@gm.nosp@m.ail.c.nosp@m.om
Definition at line 40 of file itkFeaturesFromSPFImageFilter.h.
Public Types
enum BasisType {
SPF =0,
DSPF
}
typedef SmartPointer< const Self > ConstPointer
typedef utl_shared_ptr< MatrixType > MatrixPointer
typedef utl::NDArray< double, 2 > MatrixType
typedef SmartPointer< Self > Pointer
typedef FeaturesFromSPFImageFilter Self
typedef SphericalPolarFourierEstimationImageFilter< TInputImage, TOutputImage > SPFIFilterBaseType
typedef utl_shared_ptr< STDVectorType > STDVectorPointer
typedef std::vector< double > STDVectorType
typedef MaskedImageToImageFilter< TInputImage, TOutputImage > Superclass
typedef utl_shared_ptr< VectorType > VectorPointer
typedef utl::NDArray< double, 1 > VectorType
Public Types inherited from itk::MaskedImageToImageFilter< TInputImage, TOutputImage >
typedef SmartPointer< const Self > ConstPointer
typedef InputImageType::ConstPointer InputImageConstPointer
typedef InputImageType::IndexType InputImageIndexType
typedef InputImageType::PixelType InputImagePixelType
typedef InputImageType::Pointer InputImagePointer
typedef InputImageType::RegionType InputImageRegionType
typedef InputImageType::SizeType InputImageSizeType
typedef InputImageType::SpacingType InputImageSpacingType
typedef TInputImage InputImageType
typedef LoggerType::Pointer LoggerPointer
typedef ThreadLogger LoggerType
typedef utl_shared_ptr< LoggerVectorType > LoggerVectorPointer
typedef std::vector< LoggerPointer > LoggerVectorType
typedef MaskImageType::Pointer MaskImagePointer
typedef Image< double, 3 > MaskImageType
typedef OutputImageType::IndexType OutputImageIndexType
typedef OutputImageType::PixelType OutputImagePixelType
typedef OutputImageType::Pointer OutputImagePointer
typedef OutputImageType::RegionType OutputImageRegionType
typedef OutputImageType::SizeType OutputImageSizeType
typedef OutputImageType::SpacingType OutputImageSpacingType
typedef TOutputImage OutputImageType
typedef SmartPointer< Self > Pointer
typedef MaskedImageToImageFilter Self
typedef ImageToImageFilter< TInputImage, TOutputImage > Superclass
Public Member Functions
double ComputeScale (const bool setScale=true)
virtual void ComputeSPFToFeatureTransform ()
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual double GetBasisScale ()
virtual BasisType GetBasisType ()
virtual bool GetIsFourier ()
virtual bool GetIsInQSpace ()
virtual double GetMD0 ()
virtual const char * GetNameOfClass () const
virtual MatrixPointer GetOrientations ()
virtual int GetRadialRank ()
virtual const ScalarImageType * GetScaleImage () const
virtual int GetSHRank ()
virtual MatrixPointer GetSPFToFeatureTransform ()
virtual double GetTau ()
virtual void IsFourierOff ()
virtual void IsFourierOn ()
virtual void IsInQSpaceOff ()
virtual void IsInQSpaceOn ()
itkGetObjectMacro (ScaleImage, ScalarImageType)
itkTypedefMaskedImageToImageMacro (Superclass)
virtual void SetBasisScale (const double scale)
virtual void SetBasisType (BasisType _arg)
virtual void SetIsFourier (bool _arg)
virtual void SetIsInQSpace (bool _arg)
virtual void SetMD0 (double _arg)
virtual void SetOrientations (MatrixPointer _arg)
virtual void SetRadialRank (int _arg)
void SetScaleImage (const ScalarImagePointer &scaleImage)
virtual void SetSHRank (int _arg)
virtual void SetTau (double _arg)
Public Member Functions inherited from itk::MaskedImageToImageFilter< TInputImage, TOutputImage >
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual const LoggerType * GetLogger () const
virtual const MaskImageType * GetMaskImage () const
bool IsMaskUsed ()
itkGetObjectMacro (MaskImage, MaskImageType)
itkGetObjectMacro (Logger, LoggerType)
itkSetGetMacro (LogLevel, int)
virtual void SetLogger (LoggerType *_arg)
virtual void SetMaskImage (MaskImageType *_arg)
void SetMaskImage (const std::string &file)
Static Public Member Functions
static Pointer New ()
Static Public Member Functions inherited from itk::MaskedImageToImageFilter< TInputImage, TOutputImage >
static Pointer New ()
Protected Member Functions
void BeforeThreadedGenerateData () ITK_OVERRIDE
FeaturesFromSPFImageFilter ()
LightObject::Pointer InternalClone () const ITK_OVERRIDE
void PrintSelf (std::ostream &os, Indent indent) const ITK_OVERRIDE
void SetSPFIEstimator ()
virtual void VerifyInputParameters () const ITK_OVERRIDE
virtual ~FeaturesFromSPFImageFilter ()
Protected Member Functions inherited from itk::MaskedImageToImageFilter< TInputImage, TOutputImage >
void CreateLoggerVector ()
virtual void InitializeThreadedLibraries ()
LightObject::Pointer InternalClone () const ITK_OVERRIDE
MaskedImageToImageFilter ()
std::string ThreadIDToString () const
virtual void VerifyMaskInformation () const
void WriteLogger (const std::string &str, const LoggerBase::PriorityLevelType level=LoggerBase::DEBUG) const
virtual ~MaskedImageToImageFilter ()
Protected Attributes
double m_BasisScale
BasisType m_BasisType
bool m_IsFourier
bool m_IsInQSpace
double m_MD0
MatrixPointer m_Orientations
int m_RadialRank
ScalarImageType::Pointer m_ScaleImage
int m_SHRank
SPFIFilterBaseType::Pointer m_SPFIEstimator
MatrixPointer m_SPFToFeatureTransform
double m_Tau
Protected Attributes inherited from itk::MaskedImageToImageFilter< TInputImage, TOutputImage >
LoggerPointer m_Logger
LoggerVectorPointer m_LoggerVector
int m_LogLevel
MaskImagePointer m_MaskImage
int m_ThreadID
Private Member Functions
FeaturesFromSPFImageFilter (const Self &)
void operator= (const Self &)
Additional Inherited Members
Static Public Attributes inherited from itk::MaskedImageToImageFilter< TInputImage, TOutputImage >
static const unsigned int InputImageDimension
static const unsigned int OutputImageDimension
Member Typedef Documentation
template<class TInputImage , class TOutputImage > typedef SmartPointer<const Self> itk::FeaturesFromSPFImageFilter< TInputImage, TOutputImage >::ConstPointer
Definition at line 48 of file itkFeaturesFromSPFImageFilter.h.
template<class TInputImage , class TOutputImage > typedef utl_shared_ptr<MatrixType> itk::FeaturesFromSPFImageFilter< TInputImage, TOutputImage >::MatrixPointer
Definition at line 59 of file itkFeaturesFromSPFImageFilter.h.
template<class TInputImage , class TOutputImage > typedef utl::NDArray<double,2> itk::FeaturesFromSPFImageFilter< TInputImage, TOutputImage >::MatrixType
Definition at line 58 of file itkFeaturesFromSPFImageFilter.h.
template<class TInputImage , class TOutputImage > typedef SmartPointer<Self> itk::FeaturesFromSPFImageFilter< TInputImage, TOutputImage >::Pointer
Definition at line 47 of file itkFeaturesFromSPFImageFilter.h.
template<class TInputImage , class TOutputImage > typedef FeaturesFromSPFImageFilter itk::FeaturesFromSPFImageFilter< TInputImage, TOutputImage >::Self
Standard class typedefs.
Definition at line 45 of file itkFeaturesFromSPFImageFilter.h.
template<class TInputImage , class TOutputImage > typedef SphericalPolarFourierEstimationImageFilter<TInputImage, TOutputImage> itk::FeaturesFromSPFImageFilter< TInputImage, TOutputImage >::SPFIFilterBaseType
Definition at line 65 of file itkFeaturesFromSPFImageFilter.h.
template<class TInputImage , class TOutputImage > typedef utl_shared_ptr<STDVectorType > itk::FeaturesFromSPFImageFilter< TInputImage, TOutputImage >::STDVectorPointer
Definition at line 63 of file itkFeaturesFromSPFImageFilter.h.
template<class TInputImage , class TOutputImage > typedef std::vector<double> itk::FeaturesFromSPFImageFilter< TInputImage, TOutputImage >::STDVectorType
Definition at line 62 of file itkFeaturesFromSPFImageFilter.h.
template<class TInputImage , class TOutputImage > typedef MaskedImageToImageFilter<TInputImage,TOutputImage> itk::FeaturesFromSPFImageFilter< TInputImage, TOutputImage >::Superclass
Definition at line 46 of file itkFeaturesFromSPFImageFilter.h.
template<class TInputImage , class TOutputImage > typedef utl_shared_ptr<VectorType> itk::FeaturesFromSPFImageFilter< TInputImage, TOutputImage >::VectorPointer
Definition at line 61 of file itkFeaturesFromSPFImageFilter.h.
template<class TInputImage , class TOutputImage > typedef utl::NDArray<double,1> itk::FeaturesFromSPFImageFilter< TInputImage, TOutputImage >::VectorType
Definition at line 60 of file itkFeaturesFromSPFImageFilter.h.
Member Enumeration Documentation
template<class TInputImage , class TOutputImage > enum itk::FeaturesFromSPFImageFilter::BasisType
Enumerator
SPF
DSPF
Definition at line 67 of file itkFeaturesFromSPFImageFilter.h.
Constructor & Destructor Documentation
template<class TInputImage , class TOutputImage > itk::FeaturesFromSPFImageFilter< TInputImage, TOutputImage >::FeaturesFromSPFImageFilter () protected
Definition at line 30 of file itkFeaturesFromSPFImageFilter.hxx.
References itk::FeaturesFromSPFImageFilter< TInputImage, TOutputImage >::ComputeScale(), and ONE_OVER_4_PI_2.
template<class TInputImage , class TOutputImage > virtual itk::FeaturesFromSPFImageFilter< TInputImage, TOutputImage >::~FeaturesFromSPFImageFilter () inline protected virtual
Definition at line 117 of file itkFeaturesFromSPFImageFilter.h.
References ITK_OVERRIDE.
template<class TInputImage , class TOutputImage > itk::FeaturesFromSPFImageFilter< TInputImage, TOutputImage >::FeaturesFromSPFImageFilter (const Self &) private
Member Function Documentation
template<class TInputImage , class TOutputImage > void itk::FeaturesFromSPFImageFilter< TInputImage, TOutputImage >::BeforeThreadedGenerateData () protected
Definition at line 145 of file itkFeaturesFromSPFImageFilter.hxx.
References itk::FeaturesFromSPFImageFilter< TInputImage, TOutputImage >::SetSPFIEstimator().
Referenced by itk::FeaturesFromSPFImageFilter< TInputImage, TOutputImage >::InternalClone().
template<class TInputImage , class TOutputImage > double itk::FeaturesFromSPFImageFilter< TInputImage, TOutputImage >::ComputeScale (const bool setScale = true)
Definition at line 52 of file itkFeaturesFromSPFImageFilter.hxx.
References M_PI, and itk::FeaturesFromSPFImageFilter< TInputImage, TOutputImage >::SetBasisScale().
Referenced by itk::FeaturesFromSPFImageFilter< TInputImage, TOutputImage >::FeaturesFromSPFImageFilter().
template<class TInputImage , class TOutputImage > virtual void itk::FeaturesFromSPFImageFilter< TInputImage, TOutputImage >::ComputeSPFToFeatureTransform () inline virtual
Reimplemented in itk::ProfileFromSPFImageFilter< TInputImage, TOutputImage >, and itk::ODFFromSPFImageFilter< TInputImage, TOutputImage >.
Definition at line 112 of file itkFeaturesFromSPFImageFilter.h.
template<class TInputImage , class TOutputImage > virtual::itk::LightObject::Pointer itk::FeaturesFromSPFImageFilter< TInputImage, TOutputImage >::CreateAnother (void) const
template<class TInputImage , class TOutputImage > virtual double itk::FeaturesFromSPFImageFilter< TInputImage, TOutputImage >::GetBasisScale () virtual
template<class TInputImage , class TOutputImage > virtual BasisType itk::FeaturesFromSPFImageFilter< TInputImage, TOutputImage >::GetBasisType () virtual
template<class TInputImage , class TOutputImage > virtual bool itk::FeaturesFromSPFImageFilter< TInputImage, TOutputImage >::GetIsFourier () virtual
template<class TInputImage , class TOutputImage > virtual bool itk::FeaturesFromSPFImageFilter< TInputImage, TOutputImage >::GetIsInQSpace () virtual
template<class TInputImage , class TOutputImage > virtual double itk::FeaturesFromSPFImageFilter< TInputImage, TOutputImage >::GetMD0 () virtual
template<class TInputImage , class TOutputImage > virtual const char* itk::FeaturesFromSPFImageFilter< TInputImage, TOutputImage >::GetNameOfClass () const virtual
Run-time type information (and related methods)
Reimplemented from itk::MaskedImageToImageFilter< TInputImage, TOutputImage >.
Reimplemented in itk::ProfileFromSPFImageFilter< TInputImage, TOutputImage >, itk::ODFFromSPFImageFilter< TInputImage, TOutputImage >, and itk::ScalarMapFromSPFImageFilter< TInputImage, TOutputImage >.
template<class TInputImage , class TOutputImage > virtual MatrixPointer itk::FeaturesFromSPFImageFilter< TInputImage, TOutputImage >::GetOrientations () virtual
template<class TInputImage , class TOutputImage > virtual int itk::FeaturesFromSPFImageFilter< TInputImage, TOutputImage >::GetRadialRank () virtual
template<class TInputImage , class TOutputImage > virtual const ScalarImageType* itk::FeaturesFromSPFImageFilter< TInputImage, TOutputImage >::GetScaleImage () const virtual
template<class TInputImage , class TOutputImage > virtual int itk::FeaturesFromSPFImageFilter< TInputImage, TOutputImage >::GetSHRank () virtual
template<class TInputImage , class TOutputImage > virtual MatrixPointer itk::FeaturesFromSPFImageFilter< TInputImage, TOutputImage >::GetSPFToFeatureTransform () virtual
template<class TInputImage , class TOutputImage > virtual double itk::FeaturesFromSPFImageFilter< TInputImage, TOutputImage >::GetTau () virtual
template<class TInputImage , class TOutputImage > LightObject::Pointer itk::FeaturesFromSPFImageFilter< TInputImage, TOutputImage >::InternalClone () const protected
Definition at line 112 of file itkFeaturesFromSPFImageFilter.hxx.
References itk::FeaturesFromSPFImageFilter< TInputImage, TOutputImage >::BeforeThreadedGenerateData().
Referenced by itk::FeaturesFromSPFImageFilter< TInputImage, TOutputImage >::VerifyInputParameters().
template<class TInputImage , class TOutputImage > virtual void itk::FeaturesFromSPFImageFilter< TInputImage, TOutputImage >::IsFourierOff () virtual
template<class TInputImage , class TOutputImage > virtual void itk::FeaturesFromSPFImageFilter< TInputImage, TOutputImage >::IsFourierOn () virtual
template<class TInputImage , class TOutputImage > virtual void itk::FeaturesFromSPFImageFilter< TInputImage, TOutputImage >::IsInQSpaceOff () virtual
template<class TInputImage , class TOutputImage > virtual void itk::FeaturesFromSPFImageFilter< TInputImage, TOutputImage >::IsInQSpaceOn () virtual
template<class TInputImage , class TOutputImage > itk::FeaturesFromSPFImageFilter< TInputImage, TOutputImage >::itkGetObjectMacro (ScaleImage , ScalarImageType)
template<class TInputImage , class TOutputImage > itk::FeaturesFromSPFImageFilter< TInputImage, TOutputImage >::itkTypedefMaskedImageToImageMacro (Superclass)
template<class TInputImage , class TOutputImage > static Pointer itk::FeaturesFromSPFImageFilter< TInputImage, TOutputImage >::New () static
Method for creation through the object factory.
template<class TInputImage , class TOutputImage > void itk::FeaturesFromSPFImageFilter< TInputImage, TOutputImage >::operator= (const Self &) private
template<class TInputImage , class TOutputImage > void itk::FeaturesFromSPFImageFilter< TInputImage, TOutputImage >::PrintSelf (std::ostream & os, Indent indent) const protected virtual
Reimplemented from itk::MaskedImageToImageFilter< TInputImage, TOutputImage >.
Reimplemented in itk::ODFFromSPFImageFilter< TInputImage, TOutputImage >, itk::ProfileFromSPFImageFilter< TInputImage, TOutputImage >, and itk::ScalarMapFromSPFImageFilter< TInputImage, TOutputImage >.
Definition at line 171 of file itkFeaturesFromSPFImageFilter.hxx.
References itk::IsImageEmpty(), and utl::PrintUtlMatrix().
Referenced by itk::FeaturesFromSPFImageFilter< TInputImage, TOutputImage >::SetSPFIEstimator().
template<class TInputImage , class TOutputImage > void itk::FeaturesFromSPFImageFilter< TInputImage, TOutputImage >::SetBasisScale (const double scale) virtual
Definition at line 67 of file itkFeaturesFromSPFImageFilter.hxx.
References itk::FeaturesFromSPFImageFilter< TInputImage, TOutputImage >::SetScaleImage().
Referenced by itk::FeaturesFromSPFImageFilter< TInputImage, TOutputImage >::ComputeScale().
template<class TInputImage , class TOutputImage > virtual void itk::FeaturesFromSPFImageFilter< TInputImage, TOutputImage >::SetBasisType (BasisType _arg) virtual
template<class TInputImage , class TOutputImage > virtual void itk::FeaturesFromSPFImageFilter< TInputImage, TOutputImage >::SetIsFourier (bool _arg) virtual
for dwi/eap profile
template<class TInputImage , class TOutputImage > virtual void itk::FeaturesFromSPFImageFilter< TInputImage, TOutputImage >::SetIsInQSpace (bool _arg) virtual
template<class TInputImage , class TOutputImage > virtual void itk::FeaturesFromSPFImageFilter< TInputImage, TOutputImage >::SetMD0 (double _arg) virtual
template<class TInputImage , class TOutputImage > virtual void itk::FeaturesFromSPFImageFilter< TInputImage, TOutputImage >::SetOrientations (MatrixPointer _arg) virtual
template<class TInputImage , class TOutputImage > virtual void itk::FeaturesFromSPFImageFilter< TInputImage, TOutputImage >::SetRadialRank (int _arg) virtual
template<class TInputImage , class TOutputImage > void itk::FeaturesFromSPFImageFilter< TInputImage, TOutputImage >::SetScaleImage (const ScalarImagePointer & scaleImage)
Set/Get the scale image, which is normally determined by MDImage.
Definition at line 87 of file itkFeaturesFromSPFImageFilter.hxx.
References itk::FeaturesFromSPFImageFilter< TInputImage, TOutputImage >::VerifyInputParameters().
Referenced by itk::FeaturesFromSPFImageFilter< TInputImage, TOutputImage >::SetBasisScale().
template<class TInputImage , class TOutputImage > virtual void itk::FeaturesFromSPFImageFilter< TInputImage, TOutputImage >::SetSHRank (int _arg) virtual
template<class TInputImage , class TOutputImage > void itk::FeaturesFromSPFImageFilter< TInputImage, TOutputImage >::SetSPFIEstimator () protected
Definition at line 154 of file itkFeaturesFromSPFImageFilter.hxx.
References itk::FeaturesFromSPFImageFilter< TInputImage, TOutputImage >::PrintSelf().
Referenced by itk::FeaturesFromSPFImageFilter< TInputImage, TOutputImage >::BeforeThreadedGenerateData().
template<class TInputImage , class TOutputImage > virtual void itk::FeaturesFromSPFImageFilter< TInputImage, TOutputImage >::SetTau (double _arg) virtual
template<class TInputImage , class TOutputImage > void itk::FeaturesFromSPFImageFilter< TInputImage, TOutputImage >::VerifyInputParameters () const protected virtual
Reimplemented from itk::MaskedImageToImageFilter< TInputImage, TOutputImage >.
Reimplemented in itk::ProfileFromSPFImageFilter< TInputImage, TOutputImage >, itk::ODFFromSPFImageFilter< TInputImage, TOutputImage >, and itk::ScalarMapFromSPFImageFilter< TInputImage, TOutputImage >.
Definition at line 101 of file itkFeaturesFromSPFImageFilter.hxx.
References itk::FeaturesFromSPFImageFilter< TInputImage, TOutputImage >::InternalClone(), utlGlobalException, and utlSAGlobalException.
Referenced by itk::FeaturesFromSPFImageFilter< TInputImage, TOutputImage >::SetScaleImage().
Member Data Documentation
template<class TInputImage , class TOutputImage > double itk::FeaturesFromSPFImageFilter< TInputImage, TOutputImage >::m_BasisScale protected
Definition at line 130 of file itkFeaturesFromSPFImageFilter.h.
template<class TInputImage , class TOutputImage > BasisType itk::FeaturesFromSPFImageFilter< TInputImage, TOutputImage >::m_BasisType protected
Definition at line 144 of file itkFeaturesFromSPFImageFilter.h.
template<class TInputImage , class TOutputImage > bool itk::FeaturesFromSPFImageFilter< TInputImage, TOutputImage >::m_IsFourier protected
for profile
Definition at line 141 of file itkFeaturesFromSPFImageFilter.h.
template<class TInputImage , class TOutputImage > bool itk::FeaturesFromSPFImageFilter< TInputImage, TOutputImage >::m_IsInQSpace protected
the basis is in qspace or in the fourier space
Definition at line 138 of file itkFeaturesFromSPFImageFilter.h.
template<class TInputImage , class TOutputImage > double itk::FeaturesFromSPFImageFilter< TInputImage, TOutputImage >::m_MD0 protected
Definition at line 131 of file itkFeaturesFromSPFImageFilter.h.
template<class TInputImage , class TOutputImage > MatrixPointer itk::FeaturesFromSPFImageFilter< TInputImage, TOutputImage >::m_Orientations protected
Orientaitons in spherical format. If it is set, the output will be samples, not SH coefficients
Definition at line 147 of file itkFeaturesFromSPFImageFilter.h.
template<class TInputImage , class TOutputImage > int itk::FeaturesFromSPFImageFilter< TInputImage, TOutputImage >::m_RadialRank protected
Definition at line 134 of file itkFeaturesFromSPFImageFilter.h.
template<class TInputImage , class TOutputImage > ScalarImageType::Pointer itk::FeaturesFromSPFImageFilter< TInputImage, TOutputImage >::m_ScaleImage protected
Definition at line 135 of file itkFeaturesFromSPFImageFilter.h.
template<class TInputImage , class TOutputImage > int itk::FeaturesFromSPFImageFilter< TInputImage, TOutputImage >::m_SHRank protected
Definition at line 133 of file itkFeaturesFromSPFImageFilter.h.
template<class TInputImage , class TOutputImage > SPFIFilterBaseType::Pointer itk::FeaturesFromSPFImageFilter< TInputImage, TOutputImage >::m_SPFIEstimator protected
Definition at line 149 of file itkFeaturesFromSPFImageFilter.h.
template<class TInputImage , class TOutputImage > MatrixPointer itk::FeaturesFromSPFImageFilter< TInputImage, TOutputImage >::m_SPFToFeatureTransform protected
Definition at line 143 of file itkFeaturesFromSPFImageFilter.h.
template<class TInputImage , class TOutputImage > double itk::FeaturesFromSPFImageFilter< TInputImage, TOutputImage >::m_Tau protected
Definition at line 132 of file itkFeaturesFromSPFImageFilter.h.
The documentation for this class was generated from the following files:
Modules/DiffusionModels/include/itkFeaturesFromSPFImageFilter.h
Modules/DiffusionModels/include/itkFeaturesFromSPFImageFilter.hxx