DMRITool: itk::GeneralizedHighOrderTensorImageFilter< TInputImage, TOutputImage > Class Template Reference
itk::GeneralizedHighOrderTensorImageFilter< TInputImage, TOutputImage > Class Template Reference
DiffusionModels
#include <itkGeneralizedHighOrderTensorImageFilter.h>
Detailed Description
template<class TInputImage, class TOutputImage = TInputImage>
class itk::GeneralizedHighOrderTensorImageFilter< TInputImage, TOutputImage >
estimate the coefficients in GHOT model, which is used for md image estimation
Author
Jian Cheng (JC), jian..nosp@m.chen.nosp@m.g.198.nosp@m.3@gm.nosp@m.ail.c.nosp@m.om
Definition at line 35 of file itkGeneralizedHighOrderTensorImageFilter.h.
Public Types
typedef SmartPointer< const Self > ConstPointer
typedef Superclass::EstimationType EstimationType
typedef Superclass::L2SolverType L2SolverType
typedef Superclass::MatrixPointer MatrixPointer
typedef Superclass::MatrixType MatrixType
typedef SmartPointer< Self > Pointer
typedef GeneralizedHighOrderTensorImageFilter Self
typedef Superclass::STDVectorPointer STDVectorPointer
typedef Superclass::STDVectorType STDVectorType
typedef SphericalPolarFourierEstimationImageFilter< TInputImage, TOutputImage > Superclass
typedef Superclass::VectorPointer VectorPointer
typedef Superclass::VectorType VectorType
Public Types inherited from itk::SphericalPolarFourierEstimationImageFilter< TInputImage, TOutputImage >
typedef SmartPointer< const Self > ConstPointer
enum EstimationType {
LS =0,
L1_2,
L1_DL
}
typedef L1RegularizedLeastSquaresFISTASolver< double > L1FISTASolverType
enum L1SolverType {
FISTA_LS =0,
SPAMS
}
typedef SpamsWeightedLassoSolver< double > L1SpamsSolverType
typedef L2RegularizedLeastSquaresSolver< double > L2SolverType
typedef Superclass::MatrixPointer MatrixPointer
typedef Superclass::MatrixType MatrixType
typedef SmartPointer< Self > Pointer
typedef SphericalPolarFourierEstimationImageFilter Self
typedef Superclass::STDVectorPointer STDVectorPointer
typedef Superclass::STDVectorType STDVectorType
typedef DiffusionModelEstimationInSphericalCoordinateImageFilter< TInputImage, TOutputImage > Superclass
typedef Superclass::VectorPointer VectorPointer
typedef Superclass::VectorType VectorType
Public Types inherited from itk::DiffusionModelEstimationInSphericalCoordinateImageFilter< TInputImage, TOutputImage >
typedef SmartPointer< const Self > ConstPointer
typedef Superclass::InputImageConstPointer InputImageConstPointer
typedef Superclass::InputImageIndexType InputImageIndexType
typedef Superclass::InputImagePixelType InputImagePixelType
typedef Superclass::InputImagePointer InputImagePointer
typedef Superclass::InputImageRegionType InputImageRegionType
typedef Superclass::InputImageSizeType InputImageSizeType
typedef Superclass::InputImageSpacingType InputImageSpacingType
typedef Superclass::InputImageType InputImageType
typedef Superclass::MaskImageType MaskImageType
typedef Superclass::MatrixPointer MatrixPointer
typedef Superclass::MatrixType MatrixType
typedef Superclass::OutputImageIndexType OutputImageIndexType
typedef Superclass::OutputImagePixelType OutputImagePixelType
typedef Superclass::OutputImagePointer OutputImagePointer
typedef Superclass::OutputImageRegionType OutputImageRegionType
typedef Superclass::OutputImageSizeType OutputImageSizeType
typedef Superclass::OutputImageSpacingType OutputImageSpacingType
typedef Superclass::OutputImageType OutputImageType
typedef SmartPointer< Self > Pointer
typedef DiffusionModelEstimationInSphericalCoordinateImageFilter Self
typedef Superclass::STDVectorPointer STDVectorPointer
typedef Superclass::STDVectorType STDVectorType
typedef DiffusionModelEstimationImageFilter< TInputImage, TOutputImage > Superclass
typedef Superclass::VectorPointer VectorPointer
typedef Superclass::VectorType VectorType
Public Types inherited from itk::DiffusionModelEstimationImageFilter< TInputImage, TOutputImage >
typedef SmartPointer< const Self > ConstPointer
typedef utl_shared_ptr< MatrixType > MatrixPointer
typedef utl::NDArray< double, 2 > MatrixType
typedef SmartPointer< Self > Pointer
typedef SamplingSchemeQSpaceType::Pointer SamplingSchemeQSpacePointer
typedef SamplingSchemeQSpace< double > SamplingSchemeQSpaceType
typedef SamplingSchemeRSpaceType::Pointer SamplingSchemeRSpacePointer
typedef SamplingScheme3D< double > SamplingSchemeRSpaceType
typedef DiffusionModelEstimationImageFilter Self
typedef utl_shared_ptr< STDVectorType > STDVectorPointer
typedef std::vector< double > STDVectorType
typedef MaskedImageToImageFilter< TInputImage, TOutputImage > Superclass
typedef utl_shared_ptr< VectorType > VectorPointer
typedef utl::NDArray< double, 1 > VectorType
Public Types inherited from itk::MaskedImageToImageFilter< TInputImage, TOutputImage >
typedef SmartPointer< const Self > ConstPointer
typedef InputImageType::ConstPointer InputImageConstPointer
typedef InputImageType::IndexType InputImageIndexType
typedef InputImageType::PixelType InputImagePixelType
typedef InputImageType::Pointer InputImagePointer
typedef InputImageType::RegionType InputImageRegionType
typedef InputImageType::SizeType InputImageSizeType
typedef InputImageType::SpacingType InputImageSpacingType
typedef TInputImage InputImageType
typedef LoggerType::Pointer LoggerPointer
typedef ThreadLogger LoggerType
typedef utl_shared_ptr< LoggerVectorType > LoggerVectorPointer
typedef std::vector< LoggerPointer > LoggerVectorType
typedef MaskImageType::Pointer MaskImagePointer
typedef Image< double, 3 > MaskImageType
typedef OutputImageType::IndexType OutputImageIndexType
typedef OutputImageType::PixelType OutputImagePixelType
typedef OutputImageType::Pointer OutputImagePointer
typedef OutputImageType::RegionType OutputImageRegionType
typedef OutputImageType::SizeType OutputImageSizeType
typedef OutputImageType::SpacingType OutputImageSpacingType
typedef TOutputImage OutputImageType
typedef SmartPointer< Self > Pointer
typedef MaskedImageToImageFilter Self
typedef ImageToImageFilter< TInputImage, TOutputImage > Superclass
Public Member Functions
void ComputeBasisMatrix () ITK_OVERRIDE
void ComputeRadialMatrix () ITK_OVERRIDE
void ComputeRegularizationWeight () ITK_OVERRIDE
double ComputeScale (const bool setScale=true) ITK_OVERRIDE
virtual ::itk::LightObject::Pointer CreateAnother (void) const
std::vector< int > DimToRank (const int dimm) const ITK_OVERRIDE
virtual const char * GetNameOfClass () const
itkTypedefMaskedImageToImageMacro (Superclass)
int RankToDim (const bool is_radial=false, const int radialRank=-1, const int shRank=-1) const ITK_OVERRIDE
void VerifyInputParameters () const ITK_OVERRIDE
Public Member Functions inherited from itk::SphericalPolarFourierEstimationImageFilter< TInputImage, TOutputImage >
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual double GetB0Weight ()
virtual MatrixPointer GetBasisCombinationMatrix ()
virtual VectorPointer GetBasisEnergyDL ()
virtual double GetBasisEnergyPowerDL ()
virtual double GetBasisScale ()
virtual EstimationType GetEstimationType ()
virtual int GetIndexJ (const int n, const int l, const int m) const
virtual std::vector< int > GetIndexNLM (const int index) const
virtual bool GetIsOriginalBasis ()
virtual L1SolverType GetL1SolverType ()
virtual double GetLambdaL1 ()
virtual double GetLambdaRadial ()
virtual double GetLambdaSpherical ()
virtual const ScalarImageType * GetMDImage () const
virtual VectorPointer GetRegularizationWeight ()
virtual const ScalarImageType * GetScaleImage () const
bool IsAdaptiveScale () const
virtual void IsOriginalBasisOff ()
virtual void IsOriginalBasisOn ()
itkGetObjectMacro (MDImage, ScalarImageType)
itkGetObjectMacro (ScaleImage, ScalarImageType)
itkSetGetBooleanMacro (IsAnalyticalB0)
itkTypedefMaskedImageToImageMacro (Superclass)
virtual void SetB0Weight (double _arg)
virtual void SetBasisCombinationMatrix (MatrixPointer _arg)
virtual void SetBasisEnergyDL (VectorPointer _arg)
virtual void SetBasisEnergyPowerDL (double _arg)
virtual void SetBasisScale (const double scale)
virtual void SetEstimationType (EstimationType _arg)
virtual void SetIsOriginalBasis (bool _arg)
virtual void SetL1FISTASolver (typename L1FISTASolverType::Pointer _arg)
virtual void SetL1SolverType (L1SolverType _arg)
virtual void SetL1SpamsSolver (typename L1SpamsSolverType::Pointer _arg)
virtual void SetLambdaL1 (double _arg)
virtual void SetLambdaRadial (double _arg)
virtual void SetLambdaSpherical (double _arg)
virtual void SetMDImage (ScalarImageType *_arg)
virtual void SetScaleImage (ScalarImageType *_arg)
Public Member Functions inherited from itk::DiffusionModelEstimationInSphericalCoordinateImageFilter< TInputImage, TOutputImage >
virtual void ComputeSHMatrix ()
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual MatrixPointer GetBasisRadialMatrix ()
virtual MatrixPointer GetBasisSHMatrix ()
virtual int GetRadialRank ()
virtual int GetSHRank ()
virtual void SetRadialRank (int _arg)
virtual void SetSHRank (int _arg)
Public Member Functions inherited from itk::DiffusionModelEstimationImageFilter< TInputImage, TOutputImage >
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual MatrixPointer GetBasisMatrix ()
virtual double GetMD0 ()
itkGetObjectMacro (SamplingSchemeQSpace, SamplingSchemeQSpaceType)
itkTypedefMaskedImageToImageMacro (Superclass)
virtual void SetMD0 (double _arg)
virtual void SetSamplingSchemeQSpace (SamplingSchemeQSpaceType *_arg)
Public Member Functions inherited from itk::MaskedImageToImageFilter< TInputImage, TOutputImage >
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual const LoggerType * GetLogger () const
virtual const MaskImageType * GetMaskImage () const
bool IsMaskUsed ()
itkGetObjectMacro (MaskImage, MaskImageType)
itkGetObjectMacro (Logger, LoggerType)
itkSetGetMacro (LogLevel, int)
virtual void SetLogger (LoggerType *_arg)
virtual void SetMaskImage (MaskImageType *_arg)
void SetMaskImage (const std::string &file)
Static Public Member Functions
static Pointer New ()
Static Public Member Functions inherited from itk::SphericalPolarFourierEstimationImageFilter< TInputImage, TOutputImage >
static Pointer New ()
Static Public Member Functions inherited from itk::DiffusionModelEstimationInSphericalCoordinateImageFilter< TInputImage, TOutputImage >
static Pointer New ()
Static Public Member Functions inherited from itk::DiffusionModelEstimationImageFilter< TInputImage, TOutputImage >
static Pointer New ()
Static Public Member Functions inherited from itk::MaskedImageToImageFilter< TInputImage, TOutputImage >
static Pointer New ()
Protected Member Functions
void BeforeThreadedGenerateData () ITK_OVERRIDE
GeneralizedHighOrderTensorImageFilter ()
void PrintSelf (std::ostream &os, Indent indent) const ITK_OVERRIDE
void ThreadedGenerateData (const OutputImageRegionType &outputRegionForThread, ThreadIdType threadId) ITK_OVERRIDE
virtual ~GeneralizedHighOrderTensorImageFilter ()
Protected Member Functions inherited from itk::SphericalPolarFourierEstimationImageFilter< TInputImage, TOutputImage >
void BeforeThreadedGenerateData () ITK_OVERRIDE
void GenerateOutputInformation () ITK_OVERRIDE
void InitializeThreadedLibraries () ITK_OVERRIDE
LightObject::Pointer InternalClone () const ITK_OVERRIDE
void PrintSelf (std::ostream &os, Indent indent) const ITK_OVERRIDE
SphericalPolarFourierEstimationImageFilter ()
void VerifyInputParameters () const ITK_OVERRIDE
virtual ~SphericalPolarFourierEstimationImageFilter ()
Protected Member Functions inherited from itk::DiffusionModelEstimationInSphericalCoordinateImageFilter< TInputImage, TOutputImage >
DiffusionModelEstimationInSphericalCoordinateImageFilter ()
LightObject::Pointer InternalClone () const ITK_OVERRIDE
virtual ~DiffusionModelEstimationInSphericalCoordinateImageFilter ()
Protected Member Functions inherited from itk::DiffusionModelEstimationImageFilter< TInputImage, TOutputImage >
DiffusionModelEstimationImageFilter ()
LightObject::Pointer InternalClone () const ITK_OVERRIDE
virtual ~DiffusionModelEstimationImageFilter ()
Protected Member Functions inherited from itk::MaskedImageToImageFilter< TInputImage, TOutputImage >
void CreateLoggerVector ()
LightObject::Pointer InternalClone () const ITK_OVERRIDE
MaskedImageToImageFilter ()
std::string ThreadIDToString () const
virtual void VerifyMaskInformation () const
void WriteLogger (const std::string &str, const LoggerBase::PriorityLevelType level=LoggerBase::DEBUG) const
virtual ~MaskedImageToImageFilter ()
Private Member Functions
GeneralizedHighOrderTensorImageFilter (const Self &)
void operator= (const Self &)
Additional Inherited Members
Static Public Attributes inherited from itk::MaskedImageToImageFilter< TInputImage, TOutputImage >
static const unsigned int InputImageDimension
static const unsigned int OutputImageDimension
Protected Attributes inherited from itk::SphericalPolarFourierEstimationImageFilter< TInputImage, TOutputImage >
double m_B0Weight
MatrixPointer m_BasisCombinationMatrix
VectorPointer m_BasisEnergyDL
double m_BasisEnergyPowerDL
MatrixPointer m_BasisMatrixForB0
double m_BasisScale
EstimationType m_EstimationType
bool m_IsAnalyticalB0
bool m_IsOriginalBasis
L1FISTASolverType::Pointer m_L1FISTASolver
L1SolverType m_L1SolverType
L1SpamsSolverType::Pointer m_L1SpamsSolver
L2SolverType::Pointer m_L2Solver
double m_LambdaL1
double m_LambdaL2
double m_LambdaRadial
double m_LambdaSpherical
ScalarImageType::Pointer m_MDImage
ScalarImageType::Pointer m_ScaleImage
Protected Attributes inherited from itk::DiffusionModelEstimationInSphericalCoordinateImageFilter< TInputImage, TOutputImage >
MatrixPointer m_BasisRadialMatrix
MatrixPointer m_BasisSHMatrix
int m_RadialRank
int m_SHRank
Protected Attributes inherited from itk::DiffusionModelEstimationImageFilter< TInputImage, TOutputImage >
MatrixPointer m_BasisMatrix
double m_MD0
VectorPointer m_RegularizationWeight
SamplingSchemeQSpacePointer m_SamplingSchemeQSpace
Protected Attributes inherited from itk::MaskedImageToImageFilter< TInputImage, TOutputImage >
LoggerPointer m_Logger
LoggerVectorPointer m_LoggerVector
int m_LogLevel
MaskImagePointer m_MaskImage
int m_ThreadID
Member Typedef Documentation
template<class TInputImage , class TOutputImage = TInputImage> typedef SmartPointer<const Self> itk::GeneralizedHighOrderTensorImageFilter< TInputImage, TOutputImage >::ConstPointer
Definition at line 43 of file itkGeneralizedHighOrderTensorImageFilter.h.
template<class TInputImage , class TOutputImage = TInputImage> typedef Superclass::EstimationType itk::GeneralizedHighOrderTensorImageFilter< TInputImage, TOutputImage >::EstimationType
Definition at line 61 of file itkGeneralizedHighOrderTensorImageFilter.h.
template<class TInputImage , class TOutputImage = TInputImage> typedef Superclass::L2SolverType itk::GeneralizedHighOrderTensorImageFilter< TInputImage, TOutputImage >::L2SolverType
Definition at line 60 of file itkGeneralizedHighOrderTensorImageFilter.h.
template<class TInputImage , class TOutputImage = TInputImage> typedef Superclass::MatrixPointer itk::GeneralizedHighOrderTensorImageFilter< TInputImage, TOutputImage >::MatrixPointer
Definition at line 55 of file itkGeneralizedHighOrderTensorImageFilter.h.
template<class TInputImage , class TOutputImage = TInputImage> typedef Superclass::MatrixType itk::GeneralizedHighOrderTensorImageFilter< TInputImage, TOutputImage >::MatrixType
Definition at line 53 of file itkGeneralizedHighOrderTensorImageFilter.h.
template<class TInputImage , class TOutputImage = TInputImage> typedef SmartPointer<Self> itk::GeneralizedHighOrderTensorImageFilter< TInputImage, TOutputImage >::Pointer
Definition at line 42 of file itkGeneralizedHighOrderTensorImageFilter.h.
template<class TInputImage , class TOutputImage = TInputImage> typedef GeneralizedHighOrderTensorImageFilter itk::GeneralizedHighOrderTensorImageFilter< TInputImage, TOutputImage >::Self
Standard class typedefs.
Definition at line 40 of file itkGeneralizedHighOrderTensorImageFilter.h.
template<class TInputImage , class TOutputImage = TInputImage> typedef Superclass::STDVectorPointer itk::GeneralizedHighOrderTensorImageFilter< TInputImage, TOutputImage >::STDVectorPointer
Definition at line 58 of file itkGeneralizedHighOrderTensorImageFilter.h.
template<class TInputImage , class TOutputImage = TInputImage> typedef Superclass::STDVectorType itk::GeneralizedHighOrderTensorImageFilter< TInputImage, TOutputImage >::STDVectorType
Definition at line 57 of file itkGeneralizedHighOrderTensorImageFilter.h.
template<class TInputImage , class TOutputImage = TInputImage> typedef SphericalPolarFourierEstimationImageFilter<TInputImage,TOutputImage> itk::GeneralizedHighOrderTensorImageFilter< TInputImage, TOutputImage >::Superclass
Definition at line 41 of file itkGeneralizedHighOrderTensorImageFilter.h.
template<class TInputImage , class TOutputImage = TInputImage> typedef Superclass::VectorPointer itk::GeneralizedHighOrderTensorImageFilter< TInputImage, TOutputImage >::VectorPointer
Definition at line 56 of file itkGeneralizedHighOrderTensorImageFilter.h.
template<class TInputImage , class TOutputImage = TInputImage> typedef Superclass::VectorType itk::GeneralizedHighOrderTensorImageFilter< TInputImage, TOutputImage >::VectorType
Definition at line 54 of file itkGeneralizedHighOrderTensorImageFilter.h.
Constructor & Destructor Documentation
template<class TInputImage , class TOutputImage > itk::GeneralizedHighOrderTensorImageFilter< TInputImage, TOutputImage >::GeneralizedHighOrderTensorImageFilter () protected
Definition at line 28 of file itkGeneralizedHighOrderTensorImageFilter.hxx.
References itk::GeneralizedHighOrderTensorImageFilter< TInputImage, TOutputImage >::ComputeScale().
template<class TInputImage , class TOutputImage = TInputImage> virtual itk::GeneralizedHighOrderTensorImageFilter< TInputImage, TOutputImage >::~GeneralizedHighOrderTensorImageFilter () inline protected virtual
Definition at line 78 of file itkGeneralizedHighOrderTensorImageFilter.h.
References ITK_OVERRIDE.
template<class TInputImage , class TOutputImage = TInputImage> itk::GeneralizedHighOrderTensorImageFilter< TInputImage, TOutputImage >::GeneralizedHighOrderTensorImageFilter (const Self &) private
Member Function Documentation
template<class TInputImage , class TOutputImage > void itk::GeneralizedHighOrderTensorImageFilter< TInputImage, TOutputImage >::BeforeThreadedGenerateData () protected
Definition at line 251 of file itkGeneralizedHighOrderTensorImageFilter.hxx.
References itk::GeneralizedHighOrderTensorImageFilter< TInputImage, TOutputImage >::ThreadedGenerateData(), and utlShowPosition.
Referenced by itk::GeneralizedHighOrderTensorImageFilter< TInputImage, TOutputImage >::ComputeRegularizationWeight().
template<class TInputImage , class TOutputImage > void itk::GeneralizedHighOrderTensorImageFilter< TInputImage, TOutputImage >::ComputeBasisMatrix () virtual
compute basis matrix which incorporates radial matrix and spherical matrix
Reimplemented from itk::DiffusionModelEstimationImageFilter< TInputImage, TOutputImage >.
Definition at line 162 of file itkGeneralizedHighOrderTensorImageFilter.hxx.
References itk::GeneralizedHighOrderTensorImageFilter< TInputImage, TOutputImage >::ComputeRegularizationWeight(), utl::ComputeSHMatrix(), utl::PrintUtlMatrix(), utlException, and utlShowPosition.
Referenced by itk::GeneralizedHighOrderTensorImageFilter< TInputImage, TOutputImage >::ComputeRadialMatrix().
template<class TInputImage , class TOutputImage > void itk::GeneralizedHighOrderTensorImageFilter< TInputImage, TOutputImage >::ComputeRadialMatrix () virtual
compute radial matrix
Reimplemented from itk::DiffusionModelEstimationInSphericalCoordinateImageFilter< TInputImage, TOutputImage >.
Definition at line 109 of file itkGeneralizedHighOrderTensorImageFilter.hxx.
References itk::GeneralizedHighOrderTensorImageFilter< TInputImage, TOutputImage >::ComputeBasisMatrix(), M_PI, utl::PrintUtlMatrix(), utlGlobalException, and utlShowPosition.
Referenced by itk::GeneralizedHighOrderTensorImageFilter< TInputImage, TOutputImage >::VerifyInputParameters().
template<class TInputImage , class TOutputImage > void itk::GeneralizedHighOrderTensorImageFilter< TInputImage, TOutputImage >::ComputeRegularizationWeight () virtual
Reimplemented from itk::DiffusionModelEstimationImageFilter< TInputImage, TOutputImage >.
Definition at line 226 of file itkGeneralizedHighOrderTensorImageFilter.hxx.
References itk::GeneralizedHighOrderTensorImageFilter< TInputImage, TOutputImage >::BeforeThreadedGenerateData().
Referenced by itk::GeneralizedHighOrderTensorImageFilter< TInputImage, TOutputImage >::ComputeBasisMatrix().
template<class TInputImage , class TOutputImage > double itk::GeneralizedHighOrderTensorImageFilter< TInputImage, TOutputImage >::ComputeScale (const bool setScale = true) virtual
need to be overidden by subclasses
Reimplemented from itk::SphericalPolarFourierEstimationImageFilter< TInputImage, TOutputImage >.
Definition at line 35 of file itkGeneralizedHighOrderTensorImageFilter.hxx.
References itk::GeneralizedHighOrderTensorImageFilter< TInputImage, TOutputImage >::DimToRank(), M_PI, utl::max_element(), utlGlobalException, and utlShowPosition.
Referenced by itk::GeneralizedHighOrderTensorImageFilter< TInputImage, TOutputImage >::GeneralizedHighOrderTensorImageFilter().
template<class TInputImage , class TOutputImage = TInputImage> virtual::itk::LightObject::Pointer itk::GeneralizedHighOrderTensorImageFilter< TInputImage, TOutputImage >::CreateAnother (void) const
template<class TInputImage , class TOutputImage > std::vector< int > itk::GeneralizedHighOrderTensorImageFilter< TInputImage, TOutputImage >::DimToRank (const int dimm) const virtual
from dimension to rank
Reimplemented from itk::SphericalPolarFourierEstimationImageFilter< TInputImage, TOutputImage >.
Definition at line 60 of file itkGeneralizedHighOrderTensorImageFilter.hxx.
References itk::GeneralizedHighOrderTensorImageFilter< TInputImage, TOutputImage >::RankToDim(), and utlException.
Referenced by itk::GeneralizedHighOrderTensorImageFilter< TInputImage, TOutputImage >::ComputeScale().
template<class TInputImage , class TOutputImage = TInputImage> virtual const char* itk::GeneralizedHighOrderTensorImageFilter< TInputImage, TOutputImage >::GetNameOfClass () const virtual
Run-time type information (and related methods)
Reimplemented from itk::SphericalPolarFourierEstimationImageFilter< TInputImage, TOutputImage >.
template<class TInputImage , class TOutputImage = TInputImage> itk::GeneralizedHighOrderTensorImageFilter< TInputImage, TOutputImage >::itkTypedefMaskedImageToImageMacro (Superclass)
template<class TInputImage , class TOutputImage = TInputImage> static Pointer itk::GeneralizedHighOrderTensorImageFilter< TInputImage, TOutputImage >::New () static
Method for creation through the object factory.
template<class TInputImage , class TOutputImage = TInputImage> void itk::GeneralizedHighOrderTensorImageFilter< TInputImage, TOutputImage >::operator= (const Self &) private
template<class TInputImage , class TOutputImage > void itk::GeneralizedHighOrderTensorImageFilter< TInputImage, TOutputImage >::PrintSelf (std::ostream & os, Indent indent) const protected virtual
Reimplemented from itk::DiffusionModelEstimationInSphericalCoordinateImageFilter< TInputImage, TOutputImage >.
Definition at line 339 of file itkGeneralizedHighOrderTensorImageFilter.hxx.
Referenced by itk::GeneralizedHighOrderTensorImageFilter< TInputImage, TOutputImage >::ThreadedGenerateData().
template<class TInputImage , class TOutputImage > int itk::GeneralizedHighOrderTensorImageFilter< TInputImage, TOutputImage >::RankToDim (const bool is_radial = false, const int radialRank = -1, const int shRank = -1) const virtual
from rank to dimension
Reimplemented from itk::SphericalPolarFourierEstimationImageFilter< TInputImage, TOutputImage >.
Definition at line 84 of file itkGeneralizedHighOrderTensorImageFilter.hxx.
References itk::GeneralizedHighOrderTensorImageFilter< TInputImage, TOutputImage >::VerifyInputParameters().
Referenced by itk::GeneralizedHighOrderTensorImageFilter< TInputImage, TOutputImage >::DimToRank().
template<class TInputImage , class TOutputImage > void itk::GeneralizedHighOrderTensorImageFilter< TInputImage, TOutputImage >::ThreadedGenerateData (const OutputImageRegionType & outputRegionForThread, ThreadIdType threadId) protected
Definition at line 277 of file itkGeneralizedHighOrderTensorImageFilter.hxx.
References utl::NDArrayBase< T, Dim >::Fill(), itk::GeneralizedHighOrderTensorImageFilter< TInputImage, TOutputImage >::PrintSelf(), and utlShowPosition.
Referenced by itk::GeneralizedHighOrderTensorImageFilter< TInputImage, TOutputImage >::BeforeThreadedGenerateData().
template<class TInputImage , class TOutputImage > void itk::GeneralizedHighOrderTensorImageFilter< TInputImage, TOutputImage >::VerifyInputParameters () const virtual
Reimplemented from itk::DiffusionModelEstimationInSphericalCoordinateImageFilter< TInputImage, TOutputImage >.
Definition at line 97 of file itkGeneralizedHighOrderTensorImageFilter.hxx.
References itk::GeneralizedHighOrderTensorImageFilter< TInputImage, TOutputImage >::ComputeRadialMatrix(), utlGlobalException, and utlShowPosition.
Referenced by itk::GeneralizedHighOrderTensorImageFilter< TInputImage, TOutputImage >::RankToDim().
The documentation for this class was generated from the following files:
Modules/DiffusionModels/include/itkGeneralizedHighOrderTensorImageFilter.h
Modules/DiffusionModels/include/itkGeneralizedHighOrderTensorImageFilter.hxx