DMRITool: spams::FISTA::GraphPathConv< T > Class Template Reference
spams::FISTA::GraphPathConv< T > Class Template Reference
#include <fista.h>
Detailed Description
template<typename T>
class spams::FISTA::GraphPathConv< T >
Definition at line 2098 of file fista.h.
Public Member Functions
T eval (const Vector< T > &x) const
T eval_dual_norm (const Vector< T > &x) const
T eval_dual_norm_paths (const Vector< T > &x, SpMatrix< T > &paths_mat) const
T eval_paths (const Vector< T > &x, SpMatrix< T > &paths_mat) const
void fenchel (const Vector< T > &input, T &val, T &scal) const
GraphPathConv (const ParamReg< T > &param)
virtual bool is_fenchel () const
void prox (const Vector< T > &x, Vector< T > &y, const T lambda)
virtual ~GraphPathConv ()
Public Member Functions inherited from spams::FISTA::Regularizer< T >
virtual bool is_intercept () const
virtual bool is_subgrad () const
Regularizer ()
Regularizer (const ParamReg< T > &param)
virtual void reset ()
virtual void sub_grad (const Vector< T > &input, Vector< T > &output) const
virtual ~Regularizer ()
Private Attributes
GraphPath< T > _graph
Additional Inherited Members
Protected Attributes inherited from spams::FISTA::Regularizer< T >
bool _intercept
bool _pos
Constructor & Destructor Documentation
template<typename T > spams::FISTA::GraphPathConv< T >::GraphPathConv (const ParamReg< T > & param) inline
Definition at line 2100 of file fista.h.
References spams::FISTA::ParamReg< T >::graph_path_st.
template<typename T > virtual spams::FISTA::GraphPathConv< T >::~GraphPathConv () inline virtual
Definition at line 2104 of file fista.h.
Member Function Documentation
template<typename T > T spams::FISTA::GraphPathConv< T >::eval (const Vector< T > & x) const inline virtual
Implements spams::FISTA::Regularizer< T >.
Definition at line 2111 of file fista.h.
References spams::Vector< T >::rawX().
template<typename T > T spams::FISTA::GraphPathConv< T >::eval_dual_norm (const Vector< T > & x) const inline virtual
Reimplemented from spams::FISTA::Regularizer< T >.
Definition at line 2114 of file fista.h.
References spams::FISTA::ParamFISTA< T >::eval_dual_norm, and spams::Vector< T >::rawX().
template<typename T > T spams::FISTA::GraphPathConv< T >::eval_dual_norm_paths (const Vector< T > & x, SpMatrix< T > & paths_mat) const inline virtual
Reimplemented from spams::FISTA::Regularizer< T >.
Definition at line 2125 of file fista.h.
References spams::FISTA::ParamFISTA< T >::eval_dual_norm, spams::Path< Int >::flow, spams::Path< Int >::flow_int, spams::SpMatrix< T >::n(), spams::Path< Int >::nodes, and spams::Vector< T >::rawX().
template<typename T > T spams::FISTA::GraphPathConv< T >::eval_paths (const Vector< T > & x, SpMatrix< T > & paths_mat) const inline virtual
Reimplemented from spams::FISTA::Regularizer< T >.
Definition at line 2117 of file fista.h.
References spams::SpMatrix< T >::n(), and spams::Vector< T >::rawX().
template<typename T > void spams::FISTA::GraphPathConv< T >::fenchel (const Vector< T > & input, T & val, T & scal) const inline virtual
returns phi^star(input) and ouput=input if the fenchel is unconstrained returns 0 and scale input such that phi^star(output)=0 otherwise
Implements spams::FISTA::Regularizer< T >.
Definition at line 2137 of file fista.h.
References spams::Vector< T >::copy(), EPSILON, spams::FISTA::ParamFISTA< T >::eval_dual_norm, INFINITY, spams::Vector< T >::n(), spams::Vector< T >::rawX(), and spams::Vector< T >::thrsPos().
template<typename T > virtual bool spams::FISTA::GraphPathConv< T >::is_fenchel () const inline virtual
Reimplemented from spams::FISTA::Regularizer< T >.
Definition at line 2135 of file fista.h.
template<typename T > void spams::FISTA::GraphPathConv< T >::prox (const Vector< T > & x, Vector< T > & y, const T lambda) inline virtual
Implements spams::FISTA::Regularizer< T >.
Definition at line 2106 of file fista.h.
References spams::Vector< T >::copy(), spams::FISTA::ParamFISTA< T >::lambda, spams::Vector< T >::rawX(), and spams::Vector< T >::thrsPos().
Member Data Documentation
template<typename T > GraphPath<T> spams::FISTA::GraphPathConv< T >::_graph private
Definition at line 2150 of file fista.h.
The documentation for this class was generated from the following file:
ThirdParty/Spams/include/fista.h