DMRITool: itk::SamplingSchemeQSpaceIncrementalEstimationFilter< TSamplingType > Class Template Reference
itk::SamplingSchemeQSpaceIncrementalEstimationFilter< TSamplingType > Class Template Reference
SamplingScheme
#include <itkSamplingSchemeQSpaceIncrementalEstimationFilter.h>
Detailed Description
template<class TSamplingType>
class itk::SamplingSchemeQSpaceIncrementalEstimationFilter< TSamplingType >
incremental estimation of single/multi-shell orientations
Author
Jian Cheng (JC), jian..nosp@m.chen.nosp@m.g.198.nosp@m.3@gm.nosp@m.ail.c.nosp@m.om
Definition at line 36 of file itkSamplingSchemeQSpaceIncrementalEstimationFilter.h.
Public Types
typedef SmartPointer< const Self > ConstPointer
typedef Superclass::Index2DVectorPointer Index2DVectorPointer
typedef Superclass::Index2DVectorType Index2DVectorType
typedef Superclass::IndexVectorType IndexVectorType
typedef Superclass::MatrixPointer MatrixPointer
typedef Superclass::MatrixType MatrixType
typedef SmartPointer< Self > Pointer
typedef SamplingType::Pointer SamplingPointer
typedef TSamplingType SamplingType
typedef SamplingSchemeQSpaceIncrementalEstimationFilter Self
typedef Superclass::STDVectorPointer STDVectorPointer
typedef Superclass::STDVectorType STDVectorType
typedef SamplingSchemeQSpaceEstimationFilter< TSamplingType > Superclass
typedef Superclass::ValueType ValueType
Public Types inherited from itk::SamplingSchemeQSpaceEstimationFilter< TSamplingType >
typedef SmartPointer< const Self > ConstPointer
enum CriteriaType {
DISTANCE =0,
ELECTROSTATIC
}
typedef SamplingType::Index2DVectorPointer Index2DVectorPointer
typedef SamplingType::Index2DVectorType Index2DVectorType
typedef SamplingType::IndexVectorType IndexVectorType
typedef SamplingType::MatrixPointer MatrixPointer
typedef SamplingType::MatrixType MatrixType
typedef SmartPointer< Self > Pointer
typedef SamplingType::ConstPointer SamplingConstPointer
typedef SamplingType::Pointer SamplingPointer
typedef TSamplingType SamplingType
typedef SamplingSchemeQSpaceEstimationFilter Self
typedef SamplingType::STDVectorPointer STDVectorPointer
typedef SamplingType::STDVectorType STDVectorType
typedef LightProcessObject Superclass
typedef SamplingType::ValueType ValueType
Public Member Functions
virtual ::itk::LightObject::Pointer CreateAnother (void) const
void GenerateData () ITK_OVERRIDE
virtual MatrixPointer GetFineOrientations ()
virtual const char * GetNameOfClass () const
virtual unsigned int GetTessellationOrder ()
virtual void SetFineOrientations (MatrixPointer _arg)
virtual void SetTessellationOrder (unsigned int _arg)
Public Member Functions inherited from itk::SamplingSchemeQSpaceEstimationFilter< TSamplingType >
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual CriteriaType GetCriteriaType ()
virtual double GetElectrostaticOrder ()
virtual IndexVectorType GetNumbersInShell ()
virtual const SamplingType * GetOutputOrientations () const
virtual double GetWeightForSingleShell ()
bool IsSetInitialization () const
itkGetObjectMacro (InitialOrientations, SamplingType)
itkGetObjectMacro (OutputOrientations, SamplingType)
itkSetNDebugMacro (NumbersInShell, IndexVectorType)
virtual void SetCriteriaType (CriteriaType _arg)
virtual void SetElectrostaticOrder (double _arg)
virtual void SetInitialOrientations (SamplingType *_arg)
virtual void SetWeightForSingleShell (double _arg)
Static Public Member Functions
static Pointer New ()
Static Public Member Functions inherited from itk::SamplingSchemeQSpaceEstimationFilter< TSamplingType >
static Pointer New ()
Protected Member Functions
void Initialization () ITK_OVERRIDE
SamplingSchemeQSpaceIncrementalEstimationFilter ()
~SamplingSchemeQSpaceIncrementalEstimationFilter ()
Protected Member Functions inherited from itk::SamplingSchemeQSpaceEstimationFilter< TSamplingType >
SamplingSchemeQSpaceEstimationFilter ()
~SamplingSchemeQSpaceEstimationFilter ()
Protected Attributes
MatrixPointer m_FineOrientations
unsigned int m_TessellationOrder
Protected Attributes inherited from itk::SamplingSchemeQSpaceEstimationFilter< TSamplingType >
CriteriaType m_CriteriaType
double m_ElectrostaticOrder
SamplingPointer m_InitialOrientations
IndexVectorType m_NumbersInShell
SamplingPointer m_OutputOrientations
double m_WeightForSingleShell
Private Member Functions
void operator= (const Self &)
SamplingSchemeQSpaceIncrementalEstimationFilter (const Self &)
Member Typedef Documentation
template<class TSamplingType > typedef SmartPointer< const Self > itk::SamplingSchemeQSpaceIncrementalEstimationFilter< TSamplingType >::ConstPointer
Definition at line 45 of file itkSamplingSchemeQSpaceIncrementalEstimationFilter.h.
template<class TSamplingType > typedef Superclass::Index2DVectorPointer itk::SamplingSchemeQSpaceIncrementalEstimationFilter< TSamplingType >::Index2DVectorPointer
Definition at line 57 of file itkSamplingSchemeQSpaceIncrementalEstimationFilter.h.
template<class TSamplingType > typedef Superclass::Index2DVectorType itk::SamplingSchemeQSpaceIncrementalEstimationFilter< TSamplingType >::Index2DVectorType
Definition at line 56 of file itkSamplingSchemeQSpaceIncrementalEstimationFilter.h.
template<class TSamplingType > typedef Superclass::IndexVectorType itk::SamplingSchemeQSpaceIncrementalEstimationFilter< TSamplingType >::IndexVectorType
Definition at line 55 of file itkSamplingSchemeQSpaceIncrementalEstimationFilter.h.
template<class TSamplingType > typedef Superclass::MatrixPointer itk::SamplingSchemeQSpaceIncrementalEstimationFilter< TSamplingType >::MatrixPointer
Definition at line 52 of file itkSamplingSchemeQSpaceIncrementalEstimationFilter.h.
template<class TSamplingType > typedef Superclass::MatrixType itk::SamplingSchemeQSpaceIncrementalEstimationFilter< TSamplingType >::MatrixType
Definition at line 51 of file itkSamplingSchemeQSpaceIncrementalEstimationFilter.h.
template<class TSamplingType > typedef SmartPointer< Self > itk::SamplingSchemeQSpaceIncrementalEstimationFilter< TSamplingType >::Pointer
Definition at line 44 of file itkSamplingSchemeQSpaceIncrementalEstimationFilter.h.
template<class TSamplingType > typedef SamplingType::Pointer itk::SamplingSchemeQSpaceIncrementalEstimationFilter< TSamplingType >::SamplingPointer
Definition at line 48 of file itkSamplingSchemeQSpaceIncrementalEstimationFilter.h.
template<class TSamplingType > typedef TSamplingType itk::SamplingSchemeQSpaceIncrementalEstimationFilter< TSamplingType >::SamplingType
Definition at line 47 of file itkSamplingSchemeQSpaceIncrementalEstimationFilter.h.
template<class TSamplingType > typedef SamplingSchemeQSpaceIncrementalEstimationFilter itk::SamplingSchemeQSpaceIncrementalEstimationFilter< TSamplingType >::Self
Standard class typedefs.
Definition at line 42 of file itkSamplingSchemeQSpaceIncrementalEstimationFilter.h.
template<class TSamplingType > typedef Superclass::STDVectorPointer itk::SamplingSchemeQSpaceIncrementalEstimationFilter< TSamplingType >::STDVectorPointer
Definition at line 54 of file itkSamplingSchemeQSpaceIncrementalEstimationFilter.h.
template<class TSamplingType > typedef Superclass::STDVectorType itk::SamplingSchemeQSpaceIncrementalEstimationFilter< TSamplingType >::STDVectorType
Definition at line 53 of file itkSamplingSchemeQSpaceIncrementalEstimationFilter.h.
template<class TSamplingType > typedef SamplingSchemeQSpaceEstimationFilter<TSamplingType> itk::SamplingSchemeQSpaceIncrementalEstimationFilter< TSamplingType >::Superclass
Definition at line 43 of file itkSamplingSchemeQSpaceIncrementalEstimationFilter.h.
template<class TSamplingType > typedef Superclass::ValueType itk::SamplingSchemeQSpaceIncrementalEstimationFilter< TSamplingType >::ValueType
Definition at line 50 of file itkSamplingSchemeQSpaceIncrementalEstimationFilter.h.
Constructor & Destructor Documentation
template<class TSamplingType > itk::SamplingSchemeQSpaceIncrementalEstimationFilter< TSamplingType >::SamplingSchemeQSpaceIncrementalEstimationFilter () protected
Definition at line 29 of file itkSamplingSchemeQSpaceIncrementalEstimationFilter.hxx.
References itk::SamplingSchemeQSpaceIncrementalEstimationFilter< TSamplingType >::Initialization().
template<class TSamplingType > itk::SamplingSchemeQSpaceIncrementalEstimationFilter< TSamplingType >::~SamplingSchemeQSpaceIncrementalEstimationFilter () inline protected
Definition at line 75 of file itkSamplingSchemeQSpaceIncrementalEstimationFilter.h.
References ITK_OVERRIDE.
template<class TSamplingType > itk::SamplingSchemeQSpaceIncrementalEstimationFilter< TSamplingType >::SamplingSchemeQSpaceIncrementalEstimationFilter (const Self &) private
Member Function Documentation
template<class TSamplingType > virtual::itk::LightObject::Pointer itk::SamplingSchemeQSpaceIncrementalEstimationFilter< TSamplingType >::CreateAnother (void) const
template<class TSamplingType > void itk::SamplingSchemeQSpaceIncrementalEstimationFilter< TSamplingType >::GenerateData (void) virtual
Reimplemented from itk::SamplingSchemeQSpaceEstimationFilter< TSamplingType >.
Definition at line 96 of file itkSamplingSchemeQSpaceIncrementalEstimationFilter.hxx.
References spams::abs(), utl::max(), utlException, and utlGlobalException.
Referenced by itk::SamplingSchemeQSpaceIncrementalEstimationFilter< TSamplingType >::Initialization().
template<class TSamplingType > virtual MatrixPointer itk::SamplingSchemeQSpaceIncrementalEstimationFilter< TSamplingType >::GetFineOrientations () virtual
template<class TSamplingType > virtual const char* itk::SamplingSchemeQSpaceIncrementalEstimationFilter< TSamplingType >::GetNameOfClass () const virtual
Standard Macros
Reimplemented from itk::SamplingSchemeQSpaceEstimationFilter< TSamplingType >.
template<class TSamplingType > virtual unsigned int itk::SamplingSchemeQSpaceIncrementalEstimationFilter< TSamplingType >::GetTessellationOrder () virtual
template<class TSamplingType > void itk::SamplingSchemeQSpaceIncrementalEstimationFilter< TSamplingType >::Initialization () protected virtual
Reimplemented from itk::SamplingSchemeQSpaceEstimationFilter< TSamplingType >.
Definition at line 39 of file itkSamplingSchemeQSpaceIncrementalEstimationFilter.hxx.
References CARTESIAN_TO_CARTESIAN, utl::ConnectUtlMatrix(), DIRECTION_NODUPLICATE, itk::SamplingSchemeQSpaceIncrementalEstimationFilter< TSamplingType >::GenerateData(), and utlGlobalException.
Referenced by itk::SamplingSchemeQSpaceIncrementalEstimationFilter< TSamplingType >::SamplingSchemeQSpaceIncrementalEstimationFilter().
template<class TSamplingType > static Pointer itk::SamplingSchemeQSpaceIncrementalEstimationFilter< TSamplingType >::New () static
template<class TSamplingType > void itk::SamplingSchemeQSpaceIncrementalEstimationFilter< TSamplingType >::operator= (const Self &) private
template<class TSamplingType > virtual void itk::SamplingSchemeQSpaceIncrementalEstimationFilter< TSamplingType >::SetFineOrientations (MatrixPointer _arg) virtual
template<class TSamplingType > virtual void itk::SamplingSchemeQSpaceIncrementalEstimationFilter< TSamplingType >::SetTessellationOrder (unsigned int _arg) virtual
Member Data Documentation
template<class TSamplingType > MatrixPointer itk::SamplingSchemeQSpaceIncrementalEstimationFilter< TSamplingType >::m_FineOrientations protected
It is the input data or generated from m_TessellationOrder
Definition at line 83 of file itkSamplingSchemeQSpaceIncrementalEstimationFilter.h.
template<class TSamplingType > unsigned int itk::SamplingSchemeQSpaceIncrementalEstimationFilter< TSamplingType >::m_TessellationOrder protected
the order of tessellation for the orignal fine mesh
Definition at line 80 of file itkSamplingSchemeQSpaceIncrementalEstimationFilter.h.
The documentation for this class was generated from the following files:
Modules/SamplingScheme/include/itkSamplingSchemeQSpaceIncrementalEstimationFilter.h
Modules/SamplingScheme/include/itkSamplingSchemeQSpaceIncrementalEstimationFilter.hxx