DMRITool: itk::MeshFromFiberTractsFilter Class Reference
itk::MeshFromFiberTractsFilter Class Reference
Visualization
#include <itkMeshFromFiberTractsFilter.h>
Detailed Description
Compute mesh from fibers.
Author
Jian Cheng (jian..nosp@m.chen.nosp@m.g.198.nosp@m.3@gm.nosp@m.ail.c.nosp@m.om)
Definition at line 31 of file itkMeshFromFiberTractsFilter.h.
Public Types
enum ColorSchemeType {
COLOR_NONE =0,
COLOR_FIXED,
COLOR_BY_POINT_DIRECTION,
COLOR_BY_MEAN_DIRECTION,
COLOR_BY_ENDPOINTS_DIRECTION,
COLOR_BY_IMAGE,
COLOR_BY_SCALARS,
COLOR_BY_PROPERTY
}
typedef FiberTractsType::FiberPointer FiberPointer
typedef FiberTractsType::Pointer FiberTractsPointer
typedef FiberTracts< double > FiberTractsType
typedef FiberTractsType::FiberType FiberType
enum GlyphShapeType {
GLYPH_LINE =0,
GLYPH_TUBE
}
typedef vtkSmartPointer< vtkPolyData > OutputMeshPolyDataPointer
typedef vtkPolyData OutputMeshPolyDataType
typedef SmartPointer< Self > Pointer
typedef MeshFromFiberTractsFilter Self
typedef FiberType::STDVectorType STDVectorType
typedef LightProcessObject Superclass
typedef FiberType::VertexType VertexType
Public Member Functions
virtual ::itk::LightObject::Pointer CreateAnother (void) const
const double * GetColor () const
std::vector< int > GetFlip () const
virtual const char * GetNameOfClass () const
OutputMeshPolyDataPointer GetOutput () const
itkSetGetMacro (FiberTracts, FiberTractsPointer)
itkSetGetMacro (ColorScheme, ColorSchemeType)
itkSetGetMacro (ShapeMode, GlyphShapeType)
itkSetGetMacro (TubeRadius, double)
void SetColor (double r, double g, double b)
void SetFlip (const int flipx, const int flipy, const int flipz)
virtual void Update ()
Static Public Member Functions
static Pointer New ()
Protected Member Functions
LightObject::Pointer InternalClone () const ITK_OVERRIDE
MeshFromFiberTractsFilter ()
void PrintSelf (std::ostream &os, Indent indent) const ITK_OVERRIDE
~MeshFromFiberTractsFilter ()
Protected Attributes
double m_Color [3] ={255,0,0}
ColorSchemeType m_ColorScheme =COLOR_BY_POINT_DIRECTION
FiberTractsPointer m_FiberTracts = FiberTractsType::New()
std::vector< int > m_Flip = std::vector<int>(3, 0)
OutputMeshPolyDataPointer m_Mesh = OutputMeshPolyDataType::New()
GlyphShapeType m_ShapeMode =GLYPH_LINE
double m_TubeRadius =0.2
Private Member Functions
MeshFromFiberTractsFilter (const Self &)
void operator= (const Self &)
Member Typedef Documentation
typedef FiberTractsType::FiberPointer itk::MeshFromFiberTractsFilter::FiberPointer
Definition at line 48 of file itkMeshFromFiberTractsFilter.h.
typedef FiberTractsType::Pointer itk::MeshFromFiberTractsFilter::FiberTractsPointer
Definition at line 46 of file itkMeshFromFiberTractsFilter.h.
typedef FiberTracts<double> itk::MeshFromFiberTractsFilter::FiberTractsType
Definition at line 43 of file itkMeshFromFiberTractsFilter.h.
typedef FiberTractsType::FiberType itk::MeshFromFiberTractsFilter::FiberType
Definition at line 47 of file itkMeshFromFiberTractsFilter.h.
typedef vtkSmartPointer<vtkPolyData> itk::MeshFromFiberTractsFilter::OutputMeshPolyDataPointer
Definition at line 53 of file itkMeshFromFiberTractsFilter.h.
typedef vtkPolyData itk::MeshFromFiberTractsFilter::OutputMeshPolyDataType
Definition at line 52 of file itkMeshFromFiberTractsFilter.h.
typedef SmartPointer<Self> itk::MeshFromFiberTractsFilter::Pointer
Definition at line 37 of file itkMeshFromFiberTractsFilter.h.
typedef MeshFromFiberTractsFilter itk::MeshFromFiberTractsFilter::Self
Standard class typedefs.
Definition at line 35 of file itkMeshFromFiberTractsFilter.h.
typedef FiberType::STDVectorType itk::MeshFromFiberTractsFilter::STDVectorType
Definition at line 49 of file itkMeshFromFiberTractsFilter.h.
typedef LightProcessObject itk::MeshFromFiberTractsFilter::Superclass
Definition at line 36 of file itkMeshFromFiberTractsFilter.h.
typedef FiberType::VertexType itk::MeshFromFiberTractsFilter::VertexType
Definition at line 50 of file itkMeshFromFiberTractsFilter.h.
Member Enumeration Documentation
enum itk::MeshFromFiberTractsFilter::ColorSchemeType
Enumerator
COLOR_NONE
default color
COLOR_FIXED
fixed color
COLOR_BY_POINT_DIRECTION
by direction in each point
COLOR_BY_MEAN_DIRECTION
by mean direction in a tract
COLOR_BY_ENDPOINTS_DIRECTION
by start and end points
COLOR_BY_IMAGE
by an input image
COLOR_BY_SCALARS
by scalar
COLOR_BY_PROPERTY
by scalar
Definition at line 64 of file itkMeshFromFiberTractsFilter.h.
enum itk::MeshFromFiberTractsFilter::GlyphShapeType
enum of the possible shapes for the glyphs
Enumerator
GLYPH_LINE
lines
GLYPH_TUBE
tubes
Definition at line 56 of file itkMeshFromFiberTractsFilter.h.
Constructor & Destructor Documentation
itk::MeshFromFiberTractsFilter::MeshFromFiberTractsFilter () inline protected
Definition at line 119 of file itkMeshFromFiberTractsFilter.h.
itk::MeshFromFiberTractsFilter::~MeshFromFiberTractsFilter () inline protected
Definition at line 120 of file itkMeshFromFiberTractsFilter.h.
References ITK_OVERRIDE.
itk::MeshFromFiberTractsFilter::MeshFromFiberTractsFilter (const Self &) private
Member Function Documentation
virtual::itk::LightObject::Pointer itk::MeshFromFiberTractsFilter::CreateAnother (void) const
const double* itk::MeshFromFiberTractsFilter::GetColor () const inline
Definition at line 95 of file itkMeshFromFiberTractsFilter.h.
std::vector<int> itk::MeshFromFiberTractsFilter::GetFlip () const inline
Definition at line 104 of file itkMeshFromFiberTractsFilter.h.
virtual const char* itk::MeshFromFiberTractsFilter::GetNameOfClass () const virtual
Run-time type information (and related methods).
OutputMeshPolyDataPointer itk::MeshFromFiberTractsFilter::GetOutput () const inline
Definition at line 112 of file itkMeshFromFiberTractsFilter.h.
LightObject::Pointer itk::MeshFromFiberTractsFilter::InternalClone () const protected
Definition at line 32 of file itkMeshFromFiberTractsFilter.hxx.
References Update().
itk::MeshFromFiberTractsFilter::itkSetGetMacro (FiberTracts , FiberTractsPointer)
itk::MeshFromFiberTractsFilter::itkSetGetMacro (ColorScheme , ColorSchemeType)
itk::MeshFromFiberTractsFilter::itkSetGetMacro (ShapeMode , GlyphShapeType)
itk::MeshFromFiberTractsFilter::itkSetGetMacro (TubeRadius , double)
static Pointer itk::MeshFromFiberTractsFilter::New () static
Method for creation through the object factory.
void itk::MeshFromFiberTractsFilter::operator= (const Self &) private
void itk::MeshFromFiberTractsFilter::PrintSelf (std::ostream & os, Indent indent) const inline protected
Definition at line 124 of file itkMeshFromFiberTractsFilter.h.
References PrintVar, and utl::PrintVector().
void itk::MeshFromFiberTractsFilter::SetColor (double r, double g, double b) inline
Definition at line 91 of file itkMeshFromFiberTractsFilter.h.
void itk::MeshFromFiberTractsFilter::SetFlip (const int flipx, const int flipy, const int flipz) inline
Definition at line 100 of file itkMeshFromFiberTractsFilter.h.
void itk::MeshFromFiberTractsFilter::Update () virtual
Does the real work.
Definition at line 57 of file itkMeshFromFiberTractsFilter.hxx.
References utl::FlipVector(), utl::NDArrayBase< T, 1 >::GetTwoNorm(), utlGlobalException, utlPrintVar, and utl::VectorToVector().
Referenced by InternalClone().
Member Data Documentation
double itk::MeshFromFiberTractsFilter::m_Color[3] ={255,0,0} protected
Definition at line 142 of file itkMeshFromFiberTractsFilter.h.
ColorSchemeType itk::MeshFromFiberTractsFilter::m_ColorScheme =COLOR_BY_POINT_DIRECTION protected
Definition at line 136 of file itkMeshFromFiberTractsFilter.h.
FiberTractsPointer itk::MeshFromFiberTractsFilter::m_FiberTracts = FiberTractsType::New() protected
Definition at line 134 of file itkMeshFromFiberTractsFilter.h.
std::vector<int> itk::MeshFromFiberTractsFilter::m_Flip = std::vector<int>(3, 0) protected
flips in x/y/z-axis. 0 means no flip, 1 means flip
Definition at line 147 of file itkMeshFromFiberTractsFilter.h.
OutputMeshPolyDataPointer itk::MeshFromFiberTractsFilter::m_Mesh = OutputMeshPolyDataType::New() protected
Definition at line 140 of file itkMeshFromFiberTractsFilter.h.
GlyphShapeType itk::MeshFromFiberTractsFilter::m_ShapeMode =GLYPH_LINE protected
Definition at line 138 of file itkMeshFromFiberTractsFilter.h.
double itk::MeshFromFiberTractsFilter::m_TubeRadius =0.2 protected
Definition at line 144 of file itkMeshFromFiberTractsFilter.h.
The documentation for this class was generated from the following files:
Modules/Visualization/include/itkMeshFromFiberTractsFilter.h
Modules/Visualization/include/itkMeshFromFiberTractsFilter.hxx