DMRITool: itk::CastImageFileWriter< TInputImage > Class Template Reference
itk::CastImageFileWriter< TInputImage > Class Template Reference
#include <itkCastImageFileWriter.h>
Detailed Description
template<class TInputImage>
class itk::CastImageFileWriter< TInputImage >
Writes image data, after casting, to a single file.
Definition at line 32 of file itkCastImageFileWriter.h.
Public Types
typedef SmartPointer< const Self > ConstPointer
typedef InputImageType::PixelType InputImagePixelType
typedef InputImageType::Pointer InputImagePointer
typedef InputImageType::RegionType InputImageRegionType
typedef TInputImage InputImageType
typedef ImageIOBase::IOComponentType IOComponentType
typedef SmartPointer< Self > Pointer
typedef CastImageFileWriter Self
typedef ProcessObject Superclass
Public Member Functions
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual IOComponentType GetComponentType () const
virtual const char * GetFileName () const
const InputImageType * GetInput (void)
const InputImageType * GetInput (unsigned int idx)
const ImageIORegion & GetIORegion (void) const
virtual const char * GetNameOfClass () const
virtual const unsigned int & GetNumberOfStreamDivisions ()
virtual const bool & GetUseCompression ()
virtual const bool & GetUseInputMetaDataDictionary ()
itkGetObjectMacro (ImageIO, ImageIOBase)
virtual void SetComponentType (const IOComponentType _arg)
virtual void SetFileName (const char *_arg)
void SetImageIO (ImageIOBase *io)
virtual void SetInput (const InputImageType *input)
void SetIORegion (const ImageIORegion &region)
virtual void SetNumberOfStreamDivisions (unsigned int _arg)
virtual void SetUseCompression (bool _arg)
virtual void SetUseInputMetaDataDictionary (bool _arg)
virtual void Update () ITK_OVERRIDE
virtual void UseCompressionOff ()
virtual void UseCompressionOn ()
virtual void UseInputMetaDataDictionaryOff ()
virtual void UseInputMetaDataDictionaryOn ()
virtual void Write (void)
Static Public Member Functions
static Pointer New ()
Protected Member Functions
CastImageFileWriter ()
void GenerateData (void) ITK_OVERRIDE
void PrintSelf (std::ostream &os, Indent indent) const ITK_OVERRIDE
~CastImageFileWriter ()
Private Member Functions
CastImageFileWriter (const Self &)
void operator= (const Self &)
Private Attributes
IOComponentType m_ComponentType
bool m_FactorySpecifiedImageIO
std::string m_FileName
ImageIOBase::Pointer m_ImageIO
unsigned int m_NumberOfStreamDivisions
ImageIORegion m_PasteIORegion
bool m_UseCompression
bool m_UseInputMetaDataDictionary
bool m_UserSpecifiedImageIO
bool m_UserSpecifiedIORegion
Member Typedef Documentation
template<class TInputImage> typedef SmartPointer<const Self> itk::CastImageFileWriter< TInputImage >::ConstPointer
Definition at line 39 of file itkCastImageFileWriter.h.
template<class TInputImage> typedef InputImageType::PixelType itk::CastImageFileWriter< TInputImage >::InputImagePixelType
Definition at line 51 of file itkCastImageFileWriter.h.
template<class TInputImage> typedef InputImageType::Pointer itk::CastImageFileWriter< TInputImage >::InputImagePointer
Definition at line 49 of file itkCastImageFileWriter.h.
template<class TInputImage> typedef InputImageType::RegionType itk::CastImageFileWriter< TInputImage >::InputImageRegionType
Definition at line 50 of file itkCastImageFileWriter.h.
template<class TInputImage> typedef TInputImage itk::CastImageFileWriter< TInputImage >::InputImageType
Some convenient typedefs.
Definition at line 45 of file itkCastImageFileWriter.h.
template<class TInputImage> typedef ImageIOBase::IOComponentType itk::CastImageFileWriter< TInputImage >::IOComponentType
Definition at line 53 of file itkCastImageFileWriter.h.
template<class TInputImage> typedef SmartPointer<Self> itk::CastImageFileWriter< TInputImage >::Pointer
Definition at line 38 of file itkCastImageFileWriter.h.
template<class TInputImage> typedef CastImageFileWriter itk::CastImageFileWriter< TInputImage >::Self
Standard class typedefs.
Definition at line 36 of file itkCastImageFileWriter.h.
template<class TInputImage> typedef ProcessObject itk::CastImageFileWriter< TInputImage >::Superclass
Definition at line 37 of file itkCastImageFileWriter.h.
Constructor & Destructor Documentation
template<class TInputImage > itk::CastImageFileWriter< TInputImage >::CastImageFileWriter () protected
Definition at line 30 of file itkCastImageFileWriter.hxx.
References itk::CastImageFileWriter< TInputImage >::~CastImageFileWriter().
template<class TInputImage > itk::CastImageFileWriter< TInputImage >::~CastImageFileWriter () protected
Definition at line 45 of file itkCastImageFileWriter.hxx.
References itk::CastImageFileWriter< TInputImage >::SetInput().
Referenced by itk::CastImageFileWriter< TInputImage >::CastImageFileWriter().
template<class TInputImage> itk::CastImageFileWriter< TInputImage >::CastImageFileWriter (const Self &) private
Member Function Documentation
template<class TInputImage> virtual::itk::LightObject::Pointer itk::CastImageFileWriter< TInputImage >::CreateAnother (void) const
template<class TInputImage > void itk::CastImageFileWriter< TInputImage >::GenerateData (void) protected
Does the real work.
Definition at line 115 of file itkCastImageFileWriter.hxx.
References itk::CastImageFileWriter< TInputImage >::PrintSelf().
Referenced by itk::CastImageFileWriter< TInputImage >::Write().
template<class TInputImage> virtual IOComponentType itk::CastImageFileWriter< TInputImage >::GetComponentType () const virtual
template<class TInputImage> virtual const char* itk::CastImageFileWriter< TInputImage >::GetFileName () const virtual
template<class TInputImage > const CastImageFileWriter< TInputImage >::InputImageType * itk::CastImageFileWriter< TInputImage >::GetInput (void)
Definition at line 65 of file itkCastImageFileWriter.hxx.
Referenced by itk::CastImageFileWriter< TInputImage >::SetInput().
template<class TInputImage > const CastImageFileWriter< TInputImage >::InputImageType * itk::CastImageFileWriter< TInputImage >::GetInput (unsigned int idx)
Definition at line 80 of file itkCastImageFileWriter.hxx.
References itk::CastImageFileWriter< TInputImage >::SetIORegion().
template<class TInputImage> const ImageIORegion& itk::CastImageFileWriter< TInputImage >::GetIORegion (void) const inline
Definition at line 98 of file itkCastImageFileWriter.h.
template<class TInputImage> virtual const char* itk::CastImageFileWriter< TInputImage >::GetNameOfClass () const virtual
Run-time type information (and related methods).
template<class TInputImage> virtual const unsigned int& itk::CastImageFileWriter< TInputImage >::GetNumberOfStreamDivisions () virtual
template<class TInputImage> virtual const bool& itk::CastImageFileWriter< TInputImage >::GetUseCompression () virtual
template<class TInputImage> virtual const bool& itk::CastImageFileWriter< TInputImage >::GetUseInputMetaDataDictionary () virtual
template<class TInputImage> itk::CastImageFileWriter< TInputImage >::itkGetObjectMacro (ImageIO , ImageIOBase)
template<class TInputImage> static Pointer itk::CastImageFileWriter< TInputImage >::New () static
Method for creation through the object factory.
template<class TInputImage> void itk::CastImageFileWriter< TInputImage >::operator= (const Self &) private
template<class TInputImage > void itk::CastImageFileWriter< TInputImage >::PrintSelf (std::ostream & os, Indent indent) const protected
Definition at line 322 of file itkCastImageFileWriter.hxx.
Referenced by itk::CastImageFileWriter< TInputImage >::GenerateData().
template<class TInputImage> virtual void itk::CastImageFileWriter< TInputImage >::SetComponentType (const IOComponentType _arg) virtual
Set/Get component type
template<class TInputImage> virtual void itk::CastImageFileWriter< TInputImage >::SetFileName (const char * _arg) virtual
Specify the name of the output file to write.
template<class TInputImage> void itk::CastImageFileWriter< TInputImage >::SetImageIO (ImageIOBase * io) inline
Set/Get the ImageIO helper class. Usually this is created via the object factory mechanism that determines whether a particular ImageIO can write a certain file. This method provides a way to get the ImageIO instance that is created, or one can be manually set where the IO factory mechanism may not work (for example, raw image files or image files with non-standard filename suffix's. If the user specifies the ImageIO, we assume she makes the correct choice and will allow a file to be created regardless of the file extension. If the factory has set the ImageIO, the extension must be supported by the specified ImageIO.
Definition at line 75 of file itkCastImageFileWriter.h.
template<class TInputImage > void itk::CastImageFileWriter< TInputImage >::SetInput (const InputImageType * input) virtual
Definition at line 53 of file itkCastImageFileWriter.hxx.
References itk::CastImageFileWriter< TInputImage >::GetInput().
Referenced by itk::CastImageFileWriter< TInputImage >::~CastImageFileWriter().
template<class TInputImage > void itk::CastImageFileWriter< TInputImage >::SetIORegion (const ImageIORegion & region)
Specify the region to write. If left NULL, then the whole image is written.
Definition at line 89 of file itkCastImageFileWriter.hxx.
References itk::CastImageFileWriter< TInputImage >::Write().
Referenced by itk::CastImageFileWriter< TInputImage >::GetInput().
template<class TInputImage> virtual void itk::CastImageFileWriter< TInputImage >::SetNumberOfStreamDivisions (unsigned int _arg) virtual
Set/Get the number of pieces to divide the input. The upstream pipeline will try to be executed this many times.
template<class TInputImage> virtual void itk::CastImageFileWriter< TInputImage >::SetUseCompression (bool _arg) virtual
Set the compression On or Off
template<class TInputImage> virtual void itk::CastImageFileWriter< TInputImage >::SetUseInputMetaDataDictionary (bool _arg) virtual
By default the MetaDataDictionary is taken from the input image and passed to the ImageIO. In some cases, however, a user may prefer to introduce her/his own MetaDataDictionary. This is often the case of the ImageSeriesWriter. This flag defined whether the MetaDataDictionary to use will be the one from the input image or the one already set in the ImageIO object.
template<class TInputImage> virtual void itk::CastImageFileWriter< TInputImage >::Update () inline virtual
Aliased to the Write() method to be consistent with the rest of the pipeline.
Definition at line 112 of file itkCastImageFileWriter.h.
References ITK_OVERRIDE.
template<class TInputImage> virtual void itk::CastImageFileWriter< TInputImage >::UseCompressionOff () virtual
template<class TInputImage> virtual void itk::CastImageFileWriter< TInputImage >::UseCompressionOn () virtual
template<class TInputImage> virtual void itk::CastImageFileWriter< TInputImage >::UseInputMetaDataDictionaryOff () virtual
template<class TInputImage> virtual void itk::CastImageFileWriter< TInputImage >::UseInputMetaDataDictionaryOn () virtual
template<class TInputImage > void itk::CastImageFileWriter< TInputImage >::Write (void) virtual
A special version of the Update() method for writers. It invokes start and end events and handles releasing data. It eventually calls GenerateData() which does the actual writing. Note: the write method will write data specified by the IORegion. If not set, then then the whole image is written. Note that the region will be cropped to fit the input image's LargestPossibleRegion.
Definition at line 104 of file itkCastImageFileWriter.hxx.
References itk::CastImageFileWriter< TInputImage >::GenerateData().
Referenced by itk::CastImageFileWriter< TInputImage >::SetIORegion().
Member Data Documentation
template<class TInputImage> IOComponentType itk::CastImageFileWriter< TInputImage >::m_ComponentType private
Definition at line 165 of file itkCastImageFileWriter.h.
template<class TInputImage> bool itk::CastImageFileWriter< TInputImage >::m_FactorySpecifiedImageIO private
Definition at line 158 of file itkCastImageFileWriter.h.
template<class TInputImage> std::string itk::CastImageFileWriter< TInputImage >::m_FileName private
Definition at line 148 of file itkCastImageFileWriter.h.
template<class TInputImage> ImageIOBase::Pointer itk::CastImageFileWriter< TInputImage >::m_ImageIO private
Definition at line 150 of file itkCastImageFileWriter.h.
template<class TInputImage> unsigned int itk::CastImageFileWriter< TInputImage >::m_NumberOfStreamDivisions private
Definition at line 155 of file itkCastImageFileWriter.h.
template<class TInputImage> ImageIORegion itk::CastImageFileWriter< TInputImage >::m_PasteIORegion private
Definition at line 154 of file itkCastImageFileWriter.h.
template<class TInputImage> bool itk::CastImageFileWriter< TInputImage >::m_UseCompression private
Definition at line 160 of file itkCastImageFileWriter.h.
template<class TInputImage> bool itk::CastImageFileWriter< TInputImage >::m_UseInputMetaDataDictionary private
Definition at line 161 of file itkCastImageFileWriter.h.
template<class TInputImage> bool itk::CastImageFileWriter< TInputImage >::m_UserSpecifiedImageIO private
Definition at line 151 of file itkCastImageFileWriter.h.
template<class TInputImage> bool itk::CastImageFileWriter< TInputImage >::m_UserSpecifiedIORegion private
Definition at line 156 of file itkCastImageFileWriter.h.
The documentation for this class was generated from the following files:
Modules/Common/include/itkCastImageFileWriter.h
Modules/Common/include/itkCastImageFileWriter.hxx