DMRITool: itk::SamplingSchemeQSpaceIMOCEstimationFilter< TSamplingType > Class Template Reference
itk::SamplingSchemeQSpaceIMOCEstimationFilter< TSamplingType > Class Template Reference
SamplingScheme
#include <itkSamplingSchemeQSpaceIMOCEstimationFilter.h>
Detailed Description
template<class TSamplingType>
class itk::SamplingSchemeQSpaceIMOCEstimationFilter< TSamplingType >
Estimation of single/multi-shell orientations using Iterative Maximum Overlap Construction (IMOC)
Author
Jian Cheng (JC), jian..nosp@m.chen.nosp@m.g.198.nosp@m.3@gm.nosp@m.ail.c.nosp@m.om
Definition at line 38 of file itkSamplingSchemeQSpaceIMOCEstimationFilter.h.
Public Types
typedef SmartPointer< const Self > ConstPointer
typedef Superclass::Index2DVectorPointer Index2DVectorPointer
typedef Superclass::Index2DVectorType Index2DVectorType
typedef Superclass::IndexVectorType IndexVectorType
typedef Superclass::MatrixPointer MatrixPointer
typedef Superclass::MatrixType MatrixType
typedef itk::Point< double, 3 > MeasurementVectorType
typedef SmartPointer< Self > Pointer
typedef itk::Statistics::ListSample< MeasurementVectorType > SampleType
typedef SamplingType::Pointer SamplingPointer
typedef TSamplingType SamplingType
typedef SamplingSchemeQSpaceIMOCEstimationFilter Self
typedef Superclass::STDVectorPointer STDVectorPointer
typedef Superclass::STDVectorType STDVectorType
typedef SamplingSchemeQSpaceEstimationFilter< TSamplingType > Superclass
typedef itk::Statistics::KdTreeGenerator< SampleType > TreeGeneratorType
typedef TreeGeneratorType::KdTreeType TreeType
typedef Superclass::ValueType ValueType
Public Types inherited from itk::SamplingSchemeQSpaceEstimationFilter< TSamplingType >
typedef SmartPointer< const Self > ConstPointer
enum CriteriaType {
DISTANCE =0,
ELECTROSTATIC
}
typedef SamplingType::Index2DVectorPointer Index2DVectorPointer
typedef SamplingType::Index2DVectorType Index2DVectorType
typedef SamplingType::IndexVectorType IndexVectorType
typedef SamplingType::MatrixPointer MatrixPointer
typedef SamplingType::MatrixType MatrixType
typedef SmartPointer< Self > Pointer
typedef SamplingType::ConstPointer SamplingConstPointer
typedef SamplingType::Pointer SamplingPointer
typedef TSamplingType SamplingType
typedef SamplingSchemeQSpaceEstimationFilter Self
typedef SamplingType::STDVectorPointer STDVectorPointer
typedef SamplingType::STDVectorType STDVectorType
typedef LightProcessObject Superclass
typedef SamplingType::ValueType ValueType
Public Member Functions
virtual ::itk::LightObject::Pointer CreateAnother (void) const
void GenerateData () ITK_OVERRIDE
virtual const char * GetNameOfClass () const
itkSetGetMacro (TessellationOrder, unsigned int)
itkSetGetMacro (FineOrientations, MatrixPointer)
itkSetGetMacro (AngleMinChange, double)
itkSetGetMacro (ChooseMinimalCoverageShell, bool)
Public Member Functions inherited from itk::SamplingSchemeQSpaceEstimationFilter< TSamplingType >
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual CriteriaType GetCriteriaType ()
virtual double GetElectrostaticOrder ()
virtual IndexVectorType GetNumbersInShell ()
virtual const SamplingType * GetOutputOrientations () const
virtual double GetWeightForSingleShell ()
bool IsSetInitialization () const
itkGetObjectMacro (InitialOrientations, SamplingType)
itkGetObjectMacro (OutputOrientations, SamplingType)
itkSetNDebugMacro (NumbersInShell, IndexVectorType)
virtual void SetCriteriaType (CriteriaType _arg)
virtual void SetElectrostaticOrder (double _arg)
virtual void SetInitialOrientations (SamplingType *_arg)
virtual void SetWeightForSingleShell (double _arg)
Static Public Member Functions
static Pointer New ()
Static Public Member Functions inherited from itk::SamplingSchemeQSpaceEstimationFilter< TSamplingType >
static Pointer New ()
Protected Member Functions
void Initialization () ITK_OVERRIDE
bool IsSatisfiedSeparationAngles (const std::vector< double > &angles)
SamplingSchemeQSpaceIMOCEstimationFilter ()
~SamplingSchemeQSpaceIMOCEstimationFilter ()
Protected Member Functions inherited from itk::SamplingSchemeQSpaceEstimationFilter< TSamplingType >
SamplingSchemeQSpaceEstimationFilter ()
~SamplingSchemeQSpaceEstimationFilter ()
Protected Attributes
double m_AngleMinChange =0.0001
bool m_ChooseMinimalCoverageShell =true
MatrixPointer m_FineOrientations
SamplingPointer m_FineScheme = SamplingType::New()
TreeType::Pointer m_KDTree = nullptr
double m_MinDistanceInFineScheme =-1
SampleType::Pointer m_Sample
unsigned int m_TessellationOrder =7
TreeGeneratorType::Pointer m_TreeGenerator =nullptr
Protected Attributes inherited from itk::SamplingSchemeQSpaceEstimationFilter< TSamplingType >
CriteriaType m_CriteriaType
double m_ElectrostaticOrder
SamplingPointer m_InitialOrientations
IndexVectorType m_NumbersInShell
SamplingPointer m_OutputOrientations
double m_WeightForSingleShell
Private Member Functions
void operator= (const Self &)
SamplingSchemeQSpaceIMOCEstimationFilter (const Self &)
Member Typedef Documentation
template<class TSamplingType > typedef SmartPointer< const Self > itk::SamplingSchemeQSpaceIMOCEstimationFilter< TSamplingType >::ConstPointer
Definition at line 47 of file itkSamplingSchemeQSpaceIMOCEstimationFilter.h.
template<class TSamplingType > typedef Superclass::Index2DVectorPointer itk::SamplingSchemeQSpaceIMOCEstimationFilter< TSamplingType >::Index2DVectorPointer
Definition at line 59 of file itkSamplingSchemeQSpaceIMOCEstimationFilter.h.
template<class TSamplingType > typedef Superclass::Index2DVectorType itk::SamplingSchemeQSpaceIMOCEstimationFilter< TSamplingType >::Index2DVectorType
Definition at line 58 of file itkSamplingSchemeQSpaceIMOCEstimationFilter.h.
template<class TSamplingType > typedef Superclass::IndexVectorType itk::SamplingSchemeQSpaceIMOCEstimationFilter< TSamplingType >::IndexVectorType
Definition at line 57 of file itkSamplingSchemeQSpaceIMOCEstimationFilter.h.
template<class TSamplingType > typedef Superclass::MatrixPointer itk::SamplingSchemeQSpaceIMOCEstimationFilter< TSamplingType >::MatrixPointer
Definition at line 54 of file itkSamplingSchemeQSpaceIMOCEstimationFilter.h.
template<class TSamplingType > typedef Superclass::MatrixType itk::SamplingSchemeQSpaceIMOCEstimationFilter< TSamplingType >::MatrixType
Definition at line 53 of file itkSamplingSchemeQSpaceIMOCEstimationFilter.h.
template<class TSamplingType > typedef itk::Point<double,3> itk::SamplingSchemeQSpaceIMOCEstimationFilter< TSamplingType >::MeasurementVectorType
Definition at line 61 of file itkSamplingSchemeQSpaceIMOCEstimationFilter.h.
template<class TSamplingType > typedef SmartPointer< Self > itk::SamplingSchemeQSpaceIMOCEstimationFilter< TSamplingType >::Pointer
Definition at line 46 of file itkSamplingSchemeQSpaceIMOCEstimationFilter.h.
template<class TSamplingType > typedef itk::Statistics::ListSample< MeasurementVectorType > itk::SamplingSchemeQSpaceIMOCEstimationFilter< TSamplingType >::SampleType
Definition at line 62 of file itkSamplingSchemeQSpaceIMOCEstimationFilter.h.
template<class TSamplingType > typedef SamplingType::Pointer itk::SamplingSchemeQSpaceIMOCEstimationFilter< TSamplingType >::SamplingPointer
Definition at line 50 of file itkSamplingSchemeQSpaceIMOCEstimationFilter.h.
template<class TSamplingType > typedef TSamplingType itk::SamplingSchemeQSpaceIMOCEstimationFilter< TSamplingType >::SamplingType
Definition at line 49 of file itkSamplingSchemeQSpaceIMOCEstimationFilter.h.
template<class TSamplingType > typedef SamplingSchemeQSpaceIMOCEstimationFilter itk::SamplingSchemeQSpaceIMOCEstimationFilter< TSamplingType >::Self
Standard class typedefs.
Definition at line 44 of file itkSamplingSchemeQSpaceIMOCEstimationFilter.h.
template<class TSamplingType > typedef Superclass::STDVectorPointer itk::SamplingSchemeQSpaceIMOCEstimationFilter< TSamplingType >::STDVectorPointer
Definition at line 56 of file itkSamplingSchemeQSpaceIMOCEstimationFilter.h.
template<class TSamplingType > typedef Superclass::STDVectorType itk::SamplingSchemeQSpaceIMOCEstimationFilter< TSamplingType >::STDVectorType
Definition at line 55 of file itkSamplingSchemeQSpaceIMOCEstimationFilter.h.
template<class TSamplingType > typedef SamplingSchemeQSpaceEstimationFilter<TSamplingType> itk::SamplingSchemeQSpaceIMOCEstimationFilter< TSamplingType >::Superclass
Definition at line 45 of file itkSamplingSchemeQSpaceIMOCEstimationFilter.h.
template<class TSamplingType > typedef itk::Statistics::KdTreeGenerator< SampleType > itk::SamplingSchemeQSpaceIMOCEstimationFilter< TSamplingType >::TreeGeneratorType
Definition at line 63 of file itkSamplingSchemeQSpaceIMOCEstimationFilter.h.
template<class TSamplingType > typedef TreeGeneratorType::KdTreeType itk::SamplingSchemeQSpaceIMOCEstimationFilter< TSamplingType >::TreeType
Definition at line 64 of file itkSamplingSchemeQSpaceIMOCEstimationFilter.h.
template<class TSamplingType > typedef Superclass::ValueType itk::SamplingSchemeQSpaceIMOCEstimationFilter< TSamplingType >::ValueType
Definition at line 52 of file itkSamplingSchemeQSpaceIMOCEstimationFilter.h.
Constructor & Destructor Documentation
template<class TSamplingType > itk::SamplingSchemeQSpaceIMOCEstimationFilter< TSamplingType >::SamplingSchemeQSpaceIMOCEstimationFilter () protected
Definition at line 31 of file itkSamplingSchemeQSpaceIMOCEstimationFilter.hxx.
References itk::SamplingSchemeQSpaceIMOCEstimationFilter< TSamplingType >::Initialization().
template<class TSamplingType > itk::SamplingSchemeQSpaceIMOCEstimationFilter< TSamplingType >::~SamplingSchemeQSpaceIMOCEstimationFilter () inline protected
Definition at line 82 of file itkSamplingSchemeQSpaceIMOCEstimationFilter.h.
References ITK_OVERRIDE.
template<class TSamplingType > itk::SamplingSchemeQSpaceIMOCEstimationFilter< TSamplingType >::SamplingSchemeQSpaceIMOCEstimationFilter (const Self &) private
Member Function Documentation
template<class TSamplingType > virtual::itk::LightObject::Pointer itk::SamplingSchemeQSpaceIMOCEstimationFilter< TSamplingType >::CreateAnother (void) const
template<class TSamplingType > void itk::SamplingSchemeQSpaceIMOCEstimationFilter< TSamplingType >::GenerateData (void) virtual
Reimplemented from itk::SamplingSchemeQSpaceEstimationFilter< TSamplingType >.
Definition at line 554 of file itkSamplingSchemeQSpaceIMOCEstimationFilter.hxx.
References utlGlobalException.
Referenced by itk::SamplingSchemeQSpaceIMOCEstimationFilter< TSamplingType >::IsSatisfiedSeparationAngles().
template<class TSamplingType > virtual const char* itk::SamplingSchemeQSpaceIMOCEstimationFilter< TSamplingType >::GetNameOfClass () const virtual
Standard Macros
Reimplemented from itk::SamplingSchemeQSpaceEstimationFilter< TSamplingType >.
template<class TSamplingType > void itk::SamplingSchemeQSpaceIMOCEstimationFilter< TSamplingType >::Initialization () protected virtual
Reimplemented from itk::SamplingSchemeQSpaceEstimationFilter< TSamplingType >.
Definition at line 40 of file itkSamplingSchemeQSpaceIMOCEstimationFilter.hxx.
References CARTESIAN_TO_CARTESIAN, DIRECTION_NODUPLICATE, and itk::SamplingSchemeQSpaceIMOCEstimationFilter< TSamplingType >::IsSatisfiedSeparationAngles().
Referenced by itk::SamplingSchemeQSpaceIMOCEstimationFilter< TSamplingType >::SamplingSchemeQSpaceIMOCEstimationFilter().
template<class TSamplingType > bool itk::SamplingSchemeQSpaceIMOCEstimationFilter< TSamplingType >::IsSatisfiedSeparationAngles (const std::vector< double > & angles) protected
Definition at line 80 of file itkSamplingSchemeQSpaceIMOCEstimationFilter.hxx.
References utl::argmin(), itk::SamplingSchemeQSpaceIMOCEstimationFilter< TSamplingType >::GenerateData(), and utlException.
Referenced by itk::SamplingSchemeQSpaceIMOCEstimationFilter< TSamplingType >::Initialization().
template<class TSamplingType > itk::SamplingSchemeQSpaceIMOCEstimationFilter< TSamplingType >::itkSetGetMacro (TessellationOrder , unsigned int)
template<class TSamplingType > itk::SamplingSchemeQSpaceIMOCEstimationFilter< TSamplingType >::itkSetGetMacro (FineOrientations , MatrixPointer)
template<class TSamplingType > itk::SamplingSchemeQSpaceIMOCEstimationFilter< TSamplingType >::itkSetGetMacro (AngleMinChange , double)
template<class TSamplingType > itk::SamplingSchemeQSpaceIMOCEstimationFilter< TSamplingType >::itkSetGetMacro (ChooseMinimalCoverageShell , bool)
template<class TSamplingType > static Pointer itk::SamplingSchemeQSpaceIMOCEstimationFilter< TSamplingType >::New () static
template<class TSamplingType > void itk::SamplingSchemeQSpaceIMOCEstimationFilter< TSamplingType >::operator= (const Self &) private
Member Data Documentation
template<class TSamplingType > double itk::SamplingSchemeQSpaceIMOCEstimationFilter< TSamplingType >::m_AngleMinChange =0.0001 protected
Definition at line 101 of file itkSamplingSchemeQSpaceIMOCEstimationFilter.h.
template<class TSamplingType > bool itk::SamplingSchemeQSpaceIMOCEstimationFilter< TSamplingType >::m_ChooseMinimalCoverageShell =true protected
If true, always choose the shell with the minimal total coverage in each step. It is used only for multi-shell case where the number of samples are different in shells. It is better to always set it as true.
Definition at line 108 of file itkSamplingSchemeQSpaceIMOCEstimationFilter.h.
template<class TSamplingType > MatrixPointer itk::SamplingSchemeQSpaceIMOCEstimationFilter< TSamplingType >::m_FineOrientations protected
It is generated from m_TessellationOrder
Definition at line 92 of file itkSamplingSchemeQSpaceIMOCEstimationFilter.h.
template<class TSamplingType > SamplingPointer itk::SamplingSchemeQSpaceIMOCEstimationFilter< TSamplingType >::m_FineScheme = SamplingType::New() protected
Definition at line 93 of file itkSamplingSchemeQSpaceIMOCEstimationFilter.h.
template<class TSamplingType > TreeType::Pointer itk::SamplingSchemeQSpaceIMOCEstimationFilter< TSamplingType >::m_KDTree = nullptr protected
Definition at line 98 of file itkSamplingSchemeQSpaceIMOCEstimationFilter.h.
template<class TSamplingType > double itk::SamplingSchemeQSpaceIMOCEstimationFilter< TSamplingType >::m_MinDistanceInFineScheme =-1 protected
Definition at line 95 of file itkSamplingSchemeQSpaceIMOCEstimationFilter.h.
template<class TSamplingType > SampleType::Pointer itk::SamplingSchemeQSpaceIMOCEstimationFilter< TSamplingType >::m_Sample protected
Definition at line 99 of file itkSamplingSchemeQSpaceIMOCEstimationFilter.h.
template<class TSamplingType > unsigned int itk::SamplingSchemeQSpaceIMOCEstimationFilter< TSamplingType >::m_TessellationOrder =7 protected
the order of tessellation for the orignal fine mesh
Definition at line 89 of file itkSamplingSchemeQSpaceIMOCEstimationFilter.h.
template<class TSamplingType > TreeGeneratorType::Pointer itk::SamplingSchemeQSpaceIMOCEstimationFilter< TSamplingType >::m_TreeGenerator =nullptr protected
Definition at line 97 of file itkSamplingSchemeQSpaceIMOCEstimationFilter.h.
The documentation for this class was generated from the following files:
Modules/SamplingScheme/include/itkSamplingSchemeQSpaceIMOCEstimationFilter.h
Modules/SamplingScheme/include/itkSamplingSchemeQSpaceIMOCEstimationFilter.hxx