DMRITool: spams::SubMatrix< T > Class Template Reference
spams::SubMatrix< T > Class Template Reference
#include <linalg.h>
Detailed Description
template<typename T>
class spams::SubMatrix< T >
Definition at line 5163 of file linalg.h.
Public Member Functions
void add_rawCol (const int i, T *DtXi, const T a) const
void convertIndicesI (Vector< int > &ind) const
void convertIndicesJ (Vector< int > &ind) const
void copyCol (const int i, Vector< T > &DtXi) const
void diag (Vector< T > &diag) const
void extract_rawCol (const int i, T *pr) const
int m () const
int n () const
T operator() (const int index1, const int index2) const
SubMatrix (AbstractMatrix< T > &G, Vector< int > &indI, Vector< int > &indJ)
Public Member Functions inherited from spams::AbstractMatrix< T >
virtual ~AbstractMatrix ()
Private Attributes
Vector< int > _indicesI
Vector< int > _indicesJ
AbstractMatrix< T > * _matrix
Constructor & Destructor Documentation
template<typename T > spams::SubMatrix< T >::SubMatrix (AbstractMatrix< T > & G, Vector< int > & indI, Vector< int > & indJ)
Definition at line 5188 of file linalg.h.
Member Function Documentation
template<typename T > void spams::SubMatrix< T >::add_rawCol (const int i, T * DtXi, const T a) const inline virtual
compute DtX(:,i)
Implements spams::AbstractMatrix< T >.
Definition at line 5225 of file linalg.h.
template<typename T > void spams::SubMatrix< T >::convertIndicesI (Vector< int > & ind) const inline
Definition at line 5194 of file linalg.h.
References spams::Vector< T >::n(), and spams::Vector< T >::rawX().
template<typename T > void spams::SubMatrix< T >::convertIndicesJ (Vector< int > & ind) const inline
Definition at line 5203 of file linalg.h.
References spams::Vector< T >::n(), and spams::Vector< T >::rawX().
template<typename T > void spams::SubMatrix< T >::copyCol (const int i, Vector< T > & DtXi) const inline virtual
compute DtX(:,i)
Implements spams::AbstractMatrix< T >.
Definition at line 5220 of file linalg.h.
References spams::Vector< T >::rawX().
template<typename T > void spams::SubMatrix< T >::diag (Vector< T > & diag) const inline virtual
compute DtX(:,i)
Implements spams::AbstractMatrix< T >.
Definition at line 5234 of file linalg.h.
References spams::Vector< T >::rawX().
template<typename T > void spams::SubMatrix< T >::extract_rawCol (const int i, T * Xi) const inline virtual
copy X(:,i) into Xi
Implements spams::AbstractMatrix< T >.
Definition at line 5212 of file linalg.h.
template<typename T > int spams::SubMatrix< T >::m () const inline virtual
Implements spams::AbstractMatrix< T >.
Definition at line 5171 of file linalg.h.
template<typename T > int spams::SubMatrix< T >::n () const inline virtual
Implements spams::AbstractMatrix< T >.
Definition at line 5170 of file linalg.h.
template<typename T > T spams::SubMatrix< T >::operator() (const int index1, const int index2) const inline virtual
Implements spams::AbstractMatrix< T >.
Definition at line 5242 of file linalg.h.
Member Data Documentation
template<typename T > Vector<int> spams::SubMatrix< T >::_indicesI private
Definition at line 5182 of file linalg.h.
template<typename T > Vector<int> spams::SubMatrix< T >::_indicesJ private
Definition at line 5183 of file linalg.h.
template<typename T > AbstractMatrix<T>* spams::SubMatrix< T >::_matrix private
Definition at line 5184 of file linalg.h.
The documentation for this class was generated from the following file:
ThirdParty/Spams/include/linalg.h