DMRITool: spams::FISTA::MixedL1L2< T > Class Template Reference
spams::FISTA::MixedL1L2< T > Class Template Reference
#include <fista.h>
Detailed Description
template<typename T>
class spams::FISTA::MixedL1L2< T >
Definition at line 1786 of file fista.h.
Public Member Functions
T eval (const Matrix< T > &x) const
void fenchel (const Matrix< T > &input, T &val, T &scal) const
virtual bool is_subgrad () const
MixedL1L2 (const ParamReg< T > &param)
void prox (const Matrix< T > &x, Matrix< T > &y, const T lambda)
virtual void sub_grad (const Matrix< T > &input, Matrix< T > &output) const
virtual ~MixedL1L2 ()
Public Member Functions inherited from spams::FISTA::Regularizer< T, Matrix< T > >
virtual T eval_dual_norm (const Matrix< T > &x) const
virtual T eval_dual_norm_paths (const Matrix< T > &x, SpMatrix< T > &path) const
virtual T eval_paths (const Matrix< T > &x, SpMatrix< T > &paths_mat) const
virtual bool is_fenchel () const
virtual bool is_intercept () const
Regularizer ()
Regularizer (const ParamReg< T > &param)
virtual void reset ()
virtual ~Regularizer ()
Additional Inherited Members
Protected Attributes inherited from spams::FISTA::Regularizer< T, Matrix< T > >
bool _intercept
bool _pos
Constructor & Destructor Documentation
template<typename T > spams::FISTA::MixedL1L2< T >::MixedL1L2 (const ParamReg< T > & param) inline
Definition at line 1788 of file fista.h.
template<typename T > virtual spams::FISTA::MixedL1L2< T >::~MixedL1L2 () inline virtual
Definition at line 1789 of file fista.h.
Member Function Documentation
template<typename T > T spams::FISTA::MixedL1L2< T >::eval (const Matrix< T > & x) const inline virtual
Implements spams::FISTA::Regularizer< T, Matrix< T > >.
Definition at line 1811 of file fista.h.
References spams::Vector< T >::asum(), spams::Vector< T >::n(), and spams::Matrix< T >::norm_2_rows().
template<typename T > void spams::FISTA::MixedL1L2< T >::fenchel (const Matrix< T > & input, T & val, T & scal) const inline virtual
returns phi^star(input) and ouput=input if the fenchel is unconstrained returns 0 and scale input such that phi^star(output)=0 otherwise
Implements spams::FISTA::Regularizer< T, Matrix< T > >.
Definition at line 1828 of file fista.h.
References spams::Matrix< T >::copy(), EPSILON, spams::Vector< T >::fmaxval(), INFINITY, spams::Vector< T >::n(), spams::Matrix< T >::norm_2_rows(), and spams::Matrix< T >::thrsPos().
template<typename T > virtual bool spams::FISTA::MixedL1L2< T >::is_subgrad () const inline virtual
Reimplemented from spams::FISTA::Regularizer< T, Matrix< T > >.
Definition at line 1816 of file fista.h.
template<typename T > void spams::FISTA::MixedL1L2< T >::prox (const Matrix< T > & x, Matrix< T > & y, const T lambda) inline virtual
Implements spams::FISTA::Regularizer< T, Matrix< T > >.
Definition at line 1791 of file fista.h.
References spams::Matrix< T >::copy(), spams::FISTA::ParamFISTA< T >::lambda, spams::Matrix< T >::m(), spams::Matrix< T >::n(), spams::Matrix< T >::norm_2_rows(), spams::Matrix< T >::setZeros(), and spams::Matrix< T >::thrsPos().
template<typename T > virtual void spams::FISTA::MixedL1L2< T >::sub_grad (const Matrix< T > & input, Matrix< T > & output) const inline virtual
Reimplemented from spams::FISTA::Regularizer< T, Matrix< T > >.
Definition at line 1817 of file fista.h.
References spams::Matrix< T >::copy(), spams::Vector< T >::inv(), spams::Matrix< T >::multDiagLeft(), spams::Vector< T >::n(), and spams::Matrix< T >::norm_2_rows().
The documentation for this class was generated from the following file:
ThirdParty/Spams/include/fista.h