DMRITool: itk::DiscreteBasisMatrixGenerator< TElement > Class Template Reference
itk::DiscreteBasisMatrixGenerator< TElement > Class Template Reference
DiffusionModels
#include <itkDiscreteBasisMatrixGenerator.h>
Detailed Description
template<typename TElement = double>
class itk::DiscreteBasisMatrixGenerator< TElement >
Generate basis matrix.
Author
Jian Cheng (jian..nosp@m.chen.nosp@m.g.198.nosp@m.3@gm.nosp@m.ail.c.nosp@m.om)
Definition at line 36 of file itkDiscreteBasisMatrixGenerator.h.
Public Types
typedef SmartPointer< const Self > ConstPointer
typedef Superclass::MatrixPointer MatrixPointer
typedef Superclass::MatrixType MatrixType
typedef SmartPointer< Self > Pointer
typedef DiscreteBasisMatrixGenerator Self
typedef Superclass::STDVectorPointer STDVectorPointer
typedef Superclass::STDVectorType STDVectorType
typedef BasisMatrixGenerator< TElement > Superclass
typedef Superclass::VectorPointer VectorPointer
typedef Superclass::VectorType VectorType
Public Types inherited from itk::BasisMatrixGenerator< TElement >
typedef SmartPointer< const Self > ConstPointer
typedef utl_shared_ptr< MatrixType > MatrixPointer
typedef utl::NDArray< double, 2 > MatrixType
enum OutputType {
DWI =0,
EAP,
ODF
}
typedef SmartPointer< Self > Pointer
typedef SamplingSchemeQSpaceType::Pointer SamplingSchemeQSpacePointer
typedef SamplingSchemeQSpace< double > SamplingSchemeQSpaceType
typedef SamplingSchemeRSpaceType::Pointer SamplingSchemeRSpacePointer
typedef SamplingScheme3D< double > SamplingSchemeRSpaceType
typedef BasisMatrixGenerator Self
typedef utl_shared_ptr< STDVectorType > STDVectorPointer
typedef std::vector< double > STDVectorType
typedef Object Superclass
typedef utl_shared_ptr< VectorType > VectorPointer
typedef utl::NDArray< double, 1 > VectorType
Public Member Functions
virtual ::itk::LightObject::Pointer CreateAnother (void) const
void Flip (const int flipx, const int flipy, const int flipz) override
virtual MatrixPointer GetBasisOrientations ()
virtual const char * GetNameOfClass () const
int GetNumberOfBasis () const override
virtual bool GetUseIsotropicTerm ()
virtual void SetBasisOrientations (MatrixPointer _arg)
virtual void SetUseIsotropicTerm (bool _arg)
virtual void UseIsotropicTermOff ()
virtual void UseIsotropicTermOn ()
Public Member Functions inherited from itk::BasisMatrixGenerator< TElement >
virtual void ComputeBasisMatrix ()
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual MatrixPointer GetBasisMatrix () const
virtual double GetMD0 ()
virtual int GetNumberOfSamples () const
virtual int GetODFOrder ()
virtual OutputType GetOutputType ()
virtual MatrixPointer GetQBasisMatrixForDWI ()
virtual MatrixPointer GetRBasisMatrixForEAP ()
virtual MatrixPointer GetRBasisMatrixForODF ()
itkGetObjectMacro (SamplingSchemeQSpace, SamplingSchemeQSpaceType)
itkGetObjectMacro (SamplingSchemeRSpace, SamplingSchemeRSpaceType)
virtual void SetMD0 (double _arg)
virtual void SetODFOrder (int _arg)
virtual void SetOutputType (OutputType _arg)
virtual void SetSamplingSchemeQSpace (SamplingSchemeQSpaceType *_arg)
virtual void SetSamplingSchemeRSpace (SamplingSchemeRSpaceType *_arg)
Static Public Member Functions
static Pointer New ()
Static Public Member Functions inherited from itk::BasisMatrixGenerator< TElement >
static Pointer New ()
Protected Member Functions
DiscreteBasisMatrixGenerator ()
LightObject::Pointer InternalClone () const ITK_OVERRIDE
void PrintSelf (std::ostream &os, Indent indent) const ITK_OVERRIDE
virtual void VerifyInputParameters () const ITK_OVERRIDE
virtual ~DiscreteBasisMatrixGenerator ()
Protected Member Functions inherited from itk::BasisMatrixGenerator< TElement >
BasisMatrixGenerator ()
LightObject::Pointer InternalClone () const ITK_OVERRIDE
void PrintSelf (std::ostream &os, Indent indent) const ITK_OVERRIDE
virtual ~BasisMatrixGenerator ()
Protected Attributes
MatrixPointer m_BasisOrientations
bool m_UseIsotropicTerm
Protected Attributes inherited from itk::BasisMatrixGenerator< TElement >
double m_MD0
int m_ODFOrder
OutputType m_OutputType
MatrixPointer m_QBasisMatrixForDWI
MatrixPointer m_RBasisMatrixForEAP
MatrixPointer m_RBasisMatrixForODF
SamplingSchemeQSpacePointer m_SamplingSchemeQSpace
SamplingSchemeRSpacePointer m_SamplingSchemeRSpace
Private Member Functions
DiscreteBasisMatrixGenerator (const Self &)
void operator= (const Self &)
Member Typedef Documentation
template<typename TElement = double> typedef SmartPointer<const Self> itk::DiscreteBasisMatrixGenerator< TElement >::ConstPointer
Definition at line 44 of file itkDiscreteBasisMatrixGenerator.h.
template<typename TElement = double> typedef Superclass::MatrixPointer itk::DiscreteBasisMatrixGenerator< TElement >::MatrixPointer
Definition at line 55 of file itkDiscreteBasisMatrixGenerator.h.
template<typename TElement = double> typedef Superclass::MatrixType itk::DiscreteBasisMatrixGenerator< TElement >::MatrixType
Save the template parameters.
Definition at line 50 of file itkDiscreteBasisMatrixGenerator.h.
template<typename TElement = double> typedef SmartPointer<Self> itk::DiscreteBasisMatrixGenerator< TElement >::Pointer
Definition at line 43 of file itkDiscreteBasisMatrixGenerator.h.
template<typename TElement = double> typedef DiscreteBasisMatrixGenerator itk::DiscreteBasisMatrixGenerator< TElement >::Self
Standard class typedefs.
Definition at line 41 of file itkDiscreteBasisMatrixGenerator.h.
template<typename TElement = double> typedef Superclass::STDVectorPointer itk::DiscreteBasisMatrixGenerator< TElement >::STDVectorPointer
Definition at line 58 of file itkDiscreteBasisMatrixGenerator.h.
template<typename TElement = double> typedef Superclass::STDVectorType itk::DiscreteBasisMatrixGenerator< TElement >::STDVectorType
Definition at line 57 of file itkDiscreteBasisMatrixGenerator.h.
template<typename TElement = double> typedef BasisMatrixGenerator<TElement> itk::DiscreteBasisMatrixGenerator< TElement >::Superclass
Definition at line 42 of file itkDiscreteBasisMatrixGenerator.h.
template<typename TElement = double> typedef Superclass::VectorPointer itk::DiscreteBasisMatrixGenerator< TElement >::VectorPointer
Definition at line 56 of file itkDiscreteBasisMatrixGenerator.h.
template<typename TElement = double> typedef Superclass::VectorType itk::DiscreteBasisMatrixGenerator< TElement >::VectorType
Definition at line 54 of file itkDiscreteBasisMatrixGenerator.h.
Constructor & Destructor Documentation
template<typename TElement > itk::DiscreteBasisMatrixGenerator< TElement >::DiscreteBasisMatrixGenerator () protected
Definition at line 28 of file itkDiscreteBasisMatrixGenerator.hxx.
References itk::DiscreteBasisMatrixGenerator< TElement >::InternalClone().
template<typename TElement = double> virtual itk::DiscreteBasisMatrixGenerator< TElement >::~DiscreteBasisMatrixGenerator () inline protected virtual
Definition at line 87 of file itkDiscreteBasisMatrixGenerator.h.
References ITK_OVERRIDE.
template<typename TElement = double> itk::DiscreteBasisMatrixGenerator< TElement >::DiscreteBasisMatrixGenerator (const Self &) private
Member Function Documentation
template<typename TElement = double> virtual::itk::LightObject::Pointer itk::DiscreteBasisMatrixGenerator< TElement >::CreateAnother (void) const
template<typename TElement = double> void itk::DiscreteBasisMatrixGenerator< TElement >::Flip (const int flipx, const int flipy, const int flipz) inline override virtual
Reimplemented from itk::BasisMatrixGenerator< TElement >.
Definition at line 76 of file itkDiscreteBasisMatrixGenerator.h.
References utl::FlipOrientations().
template<typename TElement = double> virtual MatrixPointer itk::DiscreteBasisMatrixGenerator< TElement >::GetBasisOrientations () virtual
template<typename TElement = double> virtual const char* itk::DiscreteBasisMatrixGenerator< TElement >::GetNameOfClass () const virtual
Standard part of every itk Object.
Reimplemented from itk::BasisMatrixGenerator< TElement >.
Reimplemented in itk::TensorBasisMatrixGenerator< TElement >.
template<typename TElement = double> int itk::DiscreteBasisMatrixGenerator< TElement >::GetNumberOfBasis () const inline override virtual
Reimplemented from itk::BasisMatrixGenerator< TElement >.
Definition at line 63 of file itkDiscreteBasisMatrixGenerator.h.
template<typename TElement = double> virtual bool itk::DiscreteBasisMatrixGenerator< TElement >::GetUseIsotropicTerm () virtual
template<typename TElement > LightObject::Pointer itk::DiscreteBasisMatrixGenerator< TElement >::InternalClone () const protected
Definition at line 37 of file itkDiscreteBasisMatrixGenerator.hxx.
References itk::DiscreteBasisMatrixGenerator< TElement >::PrintSelf(), and utlShowPosition.
Referenced by itk::DiscreteBasisMatrixGenerator< TElement >::DiscreteBasisMatrixGenerator().
template<typename TElement = double> static Pointer itk::DiscreteBasisMatrixGenerator< TElement >::New () static
Method for creation through the object factory.
template<typename TElement = double> void itk::DiscreteBasisMatrixGenerator< TElement >::operator= (const Self &) private
template<typename TElement > void itk::DiscreteBasisMatrixGenerator< TElement >::PrintSelf (std::ostream & os, Indent indent) const protected
Definition at line 55 of file itkDiscreteBasisMatrixGenerator.hxx.
References utl::PrintUtlMatrix(), PrintVar1, and itk::DiscreteBasisMatrixGenerator< TElement >::VerifyInputParameters().
Referenced by itk::DiscreteBasisMatrixGenerator< TElement >::InternalClone().
template<typename TElement = double> virtual void itk::DiscreteBasisMatrixGenerator< TElement >::SetBasisOrientations (MatrixPointer _arg) virtual
template<typename TElement = double> virtual void itk::DiscreteBasisMatrixGenerator< TElement >::SetUseIsotropicTerm (bool _arg) virtual
Some parameters
template<typename TElement = double> virtual void itk::DiscreteBasisMatrixGenerator< TElement >::UseIsotropicTermOff () virtual
template<typename TElement = double> virtual void itk::DiscreteBasisMatrixGenerator< TElement >::UseIsotropicTermOn () virtual
template<typename TElement > void itk::DiscreteBasisMatrixGenerator< TElement >::VerifyInputParameters () const protected virtual
Reimplemented from itk::BasisMatrixGenerator< TElement >.
Reimplemented in itk::TensorBasisMatrixGenerator< TElement >.
Definition at line 66 of file itkDiscreteBasisMatrixGenerator.hxx.
References utlGlobalException.
Referenced by itk::DiscreteBasisMatrixGenerator< TElement >::PrintSelf().
Member Data Documentation
template<typename TElement = double> MatrixPointer itk::DiscreteBasisMatrixGenerator< TElement >::m_BasisOrientations protected
Definition at line 97 of file itkDiscreteBasisMatrixGenerator.h.
template<typename TElement = double> bool itk::DiscreteBasisMatrixGenerator< TElement >::m_UseIsotropicTerm protected
Definition at line 95 of file itkDiscreteBasisMatrixGenerator.h.
The documentation for this class was generated from the following files:
Modules/DiffusionModels/include/itkDiscreteBasisMatrixGenerator.h
Modules/DiffusionModels/include/itkDiscreteBasisMatrixGenerator.hxx