DMRITool: spams::FISTA::SqLossMissing< T > Class Template Reference
spams::FISTA::SqLossMissing< T > Class Template Reference
#include <fista.h>
Detailed Description
template<typename T>
class spams::FISTA::SqLossMissing< T >
Definition at line 293 of file fista.h.
Public Member Functions
T eval (const Vector< T > &alpha) const
virtual T fenchel (const Vector< T > &input) const
void grad (const Vector< T > &alpha, Vector< T > &grad) const
void init (const Vector< T > &x)
SqLossMissing (const AbstractMatrixB< T > &D)
virtual void var_fenchel (const Vector< T > &x, Vector< T > &grad1, Vector< T > &grad2, const bool intercept) const
virtual ~SqLossMissing ()
Public Member Functions inherited from spams::FISTA::Loss< T >
virtual bool is_fenchel () const
Loss ()
virtual bool test_backtracking (const Vector< T > &y, const Vector< T > &grad, const Vector< T > &prox, const T L) const
virtual ~Loss ()
Private Member Functions
SqLossMissing< T > & operator= (const SqLossMissing< T > &dict)
SqLossMissing (const SqLossMissing< T > &dict)
Private Attributes
const AbstractMatrixB< T > * _D
List< int > _missingvalues
Vector< T > _x
Constructor & Destructor Documentation
template<typename T> spams::FISTA::SqLossMissing< T >::SqLossMissing (const AbstractMatrixB< T > & D) inline
Definition at line 295 of file fista.h.
template<typename T> virtual spams::FISTA::SqLossMissing< T >::~SqLossMissing () inline virtual
Definition at line 296 of file fista.h.
template<typename T> spams::FISTA::SqLossMissing< T >::SqLossMissing (const SqLossMissing< T > & dict) explicit private
Member Function Documentation
template<typename T> T spams::FISTA::SqLossMissing< T >::eval (const Vector< T > & alpha) const inline virtual
Implements spams::FISTA::Loss< T >.
Definition at line 309 of file fista.h.
References spams::Vector< T >::copy(), spams::Vector< T >::n(), spams::Vector< T >::nrm2sq(), and spams::Vector< T >::toSparse().
template<typename T> virtual T spams::FISTA::SqLossMissing< T >::fenchel (const Vector< T > & input) const inline virtual
Implements spams::FISTA::Loss< T >.
Definition at line 332 of file fista.h.
References spams::Vector< T >::dot(), and spams::Vector< T >::nrm2sq().
template<typename T> void spams::FISTA::SqLossMissing< T >::grad (const Vector< T > & alpha, Vector< T > & grad) const inline virtual
Implements spams::FISTA::Loss< T >.
Definition at line 321 of file fista.h.
References spams::Vector< T >::copy(), spams::Vector< T >::n(), and spams::Vector< T >::toSparse().
template<typename T> void spams::FISTA::SqLossMissing< T >::init (const Vector< T > & x) inline virtual
Implements spams::FISTA::Loss< T >.
Definition at line 298 of file fista.h.
template<typename T> SqLossMissing<T>& spams::FISTA::SqLossMissing< T >::operator= (const SqLossMissing< T > & dict) private
template<typename T> virtual void spams::FISTA::SqLossMissing< T >::var_fenchel (const Vector< T > & x, Vector< T > & grad1, Vector< T > & grad2, const bool intercept) const inline virtual
Implements spams::FISTA::Loss< T >.
Definition at line 335 of file fista.h.
References spams::Vector< T >::copy(), spams::Vector< T >::n(), spams::Vector< T >::toSparse(), and spams::Vector< T >::whiten().
Member Data Documentation
template<typename T> const AbstractMatrixB<T>* spams::FISTA::SqLossMissing< T >::_D private
Definition at line 353 of file fista.h.
template<typename T> List<int> spams::FISTA::SqLossMissing< T >::_missingvalues private
Definition at line 355 of file fista.h.
template<typename T> Vector<T> spams::FISTA::SqLossMissing< T >::_x private
Definition at line 354 of file fista.h.
The documentation for this class was generated from the following file:
ThirdParty/Spams/include/fista.h