DMRITool: spams::List< T > Class Template Reference
spams::List< T > Class Template Reference
#include <list.h>
Detailed Description
template<typename T>
class spams::List< T >
Definition at line 50 of file list.h.
Public Member Functions
ListIterator< T > & begin () const
void clear ()
bool empty () const
void * end () const
T front () const
void fusion (const List< T > &list)
List ()
void pop_front ()
void print () const
void push_back (T elem)
void push_front (T elem)
void remove (T elem)
void reverse (List< T > &list)
int size () const
~List ()
Private Attributes
Element< T > * _first
ListIterator< T > * _iterator
Element< T > * _last
int _size
Constructor & Destructor Documentation
template<typename T> spams::List< T >::List () inline
Definition at line 53 of file list.h.
template<typename T> spams::List< T >::~List () inline
Definition at line 54 of file list.h.
Member Function Documentation
template<typename T> ListIterator<T>& spams::List< T >::begin () const inline
Definition at line 117 of file list.h.
Referenced by spams::MaxFlow< T >::component_relabelling(), spams::MaxFlow< T >::deactivate(), spams::Tree_Seq< T >::dual_norm_inf(), spams::Graph< T >::dual_norm_inf(), spams::FISTA::GroupProx< T, Reg >::eval(), spams::GraphPath< T, Int >::eval_dual_norm(), spams::FISTA::GroupProx< T, Reg >::fenchel(), spams::MaxFlow< T >::flow_component(), spams::List< int >::fusion(), spams::MaxFlow< T >::gap_relabelling(), spams::MaxFlow< T >::print_component(), spams::MaxFlow< T >::print_component2(), spams::MaxFlow< T >::project(), spams::MaxFlow< T >::project_box(), spams::MaxFlow< T >::project_weighted(), spams::FISTA::GroupProx< T, Reg >::prox(), spams::remove_cycles(), spams::MaxFlow< T >::reset_component(), spams::MaxFlow< T >::restore_capacities(), spams::MaxFlow< T >::set_capacities_groups(), spams::MaxFlow< T >::splitComponent(), spams::MinCostFlow< Int >::st_flow_decomposition_dag(), spams::MaxFlow< T >::sub_gradient_aux(), and spams::MaxFlow< T >::update_capacities().
template<typename T> void spams::List< T >::clear () inline
Definition at line 87 of file list.h.
Referenced by spams::MinCostFlow< Int >::cost_shortest_path_in_dag(), spams::GraphPath< T, Int >::eval_dual_norm(), spams::remove_cycles(), and spams::List< int >::reverse().
template<typename T> bool spams::List< T >::empty () const inline
Definition at line 58 of file list.h.
Referenced by spams::MaxFlow< T >::check_flow(), spams::MaxFlow< T >::component_relabelling(), spams::count_cc_graph(), spams::count_paths_dags(), spams::MaxFlow< T >::extractConnexComponents(), spams::MaxFlow< T >::global_relabelling(), spams::MaxFlow< T >::norm(), spams::MaxFlow< T >::project_box(), spams::remove_cycles(), spams::MaxFlow< T >::splitComponent(), spams::MaxFlow< T >::sub_gradient(), spams::MinCostFlow< Int >::topological_sort(), and spams::MaxFlow< T >::update_capacities().
template<typename T> void* spams::List< T >::end () const inline
Definition at line 118 of file list.h.
Referenced by spams::MaxFlow< T >::component_relabelling(), spams::count_cc_graph(), spams::MaxFlow< T >::deactivate(), spams::Tree_Seq< T >::dual_norm_inf(), spams::Graph< T >::dual_norm_inf(), spams::FISTA::GroupProx< T, Reg >::eval(), spams::GraphPath< T, Int >::eval_dual_norm(), spams::FISTA::GroupProx< T, Reg >::fenchel(), spams::MaxFlow< T >::flow_component(), spams::List< int >::fusion(), spams::MaxFlow< T >::gap_relabelling(), spams::MaxFlow< T >::init_split_variables(), spams::MaxFlow< T >::init_split_variables_aux(), spams::MaxFlow< T >::print_component(), spams::MaxFlow< T >::print_component2(), spams::MaxFlow< T >::project(), spams::MaxFlow< T >::project_box(), spams::MaxFlow< T >::project_weighted(), spams::FISTA::GroupProx< T, Reg >::prox(), spams::remove_cycles(), spams::MaxFlow< T >::reset_component(), spams::MaxFlow< T >::restore_capacities(), spams::MaxFlow< T >::set_capacities_groups(), spams::MaxFlow< T >::splitComponent(), spams::MinCostFlow< Int >::st_flow_decomposition_dag(), spams::MaxFlow< T >::sub_gradient_aux(), and spams::MaxFlow< T >::update_capacities().
template<typename T> T spams::List< T >::front () const inline
Definition at line 59 of file list.h.
Referenced by spams::MaxFlow< T >::check_flow(), spams::MaxFlow< T >::component_relabelling(), spams::count_cc_graph(), spams::count_paths_dags(), spams::Tree_Seq< T >::dual_norm_inf(), spams::MaxFlow< T >::extractConnexComponents(), spams::MaxFlow< T >::global_relabelling(), spams::MaxFlow< T >::norm(), spams::MaxFlow< T >::project_box(), spams::remove_cycles(), spams::MaxFlow< T >::splitComponent(), spams::MaxFlow< T >::sub_gradient(), spams::MinCostFlow< Int >::topological_sort(), and spams::MaxFlow< T >::update_capacities().
template<typename T> void spams::List< T >::fusion (const List< T > & list) inline
Definition at line 119 of file list.h.
Referenced by spams::count_cc_graph(), spams::GraphPath< T, Int >::eval_dual_norm(), and spams::MaxFlow< T >::sub_gradient_aux().
template<typename T> void spams::List< T >::pop_front () inline
Definition at line 62 of file list.h.
Referenced by spams::MaxFlow< T >::check_flow(), spams::MaxFlow< T >::component_relabelling(), spams::count_cc_graph(), spams::count_paths_dags(), spams::MaxFlow< T >::extractConnexComponents(), spams::MaxFlow< T >::global_relabelling(), spams::MaxFlow< T >::norm(), spams::MaxFlow< T >::project_box(), spams::remove_cycles(), spams::MaxFlow< T >::splitComponent(), spams::MaxFlow< T >::sub_gradient(), spams::MinCostFlow< Int >::topological_sort(), and spams::MaxFlow< T >::update_capacities().
template<typename T> void spams::List< T >::print () const inline
Definition at line 130 of file list.h.
template<typename T> void spams::List< T >::push_back (T elem) inline
Definition at line 69 of file list.h.
Referenced by spams::MaxFlow< T >::check_flow(), spams::MaxFlow< T >::component_relabelling(), spams::count_cc_graph(), spams::count_paths_dags(), spams::MaxFlow< T >::extractConnexComponents(), spams::GraphPath< T, Int >::flow_decomposition(), spams::MaxFlow< T >::global_relabelling(), spams::FISTA::GroupProx< T, Reg >::GroupProx(), spams::MaxFlow< T >::init_split_variables_aux(), spams::MaxFlow< T >::norm(), spams::MaxFlow< T >::project_box(), spams::remove_cycles(), spams::MaxFlow< T >::splitComponent(), spams::MinCostFlow< Int >::st_flow_decomposition_dag(), spams::MaxFlow< T >::sub_gradient(), spams::MaxFlow< T >::sub_gradient_aux(), spams::MinCostFlow< Int >::topological_sort(), and spams::MaxFlow< T >::update_capacities().
template<typename T> void spams::List< T >::push_front (T elem) inline
Definition at line 80 of file list.h.
Referenced by spams::MinCostFlow< Int >::cost_shortest_path_in_dag(), spams::count_paths_dags(), spams::Tree_Seq< T >::dual_norm_inf(), spams::MaxFlow< T >::norm(), spams::MaxFlow< T >::project_box(), spams::remove_cycles(), spams::List< int >::reverse(), and spams::MaxFlow< T >::update_capacities().
template<typename T> void spams::List< T >::remove (T elem) inline
Definition at line 98 of file list.h.
template<typename T> void spams::List< T >::reverse (List< T > & list) inline
Definition at line 124 of file list.h.
Referenced by spams::remove_cycles().
template<typename T> int spams::List< T >::size () const inline
Definition at line 116 of file list.h.
Referenced by spams::MaxFlow< T >::component_relabelling(), spams::Graph< T >::dual_norm_inf(), spams::FISTA::GroupProx< T, Reg >::eval(), spams::FISTA::GroupProx< T, Reg >::fenchel(), spams::MaxFlow< T >::init_split_variables(), spams::MaxFlow< T >::perform_maxflow_component(), spams::MaxFlow< T >::project_weighted(), spams::FISTA::GroupProx< T, Reg >::prox(), spams::Graph< T >::proximal_operator(), and spams::MaxFlow< T >::sub_gradient_aux().
Member Data Documentation
template<typename T> Element<T>* spams::List< T >::_first private
Definition at line 141 of file list.h.
template<typename T> ListIterator<T>* spams::List< T >::_iterator private
Definition at line 140 of file list.h.
template<typename T> Element<T>* spams::List< T >::_last private
Definition at line 142 of file list.h.
template<typename T> int spams::List< T >::_size private
Definition at line 143 of file list.h.
The documentation for this class was generated from the following file:
ThirdParty/Spams/include/list.h