DMRITool: itk::DWIGeneratorBase< TOutputImage, TScalarImage > Class Template Reference
itk::DWIGeneratorBase< TOutputImage, TScalarImage > Class Template Reference abstract
DWIProcessing
#include <itkDWIGeneratorBase.h>
Detailed Description
template<class TOutputImage, class TScalarImage = Image<double,3>>
class itk::DWIGeneratorBase< TOutputImage, TScalarImage >
Generate DWI data based on provided parameter file.
Author
Jian Cheng (jian..nosp@m.chen.nosp@m.g.198.nosp@m.3@gm.nosp@m.ail.c.nosp@m.om)
Definition at line 40 of file itkDWIGeneratorBase.h.
Public Types
typedef CylinderModelType::Pointer CylinderModelPointer
typedef CylinderModelGenerator< double > CylinderModelType
typedef std::vector< DiffusionParameterValuesType > DiffusionParameterContainerType
typedef std::vector< double > DiffusionParameterValuesType
typedef utl_shared_ptr< MatrixType > MatrixPointer
typedef utl::NDArray< PrecisionType, 2 > MatrixType
enum ModelType {
SYMMETRICAL_TENSOR_IN_CARTESIAN_COORDS =0,
SYMMETRICAL_TENSOR_IN_SPHERICAL_COORDS,
TENSOR_IN_EULER_ANGLES,
CYLINDER_SPHERICAL_MODEL
}
typedef OutputImageType::DirectionType OutputImageDirectionType
typedef OutputImageType::IndexType OutputImageIndexType
typedef OutputImageType::InternalPixelType OutputImageInternalPixelType
typedef OutputImageType::PixelType OutputImagePixelType
typedef OutputImageType::Pointer OutputImagePointer
typedef OutputImageType::PointType OutputImagePointType
typedef OutputImageType::RegionType OutputImageRegionType
typedef OutputImageType::SizeType OutputImageSizeType
typedef OutputImageType::SpacingType OutputImageSpacingType
typedef TOutputImage OutputImageType
typedef SmartPointer< Self > Pointer
typedef double PrecisionType
typedef SamplingSchemeQSpaceType::Pointer SamplingSchemeQSpacePointer
typedef SamplingSchemeQSpace< double > SamplingSchemeQSpaceType
typedef SamplingSchemeRSpaceType::Pointer SamplingSchemeRSpacePointer
typedef SamplingScheme3D< double > SamplingSchemeRSpaceType
typedef ScalarImageType::Pointer ScalarImagePointer
typedef TScalarImage ScalarImageType
typedef DWIGeneratorBase Self
typedef utl_shared_ptr< STDVectorType > STDVectorPointer
typedef std::vector< PrecisionType > STDVectorType
typedef ImageSource< TOutputImage > Superclass
typedef utl::NDArray< PrecisionType, 1 > VectorType
Public Member Functions
ScalarImageType * GetB0Image ()
virtual double GetB0Scale ()
OutputImageType * GetDWIImage ()
OutputImageType * GetEAPImage ()
virtual int GetMaxNumberOfPeaks ()
virtual ModelType GetModelType () const
ScalarImageType * GetMSDImage ()
virtual const char * GetNameOfClass () const
virtual double GetNoiseSigma ()
unsigned int GetNumberOfQSpaceSamples () const
unsigned int GetNumberOfRSpaceSamples () const
OutputImageType * GetODFImage ()
virtual unsigned int GetODFOrder ()
virtual OutputImageSizeType GetOutputSize ()
OutputImageType * GetPeakImage ()
virtual PeakType GetPeakType ()
ScalarImageType * GetRTOImage ()
virtual double GetSNR ()
itkGetObjectMacro (SamplingSchemeQSpace, SamplingSchemeQSpaceType)
itkGetObjectMacro (SamplingSchemeRSpace, SamplingSchemeRSpaceType)
itkGetObjectMacro (CylinderModel, CylinderModelType)
itkSetGetBooleanMacro (IsOutputDWI)
itkSetGetBooleanMacro (IsOutputEAP)
itkSetGetBooleanMacro (IsOutputODF)
itkSetGetBooleanMacro (IsOutputRTO)
itkSetGetBooleanMacro (IsOutputMSD)
virtual void SetB0Scale (double _arg)
virtual void SetCylinderModel (CylinderModelType *_arg)
virtual void SetMaxNumberOfPeaks (int _arg)
virtual void SetModelType (const ModelType _arg)
virtual void SetNoiseSigma (double _arg)
virtual void SetODFOrder (unsigned int _arg)
virtual void SetOutputSize (OutputImageSizeType _arg)
virtual void SetPeakType (PeakType _arg)
virtual void SetSamplingSchemeQSpace (SamplingSchemeQSpaceType *_arg)
virtual void SetSamplingSchemeRSpace (SamplingSchemeRSpaceType *_arg)
virtual void SetSNR (double _arg)
Static Public Attributes
static const unsigned int OutputImageDimension = OutputImageType::ImageDimension
Protected Member Functions
virtual void AllocateOutputs () ITK_OVERRIDE
DWIGeneratorBase ()
void GenerateData () ITK_OVERRIDE=0
virtual void Initialization ()
LightObject::Pointer InternalClone () const ITK_OVERRIDE
void PrintSelf (std::ostream &os, Indent indent) const ITK_OVERRIDE
~DWIGeneratorBase ()
Protected Attributes
double m_B0Scale
CylinderModelPointer m_CylinderModel
bool m_IsOutputDWI
bool m_IsOutputEAP
bool m_IsOutputMSD
bool m_IsOutputODF
bool m_IsOutputRTO
int m_MaxNumberOfPeaks
ModelType m_ModelType
double m_NoiseSigma
unsigned int m_ODFOrder
OutputImageDirectionType m_OutputDirection
OutputImagePointType m_OutputOrigin
OutputImageSizeType m_OutputSize
OutputImageSpacingType m_OutputSpacing
PeakType m_PeakType
SamplingSchemeQSpacePointer m_SamplingSchemeQSpace
SamplingSchemeRSpacePointer m_SamplingSchemeRSpace
double m_SNR
Private Member Functions
DWIGeneratorBase (const Self &)
void operator= (const Self &)
Member Typedef Documentation
template<class TOutputImage , class TScalarImage = Image<double,3>> typedef CylinderModelType::Pointer itk::DWIGeneratorBase< TOutputImage, TScalarImage >::CylinderModelPointer
Definition at line 87 of file itkDWIGeneratorBase.h.
template<class TOutputImage , class TScalarImage = Image<double,3>> typedef CylinderModelGenerator<double> itk::DWIGeneratorBase< TOutputImage, TScalarImage >::CylinderModelType
Definition at line 86 of file itkDWIGeneratorBase.h.
template<class TOutputImage , class TScalarImage = Image<double,3>> typedef std::vector<DiffusionParameterValuesType> itk::DWIGeneratorBase< TOutputImage, TScalarImage >::DiffusionParameterContainerType
Definition at line 84 of file itkDWIGeneratorBase.h.
template<class TOutputImage , class TScalarImage = Image<double,3>> typedef std::vector<double> itk::DWIGeneratorBase< TOutputImage, TScalarImage >::DiffusionParameterValuesType
Some convenient typedefs for diffusion parameters.
Definition at line 83 of file itkDWIGeneratorBase.h.
template<class TOutputImage , class TScalarImage = Image<double,3>> typedef utl_shared_ptr<MatrixType > itk::DWIGeneratorBase< TOutputImage, TScalarImage >::MatrixPointer
Definition at line 78 of file itkDWIGeneratorBase.h.
template<class TOutputImage , class TScalarImage = Image<double,3>> typedef utl::NDArray<PrecisionType,2> itk::DWIGeneratorBase< TOutputImage, TScalarImage >::MatrixType
Definition at line 76 of file itkDWIGeneratorBase.h.
template<class TOutputImage , class TScalarImage = Image<double,3>> typedef OutputImageType::DirectionType itk::DWIGeneratorBase< TOutputImage, TScalarImage >::OutputImageDirectionType
Definition at line 61 of file itkDWIGeneratorBase.h.
template<class TOutputImage , class TScalarImage = Image<double,3>> typedef OutputImageType::IndexType itk::DWIGeneratorBase< TOutputImage, TScalarImage >::OutputImageIndexType
Definition at line 59 of file itkDWIGeneratorBase.h.
template<class TOutputImage , class TScalarImage = Image<double,3>> typedef OutputImageType::InternalPixelType itk::DWIGeneratorBase< TOutputImage, TScalarImage >::OutputImageInternalPixelType
Definition at line 64 of file itkDWIGeneratorBase.h.
template<class TOutputImage , class TScalarImage = Image<double,3>> typedef OutputImageType::PixelType itk::DWIGeneratorBase< TOutputImage, TScalarImage >::OutputImagePixelType
Definition at line 63 of file itkDWIGeneratorBase.h.
template<class TOutputImage , class TScalarImage = Image<double,3>> typedef OutputImageType::Pointer itk::DWIGeneratorBase< TOutputImage, TScalarImage >::OutputImagePointer
Definition at line 56 of file itkDWIGeneratorBase.h.
template<class TOutputImage , class TScalarImage = Image<double,3>> typedef OutputImageType::PointType itk::DWIGeneratorBase< TOutputImage, TScalarImage >::OutputImagePointType
Definition at line 60 of file itkDWIGeneratorBase.h.
template<class TOutputImage , class TScalarImage = Image<double,3>> typedef OutputImageType::RegionType itk::DWIGeneratorBase< TOutputImage, TScalarImage >::OutputImageRegionType
Definition at line 62 of file itkDWIGeneratorBase.h.
template<class TOutputImage , class TScalarImage = Image<double,3>> typedef OutputImageType::SizeType itk::DWIGeneratorBase< TOutputImage, TScalarImage >::OutputImageSizeType
Definition at line 57 of file itkDWIGeneratorBase.h.
template<class TOutputImage , class TScalarImage = Image<double,3>> typedef OutputImageType::SpacingType itk::DWIGeneratorBase< TOutputImage, TScalarImage >::OutputImageSpacingType
Definition at line 58 of file itkDWIGeneratorBase.h.
template<class TOutputImage , class TScalarImage = Image<double,3>> typedef TOutputImage itk::DWIGeneratorBase< TOutputImage, TScalarImage >::OutputImageType
Some convenient typedefs.
Definition at line 52 of file itkDWIGeneratorBase.h.
template<class TOutputImage , class TScalarImage = Image<double,3>> typedef SmartPointer<Self> itk::DWIGeneratorBase< TOutputImage, TScalarImage >::Pointer
Definition at line 46 of file itkDWIGeneratorBase.h.
template<class TOutputImage , class TScalarImage = Image<double,3>> typedef double itk::DWIGeneratorBase< TOutputImage, TScalarImage >::PrecisionType
Orientation Matrice Type
Definition at line 75 of file itkDWIGeneratorBase.h.
template<class TOutputImage , class TScalarImage = Image<double,3>> typedef SamplingSchemeQSpaceType::Pointer itk::DWIGeneratorBase< TOutputImage, TScalarImage >::SamplingSchemeQSpacePointer
Definition at line 90 of file itkDWIGeneratorBase.h.
template<class TOutputImage , class TScalarImage = Image<double,3>> typedef SamplingSchemeQSpace<double> itk::DWIGeneratorBase< TOutputImage, TScalarImage >::SamplingSchemeQSpaceType
Definition at line 89 of file itkDWIGeneratorBase.h.
template<class TOutputImage , class TScalarImage = Image<double,3>> typedef SamplingSchemeRSpaceType::Pointer itk::DWIGeneratorBase< TOutputImage, TScalarImage >::SamplingSchemeRSpacePointer
Definition at line 93 of file itkDWIGeneratorBase.h.
template<class TOutputImage , class TScalarImage = Image<double,3>> typedef SamplingScheme3D<double> itk::DWIGeneratorBase< TOutputImage, TScalarImage >::SamplingSchemeRSpaceType
Definition at line 92 of file itkDWIGeneratorBase.h.
template<class TOutputImage , class TScalarImage = Image<double,3>> typedef ScalarImageType::Pointer itk::DWIGeneratorBase< TOutputImage, TScalarImage >::ScalarImagePointer
Definition at line 72 of file itkDWIGeneratorBase.h.
template<class TOutputImage , class TScalarImage = Image<double,3>> typedef TScalarImage itk::DWIGeneratorBase< TOutputImage, TScalarImage >::ScalarImageType
B0 Image
Definition at line 71 of file itkDWIGeneratorBase.h.
template<class TOutputImage , class TScalarImage = Image<double,3>> typedef DWIGeneratorBase itk::DWIGeneratorBase< TOutputImage, TScalarImage >::Self
Standard class typedefs.
Definition at line 44 of file itkDWIGeneratorBase.h.
template<class TOutputImage , class TScalarImage = Image<double,3>> typedef utl_shared_ptr<STDVectorType> itk::DWIGeneratorBase< TOutputImage, TScalarImage >::STDVectorPointer
Definition at line 80 of file itkDWIGeneratorBase.h.
template<class TOutputImage , class TScalarImage = Image<double,3>> typedef std::vector<PrecisionType> itk::DWIGeneratorBase< TOutputImage, TScalarImage >::STDVectorType
Definition at line 79 of file itkDWIGeneratorBase.h.
template<class TOutputImage , class TScalarImage = Image<double,3>> typedef ImageSource<TOutputImage> itk::DWIGeneratorBase< TOutputImage, TScalarImage >::Superclass
Definition at line 45 of file itkDWIGeneratorBase.h.
template<class TOutputImage , class TScalarImage = Image<double,3>> typedef utl::NDArray<PrecisionType,1> itk::DWIGeneratorBase< TOutputImage, TScalarImage >::VectorType
Definition at line 77 of file itkDWIGeneratorBase.h.
Member Enumeration Documentation
template<class TOutputImage , class TScalarImage = Image<double,3>> enum itk::DWIGeneratorBase::ModelType
Parameters
TENSOR_SYM_CARTESIAN symmetric tensor with the principal direction (x,y,z) in Cartesian coordinates
TENSOR_SYM_SPHERICAL symmetric tensor with the principal direction (theta,phi) in spherical coordinates
TENSOR general tensor with three Eular angles
CYLINDER_SPHERICAL cylinder spherical model with two spherical angles (theta,phi)
Enumerator
SYMMETRICAL_TENSOR_IN_CARTESIAN_COORDS
SYMMETRICAL_TENSOR_IN_SPHERICAL_COORDS
TENSOR_IN_EULER_ANGLES
CYLINDER_SPHERICAL_MODEL
Definition at line 100 of file itkDWIGeneratorBase.h.
Constructor & Destructor Documentation
template<class TOutputImage , class TScalarImage > itk::DWIGeneratorBase< TOutputImage, TScalarImage >::DWIGeneratorBase () protected
Definition at line 30 of file itkDWIGeneratorBase.hxx.
References itk::NXYZ, and itk::DWIGeneratorBase< TOutputImage, TScalarImage >::~DWIGeneratorBase().
template<class TOutputImage , class TScalarImage > itk::DWIGeneratorBase< TOutputImage, TScalarImage >::~DWIGeneratorBase () protected
Definition at line 71 of file itkDWIGeneratorBase.hxx.
References itk::DWIGeneratorBase< TOutputImage, TScalarImage >::InternalClone().
Referenced by itk::DWIGeneratorBase< TOutputImage, TScalarImage >::DWIGeneratorBase().
template<class TOutputImage , class TScalarImage = Image<double,3>> itk::DWIGeneratorBase< TOutputImage, TScalarImage >::DWIGeneratorBase (const Self &) private
Member Function Documentation
template<class TOutputImage , class TScalarImage > void itk::DWIGeneratorBase< TOutputImage, TScalarImage >::AllocateOutputs () protected virtual
allocate all outputs
Definition at line 145 of file itkDWIGeneratorBase.hxx.
References itk::PeakContainerHelper::GetDimension(), itk::DWIGeneratorBase< TOutputImage, TScalarImage >::PrintSelf(), and utlShowPosition.
Referenced by itk::DWIGeneratorBase< TOutputImage, TScalarImage >::Initialization().
template<class TOutputImage , class TScalarImage = Image<double,3>> void itk::DWIGeneratorBase< TOutputImage, TScalarImage >::GenerateData () protected pure virtual
Implemented in itk::DWISingleVoxelGenerator< TOutputImage, TScalarImage >, and itk::DWIGenerator< TOutputImage, TScalarImage >.
template<class TOutputImage , class TScalarImage = Image<double,3>> ScalarImageType* itk::DWIGeneratorBase< TOutputImage, TScalarImage >::GetB0Image () inline
Get B0Image
Definition at line 159 of file itkDWIGeneratorBase.h.
template<class TOutputImage , class TScalarImage = Image<double,3>> virtual double itk::DWIGeneratorBase< TOutputImage, TScalarImage >::GetB0Scale () virtual
template<class TOutputImage , class TScalarImage = Image<double,3>> OutputImageType* itk::DWIGeneratorBase< TOutputImage, TScalarImage >::GetDWIImage () inline
Definition at line 164 of file itkDWIGeneratorBase.h.
template<class TOutputImage , class TScalarImage = Image<double,3>> OutputImageType* itk::DWIGeneratorBase< TOutputImage, TScalarImage >::GetEAPImage () inline
Definition at line 174 of file itkDWIGeneratorBase.h.
template<class TOutputImage , class TScalarImage = Image<double,3>> virtual int itk::DWIGeneratorBase< TOutputImage, TScalarImage >::GetMaxNumberOfPeaks () virtual
template<class TOutputImage , class TScalarImage = Image<double,3>> virtual ModelType itk::DWIGeneratorBase< TOutputImage, TScalarImage >::GetModelType () const virtual
template<class TOutputImage , class TScalarImage = Image<double,3>> ScalarImageType* itk::DWIGeneratorBase< TOutputImage, TScalarImage >::GetMSDImage () inline
Definition at line 188 of file itkDWIGeneratorBase.h.
References ITK_OVERRIDE.
template<class TOutputImage , class TScalarImage = Image<double,3>> virtual const char* itk::DWIGeneratorBase< TOutputImage, TScalarImage >::GetNameOfClass () const virtual
Run-time type information (and related methods).
Reimplemented in itk::DWISingleVoxelGenerator< TOutputImage, TScalarImage >, and itk::DWIGenerator< TOutputImage, TScalarImage >.
template<class TOutputImage , class TScalarImage = Image<double,3>> virtual double itk::DWIGeneratorBase< TOutputImage, TScalarImage >::GetNoiseSigma () virtual
template<class TOutputImage , class TScalarImage = Image<double,3>> unsigned int itk::DWIGeneratorBase< TOutputImage, TScalarImage >::GetNumberOfQSpaceSamples () const inline
Definition at line 131 of file itkDWIGeneratorBase.h.
template<class TOutputImage , class TScalarImage = Image<double,3>> unsigned int itk::DWIGeneratorBase< TOutputImage, TScalarImage >::GetNumberOfRSpaceSamples () const inline
Definition at line 136 of file itkDWIGeneratorBase.h.
References itkSetGetBooleanMacro.
template<class TOutputImage , class TScalarImage = Image<double,3>> OutputImageType* itk::DWIGeneratorBase< TOutputImage, TScalarImage >::GetODFImage () inline
Definition at line 169 of file itkDWIGeneratorBase.h.
template<class TOutputImage , class TScalarImage = Image<double,3>> virtual unsigned int itk::DWIGeneratorBase< TOutputImage, TScalarImage >::GetODFOrder () virtual
template<class TOutputImage , class TScalarImage = Image<double,3>> virtual OutputImageSizeType itk::DWIGeneratorBase< TOutputImage, TScalarImage >::GetOutputSize () virtual
template<class TOutputImage , class TScalarImage = Image<double,3>> OutputImageType* itk::DWIGeneratorBase< TOutputImage, TScalarImage >::GetPeakImage () inline
Definition at line 179 of file itkDWIGeneratorBase.h.
template<class TOutputImage , class TScalarImage = Image<double,3>> virtual PeakType itk::DWIGeneratorBase< TOutputImage, TScalarImage >::GetPeakType () virtual
template<class TOutputImage , class TScalarImage = Image<double,3>> ScalarImageType* itk::DWIGeneratorBase< TOutputImage, TScalarImage >::GetRTOImage () inline
Definition at line 184 of file itkDWIGeneratorBase.h.
template<class TOutputImage , class TScalarImage = Image<double,3>> virtual double itk::DWIGeneratorBase< TOutputImage, TScalarImage >::GetSNR () virtual
template<class TOutputImage , class TScalarImage > void itk::DWIGeneratorBase< TOutputImage, TScalarImage >::Initialization () protected virtual
initialization, test
Reimplemented in itk::DWISingleVoxelGenerator< TOutputImage, TScalarImage >.
Definition at line 121 of file itkDWIGeneratorBase.hxx.
References itk::DWIGeneratorBase< TOutputImage, TScalarImage >::AllocateOutputs(), utlGlobalException, and utlShowPosition.
Referenced by itk::DWIGeneratorBase< TOutputImage, TScalarImage >::InternalClone().
template<class TOutputImage , class TScalarImage > LightObject::Pointer itk::DWIGeneratorBase< TOutputImage, TScalarImage >::InternalClone () const protected
Definition at line 78 of file itkDWIGeneratorBase.hxx.
References itk::DWIGeneratorBase< TOutputImage, TScalarImage >::Initialization().
Referenced by itk::DWIGeneratorBase< TOutputImage, TScalarImage >::~DWIGeneratorBase().
template<class TOutputImage , class TScalarImage = Image<double,3>> itk::DWIGeneratorBase< TOutputImage, TScalarImage >::itkGetObjectMacro (SamplingSchemeQSpace , SamplingSchemeQSpaceType)
template<class TOutputImage , class TScalarImage = Image<double,3>> itk::DWIGeneratorBase< TOutputImage, TScalarImage >::itkGetObjectMacro (SamplingSchemeRSpace , SamplingSchemeRSpaceType)
template<class TOutputImage , class TScalarImage = Image<double,3>> itk::DWIGeneratorBase< TOutputImage, TScalarImage >::itkGetObjectMacro (CylinderModel , CylinderModelType)
template<class TOutputImage , class TScalarImage = Image<double,3>> itk::DWIGeneratorBase< TOutputImage, TScalarImage >::itkSetGetBooleanMacro (IsOutputDWI)
template<class TOutputImage , class TScalarImage = Image<double,3>> itk::DWIGeneratorBase< TOutputImage, TScalarImage >::itkSetGetBooleanMacro (IsOutputEAP)
template<class TOutputImage , class TScalarImage = Image<double,3>> itk::DWIGeneratorBase< TOutputImage, TScalarImage >::itkSetGetBooleanMacro (IsOutputODF)
template<class TOutputImage , class TScalarImage = Image<double,3>> itk::DWIGeneratorBase< TOutputImage, TScalarImage >::itkSetGetBooleanMacro (IsOutputRTO)
template<class TOutputImage , class TScalarImage = Image<double,3>> itk::DWIGeneratorBase< TOutputImage, TScalarImage >::itkSetGetBooleanMacro (IsOutputMSD)
template<class TOutputImage , class TScalarImage = Image<double,3>> void itk::DWIGeneratorBase< TOutputImage, TScalarImage >::operator= (const Self &) private
template<class TOutputImage , class TScalarImage > void itk::DWIGeneratorBase< TOutputImage, TScalarImage >::PrintSelf (std::ostream & os, Indent indent) const protected
Definition at line 251 of file itkDWIGeneratorBase.hxx.
References itk::PeakContainerHelper::GetString(), PrintVar1, and PrintVar2.
Referenced by itk::DWIGeneratorBase< TOutputImage, TScalarImage >::AllocateOutputs().
template<class TOutputImage , class TScalarImage = Image<double,3>> virtual void itk::DWIGeneratorBase< TOutputImage, TScalarImage >::SetB0Scale (double _arg) virtual
template<class TOutputImage , class TScalarImage = Image<double,3>> virtual void itk::DWIGeneratorBase< TOutputImage, TScalarImage >::SetCylinderModel (CylinderModelType * _arg) virtual
template<class TOutputImage , class TScalarImage = Image<double,3>> virtual void itk::DWIGeneratorBase< TOutputImage, TScalarImage >::SetMaxNumberOfPeaks (int _arg) virtual
template<class TOutputImage , class TScalarImage = Image<double,3>> virtual void itk::DWIGeneratorBase< TOutputImage, TScalarImage >::SetModelType (const ModelType _arg) virtual
template<class TOutputImage , class TScalarImage = Image<double,3>> virtual void itk::DWIGeneratorBase< TOutputImage, TScalarImage >::SetNoiseSigma (double _arg) virtual
Parameters
template<class TOutputImage , class TScalarImage = Image<double,3>> virtual void itk::DWIGeneratorBase< TOutputImage, TScalarImage >::SetODFOrder (unsigned int _arg) virtual
template<class TOutputImage , class TScalarImage = Image<double,3>> virtual void itk::DWIGeneratorBase< TOutputImage, TScalarImage >::SetOutputSize (OutputImageSizeType _arg) virtual
Image size with the same diffusion parameters in all voxels
template<class TOutputImage , class TScalarImage = Image<double,3>> virtual void itk::DWIGeneratorBase< TOutputImage, TScalarImage >::SetPeakType (PeakType _arg) virtual
template<class TOutputImage , class TScalarImage = Image<double,3>> virtual void itk::DWIGeneratorBase< TOutputImage, TScalarImage >::SetSamplingSchemeQSpace (SamplingSchemeQSpaceType * _arg) virtual
template<class TOutputImage , class TScalarImage = Image<double,3>> virtual void itk::DWIGeneratorBase< TOutputImage, TScalarImage >::SetSamplingSchemeRSpace (SamplingSchemeRSpaceType * _arg) virtual
template<class TOutputImage , class TScalarImage = Image<double,3>> virtual void itk::DWIGeneratorBase< TOutputImage, TScalarImage >::SetSNR (double _arg) virtual
Member Data Documentation
template<class TOutputImage , class TScalarImage = Image<double,3>> double itk::DWIGeneratorBase< TOutputImage, TScalarImage >::m_B0Scale protected
Definition at line 223 of file itkDWIGeneratorBase.h.
template<class TOutputImage , class TScalarImage = Image<double,3>> CylinderModelPointer itk::DWIGeneratorBase< TOutputImage, TScalarImage >::m_CylinderModel protected
Definition at line 228 of file itkDWIGeneratorBase.h.
template<class TOutputImage , class TScalarImage = Image<double,3>> bool itk::DWIGeneratorBase< TOutputImage, TScalarImage >::m_IsOutputDWI protected
Definition at line 211 of file itkDWIGeneratorBase.h.
template<class TOutputImage , class TScalarImage = Image<double,3>> bool itk::DWIGeneratorBase< TOutputImage, TScalarImage >::m_IsOutputEAP protected
Definition at line 213 of file itkDWIGeneratorBase.h.
template<class TOutputImage , class TScalarImage = Image<double,3>> bool itk::DWIGeneratorBase< TOutputImage, TScalarImage >::m_IsOutputMSD protected
Definition at line 215 of file itkDWIGeneratorBase.h.
template<class TOutputImage , class TScalarImage = Image<double,3>> bool itk::DWIGeneratorBase< TOutputImage, TScalarImage >::m_IsOutputODF protected
Definition at line 212 of file itkDWIGeneratorBase.h.
template<class TOutputImage , class TScalarImage = Image<double,3>> bool itk::DWIGeneratorBase< TOutputImage, TScalarImage >::m_IsOutputRTO protected
Definition at line 214 of file itkDWIGeneratorBase.h.
template<class TOutputImage , class TScalarImage = Image<double,3>> int itk::DWIGeneratorBase< TOutputImage, TScalarImage >::m_MaxNumberOfPeaks protected
Definition at line 225 of file itkDWIGeneratorBase.h.
template<class TOutputImage , class TScalarImage = Image<double,3>> ModelType itk::DWIGeneratorBase< TOutputImage, TScalarImage >::m_ModelType protected
Definition at line 222 of file itkDWIGeneratorBase.h.
template<class TOutputImage , class TScalarImage = Image<double,3>> double itk::DWIGeneratorBase< TOutputImage, TScalarImage >::m_NoiseSigma protected
Definition at line 217 of file itkDWIGeneratorBase.h.
template<class TOutputImage , class TScalarImage = Image<double,3>> unsigned int itk::DWIGeneratorBase< TOutputImage, TScalarImage >::m_ODFOrder protected
Definition at line 220 of file itkDWIGeneratorBase.h.
template<class TOutputImage , class TScalarImage = Image<double,3>> OutputImageDirectionType itk::DWIGeneratorBase< TOutputImage, TScalarImage >::m_OutputDirection protected
Definition at line 233 of file itkDWIGeneratorBase.h.
template<class TOutputImage , class TScalarImage = Image<double,3>> OutputImagePointType itk::DWIGeneratorBase< TOutputImage, TScalarImage >::m_OutputOrigin protected
Definition at line 232 of file itkDWIGeneratorBase.h.
template<class TOutputImage , class TScalarImage = Image<double,3>> OutputImageSizeType itk::DWIGeneratorBase< TOutputImage, TScalarImage >::m_OutputSize protected
Definition at line 230 of file itkDWIGeneratorBase.h.
template<class TOutputImage , class TScalarImage = Image<double,3>> OutputImageSpacingType itk::DWIGeneratorBase< TOutputImage, TScalarImage >::m_OutputSpacing protected
Definition at line 231 of file itkDWIGeneratorBase.h.
template<class TOutputImage , class TScalarImage = Image<double,3>> PeakType itk::DWIGeneratorBase< TOutputImage, TScalarImage >::m_PeakType protected
Definition at line 226 of file itkDWIGeneratorBase.h.
template<class TOutputImage , class TScalarImage = Image<double,3>> SamplingSchemeQSpacePointer itk::DWIGeneratorBase< TOutputImage, TScalarImage >::m_SamplingSchemeQSpace protected
Definition at line 207 of file itkDWIGeneratorBase.h.
template<class TOutputImage , class TScalarImage = Image<double,3>> SamplingSchemeRSpacePointer itk::DWIGeneratorBase< TOutputImage, TScalarImage >::m_SamplingSchemeRSpace protected
Definition at line 209 of file itkDWIGeneratorBase.h.
template<class TOutputImage , class TScalarImage = Image<double,3>> double itk::DWIGeneratorBase< TOutputImage, TScalarImage >::m_SNR protected
Definition at line 218 of file itkDWIGeneratorBase.h.
template<class TOutputImage , class TScalarImage = Image<double,3>> const unsigned int itk::DWIGeneratorBase< TOutputImage, TScalarImage >::OutputImageDimension = OutputImageType::ImageDimension static
Output image dimension
Definition at line 67 of file itkDWIGeneratorBase.h.
The documentation for this class was generated from the following files:
Modules/DWIProcessing/include/itkDWIGeneratorBase.h
Modules/DWIProcessing/include/itkDWIGeneratorBase.hxx