DMRITool: spams::FISTA::Lzero< T > Class Template Reference
spams::FISTA::Lzero< T > Class Template Reference
#include <fista.h>
Detailed Description
template<typename T>
class spams::FISTA::Lzero< T >
Definition at line 1147 of file fista.h.
Public Member Functions
T eval (const Vector< T > &x) const
void fenchel (const Vector< T > &input, T &val, T &scal) const
virtual bool is_fenchel () const
Lzero (const ParamReg< T > &param)
void prox (const Vector< T > &x, Vector< T > &y, const T lambda)
virtual ~Lzero ()
Public Member Functions inherited from spams::FISTA::Regularizer< T >
virtual T eval_dual_norm (const Vector< T > &x) const
virtual T eval_dual_norm_paths (const Vector< T > &x, SpMatrix< T > &path) const
virtual T eval_paths (const Vector< T > &x, SpMatrix< T > &paths_mat) const
virtual bool is_intercept () const
virtual bool is_subgrad () const
Regularizer ()
Regularizer (const ParamReg< T > &param)
virtual void reset ()
virtual void sub_grad (const Vector< T > &input, Vector< T > &output) const
virtual ~Regularizer ()
Additional Inherited Members
Protected Attributes inherited from spams::FISTA::Regularizer< T >
bool _intercept
bool _pos
Constructor & Destructor Documentation
template<typename T > spams::FISTA::Lzero< T >::Lzero (const ParamReg< T > & param) inline
Definition at line 1149 of file fista.h.
template<typename T > virtual spams::FISTA::Lzero< T >::~Lzero () inline virtual
Definition at line 1150 of file fista.h.
Member Function Documentation
template<typename T > T spams::FISTA::Lzero< T >::eval (const Vector< T > & x) const inline virtual
Implements spams::FISTA::Regularizer< T >.
Definition at line 1159 of file fista.h.
References spams::Vector< T >::lzero().
template<typename T > void spams::FISTA::Lzero< T >::fenchel (const Vector< T > & input, T & val, T & scal) const inline virtual
returns phi^star(input) and ouput=input if the fenchel is unconstrained returns 0 and scale input such that phi^star(output)=0 otherwise
Implements spams::FISTA::Regularizer< T >.
Definition at line 1162 of file fista.h.
template<typename T > virtual bool spams::FISTA::Lzero< T >::is_fenchel () const inline virtual
Reimplemented from spams::FISTA::Regularizer< T >.
Definition at line 1152 of file fista.h.
template<typename T > void spams::FISTA::Lzero< T >::prox (const Vector< T > & x, Vector< T > & y, const T lambda) inline virtual
Implements spams::FISTA::Regularizer< T >.
Definition at line 1153 of file fista.h.
References spams::Vector< T >::copy(), spams::Vector< T >::hardThrshold(), spams::Vector< T >::n(), and spams::Vector< T >::thrsPos().
The documentation for this class was generated from the following file:
ThirdParty/Spams/include/fista.h