DMRITool: itk::SpatiallyDenseSparseVectorImageFileWriter< TInputImage > Class Template Reference
itk::SpatiallyDenseSparseVectorImageFileWriter< TInputImage > Class Template Reference
#include <itkSpatiallyDenseSparseVectorImageFileWriter.h>
Detailed Description
template<class TInputImage>
class itk::SpatiallyDenseSparseVectorImageFileWriter< TInputImage >
Writes sparse vector image data to key and value files.
Author
Pew-Thian Yap (ptyap.nosp@m.@med.nosp@m..unc..nosp@m.edu)
Definition at line 35 of file itkSpatiallyDenseSparseVectorImageFileWriter.h.
Public Types
typedef SmartPointer< const Self > ConstPointer
typedef InputImageType::DirectionType InputImageDirectionType
typedef InputImageType::IndexType InputImageIndexType
typedef InputImageType::InternalPixelType InputImageInternalPixelType
typedef InputImageType::KeyType InputImageKeyType
typedef InputImageType::PixelContainerConstPointer InputImagePixelContainerConstPointerType
typedef InputImageType::PixelContainer InputImagePixelContainerType
typedef InputImageType::PixelMapConstIterator InputImagePixelMapConstIteratorType
typedef InputImageType::PixelMapType InputImagePixelPixelMapType
typedef InputImageType::Pointer InputImagePointer
typedef InputImageType::PointType InputImagePointType
typedef InputImageType::RegionType InputImageRegionType
typedef InputImageType::SizeType InputImageSizeType
typedef InputImageType::SpacingType InputImageSpacingType
typedef TInputImage InputImageType
typedef InputImageType::ValueType InputImageValueType
typedef KeyImageFileWriterType::Pointer KeyImageFileWriterPointer
typedef ImageFileWriter< KeyImageType > KeyImageFileWriterType
typedef KeyImageType::Pointer KeyImagePointer
typedef Image< InputImageKeyType, 1 > KeyImageType
typedef SmartPointer< Self > Pointer
typedef SpatiallyDenseSparseVectorImageFileWriter Self
typedef ProcessObject Superclass
typedef ValueImageFileWriterType::Pointer ValueImageFileWriterPointer
typedef ImageFileWriter< ValueImageType > ValueImageFileWriterType
typedef ValueImageType::Pointer ValueImagePointer
typedef Image< InputImageValueType, 1 > ValueImageType
Public Member Functions
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual const char * GetFileName () const
const InputImageType * GetInput (void)
const InputImageType * GetInput (unsigned int idx)
virtual const char * GetNameOfClass () const
virtual const bool & GetUseCompression ()
virtual void SetFileName (const char *_arg)
void SetInput (const InputImageType *input)
virtual void SetUseCompression (bool _arg)
virtual void Update () ITK_OVERRIDE
virtual void UseCompressionOff ()
virtual void UseCompressionOn ()
virtual void Write (void)
Static Public Member Functions
static Pointer New ()
Protected Member Functions
void GenerateData (void) ITK_OVERRIDE
void PrintSelf (std::ostream &os, Indent indent) const ITK_OVERRIDE
SpatiallyDenseSparseVectorImageFileWriter ()
~SpatiallyDenseSparseVectorImageFileWriter ()
Protected Attributes
KeyImagePointer m_KeyImage
KeyImageFileWriterPointer m_KeyImageFileWriter
ValueImagePointer m_ValueImage
ValueImageFileWriterPointer m_ValueImageFileWriter
Private Member Functions
void operator= (const Self &)
SpatiallyDenseSparseVectorImageFileWriter (const Self &)
Private Attributes
std::string m_FileName
bool m_UseCompression
Member Typedef Documentation
template<class TInputImage> typedef SmartPointer<const Self> itk::SpatiallyDenseSparseVectorImageFileWriter< TInputImage >::ConstPointer
Definition at line 42 of file itkSpatiallyDenseSparseVectorImageFileWriter.h.
template<class TInputImage> typedef InputImageType::DirectionType itk::SpatiallyDenseSparseVectorImageFileWriter< TInputImage >::InputImageDirectionType
Definition at line 58 of file itkSpatiallyDenseSparseVectorImageFileWriter.h.
template<class TInputImage> typedef InputImageType::IndexType itk::SpatiallyDenseSparseVectorImageFileWriter< TInputImage >::InputImageIndexType
Definition at line 55 of file itkSpatiallyDenseSparseVectorImageFileWriter.h.
template<class TInputImage> typedef InputImageType::InternalPixelType itk::SpatiallyDenseSparseVectorImageFileWriter< TInputImage >::InputImageInternalPixelType
Definition at line 59 of file itkSpatiallyDenseSparseVectorImageFileWriter.h.
template<class TInputImage> typedef InputImageType::KeyType itk::SpatiallyDenseSparseVectorImageFileWriter< TInputImage >::InputImageKeyType
Definition at line 61 of file itkSpatiallyDenseSparseVectorImageFileWriter.h.
template<class TInputImage> typedef InputImageType::PixelContainerConstPointer itk::SpatiallyDenseSparseVectorImageFileWriter< TInputImage >::InputImagePixelContainerConstPointerType
Definition at line 63 of file itkSpatiallyDenseSparseVectorImageFileWriter.h.
template<class TInputImage> typedef InputImageType::PixelContainer itk::SpatiallyDenseSparseVectorImageFileWriter< TInputImage >::InputImagePixelContainerType
Definition at line 62 of file itkSpatiallyDenseSparseVectorImageFileWriter.h.
template<class TInputImage> typedef InputImageType::PixelMapConstIterator itk::SpatiallyDenseSparseVectorImageFileWriter< TInputImage >::InputImagePixelMapConstIteratorType
Definition at line 65 of file itkSpatiallyDenseSparseVectorImageFileWriter.h.
template<class TInputImage> typedef InputImageType::PixelMapType itk::SpatiallyDenseSparseVectorImageFileWriter< TInputImage >::InputImagePixelPixelMapType
Definition at line 64 of file itkSpatiallyDenseSparseVectorImageFileWriter.h.
template<class TInputImage> typedef InputImageType::Pointer itk::SpatiallyDenseSparseVectorImageFileWriter< TInputImage >::InputImagePointer
Definition at line 52 of file itkSpatiallyDenseSparseVectorImageFileWriter.h.
template<class TInputImage> typedef InputImageType::PointType itk::SpatiallyDenseSparseVectorImageFileWriter< TInputImage >::InputImagePointType
Definition at line 57 of file itkSpatiallyDenseSparseVectorImageFileWriter.h.
template<class TInputImage> typedef InputImageType::RegionType itk::SpatiallyDenseSparseVectorImageFileWriter< TInputImage >::InputImageRegionType
Definition at line 53 of file itkSpatiallyDenseSparseVectorImageFileWriter.h.
template<class TInputImage> typedef InputImageType::SizeType itk::SpatiallyDenseSparseVectorImageFileWriter< TInputImage >::InputImageSizeType
Definition at line 54 of file itkSpatiallyDenseSparseVectorImageFileWriter.h.
template<class TInputImage> typedef InputImageType::SpacingType itk::SpatiallyDenseSparseVectorImageFileWriter< TInputImage >::InputImageSpacingType
Definition at line 56 of file itkSpatiallyDenseSparseVectorImageFileWriter.h.
template<class TInputImage> typedef TInputImage itk::SpatiallyDenseSparseVectorImageFileWriter< TInputImage >::InputImageType
Some convenient typedefs.
Definition at line 48 of file itkSpatiallyDenseSparseVectorImageFileWriter.h.
template<class TInputImage> typedef InputImageType::ValueType itk::SpatiallyDenseSparseVectorImageFileWriter< TInputImage >::InputImageValueType
Definition at line 60 of file itkSpatiallyDenseSparseVectorImageFileWriter.h.
template<class TInputImage> typedef KeyImageFileWriterType::Pointer itk::SpatiallyDenseSparseVectorImageFileWriter< TInputImage >::KeyImageFileWriterPointer
Definition at line 73 of file itkSpatiallyDenseSparseVectorImageFileWriter.h.
template<class TInputImage> typedef ImageFileWriter<KeyImageType> itk::SpatiallyDenseSparseVectorImageFileWriter< TInputImage >::KeyImageFileWriterType
Definition at line 72 of file itkSpatiallyDenseSparseVectorImageFileWriter.h.
template<class TInputImage> typedef KeyImageType::Pointer itk::SpatiallyDenseSparseVectorImageFileWriter< TInputImage >::KeyImagePointer
Definition at line 68 of file itkSpatiallyDenseSparseVectorImageFileWriter.h.
template<class TInputImage> typedef Image<InputImageKeyType, 1> itk::SpatiallyDenseSparseVectorImageFileWriter< TInputImage >::KeyImageType
Definition at line 67 of file itkSpatiallyDenseSparseVectorImageFileWriter.h.
template<class TInputImage> typedef SmartPointer<Self> itk::SpatiallyDenseSparseVectorImageFileWriter< TInputImage >::Pointer
Definition at line 41 of file itkSpatiallyDenseSparseVectorImageFileWriter.h.
template<class TInputImage> typedef SpatiallyDenseSparseVectorImageFileWriter itk::SpatiallyDenseSparseVectorImageFileWriter< TInputImage >::Self
Standard class typedefs.
Definition at line 39 of file itkSpatiallyDenseSparseVectorImageFileWriter.h.
template<class TInputImage> typedef ProcessObject itk::SpatiallyDenseSparseVectorImageFileWriter< TInputImage >::Superclass
Definition at line 40 of file itkSpatiallyDenseSparseVectorImageFileWriter.h.
template<class TInputImage> typedef ValueImageFileWriterType::Pointer itk::SpatiallyDenseSparseVectorImageFileWriter< TInputImage >::ValueImageFileWriterPointer
Definition at line 75 of file itkSpatiallyDenseSparseVectorImageFileWriter.h.
template<class TInputImage> typedef ImageFileWriter<ValueImageType> itk::SpatiallyDenseSparseVectorImageFileWriter< TInputImage >::ValueImageFileWriterType
Definition at line 74 of file itkSpatiallyDenseSparseVectorImageFileWriter.h.
template<class TInputImage> typedef ValueImageType::Pointer itk::SpatiallyDenseSparseVectorImageFileWriter< TInputImage >::ValueImagePointer
Definition at line 70 of file itkSpatiallyDenseSparseVectorImageFileWriter.h.
template<class TInputImage> typedef Image<InputImageValueType, 1> itk::SpatiallyDenseSparseVectorImageFileWriter< TInputImage >::ValueImageType
Definition at line 69 of file itkSpatiallyDenseSparseVectorImageFileWriter.h.
Constructor & Destructor Documentation
template<class TInputImage > itk::SpatiallyDenseSparseVectorImageFileWriter< TInputImage >::SpatiallyDenseSparseVectorImageFileWriter () protected
By default the MetaDataDictionary is taken from the input image and passed to the ImageIO. In some cases, however, a user may prefer to introduce her/his own MetaDataDictionary. This is often the case of the ImageSeriesWriter. This flag defined whether the MetaDataDictionary to use will be the one from the input image or the one already set in the ImageIO object.
Definition at line 28 of file itkSpatiallyDenseSparseVectorImageFileWriter.hxx.
References itk::SpatiallyDenseSparseVectorImageFileWriter< TInputImage >::~SpatiallyDenseSparseVectorImageFileWriter().
template<class TInputImage > itk::SpatiallyDenseSparseVectorImageFileWriter< TInputImage >::~SpatiallyDenseSparseVectorImageFileWriter () protected
Definition at line 38 of file itkSpatiallyDenseSparseVectorImageFileWriter.hxx.
References itk::SpatiallyDenseSparseVectorImageFileWriter< TInputImage >::SetInput().
Referenced by itk::SpatiallyDenseSparseVectorImageFileWriter< TInputImage >::SpatiallyDenseSparseVectorImageFileWriter().
template<class TInputImage> itk::SpatiallyDenseSparseVectorImageFileWriter< TInputImage >::SpatiallyDenseSparseVectorImageFileWriter (const Self &) private
Member Function Documentation
template<class TInputImage> virtual::itk::LightObject::Pointer itk::SpatiallyDenseSparseVectorImageFileWriter< TInputImage >::CreateAnother (void) const
template<class TInputImage > void itk::SpatiallyDenseSparseVectorImageFileWriter< TInputImage >::GenerateData (void) protected
Does the actual work.
Definition at line 108 of file itkSpatiallyDenseSparseVectorImageFileWriter.hxx.
References itk::SpatiallyDenseSparseVectorImageFileWriter< TInputImage >::PrintSelf().
Referenced by itk::SpatiallyDenseSparseVectorImageFileWriter< TInputImage >::Write().
template<class TInputImage> virtual const char* itk::SpatiallyDenseSparseVectorImageFileWriter< TInputImage >::GetFileName () const virtual
template<class TInputImage > const SpatiallyDenseSparseVectorImageFileWriter< TInputImage >::InputImageType * itk::SpatiallyDenseSparseVectorImageFileWriter< TInputImage >::GetInput (void)
Definition at line 58 of file itkSpatiallyDenseSparseVectorImageFileWriter.hxx.
Referenced by itk::SpatiallyDenseSparseVectorImageFileWriter< TInputImage >::SetInput().
template<class TInputImage > const SpatiallyDenseSparseVectorImageFileWriter< TInputImage >::InputImageType * itk::SpatiallyDenseSparseVectorImageFileWriter< TInputImage >::GetInput (unsigned int idx)
Definition at line 73 of file itkSpatiallyDenseSparseVectorImageFileWriter.hxx.
References itk::SpatiallyDenseSparseVectorImageFileWriter< TInputImage >::Write().
template<class TInputImage> virtual const char* itk::SpatiallyDenseSparseVectorImageFileWriter< TInputImage >::GetNameOfClass () const virtual
Run-time type information (and related methods).
template<class TInputImage> virtual const bool& itk::SpatiallyDenseSparseVectorImageFileWriter< TInputImage >::GetUseCompression () virtual
template<class TInputImage> static Pointer itk::SpatiallyDenseSparseVectorImageFileWriter< TInputImage >::New () static
Method for creation through the object factory.
template<class TInputImage> void itk::SpatiallyDenseSparseVectorImageFileWriter< TInputImage >::operator= (const Self &) private
template<class TInputImage > void itk::SpatiallyDenseSparseVectorImageFileWriter< TInputImage >::PrintSelf (std::ostream & os, Indent indent) const protected
Definition at line 342 of file itkSpatiallyDenseSparseVectorImageFileWriter.hxx.
Referenced by itk::SpatiallyDenseSparseVectorImageFileWriter< TInputImage >::GenerateData().
template<class TInputImage> virtual void itk::SpatiallyDenseSparseVectorImageFileWriter< TInputImage >::SetFileName (const char * _arg) virtual
Specify the names of the output files to write.
template<class TInputImage > void itk::SpatiallyDenseSparseVectorImageFileWriter< TInputImage >::SetInput (const InputImageType * input)
Definition at line 46 of file itkSpatiallyDenseSparseVectorImageFileWriter.hxx.
References itk::SpatiallyDenseSparseVectorImageFileWriter< TInputImage >::GetInput().
Referenced by itk::SpatiallyDenseSparseVectorImageFileWriter< TInputImage >::~SpatiallyDenseSparseVectorImageFileWriter().
template<class TInputImage> virtual void itk::SpatiallyDenseSparseVectorImageFileWriter< TInputImage >::SetUseCompression (bool _arg) virtual
Set the compression On or Off
template<class TInputImage> virtual void itk::SpatiallyDenseSparseVectorImageFileWriter< TInputImage >::Update () inline virtual
Aliased to the Write() method to be consistent with the rest of the pipeline.
Definition at line 98 of file itkSpatiallyDenseSparseVectorImageFileWriter.h.
References ITK_OVERRIDE.
template<class TInputImage> virtual void itk::SpatiallyDenseSparseVectorImageFileWriter< TInputImage >::UseCompressionOff () virtual
template<class TInputImage> virtual void itk::SpatiallyDenseSparseVectorImageFileWriter< TInputImage >::UseCompressionOn () virtual
template<class TInputImage > void itk::SpatiallyDenseSparseVectorImageFileWriter< TInputImage >::Write (void) virtual
A special version of the Update() method for writers. It invokes start and end events and handles releasing data. It eventually calls GenerateData() which does the actual writing. Note: the write method will write data specified by the IORegion. If not set, then then the whole image is written. Note that the region will be cropped to fit the input image's LargestPossibleRegion.
Definition at line 82 of file itkSpatiallyDenseSparseVectorImageFileWriter.hxx.
References itk::SpatiallyDenseSparseVectorImageFileWriter< TInputImage >::GenerateData().
Referenced by itk::SpatiallyDenseSparseVectorImageFileWriter< TInputImage >::GetInput().
Member Data Documentation
template<class TInputImage> std::string itk::SpatiallyDenseSparseVectorImageFileWriter< TInputImage >::m_FileName private
Definition at line 139 of file itkSpatiallyDenseSparseVectorImageFileWriter.h.
template<class TInputImage> KeyImagePointer itk::SpatiallyDenseSparseVectorImageFileWriter< TInputImage >::m_KeyImage protected
Definition at line 124 of file itkSpatiallyDenseSparseVectorImageFileWriter.h.
template<class TInputImage> KeyImageFileWriterPointer itk::SpatiallyDenseSparseVectorImageFileWriter< TInputImage >::m_KeyImageFileWriter protected
Definition at line 128 of file itkSpatiallyDenseSparseVectorImageFileWriter.h.
template<class TInputImage> bool itk::SpatiallyDenseSparseVectorImageFileWriter< TInputImage >::m_UseCompression private
Definition at line 141 of file itkSpatiallyDenseSparseVectorImageFileWriter.h.
template<class TInputImage> ValueImagePointer itk::SpatiallyDenseSparseVectorImageFileWriter< TInputImage >::m_ValueImage protected
Definition at line 125 of file itkSpatiallyDenseSparseVectorImageFileWriter.h.
template<class TInputImage> ValueImageFileWriterPointer itk::SpatiallyDenseSparseVectorImageFileWriter< TInputImage >::m_ValueImageFileWriter protected
Definition at line 129 of file itkSpatiallyDenseSparseVectorImageFileWriter.h.
The documentation for this class was generated from the following files:
ThirdParty/SpatiallyDenseSparseVectorImage/include/itkSpatiallyDenseSparseVectorImageFileWriter.h
ThirdParty/SpatiallyDenseSparseVectorImage/include/itkSpatiallyDenseSparseVectorImageFileWriter.hxx