DMRITool: itk::Fiber< TValue > Class Template Reference
itk::Fiber< TValue > Class Template Reference
#include <itkFiber.h>
Detailed Description
template<typename TValue = double>
class itk::Fiber< TValue >
Definition at line 27 of file itkFiber.h.
Public Types
typedef SmartPointer< const Self > ConstPointer
typedef SmartPointer< Self > Pointer
typedef Fiber Self
typedef std::shared_ptr< STD2DVectorType > STD2DVectorPointer
typedef std::vector< std::vector< ValueType > > STD2DVectorType
typedef std::shared_ptr< STDVectorType > STDVectorPointer
typedef std::vector< ValueType > STDVectorType
typedef DataObject Superclass
typedef TractType::Pointer TractPointer
typedef SlowPolyLineParametricPath< 3 > TractType
typedef TValue ValueType
typedef TractType::VertexType VertexType
Public Member Functions
virtual ::itk::LightObject::Pointer CreateAnother (void) const
Fiber< TValue >::Pointer DeepClone () const
double DistanceToPoint (double x, double y, double z) const
int GetDimensionOfProperties () const
int GetDimensionOfScalarsPerPoint () const
Vector< double, 3 > GetDirection (const double pos, bool isDerivativeNormalizedByDistance=false) const
virtual const char * GetNameOfClass () const
int GetNumberOfPoints () const
VertexType GetPoint (const int index) const
std::vector< double > GetPointDistanceStats () const
itkSetGetMacro (Properties, STDVectorPointer)
itkSetGetMacro (Scalars, STD2DVectorPointer)
itkSetGetMacro (Tract, TractPointer)
void RemovePropertiesByName (const std::string &name, const std::vector< std::string > &nameVec)
void RemoveScalarsByName (const std::string &name, const std::vector< std::string > &nameVec)
Static Public Member Functions
static Pointer New ()
Protected Member Functions
Fiber ()
LightObject::Pointer InternalClone () const ITK_OVERRIDE
virtual void PrintSelf (std::ostream &os, Indent indent) const ITK_OVERRIDE
~Fiber ()
Protected Attributes
STDVectorPointer m_Properties
STD2DVectorPointer m_Scalars
TractPointer m_Tract = TractType::New()
Private Member Functions
Fiber (const Self &) ITK_DELETE_FUNCTION
void operator= (const Self &) ITK_DELETE_FUNCTION
Member Typedef Documentation
template<typename TValue = double> typedef SmartPointer< const Self > itk::Fiber< TValue >::ConstPointer
Definition at line 34 of file itkFiber.h.
template<typename TValue = double> typedef SmartPointer< Self > itk::Fiber< TValue >::Pointer
Definition at line 33 of file itkFiber.h.
template<typename TValue = double> typedef Fiber itk::Fiber< TValue >::Self
Standard class typedefs.
Definition at line 31 of file itkFiber.h.
template<typename TValue = double> typedef std::shared_ptr<STD2DVectorType> itk::Fiber< TValue >::STD2DVectorPointer
Definition at line 49 of file itkFiber.h.
template<typename TValue = double> typedef std::vector<std::vector<ValueType> > itk::Fiber< TValue >::STD2DVectorType
Definition at line 48 of file itkFiber.h.
template<typename TValue = double> typedef std::shared_ptr<STDVectorType> itk::Fiber< TValue >::STDVectorPointer
Definition at line 47 of file itkFiber.h.
template<typename TValue = double> typedef std::vector<ValueType> itk::Fiber< TValue >::STDVectorType
Definition at line 46 of file itkFiber.h.
template<typename TValue = double> typedef DataObject itk::Fiber< TValue >::Superclass
Definition at line 32 of file itkFiber.h.
template<typename TValue = double> typedef TractType::Pointer itk::Fiber< TValue >::TractPointer
Definition at line 43 of file itkFiber.h.
template<typename TValue = double> typedef SlowPolyLineParametricPath< 3 > itk::Fiber< TValue >::TractType
Definition at line 42 of file itkFiber.h.
template<typename TValue = double> typedef TValue itk::Fiber< TValue >::ValueType
Definition at line 38 of file itkFiber.h.
template<typename TValue = double> typedef TractType::VertexType itk::Fiber< TValue >::VertexType
Definition at line 44 of file itkFiber.h.
Constructor & Destructor Documentation
template<typename TValue = double> itk::Fiber< TValue >::Fiber () inline protected
Definition at line 103 of file itkFiber.h.
template<typename TValue = double> itk::Fiber< TValue >::~Fiber () inline protected
Definition at line 105 of file itkFiber.h.
References itk::Fiber< TValue >::InternalClone(), ITK_OVERRIDE, and itk::Fiber< TValue >::PrintSelf().
template<typename TValue = double> itk::Fiber< TValue >::Fiber (const Self &) private
Member Function Documentation
template<typename TValue = double> virtual::itk::LightObject::Pointer itk::Fiber< TValue >::CreateAnother (void) const
template<class TValue > Fiber< TValue >::Pointer itk::Fiber< TValue >::DeepClone () const
Definition at line 43 of file itkFiber.hxx.
References itk::Fiber< TValue >::DistanceToPoint().
Referenced by itk::Fiber< TValue >::GetDirection(), and itk::Fiber< TValue >::InternalClone().
template<class TValue > double itk::Fiber< TValue >::DistanceToPoint (double x, double y, double z) const
Definition at line 65 of file itkFiber.hxx.
References itk::Fiber< TValue >::GetPointDistanceStats(), and utl::max().
Referenced by itk::Fiber< TValue >::DeepClone(), and itk::Fiber< TValue >::GetDirection().
template<typename TValue = double> int itk::Fiber< TValue >::GetDimensionOfProperties () const inline
Definition at line 56 of file itkFiber.h.
References itk::Fiber< TValue >::m_Properties.
template<typename TValue = double> int itk::Fiber< TValue >::GetDimensionOfScalarsPerPoint () const inline
Definition at line 61 of file itkFiber.h.
References itk::Fiber< TValue >::m_Scalars.
template<typename TValue = double> Vector<double,3> itk::Fiber< TValue >::GetDirection (const double pos, bool isDerivativeNormalizedByDistance = false) const inline
Definition at line 74 of file itkFiber.h.
References itk::Fiber< TValue >::DeepClone(), itk::Fiber< TValue >::DistanceToPoint(), itk::Fiber< TValue >::GetNumberOfPoints(), itk::Fiber< TValue >::GetPointDistanceStats(), itk::Fiber< TValue >::itkSetGetMacro(), and itk::Fiber< TValue >::m_Tract.
template<typename TValue = double> virtual const char* itk::Fiber< TValue >::GetNameOfClass () const virtual
template<typename TValue = double> int itk::Fiber< TValue >::GetNumberOfPoints () const inline
Definition at line 51 of file itkFiber.h.
References itk::Fiber< TValue >::m_Tract.
Referenced by itk::Fiber< TValue >::GetDirection().
template<typename TValue = double> VertexType itk::Fiber< TValue >::GetPoint (const int index) const inline
Definition at line 66 of file itkFiber.h.
References itk::Fiber< TValue >::m_Tract, itk::Fiber< TValue >::RemovePropertiesByName(), and itk::Fiber< TValue >::RemoveScalarsByName().
template<class TValue > std::vector< double > itk::Fiber< TValue >::GetPointDistanceStats () const
Definition at line 86 of file itkFiber.hxx.
References utl::GetContainerStats(), and itk::Fiber< TValue >::RemoveScalarsByName().
Referenced by itk::Fiber< TValue >::DistanceToPoint(), and itk::Fiber< TValue >::GetDirection().
template<class TValue > LightObject::Pointer itk::Fiber< TValue >::InternalClone () const protected
Definition at line 24 of file itkFiber.hxx.
References itk::Fiber< TValue >::DeepClone().
Referenced by itk::Fiber< TValue >::~Fiber().
template<typename TValue = double> itk::Fiber< TValue >::itkSetGetMacro (Properties , STDVectorPointer)
Referenced by itk::Fiber< TValue >::GetDirection().
template<typename TValue = double> itk::Fiber< TValue >::itkSetGetMacro (Scalars , STD2DVectorPointer)
template<typename TValue = double> itk::Fiber< TValue >::itkSetGetMacro (Tract , TractPointer)
template<typename TValue = double> static Pointer itk::Fiber< TValue >::New () static
Referenced by itk::FiberTractsReader::ReadTractsTRK().
template<typename TValue = double> void itk::Fiber< TValue >::operator= (const Self &) private
template<class TValue > void itk::Fiber< TValue >::PrintSelf (std::ostream & os, Indent indent) const protected virtual
Definition at line 122 of file itkFiber.hxx.
References itk::GetDimensionOfProperties(), PrintVar, and utl::PrintVector().
Referenced by itk::Fiber< TValue >::RemovePropertiesByName(), and itk::Fiber< TValue >::~Fiber().
template<class TValue > void itk::Fiber< TValue >::RemovePropertiesByName (const std::string & name, const std::vector< std::string > & nameVec)
Definition at line 114 of file itkFiber.hxx.
References itk::Fiber< TValue >::PrintSelf(), and utl::RemoveScalarsByName().
Referenced by itk::Fiber< TValue >::GetPoint(), and itk::Fiber< TValue >::RemoveScalarsByName().
template<class TValue > void itk::Fiber< TValue >::RemoveScalarsByName (const std::string & name, const std::vector< std::string > & nameVec)
Definition at line 102 of file itkFiber.hxx.
References itk::Fiber< TValue >::RemovePropertiesByName(), and utl::RemoveScalarsByName().
Referenced by itk::Fiber< TValue >::GetPoint(), and itk::Fiber< TValue >::GetPointDistanceStats().
Member Data Documentation
template<typename TValue = double> STDVectorPointer itk::Fiber< TValue >::m_Properties protected
properties for a single tract
Definition at line 114 of file itkFiber.h.
Referenced by itk::Fiber< TValue >::GetDimensionOfProperties().
template<typename TValue = double> STD2DVectorPointer itk::Fiber< TValue >::m_Scalars protected
various scalars for points along a single tract
Definition at line 117 of file itkFiber.h.
Referenced by itk::Fiber< TValue >::GetDimensionOfScalarsPerPoint().
template<typename TValue = double> TractPointer itk::Fiber< TValue >::m_Tract = TractType::New() protected
Definition at line 111 of file itkFiber.h.
Referenced by itk::Fiber< TValue >::GetDirection(), itk::Fiber< TValue >::GetNumberOfPoints(), and itk::Fiber< TValue >::GetPoint().
The documentation for this class was generated from the following files:
Modules/Tractography/include/itkFiber.h
Modules/Tractography/include/itkFiber.hxx