DMRITool: itk::MaskedImageToImageFilter< TInputImage, TOutputImage, TMaskImage > Class Template Reference
itk::MaskedImageToImageFilter< TInputImage, TOutputImage, TMaskImage > Class Template Reference
#include <itkMaskedImageToImageFilter.h>
Detailed Description
template<class TInputImage, class TOutputImage, class TMaskImage = Image<double, 3>>
class itk::MaskedImageToImageFilter< TInputImage, TOutputImage, TMaskImage >
ImageToImageFilter with mask and threaded logger support.
Author
Jian Cheng (JC), jian..nosp@m.chen.nosp@m.g.198.nosp@m.3@gm.nosp@m.ail.c.nosp@m.om
Definition at line 37 of file itkMaskedImageToImageFilter.h.
Public Types
typedef SmartPointer< const Self > ConstPointer
typedef InputImageType::ConstPointer InputImageConstPointer
typedef InputImageType::IndexType InputImageIndexType
typedef InputImageType::PixelType InputImagePixelType
typedef InputImageType::Pointer InputImagePointer
typedef InputImageType::RegionType InputImageRegionType
typedef InputImageType::SizeType InputImageSizeType
typedef InputImageType::SpacingType InputImageSpacingType
typedef TInputImage InputImageType
typedef LoggerType::Pointer LoggerPointer
typedef ThreadLogger LoggerType
typedef utl_shared_ptr< LoggerVectorType > LoggerVectorPointer
typedef std::vector< LoggerPointer > LoggerVectorType
typedef MaskImageType::Pointer MaskImagePointer
typedef TMaskImage MaskImageType
typedef OutputImageType::IndexType OutputImageIndexType
typedef OutputImageType::PixelType OutputImagePixelType
typedef OutputImageType::Pointer OutputImagePointer
typedef OutputImageType::RegionType OutputImageRegionType
typedef OutputImageType::SizeType OutputImageSizeType
typedef OutputImageType::SpacingType OutputImageSpacingType
typedef TOutputImage OutputImageType
typedef SmartPointer< Self > Pointer
typedef MaskedImageToImageFilter Self
typedef ImageToImageFilter< TInputImage, TOutputImage > Superclass
Public Member Functions
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual const LoggerType * GetLogger () const
virtual const MaskImageType * GetMaskImage () const
virtual const char * GetNameOfClass () const
bool IsMaskUsed ()
itkGetObjectMacro (MaskImage, MaskImageType)
itkGetObjectMacro (Logger, LoggerType)
itkSetGetMacro (LogLevel, int)
virtual void SetLogger (LoggerType *_arg)
virtual void SetMaskImage (MaskImageType *_arg)
void SetMaskImage (const std::string &file)
Static Public Member Functions
static Pointer New ()
Static Public Attributes
static const unsigned int InputImageDimension = TInputImage::ImageDimension
static const unsigned int OutputImageDimension = TOutputImage::ImageDimension
Protected Member Functions
void CreateLoggerVector ()
virtual void InitializeThreadedLibraries ()
LightObject::Pointer InternalClone () const ITK_OVERRIDE
MaskedImageToImageFilter ()
virtual void PrintSelf (std::ostream &os, Indent indent) const ITK_OVERRIDE
std::string ThreadIDToString () const
virtual void VerifyInputParameters () const
virtual void VerifyMaskInformation () const
void WriteLogger (const std::string &str, const LoggerBase::PriorityLevelType level=LoggerBase::DEBUG) const
virtual ~MaskedImageToImageFilter ()
Protected Attributes
LoggerPointer m_Logger
LoggerVectorPointer m_LoggerVector
int m_LogLevel
MaskImagePointer m_MaskImage
int m_ThreadID
Private Member Functions
MaskedImageToImageFilter (const Self &)
void operator= (const Self &)
Member Typedef Documentation
template<class TInputImage, class TOutputImage, class TMaskImage = Image<double, 3>> typedef SmartPointer< const Self > itk::MaskedImageToImageFilter< TInputImage, TOutputImage, TMaskImage >::ConstPointer
Definition at line 45 of file itkMaskedImageToImageFilter.h.
template<class TInputImage, class TOutputImage, class TMaskImage = Image<double, 3>> typedef InputImageType::ConstPointer itk::MaskedImageToImageFilter< TInputImage, TOutputImage, TMaskImage >::InputImageConstPointer
Definition at line 55 of file itkMaskedImageToImageFilter.h.
template<class TInputImage, class TOutputImage, class TMaskImage = Image<double, 3>> typedef InputImageType::IndexType itk::MaskedImageToImageFilter< TInputImage, TOutputImage, TMaskImage >::InputImageIndexType
Definition at line 56 of file itkMaskedImageToImageFilter.h.
template<class TInputImage, class TOutputImage, class TMaskImage = Image<double, 3>> typedef InputImageType::PixelType itk::MaskedImageToImageFilter< TInputImage, TOutputImage, TMaskImage >::InputImagePixelType
Definition at line 59 of file itkMaskedImageToImageFilter.h.
template<class TInputImage, class TOutputImage, class TMaskImage = Image<double, 3>> typedef InputImageType::Pointer itk::MaskedImageToImageFilter< TInputImage, TOutputImage, TMaskImage >::InputImagePointer
Definition at line 54 of file itkMaskedImageToImageFilter.h.
template<class TInputImage, class TOutputImage, class TMaskImage = Image<double, 3>> typedef InputImageType::RegionType itk::MaskedImageToImageFilter< TInputImage, TOutputImage, TMaskImage >::InputImageRegionType
Definition at line 60 of file itkMaskedImageToImageFilter.h.
template<class TInputImage, class TOutputImage, class TMaskImage = Image<double, 3>> typedef InputImageType::SizeType itk::MaskedImageToImageFilter< TInputImage, TOutputImage, TMaskImage >::InputImageSizeType
Definition at line 57 of file itkMaskedImageToImageFilter.h.
template<class TInputImage, class TOutputImage, class TMaskImage = Image<double, 3>> typedef InputImageType::SpacingType itk::MaskedImageToImageFilter< TInputImage, TOutputImage, TMaskImage >::InputImageSpacingType
Definition at line 58 of file itkMaskedImageToImageFilter.h.
template<class TInputImage, class TOutputImage, class TMaskImage = Image<double, 3>> typedef TInputImage itk::MaskedImageToImageFilter< TInputImage, TOutputImage, TMaskImage >::InputImageType
Definition at line 51 of file itkMaskedImageToImageFilter.h.
template<class TInputImage, class TOutputImage, class TMaskImage = Image<double, 3>> typedef LoggerType::Pointer itk::MaskedImageToImageFilter< TInputImage, TOutputImage, TMaskImage >::LoggerPointer
Definition at line 78 of file itkMaskedImageToImageFilter.h.
template<class TInputImage, class TOutputImage, class TMaskImage = Image<double, 3>> typedef ThreadLogger itk::MaskedImageToImageFilter< TInputImage, TOutputImage, TMaskImage >::LoggerType
Definition at line 77 of file itkMaskedImageToImageFilter.h.
template<class TInputImage, class TOutputImage, class TMaskImage = Image<double, 3>> typedef utl_shared_ptr<LoggerVectorType> itk::MaskedImageToImageFilter< TInputImage, TOutputImage, TMaskImage >::LoggerVectorPointer
Definition at line 80 of file itkMaskedImageToImageFilter.h.
template<class TInputImage, class TOutputImage, class TMaskImage = Image<double, 3>> typedef std::vector<LoggerPointer> itk::MaskedImageToImageFilter< TInputImage, TOutputImage, TMaskImage >::LoggerVectorType
Definition at line 79 of file itkMaskedImageToImageFilter.h.
template<class TInputImage, class TOutputImage, class TMaskImage = Image<double, 3>> typedef MaskImageType::Pointer itk::MaskedImageToImageFilter< TInputImage, TOutputImage, TMaskImage >::MaskImagePointer
Definition at line 71 of file itkMaskedImageToImageFilter.h.
template<class TInputImage, class TOutputImage, class TMaskImage = Image<double, 3>> typedef TMaskImage itk::MaskedImageToImageFilter< TInputImage, TOutputImage, TMaskImage >::MaskImageType
Definition at line 70 of file itkMaskedImageToImageFilter.h.
template<class TInputImage, class TOutputImage, class TMaskImage = Image<double, 3>> typedef OutputImageType::IndexType itk::MaskedImageToImageFilter< TInputImage, TOutputImage, TMaskImage >::OutputImageIndexType
Definition at line 64 of file itkMaskedImageToImageFilter.h.
template<class TInputImage, class TOutputImage, class TMaskImage = Image<double, 3>> typedef OutputImageType::PixelType itk::MaskedImageToImageFilter< TInputImage, TOutputImage, TMaskImage >::OutputImagePixelType
Definition at line 67 of file itkMaskedImageToImageFilter.h.
template<class TInputImage, class TOutputImage, class TMaskImage = Image<double, 3>> typedef OutputImageType::Pointer itk::MaskedImageToImageFilter< TInputImage, TOutputImage, TMaskImage >::OutputImagePointer
Definition at line 63 of file itkMaskedImageToImageFilter.h.
template<class TInputImage, class TOutputImage, class TMaskImage = Image<double, 3>> typedef OutputImageType::RegionType itk::MaskedImageToImageFilter< TInputImage, TOutputImage, TMaskImage >::OutputImageRegionType
Definition at line 68 of file itkMaskedImageToImageFilter.h.
template<class TInputImage, class TOutputImage, class TMaskImage = Image<double, 3>> typedef OutputImageType::SizeType itk::MaskedImageToImageFilter< TInputImage, TOutputImage, TMaskImage >::OutputImageSizeType
Definition at line 65 of file itkMaskedImageToImageFilter.h.
template<class TInputImage, class TOutputImage, class TMaskImage = Image<double, 3>> typedef OutputImageType::SpacingType itk::MaskedImageToImageFilter< TInputImage, TOutputImage, TMaskImage >::OutputImageSpacingType
Definition at line 66 of file itkMaskedImageToImageFilter.h.
template<class TInputImage, class TOutputImage, class TMaskImage = Image<double, 3>> typedef TOutputImage itk::MaskedImageToImageFilter< TInputImage, TOutputImage, TMaskImage >::OutputImageType
Definition at line 62 of file itkMaskedImageToImageFilter.h.
template<class TInputImage, class TOutputImage, class TMaskImage = Image<double, 3>> typedef SmartPointer< Self > itk::MaskedImageToImageFilter< TInputImage, TOutputImage, TMaskImage >::Pointer
Definition at line 44 of file itkMaskedImageToImageFilter.h.
template<class TInputImage, class TOutputImage, class TMaskImage = Image<double, 3>> typedef MaskedImageToImageFilter itk::MaskedImageToImageFilter< TInputImage, TOutputImage, TMaskImage >::Self
Standard class typedefs.
Definition at line 42 of file itkMaskedImageToImageFilter.h.
template<class TInputImage, class TOutputImage, class TMaskImage = Image<double, 3>> typedef ImageToImageFilter< TInputImage, TOutputImage > itk::MaskedImageToImageFilter< TInputImage, TOutputImage, TMaskImage >::Superclass
Definition at line 43 of file itkMaskedImageToImageFilter.h.
Constructor & Destructor Documentation
template<class TInputImage , class TOutputImage , class TMaskImage > itk::MaskedImageToImageFilter< TInputImage, TOutputImage, TMaskImage >::MaskedImageToImageFilter () protected
Definition at line 32 of file itkMaskedImageToImageFilter.hxx.
References LOG_NORMAL, and itk::MaskedImageToImageFilter< TInputImage, TOutputImage, TMaskImage >::~MaskedImageToImageFilter().
template<class TInputImage , class TOutputImage , class TMaskImage > itk::MaskedImageToImageFilter< TInputImage, TOutputImage, TMaskImage >::~MaskedImageToImageFilter () protected virtual
Definition at line 48 of file itkMaskedImageToImageFilter.hxx.
References itk::MaskedImageToImageFilter< TInputImage, TOutputImage, TMaskImage >::SetMaskImage().
Referenced by itk::MaskedImageToImageFilter< TInputImage, TOutputImage, TMaskImage >::MaskedImageToImageFilter().
template<class TInputImage, class TOutputImage, class TMaskImage = Image<double, 3>> itk::MaskedImageToImageFilter< TInputImage, TOutputImage, TMaskImage >::MaskedImageToImageFilter (const Self &) private
Member Function Documentation
template<class TInputImage, class TOutputImage, class TMaskImage = Image<double, 3>> virtual::itk::LightObject::Pointer itk::MaskedImageToImageFilter< TInputImage, TOutputImage, TMaskImage >::CreateAnother (void) const
template<class TInputImage , class TOutputImage , class TMaskImage > void itk::MaskedImageToImageFilter< TInputImage, TOutputImage, TMaskImage >::CreateLoggerVector () protected
create m_LoggerVector only when m_Debug is true and multiple threads are used
Definition at line 98 of file itkMaskedImageToImageFilter.hxx.
References utlException, and itk::MaskedImageToImageFilter< TInputImage, TOutputImage, TMaskImage >::WriteLogger().
Referenced by itk::MaskedImageToImageFilter< TInputImage, TOutputImage, TMaskImage >::InternalClone().
template<class TInputImage, class TOutputImage, class TMaskImage = Image<double, 3>> virtual const LoggerType* itk::MaskedImageToImageFilter< TInputImage, TOutputImage, TMaskImage >::GetLogger () const virtual
template<class TInputImage, class TOutputImage, class TMaskImage = Image<double, 3>> virtual const MaskImageType* itk::MaskedImageToImageFilter< TInputImage, TOutputImage, TMaskImage >::GetMaskImage () const virtual
template<class TInputImage, class TOutputImage, class TMaskImage = Image<double, 3>> virtual const char* itk::MaskedImageToImageFilter< TInputImage, TOutputImage, TMaskImage >::GetNameOfClass () const virtual
Run-time type information (and related methods).
Reimplemented in itk::MeshFromImageImageFilter< TInputImage, TOutputMesh >, itk::MeshFromPeaksImageFilter< TInputImage, TOutputMesh >, itk::DiffusionModelEstimationImageFilter< TInputImage, TOutputImage >, itk::MeshFromContinuousSphericalFunctionImageFilter< TInputImage, TOutputMesh >, itk::FeaturesFromSPFImageFilter< TInputImage, TOutputImage >, itk::SphericalPolarFourierEstimationImageFilter< TInputImage, TOutputImage >, itk::FunctorBaseVectorImageFilter< TInputImage, TOutputImage, TFunction, TMaskImage >, itk::FunctorBaseVectorImageFilter< TInputImage, TOutputImage, utl::Functor::VectorMultiVariableFunctionWrapper<>, TMaskImage >, itk::FunctorFromStringImageFilter< TInputImage, TOutputImage, TMaskImage >, itk::DiffusionModelEstimationInSphericalCoordinateImageFilter< TInputImage, TOutputImage >, itk::SphericalPolarFourierImageFilter< TInputImage, TOutputImage >, itk::MeshFromDiscreteFiberODFImageFilter< TInputImage, TOutputMesh >, itk::GeneralizedHighOrderTensorImageFilter< TInputImage, TOutputImage >, itk::ProfileFromSPFImageFilter< TInputImage, TOutputImage >, itk::MeshFromSphericalFunctionImageFilter< TInputImage, TOutputMesh >, itk::MeshFromSphericalFunctionTessellatedSamplesImageFilter< TInputImage, TOutputMesh >, itk::ODFFromSPFImageFilter< TInputImage, TOutputImage >, itk::MeshFromTensorImageFilter< TInputImage, TOutputMesh >, itk::MultiVariableFunctorVectorImageFilter< TInputImage, TOutputImage, TFunction, TMaskImage >, itk::UnaryFunctorVectorImageFilter< TInputImage, TOutputImage, TFunction, TMaskImage >, itk::MeshFromSHCoefficientsImageFilter< TInputImage, TOutputMesh >, and itk::ScalarMapFromSPFImageFilter< TInputImage, TOutputImage >.
template<class TInputImage , class TOutputImage , class TMaskImage > void itk::MaskedImageToImageFilter< TInputImage, TOutputImage, TMaskImage >::InitializeThreadedLibraries () protected virtual
Use single thread for MKL or openmp to avoid confliction with itk threader. Otherwise it has worse performance due to thread conflication (but correct solution).
Reimplemented in itk::SphericalPolarFourierEstimationImageFilter< TInputImage, TOutputImage >.
Definition at line 151 of file itkMaskedImageToImageFilter.hxx.
References utl::InitializeThreadedLibraries(), and itk::MaskedImageToImageFilter< TInputImage, TOutputImage, TMaskImage >::PrintSelf().
Referenced by itk::MaskedImageToImageFilter< TInputImage, TOutputImage, TMaskImage >::ThreadIDToString().
template<class TInputImage , class TOutputImage , class TMaskImage > LightObject::Pointer itk::MaskedImageToImageFilter< TInputImage, TOutputImage, TMaskImage >::InternalClone () const protected
Definition at line 76 of file itkMaskedImageToImageFilter.hxx.
References itk::MaskedImageToImageFilter< TInputImage, TOutputImage, TMaskImage >::CreateLoggerVector().
Referenced by itk::MaskedImageToImageFilter< TInputImage, TOutputImage, TMaskImage >::VerifyMaskInformation().
template<class TInputImage, class TOutputImage, class TMaskImage = Image<double, 3>> bool itk::MaskedImageToImageFilter< TInputImage, TOutputImage, TMaskImage >::IsMaskUsed () inline
Definition at line 95 of file itkMaskedImageToImageFilter.h.
template<class TInputImage, class TOutputImage, class TMaskImage = Image<double, 3>> itk::MaskedImageToImageFilter< TInputImage, TOutputImage, TMaskImage >::itkGetObjectMacro (MaskImage , MaskImageType)
template<class TInputImage, class TOutputImage, class TMaskImage = Image<double, 3>> itk::MaskedImageToImageFilter< TInputImage, TOutputImage, TMaskImage >::itkGetObjectMacro (Logger , LoggerType)
template<class TInputImage, class TOutputImage, class TMaskImage = Image<double, 3>> itk::MaskedImageToImageFilter< TInputImage, TOutputImage, TMaskImage >::itkSetGetMacro (LogLevel , int)
template<class TInputImage, class TOutputImage, class TMaskImage = Image<double, 3>> static Pointer itk::MaskedImageToImageFilter< TInputImage, TOutputImage, TMaskImage >::New () static
Method for creation through the object factory.
template<class TInputImage, class TOutputImage, class TMaskImage = Image<double, 3>> void itk::MaskedImageToImageFilter< TInputImage, TOutputImage, TMaskImage >::operator= (const Self &) private
template<class TInputImage , class TOutputImage , class TMaskImage > void itk::MaskedImageToImageFilter< TInputImage, TOutputImage, TMaskImage >::PrintSelf (std::ostream & os, Indent indent) const protected virtual
Reimplemented in itk::MeshFromImageImageFilter< TInputImage, TOutputMesh >, itk::SphericalPolarFourierEstimationImageFilter< TInputImage, TOutputImage >, itk::MeshFromTensorImageFilter< TInputImage, TOutputMesh >, itk::MeshFromDiscreteFiberODFImageFilter< TInputImage, TOutputMesh >, itk::MeshFromSphericalFunctionTessellatedSamplesImageFilter< TInputImage, TOutputMesh >, itk::MeshFromContinuousSphericalFunctionImageFilter< TInputImage, TOutputMesh >, itk::FeaturesFromSPFImageFilter< TInputImage, TOutputImage >, itk::MeshFromSphericalFunctionImageFilter< TInputImage, TOutputMesh >, itk::MeshFromSHCoefficientsImageFilter< TInputImage, TOutputMesh >, itk::MeshFromPeaksImageFilter< TInputImage, TOutputMesh >, itk::FunctorBaseVectorImageFilter< TInputImage, TOutputImage, TFunction, TMaskImage >, itk::FunctorBaseVectorImageFilter< TInputImage, TOutputImage, utl::Functor::VectorMultiVariableFunctionWrapper<>, TMaskImage >, itk::DiffusionModelEstimationInSphericalCoordinateImageFilter< TInputImage, TOutputImage >, itk::DiffusionModelEstimationImageFilter< TInputImage, TOutputImage >, itk::SphericalPolarFourierImageFilter< TInputImage, TOutputImage >, itk::ODFFromSPFImageFilter< TInputImage, TOutputImage >, itk::ProfileFromSPFImageFilter< TInputImage, TOutputImage >, itk::ScalarMapFromSPFImageFilter< TInputImage, TOutputImage >, and itk::GeneralizedHighOrderTensorImageFilter< TInputImage, TOutputImage >.
Definition at line 159 of file itkMaskedImageToImageFilter.hxx.
References itk::IsImageEmpty().
Referenced by itk::MaskedImageToImageFilter< TInputImage, TOutputImage, TMaskImage >::InitializeThreadedLibraries().
template<class TInputImage, class TOutputImage, class TMaskImage = Image<double, 3>> virtual void itk::MaskedImageToImageFilter< TInputImage, TOutputImage, TMaskImage >::SetLogger (LoggerType * _arg) virtual
Set/Get the mask image.
template<class TInputImage, class TOutputImage, class TMaskImage = Image<double, 3>> virtual void itk::MaskedImageToImageFilter< TInputImage, TOutputImage, TMaskImage >::SetMaskImage (MaskImageType * _arg) virtual
Set/Get the mask image.
Referenced by itk::MaskedImageToImageFilter< TInputImage, TOutputImage, TMaskImage >::~MaskedImageToImageFilter().
template<class TInputImage , class TOutputImage , class TMaskImage > void itk::MaskedImageToImageFilter< TInputImage, TOutputImage, TMaskImage >::SetMaskImage (const std::string & file)
Definition at line 54 of file itkMaskedImageToImageFilter.hxx.
References itk::MaskedImageToImageFilter< TInputImage, TOutputImage, TMaskImage >::VerifyMaskInformation().
template<class TInputImage , class TOutputImage , class TMaskImage > std::string itk::MaskedImageToImageFilter< TInputImage, TOutputImage, TMaskImage >::ThreadIDToString () const protected
Definition at line 136 of file itkMaskedImageToImageFilter.hxx.
References itk::MaskedImageToImageFilter< TInputImage, TOutputImage, TMaskImage >::InitializeThreadedLibraries().
Referenced by itk::MaskedImageToImageFilter< TInputImage, TOutputImage, TMaskImage >::WriteLogger().
template<class TInputImage, class TOutputImage, class TMaskImage = Image<double, 3>> virtual void itk::MaskedImageToImageFilter< TInputImage, TOutputImage, TMaskImage >::VerifyInputParameters () const inline protected virtual
Reimplemented in itk::MeshFromImageImageFilter< TInputImage, TOutputMesh >, itk::MeshFromTensorImageFilter< TInputImage, TOutputMesh >, itk::SphericalPolarFourierEstimationImageFilter< TInputImage, TOutputImage >, itk::FeaturesFromSPFImageFilter< TInputImage, TOutputImage >, itk::MeshFromContinuousSphericalFunctionImageFilter< TInputImage, TOutputMesh >, itk::MeshFromPeaksImageFilter< TInputImage, TOutputMesh >, itk::DiffusionModelEstimationInSphericalCoordinateImageFilter< TInputImage, TOutputImage >, itk::DiffusionModelEstimationImageFilter< TInputImage, TOutputImage >, itk::ProfileFromSPFImageFilter< TInputImage, TOutputImage >, itk::ODFFromSPFImageFilter< TInputImage, TOutputImage >, itk::ScalarMapFromSPFImageFilter< TInputImage, TOutputImage >, and itk::GeneralizedHighOrderTensorImageFilter< TInputImage, TOutputImage >.
Definition at line 110 of file itkMaskedImageToImageFilter.h.
template<class TInputImage , class TOutputImage , class TMaskImage > void itk::MaskedImageToImageFilter< TInputImage, TOutputImage, TMaskImage >::VerifyMaskInformation () const protected virtual
Definition at line 64 of file itkMaskedImageToImageFilter.hxx.
References itk::MaskedImageToImageFilter< TInputImage, TOutputImage, TMaskImage >::InternalClone(), and utlGlobalException.
Referenced by itk::MaskedImageToImageFilter< TInputImage, TOutputImage, TMaskImage >::SetMaskImage().
template<class TInputImage , class TOutputImage , class TMaskImage > void itk::MaskedImageToImageFilter< TInputImage, TOutputImage, TMaskImage >::WriteLogger (const std::string & str, const LoggerBase::PriorityLevelType level = LoggerBase::DEBUG) const protected
Definition at line 120 of file itkMaskedImageToImageFilter.hxx.
References itk::MaskedImageToImageFilter< TInputImage, TOutputImage, TMaskImage >::ThreadIDToString(), and utlSAException.
Referenced by itk::MaskedImageToImageFilter< TInputImage, TOutputImage, TMaskImage >::CreateLoggerVector().
Member Data Documentation
template<class TInputImage, class TOutputImage, class TMaskImage = Image<double, 3>> const unsigned int itk::MaskedImageToImageFilter< TInputImage, TOutputImage, TMaskImage >::InputImageDimension = TInputImage::ImageDimension static
ImageDimension constants
Definition at line 74 of file itkMaskedImageToImageFilter.h.
template<class TInputImage, class TOutputImage, class TMaskImage = Image<double, 3>> LoggerPointer itk::MaskedImageToImageFilter< TInputImage, TOutputImage, TMaskImage >::m_Logger protected
Definition at line 129 of file itkMaskedImageToImageFilter.h.
template<class TInputImage, class TOutputImage, class TMaskImage = Image<double, 3>> LoggerVectorPointer itk::MaskedImageToImageFilter< TInputImage, TOutputImage, TMaskImage >::m_LoggerVector protected
Definition at line 130 of file itkMaskedImageToImageFilter.h.
template<class TInputImage, class TOutputImage, class TMaskImage = Image<double, 3>> int itk::MaskedImageToImageFilter< TInputImage, TOutputImage, TMaskImage >::m_LogLevel protected
Debug verbose log level. Default value is 1 (LOG_NORMAL), which only shows some process information. It is normally set as utl::LogLevel, but each class could have its own logLevel. If it is LOG_MUTE, mute all output messeage. If it is LOG_LARGE, print some large matrix etc.
Definition at line 139 of file itkMaskedImageToImageFilter.h.
template<class TInputImage, class TOutputImage, class TMaskImage = Image<double, 3>> MaskImagePointer itk::MaskedImageToImageFilter< TInputImage, TOutputImage, TMaskImage >::m_MaskImage protected
Definition at line 127 of file itkMaskedImageToImageFilter.h.
template<class TInputImage, class TOutputImage, class TMaskImage = Image<double, 3>> int itk::MaskedImageToImageFilter< TInputImage, TOutputImage, TMaskImage >::m_ThreadID protected
It is used for ThreadLogger. It is -1 as default, and it is set as thread id when *this is cloned.
Definition at line 133 of file itkMaskedImageToImageFilter.h.
template<class TInputImage, class TOutputImage, class TMaskImage = Image<double, 3>> const unsigned int itk::MaskedImageToImageFilter< TInputImage, TOutputImage, TMaskImage >::OutputImageDimension = TOutputImage::ImageDimension static
Definition at line 75 of file itkMaskedImageToImageFilter.h.
The documentation for this class was generated from the following files:
Modules/Common/include/itkMaskedImageToImageFilter.h
Modules/Common/include/itkMaskedImageToImageFilter.hxx