DMRITool: itk::FiberTracts< TValue > Class Template Reference
itk::FiberTracts< TValue > Class Template Reference
#include <itkFiberTracts.h>
Detailed Description
template<typename TValue = double>
class itk::FiberTracts< TValue >
Definition at line 26 of file itkFiberTracts.h.
Public Types
typedef SmartPointer< const Self > ConstPointer
typedef FiberContainerType::Pointer FiberContainerPointer
typedef VectorContainer< unsigned int, FiberPointer > FiberContainerType
typedef FiberType::Pointer FiberPointer
typedef Fiber< ValueType > FiberType
typedef std::shared_ptr< HeaderType > HeaderPointer
typedef TrackVisHeaderType HeaderType
typedef SmartPointer< Self > Pointer
typedef FiberTracts Self
typedef DataObject Superclass
typedef FiberType::TractPointer TractPointer
typedef FiberType::TractType TractType
typedef TValue ValueType
typedef TractType::VertexType VertexType
Public Member Functions
void AppendFiber (const FiberPointer fiber)
void AppendFibers (const Pointer fibers)
virtual ::itk::LightObject::Pointer CreateAnother (void) const
FiberTracts< TValue >::Pointer DeepClone () const
FiberPointer GetFiber (const int index) const
virtual const char * GetNameOfClass () const
int GetNumberOfFibers () const
int GetNumberOfPoints () const
void GetPointStats (std::vector< double > &numPointsStats, std::vector< double > &pointDistStats) const
bool HasPropertyName (const std::string &name) const
bool HasScalarName (const std::string &name) const
itkSetGetMacro (Header, HeaderPointer)
itkSetGetMacro (Fibers, FiberContainerPointer)
void PrintFibersHeader (std::ostream &os=std::cout, Indent indent=0) const
void RemovePropertiesByName (const std::string &name)
void RemoveScalarsByName (const std::string &name)
Pointer SelectByBallROI (double x, double y, double z, double radius)
Pointer SelectByIndicesOfTracts (const std::vector< int > &indices)
Static Public Member Functions
static Pointer New ()
Protected Member Functions
FiberTracts ()
LightObject::Pointer InternalClone () const ITK_OVERRIDE
virtual void PrintSelf (std::ostream &os, Indent indent) const ITK_OVERRIDE
~FiberTracts ()
Protected Attributes
FiberContainerPointer m_Fibers = FiberContainerType::New()
HeaderPointer m_Header
Private Member Functions
FiberTracts (const Self &) ITK_DELETE_FUNCTION
void operator= (const Self &) ITK_DELETE_FUNCTION
Member Typedef Documentation
template<typename TValue = double> typedef SmartPointer< const Self > itk::FiberTracts< TValue >::ConstPointer
Definition at line 33 of file itkFiberTracts.h.
template<typename TValue = double> typedef FiberContainerType::Pointer itk::FiberTracts< TValue >::FiberContainerPointer
Definition at line 51 of file itkFiberTracts.h.
template<typename TValue = double> typedef VectorContainer< unsigned int, FiberPointer > itk::FiberTracts< TValue >::FiberContainerType
Definition at line 50 of file itkFiberTracts.h.
template<typename TValue = double> typedef FiberType::Pointer itk::FiberTracts< TValue >::FiberPointer
Definition at line 45 of file itkFiberTracts.h.
template<typename TValue = double> typedef Fiber<ValueType> itk::FiberTracts< TValue >::FiberType
Definition at line 44 of file itkFiberTracts.h.
template<typename TValue = double> typedef std::shared_ptr<HeaderType> itk::FiberTracts< TValue >::HeaderPointer
Definition at line 42 of file itkFiberTracts.h.
template<typename TValue = double> typedef TrackVisHeaderType itk::FiberTracts< TValue >::HeaderType
Definition at line 41 of file itkFiberTracts.h.
template<typename TValue = double> typedef SmartPointer< Self > itk::FiberTracts< TValue >::Pointer
Definition at line 32 of file itkFiberTracts.h.
template<typename TValue = double> typedef FiberTracts itk::FiberTracts< TValue >::Self
Standard class typedefs.
Definition at line 30 of file itkFiberTracts.h.
template<typename TValue = double> typedef DataObject itk::FiberTracts< TValue >::Superclass
Definition at line 31 of file itkFiberTracts.h.
template<typename TValue = double> typedef FiberType::TractPointer itk::FiberTracts< TValue >::TractPointer
Definition at line 47 of file itkFiberTracts.h.
template<typename TValue = double> typedef FiberType::TractType itk::FiberTracts< TValue >::TractType
Definition at line 46 of file itkFiberTracts.h.
template<typename TValue = double> typedef TValue itk::FiberTracts< TValue >::ValueType
Definition at line 37 of file itkFiberTracts.h.
template<typename TValue = double> typedef TractType::VertexType itk::FiberTracts< TValue >::VertexType
Definition at line 48 of file itkFiberTracts.h.
Constructor & Destructor Documentation
template<typename TValue = double> itk::FiberTracts< TValue >::FiberTracts () inline protected
Definition at line 106 of file itkFiberTracts.h.
template<typename TValue = double> itk::FiberTracts< TValue >::~FiberTracts () inline protected
Definition at line 109 of file itkFiberTracts.h.
References itk::FiberTracts< TValue >::InternalClone(), ITK_OVERRIDE, and itk::FiberTracts< TValue >::PrintSelf().
template<typename TValue = double> itk::FiberTracts< TValue >::FiberTracts (const Self &) private
Member Function Documentation
template<class TValue > void itk::FiberTracts< TValue >::AppendFiber (const FiberPointer fiber)
Append a fiber. Should have the same number of scalars and the same number of properties.
Definition at line 151 of file itkFiberTracts.hxx.
References itk::FiberTracts< TValue >::AppendFibers().
Referenced by itk::FiberTracts< TValue >::HasScalarName(), and itk::FiberTracts< TValue >::SelectByBallROI().
template<class TValue > void itk::FiberTracts< TValue >::AppendFibers (const Pointer fibers)
Append fibers. Should have the same number of scalars and the same number of properties.
Definition at line 160 of file itkFiberTracts.hxx.
References itk::IsSameStructure(), itk::FiberTracts< TValue >::PrintSelf(), and utlGlobalException.
Referenced by itk::FiberTracts< TValue >::AppendFiber(), and itk::FiberTracts< TValue >::HasScalarName().
template<typename TValue = double> virtual::itk::LightObject::Pointer itk::FiberTracts< TValue >::CreateAnother (void) const
template<class TValue > FiberTracts< TValue >::Pointer itk::FiberTracts< TValue >::DeepClone () const
Definition at line 41 of file itkFiberTracts.hxx.
References itk::CopyTrackvisHeader(), and itk::FiberTracts< TValue >::GetNumberOfPoints().
Referenced by itk::FiberTracts< TValue >::GetFiber(), and itk::FiberTracts< TValue >::InternalClone().
template<typename TValue = double> FiberPointer itk::FiberTracts< TValue >::GetFiber (const int index) const inline
Definition at line 64 of file itkFiberTracts.h.
References itk::FiberTracts< TValue >::DeepClone(), and itk::FiberTracts< TValue >::m_Fibers.
template<typename TValue = double> virtual const char* itk::FiberTracts< TValue >::GetNameOfClass () const virtual
template<typename TValue = double> int itk::FiberTracts< TValue >::GetNumberOfFibers () const inline
Definition at line 57 of file itkFiberTracts.h.
References itk::FiberTracts< TValue >::GetNumberOfPoints(), and itk::FiberTracts< TValue >::m_Fibers.
template<class TValue > int itk::FiberTracts< TValue >::GetNumberOfPoints () const
Definition at line 58 of file itkFiberTracts.hxx.
References itk::FiberTracts< TValue >::GetPointStats().
Referenced by itk::FiberTracts< TValue >::DeepClone(), and itk::FiberTracts< TValue >::GetNumberOfFibers().
template<class TValue > void itk::FiberTracts< TValue >::GetPointStats (std::vector< double > & numPointsStats, std::vector< double > & pointDistStats) const
Get the stats of the number of points in each tract, and the stats of distances between two points in each tract.
Definition at line 69 of file itkFiberTracts.hxx.
References utl::GetContainerStats(), and itk::FiberTracts< TValue >::RemoveScalarsByName().
Referenced by itk::FiberTracts< TValue >::GetNumberOfPoints(), and itk::FiberTracts< TValue >::HasScalarName().
template<typename TValue = double> bool itk::FiberTracts< TValue >::HasPropertyName (const std::string & name) const inline
Definition at line 76 of file itkFiberTracts.h.
References itk::HasPropertyName(), and itk::FiberTracts< TValue >::m_Header.
template<typename TValue = double> bool itk::FiberTracts< TValue >::HasScalarName (const std::string & name) const inline
Definition at line 80 of file itkFiberTracts.h.
References itk::FiberTracts< TValue >::AppendFiber(), itk::FiberTracts< TValue >::AppendFibers(), itk::FiberTracts< TValue >::GetPointStats(), itk::HasScalarName(), itk::FiberTracts< TValue >::m_Header, itk::FiberTracts< TValue >::RemovePropertiesByName(), itk::FiberTracts< TValue >::RemoveScalarsByName(), itk::FiberTracts< TValue >::SelectByBallROI(), and itk::FiberTracts< TValue >::SelectByIndicesOfTracts().
template<class TValue > LightObject::Pointer itk::FiberTracts< TValue >::InternalClone () const protected
Definition at line 23 of file itkFiberTracts.hxx.
References itk::FiberTracts< TValue >::DeepClone().
Referenced by itk::FiberTracts< TValue >::~FiberTracts().
template<typename TValue = double> itk::FiberTracts< TValue >::itkSetGetMacro (Header , HeaderPointer)
template<typename TValue = double> itk::FiberTracts< TValue >::itkSetGetMacro (Fibers , FiberContainerPointer)
template<typename TValue = double> static Pointer itk::FiberTracts< TValue >::New () static
template<typename TValue = double> void itk::FiberTracts< TValue >::operator= (const Self &) private
template<typename TValue = double> void itk::FiberTracts< TValue >::PrintFibersHeader (std::ostream & os = std::cout, Indent indent = 0) const inline
Definition at line 71 of file itkFiberTracts.h.
References itk::FiberTracts< TValue >::m_Header, and itk::PrintTractVisHeader().
template<class TValue > void itk::FiberTracts< TValue >::PrintSelf (std::ostream & os, Indent indent) const protected virtual
Definition at line 170 of file itkFiberTracts.hxx.
References utl::PrintVector(), and utlSAGlobalException.
Referenced by itk::FiberTracts< TValue >::AppendFibers(), and itk::FiberTracts< TValue >::~FiberTracts().
template<class TValue > void itk::FiberTracts< TValue >::RemovePropertiesByName (const std::string & name)
remove properties by name
Definition at line 98 of file itkFiberTracts.hxx.
References utl::CovertChar2DArrayToStringArray(), itk::RemovePropertyName(), and itk::FiberTracts< TValue >::SelectByIndicesOfTracts().
Referenced by itk::FiberTracts< TValue >::HasScalarName(), and itk::FiberTracts< TValue >::RemoveScalarsByName().
template<class TValue > void itk::FiberTracts< TValue >::RemoveScalarsByName (const std::string & name)
remove scalars by name
Definition at line 86 of file itkFiberTracts.hxx.
References utl::CovertChar2DArrayToStringArray(), itk::FiberTracts< TValue >::RemovePropertiesByName(), and itk::RemoveScalarName().
Referenced by itk::FiberTracts< TValue >::GetPointStats(), and itk::FiberTracts< TValue >::HasScalarName().
template<class TValue > FiberTracts< TValue >::Pointer itk::FiberTracts< TValue >::SelectByBallROI (double x, double y, double z, double radius)
Get fiber tracts across in a ball ROI (origin x,y,z and radius)
Definition at line 126 of file itkFiberTracts.hxx.
References itk::FiberTracts< TValue >::AppendFiber(), and itk::CopyTrackvisHeader().
Referenced by itk::FiberTracts< TValue >::HasScalarName(), and itk::FiberTracts< TValue >::SelectByIndicesOfTracts().
template<class TValue > FiberTracts< TValue >::Pointer itk::FiberTracts< TValue >::SelectByIndicesOfTracts (const std::vector< int > & indices)
Get fiber tracts based on indices
Definition at line 110 of file itkFiberTracts.hxx.
References itk::CopyTrackvisHeader(), and itk::FiberTracts< TValue >::SelectByBallROI().
Referenced by itk::FiberTracts< TValue >::HasScalarName(), and itk::FiberTracts< TValue >::RemovePropertiesByName().
Member Data Documentation
template<typename TValue = double> FiberContainerPointer itk::FiberTracts< TValue >::m_Fibers = FiberContainerType::New() protected
Definition at line 117 of file itkFiberTracts.h.
Referenced by itk::FiberTracts< TValue >::GetFiber(), and itk::FiberTracts< TValue >::GetNumberOfFibers().
template<typename TValue = double> HeaderPointer itk::FiberTracts< TValue >::m_Header protected
Definition at line 115 of file itkFiberTracts.h.
Referenced by itk::FiberTracts< TValue >::HasPropertyName(), itk::FiberTracts< TValue >::HasScalarName(), and itk::FiberTracts< TValue >::PrintFibersHeader().
The documentation for this class was generated from the following files:
Modules/Tractography/include/itkFiberTracts.h
Modules/Tractography/include/itkFiberTracts.hxx