DMRITool: itk::FiberTractsReader Class Reference
itk::FiberTractsReader Class Reference
#include <itkFiberTractsReader.h>
Detailed Description
Definition at line 22 of file itkFiberTractsReader.h.
Public Types
typedef FiberTractsType::FiberPointer FiberPointer
typedef FiberTractsType::Pointer FiberTractsPointer
typedef FiberTracts< double > FiberTractsType
typedef FiberTractsType::FiberType FiberType
typedef SmartPointer< Self > Pointer
typedef FiberTractsReader Self
typedef FiberType::STDVectorType STDVectorType
typedef LightProcessObject Superclass
typedef FiberType::VertexType VertexType
Public Member Functions
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual const char * GetNameOfClass () const
FiberTractsPointer GetOutput () const
itkSetGetMacro (FileName, std::string)
void ReadTractsTCK ()
void ReadTractsTRK ()
void ReadTractsVTK ()
virtual void Update ()
Static Public Member Functions
static Pointer New ()
Protected Member Functions
FiberTractsReader ()
void PrintSelf (std::ostream &os, Indent indent) const ITK_OVERRIDE
~FiberTractsReader ()
Protected Attributes
FiberTractsPointer m_FiberTracts = FiberTractsType::New()
std::string m_FileName
Private Member Functions
FiberTractsReader (const Self &)
void operator= (const Self &)
Member Typedef Documentation
typedef FiberTractsType::FiberPointer itk::FiberTractsReader::FiberPointer
Definition at line 39 of file itkFiberTractsReader.h.
typedef FiberTractsType::Pointer itk::FiberTractsReader::FiberTractsPointer
Definition at line 37 of file itkFiberTractsReader.h.
typedef FiberTracts<double> itk::FiberTractsReader::FiberTractsType
Definition at line 34 of file itkFiberTractsReader.h.
typedef FiberTractsType::FiberType itk::FiberTractsReader::FiberType
Definition at line 38 of file itkFiberTractsReader.h.
typedef SmartPointer<Self> itk::FiberTractsReader::Pointer
Definition at line 28 of file itkFiberTractsReader.h.
typedef FiberTractsReader itk::FiberTractsReader::Self
Standard class typedefs.
Definition at line 26 of file itkFiberTractsReader.h.
typedef FiberType::STDVectorType itk::FiberTractsReader::STDVectorType
Definition at line 40 of file itkFiberTractsReader.h.
typedef LightProcessObject itk::FiberTractsReader::Superclass
Definition at line 27 of file itkFiberTractsReader.h.
typedef FiberType::VertexType itk::FiberTractsReader::VertexType
Definition at line 41 of file itkFiberTractsReader.h.
Constructor & Destructor Documentation
itk::FiberTractsReader::FiberTractsReader () inline protected
Definition at line 61 of file itkFiberTractsReader.h.
itk::FiberTractsReader::~FiberTractsReader () inline protected
Definition at line 62 of file itkFiberTractsReader.h.
itk::FiberTractsReader::FiberTractsReader (const Self &) private
Member Function Documentation
virtual::itk::LightObject::Pointer itk::FiberTractsReader::CreateAnother (void) const
virtual const char* itk::FiberTractsReader::GetNameOfClass () const virtual
Run-time type information (and related methods).
FiberTractsPointer itk::FiberTractsReader::GetOutput () const inline
Definition at line 55 of file itkFiberTractsReader.h.
itk::FiberTractsReader::itkSetGetMacro (FileName , std::string)
static Pointer itk::FiberTractsReader::New () static
Method for creation through the object factory.
Referenced by main(), and itk::ReadFibers().
void itk::FiberTractsReader::operator= (const Self &) private
void itk::FiberTractsReader::PrintSelf (std::ostream & os, Indent indent) const inline protected
Definition at line 64 of file itkFiberTractsReader.h.
References PrintVar.
void itk::FiberTractsReader::ReadTractsTCK ()
Definition at line 91 of file itkFiberTractsReader.hxx.
References utlGlobalException.
Referenced by Update().
void itk::FiberTractsReader::ReadTractsTRK ()
Definition at line 36 of file itkFiberTractsReader.hxx.
References itk::GetDimensionOfProperties(), itk::GetDimensionOfScalars(), m_FiberTracts, m_FileName, itk::Fiber< TValue >::New(), and itk::ReadTrackVisHeader().
Referenced by Update().
void itk::FiberTractsReader::ReadTractsVTK ()
Definition at line 96 of file itkFiberTractsReader.hxx.
References utlGlobalException.
Referenced by Update().
void itk::FiberTractsReader::Update () virtual
Does the real work.
Definition at line 20 of file itkFiberTractsReader.hxx.
References utl::GetFiberTractsFormat(), utl::IsFileExist(), m_FileName, ReadTractsTCK(), ReadTractsTRK(), ReadTractsVTK(), TRACTS_TCK, TRACTS_TRK, TRACTS_VTK, and utlGlobalException.
Member Data Documentation
FiberTractsPointer itk::FiberTractsReader::m_FiberTracts = FiberTractsType::New() protected
Definition at line 73 of file itkFiberTractsReader.h.
Referenced by ReadTractsTRK().
std::string itk::FiberTractsReader::m_FileName protected
Definition at line 71 of file itkFiberTractsReader.h.
Referenced by ReadTractsTRK(), and Update().
The documentation for this class was generated from the following files:
Modules/Tractography/include/itkFiberTractsReader.h
Modules/Tractography/include/itkFiberTractsReader.hxx