DMRITool: itk::DWIGenerator< TOutputImage, TScalarImage > Class Template Reference
itk::DWIGenerator< TOutputImage, TScalarImage > Class Template Reference
DWIProcessing
#include <itkDWIGenerator.h>
Detailed Description
template<class TOutputImage, class TScalarImage = Image<float,3>>
class itk::DWIGenerator< TOutputImage, TScalarImage >
Generate DWI data based on provided parameter file.
Author
Pew-Thian Yap, Jian Cheng
Definition at line 30 of file itkDWIGenerator.h.
Public Types
typedef Superclass::CylinderModelPointer CylinderModelPointer
typedef Superclass::CylinderModelType CylinderModelType
typedef Superclass::DiffusionParameterContainerType DiffusionParameterContainerType
typedef Superclass::DiffusionParameterValuesType DiffusionParameterValuesType
typedef Superclass::MatrixPointer MatrixPointer
typedef Superclass::MatrixType MatrixType
typedef Superclass::OutputImageDirectionType OutputImageDirectionType
typedef Superclass::OutputImageIndexType OutputImageIndexType
typedef Superclass::OutputImageInternalPixelType OutputImageInternalPixelType
typedef Superclass::OutputImagePixelType OutputImagePixelType
typedef Superclass::OutputImagePointer OutputImagePointer
typedef Superclass::OutputImagePointType OutputImagePointType
typedef Superclass::OutputImageRegionType OutputImageRegionType
typedef Superclass::OutputImageSizeType OutputImageSizeType
typedef Superclass::OutputImageSpacingType OutputImageSpacingType
typedef Superclass::OutputImageType OutputImageType
typedef SmartPointer< Self > Pointer
typedef Superclass::PrecisionType PrecisionType
typedef Superclass::ScalarImagePointer ScalarImagePointer
typedef Superclass::ScalarImageType ScalarImageType
typedef DWIGenerator Self
typedef Superclass::STDVectorPointer STDVectorPointer
typedef Superclass::STDVectorType STDVectorType
typedef DWIGeneratorBase< TOutputImage, TScalarImage > Superclass
Public Types inherited from itk::DWIGeneratorBase< TOutputImage, TScalarImage >
typedef CylinderModelType::Pointer CylinderModelPointer
typedef CylinderModelGenerator< double > CylinderModelType
typedef std::vector< DiffusionParameterValuesType > DiffusionParameterContainerType
typedef std::vector< double > DiffusionParameterValuesType
typedef utl_shared_ptr< MatrixType > MatrixPointer
typedef utl::NDArray< PrecisionType, 2 > MatrixType
enum ModelType {
SYMMETRICAL_TENSOR_IN_CARTESIAN_COORDS =0,
SYMMETRICAL_TENSOR_IN_SPHERICAL_COORDS,
TENSOR_IN_EULER_ANGLES,
CYLINDER_SPHERICAL_MODEL
}
typedef OutputImageType::DirectionType OutputImageDirectionType
typedef OutputImageType::IndexType OutputImageIndexType
typedef OutputImageType::InternalPixelType OutputImageInternalPixelType
typedef OutputImageType::PixelType OutputImagePixelType
typedef OutputImageType::Pointer OutputImagePointer
typedef OutputImageType::PointType OutputImagePointType
typedef OutputImageType::RegionType OutputImageRegionType
typedef OutputImageType::SizeType OutputImageSizeType
typedef OutputImageType::SpacingType OutputImageSpacingType
typedef TOutputImage OutputImageType
typedef SmartPointer< Self > Pointer
typedef double PrecisionType
typedef SamplingSchemeQSpaceType::Pointer SamplingSchemeQSpacePointer
typedef SamplingSchemeQSpace< double > SamplingSchemeQSpaceType
typedef SamplingSchemeRSpaceType::Pointer SamplingSchemeRSpacePointer
typedef SamplingScheme3D< double > SamplingSchemeRSpaceType
typedef ScalarImageType::Pointer ScalarImagePointer
typedef TScalarImage ScalarImageType
typedef DWIGeneratorBase Self
typedef utl_shared_ptr< STDVectorType > STDVectorPointer
typedef std::vector< PrecisionType > STDVectorType
typedef ImageSource< TOutputImage > Superclass
typedef utl::NDArray< PrecisionType, 1 > VectorType
Public Member Functions
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual STDVectorType GetBackgroundDiffusionParameterValues ()
virtual const char * GetFileName () const
virtual const char * GetNameOfClass () const
itkSetNDebugMacro (BackgroundDiffusionParameterValues, STDVectorType)
virtual void SetFileName (const char *_arg)
Public Member Functions inherited from itk::DWIGeneratorBase< TOutputImage, TScalarImage >
ScalarImageType * GetB0Image ()
virtual double GetB0Scale ()
OutputImageType * GetDWIImage ()
OutputImageType * GetEAPImage ()
virtual int GetMaxNumberOfPeaks ()
virtual ModelType GetModelType () const
ScalarImageType * GetMSDImage ()
virtual double GetNoiseSigma ()
unsigned int GetNumberOfQSpaceSamples () const
unsigned int GetNumberOfRSpaceSamples () const
OutputImageType * GetODFImage ()
virtual unsigned int GetODFOrder ()
virtual OutputImageSizeType GetOutputSize ()
OutputImageType * GetPeakImage ()
virtual PeakType GetPeakType ()
ScalarImageType * GetRTOImage ()
virtual double GetSNR ()
itkGetObjectMacro (SamplingSchemeQSpace, SamplingSchemeQSpaceType)
itkGetObjectMacro (SamplingSchemeRSpace, SamplingSchemeRSpaceType)
itkGetObjectMacro (CylinderModel, CylinderModelType)
itkSetGetBooleanMacro (IsOutputDWI)
itkSetGetBooleanMacro (IsOutputEAP)
itkSetGetBooleanMacro (IsOutputODF)
itkSetGetBooleanMacro (IsOutputRTO)
itkSetGetBooleanMacro (IsOutputMSD)
virtual void SetB0Scale (double _arg)
virtual void SetCylinderModel (CylinderModelType *_arg)
virtual void SetMaxNumberOfPeaks (int _arg)
virtual void SetModelType (const ModelType _arg)
virtual void SetNoiseSigma (double _arg)
virtual void SetODFOrder (unsigned int _arg)
virtual void SetOutputSize (OutputImageSizeType _arg)
virtual void SetPeakType (PeakType _arg)
virtual void SetSamplingSchemeQSpace (SamplingSchemeQSpaceType *_arg)
virtual void SetSamplingSchemeRSpace (SamplingSchemeRSpaceType *_arg)
virtual void SetSNR (double _arg)
Static Public Member Functions
static Pointer New ()
Static Public Attributes
static const unsigned int OutputImageDimension = OutputImageType::ImageDimension
Static Public Attributes inherited from itk::DWIGeneratorBase< TOutputImage, TScalarImage >
static const unsigned int OutputImageDimension = OutputImageType::ImageDimension
Protected Member Functions
DWIGenerator ()
void GenerateData ()
LightObject::Pointer InternalClone () const ITK_OVERRIDE
void PrintSelf (std::ostream &os, Indent indent) const ITK_OVERRIDE
~DWIGenerator ()
Protected Member Functions inherited from itk::DWIGeneratorBase< TOutputImage, TScalarImage >
virtual void AllocateOutputs () ITK_OVERRIDE
DWIGeneratorBase ()
virtual void Initialization ()
LightObject::Pointer InternalClone () const ITK_OVERRIDE
void PrintSelf (std::ostream &os, Indent indent) const ITK_OVERRIDE
~DWIGeneratorBase ()
Protected Attributes
STDVectorType m_BackgroundDiffusionParameterValues
std::string m_FileName
Protected Attributes inherited from itk::DWIGeneratorBase< TOutputImage, TScalarImage >
double m_B0Scale
CylinderModelPointer m_CylinderModel
bool m_IsOutputDWI
bool m_IsOutputEAP
bool m_IsOutputMSD
bool m_IsOutputODF
bool m_IsOutputRTO
int m_MaxNumberOfPeaks
ModelType m_ModelType
double m_NoiseSigma
unsigned int m_ODFOrder
OutputImageDirectionType m_OutputDirection
OutputImagePointType m_OutputOrigin
OutputImageSizeType m_OutputSize
OutputImageSpacingType m_OutputSpacing
PeakType m_PeakType
SamplingSchemeQSpacePointer m_SamplingSchemeQSpace
SamplingSchemeRSpacePointer m_SamplingSchemeRSpace
double m_SNR
Private Member Functions
DWIGenerator (const Self &)
void operator= (const Self &)
Member Typedef Documentation
template<class TOutputImage , class TScalarImage = Image<float,3>> typedef Superclass::CylinderModelPointer itk::DWIGenerator< TOutputImage, TScalarImage >::CylinderModelPointer
Definition at line 75 of file itkDWIGenerator.h.
template<class TOutputImage , class TScalarImage = Image<float,3>> typedef Superclass::CylinderModelType itk::DWIGenerator< TOutputImage, TScalarImage >::CylinderModelType
Definition at line 74 of file itkDWIGenerator.h.
template<class TOutputImage , class TScalarImage = Image<float,3>> typedef Superclass::DiffusionParameterContainerType itk::DWIGenerator< TOutputImage, TScalarImage >::DiffusionParameterContainerType
Definition at line 72 of file itkDWIGenerator.h.
template<class TOutputImage , class TScalarImage = Image<float,3>> typedef Superclass::DiffusionParameterValuesType itk::DWIGenerator< TOutputImage, TScalarImage >::DiffusionParameterValuesType
Some convenient typedefs for diffusion parameters.
Definition at line 71 of file itkDWIGenerator.h.
template<class TOutputImage , class TScalarImage = Image<float,3>> typedef Superclass::MatrixPointer itk::DWIGenerator< TOutputImage, TScalarImage >::MatrixPointer
Definition at line 66 of file itkDWIGenerator.h.
template<class TOutputImage , class TScalarImage = Image<float,3>> typedef Superclass::MatrixType itk::DWIGenerator< TOutputImage, TScalarImage >::MatrixType
Definition at line 65 of file itkDWIGenerator.h.
template<class TOutputImage , class TScalarImage = Image<float,3>> typedef Superclass::OutputImageDirectionType itk::DWIGenerator< TOutputImage, TScalarImage >::OutputImageDirectionType
Definition at line 51 of file itkDWIGenerator.h.
template<class TOutputImage , class TScalarImage = Image<float,3>> typedef Superclass::OutputImageIndexType itk::DWIGenerator< TOutputImage, TScalarImage >::OutputImageIndexType
Definition at line 49 of file itkDWIGenerator.h.
template<class TOutputImage , class TScalarImage = Image<float,3>> typedef Superclass::OutputImageInternalPixelType itk::DWIGenerator< TOutputImage, TScalarImage >::OutputImageInternalPixelType
Definition at line 54 of file itkDWIGenerator.h.
template<class TOutputImage , class TScalarImage = Image<float,3>> typedef Superclass::OutputImagePixelType itk::DWIGenerator< TOutputImage, TScalarImage >::OutputImagePixelType
Definition at line 53 of file itkDWIGenerator.h.
template<class TOutputImage , class TScalarImage = Image<float,3>> typedef Superclass::OutputImagePointer itk::DWIGenerator< TOutputImage, TScalarImage >::OutputImagePointer
Definition at line 46 of file itkDWIGenerator.h.
template<class TOutputImage , class TScalarImage = Image<float,3>> typedef Superclass::OutputImagePointType itk::DWIGenerator< TOutputImage, TScalarImage >::OutputImagePointType
Definition at line 50 of file itkDWIGenerator.h.
template<class TOutputImage , class TScalarImage = Image<float,3>> typedef Superclass::OutputImageRegionType itk::DWIGenerator< TOutputImage, TScalarImage >::OutputImageRegionType
Definition at line 52 of file itkDWIGenerator.h.
template<class TOutputImage , class TScalarImage = Image<float,3>> typedef Superclass::OutputImageSizeType itk::DWIGenerator< TOutputImage, TScalarImage >::OutputImageSizeType
Definition at line 47 of file itkDWIGenerator.h.
template<class TOutputImage , class TScalarImage = Image<float,3>> typedef Superclass::OutputImageSpacingType itk::DWIGenerator< TOutputImage, TScalarImage >::OutputImageSpacingType
Definition at line 48 of file itkDWIGenerator.h.
template<class TOutputImage , class TScalarImage = Image<float,3>> typedef Superclass::OutputImageType itk::DWIGenerator< TOutputImage, TScalarImage >::OutputImageType
Some convenient typedefs.
Definition at line 42 of file itkDWIGenerator.h.
template<class TOutputImage , class TScalarImage = Image<float,3>> typedef SmartPointer<Self> itk::DWIGenerator< TOutputImage, TScalarImage >::Pointer
Definition at line 36 of file itkDWIGenerator.h.
template<class TOutputImage , class TScalarImage = Image<float,3>> typedef Superclass::PrecisionType itk::DWIGenerator< TOutputImage, TScalarImage >::PrecisionType
Orientation Matrice Type
Definition at line 64 of file itkDWIGenerator.h.
template<class TOutputImage , class TScalarImage = Image<float,3>> typedef Superclass::ScalarImagePointer itk::DWIGenerator< TOutputImage, TScalarImage >::ScalarImagePointer
Definition at line 61 of file itkDWIGenerator.h.
template<class TOutputImage , class TScalarImage = Image<float,3>> typedef Superclass::ScalarImageType itk::DWIGenerator< TOutputImage, TScalarImage >::ScalarImageType
B0 Image
Definition at line 60 of file itkDWIGenerator.h.
template<class TOutputImage , class TScalarImage = Image<float,3>> typedef DWIGenerator itk::DWIGenerator< TOutputImage, TScalarImage >::Self
Standard class typedefs.
Definition at line 34 of file itkDWIGenerator.h.
template<class TOutputImage , class TScalarImage = Image<float,3>> typedef Superclass::STDVectorPointer itk::DWIGenerator< TOutputImage, TScalarImage >::STDVectorPointer
Definition at line 68 of file itkDWIGenerator.h.
template<class TOutputImage , class TScalarImage = Image<float,3>> typedef Superclass::STDVectorType itk::DWIGenerator< TOutputImage, TScalarImage >::STDVectorType
Definition at line 67 of file itkDWIGenerator.h.
template<class TOutputImage , class TScalarImage = Image<float,3>> typedef DWIGeneratorBase<TOutputImage, TScalarImage> itk::DWIGenerator< TOutputImage, TScalarImage >::Superclass
Definition at line 35 of file itkDWIGenerator.h.
Constructor & Destructor Documentation
template<class TOutputImage , class TScalarImage > itk::DWIGenerator< TOutputImage, TScalarImage >::DWIGenerator () protected
Definition at line 31 of file itkDWIGenerator.hxx.
References itk::DWIGenerator< TOutputImage, TScalarImage >::~DWIGenerator().
template<class TOutputImage , class TScalarImage > itk::DWIGenerator< TOutputImage, TScalarImage >::~DWIGenerator () protected
Definition at line 37 of file itkDWIGenerator.hxx.
References itk::DWIGenerator< TOutputImage, TScalarImage >::PrintSelf().
Referenced by itk::DWIGenerator< TOutputImage, TScalarImage >::DWIGenerator().
template<class TOutputImage , class TScalarImage = Image<float,3>> itk::DWIGenerator< TOutputImage, TScalarImage >::DWIGenerator (const Self &) private
Member Function Documentation
template<class TOutputImage , class TScalarImage = Image<float,3>> virtual::itk::LightObject::Pointer itk::DWIGenerator< TOutputImage, TScalarImage >::CreateAnother (void) const
template<class TOutputImage , class TScalarImage > void itk::DWIGenerator< TOutputImage, TScalarImage >::GenerateData (void) protected virtual
Does the real work.
Implements itk::DWIGeneratorBase< TOutputImage, TScalarImage >.
Definition at line 69 of file itkDWIGenerator.hxx.
References itk::PeakContainerHelper::GetDimension(), itk::DiffusionTensor< TPrecision >::GetDWISamples(), itk::DiffusionTensor< TPrecision >::GetEAPSamples(), itk::DiffusionTensor< TPrecision >::GetMeanSquaredDisplacement(), itk::DiffusionTensor< TPrecision >::GetODFSamples(), itk::DiffusionTensor< TPrecision >::GetReturnToOrigin(), utl::IsFileExist(), utl::IsInt(), itk::NXYZ, itk::NXYZV, utl::PrintVector(), utl::ReadLines(), itk::DiffusionTensor< TPrecision >::Rotate(), itk::DiffusionTensor< TPrecision >::SetEigenValues(), spams::sort(), utl::spherical2Cartesian(), utlException, utlGlobalException, utlSAGlobalException, utlShowPosition, and itk::XYZV.
Referenced by itk::DWIGenerator< TOutputImage, TScalarImage >::InternalClone().
template<class TOutputImage , class TScalarImage = Image<float,3>> virtual STDVectorType itk::DWIGenerator< TOutputImage, TScalarImage >::GetBackgroundDiffusionParameterValues () virtual
template<class TOutputImage , class TScalarImage = Image<float,3>> virtual const char* itk::DWIGenerator< TOutputImage, TScalarImage >::GetFileName () const virtual
template<class TOutputImage , class TScalarImage = Image<float,3>> virtual const char* itk::DWIGenerator< TOutputImage, TScalarImage >::GetNameOfClass () const virtual
Run-time type information (and related methods).
Reimplemented from itk::DWIGeneratorBase< TOutputImage, TScalarImage >.
template<class TOutputImage , class TScalarImage > LightObject::Pointer itk::DWIGenerator< TOutputImage, TScalarImage >::InternalClone () const protected
Definition at line 52 of file itkDWIGenerator.hxx.
References itk::DWIGenerator< TOutputImage, TScalarImage >::GenerateData().
Referenced by itk::DWIGenerator< TOutputImage, TScalarImage >::PrintSelf().
template<class TOutputImage , class TScalarImage = Image<float,3>> itk::DWIGenerator< TOutputImage, TScalarImage >::itkSetNDebugMacro (BackgroundDiffusionParameterValues , STDVectorType)
template<class TOutputImage , class TScalarImage = Image<float,3>> static Pointer itk::DWIGenerator< TOutputImage, TScalarImage >::New () static
Method for creation through the object factory.
template<class TOutputImage , class TScalarImage = Image<float,3>> void itk::DWIGenerator< TOutputImage, TScalarImage >::operator= (const Self &) private
template<class TOutputImage , class TScalarImage > void itk::DWIGenerator< TOutputImage, TScalarImage >::PrintSelf (std::ostream & os, Indent indent) const protected
Definition at line 43 of file itkDWIGenerator.hxx.
References itk::DWIGenerator< TOutputImage, TScalarImage >::InternalClone().
Referenced by itk::DWIGenerator< TOutputImage, TScalarImage >::~DWIGenerator().
template<class TOutputImage , class TScalarImage = Image<float,3>> virtual void itk::DWIGenerator< TOutputImage, TScalarImage >::SetFileName (const char * _arg) virtual
Specify the files to read.
Member Data Documentation
template<class TOutputImage , class TScalarImage = Image<float,3>> STDVectorType itk::DWIGenerator< TOutputImage, TScalarImage >::m_BackgroundDiffusionParameterValues protected
Definition at line 97 of file itkDWIGenerator.h.
template<class TOutputImage , class TScalarImage = Image<float,3>> std::string itk::DWIGenerator< TOutputImage, TScalarImage >::m_FileName protected
Definition at line 95 of file itkDWIGenerator.h.
template<class TOutputImage , class TScalarImage = Image<float,3>> const unsigned int itk::DWIGenerator< TOutputImage, TScalarImage >::OutputImageDimension = OutputImageType::ImageDimension static
Output image dimension
Definition at line 57 of file itkDWIGenerator.h.
The documentation for this class was generated from the following files:
Modules/DWIProcessing/include/itkDWIGenerator.h
Modules/DWIProcessing/include/itkDWIGenerator.hxx