DMRITool: itk::SphericalPolarFourierEstimationImageFilter< TInputImage, TOutputImage > Class Template Reference
itk::SphericalPolarFourierEstimationImageFilter< TInputImage, TOutputImage > Class Template Reference
#include <itkSphericalPolarFourierEstimationImageFilter.h>
Detailed Description
template<class TInputImage, class TOutputImage>
class itk::SphericalPolarFourierEstimationImageFilter< TInputImage, TOutputImage >
estimate the coeffcients of generalized Spherical Polar Fourier basis which can be separated into differe radial basis and sphercial basis.
Author
Jian Cheng (JC), jian..nosp@m.chen.nosp@m.g.198.nosp@m.3@gm.nosp@m.ail.c.nosp@m.om
Definition at line 40 of file itkSphericalPolarFourierEstimationImageFilter.h.
Public Types
typedef SmartPointer< const Self > ConstPointer
enum EstimationType {
LS =0,
L1_2,
L1_DL
}
typedef L1RegularizedLeastSquaresFISTASolver< double > L1FISTASolverType
enum L1SolverType {
FISTA_LS =0,
SPAMS
}
typedef SpamsWeightedLassoSolver< double > L1SpamsSolverType
typedef L2RegularizedLeastSquaresSolver< double > L2SolverType
typedef Superclass::MatrixPointer MatrixPointer
typedef Superclass::MatrixType MatrixType
typedef SmartPointer< Self > Pointer
typedef SphericalPolarFourierEstimationImageFilter Self
typedef Superclass::STDVectorPointer STDVectorPointer
typedef Superclass::STDVectorType STDVectorType
typedef DiffusionModelEstimationInSphericalCoordinateImageFilter< TInputImage, TOutputImage > Superclass
typedef Superclass::VectorPointer VectorPointer
typedef Superclass::VectorType VectorType
Public Types inherited from itk::DiffusionModelEstimationInSphericalCoordinateImageFilter< TInputImage, TOutputImage >
typedef SmartPointer< const Self > ConstPointer
typedef Superclass::InputImageConstPointer InputImageConstPointer
typedef Superclass::InputImageIndexType InputImageIndexType
typedef Superclass::InputImagePixelType InputImagePixelType
typedef Superclass::InputImagePointer InputImagePointer
typedef Superclass::InputImageRegionType InputImageRegionType
typedef Superclass::InputImageSizeType InputImageSizeType
typedef Superclass::InputImageSpacingType InputImageSpacingType
typedef Superclass::InputImageType InputImageType
typedef Superclass::MaskImageType MaskImageType
typedef Superclass::MatrixPointer MatrixPointer
typedef Superclass::MatrixType MatrixType
typedef Superclass::OutputImageIndexType OutputImageIndexType
typedef Superclass::OutputImagePixelType OutputImagePixelType
typedef Superclass::OutputImagePointer OutputImagePointer
typedef Superclass::OutputImageRegionType OutputImageRegionType
typedef Superclass::OutputImageSizeType OutputImageSizeType
typedef Superclass::OutputImageSpacingType OutputImageSpacingType
typedef Superclass::OutputImageType OutputImageType
typedef SmartPointer< Self > Pointer
typedef DiffusionModelEstimationInSphericalCoordinateImageFilter Self
typedef Superclass::STDVectorPointer STDVectorPointer
typedef Superclass::STDVectorType STDVectorType
typedef DiffusionModelEstimationImageFilter< TInputImage, TOutputImage > Superclass
typedef Superclass::VectorPointer VectorPointer
typedef Superclass::VectorType VectorType
Public Types inherited from itk::DiffusionModelEstimationImageFilter< TInputImage, TOutputImage >
typedef SmartPointer< const Self > ConstPointer
typedef utl_shared_ptr< MatrixType > MatrixPointer
typedef utl::NDArray< double, 2 > MatrixType
typedef SmartPointer< Self > Pointer
typedef SamplingSchemeQSpaceType::Pointer SamplingSchemeQSpacePointer
typedef SamplingSchemeQSpace< double > SamplingSchemeQSpaceType
typedef SamplingSchemeRSpaceType::Pointer SamplingSchemeRSpacePointer
typedef SamplingScheme3D< double > SamplingSchemeRSpaceType
typedef DiffusionModelEstimationImageFilter Self
typedef utl_shared_ptr< STDVectorType > STDVectorPointer
typedef std::vector< double > STDVectorType
typedef MaskedImageToImageFilter< TInputImage, TOutputImage > Superclass
typedef utl_shared_ptr< VectorType > VectorPointer
typedef utl::NDArray< double, 1 > VectorType
Public Types inherited from itk::MaskedImageToImageFilter< TInputImage, TOutputImage >
typedef SmartPointer< const Self > ConstPointer
typedef InputImageType::ConstPointer InputImageConstPointer
typedef InputImageType::IndexType InputImageIndexType
typedef InputImageType::PixelType InputImagePixelType
typedef InputImageType::Pointer InputImagePointer
typedef InputImageType::RegionType InputImageRegionType
typedef InputImageType::SizeType InputImageSizeType
typedef InputImageType::SpacingType InputImageSpacingType
typedef TInputImage InputImageType
typedef LoggerType::Pointer LoggerPointer
typedef ThreadLogger LoggerType
typedef utl_shared_ptr< LoggerVectorType > LoggerVectorPointer
typedef std::vector< LoggerPointer > LoggerVectorType
typedef MaskImageType::Pointer MaskImagePointer
typedef Image< double, 3 > MaskImageType
typedef OutputImageType::IndexType OutputImageIndexType
typedef OutputImageType::PixelType OutputImagePixelType
typedef OutputImageType::Pointer OutputImagePointer
typedef OutputImageType::RegionType OutputImageRegionType
typedef OutputImageType::SizeType OutputImageSizeType
typedef OutputImageType::SpacingType OutputImageSpacingType
typedef TOutputImage OutputImageType
typedef SmartPointer< Self > Pointer
typedef MaskedImageToImageFilter Self
typedef ImageToImageFilter< TInputImage, TOutputImage > Superclass
Public Member Functions
virtual double ComputeScale (const bool setScale=true)
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual std::vector< int > DimToRank (const int dimm) const
virtual double GetB0Weight ()
virtual MatrixPointer GetBasisCombinationMatrix ()
virtual VectorPointer GetBasisEnergyDL ()
virtual double GetBasisEnergyPowerDL ()
virtual double GetBasisScale ()
virtual EstimationType GetEstimationType ()
virtual int GetIndexJ (const int n, const int l, const int m) const
virtual std::vector< int > GetIndexNLM (const int index) const
virtual bool GetIsOriginalBasis ()
virtual L1SolverType GetL1SolverType ()
virtual double GetLambdaL1 ()
virtual double GetLambdaRadial ()
virtual double GetLambdaSpherical ()
virtual const ScalarImageType * GetMDImage () const
virtual const char * GetNameOfClass () const
virtual VectorPointer GetRegularizationWeight ()
virtual const ScalarImageType * GetScaleImage () const
bool IsAdaptiveScale () const
virtual void IsOriginalBasisOff ()
virtual void IsOriginalBasisOn ()
itkGetObjectMacro (MDImage, ScalarImageType)
itkGetObjectMacro (ScaleImage, ScalarImageType)
itkSetGetBooleanMacro (IsAnalyticalB0)
itkTypedefMaskedImageToImageMacro (Superclass)
virtual int RankToDim (const bool is_radial=false, const int radialRank=-1, const int shRank=-1) const
virtual void SetB0Weight (double _arg)
virtual void SetBasisCombinationMatrix (MatrixPointer _arg)
virtual void SetBasisEnergyDL (VectorPointer _arg)
virtual void SetBasisEnergyPowerDL (double _arg)
virtual void SetBasisScale (const double scale)
virtual void SetEstimationType (EstimationType _arg)
virtual void SetIsOriginalBasis (bool _arg)
virtual void SetL1FISTASolver (typename L1FISTASolverType::Pointer _arg)
virtual void SetL1SolverType (L1SolverType _arg)
virtual void SetL1SpamsSolver (typename L1SpamsSolverType::Pointer _arg)
virtual void SetLambdaL1 (double _arg)
virtual void SetLambdaRadial (double _arg)
virtual void SetLambdaSpherical (double _arg)
virtual void SetMDImage (ScalarImageType *_arg)
virtual void SetScaleImage (ScalarImageType *_arg)
Public Member Functions inherited from itk::DiffusionModelEstimationInSphericalCoordinateImageFilter< TInputImage, TOutputImage >
virtual void ComputeRadialMatrix ()
virtual void ComputeSHMatrix ()
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual MatrixPointer GetBasisRadialMatrix ()
virtual MatrixPointer GetBasisSHMatrix ()
virtual int GetRadialRank ()
virtual int GetSHRank ()
virtual void SetRadialRank (int _arg)
virtual void SetSHRank (int _arg)
Public Member Functions inherited from itk::DiffusionModelEstimationImageFilter< TInputImage, TOutputImage >
virtual void ComputeBasisMatrix ()
virtual void ComputeRegularizationWeight ()
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual MatrixPointer GetBasisMatrix ()
virtual double GetMD0 ()
itkGetObjectMacro (SamplingSchemeQSpace, SamplingSchemeQSpaceType)
itkTypedefMaskedImageToImageMacro (Superclass)
virtual void SetMD0 (double _arg)
virtual void SetSamplingSchemeQSpace (SamplingSchemeQSpaceType *_arg)
Public Member Functions inherited from itk::MaskedImageToImageFilter< TInputImage, TOutputImage >
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual const LoggerType * GetLogger () const
virtual const MaskImageType * GetMaskImage () const
bool IsMaskUsed ()
itkGetObjectMacro (MaskImage, MaskImageType)
itkGetObjectMacro (Logger, LoggerType)
itkSetGetMacro (LogLevel, int)
virtual void SetLogger (LoggerType *_arg)
virtual void SetMaskImage (MaskImageType *_arg)
void SetMaskImage (const std::string &file)
Static Public Member Functions
static Pointer New ()
Static Public Member Functions inherited from itk::DiffusionModelEstimationInSphericalCoordinateImageFilter< TInputImage, TOutputImage >
static Pointer New ()
Static Public Member Functions inherited from itk::DiffusionModelEstimationImageFilter< TInputImage, TOutputImage >
static Pointer New ()
Static Public Member Functions inherited from itk::MaskedImageToImageFilter< TInputImage, TOutputImage >
static Pointer New ()
Protected Member Functions
void BeforeThreadedGenerateData () ITK_OVERRIDE
void GenerateOutputInformation () ITK_OVERRIDE
void InitializeThreadedLibraries () ITK_OVERRIDE
LightObject::Pointer InternalClone () const ITK_OVERRIDE
void PrintSelf (std::ostream &os, Indent indent) const ITK_OVERRIDE
SphericalPolarFourierEstimationImageFilter ()
void VerifyInputParameters () const ITK_OVERRIDE
virtual ~SphericalPolarFourierEstimationImageFilter ()
Protected Member Functions inherited from itk::DiffusionModelEstimationInSphericalCoordinateImageFilter< TInputImage, TOutputImage >
DiffusionModelEstimationInSphericalCoordinateImageFilter ()
LightObject::Pointer InternalClone () const ITK_OVERRIDE
virtual ~DiffusionModelEstimationInSphericalCoordinateImageFilter ()
Protected Member Functions inherited from itk::DiffusionModelEstimationImageFilter< TInputImage, TOutputImage >
DiffusionModelEstimationImageFilter ()
LightObject::Pointer InternalClone () const ITK_OVERRIDE
virtual ~DiffusionModelEstimationImageFilter ()
Protected Member Functions inherited from itk::MaskedImageToImageFilter< TInputImage, TOutputImage >
void CreateLoggerVector ()
LightObject::Pointer InternalClone () const ITK_OVERRIDE
MaskedImageToImageFilter ()
std::string ThreadIDToString () const
virtual void VerifyMaskInformation () const
void WriteLogger (const std::string &str, const LoggerBase::PriorityLevelType level=LoggerBase::DEBUG) const
virtual ~MaskedImageToImageFilter ()
Protected Attributes
double m_B0Weight
MatrixPointer m_BasisCombinationMatrix
VectorPointer m_BasisEnergyDL
double m_BasisEnergyPowerDL
MatrixPointer m_BasisMatrixForB0
double m_BasisScale
EstimationType m_EstimationType
bool m_IsAnalyticalB0
bool m_IsOriginalBasis
L1FISTASolverType::Pointer m_L1FISTASolver
L1SolverType m_L1SolverType
L1SpamsSolverType::Pointer m_L1SpamsSolver
L2SolverType::Pointer m_L2Solver
double m_LambdaL1
double m_LambdaL2
double m_LambdaRadial
double m_LambdaSpherical
ScalarImageType::Pointer m_MDImage
ScalarImageType::Pointer m_ScaleImage
Protected Attributes inherited from itk::DiffusionModelEstimationInSphericalCoordinateImageFilter< TInputImage, TOutputImage >
MatrixPointer m_BasisRadialMatrix
MatrixPointer m_BasisSHMatrix
int m_RadialRank
int m_SHRank
Protected Attributes inherited from itk::DiffusionModelEstimationImageFilter< TInputImage, TOutputImage >
MatrixPointer m_BasisMatrix
double m_MD0
VectorPointer m_RegularizationWeight
SamplingSchemeQSpacePointer m_SamplingSchemeQSpace
Protected Attributes inherited from itk::MaskedImageToImageFilter< TInputImage, TOutputImage >
LoggerPointer m_Logger
LoggerVectorPointer m_LoggerVector
int m_LogLevel
MaskImagePointer m_MaskImage
int m_ThreadID
Private Member Functions
void operator= (const Self &)
SphericalPolarFourierEstimationImageFilter (const Self &)
Additional Inherited Members
Static Public Attributes inherited from itk::MaskedImageToImageFilter< TInputImage, TOutputImage >
static const unsigned int InputImageDimension
static const unsigned int OutputImageDimension
Member Typedef Documentation
template<class TInputImage , class TOutputImage > typedef SmartPointer<const Self> itk::SphericalPolarFourierEstimationImageFilter< TInputImage, TOutputImage >::ConstPointer
Definition at line 48 of file itkSphericalPolarFourierEstimationImageFilter.h.
template<class TInputImage , class TOutputImage > typedef L1RegularizedLeastSquaresFISTASolver<double> itk::SphericalPolarFourierEstimationImageFilter< TInputImage, TOutputImage >::L1FISTASolverType
Definition at line 84 of file itkSphericalPolarFourierEstimationImageFilter.h.
template<class TInputImage , class TOutputImage > typedef SpamsWeightedLassoSolver<double> itk::SphericalPolarFourierEstimationImageFilter< TInputImage, TOutputImage >::L1SpamsSolverType
Definition at line 85 of file itkSphericalPolarFourierEstimationImageFilter.h.
template<class TInputImage , class TOutputImage > typedef L2RegularizedLeastSquaresSolver<double> itk::SphericalPolarFourierEstimationImageFilter< TInputImage, TOutputImage >::L2SolverType
Definition at line 83 of file itkSphericalPolarFourierEstimationImageFilter.h.
template<class TInputImage , class TOutputImage > typedef Superclass::MatrixPointer itk::SphericalPolarFourierEstimationImageFilter< TInputImage, TOutputImage >::MatrixPointer
Definition at line 61 of file itkSphericalPolarFourierEstimationImageFilter.h.
template<class TInputImage , class TOutputImage > typedef Superclass::MatrixType itk::SphericalPolarFourierEstimationImageFilter< TInputImage, TOutputImage >::MatrixType
Definition at line 59 of file itkSphericalPolarFourierEstimationImageFilter.h.
template<class TInputImage , class TOutputImage > typedef SmartPointer<Self> itk::SphericalPolarFourierEstimationImageFilter< TInputImage, TOutputImage >::Pointer
Definition at line 47 of file itkSphericalPolarFourierEstimationImageFilter.h.
template<class TInputImage , class TOutputImage > typedef SphericalPolarFourierEstimationImageFilter itk::SphericalPolarFourierEstimationImageFilter< TInputImage, TOutputImage >::Self
Standard class typedefs.
Definition at line 45 of file itkSphericalPolarFourierEstimationImageFilter.h.
template<class TInputImage , class TOutputImage > typedef Superclass::STDVectorPointer itk::SphericalPolarFourierEstimationImageFilter< TInputImage, TOutputImage >::STDVectorPointer
Definition at line 64 of file itkSphericalPolarFourierEstimationImageFilter.h.
template<class TInputImage , class TOutputImage > typedef Superclass::STDVectorType itk::SphericalPolarFourierEstimationImageFilter< TInputImage, TOutputImage >::STDVectorType
Definition at line 63 of file itkSphericalPolarFourierEstimationImageFilter.h.
template<class TInputImage , class TOutputImage > typedef DiffusionModelEstimationInSphericalCoordinateImageFilter<TInputImage,TOutputImage> itk::SphericalPolarFourierEstimationImageFilter< TInputImage, TOutputImage >::Superclass
Definition at line 46 of file itkSphericalPolarFourierEstimationImageFilter.h.
template<class TInputImage , class TOutputImage > typedef Superclass::VectorPointer itk::SphericalPolarFourierEstimationImageFilter< TInputImage, TOutputImage >::VectorPointer
Definition at line 62 of file itkSphericalPolarFourierEstimationImageFilter.h.
template<class TInputImage , class TOutputImage > typedef Superclass::VectorType itk::SphericalPolarFourierEstimationImageFilter< TInputImage, TOutputImage >::VectorType
Definition at line 60 of file itkSphericalPolarFourierEstimationImageFilter.h.
Member Enumeration Documentation
template<class TInputImage , class TOutputImage > enum itk::SphericalPolarFourierEstimationImageFilter::EstimationType
Enumerator
LS
L1_2
L1_DL
Definition at line 66 of file itkSphericalPolarFourierEstimationImageFilter.h.
template<class TInputImage , class TOutputImage > enum itk::SphericalPolarFourierEstimationImageFilter::L1SolverType
Type of L1 solver:
Parameters
FISTA_LS FISTA with least square initialization
SPAMS weighted lasso in spams
Enumerator
FISTA_LS
SPAMS
Definition at line 77 of file itkSphericalPolarFourierEstimationImageFilter.h.
Constructor & Destructor Documentation
template<class TInputImage , class TOutputImage > itk::SphericalPolarFourierEstimationImageFilter< TInputImage, TOutputImage >::SphericalPolarFourierEstimationImageFilter () protected
Definition at line 29 of file itkSphericalPolarFourierEstimationImageFilter.hxx.
References itk::SphericalPolarFourierEstimationImageFilter< TInputImage, TOutputImage >::VerifyInputParameters().
template<class TInputImage , class TOutputImage > virtual itk::SphericalPolarFourierEstimationImageFilter< TInputImage, TOutputImage >::~SphericalPolarFourierEstimationImageFilter () inline protected virtual
Definition at line 161 of file itkSphericalPolarFourierEstimationImageFilter.h.
References utl::InitializeThreadedLibraries(), and ITK_OVERRIDE.
template<class TInputImage , class TOutputImage > itk::SphericalPolarFourierEstimationImageFilter< TInputImage, TOutputImage >::SphericalPolarFourierEstimationImageFilter (const Self &) private
Member Function Documentation
template<class TInputImage , class TOutputImage > void itk::SphericalPolarFourierEstimationImageFilter< TInputImage, TOutputImage >::BeforeThreadedGenerateData () protected
Definition at line 162 of file itkSphericalPolarFourierEstimationImageFilter.hxx.
References itk::SphericalPolarFourierEstimationImageFilter< TInputImage, TOutputImage >::InitializeThreadedLibraries(), itk::IsImageEmpty(), itkShowPositionThreadedLogger, utl::Print(), and utlGlobalException.
Referenced by itk::SphericalPolarFourierEstimationImageFilter< TInputImage, TOutputImage >::InternalClone().
template<class TInputImage , class TOutputImage > double itk::SphericalPolarFourierEstimationImageFilter< TInputImage, TOutputImage >::ComputeScale (const bool setScale = true) virtual
need to be overidden by subclasses
Reimplemented in itk::SphericalPolarFourierImageFilter< TInputImage, TOutputImage >, and itk::GeneralizedHighOrderTensorImageFilter< TInputImage, TOutputImage >.
Definition at line 87 of file itkSphericalPolarFourierEstimationImageFilter.hxx.
References itk::SphericalPolarFourierEstimationImageFilter< TInputImage, TOutputImage >::SetBasisScale().
Referenced by itk::SphericalPolarFourierEstimationImageFilter< TInputImage, TOutputImage >::GenerateOutputInformation().
template<class TInputImage , class TOutputImage > virtual::itk::LightObject::Pointer itk::SphericalPolarFourierEstimationImageFilter< TInputImage, TOutputImage >::CreateAnother (void) const
template<class TInputImage , class TOutputImage > virtual std::vector<int> itk::SphericalPolarFourierEstimationImageFilter< TInputImage, TOutputImage >::DimToRank (const int dimm) const inline virtual
from dimension to rank
Reimplemented in itk::SphericalPolarFourierImageFilter< TInputImage, TOutputImage >, and itk::GeneralizedHighOrderTensorImageFilter< TInputImage, TOutputImage >.
Definition at line 140 of file itkSphericalPolarFourierEstimationImageFilter.h.
template<class TInputImage , class TOutputImage > void itk::SphericalPolarFourierEstimationImageFilter< TInputImage, TOutputImage >::GenerateOutputInformation (void) protected
The filter produces an image which is a different size than its input image. As such, it needs to provide an implemenation for GenerateOutputInformation() which set the output information accordingly.
Definition at line 75 of file itkSphericalPolarFourierEstimationImageFilter.hxx.
References itk::SphericalPolarFourierEstimationImageFilter< TInputImage, TOutputImage >::ComputeScale(), and itkShowPositionThreadedLogger.
Referenced by itk::SphericalPolarFourierEstimationImageFilter< TInputImage, TOutputImage >::VerifyInputParameters().
template<class TInputImage , class TOutputImage > virtual double itk::SphericalPolarFourierEstimationImageFilter< TInputImage, TOutputImage >::GetB0Weight () virtual
template<class TInputImage , class TOutputImage > virtual MatrixPointer itk::SphericalPolarFourierEstimationImageFilter< TInputImage, TOutputImage >::GetBasisCombinationMatrix () virtual
template<class TInputImage , class TOutputImage > virtual VectorPointer itk::SphericalPolarFourierEstimationImageFilter< TInputImage, TOutputImage >::GetBasisEnergyDL () virtual
template<class TInputImage , class TOutputImage > virtual double itk::SphericalPolarFourierEstimationImageFilter< TInputImage, TOutputImage >::GetBasisEnergyPowerDL () virtual
template<class TInputImage , class TOutputImage > virtual double itk::SphericalPolarFourierEstimationImageFilter< TInputImage, TOutputImage >::GetBasisScale () virtual
template<class TInputImage , class TOutputImage > virtual EstimationType itk::SphericalPolarFourierEstimationImageFilter< TInputImage, TOutputImage >::GetEstimationType () virtual
template<class TInputImage , class TOutputImage > virtual int itk::SphericalPolarFourierEstimationImageFilter< TInputImage, TOutputImage >::GetIndexJ (const int n, const int l, const int m) const inline virtual
Reimplemented in itk::SphericalPolarFourierImageFilter< TInputImage, TOutputImage >.
Definition at line 148 of file itkSphericalPolarFourierEstimationImageFilter.h.
template<class TInputImage , class TOutputImage > virtual std::vector<int> itk::SphericalPolarFourierEstimationImageFilter< TInputImage, TOutputImage >::GetIndexNLM (const int index) const inline virtual
Reimplemented in itk::SphericalPolarFourierImageFilter< TInputImage, TOutputImage >.
Definition at line 146 of file itkSphericalPolarFourierEstimationImageFilter.h.
template<class TInputImage , class TOutputImage > virtual bool itk::SphericalPolarFourierEstimationImageFilter< TInputImage, TOutputImage >::GetIsOriginalBasis () virtual
template<class TInputImage , class TOutputImage > virtual L1SolverType itk::SphericalPolarFourierEstimationImageFilter< TInputImage, TOutputImage >::GetL1SolverType () virtual
template<class TInputImage , class TOutputImage > virtual double itk::SphericalPolarFourierEstimationImageFilter< TInputImage, TOutputImage >::GetLambdaL1 () virtual
template<class TInputImage , class TOutputImage > virtual double itk::SphericalPolarFourierEstimationImageFilter< TInputImage, TOutputImage >::GetLambdaRadial () virtual
template<class TInputImage , class TOutputImage > virtual double itk::SphericalPolarFourierEstimationImageFilter< TInputImage, TOutputImage >::GetLambdaSpherical () virtual
template<class TInputImage , class TOutputImage > virtual const ScalarImageType* itk::SphericalPolarFourierEstimationImageFilter< TInputImage, TOutputImage >::GetMDImage () const virtual
template<class TInputImage , class TOutputImage > virtual const char* itk::SphericalPolarFourierEstimationImageFilter< TInputImage, TOutputImage >::GetNameOfClass () const virtual
Run-time type information (and related methods)
Reimplemented from itk::DiffusionModelEstimationInSphericalCoordinateImageFilter< TInputImage, TOutputImage >.
Reimplemented in itk::SphericalPolarFourierImageFilter< TInputImage, TOutputImage >, and itk::GeneralizedHighOrderTensorImageFilter< TInputImage, TOutputImage >.
template<class TInputImage , class TOutputImage > virtual VectorPointer itk::SphericalPolarFourierEstimationImageFilter< TInputImage, TOutputImage >::GetRegularizationWeight () virtual
template<class TInputImage , class TOutputImage > virtual const ScalarImageType* itk::SphericalPolarFourierEstimationImageFilter< TInputImage, TOutputImage >::GetScaleImage () const virtual
template<class TInputImage , class TOutputImage > void itk::SphericalPolarFourierEstimationImageFilter< TInputImage, TOutputImage >::InitializeThreadedLibraries () protected virtual
Use single thread for MKL or openmp to avoid confliction with itk threader. Otherwise it has worse performance due to thread conflication (but correct solution).
Reimplemented from itk::MaskedImageToImageFilter< TInputImage, TOutputImage >.
Definition at line 213 of file itkSphericalPolarFourierEstimationImageFilter.hxx.
References utl::InitializeThreadedLibraries(), and itk::SphericalPolarFourierEstimationImageFilter< TInputImage, TOutputImage >::PrintSelf().
Referenced by itk::SphericalPolarFourierEstimationImageFilter< TInputImage, TOutputImage >::BeforeThreadedGenerateData().
template<class TInputImage , class TOutputImage > LightObject::Pointer itk::SphericalPolarFourierEstimationImageFilter< TInputImage, TOutputImage >::InternalClone () const protected
Definition at line 118 of file itkSphericalPolarFourierEstimationImageFilter.hxx.
References itk::SphericalPolarFourierEstimationImageFilter< TInputImage, TOutputImage >::BeforeThreadedGenerateData(), and itkShowPositionThreadedLogger.
Referenced by itk::SphericalPolarFourierEstimationImageFilter< TInputImage, TOutputImage >::SetBasisScale().
template<class TInputImage , class TOutputImage > bool itk::SphericalPolarFourierEstimationImageFilter< TInputImage, TOutputImage >::IsAdaptiveScale () const inline
Definition at line 154 of file itkSphericalPolarFourierEstimationImageFilter.h.
References itk::IsImageEmpty().
template<class TInputImage , class TOutputImage > virtual void itk::SphericalPolarFourierEstimationImageFilter< TInputImage, TOutputImage >::IsOriginalBasisOff () virtual
template<class TInputImage , class TOutputImage > virtual void itk::SphericalPolarFourierEstimationImageFilter< TInputImage, TOutputImage >::IsOriginalBasisOn () virtual
template<class TInputImage , class TOutputImage > itk::SphericalPolarFourierEstimationImageFilter< TInputImage, TOutputImage >::itkGetObjectMacro (MDImage , ScalarImageType)
template<class TInputImage , class TOutputImage > itk::SphericalPolarFourierEstimationImageFilter< TInputImage, TOutputImage >::itkGetObjectMacro (ScaleImage , ScalarImageType)
template<class TInputImage , class TOutputImage > itk::SphericalPolarFourierEstimationImageFilter< TInputImage, TOutputImage >::itkSetGetBooleanMacro (IsAnalyticalB0)
template<class TInputImage , class TOutputImage > itk::SphericalPolarFourierEstimationImageFilter< TInputImage, TOutputImage >::itkTypedefMaskedImageToImageMacro (Superclass)
Convenient Typedefs.
template<class TInputImage , class TOutputImage > static Pointer itk::SphericalPolarFourierEstimationImageFilter< TInputImage, TOutputImage >::New () static
Method for creation through the object factory.
template<class TInputImage , class TOutputImage > void itk::SphericalPolarFourierEstimationImageFilter< TInputImage, TOutputImage >::operator= (const Self &) private
template<class TInputImage , class TOutputImage > void itk::SphericalPolarFourierEstimationImageFilter< TInputImage, TOutputImage >::PrintSelf (std::ostream & os, Indent indent) const protected virtual
Reimplemented from itk::DiffusionModelEstimationInSphericalCoordinateImageFilter< TInputImage, TOutputImage >.
Reimplemented in itk::SphericalPolarFourierImageFilter< TInputImage, TOutputImage >.
Definition at line 232 of file itkSphericalPolarFourierEstimationImageFilter.hxx.
References utl::PrintUtlMatrix(), PrintVar2, and PrintVar4.
Referenced by itk::SphericalPolarFourierEstimationImageFilter< TInputImage, TOutputImage >::InitializeThreadedLibraries().
template<class TInputImage , class TOutputImage > virtual int itk::SphericalPolarFourierEstimationImageFilter< TInputImage, TOutputImage >::RankToDim (const bool is_radial = false, const int radialRank = -1, const int shRank = -1) const inline virtual
from rank to dimension
Reimplemented in itk::SphericalPolarFourierImageFilter< TInputImage, TOutputImage >, and itk::GeneralizedHighOrderTensorImageFilter< TInputImage, TOutputImage >.
Definition at line 143 of file itkSphericalPolarFourierEstimationImageFilter.h.
template<class TInputImage , class TOutputImage > virtual void itk::SphericalPolarFourierEstimationImageFilter< TInputImage, TOutputImage >::SetB0Weight (double _arg) virtual
template<class TInputImage , class TOutputImage > virtual void itk::SphericalPolarFourierEstimationImageFilter< TInputImage, TOutputImage >::SetBasisCombinationMatrix (MatrixPointer _arg) virtual
template<class TInputImage , class TOutputImage > virtual void itk::SphericalPolarFourierEstimationImageFilter< TInputImage, TOutputImage >::SetBasisEnergyDL (VectorPointer _arg) virtual
template<class TInputImage , class TOutputImage > virtual void itk::SphericalPolarFourierEstimationImageFilter< TInputImage, TOutputImage >::SetBasisEnergyPowerDL (double _arg) virtual
template<class TInputImage , class TOutputImage > void itk::SphericalPolarFourierEstimationImageFilter< TInputImage, TOutputImage >::SetBasisScale (const double scale) virtual
Reimplemented in itk::SphericalPolarFourierImageFilter< TInputImage, TOutputImage >.
Definition at line 96 of file itkSphericalPolarFourierEstimationImageFilter.hxx.
References itk::SphericalPolarFourierEstimationImageFilter< TInputImage, TOutputImage >::InternalClone(), and itkShowPositionThreadedLogger.
Referenced by itk::SphericalPolarFourierEstimationImageFilter< TInputImage, TOutputImage >::ComputeScale().
template<class TInputImage , class TOutputImage > virtual void itk::SphericalPolarFourierEstimationImageFilter< TInputImage, TOutputImage >::SetEstimationType (EstimationType _arg) virtual
template<class TInputImage , class TOutputImage > virtual void itk::SphericalPolarFourierEstimationImageFilter< TInputImage, TOutputImage >::SetIsOriginalBasis (bool _arg) virtual
template<class TInputImage , class TOutputImage > virtual void itk::SphericalPolarFourierEstimationImageFilter< TInputImage, TOutputImage >::SetL1FISTASolver (typename L1FISTASolverType::Pointer _arg) virtual
template<class TInputImage , class TOutputImage > virtual void itk::SphericalPolarFourierEstimationImageFilter< TInputImage, TOutputImage >::SetL1SolverType (L1SolverType _arg) virtual
template<class TInputImage , class TOutputImage > virtual void itk::SphericalPolarFourierEstimationImageFilter< TInputImage, TOutputImage >::SetL1SpamsSolver (typename L1SpamsSolverType::Pointer _arg) virtual
template<class TInputImage , class TOutputImage > virtual void itk::SphericalPolarFourierEstimationImageFilter< TInputImage, TOutputImage >::SetLambdaL1 (double _arg) virtual
template<class TInputImage , class TOutputImage > virtual void itk::SphericalPolarFourierEstimationImageFilter< TInputImage, TOutputImage >::SetLambdaRadial (double _arg) virtual
template<class TInputImage , class TOutputImage > virtual void itk::SphericalPolarFourierEstimationImageFilter< TInputImage, TOutputImage >::SetLambdaSpherical (double _arg) virtual
template<class TInputImage , class TOutputImage > virtual void itk::SphericalPolarFourierEstimationImageFilter< TInputImage, TOutputImage >::SetMDImage (ScalarImageType * _arg) virtual
Set/Get the MD image.
template<class TInputImage , class TOutputImage > virtual void itk::SphericalPolarFourierEstimationImageFilter< TInputImage, TOutputImage >::SetScaleImage (ScalarImageType * _arg) virtual
Set/Get the scale image, which is normally determined by MDImage.
template<class TInputImage , class TOutputImage > void itk::SphericalPolarFourierEstimationImageFilter< TInputImage, TOutputImage >::VerifyInputParameters () const protected virtual
Reimplemented from itk::DiffusionModelEstimationInSphericalCoordinateImageFilter< TInputImage, TOutputImage >.
Definition at line 61 of file itkSphericalPolarFourierEstimationImageFilter.hxx.
References itk::SphericalPolarFourierEstimationImageFilter< TInputImage, TOutputImage >::GenerateOutputInformation(), itk::IsImageEmpty(), itkShowPositionThreadedLogger, utlGlobalException, and itk::VerifyImageInformation().
Referenced by itk::SphericalPolarFourierEstimationImageFilter< TInputImage, TOutputImage >::SphericalPolarFourierEstimationImageFilter().
Member Data Documentation
template<class TInputImage , class TOutputImage > double itk::SphericalPolarFourierEstimationImageFilter< TInputImage, TOutputImage >::m_B0Weight protected
used for artificial samples for E(0)=1
Definition at line 201 of file itkSphericalPolarFourierEstimationImageFilter.h.
template<class TInputImage , class TOutputImage > MatrixPointer itk::SphericalPolarFourierEstimationImageFilter< TInputImage, TOutputImage >::m_BasisCombinationMatrix protected
used for learned basis (L1_DL is used)
Definition at line 192 of file itkSphericalPolarFourierEstimationImageFilter.h.
template<class TInputImage , class TOutputImage > VectorPointer itk::SphericalPolarFourierEstimationImageFilter< TInputImage, TOutputImage >::m_BasisEnergyDL protected
energy of samples in each atom of the learned basis. (L1_DL is used)
Definition at line 194 of file itkSphericalPolarFourierEstimationImageFilter.h.
template<class TInputImage , class TOutputImage > double itk::SphericalPolarFourierEstimationImageFilter< TInputImage, TOutputImage >::m_BasisEnergyPowerDL protected
power of the energy used to calculate m_RegularizationWeight. (L1_DL is used)
Definition at line 196 of file itkSphericalPolarFourierEstimationImageFilter.h.
template<class TInputImage , class TOutputImage > MatrixPointer itk::SphericalPolarFourierEstimationImageFilter< TInputImage, TOutputImage >::m_BasisMatrixForB0 protected
basis matrix for artificial b0 shell
Definition at line 203 of file itkSphericalPolarFourierEstimationImageFilter.h.
template<class TInputImage , class TOutputImage > double itk::SphericalPolarFourierEstimationImageFilter< TInputImage, TOutputImage >::m_BasisScale protected
scale for radial basis
Definition at line 181 of file itkSphericalPolarFourierEstimationImageFilter.h.
template<class TInputImage , class TOutputImage > EstimationType itk::SphericalPolarFourierEstimationImageFilter< TInputImage, TOutputImage >::m_EstimationType protected
Definition at line 209 of file itkSphericalPolarFourierEstimationImageFilter.h.
template<class TInputImage , class TOutputImage > bool itk::SphericalPolarFourierEstimationImageFilter< TInputImage, TOutputImage >::m_IsAnalyticalB0 protected
If it is true, use analytical way to ensure E(0)=1
Definition at line 199 of file itkSphericalPolarFourierEstimationImageFilter.h.
template<class TInputImage , class TOutputImage > bool itk::SphericalPolarFourierEstimationImageFilter< TInputImage, TOutputImage >::m_IsOriginalBasis protected
Original SPF basis or dual SPF basis
Definition at line 218 of file itkSphericalPolarFourierEstimationImageFilter.h.
template<class TInputImage , class TOutputImage > L1FISTASolverType::Pointer itk::SphericalPolarFourierEstimationImageFilter< TInputImage, TOutputImage >::m_L1FISTASolver protected
Definition at line 212 of file itkSphericalPolarFourierEstimationImageFilter.h.
template<class TInputImage , class TOutputImage > L1SolverType itk::SphericalPolarFourierEstimationImageFilter< TInputImage, TOutputImage >::m_L1SolverType protected
Definition at line 215 of file itkSphericalPolarFourierEstimationImageFilter.h.
template<class TInputImage , class TOutputImage > L1SpamsSolverType::Pointer itk::SphericalPolarFourierEstimationImageFilter< TInputImage, TOutputImage >::m_L1SpamsSolver protected
Definition at line 213 of file itkSphericalPolarFourierEstimationImageFilter.h.
template<class TInputImage , class TOutputImage > L2SolverType::Pointer itk::SphericalPolarFourierEstimationImageFilter< TInputImage, TOutputImage >::m_L2Solver protected
Definition at line 211 of file itkSphericalPolarFourierEstimationImageFilter.h.
template<class TInputImage , class TOutputImage > double itk::SphericalPolarFourierEstimationImageFilter< TInputImage, TOutputImage >::m_LambdaL1 protected
single lambda for L1 norm regularization
Definition at line 187 of file itkSphericalPolarFourierEstimationImageFilter.h.
template<class TInputImage , class TOutputImage > double itk::SphericalPolarFourierEstimationImageFilter< TInputImage, TOutputImage >::m_LambdaL2 protected
single lambda for L2 norm regularization
Definition at line 189 of file itkSphericalPolarFourierEstimationImageFilter.h.
template<class TInputImage , class TOutputImage > double itk::SphericalPolarFourierEstimationImageFilter< TInputImage, TOutputImage >::m_LambdaRadial protected
Definition at line 185 of file itkSphericalPolarFourierEstimationImageFilter.h.
template<class TInputImage , class TOutputImage > double itk::SphericalPolarFourierEstimationImageFilter< TInputImage, TOutputImage >::m_LambdaSpherical protected
regularization parameter in sphercial and radial parts
Definition at line 184 of file itkSphericalPolarFourierEstimationImageFilter.h.
template<class TInputImage , class TOutputImage > ScalarImageType::Pointer itk::SphericalPolarFourierEstimationImageFilter< TInputImage, TOutputImage >::m_MDImage protected
used for adaptive scale
Definition at line 206 of file itkSphericalPolarFourierEstimationImageFilter.h.
template<class TInputImage , class TOutputImage > ScalarImageType::Pointer itk::SphericalPolarFourierEstimationImageFilter< TInputImage, TOutputImage >::m_ScaleImage protected
Definition at line 207 of file itkSphericalPolarFourierEstimationImageFilter.h.
The documentation for this class was generated from the following files:
Modules/DiffusionModels/include/itkSphericalPolarFourierEstimationImageFilter.h
Modules/DiffusionModels/include/itkSphericalPolarFourierEstimationImageFilter.hxx