DMRITool: itk::MeanDiffusivityFromGHOTImageFilter< TInputImage, TOutputImage > Class Template Reference
itk::MeanDiffusivityFromGHOTImageFilter< TInputImage, TOutputImage > Class Template Reference
DiffusionModels
#include <itkMeanDiffusivityFromGHOTImageFilter.h>
Detailed Description
template<class TInputImage, class TOutputImage>
class itk::MeanDiffusivityFromGHOTImageFilter< TInputImage, TOutputImage >
Compute mean diffusivity from GHOT coefficients.
This filter is templated over the input image type and the output image type.
Author
Jian Cheng, jian..nosp@m.chen.nosp@m.g.198.nosp@m.3@gm.nosp@m.ail.c.nosp@m.om
See also
UnaryFunctorImageFilter
Definition at line 80 of file itkMeanDiffusivityFromGHOTImageFilter.h.
Public Types
typedef SmartPointer< const Self > ConstPointer
typedef SmartPointer< Self > Pointer
typedef MeanDiffusivityFromGHOTImageFilter Self
typedef UnaryFunctorImageFilter< TInputImage, TOutputImage, Functor::MeanDiffusivityFromGHOTCoefficients< typename TInputImage::PixelType, typename TOutputImage::PixelType > > Superclass
Public Member Functions
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual const char * GetNameOfClass () const
const double & GetScale () const
const double & GetTau () const
void SetScale (const double scale)
void SetTau (const double tau)
Static Public Member Functions
static Pointer New ()
Protected Member Functions
MeanDiffusivityFromGHOTImageFilter ()
void PrintSelf (std::ostream &os, Indent indent) const ITK_OVERRIDE
virtual ~MeanDiffusivityFromGHOTImageFilter ()
Private Member Functions
MeanDiffusivityFromGHOTImageFilter (const Self &)
void operator= (const Self &)
Member Typedef Documentation
template<class TInputImage , class TOutputImage > typedef SmartPointer<const Self> itk::MeanDiffusivityFromGHOTImageFilter< TInputImage, TOutputImage >::ConstPointer
Definition at line 97 of file itkMeanDiffusivityFromGHOTImageFilter.h.
template<class TInputImage , class TOutputImage > typedef SmartPointer<Self> itk::MeanDiffusivityFromGHOTImageFilter< TInputImage, TOutputImage >::Pointer
Definition at line 96 of file itkMeanDiffusivityFromGHOTImageFilter.h.
template<class TInputImage , class TOutputImage > typedef MeanDiffusivityFromGHOTImageFilter itk::MeanDiffusivityFromGHOTImageFilter< TInputImage, TOutputImage >::Self
Standard class typedefs.
Definition at line 89 of file itkMeanDiffusivityFromGHOTImageFilter.h.
template<class TInputImage , class TOutputImage > typedef UnaryFunctorImageFilter< TInputImage,TOutputImage, Functor::MeanDiffusivityFromGHOTCoefficients< typename TInputImage::PixelType, typename TOutputImage::PixelType> > itk::MeanDiffusivityFromGHOTImageFilter< TInputImage, TOutputImage >::Superclass
Definition at line 94 of file itkMeanDiffusivityFromGHOTImageFilter.h.
Constructor & Destructor Documentation
template<class TInputImage , class TOutputImage > itk::MeanDiffusivityFromGHOTImageFilter< TInputImage, TOutputImage >::MeanDiffusivityFromGHOTImageFilter () inline protected
Definition at line 132 of file itkMeanDiffusivityFromGHOTImageFilter.h.
template<class TInputImage , class TOutputImage > virtual itk::MeanDiffusivityFromGHOTImageFilter< TInputImage, TOutputImage >::~MeanDiffusivityFromGHOTImageFilter () inline protected virtual
Definition at line 133 of file itkMeanDiffusivityFromGHOTImageFilter.h.
template<class TInputImage , class TOutputImage > itk::MeanDiffusivityFromGHOTImageFilter< TInputImage, TOutputImage >::MeanDiffusivityFromGHOTImageFilter (const Self &) private
Member Function Documentation
template<class TInputImage , class TOutputImage > virtual::itk::LightObject::Pointer itk::MeanDiffusivityFromGHOTImageFilter< TInputImage, TOutputImage >::CreateAnother (void) const
template<class TInputImage , class TOutputImage > virtual const char* itk::MeanDiffusivityFromGHOTImageFilter< TInputImage, TOutputImage >::GetNameOfClass () const virtual
Run-time type information (and related methods).
template<class TInputImage , class TOutputImage > const double& itk::MeanDiffusivityFromGHOTImageFilter< TInputImage, TOutputImage >::GetScale () const inline
Definition at line 113 of file itkMeanDiffusivityFromGHOTImageFilter.h.
template<class TInputImage , class TOutputImage > const double& itk::MeanDiffusivityFromGHOTImageFilter< TInputImage, TOutputImage >::GetTau () const inline
Definition at line 126 of file itkMeanDiffusivityFromGHOTImageFilter.h.
template<class TInputImage , class TOutputImage > static Pointer itk::MeanDiffusivityFromGHOTImageFilter< TInputImage, TOutputImage >::New () static
Method for creation through the object factory.
template<class TInputImage , class TOutputImage > void itk::MeanDiffusivityFromGHOTImageFilter< TInputImage, TOutputImage >::operator= (const Self &) private
template<class TInputImage , class TOutputImage > void itk::MeanDiffusivityFromGHOTImageFilter< TInputImage, TOutputImage >::PrintSelf (std::ostream & os, Indent indent) const inline protected
Definition at line 135 of file itkMeanDiffusivityFromGHOTImageFilter.h.
References itk::Functor::MeanDiffusivityFromGHOTCoefficients< TInput, TOutput >::GetScale(), and itk::Functor::MeanDiffusivityFromGHOTCoefficients< TInput, TOutput >::GetTau().
template<class TInputImage , class TOutputImage > void itk::MeanDiffusivityFromGHOTImageFilter< TInputImage, TOutputImage >::SetScale (const double scale) inline
Definition at line 105 of file itkMeanDiffusivityFromGHOTImageFilter.h.
References itk::Functor::MeanDiffusivityFromGHOTCoefficients< TInput, TOutput >::GetScale().
template<class TInputImage , class TOutputImage > void itk::MeanDiffusivityFromGHOTImageFilter< TInputImage, TOutputImage >::SetTau (const double tau) inline
Definition at line 118 of file itkMeanDiffusivityFromGHOTImageFilter.h.
References itk::Functor::MeanDiffusivityFromGHOTCoefficients< TInput, TOutput >::GetTau().
The documentation for this class was generated from the following file:
Modules/DiffusionModels/include/itkMeanDiffusivityFromGHOTImageFilter.h