DMRITool: utl::Expr< SubType, ValueT > Class Template Reference
utl::Expr< SubType, ValueT > Class Template Reference
Utl » UtlNDArray
#include <utlExpression.h>
Detailed Description
template<typename SubType, typename ValueT>
class utl::Expr< SubType, ValueT >
base class for expression
Template Parameters
SubType inheritated class must put their type into this parameter
Definition at line 36 of file utlExpression.h.
Public Types
typedef SizeType const * ShapeType
typedef unsigned int SizeType
typedef ValueT ValueType
Public Member Functions
const SubType & ConstRef (void) const
const ShapeType GetShape () const
SubType & Ref (void)
Static Public Member Functions
static SizeType GetDimension ()
Member Typedef Documentation
template<typename SubType, typename ValueT> typedef SizeType const* utl::Expr< SubType, ValueT >::ShapeType
Definition at line 66 of file utlExpression.h.
template<typename SubType, typename ValueT> typedef unsigned int utl::Expr< SubType, ValueT >::SizeType
Definition at line 65 of file utlExpression.h.
template<typename SubType, typename ValueT> typedef ValueT utl::Expr< SubType, ValueT >::ValueType
Definition at line 64 of file utlExpression.h.
Member Function Documentation
template<typename SubType, typename ValueT> const SubType& utl::Expr< SubType, ValueT >::ConstRef (void) const inline
return reference of subtype instance of current class
Definition at line 69 of file utlExpression.h.
Referenced by utl::F(), utl::Expr< UnaryOpExpr< OP, EType >, EType::ValueType >::GetShape(), and utl::MakeExpr().
template<typename SubType, typename ValueT> static SizeType utl::Expr< SubType, ValueT >::GetDimension () inline static
Definition at line 78 of file utlExpression.h.
Referenced by utl::NDArrayBase< T, 4 >::IsSameShape().
template<typename SubType, typename ValueT> const ShapeType utl::Expr< SubType, ValueT >::GetShape () const inline
Definition at line 81 of file utlExpression.h.
template<typename SubType, typename ValueT> SubType& utl::Expr< SubType, ValueT >::Ref (void) inline
return reference of subtype instance of current class
Definition at line 74 of file utlExpression.h.
The documentation for this class was generated from the following file:
Modules/HelperFunctions/include/utlExpression.h