DMRITool: itk::DiffusionModelEstimationInSphericalCoordinateImageFilter< TInputImage, TOutputImage > Class Template Reference
itk::DiffusionModelEstimationInSphericalCoordinateImageFilter< TInputImage, TOutputImage > Class Template Reference
DiffusionModels
#include <itkDiffusionModelEstimationInSphericalCoordinateImageFilter.h>
Detailed Description
template<class TInputImage, class TOutputImage>
class itk::DiffusionModelEstimationInSphericalCoordinateImageFilter< TInputImage, TOutputImage >
base filter for estimation of diffusion models in spherical coordinates
Author
Jian Cheng (JC), jian..nosp@m.chen.nosp@m.g.198.nosp@m.3@gm.nosp@m.ail.c.nosp@m.om
Definition at line 36 of file itkDiffusionModelEstimationInSphericalCoordinateImageFilter.h.
Public Types
typedef SmartPointer< const Self > ConstPointer
typedef Superclass::InputImageConstPointer InputImageConstPointer
typedef Superclass::InputImageIndexType InputImageIndexType
typedef Superclass::InputImagePixelType InputImagePixelType
typedef Superclass::InputImagePointer InputImagePointer
typedef Superclass::InputImageRegionType InputImageRegionType
typedef Superclass::InputImageSizeType InputImageSizeType
typedef Superclass::InputImageSpacingType InputImageSpacingType
typedef Superclass::InputImageType InputImageType
typedef Superclass::MaskImageType MaskImageType
typedef Superclass::MatrixPointer MatrixPointer
typedef Superclass::MatrixType MatrixType
typedef Superclass::OutputImageIndexType OutputImageIndexType
typedef Superclass::OutputImagePixelType OutputImagePixelType
typedef Superclass::OutputImagePointer OutputImagePointer
typedef Superclass::OutputImageRegionType OutputImageRegionType
typedef Superclass::OutputImageSizeType OutputImageSizeType
typedef Superclass::OutputImageSpacingType OutputImageSpacingType
typedef Superclass::OutputImageType OutputImageType
typedef SmartPointer< Self > Pointer
typedef DiffusionModelEstimationInSphericalCoordinateImageFilter Self
typedef Superclass::STDVectorPointer STDVectorPointer
typedef Superclass::STDVectorType STDVectorType
typedef DiffusionModelEstimationImageFilter< TInputImage, TOutputImage > Superclass
typedef Superclass::VectorPointer VectorPointer
typedef Superclass::VectorType VectorType
Public Types inherited from itk::DiffusionModelEstimationImageFilter< TInputImage, TOutputImage >
typedef SmartPointer< const Self > ConstPointer
typedef utl_shared_ptr< MatrixType > MatrixPointer
typedef utl::NDArray< double, 2 > MatrixType
typedef SmartPointer< Self > Pointer
typedef SamplingSchemeQSpaceType::Pointer SamplingSchemeQSpacePointer
typedef SamplingSchemeQSpace< double > SamplingSchemeQSpaceType
typedef SamplingSchemeRSpaceType::Pointer SamplingSchemeRSpacePointer
typedef SamplingScheme3D< double > SamplingSchemeRSpaceType
typedef DiffusionModelEstimationImageFilter Self
typedef utl_shared_ptr< STDVectorType > STDVectorPointer
typedef std::vector< double > STDVectorType
typedef MaskedImageToImageFilter< TInputImage, TOutputImage > Superclass
typedef utl_shared_ptr< VectorType > VectorPointer
typedef utl::NDArray< double, 1 > VectorType
Public Types inherited from itk::MaskedImageToImageFilter< TInputImage, TOutputImage >
typedef SmartPointer< const Self > ConstPointer
typedef InputImageType::ConstPointer InputImageConstPointer
typedef InputImageType::IndexType InputImageIndexType
typedef InputImageType::PixelType InputImagePixelType
typedef InputImageType::Pointer InputImagePointer
typedef InputImageType::RegionType InputImageRegionType
typedef InputImageType::SizeType InputImageSizeType
typedef InputImageType::SpacingType InputImageSpacingType
typedef TInputImage InputImageType
typedef LoggerType::Pointer LoggerPointer
typedef ThreadLogger LoggerType
typedef utl_shared_ptr< LoggerVectorType > LoggerVectorPointer
typedef std::vector< LoggerPointer > LoggerVectorType
typedef MaskImageType::Pointer MaskImagePointer
typedef Image< double, 3 > MaskImageType
typedef OutputImageType::IndexType OutputImageIndexType
typedef OutputImageType::PixelType OutputImagePixelType
typedef OutputImageType::Pointer OutputImagePointer
typedef OutputImageType::RegionType OutputImageRegionType
typedef OutputImageType::SizeType OutputImageSizeType
typedef OutputImageType::SpacingType OutputImageSpacingType
typedef TOutputImage OutputImageType
typedef SmartPointer< Self > Pointer
typedef MaskedImageToImageFilter Self
typedef ImageToImageFilter< TInputImage, TOutputImage > Superclass
Public Member Functions
virtual void ComputeRadialMatrix ()
virtual void ComputeSHMatrix ()
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual MatrixPointer GetBasisRadialMatrix ()
virtual MatrixPointer GetBasisSHMatrix ()
virtual const char * GetNameOfClass () const
virtual int GetRadialRank ()
virtual int GetSHRank ()
virtual void SetRadialRank (int _arg)
virtual void SetSHRank (int _arg)
Public Member Functions inherited from itk::DiffusionModelEstimationImageFilter< TInputImage, TOutputImage >
virtual void ComputeBasisMatrix ()
virtual void ComputeRegularizationWeight ()
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual MatrixPointer GetBasisMatrix ()
virtual double GetMD0 ()
itkGetObjectMacro (SamplingSchemeQSpace, SamplingSchemeQSpaceType)
itkTypedefMaskedImageToImageMacro (Superclass)
virtual void SetMD0 (double _arg)
virtual void SetSamplingSchemeQSpace (SamplingSchemeQSpaceType *_arg)
Public Member Functions inherited from itk::MaskedImageToImageFilter< TInputImage, TOutputImage >
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual const LoggerType * GetLogger () const
virtual const MaskImageType * GetMaskImage () const
bool IsMaskUsed ()
itkGetObjectMacro (MaskImage, MaskImageType)
itkGetObjectMacro (Logger, LoggerType)
itkSetGetMacro (LogLevel, int)
virtual void SetLogger (LoggerType *_arg)
virtual void SetMaskImage (MaskImageType *_arg)
void SetMaskImage (const std::string &file)
Static Public Member Functions
static Pointer New ()
Static Public Member Functions inherited from itk::DiffusionModelEstimationImageFilter< TInputImage, TOutputImage >
static Pointer New ()
Static Public Member Functions inherited from itk::MaskedImageToImageFilter< TInputImage, TOutputImage >
static Pointer New ()
Protected Member Functions
DiffusionModelEstimationInSphericalCoordinateImageFilter ()
LightObject::Pointer InternalClone () const ITK_OVERRIDE
void PrintSelf (std::ostream &os, Indent indent) const ITK_OVERRIDE
virtual void VerifyInputParameters () const ITK_OVERRIDE
virtual ~DiffusionModelEstimationInSphericalCoordinateImageFilter ()
Protected Member Functions inherited from itk::DiffusionModelEstimationImageFilter< TInputImage, TOutputImage >
DiffusionModelEstimationImageFilter ()
LightObject::Pointer InternalClone () const ITK_OVERRIDE
virtual ~DiffusionModelEstimationImageFilter ()
Protected Member Functions inherited from itk::MaskedImageToImageFilter< TInputImage, TOutputImage >
void CreateLoggerVector ()
virtual void InitializeThreadedLibraries ()
LightObject::Pointer InternalClone () const ITK_OVERRIDE
MaskedImageToImageFilter ()
std::string ThreadIDToString () const
virtual void VerifyMaskInformation () const
void WriteLogger (const std::string &str, const LoggerBase::PriorityLevelType level=LoggerBase::DEBUG) const
virtual ~MaskedImageToImageFilter ()
Protected Attributes
MatrixPointer m_BasisRadialMatrix
MatrixPointer m_BasisSHMatrix
int m_RadialRank
int m_SHRank
Protected Attributes inherited from itk::DiffusionModelEstimationImageFilter< TInputImage, TOutputImage >
MatrixPointer m_BasisMatrix
double m_MD0
VectorPointer m_RegularizationWeight
SamplingSchemeQSpacePointer m_SamplingSchemeQSpace
Protected Attributes inherited from itk::MaskedImageToImageFilter< TInputImage, TOutputImage >
LoggerPointer m_Logger
LoggerVectorPointer m_LoggerVector
int m_LogLevel
MaskImagePointer m_MaskImage
int m_ThreadID
Private Member Functions
DiffusionModelEstimationInSphericalCoordinateImageFilter (const Self &)
void operator= (const Self &)
Additional Inherited Members
Static Public Attributes inherited from itk::MaskedImageToImageFilter< TInputImage, TOutputImage >
static const unsigned int InputImageDimension
static const unsigned int OutputImageDimension
Member Typedef Documentation
template<class TInputImage , class TOutputImage > typedef SmartPointer<const Self> itk::DiffusionModelEstimationInSphericalCoordinateImageFilter< TInputImage, TOutputImage >::ConstPointer
Definition at line 44 of file itkDiffusionModelEstimationInSphericalCoordinateImageFilter.h.
template<class TInputImage , class TOutputImage > typedef Superclass::InputImageConstPointer itk::DiffusionModelEstimationInSphericalCoordinateImageFilter< TInputImage, TOutputImage >::InputImageConstPointer
Definition at line 55 of file itkDiffusionModelEstimationInSphericalCoordinateImageFilter.h.
template<class TInputImage , class TOutputImage > typedef Superclass::InputImageIndexType itk::DiffusionModelEstimationInSphericalCoordinateImageFilter< TInputImage, TOutputImage >::InputImageIndexType
Definition at line 56 of file itkDiffusionModelEstimationInSphericalCoordinateImageFilter.h.
template<class TInputImage , class TOutputImage > typedef Superclass::InputImagePixelType itk::DiffusionModelEstimationInSphericalCoordinateImageFilter< TInputImage, TOutputImage >::InputImagePixelType
Definition at line 59 of file itkDiffusionModelEstimationInSphericalCoordinateImageFilter.h.
template<class TInputImage , class TOutputImage > typedef Superclass::InputImagePointer itk::DiffusionModelEstimationInSphericalCoordinateImageFilter< TInputImage, TOutputImage >::InputImagePointer
Definition at line 54 of file itkDiffusionModelEstimationInSphericalCoordinateImageFilter.h.
template<class TInputImage , class TOutputImage > typedef Superclass::InputImageRegionType itk::DiffusionModelEstimationInSphericalCoordinateImageFilter< TInputImage, TOutputImage >::InputImageRegionType
Definition at line 60 of file itkDiffusionModelEstimationInSphericalCoordinateImageFilter.h.
template<class TInputImage , class TOutputImage > typedef Superclass::InputImageSizeType itk::DiffusionModelEstimationInSphericalCoordinateImageFilter< TInputImage, TOutputImage >::InputImageSizeType
Definition at line 57 of file itkDiffusionModelEstimationInSphericalCoordinateImageFilter.h.
template<class TInputImage , class TOutputImage > typedef Superclass::InputImageSpacingType itk::DiffusionModelEstimationInSphericalCoordinateImageFilter< TInputImage, TOutputImage >::InputImageSpacingType
Definition at line 58 of file itkDiffusionModelEstimationInSphericalCoordinateImageFilter.h.
template<class TInputImage , class TOutputImage > typedef Superclass::InputImageType itk::DiffusionModelEstimationInSphericalCoordinateImageFilter< TInputImage, TOutputImage >::InputImageType
Convenient Typedefs.
Definition at line 50 of file itkDiffusionModelEstimationInSphericalCoordinateImageFilter.h.
template<class TInputImage , class TOutputImage > typedef Superclass::MaskImageType itk::DiffusionModelEstimationInSphericalCoordinateImageFilter< TInputImage, TOutputImage >::MaskImageType
Definition at line 70 of file itkDiffusionModelEstimationInSphericalCoordinateImageFilter.h.
template<class TInputImage , class TOutputImage > typedef Superclass::MatrixPointer itk::DiffusionModelEstimationInSphericalCoordinateImageFilter< TInputImage, TOutputImage >::MatrixPointer
Definition at line 74 of file itkDiffusionModelEstimationInSphericalCoordinateImageFilter.h.
template<class TInputImage , class TOutputImage > typedef Superclass::MatrixType itk::DiffusionModelEstimationInSphericalCoordinateImageFilter< TInputImage, TOutputImage >::MatrixType
Definition at line 72 of file itkDiffusionModelEstimationInSphericalCoordinateImageFilter.h.
template<class TInputImage , class TOutputImage > typedef Superclass::OutputImageIndexType itk::DiffusionModelEstimationInSphericalCoordinateImageFilter< TInputImage, TOutputImage >::OutputImageIndexType
Definition at line 64 of file itkDiffusionModelEstimationInSphericalCoordinateImageFilter.h.
template<class TInputImage , class TOutputImage > typedef Superclass::OutputImagePixelType itk::DiffusionModelEstimationInSphericalCoordinateImageFilter< TInputImage, TOutputImage >::OutputImagePixelType
Definition at line 67 of file itkDiffusionModelEstimationInSphericalCoordinateImageFilter.h.
template<class TInputImage , class TOutputImage > typedef Superclass::OutputImagePointer itk::DiffusionModelEstimationInSphericalCoordinateImageFilter< TInputImage, TOutputImage >::OutputImagePointer
Definition at line 63 of file itkDiffusionModelEstimationInSphericalCoordinateImageFilter.h.
template<class TInputImage , class TOutputImage > typedef Superclass::OutputImageRegionType itk::DiffusionModelEstimationInSphericalCoordinateImageFilter< TInputImage, TOutputImage >::OutputImageRegionType
Definition at line 68 of file itkDiffusionModelEstimationInSphericalCoordinateImageFilter.h.
template<class TInputImage , class TOutputImage > typedef Superclass::OutputImageSizeType itk::DiffusionModelEstimationInSphericalCoordinateImageFilter< TInputImage, TOutputImage >::OutputImageSizeType
Definition at line 65 of file itkDiffusionModelEstimationInSphericalCoordinateImageFilter.h.
template<class TInputImage , class TOutputImage > typedef Superclass::OutputImageSpacingType itk::DiffusionModelEstimationInSphericalCoordinateImageFilter< TInputImage, TOutputImage >::OutputImageSpacingType
Definition at line 66 of file itkDiffusionModelEstimationInSphericalCoordinateImageFilter.h.
template<class TInputImage , class TOutputImage > typedef Superclass::OutputImageType itk::DiffusionModelEstimationInSphericalCoordinateImageFilter< TInputImage, TOutputImage >::OutputImageType
Definition at line 62 of file itkDiffusionModelEstimationInSphericalCoordinateImageFilter.h.
template<class TInputImage , class TOutputImage > typedef SmartPointer<Self> itk::DiffusionModelEstimationInSphericalCoordinateImageFilter< TInputImage, TOutputImage >::Pointer
Definition at line 43 of file itkDiffusionModelEstimationInSphericalCoordinateImageFilter.h.
template<class TInputImage , class TOutputImage > typedef DiffusionModelEstimationInSphericalCoordinateImageFilter itk::DiffusionModelEstimationInSphericalCoordinateImageFilter< TInputImage, TOutputImage >::Self
Standard class typedefs.
Definition at line 41 of file itkDiffusionModelEstimationInSphericalCoordinateImageFilter.h.
template<class TInputImage , class TOutputImage > typedef Superclass::STDVectorPointer itk::DiffusionModelEstimationInSphericalCoordinateImageFilter< TInputImage, TOutputImage >::STDVectorPointer
Definition at line 77 of file itkDiffusionModelEstimationInSphericalCoordinateImageFilter.h.
template<class TInputImage , class TOutputImage > typedef Superclass::STDVectorType itk::DiffusionModelEstimationInSphericalCoordinateImageFilter< TInputImage, TOutputImage >::STDVectorType
Definition at line 76 of file itkDiffusionModelEstimationInSphericalCoordinateImageFilter.h.
template<class TInputImage , class TOutputImage > typedef DiffusionModelEstimationImageFilter<TInputImage,TOutputImage> itk::DiffusionModelEstimationInSphericalCoordinateImageFilter< TInputImage, TOutputImage >::Superclass
Definition at line 42 of file itkDiffusionModelEstimationInSphericalCoordinateImageFilter.h.
template<class TInputImage , class TOutputImage > typedef Superclass::VectorPointer itk::DiffusionModelEstimationInSphericalCoordinateImageFilter< TInputImage, TOutputImage >::VectorPointer
Definition at line 75 of file itkDiffusionModelEstimationInSphericalCoordinateImageFilter.h.
template<class TInputImage , class TOutputImage > typedef Superclass::VectorType itk::DiffusionModelEstimationInSphericalCoordinateImageFilter< TInputImage, TOutputImage >::VectorType
Definition at line 73 of file itkDiffusionModelEstimationInSphericalCoordinateImageFilter.h.
Constructor & Destructor Documentation
template<class TInputImage , class TOutputImage > itk::DiffusionModelEstimationInSphericalCoordinateImageFilter< TInputImage, TOutputImage >::DiffusionModelEstimationInSphericalCoordinateImageFilter () protected
Definition at line 28 of file itkDiffusionModelEstimationInSphericalCoordinateImageFilter.hxx.
References itk::DiffusionModelEstimationInSphericalCoordinateImageFilter< TInputImage, TOutputImage >::InternalClone().
template<class TInputImage , class TOutputImage > virtual itk::DiffusionModelEstimationInSphericalCoordinateImageFilter< TInputImage, TOutputImage >::~DiffusionModelEstimationInSphericalCoordinateImageFilter () inline protected virtual
Definition at line 99 of file itkDiffusionModelEstimationInSphericalCoordinateImageFilter.h.
References ITK_OVERRIDE.
template<class TInputImage , class TOutputImage > itk::DiffusionModelEstimationInSphericalCoordinateImageFilter< TInputImage, TOutputImage >::DiffusionModelEstimationInSphericalCoordinateImageFilter (const Self &) private
Member Function Documentation
template<class TInputImage , class TOutputImage > virtual void itk::DiffusionModelEstimationInSphericalCoordinateImageFilter< TInputImage, TOutputImage >::ComputeRadialMatrix () inline virtual
compute radial matrix
Reimplemented in itk::SphericalPolarFourierImageFilter< TInputImage, TOutputImage >, and itk::GeneralizedHighOrderTensorImageFilter< TInputImage, TOutputImage >.
Definition at line 93 of file itkDiffusionModelEstimationInSphericalCoordinateImageFilter.h.
template<class TInputImage , class TOutputImage > void itk::DiffusionModelEstimationInSphericalCoordinateImageFilter< TInputImage, TOutputImage >::ComputeSHMatrix () virtual
compute SH matrix
Definition at line 60 of file itkDiffusionModelEstimationInSphericalCoordinateImageFilter.hxx.
References utl::ComputeSHMatrix(), itkShowPositionThreadedLogger, utl::PrintUtlMatrix(), SPHERICAL_TO_SPHERICAL, and itk::DiffusionModelEstimationInSphericalCoordinateImageFilter< TInputImage, TOutputImage >::VerifyInputParameters().
Referenced by itk::DiffusionModelEstimationInSphericalCoordinateImageFilter< TInputImage, TOutputImage >::InternalClone().
template<class TInputImage , class TOutputImage > virtual::itk::LightObject::Pointer itk::DiffusionModelEstimationInSphericalCoordinateImageFilter< TInputImage, TOutputImage >::CreateAnother (void) const
template<class TInputImage , class TOutputImage > virtual MatrixPointer itk::DiffusionModelEstimationInSphericalCoordinateImageFilter< TInputImage, TOutputImage >::GetBasisRadialMatrix () virtual
template<class TInputImage , class TOutputImage > virtual MatrixPointer itk::DiffusionModelEstimationInSphericalCoordinateImageFilter< TInputImage, TOutputImage >::GetBasisSHMatrix () virtual
template<class TInputImage , class TOutputImage > virtual const char* itk::DiffusionModelEstimationInSphericalCoordinateImageFilter< TInputImage, TOutputImage >::GetNameOfClass () const virtual
Run-time type information (and related methods)
Reimplemented from itk::DiffusionModelEstimationImageFilter< TInputImage, TOutputImage >.
Reimplemented in itk::SphericalPolarFourierEstimationImageFilter< TInputImage, TOutputImage >, itk::SphericalPolarFourierImageFilter< TInputImage, TOutputImage >, and itk::GeneralizedHighOrderTensorImageFilter< TInputImage, TOutputImage >.
template<class TInputImage , class TOutputImage > virtual int itk::DiffusionModelEstimationInSphericalCoordinateImageFilter< TInputImage, TOutputImage >::GetRadialRank () virtual
template<class TInputImage , class TOutputImage > virtual int itk::DiffusionModelEstimationInSphericalCoordinateImageFilter< TInputImage, TOutputImage >::GetSHRank () virtual
template<class TInputImage , class TOutputImage > LightObject::Pointer itk::DiffusionModelEstimationInSphericalCoordinateImageFilter< TInputImage, TOutputImage >::InternalClone () const protected
Definition at line 39 of file itkDiffusionModelEstimationInSphericalCoordinateImageFilter.hxx.
References itk::DiffusionModelEstimationInSphericalCoordinateImageFilter< TInputImage, TOutputImage >::ComputeSHMatrix(), and itkShowPositionThreadedLogger.
Referenced by itk::DiffusionModelEstimationInSphericalCoordinateImageFilter< TInputImage, TOutputImage >::DiffusionModelEstimationInSphericalCoordinateImageFilter().
template<class TInputImage , class TOutputImage > static Pointer itk::DiffusionModelEstimationInSphericalCoordinateImageFilter< TInputImage, TOutputImage >::New () static
Method for creation through the object factory.
template<class TInputImage , class TOutputImage > void itk::DiffusionModelEstimationInSphericalCoordinateImageFilter< TInputImage, TOutputImage >::operator= (const Self &) private
template<class TInputImage , class TOutputImage > void itk::DiffusionModelEstimationInSphericalCoordinateImageFilter< TInputImage, TOutputImage >::PrintSelf (std::ostream & os, Indent indent) const protected virtual
Reimplemented from itk::DiffusionModelEstimationImageFilter< TInputImage, TOutputImage >.
Reimplemented in itk::SphericalPolarFourierEstimationImageFilter< TInputImage, TOutputImage >, itk::SphericalPolarFourierImageFilter< TInputImage, TOutputImage >, and itk::GeneralizedHighOrderTensorImageFilter< TInputImage, TOutputImage >.
Definition at line 93 of file itkDiffusionModelEstimationInSphericalCoordinateImageFilter.hxx.
References utl::PrintUtlMatrix(), and PrintVar2.
Referenced by itk::DiffusionModelEstimationInSphericalCoordinateImageFilter< TInputImage, TOutputImage >::VerifyInputParameters().
template<class TInputImage , class TOutputImage > virtual void itk::DiffusionModelEstimationInSphericalCoordinateImageFilter< TInputImage, TOutputImage >::SetRadialRank (int _arg) virtual
template<class TInputImage , class TOutputImage > virtual void itk::DiffusionModelEstimationInSphericalCoordinateImageFilter< TInputImage, TOutputImage >::SetSHRank (int _arg) virtual
template<class TInputImage , class TOutputImage > void itk::DiffusionModelEstimationInSphericalCoordinateImageFilter< TInputImage, TOutputImage >::VerifyInputParameters () const protected virtual
Reimplemented from itk::DiffusionModelEstimationImageFilter< TInputImage, TOutputImage >.
Reimplemented in itk::SphericalPolarFourierEstimationImageFilter< TInputImage, TOutputImage >, and itk::GeneralizedHighOrderTensorImageFilter< TInputImage, TOutputImage >.
Definition at line 81 of file itkDiffusionModelEstimationInSphericalCoordinateImageFilter.hxx.
References utl::IsEven(), itkShowPositionThreadedLogger, itk::DiffusionModelEstimationInSphericalCoordinateImageFilter< TInputImage, TOutputImage >::PrintSelf(), and utlGlobalException.
Referenced by itk::DiffusionModelEstimationInSphericalCoordinateImageFilter< TInputImage, TOutputImage >::ComputeSHMatrix().
Member Data Documentation
template<class TInputImage , class TOutputImage > MatrixPointer itk::DiffusionModelEstimationInSphericalCoordinateImageFilter< TInputImage, TOutputImage >::m_BasisRadialMatrix protected
Definition at line 112 of file itkDiffusionModelEstimationInSphericalCoordinateImageFilter.h.
template<class TInputImage , class TOutputImage > MatrixPointer itk::DiffusionModelEstimationInSphericalCoordinateImageFilter< TInputImage, TOutputImage >::m_BasisSHMatrix protected
Definition at line 111 of file itkDiffusionModelEstimationInSphericalCoordinateImageFilter.h.
template<class TInputImage , class TOutputImage > int itk::DiffusionModelEstimationInSphericalCoordinateImageFilter< TInputImage, TOutputImage >::m_RadialRank protected
rank for radial part
Definition at line 109 of file itkDiffusionModelEstimationInSphericalCoordinateImageFilter.h.
template<class TInputImage , class TOutputImage > int itk::DiffusionModelEstimationInSphericalCoordinateImageFilter< TInputImage, TOutputImage >::m_SHRank protected
rank for spherical part (SH basis)
Definition at line 107 of file itkDiffusionModelEstimationInSphericalCoordinateImageFilter.h.
The documentation for this class was generated from the following files:
Modules/DiffusionModels/include/itkDiffusionModelEstimationInSphericalCoordinateImageFilter.h
Modules/DiffusionModels/include/itkDiffusionModelEstimationInSphericalCoordinateImageFilter.hxx