DMRITool: spams::AbstractMatrix< T > Class Template Reference
spams::AbstractMatrix< T > Class Template Reference abstract
#include <linalg.h>
Detailed Description
template<typename T>
class spams::AbstractMatrix< T >
Abstract matrix class.
Definition at line 188 of file linalg.h.
Public Member Functions
virtual void add_rawCol (const int i, T *col, const T a) const =0
virtual void copyCol (const int i, Vector< T > &Xi) const =0
virtual void diag (Vector< T > &diag) const =0
virtual void extract_rawCol (const int i, T *Xi) const =0
virtual int m () const =0
virtual int n () const =0
virtual T operator() (const int index1, const int index2) const =0
virtual ~AbstractMatrix ()
Constructor & Destructor Documentation
template<typename T> virtual spams::AbstractMatrix< T >::~AbstractMatrix () inline virtual
Definition at line 202 of file linalg.h.
Member Function Documentation
template<typename T> virtual void spams::AbstractMatrix< T >::add_rawCol (const int i, T * col, const T a) const pure virtual
compute X(:,i)<- X(:,i)+a*col;
Implemented in spams::SubMatrix< T >, spams::ProdMatrix< T >, and spams::Matrix< T >.
Referenced by spams::coreIST(), and spams::coreISTconstrained().
template<typename T> virtual void spams::AbstractMatrix< T >::copyCol (const int i, Vector< T > & Xi) const pure virtual
copy X(:,i) into Xi
Implemented in spams::SubMatrix< T >, spams::ProdMatrix< T >, and spams::Matrix< T >.
Referenced by spams::coreORMP(), spams::lasso(), and spams::lasso2().
template<typename T> virtual void spams::AbstractMatrix< T >::diag (Vector< T > & diag) const pure virtual
extract diagonal
Implemented in spams::SubMatrix< T >, spams::ProdMatrix< T >, and spams::Matrix< T >.
template<typename T> virtual void spams::AbstractMatrix< T >::extract_rawCol (const int i, T * Xi) const pure virtual
copy X(:,i) into Xi
Implemented in spams::SubMatrix< T >, spams::ProdMatrix< T >, and spams::Matrix< T >.
Referenced by spams::coreLARS(), spams::coreLARS2(), and spams::coreLARS2W().
template<typename T> virtual int spams::AbstractMatrix< T >::m () const pure virtual
Implemented in spams::SubMatrix< T >, spams::ProdMatrix< T >, and spams::Matrix< T >.
template<typename T> virtual int spams::AbstractMatrix< T >::n () const pure virtual
Implemented in spams::SubMatrix< T >, spams::ProdMatrix< T >, and spams::Matrix< T >.
Referenced by spams::coreIST(), spams::coreISTconstrained(), spams::coreLARS2(), spams::coreLARS2W(), spams::coreORMPB(), spams::lasso(), and spams::lasso2().
template<typename T> virtual T spams::AbstractMatrix< T >::operator() (const int index1, const int index2) const inline pure virtual
Implemented in spams::SubMatrix< T >, spams::ProdMatrix< T >, and spams::Matrix< T >.
The documentation for this class was generated from the following file:
ThirdParty/Spams/include/linalg.h