DMRITool: spams::FISTA::FusedLasso< T > Class Template Reference
spams::FISTA::FusedLasso< T > Class Template Reference
#include <fista.h>
Detailed Description
template<typename T>
class spams::FISTA::FusedLasso< T >
Definition at line 1348 of file fista.h.
Public Member Functions
T eval (const Vector< T > &x) const
void fenchel (const Vector< T > &input, T &val, T &scal) const
FusedLasso (const ParamReg< T > &param)
virtual bool is_fenchel () const
void prox (const Vector< T > &x, Vector< T > &y, const T lambda)
virtual ~FusedLasso ()
Public Member Functions inherited from spams::FISTA::Regularizer< T >
virtual T eval_dual_norm (const Vector< T > &x) const
virtual T eval_dual_norm_paths (const Vector< T > &x, SpMatrix< T > &path) const
virtual T eval_paths (const Vector< T > &x, SpMatrix< T > &paths_mat) const
virtual bool is_intercept () const
virtual bool is_subgrad () const
Regularizer ()
Regularizer (const ParamReg< T > &param)
virtual void reset ()
virtual void sub_grad (const Vector< T > &input, Vector< T > &output) const
virtual ~Regularizer ()
Private Attributes
T _lambda2d1
T _lambda3d1
Additional Inherited Members
Protected Attributes inherited from spams::FISTA::Regularizer< T >
bool _intercept
bool _pos
Constructor & Destructor Documentation
template<typename T > spams::FISTA::FusedLasso< T >::FusedLasso (const ParamReg< T > & param) inline
Definition at line 1350 of file fista.h.
References spams::FISTA::ParamReg< T >::lambda2d1, and spams::FISTA::ParamReg< T >::lambda3d1.
template<typename T > virtual spams::FISTA::FusedLasso< T >::~FusedLasso () inline virtual
Definition at line 1354 of file fista.h.
Member Function Documentation
template<typename T > T spams::FISTA::FusedLasso< T >::eval (const Vector< T > & x) const inline virtual
Implements spams::FISTA::Regularizer< T >.
Definition at line 1362 of file fista.h.
References spams::abs(), and spams::Vector< T >::n().
template<typename T > void spams::FISTA::FusedLasso< T >::fenchel (const Vector< T > & input, T & val, T & scal) const inline virtual
returns phi^star(input) and ouput=input if the fenchel is unconstrained returns 0 and scale input such that phi^star(output)=0 otherwise
Implements spams::FISTA::Regularizer< T >.
Definition at line 1371 of file fista.h.
template<typename T > virtual bool spams::FISTA::FusedLasso< T >::is_fenchel () const inline virtual
Reimplemented from spams::FISTA::Regularizer< T >.
Definition at line 1370 of file fista.h.
template<typename T > void spams::FISTA::FusedLasso< T >::prox (const Vector< T > & x, Vector< T > & y, const T lambda) inline virtual
Implements spams::FISTA::Regularizer< T >.
Definition at line 1356 of file fista.h.
References spams::Vector< T >::copy(), spams::Vector< T >::fusedProjectHomotopy(), spams::Vector< T >::n(), and spams::Vector< T >::resize().
Member Data Documentation
template<typename T > T spams::FISTA::FusedLasso< T >::_lambda2d1 private
Definition at line 1371 of file fista.h.
template<typename T > T spams::FISTA::FusedLasso< T >::_lambda3d1 private
Definition at line 1375 of file fista.h.
The documentation for this class was generated from the following file:
ThirdParty/Spams/include/fista.h