DMRITool: itk::ProfileFromSPFImageFilter< TInputImage, TOutputImage > Class Template Reference
itk::ProfileFromSPFImageFilter< TInputImage, TOutputImage > Class Template Reference
DiffusionModels
#include <itkProfileFromSPFImageFilter.h>
Detailed Description
template<class TInputImage, class TOutputImage>
class itk::ProfileFromSPFImageFilter< TInputImage, TOutputImage >
Calculate DWI/EAP profile from SPF coefficients.
Author
Jian Cheng (JC), jian..nosp@m.chen.nosp@m.g.198.nosp@m.3@gm.nosp@m.ail.c.nosp@m.om
Definition at line 35 of file itkProfileFromSPFImageFilter.h.
Public Types
typedef Superclass::BasisType BasisType
typedef SmartPointer< const Self > ConstPointer
typedef Superclass::MatrixPointer MatrixPointer
typedef Superclass::MatrixType MatrixType
typedef SmartPointer< Self > Pointer
typedef ProfileFromSPFImageFilter Self
typedef Superclass::STDVectorPointer STDVectorPointer
typedef Superclass::STDVectorType STDVectorType
typedef FeaturesFromSPFImageFilter< TInputImage, TOutputImage > Superclass
typedef Superclass::VectorPointer VectorPointer
typedef Superclass::VectorType VectorType
Public Types inherited from itk::FeaturesFromSPFImageFilter< TInputImage, TOutputImage >
enum BasisType {
SPF =0,
DSPF
}
typedef SmartPointer< const Self > ConstPointer
typedef utl_shared_ptr< MatrixType > MatrixPointer
typedef utl::NDArray< double, 2 > MatrixType
typedef SmartPointer< Self > Pointer
typedef FeaturesFromSPFImageFilter Self
typedef SphericalPolarFourierEstimationImageFilter< TInputImage, TOutputImage > SPFIFilterBaseType
typedef utl_shared_ptr< STDVectorType > STDVectorPointer
typedef std::vector< double > STDVectorType
typedef MaskedImageToImageFilter< TInputImage, TOutputImage > Superclass
typedef utl_shared_ptr< VectorType > VectorPointer
typedef utl::NDArray< double, 1 > VectorType
Public Types inherited from itk::MaskedImageToImageFilter< TInputImage, TOutputImage >
typedef SmartPointer< const Self > ConstPointer
typedef InputImageType::ConstPointer InputImageConstPointer
typedef InputImageType::IndexType InputImageIndexType
typedef InputImageType::PixelType InputImagePixelType
typedef InputImageType::Pointer InputImagePointer
typedef InputImageType::RegionType InputImageRegionType
typedef InputImageType::SizeType InputImageSizeType
typedef InputImageType::SpacingType InputImageSpacingType
typedef TInputImage InputImageType
typedef LoggerType::Pointer LoggerPointer
typedef ThreadLogger LoggerType
typedef utl_shared_ptr< LoggerVectorType > LoggerVectorPointer
typedef std::vector< LoggerPointer > LoggerVectorType
typedef MaskImageType::Pointer MaskImagePointer
typedef Image< double, 3 > MaskImageType
typedef OutputImageType::IndexType OutputImageIndexType
typedef OutputImageType::PixelType OutputImagePixelType
typedef OutputImageType::Pointer OutputImagePointer
typedef OutputImageType::RegionType OutputImageRegionType
typedef OutputImageType::SizeType OutputImageSizeType
typedef OutputImageType::SpacingType OutputImageSpacingType
typedef TOutputImage OutputImageType
typedef SmartPointer< Self > Pointer
typedef MaskedImageToImageFilter Self
typedef ImageToImageFilter< TInputImage, TOutputImage > Superclass
Public Member Functions
void ComputeSPFToFeatureTransform () ITK_OVERRIDE
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual const char * GetNameOfClass () const
virtual double GetRadius ()
virtual STDVectorPointer GetRadiusVector ()
itkTypedefMaskedImageToImageMacro (Superclass)
virtual void SetRadius (double _arg)
virtual void SetRadiusVector (STDVectorPointer _arg)
Public Member Functions inherited from itk::FeaturesFromSPFImageFilter< TInputImage, TOutputImage >
double ComputeScale (const bool setScale=true)
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual double GetBasisScale ()
virtual BasisType GetBasisType ()
virtual bool GetIsFourier ()
virtual bool GetIsInQSpace ()
virtual double GetMD0 ()
virtual MatrixPointer GetOrientations ()
virtual int GetRadialRank ()
virtual const ScalarImageType * GetScaleImage () const
virtual int GetSHRank ()
virtual MatrixPointer GetSPFToFeatureTransform ()
virtual double GetTau ()
virtual void IsFourierOff ()
virtual void IsFourierOn ()
virtual void IsInQSpaceOff ()
virtual void IsInQSpaceOn ()
itkGetObjectMacro (ScaleImage, ScalarImageType)
itkTypedefMaskedImageToImageMacro (Superclass)
virtual void SetBasisScale (const double scale)
virtual void SetBasisType (BasisType _arg)
virtual void SetIsFourier (bool _arg)
virtual void SetIsInQSpace (bool _arg)
virtual void SetMD0 (double _arg)
virtual void SetOrientations (MatrixPointer _arg)
virtual void SetRadialRank (int _arg)
void SetScaleImage (const ScalarImagePointer &scaleImage)
virtual void SetSHRank (int _arg)
virtual void SetTau (double _arg)
Public Member Functions inherited from itk::MaskedImageToImageFilter< TInputImage, TOutputImage >
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual const LoggerType * GetLogger () const
virtual const MaskImageType * GetMaskImage () const
bool IsMaskUsed ()
itkGetObjectMacro (MaskImage, MaskImageType)
itkGetObjectMacro (Logger, LoggerType)
itkSetGetMacro (LogLevel, int)
virtual void SetLogger (LoggerType *_arg)
virtual void SetMaskImage (MaskImageType *_arg)
void SetMaskImage (const std::string &file)
Static Public Member Functions
static Pointer New ()
Static Public Member Functions inherited from itk::FeaturesFromSPFImageFilter< TInputImage, TOutputImage >
static Pointer New ()
Static Public Member Functions inherited from itk::MaskedImageToImageFilter< TInputImage, TOutputImage >
static Pointer New ()
Protected Member Functions
void BeforeThreadedGenerateData () ITK_OVERRIDE
void GenerateOutputInformation () ITK_OVERRIDE
LightObject::Pointer InternalClone () const ITK_OVERRIDE
void PrintSelf (std::ostream &os, Indent indent) const ITK_OVERRIDE
ProfileFromSPFImageFilter ()
void ThreadedGenerateData (const typename TOutputImage::RegionType &outputRegionForThread, ThreadIdType threadId) ITK_OVERRIDE
void VerifyInputParameters () const ITK_OVERRIDE
virtual ~ProfileFromSPFImageFilter ()
Protected Member Functions inherited from itk::FeaturesFromSPFImageFilter< TInputImage, TOutputImage >
void BeforeThreadedGenerateData () ITK_OVERRIDE
FeaturesFromSPFImageFilter ()
LightObject::Pointer InternalClone () const ITK_OVERRIDE
void SetSPFIEstimator ()
virtual ~FeaturesFromSPFImageFilter ()
Protected Member Functions inherited from itk::MaskedImageToImageFilter< TInputImage, TOutputImage >
void CreateLoggerVector ()
virtual void InitializeThreadedLibraries ()
LightObject::Pointer InternalClone () const ITK_OVERRIDE
MaskedImageToImageFilter ()
std::string ThreadIDToString () const
virtual void VerifyMaskInformation () const
void WriteLogger (const std::string &str, const LoggerBase::PriorityLevelType level=LoggerBase::DEBUG) const
virtual ~MaskedImageToImageFilter ()
Private Member Functions
void operator= (const Self &)
ProfileFromSPFImageFilter (const Self &)
Private Attributes
double m_Radius
STDVectorPointer m_RadiusVector
Additional Inherited Members
Static Public Attributes inherited from itk::MaskedImageToImageFilter< TInputImage, TOutputImage >
static const unsigned int InputImageDimension
static const unsigned int OutputImageDimension
Protected Attributes inherited from itk::FeaturesFromSPFImageFilter< TInputImage, TOutputImage >
double m_BasisScale
BasisType m_BasisType
bool m_IsFourier
bool m_IsInQSpace
double m_MD0
MatrixPointer m_Orientations
int m_RadialRank
ScalarImageType::Pointer m_ScaleImage
int m_SHRank
SPFIFilterBaseType::Pointer m_SPFIEstimator
MatrixPointer m_SPFToFeatureTransform
double m_Tau
Protected Attributes inherited from itk::MaskedImageToImageFilter< TInputImage, TOutputImage >
LoggerPointer m_Logger
LoggerVectorPointer m_LoggerVector
int m_LogLevel
MaskImagePointer m_MaskImage
int m_ThreadID
Member Typedef Documentation
template<class TInputImage , class TOutputImage > typedef Superclass::BasisType itk::ProfileFromSPFImageFilter< TInputImage, TOutputImage >::BasisType
Definition at line 57 of file itkProfileFromSPFImageFilter.h.
template<class TInputImage , class TOutputImage > typedef SmartPointer<const Self> itk::ProfileFromSPFImageFilter< TInputImage, TOutputImage >::ConstPointer
Definition at line 43 of file itkProfileFromSPFImageFilter.h.
template<class TInputImage , class TOutputImage > typedef Superclass::MatrixPointer itk::ProfileFromSPFImageFilter< TInputImage, TOutputImage >::MatrixPointer
Definition at line 54 of file itkProfileFromSPFImageFilter.h.
template<class TInputImage , class TOutputImage > typedef Superclass::MatrixType itk::ProfileFromSPFImageFilter< TInputImage, TOutputImage >::MatrixType
Definition at line 53 of file itkProfileFromSPFImageFilter.h.
template<class TInputImage , class TOutputImage > typedef SmartPointer<Self> itk::ProfileFromSPFImageFilter< TInputImage, TOutputImage >::Pointer
Definition at line 42 of file itkProfileFromSPFImageFilter.h.
template<class TInputImage , class TOutputImage > typedef ProfileFromSPFImageFilter itk::ProfileFromSPFImageFilter< TInputImage, TOutputImage >::Self
Standard class typedefs.
Definition at line 40 of file itkProfileFromSPFImageFilter.h.
template<class TInputImage , class TOutputImage > typedef Superclass::STDVectorPointer itk::ProfileFromSPFImageFilter< TInputImage, TOutputImage >::STDVectorPointer
Definition at line 59 of file itkProfileFromSPFImageFilter.h.
template<class TInputImage , class TOutputImage > typedef Superclass::STDVectorType itk::ProfileFromSPFImageFilter< TInputImage, TOutputImage >::STDVectorType
Definition at line 58 of file itkProfileFromSPFImageFilter.h.
template<class TInputImage , class TOutputImage > typedef FeaturesFromSPFImageFilter<TInputImage,TOutputImage> itk::ProfileFromSPFImageFilter< TInputImage, TOutputImage >::Superclass
Definition at line 41 of file itkProfileFromSPFImageFilter.h.
template<class TInputImage , class TOutputImage > typedef Superclass::VectorPointer itk::ProfileFromSPFImageFilter< TInputImage, TOutputImage >::VectorPointer
Definition at line 56 of file itkProfileFromSPFImageFilter.h.
template<class TInputImage , class TOutputImage > typedef Superclass::VectorType itk::ProfileFromSPFImageFilter< TInputImage, TOutputImage >::VectorType
Definition at line 55 of file itkProfileFromSPFImageFilter.h.
Constructor & Destructor Documentation
template<class TInputImage , class TOutputImage > itk::ProfileFromSPFImageFilter< TInputImage, TOutputImage >::ProfileFromSPFImageFilter () inline protected
Definition at line 71 of file itkProfileFromSPFImageFilter.h.
template<class TInputImage , class TOutputImage > virtual itk::ProfileFromSPFImageFilter< TInputImage, TOutputImage >::~ProfileFromSPFImageFilter () inline protected virtual
Definition at line 76 of file itkProfileFromSPFImageFilter.h.
References ITK_OVERRIDE.
template<class TInputImage , class TOutputImage > itk::ProfileFromSPFImageFilter< TInputImage, TOutputImage >::ProfileFromSPFImageFilter (const Self &) private
Member Function Documentation
template<class TInputImage , class TOutputImage > void itk::ProfileFromSPFImageFilter< TInputImage, TOutputImage >::BeforeThreadedGenerateData () protected
Definition at line 177 of file itkProfileFromSPFImageFilter.hxx.
template<class TInputImage , class TOutputImage > void itk::ProfileFromSPFImageFilter< TInputImage, TOutputImage >::ComputeSPFToFeatureTransform () virtual
Reimplemented from itk::FeaturesFromSPFImageFilter< TInputImage, TOutputImage >.
Definition at line 84 of file itkProfileFromSPFImageFilter.hxx.
References utlException, and utlShowPosition.
Referenced by itk::ProfileFromSPFImageFilter< TInputImage, TOutputImage >::InternalClone().
template<class TInputImage , class TOutputImage > virtual::itk::LightObject::Pointer itk::ProfileFromSPFImageFilter< TInputImage, TOutputImage >::CreateAnother (void) const
template<class TInputImage , class TOutputImage > void itk::ProfileFromSPFImageFilter< TInputImage, TOutputImage >::GenerateOutputInformation (void) protected
Definition at line 34 of file itkProfileFromSPFImageFilter.hxx.
References utl::RankToDimSH(), utlGlobalException, utlShowPosition, and itk::ProfileFromSPFImageFilter< TInputImage, TOutputImage >::VerifyInputParameters().
template<class TInputImage , class TOutputImage > virtual const char* itk::ProfileFromSPFImageFilter< TInputImage, TOutputImage >::GetNameOfClass () const virtual
Run-time type information (and related methods)
Reimplemented from itk::FeaturesFromSPFImageFilter< TInputImage, TOutputImage >.
template<class TInputImage , class TOutputImage > virtual double itk::ProfileFromSPFImageFilter< TInputImage, TOutputImage >::GetRadius () virtual
template<class TInputImage , class TOutputImage > virtual STDVectorPointer itk::ProfileFromSPFImageFilter< TInputImage, TOutputImage >::GetRadiusVector () virtual
template<class TInputImage , class TOutputImage > LightObject::Pointer itk::ProfileFromSPFImageFilter< TInputImage, TOutputImage >::InternalClone () const protected
Definition at line 67 of file itkProfileFromSPFImageFilter.hxx.
References itk::ProfileFromSPFImageFilter< TInputImage, TOutputImage >::ComputeSPFToFeatureTransform().
Referenced by itk::ProfileFromSPFImageFilter< TInputImage, TOutputImage >::VerifyInputParameters().
template<class TInputImage , class TOutputImage > itk::ProfileFromSPFImageFilter< TInputImage, TOutputImage >::itkTypedefMaskedImageToImageMacro (Superclass)
template<class TInputImage , class TOutputImage > static Pointer itk::ProfileFromSPFImageFilter< TInputImage, TOutputImage >::New () static
Method for creation through the object factory.
template<class TInputImage , class TOutputImage > void itk::ProfileFromSPFImageFilter< TInputImage, TOutputImage >::operator= (const Self &) private
template<class TInputImage , class TOutputImage > void itk::ProfileFromSPFImageFilter< TInputImage, TOutputImage >::PrintSelf (std::ostream & os, Indent indent) const protected virtual
Reimplemented from itk::FeaturesFromSPFImageFilter< TInputImage, TOutputImage >.
Definition at line 290 of file itkProfileFromSPFImageFilter.hxx.
template<class TInputImage , class TOutputImage > virtual void itk::ProfileFromSPFImageFilter< TInputImage, TOutputImage >::SetRadius (double _arg) virtual
template<class TInputImage , class TOutputImage > virtual void itk::ProfileFromSPFImageFilter< TInputImage, TOutputImage >::SetRadiusVector (STDVectorPointer _arg) virtual
template<class TInputImage , class TOutputImage > void itk::ProfileFromSPFImageFilter< TInputImage, TOutputImage >::ThreadedGenerateData (const typename TOutputImage::RegionType & outputRegionForThread, ThreadIdType threadId) protected
Definition at line 214 of file itkProfileFromSPFImageFilter.hxx.
template<class TInputImage , class TOutputImage > void itk::ProfileFromSPFImageFilter< TInputImage, TOutputImage >::VerifyInputParameters () const protected virtual
Reimplemented from itk::FeaturesFromSPFImageFilter< TInputImage, TOutputImage >.
Definition at line 57 of file itkProfileFromSPFImageFilter.hxx.
References itk::ProfileFromSPFImageFilter< TInputImage, TOutputImage >::InternalClone(), utlGlobalException, and utlShowPosition.
Referenced by itk::ProfileFromSPFImageFilter< TInputImage, TOutputImage >::GenerateOutputInformation().
Member Data Documentation
template<class TInputImage , class TOutputImage > double itk::ProfileFromSPFImageFilter< TInputImage, TOutputImage >::m_Radius private
b value or r value, which is dependent on m_IsInQSpace
Definition at line 92 of file itkProfileFromSPFImageFilter.h.
template<class TInputImage , class TOutputImage > STDVectorPointer itk::ProfileFromSPFImageFilter< TInputImage, TOutputImage >::m_RadiusVector private
If it is set, the output will be samples, not SH coefficients
Definition at line 95 of file itkProfileFromSPFImageFilter.h.
The documentation for this class was generated from the following files:
Modules/DiffusionModels/include/itkProfileFromSPFImageFilter.h
Modules/DiffusionModels/include/itkProfileFromSPFImageFilter.hxx