DMRITool: spams::FISTA::LogLoss< T, weighted > Class Template Reference
spams::FISTA::LogLoss< T, weighted > Class Template Reference
#include <fista.h>
Detailed Description
template<typename T, bool weighted = false>
class spams::FISTA::LogLoss< T, weighted >
Definition at line 591 of file fista.h.
Public Member Functions
T eval (const Vector< T > &w) const
virtual T fenchel (const Vector< T > &input) const
void grad (const Vector< T > &w, Vector< T > &grad) const
void init (const Vector< T > &y)
virtual bool is_fenchel () const
LogLoss (const AbstractMatrixB< T > &X)
virtual void var_fenchel (const Vector< T > &w, Vector< T > &grad1, Vector< T > &grad2, const bool intercept) const
virtual ~LogLoss ()
Public Member Functions inherited from spams::FISTA::Loss< T >
Loss ()
virtual bool test_backtracking (const Vector< T > &y, const Vector< T > &grad, const Vector< T > &prox, const T L) const
virtual ~Loss ()
Private Member Functions
LogLoss (const LogLoss< T, weighted > &dict)
LogLoss< T, weighted > & operator= (const LogLoss< T, weighted > &dict)
Private Attributes
T _weightneg
T _weightpos
const AbstractMatrixB< T > * _X
Vector< T > _y
Constructor & Destructor Documentation
template<typename T, bool weighted = false> spams::FISTA::LogLoss< T, weighted >::LogLoss (const AbstractMatrixB< T > & X) inline
Definition at line 593 of file fista.h.
template<typename T, bool weighted = false> virtual spams::FISTA::LogLoss< T, weighted >::~LogLoss () inline virtual
Definition at line 594 of file fista.h.
template<typename T, bool weighted = false> spams::FISTA::LogLoss< T, weighted >::LogLoss (const LogLoss< T, weighted > & dict) explicit private
Member Function Documentation
template<typename T, bool weighted = false> T spams::FISTA::LogLoss< T, weighted >::eval (const Vector< T > & w) const inline virtual
Implements spams::FISTA::Loss< T >.
Definition at line 607 of file fista.h.
References spams::Vector< T >::n(), and spams::Vector< T >::toSparse().
template<typename T, bool weighted = false> virtual T spams::FISTA::LogLoss< T, weighted >::fenchel (const Vector< T > & input) const inline virtual
Implements spams::FISTA::Loss< T >.
Definition at line 645 of file fista.h.
References spams::Vector< T >::n(), and spams::xlogx().
template<typename T, bool weighted = false> void spams::FISTA::LogLoss< T, weighted >::grad (const Vector< T > & w, Vector< T > & grad) const inline virtual
Implements spams::FISTA::Loss< T >.
Definition at line 624 of file fista.h.
References spams::Vector< T >::n(), spams::Vector< T >::scal(), and spams::Vector< T >::toSparse().
template<typename T, bool weighted = false> void spams::FISTA::LogLoss< T, weighted >::init (const Vector< T > & y) inline virtual
Implements spams::FISTA::Loss< T >.
Definition at line 596 of file fista.h.
References MAX, and spams::Vector< T >::n().
template<typename T, bool weighted = false> virtual bool spams::FISTA::LogLoss< T, weighted >::is_fenchel () const inline virtual
Reimplemented from spams::FISTA::Loss< T >.
Definition at line 644 of file fista.h.
template<typename T, bool weighted = false> LogLoss<T,weighted>& spams::FISTA::LogLoss< T, weighted >::operator= (const LogLoss< T, weighted > & dict) private
template<typename T, bool weighted = false> virtual void spams::FISTA::LogLoss< T, weighted >::var_fenchel (const Vector< T > & w, Vector< T > & grad1, Vector< T > & grad2, const bool intercept) const inline virtual
Implements spams::FISTA::Loss< T >.
Definition at line 662 of file fista.h.
References spams::Vector< T >::add(), spams::Vector< T >::exp(), spams::Vector< T >::inv(), spams::Vector< T >::mult(), spams::Vector< T >::n(), spams::Vector< T >::neg(), spams::Vector< T >::project_sft_binary(), spams::Vector< T >::resize(), spams::Vector< T >::scal(), and spams::Vector< T >::toSparse().
Member Data Documentation
template<typename T, bool weighted = false> T spams::FISTA::LogLoss< T, weighted >::_weightneg private
Definition at line 685 of file fista.h.
template<typename T, bool weighted = false> T spams::FISTA::LogLoss< T, weighted >::_weightpos private
Definition at line 684 of file fista.h.
template<typename T, bool weighted = false> const AbstractMatrixB<T>* spams::FISTA::LogLoss< T, weighted >::_X private
Definition at line 682 of file fista.h.
template<typename T, bool weighted = false> Vector<T> spams::FISTA::LogLoss< T, weighted >::_y private
Definition at line 683 of file fista.h.
The documentation for this class was generated from the following file:
ThirdParty/Spams/include/fista.h