DMRITool: itk::SamplingSchemeQSpaceWriter< TSamplingType > Class Template Reference
itk::SamplingSchemeQSpaceWriter< TSamplingType > Class Template Reference
SamplingScheme
#include <itkSamplingSchemeQSpaceWriter.h>
Detailed Description
template<class TSamplingType>
class itk::SamplingSchemeQSpaceWriter< TSamplingType >
write orientations and b values (single/multiple shells) into text files
Author
Jian Cheng (JC), jian..nosp@m.chen.nosp@m.g.198.nosp@m.3@gm.nosp@m.ail.c.nosp@m.om
Definition at line 34 of file itkSamplingSchemeQSpaceWriter.h.
Public Types
typedef SmartPointer< const Self > ConstPointer
typedef SmartPointer< Self > Pointer
typedef SamplingType::Pointer SamplingPointer
typedef TSamplingType SamplingType
typedef SamplingSchemeQSpaceWriter Self
typedef LightProcessObject Superclass
Public Member Functions
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual std::string GetBFile ()
virtual const char * GetNameOfClass () const
virtual std::string GetOrientationFile ()
virtual bool GetSaveAllShellsInOneFile ()
virtual bool GetSaveSingleShell ()
itkGetObjectMacro (Sampling, SamplingType)
virtual void SaveAllShellsInOneFileOff ()
virtual void SaveAllShellsInOneFileOn ()
virtual void SaveSingleShellOff ()
virtual void SaveSingleShellOn ()
virtual void SetBFile (std::string _arg)
virtual void SetOrientationFile (std::string _arg)
virtual void SetSampling (SamplingType *_arg)
virtual void SetSaveAllShellsInOneFile (bool _arg)
virtual void SetSaveSingleShell (bool _arg)
void Update ()
Static Public Member Functions
static Pointer New ()
Protected Member Functions
void PrintSelf (std::ostream &os, Indent indent) const ITK_OVERRIDE
SamplingSchemeQSpaceWriter ()
~SamplingSchemeQSpaceWriter ()
Protected Attributes
std::string m_BFile
std::string m_OrientationFile
SamplingPointer m_Sampling
bool m_SaveAllShellsInOneFile
bool m_SaveSingleShell
Private Member Functions
void operator= (const Self &)
SamplingSchemeQSpaceWriter (const Self &)
Member Typedef Documentation
template<class TSamplingType > typedef SmartPointer< const Self > itk::SamplingSchemeQSpaceWriter< TSamplingType >::ConstPointer
Definition at line 41 of file itkSamplingSchemeQSpaceWriter.h.
template<class TSamplingType > typedef SmartPointer<Self> itk::SamplingSchemeQSpaceWriter< TSamplingType >::Pointer
Definition at line 40 of file itkSamplingSchemeQSpaceWriter.h.
template<class TSamplingType > typedef SamplingType::Pointer itk::SamplingSchemeQSpaceWriter< TSamplingType >::SamplingPointer
Definition at line 44 of file itkSamplingSchemeQSpaceWriter.h.
template<class TSamplingType > typedef TSamplingType itk::SamplingSchemeQSpaceWriter< TSamplingType >::SamplingType
Definition at line 43 of file itkSamplingSchemeQSpaceWriter.h.
template<class TSamplingType > typedef SamplingSchemeQSpaceWriter itk::SamplingSchemeQSpaceWriter< TSamplingType >::Self
Standard class typedefs.
Definition at line 38 of file itkSamplingSchemeQSpaceWriter.h.
template<class TSamplingType > typedef LightProcessObject itk::SamplingSchemeQSpaceWriter< TSamplingType >::Superclass
Definition at line 39 of file itkSamplingSchemeQSpaceWriter.h.
Constructor & Destructor Documentation
template<class TSamplingType > itk::SamplingSchemeQSpaceWriter< TSamplingType >::SamplingSchemeQSpaceWriter (const Self &) private
template<class TSamplingType > itk::SamplingSchemeQSpaceWriter< TSamplingType >::SamplingSchemeQSpaceWriter () protected
Definition at line 31 of file itkSamplingSchemeQSpaceWriter.hxx.
References itk::SamplingSchemeQSpaceWriter< TSamplingType >::PrintSelf().
template<class TSamplingType > itk::SamplingSchemeQSpaceWriter< TSamplingType >::~SamplingSchemeQSpaceWriter () inline protected
Definition at line 80 of file itkSamplingSchemeQSpaceWriter.h.
References ITK_OVERRIDE.
Member Function Documentation
template<class TSamplingType > virtual::itk::LightObject::Pointer itk::SamplingSchemeQSpaceWriter< TSamplingType >::CreateAnother (void) const
template<class TSamplingType > virtual std::string itk::SamplingSchemeQSpaceWriter< TSamplingType >::GetBFile () virtual
template<class TSamplingType > virtual const char* itk::SamplingSchemeQSpaceWriter< TSamplingType >::GetNameOfClass () const virtual
Run-time type information (and related methods).
template<class TSamplingType > virtual std::string itk::SamplingSchemeQSpaceWriter< TSamplingType >::GetOrientationFile () virtual
template<class TSamplingType > virtual bool itk::SamplingSchemeQSpaceWriter< TSamplingType >::GetSaveAllShellsInOneFile () virtual
template<class TSamplingType > virtual bool itk::SamplingSchemeQSpaceWriter< TSamplingType >::GetSaveSingleShell () virtual
template<class TSamplingType > itk::SamplingSchemeQSpaceWriter< TSamplingType >::itkGetObjectMacro (Sampling , SamplingType)
template<class TSamplingType > static Pointer itk::SamplingSchemeQSpaceWriter< TSamplingType >::New () static
Method for creation through the object factory.
template<class TSamplingType > void itk::SamplingSchemeQSpaceWriter< TSamplingType >::operator= (const Self &) private
template<class TSamplingType > void itk::SamplingSchemeQSpaceWriter< TSamplingType >::PrintSelf (std::ostream & os, Indent indent) const protected
Definition at line 45 of file itkSamplingSchemeQSpaceWriter.hxx.
References itk::SamplingSchemeQSpaceWriter< TSamplingType >::Update().
Referenced by itk::SamplingSchemeQSpaceWriter< TSamplingType >::SamplingSchemeQSpaceWriter().
template<class TSamplingType > virtual void itk::SamplingSchemeQSpaceWriter< TSamplingType >::SaveAllShellsInOneFileOff () virtual
template<class TSamplingType > virtual void itk::SamplingSchemeQSpaceWriter< TSamplingType >::SaveAllShellsInOneFileOn () virtual
template<class TSamplingType > virtual void itk::SamplingSchemeQSpaceWriter< TSamplingType >::SaveSingleShellOff () virtual
template<class TSamplingType > virtual void itk::SamplingSchemeQSpaceWriter< TSamplingType >::SaveSingleShellOn () virtual
template<class TSamplingType > virtual void itk::SamplingSchemeQSpaceWriter< TSamplingType >::SetBFile (std::string _arg) virtual
template<class TSamplingType > virtual void itk::SamplingSchemeQSpaceWriter< TSamplingType >::SetOrientationFile (std::string _arg) virtual
template<class TSamplingType > virtual void itk::SamplingSchemeQSpaceWriter< TSamplingType >::SetSampling (SamplingType * _arg) virtual
template<class TSamplingType > virtual void itk::SamplingSchemeQSpaceWriter< TSamplingType >::SetSaveAllShellsInOneFile (bool _arg) virtual
template<class TSamplingType > virtual void itk::SamplingSchemeQSpaceWriter< TSamplingType >::SetSaveSingleShell (bool _arg) virtual
template<class TSamplingType > void itk::SamplingSchemeQSpaceWriter< TSamplingType >::Update ()
Definition at line 59 of file itkSamplingSchemeQSpaceWriter.hxx.
References utl::ConvertNumberToString(), utl::GetFileExtension(), utl::SaveVector(), and utlGlobalException.
Referenced by itk::SamplingSchemeQSpaceWriter< TSamplingType >::PrintSelf().
Member Data Documentation
template<class TSamplingType > std::string itk::SamplingSchemeQSpaceWriter< TSamplingType >::m_BFile protected
If it is set, save b values
Definition at line 85 of file itkSamplingSchemeQSpaceWriter.h.
template<class TSamplingType > std::string itk::SamplingSchemeQSpaceWriter< TSamplingType >::m_OrientationFile protected
This is must be set
Definition at line 88 of file itkSamplingSchemeQSpaceWriter.h.
template<class TSamplingType > SamplingPointer itk::SamplingSchemeQSpaceWriter< TSamplingType >::m_Sampling protected
input sampling scheme including orientations and b values
Definition at line 94 of file itkSamplingSchemeQSpaceWriter.h.
template<class TSamplingType > bool itk::SamplingSchemeQSpaceWriter< TSamplingType >::m_SaveAllShellsInOneFile protected
If it is set, save all data.
Definition at line 100 of file itkSamplingSchemeQSpaceWriter.h.
template<class TSamplingType > bool itk::SamplingSchemeQSpaceWriter< TSamplingType >::m_SaveSingleShell protected
If it is true, save single shell data.
Definition at line 97 of file itkSamplingSchemeQSpaceWriter.h.
The documentation for this class was generated from the following files:
Modules/SamplingScheme/include/itkSamplingSchemeQSpaceWriter.h
Modules/SamplingScheme/include/itkSamplingSchemeQSpaceWriter.hxx