DMRITool: VTKViewer Class Reference
VTKViewer Class Reference
#include <VTKViewer.h>
Detailed Description
Definition at line 26 of file VTKViewer.h.
Public Slots
void nextStereoType ()
void rotate ()
void screenshot ()
void setsize (double s1, double s2)
void setStereoType (int vtkStereoType)
void toggleRotate ()
void toggleStereo ()
Public Member Functions
void add (vtkPolyData *polyData)
void add (const char *file_name)
VTKViewer ()
Private Attributes
vtkSmartPointer< vtkRenderer > m_renderer
double m_size [2]
QTimer m_timer
Constructor & Destructor Documentation
VTKViewer::VTKViewer ()
Definition at line 222 of file VTKViewer.cxx.
References GetVTKStereoType(), m_renderer, m_size, m_timer, and rotate().
Member Function Documentation
void VTKViewer::add (vtkPolyData * polyData)
Definition at line 255 of file VTKViewer.cxx.
References m_renderer, and setInputData.
Referenced by add(), and main().
void VTKViewer::add (const char * file_name)
Definition at line 288 of file VTKViewer.cxx.
References add(), ConvertDataSetToSurface(), ReadLegacyVTK(), and ReadPDB().
void VTKViewer::nextStereoType () slot
Definition at line 377 of file VTKViewer.cxx.
References m_renderer, and setStereoType().
void VTKViewer::rotate () slot
Definition at line 354 of file VTKViewer.cxx.
References m_renderer.
Referenced by VTKViewer().
void VTKViewer::screenshot () slot
Definition at line 399 of file VTKViewer.cxx.
void VTKViewer::setsize (double s1, double s2) slot
Definition at line 249 of file VTKViewer.cxx.
References m_size.
void VTKViewer::setStereoType (int vtkStereoType) slot
Definition at line 362 of file VTKViewer.cxx.
References m_renderer.
Referenced by nextStereoType().
void VTKViewer::toggleRotate () slot
Definition at line 346 of file VTKViewer.cxx.
References m_timer.
void VTKViewer::toggleStereo () slot
Definition at line 369 of file VTKViewer.cxx.
References m_renderer.
Member Data Documentation
vtkSmartPointer< vtkRenderer > VTKViewer::m_renderer private
Definition at line 42 of file VTKViewer.h.
Referenced by add(), nextStereoType(), rotate(), setStereoType(), toggleStereo(), and VTKViewer().
double VTKViewer::m_size[2] private
Definition at line 44 of file VTKViewer.h.
Referenced by setsize(), and VTKViewer().
QTimer VTKViewer::m_timer private
Definition at line 41 of file VTKViewer.h.
Referenced by toggleRotate(), and VTKViewer().
The documentation for this class was generated from the following files:
QTApplications/vtkviewer/VTKViewer.h
QTApplications/vtkviewer/VTKViewer.cxx