DMRITool: itk::CommandProgressUpdate Class Reference
itk::CommandProgressUpdate Class Reference
#include <itkCommandProgressUpdate.h>
Detailed Description
Observer for progress notification.
Author
Pew-Thian Yap, UNC Chapel Hill, ptyap.nosp@m.@med.nosp@m..unc..nosp@m.edu
Definition at line 33 of file itkCommandProgressUpdate.h.
Public Types
typedef RealTimeClock ClockType
typedef SmartPointer< Self > Pointer
typedef CommandProgressUpdate Self
enum StyleType {
LIST =0,
BAR
}
typedef Command Superclass
typedef ClockType::TimeStampType TimeStampType
Public Member Functions
virtual ::itk::LightObject::Pointer CreateAnother (void) const
void Execute (Object *caller, const EventObject &event) ITK_OVERRIDE
void Execute (const Object *object, const EventObject &event) ITK_OVERRIDE
virtual StyleType GetStyle () const
virtual bool GetUseColor () const
virtual void SetStyle (StyleType _arg)
virtual void SetUseColor (bool _arg)
virtual void UseColorOff ()
virtual void UseColorOn ()
Static Public Member Functions
static Pointer New ()
Static Public Attributes
static const unsigned int NumberOfBarSegments = 20
Protected Member Functions
CommandProgressUpdate ()
Private Attributes
TimeProbe clock
ClockType::Pointer m_Clock
float m_LastProgress
TimeStampType m_StartTimeStamp
StyleType m_Style
bool m_SuppressOutput
bool m_UseColor
Member Typedef Documentation
typedef RealTimeClock itk::CommandProgressUpdate::ClockType
Definition at line 39 of file itkCommandProgressUpdate.h.
typedef SmartPointer<Self> itk::CommandProgressUpdate::Pointer
Definition at line 38 of file itkCommandProgressUpdate.h.
typedef CommandProgressUpdate itk::CommandProgressUpdate::Self
Definition at line 36 of file itkCommandProgressUpdate.h.
typedef Command itk::CommandProgressUpdate::Superclass
Definition at line 37 of file itkCommandProgressUpdate.h.
typedef ClockType::TimeStampType itk::CommandProgressUpdate::TimeStampType
Definition at line 42 of file itkCommandProgressUpdate.h.
Member Enumeration Documentation
enum itk::CommandProgressUpdate::StyleType
Enumerator
LIST
BAR
Definition at line 48 of file itkCommandProgressUpdate.h.
Constructor & Destructor Documentation
itk::CommandProgressUpdate::CommandProgressUpdate () inline protected
Definition at line 55 of file itkCommandProgressUpdate.h.
References BAR, m_Clock, m_LastProgress, m_StartTimeStamp, m_Style, m_SuppressOutput, and UseColorOn().
Member Function Documentation
virtual::itk::LightObject::Pointer itk::CommandProgressUpdate::CreateAnother (void) const
void itk::CommandProgressUpdate::Execute (Object * caller, const EventObject & event) inline
Definition at line 75 of file itkCommandProgressUpdate.h.
void itk::CommandProgressUpdate::Execute (const Object * object, const EventObject & event) inline
Definition at line 80 of file itkCommandProgressUpdate.h.
References BAR, LIST, and m_LastProgress.
virtual StyleType itk::CommandProgressUpdate::GetStyle () const virtual
virtual bool itk::CommandProgressUpdate::GetUseColor () const virtual
static Pointer itk::CommandProgressUpdate::New () static
Referenced by main().
virtual void itk::CommandProgressUpdate::SetStyle (StyleType _arg) virtual
virtual void itk::CommandProgressUpdate::SetUseColor (bool _arg) virtual
virtual void itk::CommandProgressUpdate::UseColorOff () virtual
virtual void itk::CommandProgressUpdate::UseColorOn () virtual
Referenced by CommandProgressUpdate().
Member Data Documentation
TimeProbe itk::CommandProgressUpdate::clock private
Definition at line 66 of file itkCommandProgressUpdate.h.
ClockType::Pointer itk::CommandProgressUpdate::m_Clock private
Definition at line 70 of file itkCommandProgressUpdate.h.
Referenced by CommandProgressUpdate().
float itk::CommandProgressUpdate::m_LastProgress private
Definition at line 72 of file itkCommandProgressUpdate.h.
Referenced by CommandProgressUpdate(), and Execute().
TimeStampType itk::CommandProgressUpdate::m_StartTimeStamp private
Definition at line 71 of file itkCommandProgressUpdate.h.
Referenced by CommandProgressUpdate().
StyleType itk::CommandProgressUpdate::m_Style private
Definition at line 68 of file itkCommandProgressUpdate.h.
Referenced by CommandProgressUpdate().
bool itk::CommandProgressUpdate::m_SuppressOutput private
Definition at line 69 of file itkCommandProgressUpdate.h.
Referenced by CommandProgressUpdate().
bool itk::CommandProgressUpdate::m_UseColor private
Definition at line 67 of file itkCommandProgressUpdate.h.
const unsigned int itk::CommandProgressUpdate::NumberOfBarSegments = 20 static
Definition at line 49 of file itkCommandProgressUpdate.h.
The documentation for this class was generated from the following file:
Modules/Observers/include/itkCommandProgressUpdate.h