DMRITool: spams::FISTA::SpecGraphMat< T > Class Template Reference
spams::FISTA::SpecGraphMat< T > Class Template Reference abstract
#include <fista.h>
Detailed Description
template<typename T>
class spams::FISTA::SpecGraphMat< T >
Definition at line 2278 of file fista.h.
Public Member Functions
virtual void dummy ()=0
T eval (const Matrix< T > &X) const
void fenchel (const Matrix< T > &input, T &val, T &scal) const
virtual bool is_fenchel () const
void prox (const Matrix< T > &x, Matrix< T > &y, const T lambda)
void reset ()
SpecGraphMat (const ParamReg< T > &param)
virtual ~SpecGraphMat ()
Public Member Functions inherited from spams::FISTA::Regularizer< T, Matrix< T > >
virtual T eval_dual_norm (const Matrix< T > &x) const
virtual T eval_dual_norm_paths (const Matrix< T > &x, SpMatrix< T > &path) const
virtual T eval_paths (const Matrix< T > &x, SpMatrix< T > &paths_mat) const
virtual bool is_intercept () const
virtual bool is_subgrad () const
Regularizer ()
Regularizer (const ParamReg< T > &param)
virtual void sub_grad (const Matrix< T > &input, Matrix< T > &output) const
virtual ~Regularizer ()
Protected Attributes
GraphLasso< T > * _graphlasso
Protected Attributes inherited from spams::FISTA::Regularizer< T, Matrix< T > >
bool _intercept
bool _pos
Constructor & Destructor Documentation
template<typename T > spams::FISTA::SpecGraphMat< T >::SpecGraphMat (const ParamReg< T > & param) inline
Definition at line 2280 of file fista.h.
template<typename T > virtual spams::FISTA::SpecGraphMat< T >::~SpecGraphMat () inline virtual
Definition at line 2281 of file fista.h.
Member Function Documentation
template<typename T > virtual void spams::FISTA::SpecGraphMat< T >::dummy () pure virtual
Implemented in spams::FISTA::GraphMult< T >, spams::FISTA::TreeMult< T >, and spams::FISTA::MixedL1LINFCR< T >.
template<typename T > T spams::FISTA::SpecGraphMat< T >::eval (const Matrix< T > & X) const inline virtual
Implements spams::FISTA::Regularizer< T, Matrix< T > >.
Definition at line 2294 of file fista.h.
References spams::Matrix< T >::toVect().
template<typename T > void spams::FISTA::SpecGraphMat< T >::fenchel (const Matrix< T > & input, T & val, T & scal) const inline virtual
returns phi^star(input) and ouput=input if the fenchel is unconstrained returns 0 and scale input such that phi^star(output)=0 otherwise
Implements spams::FISTA::Regularizer< T, Matrix< T > >.
Definition at line 2300 of file fista.h.
References spams::Matrix< T >::toVect().
template<typename T > virtual bool spams::FISTA::SpecGraphMat< T >::is_fenchel () const inline virtual
Reimplemented from spams::FISTA::Regularizer< T, Matrix< T > >.
Definition at line 2305 of file fista.h.
template<typename T > void spams::FISTA::SpecGraphMat< T >::prox (const Matrix< T > & x, Matrix< T > & y, const T lambda) inline virtual
Implements spams::FISTA::Regularizer< T, Matrix< T > >.
Definition at line 2287 of file fista.h.
References spams::Matrix< T >::m(), spams::Matrix< T >::n(), spams::Matrix< T >::resize(), and spams::Matrix< T >::toVect().
template<typename T > void spams::FISTA::SpecGraphMat< T >::reset () inline virtual
Reimplemented from spams::FISTA::Regularizer< T, Matrix< T > >.
Definition at line 2285 of file fista.h.
Member Data Documentation
template<typename T > GraphLasso<T>* spams::FISTA::SpecGraphMat< T >::_graphlasso protected
Definition at line 2307 of file fista.h.
The documentation for this class was generated from the following file:
ThirdParty/Spams/include/fista.h