DMRITool: itk::FiberTractsWriter Class Reference
itk::FiberTractsWriter Class Reference
#include <itkFiberTractsWriter.h>
Detailed Description
Definition at line 23 of file itkFiberTractsWriter.h.
Public Types
typedef FiberTractsType::FiberPointer FiberPointer
typedef FiberTractsType::Pointer FiberTractsPointer
typedef FiberTracts< double > FiberTractsType
typedef FiberTractsType::FiberType FiberType
typedef SmartPointer< Self > Pointer
typedef FiberTractsWriter Self
typedef FiberType::STDVectorType STDVectorType
typedef LightProcessObject Superclass
typedef FiberType::VertexType VertexType
Public Member Functions
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual const char * GetNameOfClass () const
itkSetGetMacro (FileName, std::string)
itkSetGetMacro (FiberTracts, FiberTractsPointer)
virtual void Update ()
void WriteTractsTCK ()
void WriteTractsTRK ()
Static Public Member Functions
static Pointer New ()
Protected Member Functions
FiberTractsWriter ()
void PrintSelf (std::ostream &os, Indent indent) const ITK_OVERRIDE
~FiberTractsWriter ()
Protected Attributes
FiberTractsPointer m_FiberTracts = FiberTractsType::New()
std::string m_FileName
Private Member Functions
FiberTractsWriter (const Self &)
void operator= (const Self &)
Member Typedef Documentation
typedef FiberTractsType::FiberPointer itk::FiberTractsWriter::FiberPointer
Definition at line 40 of file itkFiberTractsWriter.h.
typedef FiberTractsType::Pointer itk::FiberTractsWriter::FiberTractsPointer
Definition at line 38 of file itkFiberTractsWriter.h.
typedef FiberTracts<double> itk::FiberTractsWriter::FiberTractsType
Definition at line 35 of file itkFiberTractsWriter.h.
typedef FiberTractsType::FiberType itk::FiberTractsWriter::FiberType
Definition at line 39 of file itkFiberTractsWriter.h.
typedef SmartPointer<Self> itk::FiberTractsWriter::Pointer
Definition at line 29 of file itkFiberTractsWriter.h.
typedef FiberTractsWriter itk::FiberTractsWriter::Self
Standard class typedefs.
Definition at line 27 of file itkFiberTractsWriter.h.
typedef FiberType::STDVectorType itk::FiberTractsWriter::STDVectorType
Definition at line 41 of file itkFiberTractsWriter.h.
typedef LightProcessObject itk::FiberTractsWriter::Superclass
Definition at line 28 of file itkFiberTractsWriter.h.
typedef FiberType::VertexType itk::FiberTractsWriter::VertexType
Definition at line 42 of file itkFiberTractsWriter.h.
Constructor & Destructor Documentation
itk::FiberTractsWriter::FiberTractsWriter () inline protected
Definition at line 57 of file itkFiberTractsWriter.h.
itk::FiberTractsWriter::~FiberTractsWriter () inline protected
Definition at line 58 of file itkFiberTractsWriter.h.
itk::FiberTractsWriter::FiberTractsWriter (const Self &) private
Member Function Documentation
virtual::itk::LightObject::Pointer itk::FiberTractsWriter::CreateAnother (void) const
virtual const char* itk::FiberTractsWriter::GetNameOfClass () const virtual
Run-time type information (and related methods).
itk::FiberTractsWriter::itkSetGetMacro (FileName , std::string)
itk::FiberTractsWriter::itkSetGetMacro (FiberTracts , FiberTractsPointer)
static Pointer itk::FiberTractsWriter::New () static
Method for creation through the object factory.
Referenced by itk::SaveFibers().
void itk::FiberTractsWriter::operator= (const Self &) private
void itk::FiberTractsWriter::PrintSelf (std::ostream & os, Indent indent) const inline protected
Definition at line 60 of file itkFiberTractsWriter.h.
References PrintVar.
void itk::FiberTractsWriter::Update () virtual
Does the real work.
Definition at line 20 of file itkFiberTractsWriter.hxx.
References utl::GetFiberTractsFormatFromFileExtension(), m_FileName, TRACTS_TCK, TRACTS_TRK, TRACTS_VTK, utlGlobalException, WriteTractsTCK(), and WriteTractsTRK().
void itk::FiberTractsWriter::WriteTractsTCK ()
Definition at line 89 of file itkFiberTractsWriter.hxx.
References utlGlobalException.
Referenced by Update().
void itk::FiberTractsWriter::WriteTractsTRK ()
Definition at line 38 of file itkFiberTractsWriter.hxx.
References itk::GetDimensionOfProperties(), itk::GetDimensionOfScalars(), m_FiberTracts, m_FileName, utlSAGlobalException, and itk::WriteTrackVisHeader().
Referenced by Update().
Member Data Documentation
FiberTractsPointer itk::FiberTractsWriter::m_FiberTracts = FiberTractsType::New() protected
Definition at line 69 of file itkFiberTractsWriter.h.
Referenced by WriteTractsTRK().
std::string itk::FiberTractsWriter::m_FileName protected
Definition at line 67 of file itkFiberTractsWriter.h.
Referenced by Update(), and WriteTractsTRK().
The documentation for this class was generated from the following files:
Modules/Tractography/include/itkFiberTractsWriter.h
Modules/Tractography/include/itkFiberTractsWriter.hxx