DMRITool: itk::DiffusionModelEstimationImageFilter< TInputImage, TOutputImage > Class Template Reference
itk::DiffusionModelEstimationImageFilter< TInputImage, TOutputImage > Class Template Reference
DiffusionModels
#include <itkDiffusionModelEstimationImageFilter.h>
Detailed Description
template<class TInputImage, class TOutputImage>
class itk::DiffusionModelEstimationImageFilter< TInputImage, TOutputImage >
base filter for estimation of diffusion models
Author
Jian Cheng (JC), jian..nosp@m.chen.nosp@m.g.198.nosp@m.3@gm.nosp@m.ail.c.nosp@m.om
Definition at line 42 of file itkDiffusionModelEstimationImageFilter.h.
Public Types
typedef SmartPointer< const Self > ConstPointer
typedef utl_shared_ptr< MatrixType > MatrixPointer
typedef utl::NDArray< double, 2 > MatrixType
typedef SmartPointer< Self > Pointer
typedef SamplingSchemeQSpaceType::Pointer SamplingSchemeQSpacePointer
typedef SamplingSchemeQSpace< double > SamplingSchemeQSpaceType
typedef SamplingSchemeRSpaceType::Pointer SamplingSchemeRSpacePointer
typedef SamplingScheme3D< double > SamplingSchemeRSpaceType
typedef DiffusionModelEstimationImageFilter Self
typedef utl_shared_ptr< STDVectorType > STDVectorPointer
typedef std::vector< double > STDVectorType
typedef MaskedImageToImageFilter< TInputImage, TOutputImage > Superclass
typedef utl_shared_ptr< VectorType > VectorPointer
typedef utl::NDArray< double, 1 > VectorType
Public Types inherited from itk::MaskedImageToImageFilter< TInputImage, TOutputImage >
typedef SmartPointer< const Self > ConstPointer
typedef InputImageType::ConstPointer InputImageConstPointer
typedef InputImageType::IndexType InputImageIndexType
typedef InputImageType::PixelType InputImagePixelType
typedef InputImageType::Pointer InputImagePointer
typedef InputImageType::RegionType InputImageRegionType
typedef InputImageType::SizeType InputImageSizeType
typedef InputImageType::SpacingType InputImageSpacingType
typedef TInputImage InputImageType
typedef LoggerType::Pointer LoggerPointer
typedef ThreadLogger LoggerType
typedef utl_shared_ptr< LoggerVectorType > LoggerVectorPointer
typedef std::vector< LoggerPointer > LoggerVectorType
typedef MaskImageType::Pointer MaskImagePointer
typedef Image< double, 3 > MaskImageType
typedef OutputImageType::IndexType OutputImageIndexType
typedef OutputImageType::PixelType OutputImagePixelType
typedef OutputImageType::Pointer OutputImagePointer
typedef OutputImageType::RegionType OutputImageRegionType
typedef OutputImageType::SizeType OutputImageSizeType
typedef OutputImageType::SpacingType OutputImageSpacingType
typedef TOutputImage OutputImageType
typedef SmartPointer< Self > Pointer
typedef MaskedImageToImageFilter Self
typedef ImageToImageFilter< TInputImage, TOutputImage > Superclass
Public Member Functions
virtual void ComputeBasisMatrix ()
virtual void ComputeRegularizationWeight ()
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual MatrixPointer GetBasisMatrix ()
virtual double GetMD0 ()
virtual const char * GetNameOfClass () const
itkGetObjectMacro (SamplingSchemeQSpace, SamplingSchemeQSpaceType)
itkTypedefMaskedImageToImageMacro (Superclass)
virtual void SetMD0 (double _arg)
virtual void SetSamplingSchemeQSpace (SamplingSchemeQSpaceType *_arg)
Public Member Functions inherited from itk::MaskedImageToImageFilter< TInputImage, TOutputImage >
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual const LoggerType * GetLogger () const
virtual const MaskImageType * GetMaskImage () const
bool IsMaskUsed ()
itkGetObjectMacro (MaskImage, MaskImageType)
itkGetObjectMacro (Logger, LoggerType)
itkSetGetMacro (LogLevel, int)
virtual void SetLogger (LoggerType *_arg)
virtual void SetMaskImage (MaskImageType *_arg)
void SetMaskImage (const std::string &file)
Static Public Member Functions
static Pointer New ()
Static Public Member Functions inherited from itk::MaskedImageToImageFilter< TInputImage, TOutputImage >
static Pointer New ()
Protected Member Functions
DiffusionModelEstimationImageFilter ()
LightObject::Pointer InternalClone () const ITK_OVERRIDE
void PrintSelf (std::ostream &os, Indent indent) const ITK_OVERRIDE
virtual void VerifyInputParameters () const
virtual ~DiffusionModelEstimationImageFilter ()
Protected Member Functions inherited from itk::MaskedImageToImageFilter< TInputImage, TOutputImage >
void CreateLoggerVector ()
virtual void InitializeThreadedLibraries ()
LightObject::Pointer InternalClone () const ITK_OVERRIDE
MaskedImageToImageFilter ()
std::string ThreadIDToString () const
virtual void VerifyMaskInformation () const
void WriteLogger (const std::string &str, const LoggerBase::PriorityLevelType level=LoggerBase::DEBUG) const
virtual ~MaskedImageToImageFilter ()
Protected Attributes
MatrixPointer m_BasisMatrix
double m_MD0
VectorPointer m_RegularizationWeight
SamplingSchemeQSpacePointer m_SamplingSchemeQSpace
Protected Attributes inherited from itk::MaskedImageToImageFilter< TInputImage, TOutputImage >
LoggerPointer m_Logger
LoggerVectorPointer m_LoggerVector
int m_LogLevel
MaskImagePointer m_MaskImage
int m_ThreadID
Private Member Functions
DiffusionModelEstimationImageFilter (const Self &)
void operator= (const Self &)
Additional Inherited Members
Static Public Attributes inherited from itk::MaskedImageToImageFilter< TInputImage, TOutputImage >
static const unsigned int InputImageDimension
static const unsigned int OutputImageDimension
Member Typedef Documentation
template<class TInputImage , class TOutputImage > typedef SmartPointer<const Self> itk::DiffusionModelEstimationImageFilter< TInputImage, TOutputImage >::ConstPointer
Definition at line 50 of file itkDiffusionModelEstimationImageFilter.h.
template<class TInputImage , class TOutputImage > typedef utl_shared_ptr<MatrixType> itk::DiffusionModelEstimationImageFilter< TInputImage, TOutputImage >::MatrixPointer
Definition at line 63 of file itkDiffusionModelEstimationImageFilter.h.
template<class TInputImage , class TOutputImage > typedef utl::NDArray<double,2> itk::DiffusionModelEstimationImageFilter< TInputImage, TOutputImage >::MatrixType
Definition at line 61 of file itkDiffusionModelEstimationImageFilter.h.
template<class TInputImage , class TOutputImage > typedef SmartPointer<Self> itk::DiffusionModelEstimationImageFilter< TInputImage, TOutputImage >::Pointer
Definition at line 49 of file itkDiffusionModelEstimationImageFilter.h.
template<class TInputImage , class TOutputImage > typedef SamplingSchemeQSpaceType::Pointer itk::DiffusionModelEstimationImageFilter< TInputImage, TOutputImage >::SamplingSchemeQSpacePointer
Definition at line 69 of file itkDiffusionModelEstimationImageFilter.h.
template<class TInputImage , class TOutputImage > typedef SamplingSchemeQSpace<double> itk::DiffusionModelEstimationImageFilter< TInputImage, TOutputImage >::SamplingSchemeQSpaceType
Definition at line 68 of file itkDiffusionModelEstimationImageFilter.h.
template<class TInputImage , class TOutputImage > typedef SamplingSchemeRSpaceType::Pointer itk::DiffusionModelEstimationImageFilter< TInputImage, TOutputImage >::SamplingSchemeRSpacePointer
Definition at line 72 of file itkDiffusionModelEstimationImageFilter.h.
template<class TInputImage , class TOutputImage > typedef SamplingScheme3D<double> itk::DiffusionModelEstimationImageFilter< TInputImage, TOutputImage >::SamplingSchemeRSpaceType
Definition at line 71 of file itkDiffusionModelEstimationImageFilter.h.
template<class TInputImage , class TOutputImage > typedef DiffusionModelEstimationImageFilter itk::DiffusionModelEstimationImageFilter< TInputImage, TOutputImage >::Self
Standard class typedefs.
Definition at line 47 of file itkDiffusionModelEstimationImageFilter.h.
template<class TInputImage , class TOutputImage > typedef utl_shared_ptr<STDVectorType > itk::DiffusionModelEstimationImageFilter< TInputImage, TOutputImage >::STDVectorPointer
Definition at line 66 of file itkDiffusionModelEstimationImageFilter.h.
template<class TInputImage , class TOutputImage > typedef std::vector<double> itk::DiffusionModelEstimationImageFilter< TInputImage, TOutputImage >::STDVectorType
Definition at line 65 of file itkDiffusionModelEstimationImageFilter.h.
template<class TInputImage , class TOutputImage > typedef MaskedImageToImageFilter<TInputImage,TOutputImage> itk::DiffusionModelEstimationImageFilter< TInputImage, TOutputImage >::Superclass
Definition at line 48 of file itkDiffusionModelEstimationImageFilter.h.
template<class TInputImage , class TOutputImage > typedef utl_shared_ptr<VectorType> itk::DiffusionModelEstimationImageFilter< TInputImage, TOutputImage >::VectorPointer
Definition at line 64 of file itkDiffusionModelEstimationImageFilter.h.
template<class TInputImage , class TOutputImage > typedef utl::NDArray<double,1> itk::DiffusionModelEstimationImageFilter< TInputImage, TOutputImage >::VectorType
Definition at line 62 of file itkDiffusionModelEstimationImageFilter.h.
Constructor & Destructor Documentation
template<class TInputImage , class TOutputImage > itk::DiffusionModelEstimationImageFilter< TInputImage, TOutputImage >::DiffusionModelEstimationImageFilter () protected
Definition at line 29 of file itkDiffusionModelEstimationImageFilter.hxx.
References itk::DiffusionModelEstimationImageFilter< TInputImage, TOutputImage >::InternalClone().
template<class TInputImage , class TOutputImage > virtual itk::DiffusionModelEstimationImageFilter< TInputImage, TOutputImage >::~DiffusionModelEstimationImageFilter () inline protected virtual
Definition at line 93 of file itkDiffusionModelEstimationImageFilter.h.
References ITK_OVERRIDE.
template<class TInputImage , class TOutputImage > itk::DiffusionModelEstimationImageFilter< TInputImage, TOutputImage >::DiffusionModelEstimationImageFilter (const Self &) private
Member Function Documentation
template<class TInputImage , class TOutputImage > virtual void itk::DiffusionModelEstimationImageFilter< TInputImage, TOutputImage >::ComputeBasisMatrix () inline virtual
compute basis matrix which incorporates radial matrix and spherical matrix
Reimplemented in itk::SphericalPolarFourierImageFilter< TInputImage, TOutputImage >, and itk::GeneralizedHighOrderTensorImageFilter< TInputImage, TOutputImage >.
Definition at line 84 of file itkDiffusionModelEstimationImageFilter.h.
template<class TInputImage , class TOutputImage > virtual void itk::DiffusionModelEstimationImageFilter< TInputImage, TOutputImage >::ComputeRegularizationWeight () inline virtual
Reimplemented in itk::SphericalPolarFourierImageFilter< TInputImage, TOutputImage >, and itk::GeneralizedHighOrderTensorImageFilter< TInputImage, TOutputImage >.
Definition at line 87 of file itkDiffusionModelEstimationImageFilter.h.
template<class TInputImage , class TOutputImage > virtual::itk::LightObject::Pointer itk::DiffusionModelEstimationImageFilter< TInputImage, TOutputImage >::CreateAnother (void) const
template<class TInputImage , class TOutputImage > virtual MatrixPointer itk::DiffusionModelEstimationImageFilter< TInputImage, TOutputImage >::GetBasisMatrix () virtual
template<class TInputImage , class TOutputImage > virtual double itk::DiffusionModelEstimationImageFilter< TInputImage, TOutputImage >::GetMD0 () virtual
template<class TInputImage , class TOutputImage > virtual const char* itk::DiffusionModelEstimationImageFilter< TInputImage, TOutputImage >::GetNameOfClass () const virtual
Run-time type information (and related methods)
Reimplemented from itk::MaskedImageToImageFilter< TInputImage, TOutputImage >.
Reimplemented in itk::SphericalPolarFourierEstimationImageFilter< TInputImage, TOutputImage >, itk::DiffusionModelEstimationInSphericalCoordinateImageFilter< TInputImage, TOutputImage >, itk::SphericalPolarFourierImageFilter< TInputImage, TOutputImage >, and itk::GeneralizedHighOrderTensorImageFilter< TInputImage, TOutputImage >.
template<class TInputImage , class TOutputImage > LightObject::Pointer itk::DiffusionModelEstimationImageFilter< TInputImage, TOutputImage >::InternalClone () const protected
Definition at line 40 of file itkDiffusionModelEstimationImageFilter.hxx.
References itkShowPositionThreadedLogger, and itk::DiffusionModelEstimationImageFilter< TInputImage, TOutputImage >::VerifyInputParameters().
Referenced by itk::DiffusionModelEstimationImageFilter< TInputImage, TOutputImage >::DiffusionModelEstimationImageFilter().
template<class TInputImage , class TOutputImage > itk::DiffusionModelEstimationImageFilter< TInputImage, TOutputImage >::itkGetObjectMacro (SamplingSchemeQSpace , SamplingSchemeQSpaceType)
template<class TInputImage , class TOutputImage > itk::DiffusionModelEstimationImageFilter< TInputImage, TOutputImage >::itkTypedefMaskedImageToImageMacro (Superclass)
Convenient Typedefs.
template<class TInputImage , class TOutputImage > static Pointer itk::DiffusionModelEstimationImageFilter< TInputImage, TOutputImage >::New () static
Method for creation through the object factory.
template<class TInputImage , class TOutputImage > void itk::DiffusionModelEstimationImageFilter< TInputImage, TOutputImage >::operator= (const Self &) private
template<class TInputImage , class TOutputImage > void itk::DiffusionModelEstimationImageFilter< TInputImage, TOutputImage >::PrintSelf (std::ostream & os, Indent indent) const protected virtual
Reimplemented from itk::MaskedImageToImageFilter< TInputImage, TOutputImage >.
Reimplemented in itk::SphericalPolarFourierEstimationImageFilter< TInputImage, TOutputImage >, itk::DiffusionModelEstimationInSphericalCoordinateImageFilter< TInputImage, TOutputImage >, itk::SphericalPolarFourierImageFilter< TInputImage, TOutputImage >, and itk::GeneralizedHighOrderTensorImageFilter< TInputImage, TOutputImage >.
Definition at line 83 of file itkDiffusionModelEstimationImageFilter.hxx.
References utl::PrintUtlMatrix(), utl::PrintUtlVector(), and PrintVar1.
Referenced by itk::DiffusionModelEstimationImageFilter< TInputImage, TOutputImage >::VerifyInputParameters().
template<class TInputImage , class TOutputImage > virtual void itk::DiffusionModelEstimationImageFilter< TInputImage, TOutputImage >::SetMD0 (double _arg) virtual
template<class TInputImage , class TOutputImage > virtual void itk::DiffusionModelEstimationImageFilter< TInputImage, TOutputImage >::SetSamplingSchemeQSpace (SamplingSchemeQSpaceType * _arg) virtual
template<class TInputImage , class TOutputImage > void itk::DiffusionModelEstimationImageFilter< TInputImage, TOutputImage >::VerifyInputParameters () const protected virtual
Reimplemented from itk::MaskedImageToImageFilter< TInputImage, TOutputImage >.
Reimplemented in itk::SphericalPolarFourierEstimationImageFilter< TInputImage, TOutputImage >, itk::DiffusionModelEstimationInSphericalCoordinateImageFilter< TInputImage, TOutputImage >, and itk::GeneralizedHighOrderTensorImageFilter< TInputImage, TOutputImage >.
Definition at line 65 of file itkDiffusionModelEstimationImageFilter.hxx.
References itk::IsImageEmpty(), itkShowPositionThreadedLogger, itk::DiffusionModelEstimationImageFilter< TInputImage, TOutputImage >::PrintSelf(), and utlGlobalException.
Referenced by itk::DiffusionModelEstimationImageFilter< TInputImage, TOutputImage >::InternalClone().
Member Data Documentation
template<class TInputImage , class TOutputImage > MatrixPointer itk::DiffusionModelEstimationImageFilter< TInputImage, TOutputImage >::m_BasisMatrix protected
Definition at line 106 of file itkDiffusionModelEstimationImageFilter.h.
template<class TInputImage , class TOutputImage > double itk::DiffusionModelEstimationImageFilter< TInputImage, TOutputImage >::m_MD0 protected
typical MD value for typical scale
Definition at line 104 of file itkDiffusionModelEstimationImageFilter.h.
template<class TInputImage , class TOutputImage > VectorPointer itk::DiffusionModelEstimationImageFilter< TInputImage, TOutputImage >::m_RegularizationWeight protected
used for regulaization
Definition at line 109 of file itkDiffusionModelEstimationImageFilter.h.
template<class TInputImage , class TOutputImage > SamplingSchemeQSpacePointer itk::DiffusionModelEstimationImageFilter< TInputImage, TOutputImage >::m_SamplingSchemeQSpace protected
Sampling Scheme in q-space
Definition at line 101 of file itkDiffusionModelEstimationImageFilter.h.
The documentation for this class was generated from the following files:
Modules/DiffusionModels/include/itkDiffusionModelEstimationImageFilter.h
Modules/DiffusionModels/include/itkDiffusionModelEstimationImageFilter.hxx