DMRITool: spams::Timer Class Reference
spams::Timer Class Reference
#include <utils.h>
Detailed Description
Class Timer.
Definition at line 138 of file utils.h.
Public Member Functions
double getElapsed () const
void printElapsed ()
void reset ()
void start ()
void stop ()
Timer ()
~Timer ()
Private Attributes
double _cumul
bool _running
struct timeval * _time1
struct timeval * _time2
Constructor & Destructor Documentation
spams::Timer::Timer () inline
Empty constructor.
Constructor.
Definition at line 170 of file utils.h.
References _time1, and _time2.
spams::Timer::~Timer () inline
Destructor.
Definition at line 176 of file utils.h.
References _time1, and _time2.
Member Function Documentation
double spams::Timer::getElapsed () const inline
print the elapsed time
Definition at line 193 of file utils.h.
References _cumul, _running, _time1, and _time2.
Referenced by spams::FISTA::ADMM(), spams::MaxFlow< T >::component_relabelling(), spams::FISTA::FISTA_Generic(), spams::MaxFlow< T >::gap_relabelling(), spams::FISTA::ISTA_Generic(), spams::FISTA::LinADMM(), spams::FISTA::subGradientDescent_Generic(), spams::Trainer< T >::train(), and spams::Trainer< T >::trainOffline().
void spams::Timer::printElapsed () inline
print the elapsed time
Definition at line 182 of file utils.h.
References _cumul, _running, _time1, and _time2.
Referenced by spams::MinCostFlow< Int >::compute_min_cost(), spams::Graph< T >::proximal_operator(), spams::Trainer< T >::train(), and spams::Trainer< T >::trainOffline().
void spams::Timer::reset () inline
reset the timer
Definition at line 155 of file utils.h.
Referenced by spams::MinCostFlow< Int >::compute_min_cost(), spams::Tree_Seq< T >::dual_norm_inf(), and spams::Graph< T >::proximal_operator().
void spams::Timer::start () inline
start the time
Definition at line 146 of file utils.h.
Referenced by spams::FISTA::ADMM(), spams::MaxFlow< T >::component_relabelling(), spams::MinCostFlow< Int >::compute_min_cost(), spams::Graph< T >::dual_norm_inf(), spams::FISTA::FISTA_Generic(), spams::MaxFlow< T >::gap_relabelling(), spams::FISTA::ISTA_Generic(), spams::FISTA::LinADMM(), spams::MaxFlow< T >::perform_maxflow_component(), spams::MinCostFlow< Int >::price_refine(), spams::MinCostFlow< Int >::price_update(), spams::Graph< T >::proximal_operator(), spams::FISTA::subGradientDescent_Generic(), spams::Trainer< T >::train(), and spams::Trainer< T >::trainOffline().
void spams::Timer::stop () inline
stop the time
Definition at line 149 of file utils.h.
Referenced by spams::FISTA::ADMM(), spams::MaxFlow< T >::component_relabelling(), spams::MinCostFlow< Int >::compute_min_cost(), spams::FISTA::FISTA_Generic(), spams::MaxFlow< T >::gap_relabelling(), spams::FISTA::ISTA_Generic(), spams::FISTA::LinADMM(), spams::MaxFlow< T >::perform_maxflow_component(), spams::MinCostFlow< Int >::price_refine(), spams::MinCostFlow< Int >::price_update(), spams::Graph< T >::proximal_operator(), spams::FISTA::subGradientDescent_Generic(), and spams::Trainer< T >::train().
Member Data Documentation
double spams::Timer::_cumul private
Definition at line 166 of file utils.h.
Referenced by getElapsed(), and printElapsed().
bool spams::Timer::_running private
Definition at line 165 of file utils.h.
Referenced by getElapsed(), and printElapsed().
struct timeval* spams::Timer::_time1 private
Definition at line 163 of file utils.h.
Referenced by getElapsed(), printElapsed(), Timer(), and ~Timer().
struct timeval* spams::Timer::_time2 private
Definition at line 164 of file utils.h.
Referenced by getElapsed(), printElapsed(), Timer(), and ~Timer().
The documentation for this class was generated from the following file:
ThirdParty/Spams/include/utils.h