DMRITool: itk::ScalarMapFromSPFImageFilter< TInputImage, TOutputImage > Class Template Reference
itk::ScalarMapFromSPFImageFilter< TInputImage, TOutputImage > Class Template Reference
DiffusionModels
#include <itkScalarMapFromSPFImageFilter.h>
Detailed Description
template<class TInputImage, class TOutputImage = Image<double,3>>
class itk::ScalarMapFromSPFImageFilter< TInputImage, TOutputImage >
calculate ODFs from SPF coefficients
Author
Jian Cheng (JC), jian..nosp@m.chen.nosp@m.g.198.nosp@m.3@gm.nosp@m.ail.c.nosp@m.om
Definition at line 29 of file itkScalarMapFromSPFImageFilter.h.
Public Types
typedef Superclass::BasisType BasisType
typedef SmartPointer< const Self > ConstPointer
enum MapType {
RTO =0,
MSD,
PFA
}
typedef Superclass::MatrixPointer MatrixPointer
typedef Superclass::MatrixType MatrixType
typedef SmartPointer< Self > Pointer
typedef ScalarMapFromSPFImageFilter Self
typedef Superclass::STDVectorPointer STDVectorPointer
typedef Superclass::STDVectorType STDVectorType
typedef FeaturesFromSPFImageFilter< TInputImage, TOutputImage > Superclass
typedef Superclass::VectorPointer VectorPointer
typedef Superclass::VectorType VectorType
Public Types inherited from itk::FeaturesFromSPFImageFilter< TInputImage, TOutputImage >
enum BasisType {
SPF =0,
DSPF
}
typedef SmartPointer< const Self > ConstPointer
typedef utl_shared_ptr< MatrixType > MatrixPointer
typedef utl::NDArray< double, 2 > MatrixType
typedef SmartPointer< Self > Pointer
typedef FeaturesFromSPFImageFilter Self
typedef SphericalPolarFourierEstimationImageFilter< TInputImage, TOutputImage > SPFIFilterBaseType
typedef utl_shared_ptr< STDVectorType > STDVectorPointer
typedef std::vector< double > STDVectorType
typedef MaskedImageToImageFilter< TInputImage, TOutputImage > Superclass
typedef utl_shared_ptr< VectorType > VectorPointer
typedef utl::NDArray< double, 1 > VectorType
Public Types inherited from itk::MaskedImageToImageFilter< TInputImage, TOutputImage >
typedef SmartPointer< const Self > ConstPointer
typedef InputImageType::ConstPointer InputImageConstPointer
typedef InputImageType::IndexType InputImageIndexType
typedef InputImageType::PixelType InputImagePixelType
typedef InputImageType::Pointer InputImagePointer
typedef InputImageType::RegionType InputImageRegionType
typedef InputImageType::SizeType InputImageSizeType
typedef InputImageType::SpacingType InputImageSpacingType
typedef TInputImage InputImageType
typedef LoggerType::Pointer LoggerPointer
typedef ThreadLogger LoggerType
typedef utl_shared_ptr< LoggerVectorType > LoggerVectorPointer
typedef std::vector< LoggerPointer > LoggerVectorType
typedef MaskImageType::Pointer MaskImagePointer
typedef Image< double, 3 > MaskImageType
typedef OutputImageType::IndexType OutputImageIndexType
typedef OutputImageType::PixelType OutputImagePixelType
typedef OutputImageType::Pointer OutputImagePointer
typedef OutputImageType::RegionType OutputImageRegionType
typedef OutputImageType::SizeType OutputImageSizeType
typedef OutputImageType::SpacingType OutputImageSpacingType
typedef TOutputImage OutputImageType
typedef SmartPointer< Self > Pointer
typedef MaskedImageToImageFilter Self
typedef ImageToImageFilter< TInputImage, TOutputImage > Superclass
Public Member Functions
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual MapType GetMapType ()
virtual const char * GetNameOfClass () const
itkTypedefMaskedImageToImageMacro (Superclass)
virtual void SetMapType (MapType _arg)
Public Member Functions inherited from itk::FeaturesFromSPFImageFilter< TInputImage, TOutputImage >
double ComputeScale (const bool setScale=true)
virtual void ComputeSPFToFeatureTransform ()
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual double GetBasisScale ()
virtual BasisType GetBasisType ()
virtual bool GetIsFourier ()
virtual bool GetIsInQSpace ()
virtual double GetMD0 ()
virtual MatrixPointer GetOrientations ()
virtual int GetRadialRank ()
virtual const ScalarImageType * GetScaleImage () const
virtual int GetSHRank ()
virtual MatrixPointer GetSPFToFeatureTransform ()
virtual double GetTau ()
virtual void IsFourierOff ()
virtual void IsFourierOn ()
virtual void IsInQSpaceOff ()
virtual void IsInQSpaceOn ()
itkGetObjectMacro (ScaleImage, ScalarImageType)
itkTypedefMaskedImageToImageMacro (Superclass)
virtual void SetBasisScale (const double scale)
virtual void SetBasisType (BasisType _arg)
virtual void SetIsFourier (bool _arg)
virtual void SetIsInQSpace (bool _arg)
virtual void SetMD0 (double _arg)
virtual void SetOrientations (MatrixPointer _arg)
virtual void SetRadialRank (int _arg)
void SetScaleImage (const ScalarImagePointer &scaleImage)
virtual void SetSHRank (int _arg)
virtual void SetTau (double _arg)
Public Member Functions inherited from itk::MaskedImageToImageFilter< TInputImage, TOutputImage >
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual const LoggerType * GetLogger () const
virtual const MaskImageType * GetMaskImage () const
bool IsMaskUsed ()
itkGetObjectMacro (MaskImage, MaskImageType)
itkGetObjectMacro (Logger, LoggerType)
itkSetGetMacro (LogLevel, int)
virtual void SetLogger (LoggerType *_arg)
virtual void SetMaskImage (MaskImageType *_arg)
void SetMaskImage (const std::string &file)
Static Public Member Functions
static Pointer New ()
Static Public Member Functions inherited from itk::FeaturesFromSPFImageFilter< TInputImage, TOutputImage >
static Pointer New ()
Static Public Member Functions inherited from itk::MaskedImageToImageFilter< TInputImage, TOutputImage >
static Pointer New ()
Protected Member Functions
void BeforeThreadedGenerateData () ITK_OVERRIDE
void GenerateOutputInformation () ITK_OVERRIDE
LightObject::Pointer InternalClone () const ITK_OVERRIDE
void PrintSelf (std::ostream &os, Indent indent) const ITK_OVERRIDE
ScalarMapFromSPFImageFilter ()
void ThreadedGenerateData (const typename TOutputImage::RegionType &outputRegionForThread, ThreadIdType threadId) ITK_OVERRIDE
void VerifyInputParameters () const ITK_OVERRIDE
virtual ~ScalarMapFromSPFImageFilter ()
Protected Member Functions inherited from itk::FeaturesFromSPFImageFilter< TInputImage, TOutputImage >
void BeforeThreadedGenerateData () ITK_OVERRIDE
FeaturesFromSPFImageFilter ()
LightObject::Pointer InternalClone () const ITK_OVERRIDE
void SetSPFIEstimator ()
virtual ~FeaturesFromSPFImageFilter ()
Protected Member Functions inherited from itk::MaskedImageToImageFilter< TInputImage, TOutputImage >
void CreateLoggerVector ()
virtual void InitializeThreadedLibraries ()
LightObject::Pointer InternalClone () const ITK_OVERRIDE
MaskedImageToImageFilter ()
std::string ThreadIDToString () const
virtual void VerifyMaskInformation () const
void WriteLogger (const std::string &str, const LoggerBase::PriorityLevelType level=LoggerBase::DEBUG) const
virtual ~MaskedImageToImageFilter ()
Protected Attributes
MapType m_MapType
VectorType m_SumWeight
Protected Attributes inherited from itk::FeaturesFromSPFImageFilter< TInputImage, TOutputImage >
double m_BasisScale
BasisType m_BasisType
bool m_IsFourier
bool m_IsInQSpace
double m_MD0
MatrixPointer m_Orientations
int m_RadialRank
ScalarImageType::Pointer m_ScaleImage
int m_SHRank
SPFIFilterBaseType::Pointer m_SPFIEstimator
MatrixPointer m_SPFToFeatureTransform
double m_Tau
Protected Attributes inherited from itk::MaskedImageToImageFilter< TInputImage, TOutputImage >
LoggerPointer m_Logger
LoggerVectorPointer m_LoggerVector
int m_LogLevel
MaskImagePointer m_MaskImage
int m_ThreadID
Private Member Functions
void operator= (const Self &)
ScalarMapFromSPFImageFilter (const Self &)
Additional Inherited Members
Static Public Attributes inherited from itk::MaskedImageToImageFilter< TInputImage, TOutputImage >
static const unsigned int InputImageDimension
static const unsigned int OutputImageDimension
Member Typedef Documentation
template<class TInputImage , class TOutputImage = Image<double,3>> typedef Superclass::BasisType itk::ScalarMapFromSPFImageFilter< TInputImage, TOutputImage >::BasisType
Definition at line 51 of file itkScalarMapFromSPFImageFilter.h.
template<class TInputImage , class TOutputImage = Image<double,3>> typedef SmartPointer<const Self> itk::ScalarMapFromSPFImageFilter< TInputImage, TOutputImage >::ConstPointer
Definition at line 37 of file itkScalarMapFromSPFImageFilter.h.
template<class TInputImage , class TOutputImage = Image<double,3>> typedef Superclass::MatrixPointer itk::ScalarMapFromSPFImageFilter< TInputImage, TOutputImage >::MatrixPointer
Definition at line 48 of file itkScalarMapFromSPFImageFilter.h.
template<class TInputImage , class TOutputImage = Image<double,3>> typedef Superclass::MatrixType itk::ScalarMapFromSPFImageFilter< TInputImage, TOutputImage >::MatrixType
Definition at line 47 of file itkScalarMapFromSPFImageFilter.h.
template<class TInputImage , class TOutputImage = Image<double,3>> typedef SmartPointer<Self> itk::ScalarMapFromSPFImageFilter< TInputImage, TOutputImage >::Pointer
Definition at line 36 of file itkScalarMapFromSPFImageFilter.h.
template<class TInputImage , class TOutputImage = Image<double,3>> typedef ScalarMapFromSPFImageFilter itk::ScalarMapFromSPFImageFilter< TInputImage, TOutputImage >::Self
Standard class typedefs.
Definition at line 34 of file itkScalarMapFromSPFImageFilter.h.
template<class TInputImage , class TOutputImage = Image<double,3>> typedef Superclass::STDVectorPointer itk::ScalarMapFromSPFImageFilter< TInputImage, TOutputImage >::STDVectorPointer
Definition at line 53 of file itkScalarMapFromSPFImageFilter.h.
template<class TInputImage , class TOutputImage = Image<double,3>> typedef Superclass::STDVectorType itk::ScalarMapFromSPFImageFilter< TInputImage, TOutputImage >::STDVectorType
Definition at line 52 of file itkScalarMapFromSPFImageFilter.h.
template<class TInputImage , class TOutputImage = Image<double,3>> typedef FeaturesFromSPFImageFilter<TInputImage,TOutputImage> itk::ScalarMapFromSPFImageFilter< TInputImage, TOutputImage >::Superclass
Definition at line 35 of file itkScalarMapFromSPFImageFilter.h.
template<class TInputImage , class TOutputImage = Image<double,3>> typedef Superclass::VectorPointer itk::ScalarMapFromSPFImageFilter< TInputImage, TOutputImage >::VectorPointer
Definition at line 50 of file itkScalarMapFromSPFImageFilter.h.
template<class TInputImage , class TOutputImage = Image<double,3>> typedef Superclass::VectorType itk::ScalarMapFromSPFImageFilter< TInputImage, TOutputImage >::VectorType
Definition at line 49 of file itkScalarMapFromSPFImageFilter.h.
Member Enumeration Documentation
template<class TInputImage , class TOutputImage = Image<double,3>> enum itk::ScalarMapFromSPFImageFilter::MapType
Enumerator
RTO
return to origin probability
MSD
Mean Squared Displacement
PFA
generalized propagator FA for 3D EAP
Definition at line 56 of file itkScalarMapFromSPFImageFilter.h.
Constructor & Destructor Documentation
template<class TInputImage , class TOutputImage = Image<double,3>> itk::ScalarMapFromSPFImageFilter< TInputImage, TOutputImage >::ScalarMapFromSPFImageFilter () inline protected
Definition at line 70 of file itkScalarMapFromSPFImageFilter.h.
template<class TInputImage , class TOutputImage = Image<double,3>> virtual itk::ScalarMapFromSPFImageFilter< TInputImage, TOutputImage >::~ScalarMapFromSPFImageFilter () inline protected virtual
Definition at line 74 of file itkScalarMapFromSPFImageFilter.h.
template<class TInputImage , class TOutputImage = Image<double,3>> itk::ScalarMapFromSPFImageFilter< TInputImage, TOutputImage >::ScalarMapFromSPFImageFilter (const Self &) private
Member Function Documentation
template<class TInputImage , class TOutputImage > void itk::ScalarMapFromSPFImageFilter< TInputImage, TOutputImage >::BeforeThreadedGenerateData () protected
Definition at line 54 of file itkScalarMapFromSPFImageFilter.hxx.
References utl::Factorial(), utl::GammaHalfInteger(), utl::IsEven(), utl::Lagurre(), M_PI, utl::sign(), and itk::ScalarMapFromSPFImageFilter< TInputImage, TOutputImage >::ThreadedGenerateData().
Referenced by itk::ScalarMapFromSPFImageFilter< TInputImage, TOutputImage >::InternalClone().
template<class TInputImage , class TOutputImage = Image<double,3>> virtual::itk::LightObject::Pointer itk::ScalarMapFromSPFImageFilter< TInputImage, TOutputImage >::CreateAnother (void) const
template<class TInputImage , class TOutputImage > void itk::ScalarMapFromSPFImageFilter< TInputImage, TOutputImage >::GenerateOutputInformation (void) protected
Definition at line 26 of file itkScalarMapFromSPFImageFilter.hxx.
References itk::CopyImageInformation(), and itk::ScalarMapFromSPFImageFilter< TInputImage, TOutputImage >::InternalClone().
template<class TInputImage , class TOutputImage = Image<double,3>> virtual MapType itk::ScalarMapFromSPFImageFilter< TInputImage, TOutputImage >::GetMapType () virtual
template<class TInputImage , class TOutputImage = Image<double,3>> virtual const char* itk::ScalarMapFromSPFImageFilter< TInputImage, TOutputImage >::GetNameOfClass () const virtual
Run-time type information (and related methods)
Reimplemented from itk::FeaturesFromSPFImageFilter< TInputImage, TOutputImage >.
template<class TInputImage , class TOutputImage > LightObject::Pointer itk::ScalarMapFromSPFImageFilter< TInputImage, TOutputImage >::InternalClone () const protected
Definition at line 37 of file itkScalarMapFromSPFImageFilter.hxx.
References itk::ScalarMapFromSPFImageFilter< TInputImage, TOutputImage >::BeforeThreadedGenerateData().
Referenced by itk::ScalarMapFromSPFImageFilter< TInputImage, TOutputImage >::GenerateOutputInformation().
template<class TInputImage , class TOutputImage = Image<double,3>> itk::ScalarMapFromSPFImageFilter< TInputImage, TOutputImage >::itkTypedefMaskedImageToImageMacro (Superclass)
template<class TInputImage , class TOutputImage = Image<double,3>> static Pointer itk::ScalarMapFromSPFImageFilter< TInputImage, TOutputImage >::New () static
Method for creation through the object factory.
template<class TInputImage , class TOutputImage = Image<double,3>> void itk::ScalarMapFromSPFImageFilter< TInputImage, TOutputImage >::operator= (const Self &) private
template<class TInputImage , class TOutputImage > void itk::ScalarMapFromSPFImageFilter< TInputImage, TOutputImage >::PrintSelf (std::ostream & os, Indent indent) const protected virtual
Reimplemented from itk::FeaturesFromSPFImageFilter< TInputImage, TOutputImage >.
Definition at line 178 of file itkScalarMapFromSPFImageFilter.hxx.
References utl::PrintUtlVector().
Referenced by itk::ScalarMapFromSPFImageFilter< TInputImage, TOutputImage >::ThreadedGenerateData().
template<class TInputImage , class TOutputImage = Image<double,3>> virtual void itk::ScalarMapFromSPFImageFilter< TInputImage, TOutputImage >::SetMapType (MapType _arg) virtual
template<class TInputImage , class TOutputImage > void itk::ScalarMapFromSPFImageFilter< TInputImage, TOutputImage >::ThreadedGenerateData (const typename TOutputImage::RegionType & outputRegionForThread, ThreadIdType threadId) protected
Definition at line 89 of file itkScalarMapFromSPFImageFilter.hxx.
References utl::Factorial(), utl::Gamma(), itk::IsImageEmpty(), itk::ScalarMapFromSPFImageFilter< TInputImage, TOutputImage >::PrintSelf(), and utl::RankToDimSH().
Referenced by itk::ScalarMapFromSPFImageFilter< TInputImage, TOutputImage >::BeforeThreadedGenerateData().
template<class TInputImage , class TOutputImage = Image<double,3>> void itk::ScalarMapFromSPFImageFilter< TInputImage, TOutputImage >::VerifyInputParameters () const inline protected virtual
Reimplemented from itk::FeaturesFromSPFImageFilter< TInputImage, TOutputImage >.
Definition at line 76 of file itkScalarMapFromSPFImageFilter.h.
References ITK_OVERRIDE.
Member Data Documentation
template<class TInputImage , class TOutputImage = Image<double,3>> MapType itk::ScalarMapFromSPFImageFilter< TInputImage, TOutputImage >::m_MapType protected
Definition at line 88 of file itkScalarMapFromSPFImageFilter.h.
template<class TInputImage , class TOutputImage = Image<double,3>> VectorType itk::ScalarMapFromSPFImageFilter< TInputImage, TOutputImage >::m_SumWeight protected
Definition at line 87 of file itkScalarMapFromSPFImageFilter.h.
The documentation for this class was generated from the following files:
Modules/DiffusionModels/include/itkScalarMapFromSPFImageFilter.h
Modules/DiffusionModels/include/itkScalarMapFromSPFImageFilter.hxx