DMRITool: spams::Data< T > Class Template Reference
spams::Data< T > Class Template Reference abstract
#include <linalg.h>
Detailed Description
template<typename T>
class spams::Data< T >
Data class, abstract class, useful in the class image.
Definition at line 130 of file linalg.h.
Public Member Functions
virtual void getData (Vector< T > &data, const int i) const =0
virtual void getGroup (Matrix< T > &data, const vector_groups &groups, const int i) const =0
virtual int m () const =0
virtual int n () const =0
virtual void norm_2sq_cols (Vector< T > &norms) const
virtual T operator[] (const int index) const =0
virtual int V () const =0
virtual ~Data ()
Constructor & Destructor Documentation
template<typename T> virtual spams::Data< T >::~Data () inline virtual
Definition at line 140 of file linalg.h.
Member Function Documentation
template<typename T> virtual void spams::Data< T >::getData (Vector< T > & data, const int i) const pure virtual
Implemented in spams::SpMatrix< T >, and spams::Matrix< T >.
Referenced by spams::Trainer< T >::cleanDict(), spams::Matrix< T >::operator[](), spams::Trainer< T >::train(), spams::Trainer< T >::trainOffline(), and spams::SpMatrix< T >::V().
template<typename T> virtual void spams::Data< T >::getGroup (Matrix< T > & data, const vector_groups & groups, const int i) const pure virtual
Implemented in spams::SpMatrix< T >, and spams::Matrix< T >.
Referenced by spams::Matrix< T >::operator[](), and spams::SpMatrix< T >::V().
template<typename T> virtual int spams::Data< T >::m () const pure virtual
Implemented in spams::SpMatrix< T >, and spams::Matrix< T >.
Referenced by spams::Matrix< T >::copyTo(), spams::Matrix< T >::fakeSize(), spams::SpMatrix< T >::nnz(), spams::SpVector< T >::setL(), spams::Matrix< T >::setm(), spams::Trainer< T >::train(), and spams::Trainer< T >::trainOffline().
template<typename T> virtual int spams::Data< T >::n () const pure virtual
Implemented in spams::SpMatrix< T >, and spams::Matrix< T >.
Referenced by spams::Trainer< T >::cleanDict(), spams::Matrix< T >::fakeSize(), spams::Vector< int >::fakeSize(), spams::lasso(), spams::lasso2(), spams::SpMatrix< T >::nnz(), spams::Matrix< T >::operator[](), spams::SpVector< T >::setL(), spams::Matrix< T >::setn(), spams::Vector< int >::setn(), spams::Trainer< T >::train(), and spams::Trainer< T >::trainOffline().
template<typename T> virtual void spams::Data< T >::norm_2sq_cols (Vector< T > & norms) const inline virtual
Reimplemented in spams::SpMatrix< T >, and spams::Matrix< T >.
Definition at line 139 of file linalg.h.
Referenced by spams::SpMatrix< T >::copyTo(), spams::lasso(), spams::lasso2(), and spams::Matrix< T >::nrm2sq().
template<typename T> virtual T spams::Data< T >::operator[] (const int index) const inline pure virtual
Implemented in spams::SpMatrix< T >, and spams::Matrix< T >.
Referenced by spams::ProdMatrix< T >::m(), and spams::SpMatrix< T >::V().
template<typename T> virtual int spams::Data< T >::V () const pure virtual
Implemented in spams::SpMatrix< T >, and spams::Matrix< T >.
Referenced by spams::Matrix< T >::fakeSize(), spams::Vector< int >::mult_elementWise(), spams::Trainer< T >::train(), and spams::Trainer< T >::trainOffline().
The documentation for this class was generated from the following file:
ThirdParty/Spams/include/linalg.h