DMRITool: itk::RGBImageToVTKImageDataFilter< TInputImage > Class Template Reference
itk::RGBImageToVTKImageDataFilter< TInputImage > Class Template Reference
#include <itkRGBImageToVTKImageDataFilter.h>
Detailed Description
template<class TInputImage>
class itk::RGBImageToVTKImageDataFilter< TInputImage >
Converts an ITK image to VTK image data.
Definition at line 30 of file itkRGBImageToVTKImageDataFilter.h.
Public Types
typedef SmartPointer< const Self > ConstPointer
typedef InputImageType::ConstPointer InputImageConstPointer
typedef ImageRegionConstIterator< InputImageType > InputImageIteratorType
typedef InputImageType::Pointer InputImagePointer
typedef TInputImage InputImageType
typedef InputImageType::IndexType InputIndexType
typedef InputImageType::PixelType InputPixelType
typedef InputImageType::PointType InputPointType
typedef InputImageType::RegionType InputRegionType
typedef InputImageType::SizeType InputSizeType
typedef InputImageType::SpacingType InputSpacingType
typedef vtkSmartPointer< vtkImageData > OutputImageType
typedef SmartPointer< Self > Pointer
typedef RGBImageToVTKImageDataFilter Self
typedef ProcessObject Superclass
Public Member Functions
virtual ::itk::LightObject::Pointer CreateAnother (void) const
const InputImageType * GetInput () const
virtual const char * GetNameOfClass () const
vtkImageData * GetOutput () const
virtual void SetInput (const InputImageType *image)
virtual void Update () ITK_OVERRIDE
Static Public Member Functions
static Pointer New ()
Static Public Attributes
static const unsigned int Dimension = TInputImage::ImageDimension
Protected Member Functions
virtual void GenerateData () ITK_OVERRIDE
RGBImageToVTKImageDataFilter ()
virtual ~RGBImageToVTKImageDataFilter ()
Private Member Functions
void operator= (const Self &)
RGBImageToVTKImageDataFilter (const Self &)
Private Attributes
OutputImageType m_Image
Member Typedef Documentation
template<class TInputImage> typedef SmartPointer<const Self> itk::RGBImageToVTKImageDataFilter< TInputImage >::ConstPointer
Definition at line 37 of file itkRGBImageToVTKImageDataFilter.h.
template<class TInputImage> typedef InputImageType::ConstPointer itk::RGBImageToVTKImageDataFilter< TInputImage >::InputImageConstPointer
Definition at line 57 of file itkRGBImageToVTKImageDataFilter.h.
template<class TInputImage> typedef ImageRegionConstIterator<InputImageType> itk::RGBImageToVTKImageDataFilter< TInputImage >::InputImageIteratorType
Definition at line 58 of file itkRGBImageToVTKImageDataFilter.h.
template<class TInputImage> typedef InputImageType::Pointer itk::RGBImageToVTKImageDataFilter< TInputImage >::InputImagePointer
Definition at line 50 of file itkRGBImageToVTKImageDataFilter.h.
template<class TInputImage> typedef TInputImage itk::RGBImageToVTKImageDataFilter< TInputImage >::InputImageType
Some typedefs.
Definition at line 49 of file itkRGBImageToVTKImageDataFilter.h.
template<class TInputImage> typedef InputImageType::IndexType itk::RGBImageToVTKImageDataFilter< TInputImage >::InputIndexType
Definition at line 55 of file itkRGBImageToVTKImageDataFilter.h.
template<class TInputImage> typedef InputImageType::PixelType itk::RGBImageToVTKImageDataFilter< TInputImage >::InputPixelType
Definition at line 56 of file itkRGBImageToVTKImageDataFilter.h.
template<class TInputImage> typedef InputImageType::PointType itk::RGBImageToVTKImageDataFilter< TInputImage >::InputPointType
Definition at line 54 of file itkRGBImageToVTKImageDataFilter.h.
template<class TInputImage> typedef InputImageType::RegionType itk::RGBImageToVTKImageDataFilter< TInputImage >::InputRegionType
Definition at line 51 of file itkRGBImageToVTKImageDataFilter.h.
template<class TInputImage> typedef InputImageType::SizeType itk::RGBImageToVTKImageDataFilter< TInputImage >::InputSizeType
Definition at line 52 of file itkRGBImageToVTKImageDataFilter.h.
template<class TInputImage> typedef InputImageType::SpacingType itk::RGBImageToVTKImageDataFilter< TInputImage >::InputSpacingType
Definition at line 53 of file itkRGBImageToVTKImageDataFilter.h.
template<class TInputImage> typedef vtkSmartPointer<vtkImageData> itk::RGBImageToVTKImageDataFilter< TInputImage >::OutputImageType
Definition at line 60 of file itkRGBImageToVTKImageDataFilter.h.
template<class TInputImage> typedef SmartPointer<Self> itk::RGBImageToVTKImageDataFilter< TInputImage >::Pointer
Definition at line 36 of file itkRGBImageToVTKImageDataFilter.h.
template<class TInputImage> typedef RGBImageToVTKImageDataFilter itk::RGBImageToVTKImageDataFilter< TInputImage >::Self
Standard class typedefs.
Definition at line 34 of file itkRGBImageToVTKImageDataFilter.h.
template<class TInputImage> typedef ProcessObject itk::RGBImageToVTKImageDataFilter< TInputImage >::Superclass
Definition at line 35 of file itkRGBImageToVTKImageDataFilter.h.
Constructor & Destructor Documentation
template<class TInputImage > itk::RGBImageToVTKImageDataFilter< TInputImage >::RGBImageToVTKImageDataFilter () protected
Constructor
Definition at line 32 of file itkRGBImageToVTKImageDataFilter.hxx.
References itk::RGBImageToVTKImageDataFilter< TInputImage >::GetOutput().
template<class TInputImage> virtual itk::RGBImageToVTKImageDataFilter< TInputImage >::~RGBImageToVTKImageDataFilter () inline protected virtual
Definition at line 78 of file itkRGBImageToVTKImageDataFilter.h.
References ITK_OVERRIDE.
template<class TInputImage> itk::RGBImageToVTKImageDataFilter< TInputImage >::RGBImageToVTKImageDataFilter (const Self &) private
Member Function Documentation
template<class TInputImage> virtual::itk::LightObject::Pointer itk::RGBImageToVTKImageDataFilter< TInputImage >::CreateAnother (void) const
template<class TInputImage > void itk::RGBImageToVTKImageDataFilter< TInputImage >::GenerateData (void) protected virtual
Generate the data
Definition at line 78 of file itkRGBImageToVTKImageDataFilter.hxx.
Referenced by itk::RGBImageToVTKImageDataFilter< TInputImage >::GetInput().
template<class TInputImage > const RGBImageToVTKImageDataFilter< TInputImage >::InputImageType * itk::RGBImageToVTKImageDataFilter< TInputImage >::GetInput (void) const
Get a vtkImage as output
Definition at line 67 of file itkRGBImageToVTKImageDataFilter.hxx.
References itk::RGBImageToVTKImageDataFilter< TInputImage >::GenerateData().
Referenced by itk::RGBImageToVTKImageDataFilter< TInputImage >::SetInput().
template<class TInputImage> virtual const char* itk::RGBImageToVTKImageDataFilter< TInputImage >::GetNameOfClass () const virtual
Run-time type information (and related methods).
template<class TInputImage > vtkImageData * itk::RGBImageToVTKImageDataFilter< TInputImage >::GetOutput () const
Get the output in the form of a vtkImage. This call is delegated to the internal vtkImageImporter filter
Get a vtkImage as output
Definition at line 43 of file itkRGBImageToVTKImageDataFilter.hxx.
References itk::RGBImageToVTKImageDataFilter< TInputImage >::SetInput().
Referenced by itk::RGBImageToVTKImageDataFilter< TInputImage >::RGBImageToVTKImageDataFilter().
template<class TInputImage> static Pointer itk::RGBImageToVTKImageDataFilter< TInputImage >::New () static
Method for creation through the object factory.
template<class TInputImage> void itk::RGBImageToVTKImageDataFilter< TInputImage >::operator= (const Self &) private
template<class TInputImage > void itk::RGBImageToVTKImageDataFilter< TInputImage >::SetInput (const InputImageType * image) virtual
Get a vtkImage as output
Definition at line 54 of file itkRGBImageToVTKImageDataFilter.hxx.
References itk::RGBImageToVTKImageDataFilter< TInputImage >::GetInput().
Referenced by itk::RGBImageToVTKImageDataFilter< TInputImage >::GetOutput().
template<class TInputImage> virtual void itk::RGBImageToVTKImageDataFilter< TInputImage >::Update () inline virtual
Definition at line 71 of file itkRGBImageToVTKImageDataFilter.h.
Member Data Documentation
template<class TInputImage> const unsigned int itk::RGBImageToVTKImageDataFilter< TInputImage >::Dimension = TInputImage::ImageDimension static
Image Dimension
Definition at line 46 of file itkRGBImageToVTKImageDataFilter.h.
template<class TInputImage> OutputImageType itk::RGBImageToVTKImageDataFilter< TInputImage >::m_Image private
Definition at line 86 of file itkRGBImageToVTKImageDataFilter.h.
The documentation for this class was generated from the following files:
Modules/Visualization/include/itkRGBImageToVTKImageDataFilter.h
Modules/Visualization/include/itkRGBImageToVTKImageDataFilter.hxx