DMRITool: spams::FISTA::GroupProx< T, Reg > Class Template Reference
spams::FISTA::GroupProx< T, Reg > Class Template Reference
#include <fista.h>
Detailed Description
template<typename T, typename Reg>
class spams::FISTA::GroupProx< T, Reg >
Definition at line 1657 of file fista.h.
Public Member Functions
T eval (const Vector< T > &x) const
void fenchel (const Vector< T > &x, T &val, T &scal) const
GroupProx (const ParamReg< T > &param)
virtual bool is_fenchel () const
void prox (const Vector< T > &x, Vector< T > &y, const T lambda)
virtual ~GroupProx ()
Public Member Functions inherited from spams::FISTA::Regularizer< T >
virtual T eval_dual_norm (const Vector< T > &x) const
virtual T eval_dual_norm_paths (const Vector< T > &x, SpMatrix< T > &path) const
virtual T eval_paths (const Vector< T > &x, SpMatrix< T > &paths_mat) const
virtual bool is_intercept () const
virtual bool is_subgrad () const
Regularizer ()
Regularizer (const ParamReg< T > &param)
virtual void reset ()
virtual void sub_grad (const Vector< T > &input, Vector< T > &output) const
virtual ~Regularizer ()
Protected Attributes
std::vector< list_int * > _groups
Reg * _prox
int _size_group
Protected Attributes inherited from spams::FISTA::Regularizer< T >
bool _intercept
bool _pos
Constructor & Destructor Documentation
template<typename T , typename Reg > spams::FISTA::GroupProx< T, Reg >::GroupProx (const ParamReg< T > & param) inline
Definition at line 1659 of file fista.h.
References spams::FISTA::ParamReg< T >::groups, spams::FISTA::ParamReg< T >::intercept, MAX, spams::FISTA::ParamReg< T >::ngroups, spams::List< T >::push_back(), and spams::FISTA::ParamReg< T >::size_group.
template<typename T , typename Reg > virtual spams::FISTA::GroupProx< T, Reg >::~GroupProx () inline virtual
Definition at line 1672 of file fista.h.
Member Function Documentation
template<typename T , typename Reg > T spams::FISTA::GroupProx< T, Reg >::eval (const Vector< T > & x) const inline virtual
Implements spams::FISTA::Regularizer< T >.
Definition at line 1706 of file fista.h.
References spams::List< T >::begin(), spams::List< T >::end(), spams::Vector< T >::n(), spams::Vector< T >::rawX(), spams::Vector< T >::setPointer(), and spams::List< T >::size().
template<typename T , typename Reg > void spams::FISTA::GroupProx< T, Reg >::fenchel (const Vector< T > & input, T & val, T & scal) const inline virtual
returns phi^star(input) and ouput=input if the fenchel is unconstrained returns 0 and scale input such that phi^star(output)=0 otherwise
Implements spams::FISTA::Regularizer< T >.
Definition at line 1730 of file fista.h.
References spams::List< T >::begin(), spams::List< T >::end(), MIN, spams::Vector< T >::n(), spams::Vector< T >::rawX(), spams::Vector< T >::setPointer(), and spams::List< T >::size().
template<typename T , typename Reg > virtual bool spams::FISTA::GroupProx< T, Reg >::is_fenchel () const inline virtual
Reimplemented from spams::FISTA::Regularizer< T >.
Definition at line 1729 of file fista.h.
template<typename T , typename Reg > void spams::FISTA::GroupProx< T, Reg >::prox (const Vector< T > & x, Vector< T > & y, const T lambda) inline virtual
Implements spams::FISTA::Regularizer< T >.
Definition at line 1677 of file fista.h.
References spams::List< T >::begin(), spams::Vector< T >::copy(), spams::List< T >::end(), spams::Vector< T >::n(), spams::Vector< T >::rawX(), spams::Vector< T >::setPointer(), and spams::List< T >::size().
Member Data Documentation
template<typename T , typename Reg > std::vector<list_int*> spams::FISTA::GroupProx< T, Reg >::_groups protected
Definition at line 1761 of file fista.h.
template<typename T , typename Reg > Reg* spams::FISTA::GroupProx< T, Reg >::_prox protected
Definition at line 1762 of file fista.h.
template<typename T , typename Reg > int spams::FISTA::GroupProx< T, Reg >::_size_group protected
Definition at line 1758 of file fista.h.
The documentation for this class was generated from the following file:
ThirdParty/Spams/include/fista.h