DMRITool: spams::FISTA::LassoConstraint< T > Class Template Reference
spams::FISTA::LassoConstraint< T > Class Template Reference
#include <fista.h>
Detailed Description
template<typename T>
class spams::FISTA::LassoConstraint< T >
Definition at line 1115 of file fista.h.
Public Member Functions
T eval (const Vector< T > &x) const
void fenchel (const Vector< T > &input, T &val, T &scal) const
virtual bool is_subgrad () const
LassoConstraint (const ParamReg< T > &param)
void prox (const Vector< T > &x, Vector< T > &y, const T lambda)
virtual ~LassoConstraint ()
Public Member Functions inherited from spams::FISTA::Regularizer< T >
virtual T eval_dual_norm (const Vector< T > &x) const
virtual T eval_dual_norm_paths (const Vector< T > &x, SpMatrix< T > &path) const
virtual T eval_paths (const Vector< T > &x, SpMatrix< T > &paths_mat) const
virtual bool is_fenchel () const
virtual bool is_intercept () const
Regularizer ()
Regularizer (const ParamReg< T > &param)
virtual void reset ()
virtual void sub_grad (const Vector< T > &input, Vector< T > &output) const
virtual ~Regularizer ()
Private Attributes
T _thrs
Additional Inherited Members
Protected Attributes inherited from spams::FISTA::Regularizer< T >
bool _intercept
bool _pos
Constructor & Destructor Documentation
template<typename T > spams::FISTA::LassoConstraint< T >::LassoConstraint (const ParamReg< T > & param) inline
Definition at line 1117 of file fista.h.
References spams::FISTA::ParamReg< T >::lambda.
template<typename T > virtual spams::FISTA::LassoConstraint< T >::~LassoConstraint () inline virtual
Definition at line 1118 of file fista.h.
Member Function Documentation
template<typename T > T spams::FISTA::LassoConstraint< T >::eval (const Vector< T > & x) const inline virtual
Implements spams::FISTA::Regularizer< T >.
Definition at line 1131 of file fista.h.
template<typename T > void spams::FISTA::LassoConstraint< T >::fenchel (const Vector< T > & input, T & val, T & scal) const inline virtual
returns phi^star(input) and ouput=input if the fenchel is unconstrained returns 0 and scale input such that phi^star(output)=0 otherwise
Implements spams::FISTA::Regularizer< T >.
Definition at line 1134 of file fista.h.
References spams::Vector< T >::copy(), spams::Vector< T >::fmaxval(), MAX, spams::Vector< T >::maxval(), and spams::Vector< T >::n().
template<typename T > virtual bool spams::FISTA::LassoConstraint< T >::is_subgrad () const inline virtual
Reimplemented from spams::FISTA::Regularizer< T >.
Definition at line 1141 of file fista.h.
template<typename T > void spams::FISTA::LassoConstraint< T >::prox (const Vector< T > & x, Vector< T > & y, const T lambda) inline virtual
Implements spams::FISTA::Regularizer< T >.
Definition at line 1120 of file fista.h.
References spams::Vector< T >::copy(), spams::Vector< T >::n(), and spams::Vector< T >::sparseProject().
Member Data Documentation
template<typename T > T spams::FISTA::LassoConstraint< T >::_thrs private
Definition at line 1141 of file fista.h.
The documentation for this class was generated from the following file:
ThirdParty/Spams/include/fista.h