DMRITool: itk::CastVectorImageFileWriter< TInputImage > Class Template Reference
itk::CastVectorImageFileWriter< TInputImage > Class Template Reference
#include <itkCastVectorImageFileWriter.h>
Detailed Description
template<class TInputImage>
class itk::CastVectorImageFileWriter< TInputImage >
Writes image data, after casting, to a single file.
Definition at line 33 of file itkCastVectorImageFileWriter.h.
Public Types
typedef SmartPointer< const Self > ConstPointer
typedef InputImageType::PixelType InputImagePixelType
typedef InputImageType::Pointer InputImagePointer
typedef InputImageType::RegionType InputImageRegionType
typedef TInputImage InputImageType
typedef ImageIOBase::IOComponentType IOComponentType
typedef SmartPointer< Self > Pointer
typedef CastVectorImageFileWriter Self
typedef ProcessObject Superclass
Public Member Functions
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual IOComponentType GetComponentType () const
virtual const char * GetFileName () const
const InputImageType * GetInput (void)
const InputImageType * GetInput (unsigned int idx)
const ImageIORegion & GetIORegion (void) const
virtual const char * GetNameOfClass () const
virtual const unsigned int & GetNumberOfStreamDivisions ()
virtual const bool & GetUseCompression ()
virtual const bool & GetUseInputMetaDataDictionary ()
itkGetObjectMacro (ImageIO, ImageIOBase)
virtual void SetComponentType (const IOComponentType _arg)
virtual void SetFileName (const char *_arg)
void SetImageIO (ImageIOBase *io)
void SetInput (const InputImageType *input)
void SetIORegion (const ImageIORegion &region)
virtual void SetNumberOfStreamDivisions (unsigned int _arg)
virtual void SetUseCompression (bool _arg)
virtual void SetUseInputMetaDataDictionary (bool _arg)
virtual void Update () ITK_OVERRIDE
virtual void UseCompressionOff ()
virtual void UseCompressionOn ()
virtual void UseInputMetaDataDictionaryOff ()
virtual void UseInputMetaDataDictionaryOn ()
virtual void Write (void)
Static Public Member Functions
static Pointer New ()
Protected Member Functions
CastVectorImageFileWriter ()
void GenerateData (void) ITK_OVERRIDE
void PrintSelf (std::ostream &os, Indent indent) const ITK_OVERRIDE
~CastVectorImageFileWriter ()
Private Member Functions
CastVectorImageFileWriter (const Self &)
void operator= (const Self &)
Private Attributes
IOComponentType m_ComponentType
bool m_FactorySpecifiedImageIO
std::string m_FileName
ImageIOBase::Pointer m_ImageIO
unsigned int m_NumberOfStreamDivisions
ImageIORegion m_PasteIORegion
bool m_UseCompression
bool m_UseInputMetaDataDictionary
bool m_UserSpecifiedImageIO
bool m_UserSpecifiedIORegion
Member Typedef Documentation
template<class TInputImage> typedef SmartPointer<const Self> itk::CastVectorImageFileWriter< TInputImage >::ConstPointer
Definition at line 40 of file itkCastVectorImageFileWriter.h.
template<class TInputImage> typedef InputImageType::PixelType itk::CastVectorImageFileWriter< TInputImage >::InputImagePixelType
Definition at line 52 of file itkCastVectorImageFileWriter.h.
template<class TInputImage> typedef InputImageType::Pointer itk::CastVectorImageFileWriter< TInputImage >::InputImagePointer
Definition at line 50 of file itkCastVectorImageFileWriter.h.
template<class TInputImage> typedef InputImageType::RegionType itk::CastVectorImageFileWriter< TInputImage >::InputImageRegionType
Definition at line 51 of file itkCastVectorImageFileWriter.h.
template<class TInputImage> typedef TInputImage itk::CastVectorImageFileWriter< TInputImage >::InputImageType
Some convenient typedefs.
Definition at line 46 of file itkCastVectorImageFileWriter.h.
template<class TInputImage> typedef ImageIOBase::IOComponentType itk::CastVectorImageFileWriter< TInputImage >::IOComponentType
Definition at line 54 of file itkCastVectorImageFileWriter.h.
template<class TInputImage> typedef SmartPointer<Self> itk::CastVectorImageFileWriter< TInputImage >::Pointer
Definition at line 39 of file itkCastVectorImageFileWriter.h.
template<class TInputImage> typedef CastVectorImageFileWriter itk::CastVectorImageFileWriter< TInputImage >::Self
Standard class typedefs.
Definition at line 37 of file itkCastVectorImageFileWriter.h.
template<class TInputImage> typedef ProcessObject itk::CastVectorImageFileWriter< TInputImage >::Superclass
Definition at line 38 of file itkCastVectorImageFileWriter.h.
Constructor & Destructor Documentation
template<class TInputImage > itk::CastVectorImageFileWriter< TInputImage >::CastVectorImageFileWriter () protected
Definition at line 34 of file itkCastVectorImageFileWriter.hxx.
References itk::CastVectorImageFileWriter< TInputImage >::~CastVectorImageFileWriter().
template<class TInputImage > itk::CastVectorImageFileWriter< TInputImage >::~CastVectorImageFileWriter () protected
Definition at line 49 of file itkCastVectorImageFileWriter.hxx.
References itk::CastVectorImageFileWriter< TInputImage >::SetInput().
Referenced by itk::CastVectorImageFileWriter< TInputImage >::CastVectorImageFileWriter().
template<class TInputImage> itk::CastVectorImageFileWriter< TInputImage >::CastVectorImageFileWriter (const Self &) private
Member Function Documentation
template<class TInputImage> virtual::itk::LightObject::Pointer itk::CastVectorImageFileWriter< TInputImage >::CreateAnother (void) const
template<class TInputImage > void itk::CastVectorImageFileWriter< TInputImage >::GenerateData (void) protected
Does the real work.
Definition at line 119 of file itkCastVectorImageFileWriter.hxx.
References itk::CastVectorImageFileWriter< TInputImage >::PrintSelf().
Referenced by itk::CastVectorImageFileWriter< TInputImage >::Write().
template<class TInputImage> virtual IOComponentType itk::CastVectorImageFileWriter< TInputImage >::GetComponentType () const virtual
template<class TInputImage> virtual const char* itk::CastVectorImageFileWriter< TInputImage >::GetFileName () const virtual
template<class TInputImage > const CastVectorImageFileWriter< TInputImage >::InputImageType * itk::CastVectorImageFileWriter< TInputImage >::GetInput (void)
Definition at line 69 of file itkCastVectorImageFileWriter.hxx.
Referenced by itk::CastVectorImageFileWriter< TInputImage >::SetInput().
template<class TInputImage > const CastVectorImageFileWriter< TInputImage >::InputImageType * itk::CastVectorImageFileWriter< TInputImage >::GetInput (unsigned int idx)
Definition at line 84 of file itkCastVectorImageFileWriter.hxx.
References itk::CastVectorImageFileWriter< TInputImage >::SetIORegion().
template<class TInputImage> const ImageIORegion& itk::CastVectorImageFileWriter< TInputImage >::GetIORegion (void) const inline
Definition at line 99 of file itkCastVectorImageFileWriter.h.
template<class TInputImage> virtual const char* itk::CastVectorImageFileWriter< TInputImage >::GetNameOfClass () const virtual
Run-time type information (and related methods).
template<class TInputImage> virtual const unsigned int& itk::CastVectorImageFileWriter< TInputImage >::GetNumberOfStreamDivisions () virtual
template<class TInputImage> virtual const bool& itk::CastVectorImageFileWriter< TInputImage >::GetUseCompression () virtual
template<class TInputImage> virtual const bool& itk::CastVectorImageFileWriter< TInputImage >::GetUseInputMetaDataDictionary () virtual
template<class TInputImage> itk::CastVectorImageFileWriter< TInputImage >::itkGetObjectMacro (ImageIO , ImageIOBase)
template<class TInputImage> static Pointer itk::CastVectorImageFileWriter< TInputImage >::New () static
Method for creation through the object factory.
template<class TInputImage> void itk::CastVectorImageFileWriter< TInputImage >::operator= (const Self &) private
template<class TInputImage > void itk::CastVectorImageFileWriter< TInputImage >::PrintSelf (std::ostream & os, Indent indent) const protected
Definition at line 326 of file itkCastVectorImageFileWriter.hxx.
Referenced by itk::CastVectorImageFileWriter< TInputImage >::GenerateData().
template<class TInputImage> virtual void itk::CastVectorImageFileWriter< TInputImage >::SetComponentType (const IOComponentType _arg) virtual
Set/Get component type
template<class TInputImage> virtual void itk::CastVectorImageFileWriter< TInputImage >::SetFileName (const char * _arg) virtual
Specify the name of the output file to write.
template<class TInputImage> void itk::CastVectorImageFileWriter< TInputImage >::SetImageIO (ImageIOBase * io) inline
Set/Get the ImageIO helper class. Usually this is created via the object factory mechanism that determines whether a particular ImageIO can write a certain file. This method provides a way to get the ImageIO instance that is created, or one can be manually set where the IO factory mechanism may not work (for example, raw image files or image files with non-standard filename suffix's. If the user specifies the ImageIO, we assume she makes the correct choice and will allow a file to be created regardless of the file extension. If the factory has set the ImageIO, the extension must be supported by the specified ImageIO.
Definition at line 76 of file itkCastVectorImageFileWriter.h.
template<class TInputImage > void itk::CastVectorImageFileWriter< TInputImage >::SetInput (const InputImageType * input)
Definition at line 57 of file itkCastVectorImageFileWriter.hxx.
References itk::CastVectorImageFileWriter< TInputImage >::GetInput().
Referenced by itk::CastVectorImageFileWriter< TInputImage >::~CastVectorImageFileWriter().
template<class TInputImage > void itk::CastVectorImageFileWriter< TInputImage >::SetIORegion (const ImageIORegion & region)
Specify the region to write. If left NULL, then the whole image is written.
Definition at line 93 of file itkCastVectorImageFileWriter.hxx.
References itk::CastVectorImageFileWriter< TInputImage >::Write().
Referenced by itk::CastVectorImageFileWriter< TInputImage >::GetInput().
template<class TInputImage> virtual void itk::CastVectorImageFileWriter< TInputImage >::SetNumberOfStreamDivisions (unsigned int _arg) virtual
Set/Get the number of pieces to divide the input. The upstream pipeline will try to be executed this many times.
template<class TInputImage> virtual void itk::CastVectorImageFileWriter< TInputImage >::SetUseCompression (bool _arg) virtual
Set the compression On or Off
template<class TInputImage> virtual void itk::CastVectorImageFileWriter< TInputImage >::SetUseInputMetaDataDictionary (bool _arg) virtual
By default the MetaDataDictionary is taken from the input image and passed to the ImageIO. In some cases, however, a user may prefer to introduce her/his own MetaDataDictionary. This is often the case of the ImageSeriesWriter. This flag defined whether the MetaDataDictionary to use will be the one from the input image or the one already set in the ImageIO object.
template<class TInputImage> virtual void itk::CastVectorImageFileWriter< TInputImage >::Update () inline virtual
Aliased to the Write() method to be consistent with the rest of the pipeline.
Definition at line 113 of file itkCastVectorImageFileWriter.h.
References ITK_OVERRIDE.
template<class TInputImage> virtual void itk::CastVectorImageFileWriter< TInputImage >::UseCompressionOff () virtual
template<class TInputImage> virtual void itk::CastVectorImageFileWriter< TInputImage >::UseCompressionOn () virtual
template<class TInputImage> virtual void itk::CastVectorImageFileWriter< TInputImage >::UseInputMetaDataDictionaryOff () virtual
template<class TInputImage> virtual void itk::CastVectorImageFileWriter< TInputImage >::UseInputMetaDataDictionaryOn () virtual
template<class TInputImage > void itk::CastVectorImageFileWriter< TInputImage >::Write (void) virtual
A special version of the Update() method for writers. It invokes start and end events and handles releasing data. It eventually calls GenerateData() which does the actual writing. Note: the write method will write data specified by the IORegion. If not set, then then the whole image is written. Note that the region will be cropped to fit the input image's LargestPossibleRegion.
Definition at line 108 of file itkCastVectorImageFileWriter.hxx.
References itk::CastVectorImageFileWriter< TInputImage >::GenerateData().
Referenced by itk::CastVectorImageFileWriter< TInputImage >::SetIORegion().
Member Data Documentation
template<class TInputImage> IOComponentType itk::CastVectorImageFileWriter< TInputImage >::m_ComponentType private
Definition at line 166 of file itkCastVectorImageFileWriter.h.
template<class TInputImage> bool itk::CastVectorImageFileWriter< TInputImage >::m_FactorySpecifiedImageIO private
Definition at line 159 of file itkCastVectorImageFileWriter.h.
template<class TInputImage> std::string itk::CastVectorImageFileWriter< TInputImage >::m_FileName private
Definition at line 149 of file itkCastVectorImageFileWriter.h.
template<class TInputImage> ImageIOBase::Pointer itk::CastVectorImageFileWriter< TInputImage >::m_ImageIO private
Definition at line 151 of file itkCastVectorImageFileWriter.h.
template<class TInputImage> unsigned int itk::CastVectorImageFileWriter< TInputImage >::m_NumberOfStreamDivisions private
Definition at line 156 of file itkCastVectorImageFileWriter.h.
template<class TInputImage> ImageIORegion itk::CastVectorImageFileWriter< TInputImage >::m_PasteIORegion private
Definition at line 155 of file itkCastVectorImageFileWriter.h.
template<class TInputImage> bool itk::CastVectorImageFileWriter< TInputImage >::m_UseCompression private
Definition at line 161 of file itkCastVectorImageFileWriter.h.
template<class TInputImage> bool itk::CastVectorImageFileWriter< TInputImage >::m_UseInputMetaDataDictionary private
Definition at line 162 of file itkCastVectorImageFileWriter.h.
template<class TInputImage> bool itk::CastVectorImageFileWriter< TInputImage >::m_UserSpecifiedImageIO private
Definition at line 152 of file itkCastVectorImageFileWriter.h.
template<class TInputImage> bool itk::CastVectorImageFileWriter< TInputImage >::m_UserSpecifiedIORegion private
Definition at line 157 of file itkCastVectorImageFileWriter.h.
The documentation for this class was generated from the following files:
Modules/Common/include/itkCastVectorImageFileWriter.h
Modules/Common/include/itkCastVectorImageFileWriter.hxx