DMRITool: itk::SpatiallyDenseSparseVectorImage< TValueType, VImageDimension, TKeyType > Class Template Reference
itk::SpatiallyDenseSparseVectorImage< TValueType, VImageDimension, TKeyType > Class Template Reference
#include <itkSpatiallyDenseSparseVectorImage.h>
Detailed Description
template<class TValueType, unsigned int VImageDimension, typename TKeyType = unsigned long>
class itk::SpatiallyDenseSparseVectorImage< TValueType, VImageDimension, TKeyType >
An n-dimensional vector image with a sparse memory model.
The elements for this image are stored in a hash table, catering to very large images with a small number of relevant pixels. The image is spatially dense, allowing fast random access and thread-safe operations.
Definition at line 40 of file itkSpatiallyDenseSparseVectorImage.h.
Public Types
typedef SpatiallyDenseSparseVectorImagePixelAccessorFunctor< Self > AccessorFunctorType
typedef SpatiallyDenseSparseVectorImagePixelAccessor< ValueType, KeyType > AccessorType
typedef SmartPointer< const Self > ConstPointer
typedef WeakPointer< const Self > ConstWeakPointer
typedef Superclass::DirectionType DirectionType
typedef Superclass::IndexType IndexType
typedef SparseVector< TValueType, TKeyType > InternalPixelType
typedef InternalPixelType IOPixelType
typedef TKeyType KeyType
typedef SpatiallyDenseSparseVectorImageNeighborhoodAccessorFunctor< Self > NeighborhoodAccessorFunctorType
typedef Superclass::OffsetType OffsetType
typedef Superclass::OffsetValueType OffsetValueType
typedef ImportImageContainer< SizeValueType, InternalPixelType > PixelContainer
typedef PixelContainer::ConstPointer PixelContainerConstPointer
typedef PixelContainer::Pointer PixelContainerPointer
typedef PixelMapType::const_iterator PixelMapConstIterator
typedef PixelMapType::iterator PixelMapIterator
typedef InternalPixelType::InternalDataType PixelMapType
typedef VariableLengthVector< TValueType > PixelType
typedef SmartPointer< Self > Pointer
typedef Superclass::PointType PointType
typedef Superclass::RegionType RegionType
typedef SpatiallyDenseSparseVectorImage Self
typedef Superclass::SizeType SizeType
typedef Superclass::SpacingType SpacingType
typedef ImageBase< VImageDimension > Superclass
typedef TValueType ValueType
typedef unsigned long VectorLengthType
Public Member Functions
void Allocate (bool UseDefaultConstructor=false) ITK_OVERRIDE
OffsetValueType ComputeOffset (const IndexType &ind) const
virtual ::itk::LightObject::Pointer CreateAnother (void) const
void FillBuffer (const PixelType &value)
virtual const RegionType & GetBufferedRegion () const ITK_OVERRIDE
InternalPixelType * GetBufferPointer ()
const InternalPixelType * GetBufferPointer () const
const InternalPixelType & GetInternalPixel (const IndexType &index) const
InternalPixelType & GetInternalPixel (const IndexType &index)
virtual const char * GetNameOfClass () const
NeighborhoodAccessorFunctorType GetNeighborhoodAccessor ()
const NeighborhoodAccessorFunctorType GetNeighborhoodAccessor () const
virtual unsigned int GetNumberOfComponentsPerPixel () const ITK_OVERRIDE
const PixelType GetPixel (const IndexType &index) const
PixelType GetPixel (const IndexType &index)
AccessorType GetPixelAccessor (void)
const AccessorType GetPixelAccessor (void) const
PixelContainer * GetPixelContainer ()
const PixelContainer * GetPixelContainer () const
virtual const VectorLengthType & GetVectorLength ()
virtual void Graft (const DataObject *data) ITK_OVERRIDE
virtual void Initialize () ITK_OVERRIDE
PixelType operator[] (const IndexType &index)
PixelType operator[] (const IndexType &index) const
virtual void SetBufferedRegion (const RegionType &region) ITK_OVERRIDE
virtual void SetNumberOfComponentsPerPixel (unsigned int n) ITK_OVERRIDE
void SetPixel (const IndexType &index, const PixelType &value)
void SetPixelContainer (PixelContainer *container)
void SetRegions (const RegionType &region) ITK_OVERRIDE
void SetRegions (const SizeType &size) ITK_OVERRIDE
virtual void SetVectorLength (VectorLengthType _arg)
Static Public Member Functions
static Pointer New ()
Static Public Attributes
static const unsigned int ImageDimension = VImageDimension
Protected Member Functions
void PrintSelf (std::ostream &os, Indent indent) const ITK_OVERRIDE
SpatiallyDenseSparseVectorImage ()
virtual ~SpatiallyDenseSparseVectorImage ()
Private Member Functions
void operator= (const Self &)
SpatiallyDenseSparseVectorImage (const Self &)
Private Attributes
PixelContainerPointer m_Container
PixelType m_FillBufferValue
VectorLengthType m_VectorLength
Member Typedef Documentation
template<class TValueType , unsigned int VImageDimension, typename TKeyType = unsigned long> typedef SpatiallyDenseSparseVectorImagePixelAccessorFunctor< Self > itk::SpatiallyDenseSparseVectorImage< TValueType, VImageDimension, TKeyType >::AccessorFunctorType
Tyepdef for the functor used to access pixels.
Definition at line 121 of file itkSpatiallyDenseSparseVectorImage.h.
template<class TValueType , unsigned int VImageDimension, typename TKeyType = unsigned long> typedef SpatiallyDenseSparseVectorImagePixelAccessor< ValueType, KeyType > itk::SpatiallyDenseSparseVectorImage< TValueType, VImageDimension, TKeyType >::AccessorType
Accessor type that convert data between internal and external representations.
Definition at line 117 of file itkSpatiallyDenseSparseVectorImage.h.
template<class TValueType , unsigned int VImageDimension, typename TKeyType = unsigned long> typedef SmartPointer<const Self> itk::SpatiallyDenseSparseVectorImage< TValueType, VImageDimension, TKeyType >::ConstPointer
Definition at line 48 of file itkSpatiallyDenseSparseVectorImage.h.
template<class TValueType , unsigned int VImageDimension, typename TKeyType = unsigned long> typedef WeakPointer<const Self> itk::SpatiallyDenseSparseVectorImage< TValueType, VImageDimension, TKeyType >::ConstWeakPointer
Definition at line 49 of file itkSpatiallyDenseSparseVectorImage.h.
template<class TValueType , unsigned int VImageDimension, typename TKeyType = unsigned long> typedef Superclass::DirectionType itk::SpatiallyDenseSparseVectorImage< TValueType, VImageDimension, TKeyType >::DirectionType
Direction typedef support. A matrix of direction cosines.
Definition at line 96 of file itkSpatiallyDenseSparseVectorImage.h.
template<class TValueType , unsigned int VImageDimension, typename TKeyType = unsigned long> typedef Superclass::IndexType itk::SpatiallyDenseSparseVectorImage< TValueType, VImageDimension, TKeyType >::IndexType
Index typedef support. An index is used to access pixel values.
Definition at line 87 of file itkSpatiallyDenseSparseVectorImage.h.
template<class TValueType , unsigned int VImageDimension, typename TKeyType = unsigned long> typedef SparseVector<TValueType, TKeyType> itk::SpatiallyDenseSparseVectorImage< TValueType, VImageDimension, TKeyType >::InternalPixelType
Definition at line 63 of file itkSpatiallyDenseSparseVectorImage.h.
template<class TValueType , unsigned int VImageDimension, typename TKeyType = unsigned long> typedef InternalPixelType itk::SpatiallyDenseSparseVectorImage< TValueType, VImageDimension, TKeyType >::IOPixelType
Typedef alias for PixelType
Definition at line 66 of file itkSpatiallyDenseSparseVectorImage.h.
template<class TValueType , unsigned int VImageDimension, typename TKeyType = unsigned long> typedef TKeyType itk::SpatiallyDenseSparseVectorImage< TValueType, VImageDimension, TKeyType >::KeyType
Definition at line 62 of file itkSpatiallyDenseSparseVectorImage.h.
template<class TValueType , unsigned int VImageDimension, typename TKeyType = unsigned long> typedef SpatiallyDenseSparseVectorImageNeighborhoodAccessorFunctor< Self > itk::SpatiallyDenseSparseVectorImage< TValueType, VImageDimension, TKeyType >::NeighborhoodAccessorFunctorType
Tyepdef for the functor used to access a neighborhood of pixel pointers.
Definition at line 125 of file itkSpatiallyDenseSparseVectorImage.h.
template<class TValueType , unsigned int VImageDimension, typename TKeyType = unsigned long> typedef Superclass::OffsetType itk::SpatiallyDenseSparseVectorImage< TValueType, VImageDimension, TKeyType >::OffsetType
Offset typedef support. An offset is used to access pixel values.
Definition at line 90 of file itkSpatiallyDenseSparseVectorImage.h.
template<class TValueType , unsigned int VImageDimension, typename TKeyType = unsigned long> typedef Superclass::OffsetValueType itk::SpatiallyDenseSparseVectorImage< TValueType, VImageDimension, TKeyType >::OffsetValueType
Offset typedef (relative position between indices)
Definition at line 110 of file itkSpatiallyDenseSparseVectorImage.h.
template<class TValueType , unsigned int VImageDimension, typename TKeyType = unsigned long> typedef ImportImageContainer< SizeValueType, InternalPixelType > itk::SpatiallyDenseSparseVectorImage< TValueType, VImageDimension, TKeyType >::PixelContainer
Container used to store pixels in the image.
Definition at line 75 of file itkSpatiallyDenseSparseVectorImage.h.
template<class TValueType , unsigned int VImageDimension, typename TKeyType = unsigned long> typedef PixelContainer::ConstPointer itk::SpatiallyDenseSparseVectorImage< TValueType, VImageDimension, TKeyType >::PixelContainerConstPointer
Definition at line 79 of file itkSpatiallyDenseSparseVectorImage.h.
template<class TValueType , unsigned int VImageDimension, typename TKeyType = unsigned long> typedef PixelContainer::Pointer itk::SpatiallyDenseSparseVectorImage< TValueType, VImageDimension, TKeyType >::PixelContainerPointer
A pointer to the pixel container.
Definition at line 78 of file itkSpatiallyDenseSparseVectorImage.h.
template<class TValueType , unsigned int VImageDimension, typename TKeyType = unsigned long> typedef PixelMapType::const_iterator itk::SpatiallyDenseSparseVectorImage< TValueType, VImageDimension, TKeyType >::PixelMapConstIterator
Definition at line 84 of file itkSpatiallyDenseSparseVectorImage.h.
template<class TValueType , unsigned int VImageDimension, typename TKeyType = unsigned long> typedef PixelMapType::iterator itk::SpatiallyDenseSparseVectorImage< TValueType, VImageDimension, TKeyType >::PixelMapIterator
Definition at line 83 of file itkSpatiallyDenseSparseVectorImage.h.
template<class TValueType , unsigned int VImageDimension, typename TKeyType = unsigned long> typedef InternalPixelType::InternalDataType itk::SpatiallyDenseSparseVectorImage< TValueType, VImageDimension, TKeyType >::PixelMapType
Map used to store data.
Definition at line 82 of file itkSpatiallyDenseSparseVectorImage.h.
template<class TValueType , unsigned int VImageDimension, typename TKeyType = unsigned long> typedef VariableLengthVector< TValueType > itk::SpatiallyDenseSparseVectorImage< TValueType, VImageDimension, TKeyType >::PixelType
Pixel typedef support.
Definition at line 55 of file itkSpatiallyDenseSparseVectorImage.h.
template<class TValueType , unsigned int VImageDimension, typename TKeyType = unsigned long> typedef SmartPointer<Self> itk::SpatiallyDenseSparseVectorImage< TValueType, VImageDimension, TKeyType >::Pointer
Definition at line 47 of file itkSpatiallyDenseSparseVectorImage.h.
template<class TValueType , unsigned int VImageDimension, typename TKeyType = unsigned long> typedef Superclass::PointType itk::SpatiallyDenseSparseVectorImage< TValueType, VImageDimension, TKeyType >::PointType
Origin typedef support. The origin is the geometric coordinates of the index (0,0).
Definition at line 107 of file itkSpatiallyDenseSparseVectorImage.h.
template<class TValueType , unsigned int VImageDimension, typename TKeyType = unsigned long> typedef Superclass::RegionType itk::SpatiallyDenseSparseVectorImage< TValueType, VImageDimension, TKeyType >::RegionType
Region typedef support. A region is used to specify a subset of an image.
Definition at line 99 of file itkSpatiallyDenseSparseVectorImage.h.
template<class TValueType , unsigned int VImageDimension, typename TKeyType = unsigned long> typedef SpatiallyDenseSparseVectorImage itk::SpatiallyDenseSparseVectorImage< TValueType, VImageDimension, TKeyType >::Self
Standard class typedefs
Definition at line 45 of file itkSpatiallyDenseSparseVectorImage.h.
template<class TValueType , unsigned int VImageDimension, typename TKeyType = unsigned long> typedef Superclass::SizeType itk::SpatiallyDenseSparseVectorImage< TValueType, VImageDimension, TKeyType >::SizeType
Size typedef support. A size is used to define region bounds.
Definition at line 93 of file itkSpatiallyDenseSparseVectorImage.h.
template<class TValueType , unsigned int VImageDimension, typename TKeyType = unsigned long> typedef Superclass::SpacingType itk::SpatiallyDenseSparseVectorImage< TValueType, VImageDimension, TKeyType >::SpacingType
Spacing typedef support. Spacing holds the size of a pixel. The spacing is the geometric distance between image samples.
Definition at line 103 of file itkSpatiallyDenseSparseVectorImage.h.
template<class TValueType , unsigned int VImageDimension, typename TKeyType = unsigned long> typedef ImageBase< VImageDimension > itk::SpatiallyDenseSparseVectorImage< TValueType, VImageDimension, TKeyType >::Superclass
Definition at line 46 of file itkSpatiallyDenseSparseVectorImage.h.
template<class TValueType , unsigned int VImageDimension, typename TKeyType = unsigned long> typedef TValueType itk::SpatiallyDenseSparseVectorImage< TValueType, VImageDimension, TKeyType >::ValueType
This is the actual pixel type contained in the buffer.
Definition at line 61 of file itkSpatiallyDenseSparseVectorImage.h.
template<class TValueType , unsigned int VImageDimension, typename TKeyType = unsigned long> typedef unsigned long itk::SpatiallyDenseSparseVectorImage< TValueType, VImageDimension, TKeyType >::VectorLengthType
Definition at line 112 of file itkSpatiallyDenseSparseVectorImage.h.
Constructor & Destructor Documentation
template<class TValueType , unsigned int VImageDimension, typename TKeyType > itk::SpatiallyDenseSparseVectorImage< TValueType, VImageDimension, TKeyType >::SpatiallyDenseSparseVectorImage () protected
Definition at line 25 of file itkSpatiallyDenseSparseVectorImage.hxx.
References itk::SpatiallyDenseSparseVectorImage< TValueType, VImageDimension, TKeyType >::Allocate().
template<class TValueType , unsigned int VImageDimension, typename TKeyType = unsigned long> virtual itk::SpatiallyDenseSparseVectorImage< TValueType, VImageDimension, TKeyType >::~SpatiallyDenseSparseVectorImage () inline protected virtual
Definition at line 376 of file itkSpatiallyDenseSparseVectorImage.h.
template<class TValueType , unsigned int VImageDimension, typename TKeyType = unsigned long> itk::SpatiallyDenseSparseVectorImage< TValueType, VImageDimension, TKeyType >::SpatiallyDenseSparseVectorImage (const Self &) private
Member Function Documentation
template<class TValueType , unsigned int VImageDimension, typename TKeyType > void itk::SpatiallyDenseSparseVectorImage< TValueType, VImageDimension, TKeyType >::Allocate (bool UseDefaultConstructor = false)
Allocate the image memory. The size of the image must already be set, e.g. by calling SetRegions().
Definition at line 34 of file itkSpatiallyDenseSparseVectorImage.hxx.
References utl::ComputeOffsetTable(), and itk::SpatiallyDenseSparseVectorImage< TValueType, VImageDimension, TKeyType >::Initialize().
Referenced by itk::SpatiallyDenseSparseVectorImage< TValueType, VImageDimension, TKeyType >::SpatiallyDenseSparseVectorImage().
template<class TValueType , unsigned int VImageDimension, typename TKeyType = unsigned long> OffsetValueType itk::SpatiallyDenseSparseVectorImage< TValueType, VImageDimension, TKeyType >::ComputeOffset (const IndexType & ind) const inline
Definition at line 170 of file itkSpatiallyDenseSparseVectorImage.h.
template<class TValueType , unsigned int VImageDimension, typename TKeyType = unsigned long> virtual::itk::LightObject::Pointer itk::SpatiallyDenseSparseVectorImage< TValueType, VImageDimension, TKeyType >::CreateAnother (void) const
template<class TValueType , unsigned int VImageDimension, typename TKeyType > void itk::SpatiallyDenseSparseVectorImage< TValueType, VImageDimension, TKeyType >::FillBuffer (const PixelType & value)
Fill the image buffer with a value. Be sure to call Allocate() first.
Definition at line 65 of file itkSpatiallyDenseSparseVectorImage.hxx.
References itk::SpatiallyDenseSparseVectorImage< TValueType, VImageDimension, TKeyType >::SetPixelContainer().
Referenced by itk::SpatiallyDenseSparseVectorImage< TValueType, VImageDimension, TKeyType >::Initialize().
template<class TValueType , unsigned int VImageDimension, typename TKeyType = unsigned long> virtual const RegionType& itk::SpatiallyDenseSparseVectorImage< TValueType, VImageDimension, TKeyType >::GetBufferedRegion () const inline virtual
Buffered region has no meaning for sparse images. This method always returns the largest possible region.
See also
ImageRegion, SetLargestPossibleRegion(), SetRequestedRegion()
Definition at line 163 of file itkSpatiallyDenseSparseVectorImage.h.
References ITK_OVERRIDE.
template<class TValueType , unsigned int VImageDimension, typename TKeyType = unsigned long> InternalPixelType* itk::SpatiallyDenseSparseVectorImage< TValueType, VImageDimension, TKeyType >::GetBufferPointer () inline
Sparse images do not have buffer. This method always returns 0
Definition at line 315 of file itkSpatiallyDenseSparseVectorImage.h.
template<class TValueType , unsigned int VImageDimension, typename TKeyType = unsigned long> const InternalPixelType* itk::SpatiallyDenseSparseVectorImage< TValueType, VImageDimension, TKeyType >::GetBufferPointer () const inline
Definition at line 319 of file itkSpatiallyDenseSparseVectorImage.h.
References ITK_OVERRIDE.
template<class TValueType , unsigned int VImageDimension, typename TKeyType = unsigned long> const InternalPixelType& itk::SpatiallyDenseSparseVectorImage< TValueType, VImageDimension, TKeyType >::GetInternalPixel (const IndexType & index) const inline
Get an internal pixel (read only version).
For efficiency, this function does not check that the image has actually been allocated yet. Note that the method returns a pixel on the stack.
Definition at line 270 of file itkSpatiallyDenseSparseVectorImage.h.
template<class TValueType , unsigned int VImageDimension, typename TKeyType = unsigned long> InternalPixelType& itk::SpatiallyDenseSparseVectorImage< TValueType, VImageDimension, TKeyType >::GetInternalPixel (const IndexType & index) inline
Get an internal pixel (e.g. for editing).
For efficiency, this function does not check that the image has actually been allocated yet. Note that the method returns a pixel on the stack.
Definition at line 281 of file itkSpatiallyDenseSparseVectorImage.h.
template<class TValueType , unsigned int VImageDimension, typename TKeyType = unsigned long> virtual const char* itk::SpatiallyDenseSparseVectorImage< TValueType, VImageDimension, TKeyType >::GetNameOfClass () const virtual
Run-time type information (and related methods).
template<class TValueType , unsigned int VImageDimension, typename TKeyType = unsigned long> NeighborhoodAccessorFunctorType itk::SpatiallyDenseSparseVectorImage< TValueType, VImageDimension, TKeyType >::GetNeighborhoodAccessor () inline
Return the NeighborhoodAccessor functor
Definition at line 353 of file itkSpatiallyDenseSparseVectorImage.h.
template<class TValueType , unsigned int VImageDimension, typename TKeyType = unsigned long> const NeighborhoodAccessorFunctorType itk::SpatiallyDenseSparseVectorImage< TValueType, VImageDimension, TKeyType >::GetNeighborhoodAccessor () const inline
Return the NeighborhoodAccessor functor
Definition at line 359 of file itkSpatiallyDenseSparseVectorImage.h.
References ITK_OVERRIDE.
template<class TValueType , unsigned int VImageDimension, typename TKeyType > unsigned int itk::SpatiallyDenseSparseVectorImage< TValueType, VImageDimension, TKeyType >::GetNumberOfComponentsPerPixel () const virtual
Get/Set the number of components each pixel has, ie the VectorLength
Definition at line 133 of file itkSpatiallyDenseSparseVectorImage.hxx.
References itk::SpatiallyDenseSparseVectorImage< TValueType, VImageDimension, TKeyType >::SetNumberOfComponentsPerPixel().
Referenced by itk::SpatiallyDenseSparseVectorImage< TValueType, VImageDimension, TKeyType >::Graft().
template<class TValueType , unsigned int VImageDimension, typename TKeyType = unsigned long> const PixelType itk::SpatiallyDenseSparseVectorImage< TValueType, VImageDimension, TKeyType >::GetPixel (const IndexType & index) const inline
Get a pixel (read only version).
For efficiency, this function does not check that the image has actually been allocated yet. Note that the method returns a pixel on the stack.
Definition at line 213 of file itkSpatiallyDenseSparseVectorImage.h.
template<class TValueType , unsigned int VImageDimension, typename TKeyType = unsigned long> PixelType itk::SpatiallyDenseSparseVectorImage< TValueType, VImageDimension, TKeyType >::GetPixel (const IndexType & index) inline
Get a reference to a pixel (e.g. for editing).
For efficiency, this function does not check that the image has actually been allocated yet.
Definition at line 241 of file itkSpatiallyDenseSparseVectorImage.h.
template<class TValueType , unsigned int VImageDimension, typename TKeyType = unsigned long> AccessorType itk::SpatiallyDenseSparseVectorImage< TValueType, VImageDimension, TKeyType >::GetPixelAccessor (void) inline
Return the Pixel Accessor object
Definition at line 341 of file itkSpatiallyDenseSparseVectorImage.h.
template<class TValueType , unsigned int VImageDimension, typename TKeyType = unsigned long> const AccessorType itk::SpatiallyDenseSparseVectorImage< TValueType, VImageDimension, TKeyType >::GetPixelAccessor (void) const inline
Return the Pixel Accesor object
Definition at line 347 of file itkSpatiallyDenseSparseVectorImage.h.
template<class TValueType , unsigned int VImageDimension, typename TKeyType = unsigned long> PixelContainer* itk::SpatiallyDenseSparseVectorImage< TValueType, VImageDimension, TKeyType >::GetPixelContainer () inline
Return a pointer to the container.
Definition at line 303 of file itkSpatiallyDenseSparseVectorImage.h.
Referenced by itk::SpatiallyDenseSparseVectorImage< TValueType, VImageDimension, TKeyType >::Graft().
template<class TValueType , unsigned int VImageDimension, typename TKeyType = unsigned long> const PixelContainer* itk::SpatiallyDenseSparseVectorImage< TValueType, VImageDimension, TKeyType >::GetPixelContainer () const inline
Return a pointer to the container.
Definition at line 309 of file itkSpatiallyDenseSparseVectorImage.h.
template<class TValueType , unsigned int VImageDimension, typename TKeyType = unsigned long> virtual const VectorLengthType& itk::SpatiallyDenseSparseVectorImage< TValueType, VImageDimension, TKeyType >::GetVectorLength () virtual
template<class TValueType , unsigned int VImageDimension, typename TKeyType > void itk::SpatiallyDenseSparseVectorImage< TValueType, VImageDimension, TKeyType >::Graft (const DataObject * data) virtual
Graft the data and information from one image to another. This is a convenient method to setup a second image with all the meta information of another image and use the same pixel container. Note that this method is different than just using two SmartPointers to the same image since separate DataObjects are still maintained. This method is similar to ImageSource::GraftOutput(). The implementation in ImageBase simply calls CopyInformation() and copies the region ivars. The implementation here refers to the superclass' implementation and then copies over the pixel container.
Definition at line 94 of file itkSpatiallyDenseSparseVectorImage.hxx.
References itk::SpatiallyDenseSparseVectorImage< TValueType, VImageDimension, TKeyType >::GetNumberOfComponentsPerPixel(), and itk::SpatiallyDenseSparseVectorImage< TValueType, VImageDimension, TKeyType >::GetPixelContainer().
Referenced by itk::SpatiallyDenseSparseVectorImage< TValueType, VImageDimension, TKeyType >::SetPixelContainer().
template<class TValueType , unsigned int VImageDimension, typename TKeyType > void itk::SpatiallyDenseSparseVectorImage< TValueType, VImageDimension, TKeyType >::Initialize (void) virtual
Restore the data object to its initial state. This means releasing memory.
Definition at line 46 of file itkSpatiallyDenseSparseVectorImage.hxx.
References itk::SpatiallyDenseSparseVectorImage< TValueType, VImageDimension, TKeyType >::FillBuffer().
Referenced by itk::SpatiallyDenseSparseVectorImage< TValueType, VImageDimension, TKeyType >::Allocate().
template<class TValueType , unsigned int VImageDimension, typename TKeyType = unsigned long> static Pointer itk::SpatiallyDenseSparseVectorImage< TValueType, VImageDimension, TKeyType >::New () static
Method for creation through the object factory.
template<class TValueType , unsigned int VImageDimension, typename TKeyType = unsigned long> void itk::SpatiallyDenseSparseVectorImage< TValueType, VImageDimension, TKeyType >::operator= (const Self &) private
template<class TValueType , unsigned int VImageDimension, typename TKeyType = unsigned long> PixelType itk::SpatiallyDenseSparseVectorImage< TValueType, VImageDimension, TKeyType >::operator[] (const IndexType & index) inline
Access a pixel. This version cannot be an lvalue because the pixel is converted on the fly to a VariableLengthVector.
For efficiency, this function does not check that the image has actually been allocated yet.
Definition at line 292 of file itkSpatiallyDenseSparseVectorImage.h.
template<class TValueType , unsigned int VImageDimension, typename TKeyType = unsigned long> PixelType itk::SpatiallyDenseSparseVectorImage< TValueType, VImageDimension, TKeyType >::operator[] (const IndexType & index) const inline
Access a pixel.
For efficiency, this function does not check that the image has actually been allocated yet.
Definition at line 299 of file itkSpatiallyDenseSparseVectorImage.h.
template<class TValueType , unsigned int VImageDimension, typename TKeyType > void itk::SpatiallyDenseSparseVectorImage< TValueType, VImageDimension, TKeyType >::PrintSelf (std::ostream & os, Indent indent) const protected
Definition at line 154 of file itkSpatiallyDenseSparseVectorImage.hxx.
Referenced by itk::SpatiallyDenseSparseVectorImage< TValueType, VImageDimension, TKeyType >::SetNumberOfComponentsPerPixel().
template<class TValueType , unsigned int VImageDimension, typename TKeyType = unsigned long> virtual void itk::SpatiallyDenseSparseVectorImage< TValueType, VImageDimension, TKeyType >::SetBufferedRegion (const RegionType & region) inline virtual
Buffered region has no meaning for sparse images. This method does nothing except for computing offset table
See also
ImageRegion, SetLargestPossibleRegion(), SetRequestedRegion()
Definition at line 154 of file itkSpatiallyDenseSparseVectorImage.h.
References utl::ComputeOffsetTable().
template<class TValueType , unsigned int VImageDimension, typename TKeyType > void itk::SpatiallyDenseSparseVectorImage< TValueType, VImageDimension, TKeyType >::SetNumberOfComponentsPerPixel (unsigned int n) virtual
Definition at line 141 of file itkSpatiallyDenseSparseVectorImage.hxx.
References itk::SpatiallyDenseSparseVectorImage< TValueType, VImageDimension, TKeyType >::PrintSelf().
Referenced by itk::SpatiallyDenseSparseVectorImage< TValueType, VImageDimension, TKeyType >::GetNumberOfComponentsPerPixel().
template<class TValueType , unsigned int VImageDimension, typename TKeyType = unsigned long> void itk::SpatiallyDenseSparseVectorImage< TValueType, VImageDimension, TKeyType >::SetPixel (const IndexType & index, const PixelType & value) inline
Set a pixel value.
Allocate() needs to have been called first – for efficiency, this function does not check that the image has actually been allocated yet.
Definition at line 193 of file itkSpatiallyDenseSparseVectorImage.h.
template<class TValueType , unsigned int VImageDimension, typename TKeyType > void itk::SpatiallyDenseSparseVectorImage< TValueType, VImageDimension, TKeyType >::SetPixelContainer (PixelContainer * container)
Set the container to use. Note that this does not cause the DataObject to be modified.
Definition at line 81 of file itkSpatiallyDenseSparseVectorImage.hxx.
References itk::SpatiallyDenseSparseVectorImage< TValueType, VImageDimension, TKeyType >::Graft().
Referenced by itk::SpatiallyDenseSparseVectorImage< TValueType, VImageDimension, TKeyType >::FillBuffer().
template<class TValueType , unsigned int VImageDimension, typename TKeyType = unsigned long> void itk::SpatiallyDenseSparseVectorImage< TValueType, VImageDimension, TKeyType >::SetRegions (const RegionType & region) inline
Convenience methods to set the LargestPossibleRegion, BufferedRegion and RequestedRegion. Allocate must still be called.
Definition at line 136 of file itkSpatiallyDenseSparseVectorImage.h.
template<class TValueType , unsigned int VImageDimension, typename TKeyType = unsigned long> void itk::SpatiallyDenseSparseVectorImage< TValueType, VImageDimension, TKeyType >::SetRegions (const SizeType & size) inline
Definition at line 143 of file itkSpatiallyDenseSparseVectorImage.h.
template<class TValueType , unsigned int VImageDimension, typename TKeyType = unsigned long> virtual void itk::SpatiallyDenseSparseVectorImage< TValueType, VImageDimension, TKeyType >::SetVectorLength (VectorLengthType _arg) virtual
Set/Get macros for the length of each vector in the vector image
Member Data Documentation
template<class TValueType , unsigned int VImageDimension, typename TKeyType = unsigned long> const unsigned int itk::SpatiallyDenseSparseVectorImage< TValueType, VImageDimension, TKeyType >::ImageDimension = VImageDimension static
Dimension of the image. This constant is used by functions that are templated over image type (as opposed to being templated over pixel type and dimension) when they need compile time access to the dimension of the image.
Definition at line 72 of file itkSpatiallyDenseSparseVectorImage.h.
template<class TValueType , unsigned int VImageDimension, typename TKeyType = unsigned long> PixelContainerPointer itk::SpatiallyDenseSparseVectorImage< TValueType, VImageDimension, TKeyType >::m_Container private
Memory for the map containing the pixel data.
Definition at line 383 of file itkSpatiallyDenseSparseVectorImage.h.
template<class TValueType , unsigned int VImageDimension, typename TKeyType = unsigned long> PixelType itk::SpatiallyDenseSparseVectorImage< TValueType, VImageDimension, TKeyType >::m_FillBufferValue private
Definition at line 384 of file itkSpatiallyDenseSparseVectorImage.h.
template<class TValueType , unsigned int VImageDimension, typename TKeyType = unsigned long> VectorLengthType itk::SpatiallyDenseSparseVectorImage< TValueType, VImageDimension, TKeyType >::m_VectorLength private
Length of the "vector pixel"
Definition at line 387 of file itkSpatiallyDenseSparseVectorImage.h.
The documentation for this class was generated from the following files:
ThirdParty/SpatiallyDenseSparseVectorImage/include/itkSpatiallyDenseSparseVectorImage.h
ThirdParty/SpatiallyDenseSparseVectorImage/include/itkSpatiallyDenseSparseVectorImage.hxx