DMRITool: itk::MeshFromPeaksImageFilter< TInputImage, TOutputMesh > Class Template Reference
itk::MeshFromPeaksImageFilter< TInputImage, TOutputMesh > Class Template Reference
Visualization
#include <itkMeshFromPeaksImageFilter.h>
Detailed Description
template<class TInputImage, class TOutputMesh = vtkPolyData>
class itk::MeshFromPeaksImageFilter< TInputImage, TOutputMesh >
Generate a mesh from given peaks.
Author
Jian Cheng (jian..nosp@m.chen.nosp@m.g.198.nosp@m.3@gm.nosp@m.ail.c.nosp@m.om)
Definition at line 45 of file itkMeshFromPeaksImageFilter.h.
Public Types
typedef SmartPointer< const Self > ConstPointer
typedef InputImageType::ConstPointer InputImageConstPointer
typedef InputImageType::IndexType InputImageIndexType
typedef InputImageType::PixelType InputImagePixelType
typedef InputImageType::Pointer InputImagePointer
typedef InputImageType::PointType InputImagePointType
typedef InputImageType::RegionType InputImageRegionType
typedef InputImageType::SizeType InputImageSizeType
typedef InputImageType::SizeValueType InputImageSizeValueType
typedef InputImageType::SpacingType InputImageSpacingType
typedef TInputImage InputImageType
typedef utl_shared_ptr< MatrixType > MatrixPointer
typedef utl::NDArray< double, 2 > MatrixType
typedef Superclass::OutputMeshCellArrayType OutputMeshCellArrayType
typedef Superclass::OutputMeshPointsType OutputMeshPointsType
typedef Superclass::OutputMeshPolyDataPointer OutputMeshPolyDataPointer
typedef TOutputMesh OutputMeshPolyDataType
typedef Superclass::OutputMeshRGBType OutputMeshRGBType
typedef Superclass::OutputMeshScalarType OutputMeshScalarType
typedef SmartPointer< Self > Pointer
typedef MeshFromPeaksImageFilter Self
typedef utl_shared_ptr< STDVectorType > STDVectorPointer
typedef std::vector< double > STDVectorType
typedef MeshFromImageImageFilter< TInputImage, TOutputMesh > Superclass
typedef utl_shared_ptr< VectorType > VectorPointer
typedef utl::NDArray< double, 1 > VectorType
Public Types inherited from itk::MeshFromImageImageFilter< TInputImage, TOutputMesh >
enum ColorSchemeType {
UNKNOWN =0,
FIXED,
DIRECTION,
MAGNITUDE
}
typedef SmartPointer< const Self > ConstPointer
typedef InputImageType::ConstPointer InputImageConstPointer
typedef InputImageType::IndexType InputImageIndexType
typedef InputImageType::PixelType InputImagePixelType
typedef InputImageType::Pointer InputImagePointer
typedef InputImageType::PointType InputImagePointType
typedef InputImageType::RegionType InputImageRegionType
typedef InputImageType::SizeType InputImageSizeType
typedef InputImageType::SizeValueType InputImageSizeValueType
typedef InputImageType::SpacingType InputImageSpacingType
typedef TInputImage InputImageType
typedef utl_shared_ptr< MatrixType > MatrixPointer
typedef utl::NDArray< double, 2 > MatrixType
typedef vtkCellArray OutputMeshCellArrayType
typedef vtkPoints OutputMeshPointsType
typedef vtkSmartPointer< OutputMeshPolyDataType > OutputMeshPolyDataPointer
typedef TOutputMesh OutputMeshPolyDataType
typedef vtkUnsignedCharArray OutputMeshRGBType
typedef vtkDoubleArray OutputMeshScalarType
typedef SmartPointer< Self > Pointer
typedef MeshFromImageImageFilter Self
typedef utl_shared_ptr< STDVectorType > STDVectorPointer
typedef std::vector< double > STDVectorType
typedef MaskedImageToImageFilter< TInputImage, TInputImage > Superclass
typedef utl_shared_ptr< VectorType > VectorPointer
typedef utl::NDArray< double, 1 > VectorType
Public Types inherited from itk::MaskedImageToImageFilter< TInputImage, TInputImage >
typedef SmartPointer< const Self > ConstPointer
typedef InputImageType::ConstPointer InputImageConstPointer
typedef InputImageType::IndexType InputImageIndexType
typedef InputImageType::PixelType InputImagePixelType
typedef InputImageType::Pointer InputImagePointer
typedef InputImageType::RegionType InputImageRegionType
typedef InputImageType::SizeType InputImageSizeType
typedef InputImageType::SpacingType InputImageSpacingType
typedef TInputImage InputImageType
typedef LoggerType::Pointer LoggerPointer
typedef ThreadLogger LoggerType
typedef utl_shared_ptr< LoggerVectorType > LoggerVectorPointer
typedef std::vector< LoggerPointer > LoggerVectorType
typedef MaskImageType::Pointer MaskImagePointer
typedef Image< double, 3 > MaskImageType
typedef OutputImageType::IndexType OutputImageIndexType
typedef OutputImageType::PixelType OutputImagePixelType
typedef OutputImageType::Pointer OutputImagePointer
typedef OutputImageType::RegionType OutputImageRegionType
typedef OutputImageType::SizeType OutputImageSizeType
typedef OutputImageType::SpacingType OutputImageSpacingType
typedef TInputImage OutputImageType
typedef SmartPointer< Self > Pointer
typedef MaskedImageToImageFilter Self
typedef ImageToImageFilter< TInputImage, TInputImage > Superclass
Public Member Functions
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual const char * GetNameOfClass () const
itkSetGetMacro (PeakType, PeakType)
itkSetGetMacro (TubeRadius, double)
itkSetGetMacro (MaxNumberOfPeaks, int)
void SetColorPeak (double r, double g, double b)
Public Member Functions inherited from itk::MeshFromImageImageFilter< TInputImage, TOutputMesh >
virtual ::itk::LightObject::Pointer CreateAnother (void) const
std::vector< int > GetBoxView () const
virtual ColorSchemeType GetColorScheme ()
std::vector< int > GetFlip () const
OutputMeshPolyDataPointer GetOutput ()
virtual double GetScale ()
std::vector< int > GetSliceView () const
void SetBoxView (const int x0, const int x1, const int y0, const int y1, const int z0, const int z1)
virtual void SetColorScheme (ColorSchemeType _arg)
void SetFlip (const int flipx, const int flipy, const int flipz)
virtual void SetScale (double _arg)
void SetSliceView (const int coronal, const int sagittal, const int transverse)
Public Member Functions inherited from itk::MaskedImageToImageFilter< TInputImage, TInputImage >
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual const LoggerType * GetLogger () const
virtual const MaskImageType * GetMaskImage () const
bool IsMaskUsed ()
itkGetObjectMacro (MaskImage, MaskImageType)
itkGetObjectMacro (Logger, LoggerType)
itkSetGetMacro (LogLevel, int)
virtual void SetLogger (LoggerType *_arg)
virtual void SetMaskImage (MaskImageType *_arg)
void SetMaskImage (const std::string &file)
Static Public Member Functions
static Pointer New ()
Static Public Member Functions inherited from itk::MeshFromImageImageFilter< TInputImage, TOutputMesh >
static Pointer New ()
Static Public Member Functions inherited from itk::MaskedImageToImageFilter< TInputImage, TInputImage >
static Pointer New ()
Protected Member Functions
virtual void GenerateData () ITK_OVERRIDE
LightObject::Pointer InternalClone () const ITK_OVERRIDE
MeshFromPeaksImageFilter ()
void PrintSelf (std::ostream &os, Indent indent) const ITK_OVERRIDE
void VerifyInputParameters () const ITK_OVERRIDE
~MeshFromPeaksImageFilter ()
Protected Member Functions inherited from itk::MeshFromImageImageFilter< TInputImage, TOutputMesh >
virtual void AllocateOutputs () ITK_OVERRIDE
virtual void GenerateOutputInformation () ITK_OVERRIDE
LightObject::Pointer InternalClone () const ITK_OVERRIDE
virtual bool IsPixelIndexVisible (const InputImageIndexType &index)
MeshFromImageImageFilter ()
~MeshFromImageImageFilter ()
Protected Member Functions inherited from itk::MaskedImageToImageFilter< TInputImage, TInputImage >
void CreateLoggerVector ()
virtual void InitializeThreadedLibraries ()
LightObject::Pointer InternalClone () const ITK_OVERRIDE
MaskedImageToImageFilter ()
std::string ThreadIDToString () const
virtual void VerifyMaskInformation () const
void WriteLogger (const std::string &str, const LoggerBase::PriorityLevelType level=LoggerBase::DEBUG) const
virtual ~MaskedImageToImageFilter ()
Protected Attributes
double m_ColorPeak [3]
int m_MaxNumberOfPeaks
PeakType m_PeakType
double m_TubeRadius
Protected Attributes inherited from itk::MeshFromImageImageFilter< TInputImage, TOutputMesh >
std::vector< int > m_BoxView = std::vector<int>(6,-1)
ColorSchemeType m_ColorScheme =UNKNOWN
std::vector< int > m_Flip = std::vector<int>(3, 0)
OutputMeshPolyDataPointer m_Mesh = OutputMeshPolyDataType::New()
double m_Scale =1.0
std::vector< int > m_SliceView = std::vector<int>(3,-1)
Protected Attributes inherited from itk::MaskedImageToImageFilter< TInputImage, TInputImage >
LoggerPointer m_Logger
LoggerVectorPointer m_LoggerVector
int m_LogLevel
MaskImagePointer m_MaskImage
int m_ThreadID
Private Member Functions
MeshFromPeaksImageFilter (const Self &)
void operator= (const Self &)
Additional Inherited Members
Static Public Attributes inherited from itk::MeshFromImageImageFilter< TInputImage, TOutputMesh >
static const unsigned int OrientationDimension = 3
Static Public Attributes inherited from itk::MaskedImageToImageFilter< TInputImage, TInputImage >
static const unsigned int InputImageDimension
static const unsigned int OutputImageDimension
Member Typedef Documentation
template<class TInputImage , class TOutputMesh = vtkPolyData> typedef SmartPointer<const Self> itk::MeshFromPeaksImageFilter< TInputImage, TOutputMesh >::ConstPointer
Definition at line 52 of file itkMeshFromPeaksImageFilter.h.
template<class TInputImage , class TOutputMesh = vtkPolyData> typedef InputImageType::ConstPointer itk::MeshFromPeaksImageFilter< TInputImage, TOutputMesh >::InputImageConstPointer
Definition at line 63 of file itkMeshFromPeaksImageFilter.h.
template<class TInputImage , class TOutputMesh = vtkPolyData> typedef InputImageType::IndexType itk::MeshFromPeaksImageFilter< TInputImage, TOutputMesh >::InputImageIndexType
Definition at line 64 of file itkMeshFromPeaksImageFilter.h.
template<class TInputImage , class TOutputMesh = vtkPolyData> typedef InputImageType::PixelType itk::MeshFromPeaksImageFilter< TInputImage, TOutputMesh >::InputImagePixelType
Definition at line 68 of file itkMeshFromPeaksImageFilter.h.
template<class TInputImage , class TOutputMesh = vtkPolyData> typedef InputImageType::Pointer itk::MeshFromPeaksImageFilter< TInputImage, TOutputMesh >::InputImagePointer
Definition at line 62 of file itkMeshFromPeaksImageFilter.h.
template<class TInputImage , class TOutputMesh = vtkPolyData> typedef InputImageType::PointType itk::MeshFromPeaksImageFilter< TInputImage, TOutputMesh >::InputImagePointType
Definition at line 70 of file itkMeshFromPeaksImageFilter.h.
template<class TInputImage , class TOutputMesh = vtkPolyData> typedef InputImageType::RegionType itk::MeshFromPeaksImageFilter< TInputImage, TOutputMesh >::InputImageRegionType
Definition at line 69 of file itkMeshFromPeaksImageFilter.h.
template<class TInputImage , class TOutputMesh = vtkPolyData> typedef InputImageType::SizeType itk::MeshFromPeaksImageFilter< TInputImage, TOutputMesh >::InputImageSizeType
Definition at line 65 of file itkMeshFromPeaksImageFilter.h.
template<class TInputImage , class TOutputMesh = vtkPolyData> typedef InputImageType::SizeValueType itk::MeshFromPeaksImageFilter< TInputImage, TOutputMesh >::InputImageSizeValueType
Definition at line 66 of file itkMeshFromPeaksImageFilter.h.
template<class TInputImage , class TOutputMesh = vtkPolyData> typedef InputImageType::SpacingType itk::MeshFromPeaksImageFilter< TInputImage, TOutputMesh >::InputImageSpacingType
Definition at line 67 of file itkMeshFromPeaksImageFilter.h.
template<class TInputImage , class TOutputMesh = vtkPolyData> typedef TInputImage itk::MeshFromPeaksImageFilter< TInputImage, TOutputMesh >::InputImageType
Definition at line 58 of file itkMeshFromPeaksImageFilter.h.
template<class TInputImage , class TOutputMesh = vtkPolyData> typedef utl_shared_ptr<MatrixType> itk::MeshFromPeaksImageFilter< TInputImage, TOutputMesh >::MatrixPointer
Definition at line 84 of file itkMeshFromPeaksImageFilter.h.
template<class TInputImage , class TOutputMesh = vtkPolyData> typedef utl::NDArray<double,2> itk::MeshFromPeaksImageFilter< TInputImage, TOutputMesh >::MatrixType
Orientation Matrices
Definition at line 82 of file itkMeshFromPeaksImageFilter.h.
template<class TInputImage , class TOutputMesh = vtkPolyData> typedef Superclass::OutputMeshCellArrayType itk::MeshFromPeaksImageFilter< TInputImage, TOutputMesh >::OutputMeshCellArrayType
Definition at line 76 of file itkMeshFromPeaksImageFilter.h.
template<class TInputImage , class TOutputMesh = vtkPolyData> typedef Superclass::OutputMeshPointsType itk::MeshFromPeaksImageFilter< TInputImage, TOutputMesh >::OutputMeshPointsType
Definition at line 75 of file itkMeshFromPeaksImageFilter.h.
template<class TInputImage , class TOutputMesh = vtkPolyData> typedef Superclass::OutputMeshPolyDataPointer itk::MeshFromPeaksImageFilter< TInputImage, TOutputMesh >::OutputMeshPolyDataPointer
Definition at line 77 of file itkMeshFromPeaksImageFilter.h.
template<class TInputImage , class TOutputMesh = vtkPolyData> typedef TOutputMesh itk::MeshFromPeaksImageFilter< TInputImage, TOutputMesh >::OutputMeshPolyDataType
Definition at line 73 of file itkMeshFromPeaksImageFilter.h.
template<class TInputImage , class TOutputMesh = vtkPolyData> typedef Superclass::OutputMeshRGBType itk::MeshFromPeaksImageFilter< TInputImage, TOutputMesh >::OutputMeshRGBType
Definition at line 79 of file itkMeshFromPeaksImageFilter.h.
template<class TInputImage , class TOutputMesh = vtkPolyData> typedef Superclass::OutputMeshScalarType itk::MeshFromPeaksImageFilter< TInputImage, TOutputMesh >::OutputMeshScalarType
Definition at line 78 of file itkMeshFromPeaksImageFilter.h.
template<class TInputImage , class TOutputMesh = vtkPolyData> typedef SmartPointer<Self> itk::MeshFromPeaksImageFilter< TInputImage, TOutputMesh >::Pointer
Definition at line 51 of file itkMeshFromPeaksImageFilter.h.
template<class TInputImage , class TOutputMesh = vtkPolyData> typedef MeshFromPeaksImageFilter itk::MeshFromPeaksImageFilter< TInputImage, TOutputMesh >::Self
Definition at line 49 of file itkMeshFromPeaksImageFilter.h.
template<class TInputImage , class TOutputMesh = vtkPolyData> typedef utl_shared_ptr<STDVectorType > itk::MeshFromPeaksImageFilter< TInputImage, TOutputMesh >::STDVectorPointer
Definition at line 87 of file itkMeshFromPeaksImageFilter.h.
template<class TInputImage , class TOutputMesh = vtkPolyData> typedef std::vector<double> itk::MeshFromPeaksImageFilter< TInputImage, TOutputMesh >::STDVectorType
Definition at line 86 of file itkMeshFromPeaksImageFilter.h.
template<class TInputImage , class TOutputMesh = vtkPolyData> typedef MeshFromImageImageFilter<TInputImage, TOutputMesh> itk::MeshFromPeaksImageFilter< TInputImage, TOutputMesh >::Superclass
Definition at line 50 of file itkMeshFromPeaksImageFilter.h.
template<class TInputImage , class TOutputMesh = vtkPolyData> typedef utl_shared_ptr<VectorType> itk::MeshFromPeaksImageFilter< TInputImage, TOutputMesh >::VectorPointer
Definition at line 85 of file itkMeshFromPeaksImageFilter.h.
template<class TInputImage , class TOutputMesh = vtkPolyData> typedef utl::NDArray<double,1> itk::MeshFromPeaksImageFilter< TInputImage, TOutputMesh >::VectorType
Definition at line 83 of file itkMeshFromPeaksImageFilter.h.
Constructor & Destructor Documentation
template<class TInputImage , class TOutputMesh > itk::MeshFromPeaksImageFilter< TInputImage, TOutputMesh >::MeshFromPeaksImageFilter () protected
Definition at line 22 of file itkMeshFromPeaksImageFilter.hxx.
References itk::MeshFromPeaksImageFilter< TInputImage, TOutputMesh >::InternalClone(), and itk::XYZV.
template<class TInputImage , class TOutputMesh = vtkPolyData> itk::MeshFromPeaksImageFilter< TInputImage, TOutputMesh >::~MeshFromPeaksImageFilter () inline protected
Definition at line 101 of file itkMeshFromPeaksImageFilter.h.
template<class TInputImage , class TOutputMesh = vtkPolyData> itk::MeshFromPeaksImageFilter< TInputImage, TOutputMesh >::MeshFromPeaksImageFilter (const Self &) private
Member Function Documentation
template<class TInputImage , class TOutputMesh = vtkPolyData> virtual::itk::LightObject::Pointer itk::MeshFromPeaksImageFilter< TInputImage, TOutputMesh >::CreateAnother (void) const
template<class TInputImage , class TOutputMesh > void itk::MeshFromPeaksImageFilter< TInputImage, TOutputMesh >::GenerateData (void) protected virtual
Definition at line 58 of file itkMeshFromPeaksImageFilter.hxx.
References itk::PeakContainerHelper::GetDimensionPerPeak(), itk::PeakContainerHelper::GetNumberOfPeaks(), itk::PeakContainerHelper::GetPeak(), and utl::min().
Referenced by itk::MeshFromPeaksImageFilter< TInputImage, TOutputMesh >::InternalClone().
template<class TInputImage , class TOutputMesh = vtkPolyData> virtual const char* itk::MeshFromPeaksImageFilter< TInputImage, TOutputMesh >::GetNameOfClass () const virtual
Run-time type information (and related methods)
Reimplemented from itk::MeshFromImageImageFilter< TInputImage, TOutputMesh >.
template<class TInputImage , class TOutputMesh > LightObject::Pointer itk::MeshFromPeaksImageFilter< TInputImage, TOutputMesh >::InternalClone () const protected
Definition at line 35 of file itkMeshFromPeaksImageFilter.hxx.
References itk::MeshFromPeaksImageFilter< TInputImage, TOutputMesh >::GenerateData().
Referenced by itk::MeshFromPeaksImageFilter< TInputImage, TOutputMesh >::MeshFromPeaksImageFilter().
template<class TInputImage , class TOutputMesh = vtkPolyData> itk::MeshFromPeaksImageFilter< TInputImage, TOutputMesh >::itkSetGetMacro (PeakType , PeakType)
template<class TInputImage , class TOutputMesh = vtkPolyData> itk::MeshFromPeaksImageFilter< TInputImage, TOutputMesh >::itkSetGetMacro (TubeRadius , double)
template<class TInputImage , class TOutputMesh = vtkPolyData> itk::MeshFromPeaksImageFilter< TInputImage, TOutputMesh >::itkSetGetMacro (MaxNumberOfPeaks , int)
template<class TInputImage , class TOutputMesh = vtkPolyData> static Pointer itk::MeshFromPeaksImageFilter< TInputImage, TOutputMesh >::New () static
Method for creation through the object factory.
template<class TInputImage , class TOutputMesh = vtkPolyData> void itk::MeshFromPeaksImageFilter< TInputImage, TOutputMesh >::operator= (const Self &) private
template<class TInputImage , class TOutputMesh = vtkPolyData> void itk::MeshFromPeaksImageFilter< TInputImage, TOutputMesh >::PrintSelf (std::ostream & os, Indent indent) const inline protected virtual
Reimplemented from itk::MeshFromImageImageFilter< TInputImage, TOutputMesh >.
Definition at line 112 of file itkMeshFromPeaksImageFilter.h.
References itk::PeakContainerHelper::GetString(), ITK_OVERRIDE, and PrintVar.
template<class TInputImage , class TOutputMesh = vtkPolyData> void itk::MeshFromPeaksImageFilter< TInputImage, TOutputMesh >::SetColorPeak (double r, double g, double b) inline
Definition at line 93 of file itkMeshFromPeaksImageFilter.h.
template<class TInputImage , class TOutputMesh = vtkPolyData> void itk::MeshFromPeaksImageFilter< TInputImage, TOutputMesh >::VerifyInputParameters () const inline protected virtual
Reimplemented from itk::MeshFromImageImageFilter< TInputImage, TOutputMesh >.
Definition at line 104 of file itkMeshFromPeaksImageFilter.h.
References ITK_OVERRIDE, and utlSAException.
Member Data Documentation
template<class TInputImage , class TOutputMesh = vtkPolyData> double itk::MeshFromPeaksImageFilter< TInputImage, TOutputMesh >::m_ColorPeak[3] protected
Definition at line 126 of file itkMeshFromPeaksImageFilter.h.
template<class TInputImage , class TOutputMesh = vtkPolyData> int itk::MeshFromPeaksImageFilter< TInputImage, TOutputMesh >::m_MaxNumberOfPeaks protected
If m_MaxNumberOfPeaks>0, then only visualize the first m_MaxNumberOfPeaks peaks.
Definition at line 129 of file itkMeshFromPeaksImageFilter.h.
template<class TInputImage , class TOutputMesh = vtkPolyData> PeakType itk::MeshFromPeaksImageFilter< TInputImage, TOutputMesh >::m_PeakType protected
Definition at line 121 of file itkMeshFromPeaksImageFilter.h.
template<class TInputImage , class TOutputMesh = vtkPolyData> double itk::MeshFromPeaksImageFilter< TInputImage, TOutputMesh >::m_TubeRadius protected
If it is positive, use tubes for peaks. If it is non-positive, use lines.
Definition at line 124 of file itkMeshFromPeaksImageFilter.h.
The documentation for this class was generated from the following files:
Modules/Visualization/include/itkMeshFromPeaksImageFilter.h
Modules/Visualization/include/itkMeshFromPeaksImageFilter.hxx