DMRITool: itk::VTKImageDataToImageFilter< TOutputImage > Class Template Reference
itk::VTKImageDataToImageFilter< TOutputImage > Class Template Reference
#include <itkVTKImageDataToImageFilter.h>
Detailed Description
template<class TOutputImage>
class itk::VTKImageDataToImageFilter< TOutputImage >
Convert VTK image data to an ITK image.
Definition at line 30 of file itkVTKImageDataToImageFilter.h.
Public Types
typedef SmartPointer< const Self > ConstPointer
typedef vtkSmartPointer< vtkImageData > InputImageType
typedef ImageRegionIterator< OutputImageType > OutputImageIteratorType
typedef OutputImageType::Pointer OutputImagePointer
typedef TOutputImage OutputImageType
typedef OutputImageType::IndexType OutputIndexType
typedef OutputImageType::PixelType OutputPixelType
typedef OutputImageType::PointType OutputPointType
typedef OutputImageType::RegionType OutputRegionType
typedef OutputImageType::SizeType OutputSizeType
typedef OutputImageType::SpacingType OutputSpacingType
typedef SmartPointer< Self > Pointer
typedef VTKImageDataToImageFilter Self
typedef ImageSource< TOutputImage > Superclass
Public Member Functions
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual const char * GetNameOfClass () const
void SetInputData (vtkImageData *)
Static Public Member Functions
static Pointer New ()
Static Public Attributes
static const unsigned int Dimension = TOutputImage::ImageDimension
Protected Member Functions
virtual void GenerateData () ITK_OVERRIDE
VTKImageDataToImageFilter ()
virtual ~VTKImageDataToImageFilter ()
Private Member Functions
void operator= (const Self &)
VTKImageDataToImageFilter (const Self &)
Private Attributes
InputImageType m_Image
Member Typedef Documentation
template<class TOutputImage > typedef SmartPointer<const Self> itk::VTKImageDataToImageFilter< TOutputImage >::ConstPointer
Definition at line 38 of file itkVTKImageDataToImageFilter.h.
template<class TOutputImage > typedef vtkSmartPointer<vtkImageData> itk::VTKImageDataToImageFilter< TOutputImage >::InputImageType
Definition at line 59 of file itkVTKImageDataToImageFilter.h.
template<class TOutputImage > typedef ImageRegionIterator<OutputImageType> itk::VTKImageDataToImageFilter< TOutputImage >::OutputImageIteratorType
Definition at line 58 of file itkVTKImageDataToImageFilter.h.
template<class TOutputImage > typedef OutputImageType::Pointer itk::VTKImageDataToImageFilter< TOutputImage >::OutputImagePointer
Definition at line 51 of file itkVTKImageDataToImageFilter.h.
template<class TOutputImage > typedef TOutputImage itk::VTKImageDataToImageFilter< TOutputImage >::OutputImageType
Some typedefs.
Definition at line 50 of file itkVTKImageDataToImageFilter.h.
template<class TOutputImage > typedef OutputImageType::IndexType itk::VTKImageDataToImageFilter< TOutputImage >::OutputIndexType
Definition at line 56 of file itkVTKImageDataToImageFilter.h.
template<class TOutputImage > typedef OutputImageType::PixelType itk::VTKImageDataToImageFilter< TOutputImage >::OutputPixelType
Definition at line 57 of file itkVTKImageDataToImageFilter.h.
template<class TOutputImage > typedef OutputImageType::PointType itk::VTKImageDataToImageFilter< TOutputImage >::OutputPointType
Definition at line 55 of file itkVTKImageDataToImageFilter.h.
template<class TOutputImage > typedef OutputImageType::RegionType itk::VTKImageDataToImageFilter< TOutputImage >::OutputRegionType
Definition at line 52 of file itkVTKImageDataToImageFilter.h.
template<class TOutputImage > typedef OutputImageType::SizeType itk::VTKImageDataToImageFilter< TOutputImage >::OutputSizeType
Definition at line 53 of file itkVTKImageDataToImageFilter.h.
template<class TOutputImage > typedef OutputImageType::SpacingType itk::VTKImageDataToImageFilter< TOutputImage >::OutputSpacingType
Definition at line 54 of file itkVTKImageDataToImageFilter.h.
template<class TOutputImage > typedef SmartPointer<Self> itk::VTKImageDataToImageFilter< TOutputImage >::Pointer
Definition at line 37 of file itkVTKImageDataToImageFilter.h.
template<class TOutputImage > typedef VTKImageDataToImageFilter itk::VTKImageDataToImageFilter< TOutputImage >::Self
Standard class typedefs.
Definition at line 35 of file itkVTKImageDataToImageFilter.h.
template<class TOutputImage > typedef ImageSource<TOutputImage> itk::VTKImageDataToImageFilter< TOutputImage >::Superclass
Definition at line 36 of file itkVTKImageDataToImageFilter.h.
Constructor & Destructor Documentation
template<class TOutputImage > itk::VTKImageDataToImageFilter< TOutputImage >::VTKImageDataToImageFilter () protected
Constructor
Definition at line 31 of file itkVTKImageDataToImageFilter.hxx.
References itk::VTKImageDataToImageFilter< TOutputImage >::SetInputData().
template<class TOutputImage > virtual itk::VTKImageDataToImageFilter< TOutputImage >::~VTKImageDataToImageFilter () inline protected virtual
Definition at line 66 of file itkVTKImageDataToImageFilter.h.
References ITK_OVERRIDE.
template<class TOutputImage > itk::VTKImageDataToImageFilter< TOutputImage >::VTKImageDataToImageFilter (const Self &) private
Member Function Documentation
template<class TOutputImage > virtual::itk::LightObject::Pointer itk::VTKImageDataToImageFilter< TOutputImage >::CreateAnother (void) const
template<class TOutputImage > void itk::VTKImageDataToImageFilter< TOutputImage >::GenerateData (void) protected virtual
Generate the data
Definition at line 58 of file itkVTKImageDataToImageFilter.hxx.
Referenced by itk::VTKImageDataToImageFilter< TOutputImage >::SetInputData().
template<class TOutputImage > virtual const char* itk::VTKImageDataToImageFilter< TOutputImage >::GetNameOfClass () const virtual
Run-time type information (and related methods).
template<class TOutputImage > static Pointer itk::VTKImageDataToImageFilter< TOutputImage >::New () static
Method for creation through the object factory.
template<class TOutputImage > void itk::VTKImageDataToImageFilter< TOutputImage >::operator= (const Self &) private
template<class TOutputImage > void itk::VTKImageDataToImageFilter< TOutputImage >::SetInputData (vtkImageData * inputImage)
Set the input in the form of a vtkImageData
Set a vtkImageData as input
Definition at line 42 of file itkVTKImageDataToImageFilter.hxx.
References itk::VTKImageDataToImageFilter< TOutputImage >::GenerateData().
Referenced by itk::VTKImageDataToImageFilter< TOutputImage >::VTKImageDataToImageFilter().
Member Data Documentation
template<class TOutputImage > const unsigned int itk::VTKImageDataToImageFilter< TOutputImage >::Dimension = TOutputImage::ImageDimension static
Image Dimension
Definition at line 47 of file itkVTKImageDataToImageFilter.h.
template<class TOutputImage > InputImageType itk::VTKImageDataToImageFilter< TOutputImage >::m_Image private
Definition at line 74 of file itkVTKImageDataToImageFilter.h.
The documentation for this class was generated from the following files:
Modules/Visualization/include/itkVTKImageDataToImageFilter.h
Modules/Visualization/include/itkVTKImageDataToImageFilter.hxx