DMRITool: utl::Functor::Shred< TVector, TOutput > Class Template Reference
utl::Functor::Shred< TVector, TOutput > Class Template Reference
#include <utlFunctors.h>
Detailed Description
template<class TVector, class TOutput = TVector>
class utl::Functor::Shred< TVector, TOutput >
obtain a part of a vector.
For a vector with size m_Offset + N*(m_ChunkSize + m_Space) + residual, The output vector has size N*m_ChunkSize + std::min(residual, m_ChunkSize).
Definition at line 412 of file utlFunctors.h.
Public Types
typedef Shred Self
typedef VectorFunctorBase< TVector, TOutput > Superclass
Public Types inherited from utl::Functor::VectorFunctorBase< TVector, TOutput >
typedef VectorFunctorBase Self
Public Member Functions
std::vector< int > GetArguments ()
virtual int GetChunkSize () const
virtual int GetOffset () const
int GetOutputDimension (const int inputSize) const
virtual int GetSpace () const
bool operator!= (const Self &other) const
TOutput operator() (const TVector &A) const
Self & operator= (const Self &other)
bool operator== (const Self &other) const
void Print (std::ostream &os=std::cout) const
void SetArguments (const std::vector< int > &vec)
virtual void SetChunkSize (const int _arg)
virtual void SetOffset (const int _arg)
virtual void SetSpace (const int _arg)
Public Member Functions inherited from utl::Functor::VectorFunctorBase< TVector, TOutput >
virtual int GetLogLevel () const
int GetOutputDimension (const int inputSize) const
int GetOutputDimension (const std::vector< int > &sizeVec) const
void Initialize ()
bool operator!= (const Self &other) const
Self & operator= (const Self &other)
bool operator== (const Self &other) const
void Print (std::ostream &os=std::cout) const
virtual void SetLogLevel (const int _arg)
void VerifyInputParameters (const int inputSize=-1) const
Protected Attributes
int m_ChunkSize
int m_Offset
int m_Space
Protected Attributes inherited from utl::Functor::VectorFunctorBase< TVector, TOutput >
int m_LogLevel =1
Member Typedef Documentation
template<class TVector, class TOutput = TVector> typedef Shred utl::Functor::Shred< TVector, TOutput >::Self
Definition at line 415 of file utlFunctors.h.
template<class TVector, class TOutput = TVector> typedef VectorFunctorBase<TVector, TOutput> utl::Functor::Shred< TVector, TOutput >::Superclass
Definition at line 416 of file utlFunctors.h.
Member Function Documentation
template<class TVector, class TOutput = TVector> std::vector<int> utl::Functor::Shred< TVector, TOutput >::GetArguments () inline
Definition at line 467 of file utlFunctors.h.
template<class TVector, class TOutput = TVector> virtual int utl::Functor::Shred< TVector, TOutput >::GetChunkSize () const inline virtual
Definition at line 477 of file utlFunctors.h.
template<class TVector, class TOutput = TVector> virtual int utl::Functor::Shred< TVector, TOutput >::GetOffset () const inline virtual
Definition at line 476 of file utlFunctors.h.
template<class TVector, class TOutput = TVector> int utl::Functor::Shred< TVector, TOutput >::GetOutputDimension (const int inputSize) const inline
Definition at line 451 of file utlFunctors.h.
References utl::min().
template<class TVector, class TOutput = TVector> virtual int utl::Functor::Shred< TVector, TOutput >::GetSpace () const inline virtual
Definition at line 478 of file utlFunctors.h.
template<class TVector, class TOutput = TVector> bool utl::Functor::Shred< TVector, TOutput >::operator!= (const Self & other) const inline
Definition at line 420 of file utlFunctors.h.
template<class TVector, class TOutput = TVector> TOutput utl::Functor::Shred< TVector, TOutput >::operator() (const TVector & A) const inline
Definition at line 435 of file utlFunctors.h.
References utl::Functor::VectorFunctorBase< TVector, TOutput >::GetOutputDimension().
template<class TVector, class TOutput = TVector> Self& utl::Functor::Shred< TVector, TOutput >::operator= (const Self & other) inline
Definition at line 423 of file utlFunctors.h.
template<class TVector, class TOutput = TVector> bool utl::Functor::Shred< TVector, TOutput >::operator== (const Self & other) const inline
Definition at line 418 of file utlFunctors.h.
template<class TVector, class TOutput = TVector> void utl::Functor::Shred< TVector, TOutput >::Print (std::ostream & os = std::cout) const inline
Definition at line 480 of file utlFunctors.h.
References utl::Print(), and utlLogOSVar.
template<class TVector, class TOutput = TVector> void utl::Functor::Shred< TVector, TOutput >::SetArguments (const std::vector< int > & vec) inline
Definition at line 459 of file utlFunctors.h.
References utlException.
template<class TVector, class TOutput = TVector> virtual void utl::Functor::Shred< TVector, TOutput >::SetChunkSize (const int _arg) inline virtual
Definition at line 477 of file utlFunctors.h.
Referenced by ImageMath().
template<class TVector, class TOutput = TVector> virtual void utl::Functor::Shred< TVector, TOutput >::SetOffset (const int _arg) inline virtual
Definition at line 476 of file utlFunctors.h.
Referenced by ImageMath().
template<class TVector, class TOutput = TVector> virtual void utl::Functor::Shred< TVector, TOutput >::SetSpace (const int _arg) inline virtual
Definition at line 478 of file utlFunctors.h.
Referenced by ImageMath().
Member Data Documentation
template<class TVector, class TOutput = TVector> int utl::Functor::Shred< TVector, TOutput >::m_ChunkSize protected
Definition at line 488 of file utlFunctors.h.
template<class TVector, class TOutput = TVector> int utl::Functor::Shred< TVector, TOutput >::m_Offset protected
Definition at line 487 of file utlFunctors.h.
template<class TVector, class TOutput = TVector> int utl::Functor::Shred< TVector, TOutput >::m_Space protected
Definition at line 489 of file utlFunctors.h.
The documentation for this class was generated from the following file:
Modules/HelperFunctions/include/utlFunctors.h