DMRITool: itk::MeshFromContinuousSphericalFunctionImageFilter< TInputImage, TOutputMesh > Class Template Reference
itk::MeshFromContinuousSphericalFunctionImageFilter< TInputImage, TOutputMesh > Class Template Reference
Visualization
#include <itkMeshFromContinuousSphericalFunctionImageFilter.h>
Detailed Description
template<class TInputImage, class TOutputMesh = vtkPolyData>
class itk::MeshFromContinuousSphericalFunctionImageFilter< TInputImage, TOutputMesh >
Compute mesh from continuous spherical function linearly represented by a set of bases.
The samples of a spherical function is linearly represented by a set of bases.
For a generic spherical function, we can 1) generate the spherical samples in vertices of a pre-stored gradient table. 2) use itk::MeshFromSphericalFunctionTessellatedSamplesImageFilter to visualize the tessellated samples.
Author
Jian Cheng (jian..nosp@m.chen.nosp@m.g.198.nosp@m.3@gm.nosp@m.ail.c.nosp@m.om)
Definition at line 41 of file itkMeshFromContinuousSphericalFunctionImageFilter.h.
Public Types
typedef SphereTessellatorType::BasicShapeType BasicShapeType
typedef SmartPointer< const Self > ConstPointer
typedef InputImageType::ConstPointer InputImageConstPointer
typedef InputImageType::IndexType InputImageIndexType
typedef InputImageType::PixelType InputImagePixelType
typedef InputImageType::Pointer InputImagePointer
typedef InputImageType::PointType InputImagePointType
typedef InputImageType::RegionType InputImageRegionType
typedef InputImageType::SizeType InputImageSizeType
typedef InputImageType::SizeValueType InputImageSizeValueType
typedef InputImageType::SpacingType InputImageSpacingType
typedef TInputImage InputImageType
typedef Superclass::MatrixPointer MatrixPointer
typedef Superclass::MatrixType MatrixType
typedef Superclass::OutputMeshCellArrayType OutputMeshCellArrayType
typedef Superclass::OutputMeshPointsType OutputMeshPointsType
typedef Superclass::OutputMeshPolyDataPointer OutputMeshPolyDataPointer
typedef TOutputMesh OutputMeshPolyDataType
typedef Superclass::OutputMeshRGBType OutputMeshRGBType
typedef Superclass::OutputMeshScalarType OutputMeshScalarType
typedef SmartPointer< Self > Pointer
typedef MeshFromContinuousSphericalFunctionImageFilter Self
typedef SphereTessellatorType::Pointer SphereTessellatorPointer
typedef SphereTessellator< double > SphereTessellatorType
typedef Superclass::STDVectorPointer STDVectorPointer
typedef Superclass::STDVectorType STDVectorType
typedef MeshFromSphericalFunctionImageFilter< TInputImage, TOutputMesh > Superclass
typedef Superclass::VectorPointer VectorPointer
typedef Superclass::VectorType VectorType
Public Types inherited from itk::MeshFromSphericalFunctionImageFilter< TInputImage, TOutputMesh >
typedef SphereTessellatorType::BasicShapeType BasicShapeType
typedef SmartPointer< const Self > ConstPointer
typedef InputImageType::ConstPointer InputImageConstPointer
typedef InputImageType::IndexType InputImageIndexType
typedef InputImageType::PixelType InputImagePixelType
typedef InputImageType::Pointer InputImagePointer
typedef InputImageType::PointType InputImagePointType
typedef InputImageType::RegionType InputImageRegionType
typedef InputImageType::SizeType InputImageSizeType
typedef InputImageType::SizeValueType InputImageSizeValueType
typedef InputImageType::SpacingType InputImageSpacingType
typedef TInputImage InputImageType
typedef Superclass::MatrixPointer MatrixPointer
typedef Superclass::MatrixType MatrixType
enum NormalizationType {
NONE =0,
MIN_MAX,
UNIT_MAX,
UNIT_INTEGRAL
}
typedef Superclass::OutputMeshCellArrayType OutputMeshCellArrayType
typedef Superclass::OutputMeshPointsType OutputMeshPointsType
typedef Superclass::OutputMeshPolyDataPointer OutputMeshPolyDataPointer
typedef TOutputMesh OutputMeshPolyDataType
typedef Superclass::OutputMeshRGBType OutputMeshRGBType
typedef Superclass::OutputMeshScalarType OutputMeshScalarType
typedef SmartPointer< Self > Pointer
typedef MeshFromSphericalFunctionImageFilter Self
typedef SphereTessellatorType::Pointer SphereTessellatorPointer
typedef SphereTessellator< double > SphereTessellatorType
typedef Superclass::STDVectorPointer STDVectorPointer
typedef Superclass::STDVectorType STDVectorType
typedef MeshFromImageImageFilter< TInputImage, TOutputMesh > Superclass
typedef Superclass::VectorPointer VectorPointer
typedef Superclass::VectorType VectorType
Public Types inherited from itk::MeshFromImageImageFilter< TInputImage, TOutputMesh >
enum ColorSchemeType {
UNKNOWN =0,
FIXED,
DIRECTION,
MAGNITUDE
}
typedef SmartPointer< const Self > ConstPointer
typedef InputImageType::ConstPointer InputImageConstPointer
typedef InputImageType::IndexType InputImageIndexType
typedef InputImageType::PixelType InputImagePixelType
typedef InputImageType::Pointer InputImagePointer
typedef InputImageType::PointType InputImagePointType
typedef InputImageType::RegionType InputImageRegionType
typedef InputImageType::SizeType InputImageSizeType
typedef InputImageType::SizeValueType InputImageSizeValueType
typedef InputImageType::SpacingType InputImageSpacingType
typedef TInputImage InputImageType
typedef utl_shared_ptr< MatrixType > MatrixPointer
typedef utl::NDArray< double, 2 > MatrixType
typedef vtkCellArray OutputMeshCellArrayType
typedef vtkPoints OutputMeshPointsType
typedef vtkSmartPointer< OutputMeshPolyDataType > OutputMeshPolyDataPointer
typedef TOutputMesh OutputMeshPolyDataType
typedef vtkUnsignedCharArray OutputMeshRGBType
typedef vtkDoubleArray OutputMeshScalarType
typedef SmartPointer< Self > Pointer
typedef MeshFromImageImageFilter Self
typedef utl_shared_ptr< STDVectorType > STDVectorPointer
typedef std::vector< double > STDVectorType
typedef MaskedImageToImageFilter< TInputImage, TInputImage > Superclass
typedef utl_shared_ptr< VectorType > VectorPointer
typedef utl::NDArray< double, 1 > VectorType
Public Types inherited from itk::MaskedImageToImageFilter< TInputImage, TInputImage >
typedef SmartPointer< const Self > ConstPointer
typedef InputImageType::ConstPointer InputImageConstPointer
typedef InputImageType::IndexType InputImageIndexType
typedef InputImageType::PixelType InputImagePixelType
typedef InputImageType::Pointer InputImagePointer
typedef InputImageType::RegionType InputImageRegionType
typedef InputImageType::SizeType InputImageSizeType
typedef InputImageType::SpacingType InputImageSpacingType
typedef TInputImage InputImageType
typedef LoggerType::Pointer LoggerPointer
typedef ThreadLogger LoggerType
typedef utl_shared_ptr< LoggerVectorType > LoggerVectorPointer
typedef std::vector< LoggerPointer > LoggerVectorType
typedef MaskImageType::Pointer MaskImagePointer
typedef Image< double, 3 > MaskImageType
typedef OutputImageType::IndexType OutputImageIndexType
typedef OutputImageType::PixelType OutputImagePixelType
typedef OutputImageType::Pointer OutputImagePointer
typedef OutputImageType::RegionType OutputImageRegionType
typedef OutputImageType::SizeType OutputImageSizeType
typedef OutputImageType::SpacingType OutputImageSpacingType
typedef TInputImage OutputImageType
typedef SmartPointer< Self > Pointer
typedef MaskedImageToImageFilter Self
typedef ImageToImageFilter< TInputImage, TInputImage > Superclass
Public Member Functions
virtual MatrixPointer ComputeBasisMatrix ()
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual BasicShapeType GetBasicShape ()
virtual MatrixPointer GetBasisMatrix ()
virtual const char * GetNameOfClass () const
virtual unsigned int GetTessellationOrder ()
itkSetGetBooleanMacro (Stretch)
virtual VectorType NormalizeUnitIntegral (const VectorType &x) const
virtual void SetBasicShape (BasicShapeType _arg)
virtual void SetBasisMatrix (MatrixPointer _arg)
virtual void SetTessellationOrder (unsigned int _arg)
Public Member Functions inherited from itk::MeshFromSphericalFunctionImageFilter< TInputImage, TOutputMesh >
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual NormalizationType GetNormalization ()
unsigned int GetNumberOfOrientations () const
virtual MatrixPointer GetOrientations ()
virtual double GetPow ()
virtual bool GetRemoveNegativeValues ()
virtual void RemoveNegativeValuesOff ()
virtual void RemoveNegativeValuesOn ()
virtual void SetNormalization (NormalizationType _arg)
virtual void SetOrientations (MatrixPointer _arg)
virtual void SetPow (double _arg)
virtual void SetRemoveNegativeValues (bool _arg)
Public Member Functions inherited from itk::MeshFromImageImageFilter< TInputImage, TOutputMesh >
virtual ::itk::LightObject::Pointer CreateAnother (void) const
std::vector< int > GetBoxView () const
virtual ColorSchemeType GetColorScheme ()
std::vector< int > GetFlip () const
OutputMeshPolyDataPointer GetOutput ()
virtual double GetScale ()
std::vector< int > GetSliceView () const
void SetBoxView (const int x0, const int x1, const int y0, const int y1, const int z0, const int z1)
virtual void SetColorScheme (ColorSchemeType _arg)
void SetFlip (const int flipx, const int flipy, const int flipz)
virtual void SetScale (double _arg)
void SetSliceView (const int coronal, const int sagittal, const int transverse)
Public Member Functions inherited from itk::MaskedImageToImageFilter< TInputImage, TInputImage >
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual const LoggerType * GetLogger () const
virtual const MaskImageType * GetMaskImage () const
bool IsMaskUsed ()
itkGetObjectMacro (MaskImage, MaskImageType)
itkGetObjectMacro (Logger, LoggerType)
itkSetGetMacro (LogLevel, int)
virtual void SetLogger (LoggerType *_arg)
virtual void SetMaskImage (MaskImageType *_arg)
void SetMaskImage (const std::string &file)
Static Public Member Functions
static Pointer New ()
Static Public Member Functions inherited from itk::MeshFromSphericalFunctionImageFilter< TInputImage, TOutputMesh >
static Pointer New ()
Static Public Member Functions inherited from itk::MeshFromImageImageFilter< TInputImage, TOutputMesh >
static Pointer New ()
Static Public Member Functions inherited from itk::MaskedImageToImageFilter< TInputImage, TInputImage >
static Pointer New ()
Protected Member Functions
void BeforeThreadedGenerateData () ITK_OVERRIDE
LightObject::Pointer InternalClone () const ITK_OVERRIDE
MeshFromContinuousSphericalFunctionImageFilter ()
void PrintSelf (std::ostream &os, Indent indent) const ITK_OVERRIDE
void ScaleSamples (VectorType &b) const
void ThreadedGenerateData (const typename TInputImage::RegionType &regionForThread, ThreadIdType threadId) ITK_OVERRIDE
void VerifyInputParameters () const ITK_OVERRIDE
~MeshFromContinuousSphericalFunctionImageFilter ()
Protected Member Functions inherited from itk::MeshFromSphericalFunctionImageFilter< TInputImage, TOutputMesh >
LightObject::Pointer InternalClone () const ITK_OVERRIDE
MeshFromSphericalFunctionImageFilter ()
void PrintSelf (std::ostream &os, Indent indent) const ITK_OVERRIDE
~MeshFromSphericalFunctionImageFilter ()
Protected Member Functions inherited from itk::MeshFromImageImageFilter< TInputImage, TOutputMesh >
virtual void AllocateOutputs () ITK_OVERRIDE
virtual void GenerateOutputInformation () ITK_OVERRIDE
LightObject::Pointer InternalClone () const ITK_OVERRIDE
virtual bool IsPixelIndexVisible (const InputImageIndexType &index)
MeshFromImageImageFilter ()
~MeshFromImageImageFilter ()
Protected Member Functions inherited from itk::MaskedImageToImageFilter< TInputImage, TInputImage >
void CreateLoggerVector ()
virtual void InitializeThreadedLibraries ()
LightObject::Pointer InternalClone () const ITK_OVERRIDE
MaskedImageToImageFilter ()
std::string ThreadIDToString () const
virtual void VerifyMaskInformation () const
void WriteLogger (const std::string &str, const LoggerBase::PriorityLevelType level=LoggerBase::DEBUG) const
virtual ~MaskedImageToImageFilter ()
Protected Attributes
BasicShapeType m_BasicShape
MatrixPointer m_BasisMatrix
SphereTessellatorPointer m_SphereTessellator
bool m_Stretch =true
unsigned int m_TessellationOrder
Protected Attributes inherited from itk::MeshFromSphericalFunctionImageFilter< TInputImage, TOutputMesh >
NormalizationType m_Normalization
MatrixPointer m_Orientations
double m_Pow
bool m_RemoveNegativeValues
Protected Attributes inherited from itk::MeshFromImageImageFilter< TInputImage, TOutputMesh >
std::vector< int > m_BoxView = std::vector<int>(6,-1)
ColorSchemeType m_ColorScheme =UNKNOWN
std::vector< int > m_Flip = std::vector<int>(3, 0)
OutputMeshPolyDataPointer m_Mesh = OutputMeshPolyDataType::New()
double m_Scale =1.0
std::vector< int > m_SliceView = std::vector<int>(3,-1)
Protected Attributes inherited from itk::MaskedImageToImageFilter< TInputImage, TInputImage >
LoggerPointer m_Logger
LoggerVectorPointer m_LoggerVector
int m_LogLevel
MaskImagePointer m_MaskImage
int m_ThreadID
Private Member Functions
MeshFromContinuousSphericalFunctionImageFilter (const Self &)
void operator= (const Self &)
Additional Inherited Members
Static Public Attributes inherited from itk::MeshFromImageImageFilter< TInputImage, TOutputMesh >
static const unsigned int OrientationDimension = 3
Static Public Attributes inherited from itk::MaskedImageToImageFilter< TInputImage, TInputImage >
static const unsigned int InputImageDimension
static const unsigned int OutputImageDimension
Member Typedef Documentation
template<class TInputImage , class TOutputMesh = vtkPolyData> typedef SphereTessellatorType::BasicShapeType itk::MeshFromContinuousSphericalFunctionImageFilter< TInputImage, TOutputMesh >::BasicShapeType
Definition at line 81 of file itkMeshFromContinuousSphericalFunctionImageFilter.h.
template<class TInputImage , class TOutputMesh = vtkPolyData> typedef SmartPointer<const Self> itk::MeshFromContinuousSphericalFunctionImageFilter< TInputImage, TOutputMesh >::ConstPointer
Definition at line 49 of file itkMeshFromContinuousSphericalFunctionImageFilter.h.
template<class TInputImage , class TOutputMesh = vtkPolyData> typedef InputImageType::ConstPointer itk::MeshFromContinuousSphericalFunctionImageFilter< TInputImage, TOutputMesh >::InputImageConstPointer
Definition at line 60 of file itkMeshFromContinuousSphericalFunctionImageFilter.h.
template<class TInputImage , class TOutputMesh = vtkPolyData> typedef InputImageType::IndexType itk::MeshFromContinuousSphericalFunctionImageFilter< TInputImage, TOutputMesh >::InputImageIndexType
Definition at line 61 of file itkMeshFromContinuousSphericalFunctionImageFilter.h.
template<class TInputImage , class TOutputMesh = vtkPolyData> typedef InputImageType::PixelType itk::MeshFromContinuousSphericalFunctionImageFilter< TInputImage, TOutputMesh >::InputImagePixelType
Definition at line 65 of file itkMeshFromContinuousSphericalFunctionImageFilter.h.
template<class TInputImage , class TOutputMesh = vtkPolyData> typedef InputImageType::Pointer itk::MeshFromContinuousSphericalFunctionImageFilter< TInputImage, TOutputMesh >::InputImagePointer
Definition at line 59 of file itkMeshFromContinuousSphericalFunctionImageFilter.h.
template<class TInputImage , class TOutputMesh = vtkPolyData> typedef InputImageType::PointType itk::MeshFromContinuousSphericalFunctionImageFilter< TInputImage, TOutputMesh >::InputImagePointType
Definition at line 67 of file itkMeshFromContinuousSphericalFunctionImageFilter.h.
template<class TInputImage , class TOutputMesh = vtkPolyData> typedef InputImageType::RegionType itk::MeshFromContinuousSphericalFunctionImageFilter< TInputImage, TOutputMesh >::InputImageRegionType
Definition at line 66 of file itkMeshFromContinuousSphericalFunctionImageFilter.h.
template<class TInputImage , class TOutputMesh = vtkPolyData> typedef InputImageType::SizeType itk::MeshFromContinuousSphericalFunctionImageFilter< TInputImage, TOutputMesh >::InputImageSizeType
Definition at line 62 of file itkMeshFromContinuousSphericalFunctionImageFilter.h.
template<class TInputImage , class TOutputMesh = vtkPolyData> typedef InputImageType::SizeValueType itk::MeshFromContinuousSphericalFunctionImageFilter< TInputImage, TOutputMesh >::InputImageSizeValueType
Definition at line 63 of file itkMeshFromContinuousSphericalFunctionImageFilter.h.
template<class TInputImage , class TOutputMesh = vtkPolyData> typedef InputImageType::SpacingType itk::MeshFromContinuousSphericalFunctionImageFilter< TInputImage, TOutputMesh >::InputImageSpacingType
Definition at line 64 of file itkMeshFromContinuousSphericalFunctionImageFilter.h.
template<class TInputImage , class TOutputMesh = vtkPolyData> typedef TInputImage itk::MeshFromContinuousSphericalFunctionImageFilter< TInputImage, TOutputMesh >::InputImageType
Definition at line 55 of file itkMeshFromContinuousSphericalFunctionImageFilter.h.
template<class TInputImage , class TOutputMesh = vtkPolyData> typedef Superclass::MatrixPointer itk::MeshFromContinuousSphericalFunctionImageFilter< TInputImage, TOutputMesh >::MatrixPointer
Definition at line 85 of file itkMeshFromContinuousSphericalFunctionImageFilter.h.
template<class TInputImage , class TOutputMesh = vtkPolyData> typedef Superclass::MatrixType itk::MeshFromContinuousSphericalFunctionImageFilter< TInputImage, TOutputMesh >::MatrixType
Orientation Matrices
Definition at line 84 of file itkMeshFromContinuousSphericalFunctionImageFilter.h.
template<class TInputImage , class TOutputMesh = vtkPolyData> typedef Superclass::OutputMeshCellArrayType itk::MeshFromContinuousSphericalFunctionImageFilter< TInputImage, TOutputMesh >::OutputMeshCellArrayType
Definition at line 72 of file itkMeshFromContinuousSphericalFunctionImageFilter.h.
template<class TInputImage , class TOutputMesh = vtkPolyData> typedef Superclass::OutputMeshPointsType itk::MeshFromContinuousSphericalFunctionImageFilter< TInputImage, TOutputMesh >::OutputMeshPointsType
Definition at line 71 of file itkMeshFromContinuousSphericalFunctionImageFilter.h.
template<class TInputImage , class TOutputMesh = vtkPolyData> typedef Superclass::OutputMeshPolyDataPointer itk::MeshFromContinuousSphericalFunctionImageFilter< TInputImage, TOutputMesh >::OutputMeshPolyDataPointer
Definition at line 73 of file itkMeshFromContinuousSphericalFunctionImageFilter.h.
template<class TInputImage , class TOutputMesh = vtkPolyData> typedef TOutputMesh itk::MeshFromContinuousSphericalFunctionImageFilter< TInputImage, TOutputMesh >::OutputMeshPolyDataType
Definition at line 69 of file itkMeshFromContinuousSphericalFunctionImageFilter.h.
template<class TInputImage , class TOutputMesh = vtkPolyData> typedef Superclass::OutputMeshRGBType itk::MeshFromContinuousSphericalFunctionImageFilter< TInputImage, TOutputMesh >::OutputMeshRGBType
Definition at line 75 of file itkMeshFromContinuousSphericalFunctionImageFilter.h.
template<class TInputImage , class TOutputMesh = vtkPolyData> typedef Superclass::OutputMeshScalarType itk::MeshFromContinuousSphericalFunctionImageFilter< TInputImage, TOutputMesh >::OutputMeshScalarType
Definition at line 74 of file itkMeshFromContinuousSphericalFunctionImageFilter.h.
template<class TInputImage , class TOutputMesh = vtkPolyData> typedef SmartPointer<Self> itk::MeshFromContinuousSphericalFunctionImageFilter< TInputImage, TOutputMesh >::Pointer
Definition at line 48 of file itkMeshFromContinuousSphericalFunctionImageFilter.h.
template<class TInputImage , class TOutputMesh = vtkPolyData> typedef MeshFromContinuousSphericalFunctionImageFilter itk::MeshFromContinuousSphericalFunctionImageFilter< TInputImage, TOutputMesh >::Self
Standard class typedefs.
Definition at line 46 of file itkMeshFromContinuousSphericalFunctionImageFilter.h.
template<class TInputImage , class TOutputMesh = vtkPolyData> typedef SphereTessellatorType::Pointer itk::MeshFromContinuousSphericalFunctionImageFilter< TInputImage, TOutputMesh >::SphereTessellatorPointer
Definition at line 80 of file itkMeshFromContinuousSphericalFunctionImageFilter.h.
template<class TInputImage , class TOutputMesh = vtkPolyData> typedef SphereTessellator<double> itk::MeshFromContinuousSphericalFunctionImageFilter< TInputImage, TOutputMesh >::SphereTessellatorType
Set/Get the min-max normalization
Definition at line 79 of file itkMeshFromContinuousSphericalFunctionImageFilter.h.
template<class TInputImage , class TOutputMesh = vtkPolyData> typedef Superclass::STDVectorPointer itk::MeshFromContinuousSphericalFunctionImageFilter< TInputImage, TOutputMesh >::STDVectorPointer
Definition at line 89 of file itkMeshFromContinuousSphericalFunctionImageFilter.h.
template<class TInputImage , class TOutputMesh = vtkPolyData> typedef Superclass::STDVectorType itk::MeshFromContinuousSphericalFunctionImageFilter< TInputImage, TOutputMesh >::STDVectorType
Definition at line 88 of file itkMeshFromContinuousSphericalFunctionImageFilter.h.
template<class TInputImage , class TOutputMesh = vtkPolyData> typedef MeshFromSphericalFunctionImageFilter<TInputImage, TOutputMesh> itk::MeshFromContinuousSphericalFunctionImageFilter< TInputImage, TOutputMesh >::Superclass
Definition at line 47 of file itkMeshFromContinuousSphericalFunctionImageFilter.h.
template<class TInputImage , class TOutputMesh = vtkPolyData> typedef Superclass::VectorPointer itk::MeshFromContinuousSphericalFunctionImageFilter< TInputImage, TOutputMesh >::VectorPointer
Definition at line 87 of file itkMeshFromContinuousSphericalFunctionImageFilter.h.
template<class TInputImage , class TOutputMesh = vtkPolyData> typedef Superclass::VectorType itk::MeshFromContinuousSphericalFunctionImageFilter< TInputImage, TOutputMesh >::VectorType
Definition at line 86 of file itkMeshFromContinuousSphericalFunctionImageFilter.h.
Constructor & Destructor Documentation
template<class TInputImage , class TOutputMesh > itk::MeshFromContinuousSphericalFunctionImageFilter< TInputImage, TOutputMesh >::MeshFromContinuousSphericalFunctionImageFilter () protected
Default constructor.
Definition at line 39 of file itkMeshFromContinuousSphericalFunctionImageFilter.hxx.
References itk::MeshFromContinuousSphericalFunctionImageFilter< TInputImage, TOutputMesh >::PrintSelf().
template<class TInputImage , class TOutputMesh = vtkPolyData> itk::MeshFromContinuousSphericalFunctionImageFilter< TInputImage, TOutputMesh >::~MeshFromContinuousSphericalFunctionImageFilter () inline protected
Definition at line 116 of file itkMeshFromContinuousSphericalFunctionImageFilter.h.
template<class TInputImage , class TOutputMesh = vtkPolyData> itk::MeshFromContinuousSphericalFunctionImageFilter< TInputImage, TOutputMesh >::MeshFromContinuousSphericalFunctionImageFilter (const Self &) private
Member Function Documentation
template<class TInputImage , class TOutputMesh > void itk::MeshFromContinuousSphericalFunctionImageFilter< TInputImage, TOutputMesh >::BeforeThreadedGenerateData () protected
Definition at line 89 of file itkMeshFromContinuousSphericalFunctionImageFilter.hxx.
References utl::PrintUtlMatrix(), itk::MeshFromContinuousSphericalFunctionImageFilter< TInputImage, TOutputMesh >::ThreadedGenerateData(), utlGlobalException, utlShowPosition, and utl::VnlMatrixToUtlMatrix().
Referenced by itk::MeshFromContinuousSphericalFunctionImageFilter< TInputImage, TOutputMesh >::InternalClone().
template<class TInputImage , class TOutputMesh = vtkPolyData> virtual MatrixPointer itk::MeshFromContinuousSphericalFunctionImageFilter< TInputImage, TOutputMesh >::ComputeBasisMatrix () inline virtual
Reimplemented in itk::MeshFromDiscreteFiberODFImageFilter< TInputImage, TOutputMesh >, itk::MeshFromSphericalFunctionTessellatedSamplesImageFilter< TInputImage, TOutputMesh >, and itk::MeshFromSHCoefficientsImageFilter< TInputImage, TOutputMesh >.
Definition at line 103 of file itkMeshFromContinuousSphericalFunctionImageFilter.h.
template<class TInputImage , class TOutputMesh = vtkPolyData> virtual::itk::LightObject::Pointer itk::MeshFromContinuousSphericalFunctionImageFilter< TInputImage, TOutputMesh >::CreateAnother (void) const
template<class TInputImage , class TOutputMesh = vtkPolyData> virtual BasicShapeType itk::MeshFromContinuousSphericalFunctionImageFilter< TInputImage, TOutputMesh >::GetBasicShape () virtual
template<class TInputImage , class TOutputMesh = vtkPolyData> virtual MatrixPointer itk::MeshFromContinuousSphericalFunctionImageFilter< TInputImage, TOutputMesh >::GetBasisMatrix () virtual
template<class TInputImage , class TOutputMesh = vtkPolyData> virtual const char* itk::MeshFromContinuousSphericalFunctionImageFilter< TInputImage, TOutputMesh >::GetNameOfClass () const virtual
Run-time type information (and related methods)
Reimplemented from itk::MeshFromSphericalFunctionImageFilter< TInputImage, TOutputMesh >.
Reimplemented in itk::MeshFromDiscreteFiberODFImageFilter< TInputImage, TOutputMesh >, itk::MeshFromSphericalFunctionTessellatedSamplesImageFilter< TInputImage, TOutputMesh >, and itk::MeshFromSHCoefficientsImageFilter< TInputImage, TOutputMesh >.
template<class TInputImage , class TOutputMesh = vtkPolyData> virtual unsigned int itk::MeshFromContinuousSphericalFunctionImageFilter< TInputImage, TOutputMesh >::GetTessellationOrder () virtual
template<class TInputImage , class TOutputMesh > LightObject::Pointer itk::MeshFromContinuousSphericalFunctionImageFilter< TInputImage, TOutputMesh >::InternalClone () const protected
Definition at line 65 of file itkMeshFromContinuousSphericalFunctionImageFilter.hxx.
References itk::MeshFromContinuousSphericalFunctionImageFilter< TInputImage, TOutputMesh >::BeforeThreadedGenerateData().
Referenced by itk::MeshFromContinuousSphericalFunctionImageFilter< TInputImage, TOutputMesh >::PrintSelf().
template<class TInputImage , class TOutputMesh = vtkPolyData> itk::MeshFromContinuousSphericalFunctionImageFilter< TInputImage, TOutputMesh >::itkSetGetBooleanMacro (Stretch)
template<class TInputImage , class TOutputMesh = vtkPolyData> static Pointer itk::MeshFromContinuousSphericalFunctionImageFilter< TInputImage, TOutputMesh >::New () static
Method for creation through the object factory.
template<class TInputImage , class TOutputMesh = vtkPolyData> virtual VectorType itk::MeshFromContinuousSphericalFunctionImageFilter< TInputImage, TOutputMesh >::NormalizeUnitIntegral (const VectorType & x) const inline virtual
Reimplemented in itk::MeshFromSphericalFunctionTessellatedSamplesImageFilter< TInputImage, TOutputMesh >, and itk::MeshFromSHCoefficientsImageFilter< TInputImage, TOutputMesh >.
Definition at line 108 of file itkMeshFromContinuousSphericalFunctionImageFilter.h.
template<class TInputImage , class TOutputMesh = vtkPolyData> void itk::MeshFromContinuousSphericalFunctionImageFilter< TInputImage, TOutputMesh >::operator= (const Self &) private
template<class TInputImage , class TOutputMesh > void itk::MeshFromContinuousSphericalFunctionImageFilter< TInputImage, TOutputMesh >::PrintSelf (std::ostream & os, Indent indent) const protected virtual
Standard PrintSelf method.
Reimplemented from itk::MaskedImageToImageFilter< TInputImage, TInputImage >.
Reimplemented in itk::MeshFromDiscreteFiberODFImageFilter< TInputImage, TOutputMesh >, itk::MeshFromSphericalFunctionTessellatedSamplesImageFilter< TInputImage, TOutputMesh >, and itk::MeshFromSHCoefficientsImageFilter< TInputImage, TOutputMesh >.
Definition at line 53 of file itkMeshFromContinuousSphericalFunctionImageFilter.hxx.
References itk::MeshFromContinuousSphericalFunctionImageFilter< TInputImage, TOutputMesh >::InternalClone(), and utl::PrintUtlMatrix().
Referenced by itk::MeshFromContinuousSphericalFunctionImageFilter< TInputImage, TOutputMesh >::MeshFromContinuousSphericalFunctionImageFilter().
template<class TInputImage , class TOutputMesh > void itk::MeshFromContinuousSphericalFunctionImageFilter< TInputImage, TOutputMesh >::ScaleSamples (VectorType & b) const protected
Definition at line 365 of file itkMeshFromContinuousSphericalFunctionImageFilter.hxx.
Referenced by itk::MeshFromContinuousSphericalFunctionImageFilter< TInputImage, TOutputMesh >::ThreadedGenerateData().
template<class TInputImage , class TOutputMesh = vtkPolyData> virtual void itk::MeshFromContinuousSphericalFunctionImageFilter< TInputImage, TOutputMesh >::SetBasicShape (BasicShapeType _arg) virtual
template<class TInputImage , class TOutputMesh = vtkPolyData> virtual void itk::MeshFromContinuousSphericalFunctionImageFilter< TInputImage, TOutputMesh >::SetBasisMatrix (MatrixPointer _arg) virtual
template<class TInputImage , class TOutputMesh = vtkPolyData> virtual void itk::MeshFromContinuousSphericalFunctionImageFilter< TInputImage, TOutputMesh >::SetTessellationOrder (unsigned int _arg) virtual
template<class TInputImage , class TOutputMesh > void itk::MeshFromContinuousSphericalFunctionImageFilter< TInputImage, TOutputMesh >::ThreadedGenerateData (const typename TInputImage::RegionType & regionForThread, ThreadIdType threadId) protected
Generate data.
Definition at line 114 of file itkMeshFromContinuousSphericalFunctionImageFilter.hxx.
References utl::max(), utl::PrintUtlVector(), itk::MeshFromContinuousSphericalFunctionImageFilter< TInputImage, TOutputMesh >::ScaleSamples(), utlPrintVar, and utlShowPosition.
Referenced by itk::MeshFromContinuousSphericalFunctionImageFilter< TInputImage, TOutputMesh >::BeforeThreadedGenerateData().
template<class TInputImage , class TOutputMesh = vtkPolyData> void itk::MeshFromContinuousSphericalFunctionImageFilter< TInputImage, TOutputMesh >::VerifyInputParameters () const inline protected virtual
Reimplemented from itk::MeshFromImageImageFilter< TInputImage, TOutputMesh >.
Definition at line 119 of file itkMeshFromContinuousSphericalFunctionImageFilter.h.
References ITK_OVERRIDE, and utlSAGlobalException.
Member Data Documentation
template<class TInputImage , class TOutputMesh = vtkPolyData> BasicShapeType itk::MeshFromContinuousSphericalFunctionImageFilter< TInputImage, TOutputMesh >::m_BasicShape protected
Definition at line 138 of file itkMeshFromContinuousSphericalFunctionImageFilter.h.
template<class TInputImage , class TOutputMesh = vtkPolyData> MatrixPointer itk::MeshFromContinuousSphericalFunctionImageFilter< TInputImage, TOutputMesh >::m_BasisMatrix protected
Definition at line 141 of file itkMeshFromContinuousSphericalFunctionImageFilter.h.
template<class TInputImage , class TOutputMesh = vtkPolyData> SphereTessellatorPointer itk::MeshFromContinuousSphericalFunctionImageFilter< TInputImage, TOutputMesh >::m_SphereTessellator protected
Definition at line 137 of file itkMeshFromContinuousSphericalFunctionImageFilter.h.
template<class TInputImage , class TOutputMesh = vtkPolyData> bool itk::MeshFromContinuousSphericalFunctionImageFilter< TInputImage, TOutputMesh >::m_Stretch =true protected
If it is false, the mesh in each voxel is a sphere and the values of the spherical function are only for coloring.
Definition at line 144 of file itkMeshFromContinuousSphericalFunctionImageFilter.h.
template<class TInputImage , class TOutputMesh = vtkPolyData> unsigned int itk::MeshFromContinuousSphericalFunctionImageFilter< TInputImage, TOutputMesh >::m_TessellationOrder protected
Definition at line 139 of file itkMeshFromContinuousSphericalFunctionImageFilter.h.
The documentation for this class was generated from the following files:
Modules/Visualization/include/itkMeshFromContinuousSphericalFunctionImageFilter.h
Modules/Visualization/include/itkMeshFromContinuousSphericalFunctionImageFilter.hxx