DMRITool: vtk::vtkPolyDataViewer Class Reference
vtk::vtkPolyDataViewer Class Reference
Visualization
#include <vtkPolyDataViewer.h>
Detailed Description
helper class to visualize vtkPolyData.
Author
Jian Cheng (jian..nosp@m.chen.nosp@m.g.198.nosp@m.3@gm.nosp@m.ail.c.nosp@m.om)
Definition at line 89 of file vtkPolyDataViewer.h.
Public Member Functions
void Add (const vtkSmartPointer< vtkPolyData > &mesh, const double opacity=1.0)
void Add (const vtkSmartPointer< vtkPolyData > &mesh, const double opacity, const std::vector< double > &hueRange, bool useNormal, const std::vector< double > &scalarRange={-1.0,-1.0}, bool lighting=true)
void Add (const vtkSmartPointer< vtkLODActor > &actor)
void SavePNG (const std::string &pngfile)
void SetBackground (double r, double g, double b)
void Show ()
vtkGetMacro (UseNormal, bool)
vtkGetMacro (Zoom, double)
vtkGetMacro (Lighting, bool)
vtkGetVector2Macro (Angle, double)
vtkGetVector2Macro (WindowSize, int)
vtkSetMacro (UseNormal, bool)
vtkSetMacro (Zoom, double)
vtkSetMacro (Lighting, bool)
vtkSetVector2Macro (ScalarRange, double)
vtkSetVector2Macro (HueRange, double)
vtkSetVector2Macro (Angle, double)
vtkSetVector2Macro (WindowSize, int)
vtkTypeMacro (vtkPolyDataViewer, vtkObject)
Static Public Member Functions
static vtkPolyDataViewer * New ()
Protected Member Functions
void RenderWindowUpdate ()
void SetCamara ()
vtkPolyDataViewer ()
~vtkPolyDataViewer ()
Private Attributes
double Angle [2] ={0.0,0.0}
double HueRange [2] ={0.6667,0.0}
vtkSmartPointer< vtkRenderWindowInteractor > Interactor = vtkSmartPointer<vtkRenderWindowInteractor>::New()
bool Lighting =true
vtkSmartPointer< vtkRenderer > Renderer = vtkSmartPointer<vtkRenderer>::New()
vtkSmartPointer< vtkRenderWindow > RenderWindow = vtkSmartPointer<vtkRenderWindow>::New()
double ScalarRange [2] ={-1.0,-1.0}
bool UseNormal =true
int WindowSize [2] ={600,600}
double Zoom =1.0
Constructor & Destructor Documentation
vtk::vtkPolyDataViewer::vtkPolyDataViewer () inline protected
Definition at line 136 of file vtkPolyDataViewer.h.
vtk::vtkPolyDataViewer::~vtkPolyDataViewer () inline protected
Definition at line 137 of file vtkPolyDataViewer.h.
References RenderWindowUpdate(), and SetCamara().
Member Function Documentation
void vtk::vtkPolyDataViewer::Add (const vtkSmartPointer< vtkPolyData > & mesh, const double opacity = 1.0)
add mesh
Definition at line 20 of file vtkPolyDataViewer.hxx.
References HueRange, Lighting, ScalarRange, UseNormal, and vtk::vtkPolyDataToActor().
Referenced by Add().
void vtk::vtkPolyDataViewer::Add (const vtkSmartPointer< vtkPolyData > & mesh, const double opacity, const std::vector< double > & hueRange, bool useNormal, const std::vector< double > & scalarRange = {-1.0,-1.0}, bool lighting = true)
add mesh with hueRange, useNormal
Definition at line 26 of file vtkPolyDataViewer.hxx.
References Add(), ScalarRange, and vtk::vtkPolyDataToActor().
void vtk::vtkPolyDataViewer::Add (const vtkSmartPointer< vtkLODActor > & actor) inline
Definition at line 120 of file vtkPolyDataViewer.h.
References Renderer.
static vtkPolyDataViewer* vtk::vtkPolyDataViewer::New () static
void vtk::vtkPolyDataViewer::RenderWindowUpdate () protected
Definition at line 44 of file vtkPolyDataViewer.hxx.
References Interactor, Renderer, RenderWindow, SetCamara(), and WindowSize.
Referenced by SavePNG(), Show(), and ~vtkPolyDataViewer().
void vtk::vtkPolyDataViewer::SavePNG (const std::string & pngfile)
Definition at line 67 of file vtkPolyDataViewer.hxx.
References RenderWindow, and RenderWindowUpdate().
Referenced by SetBackground().
void vtk::vtkPolyDataViewer::SetBackground (double r, double g, double b) inline
Definition at line 125 of file vtkPolyDataViewer.h.
References Renderer, SavePNG(), and Show().
void vtk::vtkPolyDataViewer::SetCamara () protected
Definition at line 36 of file vtkPolyDataViewer.hxx.
References Angle, Renderer, and Zoom.
Referenced by RenderWindowUpdate(), and ~vtkPolyDataViewer().
void vtk::vtkPolyDataViewer::Show ()
Definition at line 60 of file vtkPolyDataViewer.hxx.
References Interactor, and RenderWindowUpdate().
Referenced by SetBackground().
vtk::vtkPolyDataViewer::vtkGetMacro (UseNormal , bool)
vtk::vtkPolyDataViewer::vtkGetMacro (Zoom , double)
vtk::vtkPolyDataViewer::vtkGetMacro (Lighting , bool)
vtk::vtkPolyDataViewer::vtkGetVector2Macro (Angle , double)
vtk::vtkPolyDataViewer::vtkGetVector2Macro (WindowSize , int)
vtk::vtkPolyDataViewer::vtkSetMacro (UseNormal , bool)
vtk::vtkPolyDataViewer::vtkSetMacro (Zoom , double)
vtk::vtkPolyDataViewer::vtkSetMacro (Lighting , bool)
vtk::vtkPolyDataViewer::vtkSetVector2Macro (ScalarRange , double)
vtk::vtkPolyDataViewer::vtkSetVector2Macro (HueRange , double)
vtk::vtkPolyDataViewer::vtkSetVector2Macro (Angle , double)
vtk::vtkPolyDataViewer::vtkSetVector2Macro (WindowSize , int)
vtk::vtkPolyDataViewer::vtkTypeMacro (vtkPolyDataViewer , vtkObject)
Member Data Documentation
double vtk::vtkPolyDataViewer::Angle[2] ={0.0,0.0} private
Definition at line 160 of file vtkPolyDataViewer.h.
Referenced by SetCamara().
double vtk::vtkPolyDataViewer::HueRange[2] ={0.6667,0.0} private
Definition at line 162 of file vtkPolyDataViewer.h.
Referenced by Add().
vtkSmartPointer<vtkRenderWindowInteractor> vtk::vtkPolyDataViewer::Interactor = vtkSmartPointer<vtkRenderWindowInteractor>::New() private
Definition at line 149 of file vtkPolyDataViewer.h.
Referenced by RenderWindowUpdate(), and Show().
bool vtk::vtkPolyDataViewer::Lighting =true private
Definition at line 156 of file vtkPolyDataViewer.h.
Referenced by Add().
vtkSmartPointer<vtkRenderer> vtk::vtkPolyDataViewer::Renderer = vtkSmartPointer<vtkRenderer>::New() private
Definition at line 146 of file vtkPolyDataViewer.h.
Referenced by Add(), RenderWindowUpdate(), SetBackground(), and SetCamara().
vtkSmartPointer<vtkRenderWindow> vtk::vtkPolyDataViewer::RenderWindow = vtkSmartPointer<vtkRenderWindow>::New() private
Definition at line 148 of file vtkPolyDataViewer.h.
Referenced by RenderWindowUpdate(), and SavePNG().
double vtk::vtkPolyDataViewer::ScalarRange[2] ={-1.0,-1.0} private
used to normalize the scalars for coloring
Definition at line 152 of file vtkPolyDataViewer.h.
Referenced by Add().
bool vtk::vtkPolyDataViewer::UseNormal =true private
Definition at line 154 of file vtkPolyDataViewer.h.
Referenced by Add().
int vtk::vtkPolyDataViewer::WindowSize[2] ={600,600} private
Definition at line 158 of file vtkPolyDataViewer.h.
Referenced by RenderWindowUpdate().
double vtk::vtkPolyDataViewer::Zoom =1.0 private
Definition at line 164 of file vtkPolyDataViewer.h.
Referenced by SetCamara().
The documentation for this class was generated from the following files:
Modules/Visualization/include/vtkPolyDataViewer.h
Modules/Visualization/include/vtkPolyDataViewer.hxx