DMRITool: itk::ImageToVTKImageDataFilter< TInputImage > Class Template Reference
itk::ImageToVTKImageDataFilter< TInputImage > Class Template Reference
#include <itkImageToVTKImageDataFilter.h>
Detailed Description
template<class TInputImage>
class itk::ImageToVTKImageDataFilter< TInputImage >
Converts an ITK image to VTK image data.
Definition at line 30 of file itkImageToVTKImageDataFilter.h.
Public Types
typedef SmartPointer< const Self > ConstPointer
typedef InputImageType::ConstPointer InputImageConstPointer
typedef ImageRegionConstIterator< InputImageType > InputImageIteratorType
typedef InputImageType::Pointer InputImagePointer
typedef TInputImage InputImageType
typedef InputImageType::IndexType InputIndexType
typedef InputImageType::PixelType InputPixelType
typedef InputImageType::PointType InputPointType
typedef InputImageType::RegionType InputRegionType
typedef InputImageType::SizeType InputSizeType
typedef InputImageType::SpacingType InputSpacingType
typedef vtkSmartPointer< vtkImageData > OutputImageType
typedef SmartPointer< Self > Pointer
typedef ImageToVTKImageDataFilter Self
typedef ProcessObject Superclass
Public Member Functions
virtual ::itk::LightObject::Pointer CreateAnother (void) const
const InputImageType * GetInput () const
virtual const char * GetNameOfClass () const
vtkImageData * GetOutput () const
virtual void SetInput (const InputImageType *image)
virtual void Update () ITK_OVERRIDE
Static Public Member Functions
static Pointer New ()
Static Public Attributes
static const unsigned int Dimension = TInputImage::ImageDimension
Protected Member Functions
virtual void GenerateData () ITK_OVERRIDE
ImageToVTKImageDataFilter ()
virtual ~ImageToVTKImageDataFilter ()
Private Member Functions
ImageToVTKImageDataFilter (const Self &)
void operator= (const Self &)
Private Attributes
OutputImageType m_Image
Member Typedef Documentation
template<class TInputImage> typedef SmartPointer<const Self> itk::ImageToVTKImageDataFilter< TInputImage >::ConstPointer
Definition at line 37 of file itkImageToVTKImageDataFilter.h.
template<class TInputImage> typedef InputImageType::ConstPointer itk::ImageToVTKImageDataFilter< TInputImage >::InputImageConstPointer
Definition at line 57 of file itkImageToVTKImageDataFilter.h.
template<class TInputImage> typedef ImageRegionConstIterator<InputImageType> itk::ImageToVTKImageDataFilter< TInputImage >::InputImageIteratorType
Definition at line 58 of file itkImageToVTKImageDataFilter.h.
template<class TInputImage> typedef InputImageType::Pointer itk::ImageToVTKImageDataFilter< TInputImage >::InputImagePointer
Definition at line 50 of file itkImageToVTKImageDataFilter.h.
template<class TInputImage> typedef TInputImage itk::ImageToVTKImageDataFilter< TInputImage >::InputImageType
Some typedefs.
Definition at line 49 of file itkImageToVTKImageDataFilter.h.
template<class TInputImage> typedef InputImageType::IndexType itk::ImageToVTKImageDataFilter< TInputImage >::InputIndexType
Definition at line 55 of file itkImageToVTKImageDataFilter.h.
template<class TInputImage> typedef InputImageType::PixelType itk::ImageToVTKImageDataFilter< TInputImage >::InputPixelType
Definition at line 56 of file itkImageToVTKImageDataFilter.h.
template<class TInputImage> typedef InputImageType::PointType itk::ImageToVTKImageDataFilter< TInputImage >::InputPointType
Definition at line 54 of file itkImageToVTKImageDataFilter.h.
template<class TInputImage> typedef InputImageType::RegionType itk::ImageToVTKImageDataFilter< TInputImage >::InputRegionType
Definition at line 51 of file itkImageToVTKImageDataFilter.h.
template<class TInputImage> typedef InputImageType::SizeType itk::ImageToVTKImageDataFilter< TInputImage >::InputSizeType
Definition at line 52 of file itkImageToVTKImageDataFilter.h.
template<class TInputImage> typedef InputImageType::SpacingType itk::ImageToVTKImageDataFilter< TInputImage >::InputSpacingType
Definition at line 53 of file itkImageToVTKImageDataFilter.h.
template<class TInputImage> typedef vtkSmartPointer<vtkImageData> itk::ImageToVTKImageDataFilter< TInputImage >::OutputImageType
Definition at line 60 of file itkImageToVTKImageDataFilter.h.
template<class TInputImage> typedef SmartPointer<Self> itk::ImageToVTKImageDataFilter< TInputImage >::Pointer
Definition at line 36 of file itkImageToVTKImageDataFilter.h.
template<class TInputImage> typedef ImageToVTKImageDataFilter itk::ImageToVTKImageDataFilter< TInputImage >::Self
Standard class typedefs.
Definition at line 34 of file itkImageToVTKImageDataFilter.h.
template<class TInputImage> typedef ProcessObject itk::ImageToVTKImageDataFilter< TInputImage >::Superclass
Definition at line 35 of file itkImageToVTKImageDataFilter.h.
Constructor & Destructor Documentation
template<class TInputImage > itk::ImageToVTKImageDataFilter< TInputImage >::ImageToVTKImageDataFilter () protected
Constructor
Definition at line 31 of file itkImageToVTKImageDataFilter.hxx.
References itk::ImageToVTKImageDataFilter< TInputImage >::GetOutput().
template<class TInputImage> virtual itk::ImageToVTKImageDataFilter< TInputImage >::~ImageToVTKImageDataFilter () inline protected virtual
Definition at line 78 of file itkImageToVTKImageDataFilter.h.
References ITK_OVERRIDE.
template<class TInputImage> itk::ImageToVTKImageDataFilter< TInputImage >::ImageToVTKImageDataFilter (const Self &) private
Member Function Documentation
template<class TInputImage> virtual::itk::LightObject::Pointer itk::ImageToVTKImageDataFilter< TInputImage >::CreateAnother (void) const
template<class TInputImage > void itk::ImageToVTKImageDataFilter< TInputImage >::GenerateData (void) protected virtual
Generate the data
Definition at line 77 of file itkImageToVTKImageDataFilter.hxx.
Referenced by itk::ImageToVTKImageDataFilter< TInputImage >::GetInput().
template<class TInputImage > const ImageToVTKImageDataFilter< TInputImage >::InputImageType * itk::ImageToVTKImageDataFilter< TInputImage >::GetInput (void) const
Get a vtkImage as output
Definition at line 66 of file itkImageToVTKImageDataFilter.hxx.
References itk::ImageToVTKImageDataFilter< TInputImage >::GenerateData().
Referenced by itk::ImageToVTKImageDataFilter< TInputImage >::SetInput().
template<class TInputImage> virtual const char* itk::ImageToVTKImageDataFilter< TInputImage >::GetNameOfClass () const virtual
Run-time type information (and related methods).
template<class TInputImage > vtkImageData * itk::ImageToVTKImageDataFilter< TInputImage >::GetOutput () const
Get the output in the form of a vtkImage. This call is delegated to the internal vtkImageImporter filter
Get a vtkImage as output
Definition at line 42 of file itkImageToVTKImageDataFilter.hxx.
References itk::ImageToVTKImageDataFilter< TInputImage >::SetInput().
Referenced by itk::ImageToVTKImageDataFilter< TInputImage >::ImageToVTKImageDataFilter().
template<class TInputImage> static Pointer itk::ImageToVTKImageDataFilter< TInputImage >::New () static
Method for creation through the object factory.
template<class TInputImage> void itk::ImageToVTKImageDataFilter< TInputImage >::operator= (const Self &) private
template<class TInputImage > void itk::ImageToVTKImageDataFilter< TInputImage >::SetInput (const InputImageType * image) virtual
Get a vtkImage as output
Definition at line 53 of file itkImageToVTKImageDataFilter.hxx.
References itk::ImageToVTKImageDataFilter< TInputImage >::GetInput().
Referenced by itk::ImageToVTKImageDataFilter< TInputImage >::GetOutput().
template<class TInputImage> virtual void itk::ImageToVTKImageDataFilter< TInputImage >::Update () inline virtual
Definition at line 71 of file itkImageToVTKImageDataFilter.h.
Member Data Documentation
template<class TInputImage> const unsigned int itk::ImageToVTKImageDataFilter< TInputImage >::Dimension = TInputImage::ImageDimension static
Image Dimension
Definition at line 46 of file itkImageToVTKImageDataFilter.h.
template<class TInputImage> OutputImageType itk::ImageToVTKImageDataFilter< TInputImage >::m_Image private
Definition at line 86 of file itkImageToVTKImageDataFilter.h.
The documentation for this class was generated from the following files:
Modules/Visualization/include/itkImageToVTKImageDataFilter.h
Modules/Visualization/include/itkImageToVTKImageDataFilter.hxx