DMRITool: itk::Functor::SHCoefficientsPower< TInput, TOutput > Class Template Reference
itk::Functor::SHCoefficientsPower< TInput, TOutput > Class Template Reference
#include <itkSHCoefficientsPowerImageFilter.h>
Detailed Description
template<class TInput, class TOutput>
class itk::Functor::SHCoefficientsPower< TInput, TOutput >
Definition at line 39 of file itkSHCoefficientsPowerImageFilter.h.
Public Types
typedef utl_shared_ptr< MatrixType > MatrixPointer
typedef utl::NDArray< double, 2 > MatrixType
typedef utl::NDArray< double, 1 > VectorType
Public Member Functions
bool operator!= (const SHCoefficientsPower &other) const
TOutput operator() (const TInput &shCoef)
bool operator== (const SHCoefficientsPower &other) const
SHCoefficientsPower ()
utlSetGetMacro (Power, double)
utlSetGetMacro (SHRank, int)
utlSetGetMacro (SHBasisMatrix, MatrixPointer)
utlSetGetMacro (SHBasisMatrixInverse, MatrixPointer)
~SHCoefficientsPower ()
Private Attributes
double m_Power
MatrixPointer m_SHBasisMatrix
MatrixPointer m_SHBasisMatrixInverse
int m_SHRank
Member Typedef Documentation
template<class TInput , class TOutput > typedef utl_shared_ptr<MatrixType> itk::Functor::SHCoefficientsPower< TInput, TOutput >::MatrixPointer
Definition at line 45 of file itkSHCoefficientsPowerImageFilter.h.
template<class TInput , class TOutput > typedef utl::NDArray<double, 2> itk::Functor::SHCoefficientsPower< TInput, TOutput >::MatrixType
Definition at line 44 of file itkSHCoefficientsPowerImageFilter.h.
template<class TInput , class TOutput > typedef utl::NDArray<double, 1> itk::Functor::SHCoefficientsPower< TInput, TOutput >::VectorType
Definition at line 43 of file itkSHCoefficientsPowerImageFilter.h.
Constructor & Destructor Documentation
template<class TInput , class TOutput > itk::Functor::SHCoefficientsPower< TInput, TOutput >::SHCoefficientsPower () inline
Definition at line 47 of file itkSHCoefficientsPowerImageFilter.h.
References itk::Functor::SHCoefficientsPower< TInput, TOutput >::m_Power, and itk::Functor::SHCoefficientsPower< TInput, TOutput >::m_SHRank.
template<class TInput , class TOutput > itk::Functor::SHCoefficientsPower< TInput, TOutput >::~SHCoefficientsPower () inline
Definition at line 54 of file itkSHCoefficientsPowerImageFilter.h.
Member Function Documentation
template<class TInput , class TOutput > bool itk::Functor::SHCoefficientsPower< TInput, TOutput >::operator!= (const SHCoefficientsPower< TInput, TOutput > & other) const inline
Definition at line 58 of file itkSHCoefficientsPowerImageFilter.h.
template<class TInput , class TOutput > TOutput itk::Functor::SHCoefficientsPower< TInput, TOutput >::operator() (const TInput & shCoef) inline
Definition at line 68 of file itkSHCoefficientsPowerImageFilter.h.
References utl::NDArrayBase< T, Dim >::Begin(), utl::DimToRankSH(), utl::NDArrayBase< T, Dim >::End(), itk::Functor::SHCoefficientsPower< TInput, TOutput >::m_Power, itk::Functor::SHCoefficientsPower< TInput, TOutput >::m_SHBasisMatrixInverse, itk::Functor::SHCoefficientsPower< TInput, TOutput >::m_SHRank, utl::PowerVector(), utl::RankToDimSH(), itk::Functor::SHCoefficientsPower< TInput, TOutput >::utlSetGetMacro(), and utl::VectorToVector().
template<class TInput , class TOutput > bool itk::Functor::SHCoefficientsPower< TInput, TOutput >::operator== (const SHCoefficientsPower< TInput, TOutput > & other) const inline
Definition at line 63 of file itkSHCoefficientsPowerImageFilter.h.
template<class TInput , class TOutput > itk::Functor::SHCoefficientsPower< TInput, TOutput >::utlSetGetMacro (Power , double)
Referenced by itk::Functor::SHCoefficientsPower< TInput, TOutput >::operator()().
template<class TInput , class TOutput > itk::Functor::SHCoefficientsPower< TInput, TOutput >::utlSetGetMacro (SHRank , int)
template<class TInput , class TOutput > itk::Functor::SHCoefficientsPower< TInput, TOutput >::utlSetGetMacro (SHBasisMatrix , MatrixPointer)
template<class TInput , class TOutput > itk::Functor::SHCoefficientsPower< TInput, TOutput >::utlSetGetMacro (SHBasisMatrixInverse , MatrixPointer)
Member Data Documentation
template<class TInput , class TOutput > double itk::Functor::SHCoefficientsPower< TInput, TOutput >::m_Power private
power of spherical function
Definition at line 127 of file itkSHCoefficientsPowerImageFilter.h.
Referenced by itk::Functor::SHCoefficientsPower< TInput, TOutput >::operator()(), and itk::Functor::SHCoefficientsPower< TInput, TOutput >::SHCoefficientsPower().
template<class TInput , class TOutput > MatrixPointer itk::Functor::SHCoefficientsPower< TInput, TOutput >::m_SHBasisMatrix private
Definition at line 123 of file itkSHCoefficientsPowerImageFilter.h.
template<class TInput , class TOutput > MatrixPointer itk::Functor::SHCoefficientsPower< TInput, TOutput >::m_SHBasisMatrixInverse private
Definition at line 124 of file itkSHCoefficientsPowerImageFilter.h.
Referenced by itk::Functor::SHCoefficientsPower< TInput, TOutput >::operator()().
template<class TInput , class TOutput > int itk::Functor::SHCoefficientsPower< TInput, TOutput >::m_SHRank private
it is used when m_Power is not 2 or 1
Definition at line 130 of file itkSHCoefficientsPowerImageFilter.h.
Referenced by itk::Functor::SHCoefficientsPower< TInput, TOutput >::operator()(), and itk::Functor::SHCoefficientsPower< TInput, TOutput >::SHCoefficientsPower().
The documentation for this class was generated from the following file:
Modules/DiffusionModels/include/itkSHCoefficientsPowerImageFilter.h