DMRITool: spams::FISTA::MultiLogLoss< T > Class Template Reference
spams::FISTA::MultiLogLoss< T > Class Template Reference
#include <fista.h>
Detailed Description
template<typename T>
class spams::FISTA::MultiLogLoss< T >
Definition at line 689 of file fista.h.
Public Member Functions
T eval (const Matrix< T > &W) const
virtual T fenchel (const Matrix< T > &input) const
void grad (const Matrix< T > &W, Matrix< T > &grad) const
void init (const Vector< T > &y)
MultiLogLoss (const AbstractMatrixB< T > &X)
virtual void var_fenchel (const Matrix< T > &W, Matrix< T > &grad1, Matrix< T > &grad2, const bool intercept) const
virtual ~MultiLogLoss ()
Public Member Functions inherited from spams::FISTA::Loss< T, Matrix< T > >
virtual bool is_fenchel () const
Loss ()
virtual bool test_backtracking (const Matrix< T > &y, const Matrix< T > &grad, const Matrix< T > &prox, const T L) const
virtual ~Loss ()
Private Member Functions
MultiLogLoss (const MultiLogLoss< T > &dict)
MultiLogLoss< T > & operator= (const MultiLogLoss< T > &dict)
Private Attributes
const AbstractMatrixB< T > * _X
Vector< int > _y
Constructor & Destructor Documentation
template<typename T> spams::FISTA::MultiLogLoss< T >::MultiLogLoss (const AbstractMatrixB< T > & X) inline
Definition at line 691 of file fista.h.
template<typename T> virtual spams::FISTA::MultiLogLoss< T >::~MultiLogLoss () inline virtual
Definition at line 693 of file fista.h.
template<typename T> spams::FISTA::MultiLogLoss< T >::MultiLogLoss (const MultiLogLoss< T > & dict) explicit private
Member Function Documentation
template<typename T> T spams::FISTA::MultiLogLoss< T >::eval (const Matrix< T > & W) const inline virtual
Implements spams::FISTA::Loss< T, Matrix< T > >.
Definition at line 700 of file fista.h.
References spams::Matrix< T >::multSwitch(), spams::Matrix< T >::n(), spams::Matrix< T >::refCol(), and spams::Vector< T >::softmax().
template<typename T> virtual T spams::FISTA::MultiLogLoss< T >::fenchel (const Matrix< T > & input) const inline virtual
Implements spams::FISTA::Loss< T, Matrix< T > >.
Definition at line 739 of file fista.h.
References spams::Matrix< T >::m(), spams::Matrix< T >::n(), spams::Matrix< T >::refCol(), and spams::xlogx().
template<typename T> void spams::FISTA::MultiLogLoss< T >::grad (const Matrix< T > & W, Matrix< T > & grad) const inline virtual
Implements spams::FISTA::Loss< T, Matrix< T > >.
Definition at line 712 of file fista.h.
References spams::Vector< T >::add(), spams::Vector< T >::exp(), spams::Vector< T >::fmax(), spams::Matrix< T >::m(), spams::Matrix< T >::multSwitch(), spams::Matrix< T >::n(), spams::Vector< T >::n(), spams::Matrix< T >::refCol(), spams::Matrix< T >::resize(), spams::Matrix< T >::scal(), spams::Vector< T >::scal(), spams::Vector< T >::setZeros(), and spams::Vector< T >::sum().
template<typename T> void spams::FISTA::MultiLogLoss< T >::init (const Vector< T > & y) inline virtual
Implements spams::FISTA::Loss< T, Matrix< T > >.
Definition at line 695 of file fista.h.
References spams::Vector< T >::n().
template<typename T> MultiLogLoss<T>& spams::FISTA::MultiLogLoss< T >::operator= (const MultiLogLoss< T > & dict) private
template<typename T> virtual void spams::FISTA::MultiLogLoss< T >::var_fenchel (const Matrix< T > & W, Matrix< T > & grad1, Matrix< T > & grad2, const bool intercept) const inline virtual
Implements spams::FISTA::Loss< T, Matrix< T > >.
Definition at line 755 of file fista.h.
References spams::Vector< T >::add(), spams::Vector< T >::exp(), spams::Matrix< T >::extractRow(), spams::Vector< T >::fmax(), spams::Matrix< T >::m(), spams::Matrix< T >::n(), spams::Vector< T >::n(), spams::Vector< T >::project_sft(), spams::Matrix< T >::refCol(), spams::Matrix< T >::resize(), spams::Matrix< T >::scal(), spams::Vector< T >::scal(), spams::Matrix< T >::setRow(), spams::Vector< T >::setZeros(), and spams::Vector< T >::sum().
Member Data Documentation
template<typename T> const AbstractMatrixB<T>* spams::FISTA::MultiLogLoss< T >::_X private
Definition at line 793 of file fista.h.
template<typename T> Vector<int> spams::FISTA::MultiLogLoss< T >::_y private
Definition at line 794 of file fista.h.
The documentation for this class was generated from the following file:
ThirdParty/Spams/include/fista.h