DMRITool: itk::ComposeVectorImageFilter< TInputImage, TOutputImage > Class Template Reference
itk::ComposeVectorImageFilter< TInputImage, TOutputImage > Class Template Reference
#include <itkComposeVectorImageFilter.h>
Detailed Description
template<typename TInputImage = VectorImage<double,3>, typename TOutputImage = VectorImage<typename TInputImage::PixelType, TInputImage::ImageDimension>>
class itk::ComposeVectorImageFilter< TInputImage, TOutputImage >
ComposeVectorImageFilter combine several vector images into a vector image.
Inputs and Usage
filter->SetInput(0, image0);
filter->SetInput(1, image1);
...
filter->Update();
itk::VectorImage< PixelType, dimension >::Pointer = filter->GetOutput();
All input images are expected to have the same template parameters and have the same size and origin.
See also
VectorImage
VectorIndexSelectionCastImageFilter
Wiki Examples:
All Examples
Create a vector image from a collection of scalar images
Compose a vector image (with 3 components) from three scalar images
Convert a real image and an imaginary image to a complex image
Definition at line 50 of file itkComposeVectorImageFilter.h.
Public Types
typedef SmartPointer< const Self > ConstPointer
typedef TInputImage InputImageType
typedef InputImageType::PixelType InputPixelType
typedef TOutputImage OutputImageType
typedef OutputImageType::PixelType OutputPixelType
typedef SmartPointer< Self > Pointer
typedef InputImageType::RegionType RegionType
typedef ComposeVectorImageFilter Self
typedef ImageToImageFilter< TInputImage, TOutputImage > Superclass
Public Member Functions
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual const char * GetNameOfClass () const
void SetInput1 (const InputImageType *image1)
void SetInput2 (const InputImageType *image2)
void SetInput3 (const InputImageType *image3)
Static Public Member Functions
static Pointer New ()
Static Public Attributes
static const unsigned int Dimension = TInputImage::ImageDimension
Protected Member Functions
virtual void BeforeThreadedGenerateData () ITK_OVERRIDE
ComposeVectorImageFilter ()
virtual void GenerateOutputInformation (void) ITK_OVERRIDE
virtual void ThreadedGenerateData (const RegionType &outputRegionForThread, ThreadIdType) ITK_OVERRIDE
Private Types
typedef std::vector< InputIteratorType > InputIteratorContainerType
typedef ImageRegionConstIterator< InputImageType > InputIteratorType
Private Member Functions
ComposeVectorImageFilter (const Self &)
template<typename TPixel >
void ComputeOutputPixel (TPixel &pix, InputIteratorContainerType &inputItContainer)
void operator= (const Self &)
Member Typedef Documentation
template<typename TInputImage = VectorImage<double,3>, typename TOutputImage = VectorImage<typename TInputImage::PixelType, TInputImage::ImageDimension>> typedef SmartPointer< const Self > itk::ComposeVectorImageFilter< TInputImage, TOutputImage >::ConstPointer
Definition at line 57 of file itkComposeVectorImageFilter.h.
template<typename TInputImage = VectorImage<double,3>, typename TOutputImage = VectorImage<typename TInputImage::PixelType, TInputImage::ImageDimension>> typedef TInputImage itk::ComposeVectorImageFilter< TInputImage, TOutputImage >::InputImageType
Definition at line 64 of file itkComposeVectorImageFilter.h.
template<typename TInputImage = VectorImage<double,3>, typename TOutputImage = VectorImage<typename TInputImage::PixelType, TInputImage::ImageDimension>> typedef std::vector< InputIteratorType > itk::ComposeVectorImageFilter< TInputImage, TOutputImage >::InputIteratorContainerType private
Definition at line 92 of file itkComposeVectorImageFilter.h.
template<typename TInputImage = VectorImage<double,3>, typename TOutputImage = VectorImage<typename TInputImage::PixelType, TInputImage::ImageDimension>> typedef ImageRegionConstIterator< InputImageType > itk::ComposeVectorImageFilter< TInputImage, TOutputImage >::InputIteratorType private
Definition at line 91 of file itkComposeVectorImageFilter.h.
template<typename TInputImage = VectorImage<double,3>, typename TOutputImage = VectorImage<typename TInputImage::PixelType, TInputImage::ImageDimension>> typedef InputImageType::PixelType itk::ComposeVectorImageFilter< TInputImage, TOutputImage >::InputPixelType
Definition at line 66 of file itkComposeVectorImageFilter.h.
template<typename TInputImage = VectorImage<double,3>, typename TOutputImage = VectorImage<typename TInputImage::PixelType, TInputImage::ImageDimension>> typedef TOutputImage itk::ComposeVectorImageFilter< TInputImage, TOutputImage >::OutputImageType
Definition at line 65 of file itkComposeVectorImageFilter.h.
template<typename TInputImage = VectorImage<double,3>, typename TOutputImage = VectorImage<typename TInputImage::PixelType, TInputImage::ImageDimension>> typedef OutputImageType::PixelType itk::ComposeVectorImageFilter< TInputImage, TOutputImage >::OutputPixelType
Definition at line 67 of file itkComposeVectorImageFilter.h.
template<typename TInputImage = VectorImage<double,3>, typename TOutputImage = VectorImage<typename TInputImage::PixelType, TInputImage::ImageDimension>> typedef SmartPointer< Self > itk::ComposeVectorImageFilter< TInputImage, TOutputImage >::Pointer
Definition at line 56 of file itkComposeVectorImageFilter.h.
template<typename TInputImage = VectorImage<double,3>, typename TOutputImage = VectorImage<typename TInputImage::PixelType, TInputImage::ImageDimension>> typedef InputImageType::RegionType itk::ComposeVectorImageFilter< TInputImage, TOutputImage >::RegionType
Definition at line 68 of file itkComposeVectorImageFilter.h.
template<typename TInputImage = VectorImage<double,3>, typename TOutputImage = VectorImage<typename TInputImage::PixelType, TInputImage::ImageDimension>> typedef ComposeVectorImageFilter itk::ComposeVectorImageFilter< TInputImage, TOutputImage >::Self
Definition at line 55 of file itkComposeVectorImageFilter.h.
template<typename TInputImage = VectorImage<double,3>, typename TOutputImage = VectorImage<typename TInputImage::PixelType, TInputImage::ImageDimension>> typedef ImageToImageFilter< TInputImage, TOutputImage > itk::ComposeVectorImageFilter< TInputImage, TOutputImage >::Superclass
Definition at line 58 of file itkComposeVectorImageFilter.h.
Constructor & Destructor Documentation
template<typename TInputImage , typename TOutputImage > itk::ComposeVectorImageFilter< TInputImage, TOutputImage >::ComposeVectorImageFilter () protected
Definition at line 23 of file itkComposeVectorImageFilter.hxx.
References utl::max(), and itk::ComposeVectorImageFilter< TInputImage, TOutputImage >::SetInput1().
template<typename TInputImage = VectorImage<double,3>, typename TOutputImage = VectorImage<typename TInputImage::PixelType, TInputImage::ImageDimension>> itk::ComposeVectorImageFilter< TInputImage, TOutputImage >::ComposeVectorImageFilter (const Self &) private
Member Function Documentation
template<typename TInputImage , typename TOutputImage > void itk::ComposeVectorImageFilter< TInputImage, TOutputImage >::BeforeThreadedGenerateData () protected virtual
Definition at line 86 of file itkComposeVectorImageFilter.hxx.
References itk::ComposeVectorImageFilter< TInputImage, TOutputImage >::ThreadedGenerateData().
Referenced by itk::ComposeVectorImageFilter< TInputImage, TOutputImage >::GenerateOutputInformation().
template<typename TInputImage = VectorImage<double,3>, typename TOutputImage = VectorImage<typename TInputImage::PixelType, TInputImage::ImageDimension>> template<typename TPixel > void itk::ComposeVectorImageFilter< TInputImage, TOutputImage >::ComputeOutputPixel (TPixel & pix, InputIteratorContainerType & inputItContainer) inline private
Definition at line 102 of file itkComposeVectorImageFilter.h.
template<typename TInputImage = VectorImage<double,3>, typename TOutputImage = VectorImage<typename TInputImage::PixelType, TInputImage::ImageDimension>> virtual::itk::LightObject::Pointer itk::ComposeVectorImageFilter< TInputImage, TOutputImage >::CreateAnother (void) const
template<typename TInputImage , typename TOutputImage > void itk::ComposeVectorImageFilter< TInputImage, TOutputImage >::GenerateOutputInformation (void) protected virtual
Definition at line 65 of file itkComposeVectorImageFilter.hxx.
References itk::ComposeVectorImageFilter< TInputImage, TOutputImage >::BeforeThreadedGenerateData().
Referenced by itk::ComposeVectorImageFilter< TInputImage, TOutputImage >::SetInput3().
template<typename TInputImage = VectorImage<double,3>, typename TOutputImage = VectorImage<typename TInputImage::PixelType, TInputImage::ImageDimension>> virtual const char* itk::ComposeVectorImageFilter< TInputImage, TOutputImage >::GetNameOfClass () const virtual
template<typename TInputImage = VectorImage<double,3>, typename TOutputImage = VectorImage<typename TInputImage::PixelType, TInputImage::ImageDimension>> static Pointer itk::ComposeVectorImageFilter< TInputImage, TOutputImage >::New () static
template<typename TInputImage = VectorImage<double,3>, typename TOutputImage = VectorImage<typename TInputImage::PixelType, TInputImage::ImageDimension>> void itk::ComposeVectorImageFilter< TInputImage, TOutputImage >::operator= (const Self &) private
template<typename TInputImage , typename TOutputImage > void itk::ComposeVectorImageFilter< TInputImage, TOutputImage >::SetInput1 (const InputImageType * image1)
Definition at line 35 of file itkComposeVectorImageFilter.hxx.
References itk::ComposeVectorImageFilter< TInputImage, TOutputImage >::SetInput2().
Referenced by itk::ComposeVectorImageFilter< TInputImage, TOutputImage >::ComposeVectorImageFilter().
template<typename TInputImage , typename TOutputImage > void itk::ComposeVectorImageFilter< TInputImage, TOutputImage >::SetInput2 (const InputImageType * image2)
Definition at line 45 of file itkComposeVectorImageFilter.hxx.
References itk::ComposeVectorImageFilter< TInputImage, TOutputImage >::SetInput3().
Referenced by itk::ComposeVectorImageFilter< TInputImage, TOutputImage >::SetInput1().
template<typename TInputImage , typename TOutputImage > void itk::ComposeVectorImageFilter< TInputImage, TOutputImage >::SetInput3 (const InputImageType * image3)
Definition at line 55 of file itkComposeVectorImageFilter.hxx.
References itk::ComposeVectorImageFilter< TInputImage, TOutputImage >::GenerateOutputInformation().
Referenced by itk::ComposeVectorImageFilter< TInputImage, TOutputImage >::SetInput2().
template<typename TInputImage , typename TOutputImage > void itk::ComposeVectorImageFilter< TInputImage, TOutputImage >::ThreadedGenerateData (const RegionType & outputRegionForThread, ThreadIdType threadId) protected virtual
Definition at line 116 of file itkComposeVectorImageFilter.hxx.
Referenced by itk::ComposeVectorImageFilter< TInputImage, TOutputImage >::BeforeThreadedGenerateData().
Member Data Documentation
template<typename TInputImage = VectorImage<double,3>, typename TOutputImage = VectorImage<typename TInputImage::PixelType, TInputImage::ImageDimension>> const unsigned int itk::ComposeVectorImageFilter< TInputImage, TOutputImage >::Dimension = TInputImage::ImageDimension static
Definition at line 62 of file itkComposeVectorImageFilter.h.
The documentation for this class was generated from the following files:
Modules/Common/include/itkComposeVectorImageFilter.h
Modules/Common/include/itkComposeVectorImageFilter.hxx