DMRITool: itk::AddNoiseToDWIImageFilter< TInputImage, TB0Image, TMaskImage > Class Template Reference
itk::AddNoiseToDWIImageFilter< TInputImage, TB0Image, TMaskImage > Class Template Reference
DWIProcessing
#include <itkAddNoiseToDWIImageFilter.h>
Detailed Description
template<typename TInputImage, typename TB0Image = Image<double,3>, typename TMaskImage = Image<double,3>>
class itk::AddNoiseToDWIImageFilter< TInputImage, TB0Image, TMaskImage >
add noise to DWI data
Author
Jian Cheng (JC), jian..nosp@m.chen.nosp@m.g.198.nosp@m.3@gm.nosp@m.ail.c.nosp@m.om
Definition at line 35 of file itkAddNoiseToDWIImageFilter.h.
Public Types
typedef TB0Image B0ImageType
typedef Superclass::InputImageType InputImageType
typedef TMaskImage MaskImageType
enum NoiseType {
GAUSSIAN =0,
RICIAN
}
typedef InputImageType::PixelType PixelType
typedef SmartPointer< Self > Pointer
typedef AddNoiseToDWIImageFilter Self
typedef ImageToImageFilter< TInputImage, TInputImage > Superclass
Public Member Functions
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual const B0ImageType * GetB0Image () const
virtual const MaskImageType * GetMaskImage () const
virtual const char * GetNameOfClass () const
virtual NoiseType GetNoisetype ()
virtual double GetSigma ()
virtual void SetB0Image (const B0ImageType *input)
virtual void SetMaskImage (const MaskImageType *input)
virtual void SetNoisetype (NoiseType _arg)
virtual void SetSigma (double _arg)
Static Public Member Functions
static Pointer New ()
Protected Member Functions
AddNoiseToDWIImageFilter ()
virtual void GenerateData () ITK_OVERRIDE
void PrintSelf (std::ostream &os, Indent indent) const ITK_OVERRIDE
virtual ~AddNoiseToDWIImageFilter ()
Private Member Functions
AddNoiseToDWIImageFilter (const Self &)
void operator= (const Self &)
Private Attributes
NoiseType m_Noisetype
double m_Sigma
Member Typedef Documentation
template<typename TInputImage , typename TB0Image = Image<double,3>, typename TMaskImage = Image<double,3>> typedef TB0Image itk::AddNoiseToDWIImageFilter< TInputImage, TB0Image, TMaskImage >::B0ImageType
Definition at line 52 of file itkAddNoiseToDWIImageFilter.h.
template<typename TInputImage , typename TB0Image = Image<double,3>, typename TMaskImage = Image<double,3>> typedef Superclass::InputImageType itk::AddNoiseToDWIImageFilter< TInputImage, TB0Image, TMaskImage >::InputImageType
Definition at line 48 of file itkAddNoiseToDWIImageFilter.h.
template<typename TInputImage , typename TB0Image = Image<double,3>, typename TMaskImage = Image<double,3>> typedef TMaskImage itk::AddNoiseToDWIImageFilter< TInputImage, TB0Image, TMaskImage >::MaskImageType
Definition at line 53 of file itkAddNoiseToDWIImageFilter.h.
template<typename TInputImage , typename TB0Image = Image<double,3>, typename TMaskImage = Image<double,3>> typedef InputImageType::PixelType itk::AddNoiseToDWIImageFilter< TInputImage, TB0Image, TMaskImage >::PixelType
Definition at line 55 of file itkAddNoiseToDWIImageFilter.h.
template<typename TInputImage , typename TB0Image = Image<double,3>, typename TMaskImage = Image<double,3>> typedef SmartPointer< Self > itk::AddNoiseToDWIImageFilter< TInputImage, TB0Image, TMaskImage >::Pointer
Definition at line 42 of file itkAddNoiseToDWIImageFilter.h.
template<typename TInputImage , typename TB0Image = Image<double,3>, typename TMaskImage = Image<double,3>> typedef AddNoiseToDWIImageFilter itk::AddNoiseToDWIImageFilter< TInputImage, TB0Image, TMaskImage >::Self
Standard class typedefs.
Definition at line 40 of file itkAddNoiseToDWIImageFilter.h.
template<typename TInputImage , typename TB0Image = Image<double,3>, typename TMaskImage = Image<double,3>> typedef ImageToImageFilter< TInputImage, TInputImage > itk::AddNoiseToDWIImageFilter< TInputImage, TB0Image, TMaskImage >::Superclass
Definition at line 41 of file itkAddNoiseToDWIImageFilter.h.
Member Enumeration Documentation
template<typename TInputImage , typename TB0Image = Image<double,3>, typename TMaskImage = Image<double,3>> enum itk::AddNoiseToDWIImageFilter::NoiseType
Enumerator
GAUSSIAN
RICIAN
Definition at line 57 of file itkAddNoiseToDWIImageFilter.h.
Constructor & Destructor Documentation
template<class TInputImage , class TB0Image , class TMaskImage > itk::AddNoiseToDWIImageFilter< TInputImage, TB0Image, TMaskImage >::AddNoiseToDWIImageFilter () protected
Definition at line 31 of file itkAddNoiseToDWIImageFilter.hxx.
References itk::AddNoiseToDWIImageFilter< TInputImage, TB0Image, TMaskImage >::PrintSelf().
Referenced by itk::AddNoiseToDWIImageFilter< TInputImage, TB0Image, TMaskImage >::~AddNoiseToDWIImageFilter().
template<typename TInputImage , typename TB0Image = Image<double,3>, typename TMaskImage = Image<double,3>> virtual itk::AddNoiseToDWIImageFilter< TInputImage, TB0Image, TMaskImage >::~AddNoiseToDWIImageFilter () inline protected virtual
Definition at line 77 of file itkAddNoiseToDWIImageFilter.h.
References itk::AddNoiseToDWIImageFilter< TInputImage, TB0Image, TMaskImage >::AddNoiseToDWIImageFilter(), itk::AddNoiseToDWIImageFilter< TInputImage, TB0Image, TMaskImage >::GenerateData(), ITK_OVERRIDE, itk::AddNoiseToDWIImageFilter< TInputImage, TB0Image, TMaskImage >::operator=(), and itk::AddNoiseToDWIImageFilter< TInputImage, TB0Image, TMaskImage >::PrintSelf().
template<typename TInputImage , typename TB0Image = Image<double,3>, typename TMaskImage = Image<double,3>> itk::AddNoiseToDWIImageFilter< TInputImage, TB0Image, TMaskImage >::AddNoiseToDWIImageFilter (const Self &) private
Member Function Documentation
template<typename TInputImage , typename TB0Image = Image<double,3>, typename TMaskImage = Image<double,3>> virtual::itk::LightObject::Pointer itk::AddNoiseToDWIImageFilter< TInputImage, TB0Image, TMaskImage >::CreateAnother (void) const
template<class TInputImage , class TB0Image , class TMaskImage > void itk::AddNoiseToDWIImageFilter< TInputImage, TB0Image, TMaskImage >::GenerateData (void) protected virtual
Does the real work.
Definition at line 55 of file itkAddNoiseToDWIImageFilter.hxx.
References utlException.
Referenced by itk::AddNoiseToDWIImageFilter< TInputImage, TB0Image, TMaskImage >::PrintSelf(), and itk::AddNoiseToDWIImageFilter< TInputImage, TB0Image, TMaskImage >::~AddNoiseToDWIImageFilter().
template<typename TInputImage , typename TB0Image = Image<double,3>, typename TMaskImage = Image<double,3>> virtual const B0ImageType* itk::AddNoiseToDWIImageFilter< TInputImage, TB0Image, TMaskImage >::GetB0Image () const virtual
template<typename TInputImage , typename TB0Image = Image<double,3>, typename TMaskImage = Image<double,3>> virtual const MaskImageType* itk::AddNoiseToDWIImageFilter< TInputImage, TB0Image, TMaskImage >::GetMaskImage () const virtual
template<typename TInputImage , typename TB0Image = Image<double,3>, typename TMaskImage = Image<double,3>> virtual const char* itk::AddNoiseToDWIImageFilter< TInputImage, TB0Image, TMaskImage >::GetNameOfClass () const virtual
Run-time type information (and related methods).
template<typename TInputImage , typename TB0Image = Image<double,3>, typename TMaskImage = Image<double,3>> virtual NoiseType itk::AddNoiseToDWIImageFilter< TInputImage, TB0Image, TMaskImage >::GetNoisetype () virtual
template<typename TInputImage , typename TB0Image = Image<double,3>, typename TMaskImage = Image<double,3>> virtual double itk::AddNoiseToDWIImageFilter< TInputImage, TB0Image, TMaskImage >::GetSigma () virtual
template<typename TInputImage , typename TB0Image = Image<double,3>, typename TMaskImage = Image<double,3>> static Pointer itk::AddNoiseToDWIImageFilter< TInputImage, TB0Image, TMaskImage >::New () static
Method for creation through the object factory.
template<typename TInputImage , typename TB0Image = Image<double,3>, typename TMaskImage = Image<double,3>> void itk::AddNoiseToDWIImageFilter< TInputImage, TB0Image, TMaskImage >::operator= (const Self &) private
Referenced by itk::AddNoiseToDWIImageFilter< TInputImage, TB0Image, TMaskImage >::~AddNoiseToDWIImageFilter().
template<class TInputImage , class TB0Image , class TMaskImage > void itk::AddNoiseToDWIImageFilter< TInputImage, TB0Image, TMaskImage >::PrintSelf (std::ostream & os, Indent indent) const protected
Definition at line 42 of file itkAddNoiseToDWIImageFilter.hxx.
References itk::AddNoiseToDWIImageFilter< TInputImage, TB0Image, TMaskImage >::GenerateData(), and PrintVar1.
Referenced by itk::AddNoiseToDWIImageFilter< TInputImage, TB0Image, TMaskImage >::AddNoiseToDWIImageFilter(), and itk::AddNoiseToDWIImageFilter< TInputImage, TB0Image, TMaskImage >::~AddNoiseToDWIImageFilter().
template<typename TInputImage , typename TB0Image = Image<double,3>, typename TMaskImage = Image<double,3>> virtual void itk::AddNoiseToDWIImageFilter< TInputImage, TB0Image, TMaskImage >::SetB0Image (const B0ImageType * input) virtual
template<typename TInputImage , typename TB0Image = Image<double,3>, typename TMaskImage = Image<double,3>> virtual void itk::AddNoiseToDWIImageFilter< TInputImage, TB0Image, TMaskImage >::SetMaskImage (const MaskImageType * input) virtual
template<typename TInputImage , typename TB0Image = Image<double,3>, typename TMaskImage = Image<double,3>> virtual void itk::AddNoiseToDWIImageFilter< TInputImage, TB0Image, TMaskImage >::SetNoisetype (NoiseType _arg) virtual
template<typename TInputImage , typename TB0Image = Image<double,3>, typename TMaskImage = Image<double,3>> virtual void itk::AddNoiseToDWIImageFilter< TInputImage, TB0Image, TMaskImage >::SetSigma (double _arg) virtual
Member Data Documentation
template<typename TInputImage , typename TB0Image = Image<double,3>, typename TMaskImage = Image<double,3>> NoiseType itk::AddNoiseToDWIImageFilter< TInputImage, TB0Image, TMaskImage >::m_Noisetype private
Definition at line 89 of file itkAddNoiseToDWIImageFilter.h.
template<typename TInputImage , typename TB0Image = Image<double,3>, typename TMaskImage = Image<double,3>> double itk::AddNoiseToDWIImageFilter< TInputImage, TB0Image, TMaskImage >::m_Sigma private
Definition at line 88 of file itkAddNoiseToDWIImageFilter.h.
The documentation for this class was generated from the following files:
Modules/DWIProcessing/include/itkAddNoiseToDWIImageFilter.h
Modules/DWIProcessing/include/itkAddNoiseToDWIImageFilter.hxx