DMRITool: itk::FunctorFromStringImageFilter< TInputImage, TOutputImage, TMaskImage > Class Template Reference
itk::FunctorFromStringImageFilter< TInputImage, TOutputImage, TMaskImage > Class Template Reference
#include <itkFunctorFromStringImageFilter.h>
Detailed Description
template<typename TInputImage, typename TOutputImage, class TMaskImage = Image<double,3>>
class itk::FunctorFromStringImageFilter< TInputImage, TOutputImage, TMaskImage >
Implements vector-valued generic operation on images with the same size.
m_Functor is not used. m_Expression is a math expression maps one scalar value (one input) or several sacalr values (several inputs) to another scalar (output image). This filter performs m_Expression element-wise on the images.
Author
Jian Cheng
Definition at line 36 of file itkFunctorFromStringImageFilter.h.
Public Types
typedef SmartPointer< const Self > ConstPointer
typedef utl::Functor::VectorMultiVariableFunctionWrapper FunctorType
typedef InputImageType::ConstPointer InputImageConstPointer
typedef InputImageType::IndexType InputImageIndexType
typedef InputImageType::PixelType InputImagePixelType
typedef InputImageType::Pointer InputImagePointer
typedef InputImageType::RegionType InputImageRegionType
typedef InputImageType::SizeType InputImageSizeType
typedef InputImageType::SpacingType InputImageSpacingType
typedef TInputImage InputImageType
typedef Superclass::MaskImageType MaskImageType
typedef OutputImageType::IndexType OutputImageIndexType
typedef OutputImageType::PixelType OutputImagePixelType
typedef OutputImageType::Pointer OutputImagePointer
typedef OutputImageType::RegionType OutputImageRegionType
typedef OutputImageType::SizeType OutputImageSizeType
typedef OutputImageType::SpacingType OutputImageSpacingType
typedef TOutputImage OutputImageType
typedef SmartPointer< Self > Pointer
typedef FunctorFromStringImageFilter Self
typedef FunctorBaseVectorImageFilter< TInputImage, TOutputImage, utl::Functor::VectorMultiVariableFunctionWrapper<>, TMaskImage > Superclass
Public Types inherited from itk::FunctorBaseVectorImageFilter< TInputImage, TOutputImage, utl::Functor::VectorMultiVariableFunctionWrapper<>, TMaskImage >
typedef SmartPointer< const Self > ConstPointer
typedef utl::Functor::VectorMultiVariableFunctionWrapper<> FunctorType
typedef InputImageType::ConstPointer InputImageConstPointer
typedef InputImageType::IndexType InputImageIndexType
typedef InputImageType::PixelType InputImagePixelType
typedef InputImageType::Pointer InputImagePointer
typedef InputImageType::RegionType InputImageRegionType
typedef InputImageType::SizeType InputImageSizeType
typedef InputImageType::SpacingType InputImageSpacingType
typedef TInputImage InputImageType
typedef Superclass::MaskImageType MaskImageType
typedef OutputImageType::IndexType OutputImageIndexType
typedef OutputImageType::PixelType OutputImagePixelType
typedef OutputImageType::Pointer OutputImagePointer
typedef OutputImageType::RegionType OutputImageRegionType
typedef OutputImageType::SizeType OutputImageSizeType
typedef OutputImageType::SpacingType OutputImageSpacingType
typedef TOutputImage OutputImageType
typedef SmartPointer< Self > Pointer
typedef FunctorBaseVectorImageFilter Self
typedef MaskedImageToImageFilter< TInputImage, TOutputImage, TMaskImage > Superclass
Public Types inherited from itk::MaskedImageToImageFilter< TInputImage, TOutputImage, TMaskImage >
typedef SmartPointer< const Self > ConstPointer
typedef InputImageType::ConstPointer InputImageConstPointer
typedef InputImageType::IndexType InputImageIndexType
typedef InputImageType::PixelType InputImagePixelType
typedef InputImageType::Pointer InputImagePointer
typedef InputImageType::RegionType InputImageRegionType
typedef InputImageType::SizeType InputImageSizeType
typedef InputImageType::SpacingType InputImageSpacingType
typedef TInputImage InputImageType
typedef LoggerType::Pointer LoggerPointer
typedef ThreadLogger LoggerType
typedef utl_shared_ptr< LoggerVectorType > LoggerVectorPointer
typedef std::vector< LoggerPointer > LoggerVectorType
typedef MaskImageType::Pointer MaskImagePointer
typedef TMaskImage MaskImageType
typedef OutputImageType::IndexType OutputImageIndexType
typedef OutputImageType::PixelType OutputImagePixelType
typedef OutputImageType::Pointer OutputImagePointer
typedef OutputImageType::RegionType OutputImageRegionType
typedef OutputImageType::SizeType OutputImageSizeType
typedef OutputImageType::SpacingType OutputImageSpacingType
typedef TOutputImage OutputImageType
typedef SmartPointer< Self > Pointer
typedef MaskedImageToImageFilter Self
typedef ImageToImageFilter< TInputImage, TOutputImage > Superclass
Public Member Functions
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual const char * GetNameOfClass () const
itkSetGetMacro (Expression, std::string)
Public Member Functions inherited from itk::FunctorBaseVectorImageFilter< TInputImage, TOutputImage, utl::Functor::VectorMultiVariableFunctionWrapper<>, TMaskImage >
virtual ::itk::LightObject::Pointer CreateAnother (void) const
FunctorType & GetFunctor ()
const FunctorType & GetFunctor () const
itkSetGetMacro (VectorAxis, int)
void SetFunctor (const FunctorType &functor)
Public Member Functions inherited from itk::MaskedImageToImageFilter< TInputImage, TOutputImage, TMaskImage >
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual const LoggerType * GetLogger () const
virtual const MaskImageType * GetMaskImage () const
bool IsMaskUsed ()
itkGetObjectMacro (MaskImage, MaskImageType)
itkGetObjectMacro (Logger, LoggerType)
itkSetGetMacro (LogLevel, int)
virtual void SetLogger (LoggerType *_arg)
virtual void SetMaskImage (MaskImageType *_arg)
void SetMaskImage (const std::string &file)
Static Public Member Functions
static Pointer New ()
Static Public Member Functions inherited from itk::FunctorBaseVectorImageFilter< TInputImage, TOutputImage, utl::Functor::VectorMultiVariableFunctionWrapper<>, TMaskImage >
static Pointer New ()
Static Public Member Functions inherited from itk::MaskedImageToImageFilter< TInputImage, TOutputImage, TMaskImage >
static Pointer New ()
Protected Member Functions
void BeforeThreadedGenerateData () ITK_OVERRIDE
FunctorFromStringImageFilter ()
virtual void GenerateOutputInformation () ITK_OVERRIDE
virtual void PropagateRequestedRegion (DataObject *output) ITK_OVERRIDE
void ThreadedGenerateData (const OutputImageRegionType &outputRegionForThread, ThreadIdType threadId) ITK_OVERRIDE
virtual ~FunctorFromStringImageFilter ()
Protected Member Functions inherited from itk::FunctorBaseVectorImageFilter< TInputImage, TOutputImage, utl::Functor::VectorMultiVariableFunctionWrapper<>, TMaskImage >
FunctorBaseVectorImageFilter ()
LightObject::Pointer InternalClone () const ITK_OVERRIDE
void PrintSelf (std::ostream &os, Indent indent) const ITK_OVERRIDE
virtual ~FunctorBaseVectorImageFilter ()
Protected Member Functions inherited from itk::MaskedImageToImageFilter< TInputImage, TOutputImage, TMaskImage >
void CreateLoggerVector ()
virtual void InitializeThreadedLibraries ()
LightObject::Pointer InternalClone () const ITK_OVERRIDE
MaskedImageToImageFilter ()
std::string ThreadIDToString () const
virtual void VerifyInputParameters () const
virtual void VerifyMaskInformation () const
void WriteLogger (const std::string &str, const LoggerBase::PriorityLevelType level=LoggerBase::DEBUG) const
virtual ~MaskedImageToImageFilter ()
Protected Attributes
std::string m_Expression
Protected Attributes inherited from itk::FunctorBaseVectorImageFilter< TInputImage, TOutputImage, utl::Functor::VectorMultiVariableFunctionWrapper<>, TMaskImage >
FunctorType m_Functor
int m_VectorAxis
Protected Attributes inherited from itk::MaskedImageToImageFilter< TInputImage, TOutputImage, TMaskImage >
LoggerPointer m_Logger
LoggerVectorPointer m_LoggerVector
int m_LogLevel
MaskImagePointer m_MaskImage
int m_ThreadID
Private Member Functions
FunctorFromStringImageFilter (const Self &) ITK_DELETE_FUNCTION
void operator= (const Self &) ITK_DELETE_FUNCTION
Additional Inherited Members
Static Public Attributes inherited from itk::MaskedImageToImageFilter< TInputImage, TOutputImage, TMaskImage >
static const unsigned int InputImageDimension = TInputImage::ImageDimension
static const unsigned int OutputImageDimension = TOutputImage::ImageDimension
Member Typedef Documentation
template<typename TInputImage , typename TOutputImage , class TMaskImage = Image<double,3>> typedef SmartPointer< const Self > itk::FunctorFromStringImageFilter< TInputImage, TOutputImage, TMaskImage >::ConstPointer
Definition at line 44 of file itkFunctorFromStringImageFilter.h.
template<typename TInputImage , typename TOutputImage , class TMaskImage = Image<double,3>> typedef utl::Functor::VectorMultiVariableFunctionWrapper itk::FunctorFromStringImageFilter< TInputImage, TOutputImage, TMaskImage >::FunctorType
Some typedefs.
Definition at line 50 of file itkFunctorFromStringImageFilter.h.
template<typename TInputImage , typename TOutputImage , class TMaskImage = Image<double,3>> typedef InputImageType::ConstPointer itk::FunctorFromStringImageFilter< TInputImage, TOutputImage, TMaskImage >::InputImageConstPointer
Definition at line 57 of file itkFunctorFromStringImageFilter.h.
template<typename TInputImage , typename TOutputImage , class TMaskImage = Image<double,3>> typedef InputImageType::IndexType itk::FunctorFromStringImageFilter< TInputImage, TOutputImage, TMaskImage >::InputImageIndexType
Definition at line 58 of file itkFunctorFromStringImageFilter.h.
template<typename TInputImage , typename TOutputImage , class TMaskImage = Image<double,3>> typedef InputImageType::PixelType itk::FunctorFromStringImageFilter< TInputImage, TOutputImage, TMaskImage >::InputImagePixelType
Definition at line 61 of file itkFunctorFromStringImageFilter.h.
template<typename TInputImage , typename TOutputImage , class TMaskImage = Image<double,3>> typedef InputImageType::Pointer itk::FunctorFromStringImageFilter< TInputImage, TOutputImage, TMaskImage >::InputImagePointer
Definition at line 56 of file itkFunctorFromStringImageFilter.h.
template<typename TInputImage , typename TOutputImage , class TMaskImage = Image<double,3>> typedef InputImageType::RegionType itk::FunctorFromStringImageFilter< TInputImage, TOutputImage, TMaskImage >::InputImageRegionType
Definition at line 62 of file itkFunctorFromStringImageFilter.h.
template<typename TInputImage , typename TOutputImage , class TMaskImage = Image<double,3>> typedef InputImageType::SizeType itk::FunctorFromStringImageFilter< TInputImage, TOutputImage, TMaskImage >::InputImageSizeType
Definition at line 59 of file itkFunctorFromStringImageFilter.h.
template<typename TInputImage , typename TOutputImage , class TMaskImage = Image<double,3>> typedef InputImageType::SpacingType itk::FunctorFromStringImageFilter< TInputImage, TOutputImage, TMaskImage >::InputImageSpacingType
Definition at line 60 of file itkFunctorFromStringImageFilter.h.
template<typename TInputImage , typename TOutputImage , class TMaskImage = Image<double,3>> typedef TInputImage itk::FunctorFromStringImageFilter< TInputImage, TOutputImage, TMaskImage >::InputImageType
Definition at line 55 of file itkFunctorFromStringImageFilter.h.
template<typename TInputImage , typename TOutputImage , class TMaskImage = Image<double,3>> typedef Superclass::MaskImageType itk::FunctorFromStringImageFilter< TInputImage, TOutputImage, TMaskImage >::MaskImageType
Definition at line 72 of file itkFunctorFromStringImageFilter.h.
template<typename TInputImage , typename TOutputImage , class TMaskImage = Image<double,3>> typedef OutputImageType::IndexType itk::FunctorFromStringImageFilter< TInputImage, TOutputImage, TMaskImage >::OutputImageIndexType
Definition at line 66 of file itkFunctorFromStringImageFilter.h.
template<typename TInputImage , typename TOutputImage , class TMaskImage = Image<double,3>> typedef OutputImageType::PixelType itk::FunctorFromStringImageFilter< TInputImage, TOutputImage, TMaskImage >::OutputImagePixelType
Definition at line 69 of file itkFunctorFromStringImageFilter.h.
template<typename TInputImage , typename TOutputImage , class TMaskImage = Image<double,3>> typedef OutputImageType::Pointer itk::FunctorFromStringImageFilter< TInputImage, TOutputImage, TMaskImage >::OutputImagePointer
Definition at line 65 of file itkFunctorFromStringImageFilter.h.
template<typename TInputImage , typename TOutputImage , class TMaskImage = Image<double,3>> typedef OutputImageType::RegionType itk::FunctorFromStringImageFilter< TInputImage, TOutputImage, TMaskImage >::OutputImageRegionType
Definition at line 70 of file itkFunctorFromStringImageFilter.h.
template<typename TInputImage , typename TOutputImage , class TMaskImage = Image<double,3>> typedef OutputImageType::SizeType itk::FunctorFromStringImageFilter< TInputImage, TOutputImage, TMaskImage >::OutputImageSizeType
Definition at line 67 of file itkFunctorFromStringImageFilter.h.
template<typename TInputImage , typename TOutputImage , class TMaskImage = Image<double,3>> typedef OutputImageType::SpacingType itk::FunctorFromStringImageFilter< TInputImage, TOutputImage, TMaskImage >::OutputImageSpacingType
Definition at line 68 of file itkFunctorFromStringImageFilter.h.
template<typename TInputImage , typename TOutputImage , class TMaskImage = Image<double,3>> typedef TOutputImage itk::FunctorFromStringImageFilter< TInputImage, TOutputImage, TMaskImage >::OutputImageType
Definition at line 64 of file itkFunctorFromStringImageFilter.h.
template<typename TInputImage , typename TOutputImage , class TMaskImage = Image<double,3>> typedef SmartPointer< Self > itk::FunctorFromStringImageFilter< TInputImage, TOutputImage, TMaskImage >::Pointer
Definition at line 43 of file itkFunctorFromStringImageFilter.h.
template<typename TInputImage , typename TOutputImage , class TMaskImage = Image<double,3>> typedef FunctorFromStringImageFilter itk::FunctorFromStringImageFilter< TInputImage, TOutputImage, TMaskImage >::Self
Standard class typedefs.
Definition at line 41 of file itkFunctorFromStringImageFilter.h.
template<typename TInputImage , typename TOutputImage , class TMaskImage = Image<double,3>> typedef FunctorBaseVectorImageFilter< TInputImage, TOutputImage, utl::Functor::VectorMultiVariableFunctionWrapper<>, TMaskImage > itk::FunctorFromStringImageFilter< TInputImage, TOutputImage, TMaskImage >::Superclass
Definition at line 42 of file itkFunctorFromStringImageFilter.h.
Constructor & Destructor Documentation
template<typename TInputImage , typename TOutputImage , class TMaskImage > itk::FunctorFromStringImageFilter< TInputImage, TOutputImage, TMaskImage >::FunctorFromStringImageFilter () protected
Definition at line 24 of file itkFunctorFromStringImageFilter.hxx.
References itk::FunctorFromStringImageFilter< TInputImage, TOutputImage, TMaskImage >::GenerateOutputInformation().
template<typename TInputImage , typename TOutputImage , class TMaskImage = Image<double,3>> virtual itk::FunctorFromStringImageFilter< TInputImage, TOutputImage, TMaskImage >::~FunctorFromStringImageFilter () inline protected virtual
Definition at line 78 of file itkFunctorFromStringImageFilter.h.
References ITK_OVERRIDE.
template<typename TInputImage , typename TOutputImage , class TMaskImage = Image<double,3>> itk::FunctorFromStringImageFilter< TInputImage, TOutputImage, TMaskImage >::FunctorFromStringImageFilter (const Self &) private
Member Function Documentation
template<typename TInputImage , typename TOutputImage , class TMaskImage > void itk::FunctorFromStringImageFilter< TInputImage, TOutputImage, TMaskImage >::BeforeThreadedGenerateData () protected
Definition at line 66 of file itkFunctorFromStringImageFilter.hxx.
References utl::IsLogDebug(), itkShowPositionThreadedLogger, itk::FunctorFromStringImageFilter< TInputImage, TOutputImage, TMaskImage >::ThreadedGenerateData(), and utlException.
Referenced by itk::FunctorFromStringImageFilter< TInputImage, TOutputImage, TMaskImage >::GenerateOutputInformation().
template<typename TInputImage , typename TOutputImage , class TMaskImage = Image<double,3>> virtual::itk::LightObject::Pointer itk::FunctorFromStringImageFilter< TInputImage, TOutputImage, TMaskImage >::CreateAnother (void) const
template<typename TInputImage , typename TOutputImage , class TMaskImage > void itk::FunctorFromStringImageFilter< TInputImage, TOutputImage, TMaskImage >::GenerateOutputInformation (void) protected virtual
Definition at line 33 of file itkFunctorFromStringImageFilter.hxx.
References itk::FunctorFromStringImageFilter< TInputImage, TOutputImage, TMaskImage >::BeforeThreadedGenerateData(), itk::CopyImageInformation(), itk::GetVectorImageFullSize(), utl::IsLogDebug(), itkShowPositionThreadedLogger, and utlSAGlobalException.
Referenced by itk::FunctorFromStringImageFilter< TInputImage, TOutputImage, TMaskImage >::FunctorFromStringImageFilter().
template<typename TInputImage , typename TOutputImage , class TMaskImage = Image<double,3>> virtual const char* itk::FunctorFromStringImageFilter< TInputImage, TOutputImage, TMaskImage >::GetNameOfClass () const virtual
Run-time type information (and related methods).
Reimplemented from itk::FunctorBaseVectorImageFilter< TInputImage, TOutputImage, utl::Functor::VectorMultiVariableFunctionWrapper<>, TMaskImage >.
template<typename TInputImage , typename TOutputImage , class TMaskImage = Image<double,3>> itk::FunctorFromStringImageFilter< TInputImage, TOutputImage, TMaskImage >::itkSetGetMacro (Expression , std::string)
template<typename TInputImage , typename TOutputImage , class TMaskImage = Image<double,3>> static Pointer itk::FunctorFromStringImageFilter< TInputImage, TOutputImage, TMaskImage >::New () static
Method for creation through the object factory.
template<typename TInputImage , typename TOutputImage , class TMaskImage = Image<double,3>> void itk::FunctorFromStringImageFilter< TInputImage, TOutputImage, TMaskImage >::operator= (const Self &) private
template<typename TInputImage , typename TOutputImage , class TMaskImage = Image<double,3>> virtual void itk::FunctorFromStringImageFilter< TInputImage, TOutputImage, TMaskImage >::PropagateRequestedRegion (DataObject * output) inline protected virtual
Override Superclass::PropagateRequestedRegion. Otherwise, it may have region outside error.
Definition at line 83 of file itkFunctorFromStringImageFilter.h.
References ITK_OVERRIDE.
template<typename TInputImage , typename TOutputImage , class TMaskImage > void itk::FunctorFromStringImageFilter< TInputImage, TOutputImage, TMaskImage >::ThreadedGenerateData (const OutputImageRegionType & outputRegionForThread, ThreadIdType threadId) protected
ThreadedGenerateData Performs the pixel-wise addition
Definition at line 89 of file itkFunctorFromStringImageFilter.hxx.
References itk::CopyImageRegion(), itk::VectorImageRegionIteratorWithIndex< TImage >::GetVector(), itk::GetVectorImageVectorSize(), utl::IsLogDebug(), itkShowPositionThreadedLogger, utl::PrintUtlVector(), itk::PrintVariableLengthVector(), itk::VectorImageRegionIteratorWithIndex< TImage >::SetVector(), utlSAGlobalException, utl::UtlVectorToVariableLengthVector(), and utl::VariableLengthVectorToUtlVector().
Referenced by itk::FunctorFromStringImageFilter< TInputImage, TOutputImage, TMaskImage >::BeforeThreadedGenerateData().
Member Data Documentation
template<typename TInputImage , typename TOutputImage , class TMaskImage = Image<double,3>> std::string itk::FunctorFromStringImageFilter< TInputImage, TOutputImage, TMaskImage >::m_Expression protected
Definition at line 94 of file itkFunctorFromStringImageFilter.h.
The documentation for this class was generated from the following files:
Modules/Common/include/itkFunctorFromStringImageFilter.h
Modules/Common/include/itkFunctorFromStringImageFilter.hxx