DMRITool: itk::Functor::MultiplyByConstantMatrix< TInput, TMatrix, TOutput > Class Template Reference
itk::Functor::MultiplyByConstantMatrix< TInput, TMatrix, TOutput > Class Template Reference
#include <itkMultiplyByConstantMatrixVectorImageFilter.h>
Detailed Description
template<class TInput, class TMatrix, class TOutput = TInput>
class itk::Functor::MultiplyByConstantMatrix< TInput, TMatrix, TOutput >
Definition at line 32 of file itkMultiplyByConstantMatrixVectorImageFilter.h.
Public Types
typedef TInput::ValueType InputValueType
typedef TOutput::ValueType OutputValueType
typedef utl::NDArray< double, 1 > VectorType
Public Member Functions
const TMatrix & GetConstantMatrix () const
const unsigned GetNumberOfComponentsPerPixelInOutput () const
MultiplyByConstantMatrix ()
bool operator!= (const MultiplyByConstantMatrix &other) const
TOutput operator() (const TInput &A)
bool operator== (const MultiplyByConstantMatrix &other) const
void SetConstantMatrix (const TMatrix &ct)
~MultiplyByConstantMatrix ()
Public Attributes
TMatrix m_ConstantMatrix
Member Typedef Documentation
template<class TInput , class TMatrix , class TOutput = TInput> typedef TInput::ValueType itk::Functor::MultiplyByConstantMatrix< TInput, TMatrix, TOutput >::InputValueType
Definition at line 35 of file itkMultiplyByConstantMatrixVectorImageFilter.h.
template<class TInput , class TMatrix , class TOutput = TInput> typedef TOutput::ValueType itk::Functor::MultiplyByConstantMatrix< TInput, TMatrix, TOutput >::OutputValueType
Definition at line 36 of file itkMultiplyByConstantMatrixVectorImageFilter.h.
template<class TInput , class TMatrix , class TOutput = TInput> typedef utl::NDArray<double, 1> itk::Functor::MultiplyByConstantMatrix< TInput, TMatrix, TOutput >::VectorType
Definition at line 37 of file itkMultiplyByConstantMatrixVectorImageFilter.h.
Constructor & Destructor Documentation
template<class TInput , class TMatrix , class TOutput = TInput> itk::Functor::MultiplyByConstantMatrix< TInput, TMatrix, TOutput >::MultiplyByConstantMatrix () inline
Definition at line 39 of file itkMultiplyByConstantMatrixVectorImageFilter.h.
template<class TInput , class TMatrix , class TOutput = TInput> itk::Functor::MultiplyByConstantMatrix< TInput, TMatrix, TOutput >::~MultiplyByConstantMatrix () inline
Definition at line 43 of file itkMultiplyByConstantMatrixVectorImageFilter.h.
Member Function Documentation
template<class TInput , class TMatrix , class TOutput = TInput> const TMatrix& itk::Functor::MultiplyByConstantMatrix< TInput, TMatrix, TOutput >::GetConstantMatrix () const inline
Definition at line 78 of file itkMultiplyByConstantMatrixVectorImageFilter.h.
References itk::Functor::MultiplyByConstantMatrix< TInput, TMatrix, TOutput >::m_ConstantMatrix.
Referenced by itk::MultiplyByConstantMatrixVectorImageFilter< TInputImage, TConstantMatrix, TOutputImage >::PrintSelf(), and itk::MultiplyByConstantMatrixVectorImageFilter< TInputImage, TConstantMatrix, TOutputImage >::SetConstantMatrix().
template<class TInput , class TMatrix , class TOutput = TInput> const unsigned itk::Functor::MultiplyByConstantMatrix< TInput, TMatrix, TOutput >::GetNumberOfComponentsPerPixelInOutput () const inline
Definition at line 83 of file itkMultiplyByConstantMatrixVectorImageFilter.h.
References itk::Functor::MultiplyByConstantMatrix< TInput, TMatrix, TOutput >::m_ConstantMatrix.
template<class TInput , class TMatrix , class TOutput = TInput> bool itk::Functor::MultiplyByConstantMatrix< TInput, TMatrix, TOutput >::operator!= (const MultiplyByConstantMatrix< TInput, TMatrix, TOutput > & other) const inline
Definition at line 47 of file itkMultiplyByConstantMatrixVectorImageFilter.h.
template<class TInput , class TMatrix , class TOutput = TInput> TOutput itk::Functor::MultiplyByConstantMatrix< TInput, TMatrix, TOutput >::operator() (const TInput & A) inline
Definition at line 57 of file itkMultiplyByConstantMatrixVectorImageFilter.h.
References itk::Functor::MultiplyByConstantMatrix< TInput, TMatrix, TOutput >::m_ConstantMatrix, and utl::ProductUtlMv().
template<class TInput , class TMatrix , class TOutput = TInput> bool itk::Functor::MultiplyByConstantMatrix< TInput, TMatrix, TOutput >::operator== (const MultiplyByConstantMatrix< TInput, TMatrix, TOutput > & other) const inline
Definition at line 52 of file itkMultiplyByConstantMatrixVectorImageFilter.h.
References itk::Functor::MultiplyByConstantMatrix< TInput, TMatrix, TOutput >::m_ConstantMatrix.
template<class TInput , class TMatrix , class TOutput = TInput> void itk::Functor::MultiplyByConstantMatrix< TInput, TMatrix, TOutput >::SetConstantMatrix (const TMatrix & ct) inline
Definition at line 73 of file itkMultiplyByConstantMatrixVectorImageFilter.h.
References itk::Functor::MultiplyByConstantMatrix< TInput, TMatrix, TOutput >::m_ConstantMatrix.
Member Data Documentation
template<class TInput , class TMatrix , class TOutput = TInput> TMatrix itk::Functor::MultiplyByConstantMatrix< TInput, TMatrix, TOutput >::m_ConstantMatrix
Definition at line 88 of file itkMultiplyByConstantMatrixVectorImageFilter.h.
Referenced by itk::Functor::MultiplyByConstantMatrix< TInput, TMatrix, TOutput >::GetConstantMatrix(), itk::Functor::MultiplyByConstantMatrix< TInput, TMatrix, TOutput >::GetNumberOfComponentsPerPixelInOutput(), itk::Functor::MultiplyByConstantMatrix< TInput, TMatrix, TOutput >::operator()(), itk::Functor::MultiplyByConstantMatrix< TInput, TMatrix, TOutput >::operator==(), and itk::Functor::MultiplyByConstantMatrix< TInput, TMatrix, TOutput >::SetConstantMatrix().
The documentation for this class was generated from the following file:
Modules/Common/include/itkMultiplyByConstantMatrixVectorImageFilter.h