DMRITool: spams::FISTA::TreeLasso< T > Class Template Reference
spams::FISTA::TreeLasso< T > Class Template Reference
#include <fista.h>
Detailed Description
template<typename T>
class spams::FISTA::TreeLasso< T >
Definition at line 1529 of file fista.h.
Public Member Functions
T eval (const Vector< T > &x) const
void fenchel (const Vector< T > &y, T &val, T &scal) const
virtual bool is_fenchel () const
virtual bool is_subgrad () const
void prox (const Vector< T > &x, Vector< T > &y, const T lambda)
virtual void sub_grad (const Vector< T > &input, Vector< T > &output) const
TreeLasso (const ParamReg< T > &param)
virtual ~TreeLasso ()
Public Member Functions inherited from spams::FISTA::Regularizer< T >
virtual T eval_dual_norm (const Vector< T > &x) const
virtual T eval_dual_norm_paths (const Vector< T > &x, SpMatrix< T > &path) const
virtual T eval_paths (const Vector< T > &x, SpMatrix< T > &paths_mat) const
virtual bool is_intercept () const
Regularizer ()
Regularizer (const ParamReg< T > &param)
virtual void reset ()
virtual ~Regularizer ()
Private Attributes
bool _linf
Tree_Seq< T > _tree
Additional Inherited Members
Protected Attributes inherited from spams::FISTA::Regularizer< T >
bool _intercept
bool _pos
Constructor & Destructor Documentation
template<typename T > spams::FISTA::TreeLasso< T >::TreeLasso (const ParamReg< T > & param) inline
Definition at line 1531 of file fista.h.
References spams::TreeStruct< T >::groups_ir, spams::TreeStruct< T >::groups_jc, spams::FISTA::ParamReg< T >::linf, spams::TreeStruct< T >::N_own_variables, spams::TreeStruct< T >::Ng, spams::TreeStruct< T >::Nv, spams::TreeStruct< T >::own_variables, spams::FISTA::ParamReg< T >::tree_st, and spams::TreeStruct< T >::weights.
template<typename T > virtual spams::FISTA::TreeLasso< T >::~TreeLasso () inline virtual
Definition at line 1540 of file fista.h.
Member Function Documentation
template<typename T > T spams::FISTA::TreeLasso< T >::eval (const Vector< T > & x) const inline virtual
Implements spams::FISTA::Regularizer< T >.
Definition at line 1553 of file fista.h.
References spams::Vector< T >::rawX().
template<typename T > void spams::FISTA::TreeLasso< T >::fenchel (const Vector< T > & input, T & val, T & scal) const inline virtual
returns phi^star(input) and ouput=input if the fenchel is unconstrained returns 0 and scale input such that phi^star(output)=0 otherwise
Implements spams::FISTA::Regularizer< T >.
Definition at line 1556 of file fista.h.
References spams::Vector< T >::copy(), EPSILON, INFINITY, spams::Vector< T >::n(), spams::Vector< T >::rawX(), spams::Vector< T >::setData(), and spams::Vector< T >::thrsPos().
template<typename T > virtual bool spams::FISTA::TreeLasso< T >::is_fenchel () const inline virtual
Reimplemented from spams::FISTA::Regularizer< T >.
Definition at line 1573 of file fista.h.
template<typename T > virtual bool spams::FISTA::TreeLasso< T >::is_subgrad () const inline virtual
Reimplemented from spams::FISTA::Regularizer< T >.
Definition at line 1576 of file fista.h.
template<typename T > void spams::FISTA::TreeLasso< T >::prox (const Vector< T > & x, Vector< T > & y, const T lambda) inline virtual
Implements spams::FISTA::Regularizer< T >.
Definition at line 1542 of file fista.h.
References spams::Vector< T >::copy(), spams::Vector< T >::n(), spams::Vector< T >::rawX(), spams::Vector< T >::setData(), and spams::Vector< T >::thrsPos().
template<typename T > virtual void spams::FISTA::TreeLasso< T >::sub_grad (const Vector< T > & input, Vector< T > & output) const inline virtual
Reimplemented from spams::FISTA::Regularizer< T >.
Definition at line 1577 of file fista.h.
References spams::Vector< T >::n(), and spams::Vector< T >::resize().
Member Data Documentation
template<typename T > bool spams::FISTA::TreeLasso< T >::_linf private
Definition at line 1584 of file fista.h.
template<typename T > Tree_Seq<T> spams::FISTA::TreeLasso< T >::_tree private
Definition at line 1583 of file fista.h.
The documentation for this class was generated from the following file:
ThirdParty/Spams/include/fista.h