DMRITool: itk::SHCoefficientsPowerImageFilter< TInputImage, TOutputImage > Class Template Reference
itk::SHCoefficientsPowerImageFilter< TInputImage, TOutputImage > Class Template Reference
DiffusionModels
#include <itkSHCoefficientsPowerImageFilter.h>
Detailed Description
template<class TInputImage, class TOutputImage = itk::Image<double,3>>
class itk::SHCoefficientsPowerImageFilter< TInputImage, TOutputImage >
In each vxoel, the input VectorImage is a SH coefficient vector which represents a spherical function. The output VectorImage is another SH coefficient vector whose spherical function is a power of the input function. In formula outputFunction = (inputFunction)^k, where k is a given order. When k==2, then we have closed form of the output SH coefficient vector. When k is not 2, we resample the input spherical function, power it, then refit it using SH basis.
See also
UnaryFunctorImageFilter
Definition at line 135 of file itkSHCoefficientsPowerImageFilter.h.
Public Types
typedef SmartPointer< const Self > ConstPointer
typedef Functor::SHCoefficientsPower< typename TInputImage::PixelType, typename TOutputImage::PixelType > FunctorType
typedef FunctorType::MatrixPointer MatrixPointer
typedef FunctorType::MatrixType MatrixType
typedef SmartPointer< Self > Pointer
typedef SHCoefficientsPowerImageFilter Self
typedef UnaryFunctorImageFilter< TInputImage, TOutputImage, Functor::SHCoefficientsPower< typename TInputImage::PixelType, typename TOutputImage::PixelType > > Superclass
Public Member Functions
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual const char * GetNameOfClass () const
itkFunctorSetGetMacro (Power, double)
itkFunctorSetGetMacro (SHRank, int)
Static Public Member Functions
static Pointer New ()
Protected Member Functions
void BeforeThreadedGenerateData () ITK_OVERRIDE
void GenerateOutputInformation () ITK_OVERRIDE
SHCoefficientsPowerImageFilter ()
virtual ~SHCoefficientsPowerImageFilter ()
Private Member Functions
void operator= (const Self &)
SHCoefficientsPowerImageFilter (const Self &)
Member Typedef Documentation
template<class TInputImage , class TOutputImage = itk::Image<double,3>> typedef SmartPointer<const Self> itk::SHCoefficientsPowerImageFilter< TInputImage, TOutputImage >::ConstPointer
Definition at line 152 of file itkSHCoefficientsPowerImageFilter.h.
template<class TInputImage , class TOutputImage = itk::Image<double,3>> typedef Functor::SHCoefficientsPower< typename TInputImage::PixelType, typename TOutputImage::PixelType> itk::SHCoefficientsPowerImageFilter< TInputImage, TOutputImage >::FunctorType
Definition at line 158 of file itkSHCoefficientsPowerImageFilter.h.
template<class TInputImage , class TOutputImage = itk::Image<double,3>> typedef FunctorType::MatrixPointer itk::SHCoefficientsPowerImageFilter< TInputImage, TOutputImage >::MatrixPointer
Definition at line 164 of file itkSHCoefficientsPowerImageFilter.h.
template<class TInputImage , class TOutputImage = itk::Image<double,3>> typedef FunctorType::MatrixType itk::SHCoefficientsPowerImageFilter< TInputImage, TOutputImage >::MatrixType
Definition at line 163 of file itkSHCoefficientsPowerImageFilter.h.
template<class TInputImage , class TOutputImage = itk::Image<double,3>> typedef SmartPointer<Self> itk::SHCoefficientsPowerImageFilter< TInputImage, TOutputImage >::Pointer
Definition at line 151 of file itkSHCoefficientsPowerImageFilter.h.
template<class TInputImage , class TOutputImage = itk::Image<double,3>> typedef SHCoefficientsPowerImageFilter itk::SHCoefficientsPowerImageFilter< TInputImage, TOutputImage >::Self
Standard class typedefs.
Definition at line 144 of file itkSHCoefficientsPowerImageFilter.h.
template<class TInputImage , class TOutputImage = itk::Image<double,3>> typedef UnaryFunctorImageFilter< TInputImage, TOutputImage, Functor::SHCoefficientsPower< typename TInputImage::PixelType, typename TOutputImage::PixelType> > itk::SHCoefficientsPowerImageFilter< TInputImage, TOutputImage >::Superclass
Definition at line 149 of file itkSHCoefficientsPowerImageFilter.h.
Constructor & Destructor Documentation
template<class TInputImage , class TOutputImage = itk::Image<double,3>> itk::SHCoefficientsPowerImageFilter< TInputImage, TOutputImage >::SHCoefficientsPowerImageFilter () inline protected
Definition at line 170 of file itkSHCoefficientsPowerImageFilter.h.
template<class TInputImage , class TOutputImage = itk::Image<double,3>> virtual itk::SHCoefficientsPowerImageFilter< TInputImage, TOutputImage >::~SHCoefficientsPowerImageFilter () inline protected virtual
Definition at line 174 of file itkSHCoefficientsPowerImageFilter.h.
template<class TInputImage , class TOutputImage = itk::Image<double,3>> itk::SHCoefficientsPowerImageFilter< TInputImage, TOutputImage >::SHCoefficientsPowerImageFilter (const Self &) private
Member Function Documentation
template<class TInputImage , class TOutputImage = itk::Image<double,3>> void itk::SHCoefficientsPowerImageFilter< TInputImage, TOutputImage >::BeforeThreadedGenerateData () inline protected
Definition at line 178 of file itkSHCoefficientsPowerImageFilter.h.
References CARTESIAN_TO_SPHERICAL, utl::ComputeSHMatrix(), utl::DimToRankSH(), DIRECTION_NODUPLICATE, utl::InitializeSHTripleIntegrationTable(), utl::PInverseMatrix(), SPHERICAL_TO_SPHERICAL, and utlGlobalException.
template<class TInputImage , class TOutputImage = itk::Image<double,3>> virtual::itk::LightObject::Pointer itk::SHCoefficientsPowerImageFilter< TInputImage, TOutputImage >::CreateAnother (void) const
template<class TInputImage , class TOutputImage = itk::Image<double,3>> void itk::SHCoefficientsPowerImageFilter< TInputImage, TOutputImage >::GenerateOutputInformation (void) inline protected
Definition at line 201 of file itkSHCoefficientsPowerImageFilter.h.
References utl::DimToRankSH(), utl::RankToDimSH(), and utlGlobalException.
template<class TInputImage , class TOutputImage = itk::Image<double,3>> virtual const char* itk::SHCoefficientsPowerImageFilter< TInputImage, TOutputImage >::GetNameOfClass () const virtual
Run-time type information (and related methods).
template<class TInputImage , class TOutputImage = itk::Image<double,3>> itk::SHCoefficientsPowerImageFilter< TInputImage, TOutputImage >::itkFunctorSetGetMacro (Power , double)
template<class TInputImage , class TOutputImage = itk::Image<double,3>> itk::SHCoefficientsPowerImageFilter< TInputImage, TOutputImage >::itkFunctorSetGetMacro (SHRank , int)
template<class TInputImage , class TOutputImage = itk::Image<double,3>> static Pointer itk::SHCoefficientsPowerImageFilter< TInputImage, TOutputImage >::New () static
Method for creation through the object factory.
template<class TInputImage , class TOutputImage = itk::Image<double,3>> void itk::SHCoefficientsPowerImageFilter< TInputImage, TOutputImage >::operator= (const Self &) private
The documentation for this class was generated from the following file:
Modules/DiffusionModels/include/itkSHCoefficientsPowerImageFilter.h