DMRITool: itk::Functor::MeanDiffusivityFromGHOTCoefficients< TInput, TOutput > Class Template Reference
itk::Functor::MeanDiffusivityFromGHOTCoefficients< TInput, TOutput > Class Template Reference
DiffusionModels
#include <itkMeanDiffusivityFromGHOTImageFilter.h>
Detailed Description
template<class TInput, class TOutput>
class itk::Functor::MeanDiffusivityFromGHOTCoefficients< TInput, TOutput >
MD value from GHOT coefficients.
Author
Jian Cheng (JC), jian..nosp@m.chen.nosp@m.g.198.nosp@m.3@gm.nosp@m.ail.c.nosp@m.om
Definition at line 37 of file itkMeanDiffusivityFromGHOTImageFilter.h.
Public Member Functions
const double & GetScale () const
const double & GetTau () const
MeanDiffusivityFromGHOTCoefficients ()
bool operator!= (const MeanDiffusivityFromGHOTCoefficients &other) const
TOutput operator() (const TInput &A) const
bool operator== (const MeanDiffusivityFromGHOTCoefficients &other) const
void SetScale (const double scale)
void SetTau (const double tau)
~MeanDiffusivityFromGHOTCoefficients ()
Public Attributes
double m_Scale
double m_Tau
Constructor & Destructor Documentation
template<class TInput , class TOutput > itk::Functor::MeanDiffusivityFromGHOTCoefficients< TInput, TOutput >::MeanDiffusivityFromGHOTCoefficients () inline
Definition at line 40 of file itkMeanDiffusivityFromGHOTImageFilter.h.
template<class TInput , class TOutput > itk::Functor::MeanDiffusivityFromGHOTCoefficients< TInput, TOutput >::~MeanDiffusivityFromGHOTCoefficients () inline
Definition at line 41 of file itkMeanDiffusivityFromGHOTImageFilter.h.
Member Function Documentation
template<class TInput , class TOutput > const double& itk::Functor::MeanDiffusivityFromGHOTCoefficients< TInput, TOutput >::GetScale () const inline
Definition at line 58 of file itkMeanDiffusivityFromGHOTImageFilter.h.
References itk::Functor::MeanDiffusivityFromGHOTCoefficients< TInput, TOutput >::m_Scale.
Referenced by itk::MeanDiffusivityFromGHOTImageFilter< TInputImage, TOutputImage >::PrintSelf(), and itk::MeanDiffusivityFromGHOTImageFilter< TInputImage, TOutputImage >::SetScale().
template<class TInput , class TOutput > const double& itk::Functor::MeanDiffusivityFromGHOTCoefficients< TInput, TOutput >::GetTau () const inline
Definition at line 60 of file itkMeanDiffusivityFromGHOTImageFilter.h.
References itk::Functor::MeanDiffusivityFromGHOTCoefficients< TInput, TOutput >::m_Tau.
Referenced by itk::MeanDiffusivityFromGHOTImageFilter< TInputImage, TOutputImage >::PrintSelf(), and itk::MeanDiffusivityFromGHOTImageFilter< TInputImage, TOutputImage >::SetTau().
template<class TInput , class TOutput > bool itk::Functor::MeanDiffusivityFromGHOTCoefficients< TInput, TOutput >::operator!= (const MeanDiffusivityFromGHOTCoefficients< TInput, TOutput > & other) const inline
Definition at line 42 of file itkMeanDiffusivityFromGHOTImageFilter.h.
template<class TInput , class TOutput > TOutput itk::Functor::MeanDiffusivityFromGHOTCoefficients< TInput, TOutput >::operator() (const TInput & A) const inline
Definition at line 51 of file itkMeanDiffusivityFromGHOTImageFilter.h.
References M_PI, itk::Functor::MeanDiffusivityFromGHOTCoefficients< TInput, TOutput >::m_Scale, and itk::Functor::MeanDiffusivityFromGHOTCoefficients< TInput, TOutput >::m_Tau.
template<class TInput , class TOutput > bool itk::Functor::MeanDiffusivityFromGHOTCoefficients< TInput, TOutput >::operator== (const MeanDiffusivityFromGHOTCoefficients< TInput, TOutput > & other) const inline
Definition at line 46 of file itkMeanDiffusivityFromGHOTImageFilter.h.
References itk::Functor::MeanDiffusivityFromGHOTCoefficients< TInput, TOutput >::m_Scale, and itk::Functor::MeanDiffusivityFromGHOTCoefficients< TInput, TOutput >::m_Tau.
template<class TInput , class TOutput > void itk::Functor::MeanDiffusivityFromGHOTCoefficients< TInput, TOutput >::SetScale (const double scale) inline
Definition at line 57 of file itkMeanDiffusivityFromGHOTImageFilter.h.
References itk::Functor::MeanDiffusivityFromGHOTCoefficients< TInput, TOutput >::m_Scale.
template<class TInput , class TOutput > void itk::Functor::MeanDiffusivityFromGHOTCoefficients< TInput, TOutput >::SetTau (const double tau) inline
Definition at line 59 of file itkMeanDiffusivityFromGHOTImageFilter.h.
References itk::Functor::MeanDiffusivityFromGHOTCoefficients< TInput, TOutput >::m_Tau.
Member Data Documentation
template<class TInput , class TOutput > double itk::Functor::MeanDiffusivityFromGHOTCoefficients< TInput, TOutput >::m_Scale
Definition at line 62 of file itkMeanDiffusivityFromGHOTImageFilter.h.
Referenced by itk::Functor::MeanDiffusivityFromGHOTCoefficients< TInput, TOutput >::GetScale(), itk::Functor::MeanDiffusivityFromGHOTCoefficients< TInput, TOutput >::operator()(), itk::Functor::MeanDiffusivityFromGHOTCoefficients< TInput, TOutput >::operator==(), and itk::Functor::MeanDiffusivityFromGHOTCoefficients< TInput, TOutput >::SetScale().
template<class TInput , class TOutput > double itk::Functor::MeanDiffusivityFromGHOTCoefficients< TInput, TOutput >::m_Tau
Definition at line 63 of file itkMeanDiffusivityFromGHOTImageFilter.h.
Referenced by itk::Functor::MeanDiffusivityFromGHOTCoefficients< TInput, TOutput >::GetTau(), itk::Functor::MeanDiffusivityFromGHOTCoefficients< TInput, TOutput >::operator()(), itk::Functor::MeanDiffusivityFromGHOTCoefficients< TInput, TOutput >::operator==(), and itk::Functor::MeanDiffusivityFromGHOTCoefficients< TInput, TOutput >::SetTau().
The documentation for this class was generated from the following file:
Modules/DiffusionModels/include/itkMeanDiffusivityFromGHOTImageFilter.h