DMRITool: itk::MeshFromSHCoefficientsImageFilter< TInputImage, TOutputMesh > Class Template Reference
itk::MeshFromSHCoefficientsImageFilter< TInputImage, TOutputMesh > Class Template Reference
Visualization
#include <itkMeshFromSHCoefficientsImageFilter.h>
Detailed Description
template<class TInputImage, class TOutputMesh = vtkPolyData>
class itk::MeshFromSHCoefficientsImageFilter< TInputImage, TOutputMesh >
Compute mesh from SH coefficients.
Author
Pew-Thian Yap, Jian Cheng, UNC-CH
Definition at line 30 of file itkMeshFromSHCoefficientsImageFilter.h.
Public Types
typedef SphereTessellatorType::BasicShapeType BasicShapeType
typedef SmartPointer< const Self > ConstPointer
typedef InputImageType::ConstPointer InputImageConstPointer
typedef InputImageType::IndexType InputImageIndexType
typedef InputImageType::PixelType InputImagePixelType
typedef InputImageType::Pointer InputImagePointer
typedef InputImageType::PointType InputImagePointType
typedef InputImageType::RegionType InputImageRegionType
typedef InputImageType::SizeType InputImageSizeType
typedef InputImageType::SizeValueType InputImageSizeValueType
typedef InputImageType::SpacingType InputImageSpacingType
typedef TInputImage InputImageType
typedef Superclass::MatrixPointer MatrixPointer
typedef Superclass::MatrixType MatrixType
typedef Superclass::OutputMeshCellArrayType OutputMeshCellArrayType
typedef Superclass::OutputMeshPointsType OutputMeshPointsType
typedef Superclass::OutputMeshPolyDataPointer OutputMeshPolyDataPointer
typedef TOutputMesh OutputMeshPolyDataType
typedef Superclass::OutputMeshRGBType OutputMeshRGBType
typedef Superclass::OutputMeshScalarType OutputMeshScalarType
typedef SmartPointer< Self > Pointer
typedef MeshFromSHCoefficientsImageFilter Self
typedef SphereTessellatorType::Pointer SphereTessellatorPointer
typedef SphereTessellator< double > SphereTessellatorType
typedef Superclass::STDVectorPointer STDVectorPointer
typedef Superclass::STDVectorType STDVectorType
typedef MeshFromContinuousSphericalFunctionImageFilter< TInputImage, TOutputMesh > Superclass
typedef Superclass::VectorPointer VectorPointer
typedef Superclass::VectorType VectorType
Public Types inherited from itk::MeshFromContinuousSphericalFunctionImageFilter< TInputImage, TOutputMesh >
typedef SphereTessellatorType::BasicShapeType BasicShapeType
typedef SmartPointer< const Self > ConstPointer
typedef InputImageType::ConstPointer InputImageConstPointer
typedef InputImageType::IndexType InputImageIndexType
typedef InputImageType::PixelType InputImagePixelType
typedef InputImageType::Pointer InputImagePointer
typedef InputImageType::PointType InputImagePointType
typedef InputImageType::RegionType InputImageRegionType
typedef InputImageType::SizeType InputImageSizeType
typedef InputImageType::SizeValueType InputImageSizeValueType
typedef InputImageType::SpacingType InputImageSpacingType
typedef TInputImage InputImageType
typedef Superclass::MatrixPointer MatrixPointer
typedef Superclass::MatrixType MatrixType
typedef Superclass::OutputMeshCellArrayType OutputMeshCellArrayType
typedef Superclass::OutputMeshPointsType OutputMeshPointsType
typedef Superclass::OutputMeshPolyDataPointer OutputMeshPolyDataPointer
typedef TOutputMesh OutputMeshPolyDataType
typedef Superclass::OutputMeshRGBType OutputMeshRGBType
typedef Superclass::OutputMeshScalarType OutputMeshScalarType
typedef SmartPointer< Self > Pointer
typedef MeshFromContinuousSphericalFunctionImageFilter Self
typedef SphereTessellatorType::Pointer SphereTessellatorPointer
typedef SphereTessellator< double > SphereTessellatorType
typedef Superclass::STDVectorPointer STDVectorPointer
typedef Superclass::STDVectorType STDVectorType
typedef MeshFromSphericalFunctionImageFilter< TInputImage, TOutputMesh > Superclass
typedef Superclass::VectorPointer VectorPointer
typedef Superclass::VectorType VectorType
Public Types inherited from itk::MeshFromSphericalFunctionImageFilter< TInputImage, TOutputMesh >
typedef SphereTessellatorType::BasicShapeType BasicShapeType
typedef SmartPointer< const Self > ConstPointer
typedef InputImageType::ConstPointer InputImageConstPointer
typedef InputImageType::IndexType InputImageIndexType
typedef InputImageType::PixelType InputImagePixelType
typedef InputImageType::Pointer InputImagePointer
typedef InputImageType::PointType InputImagePointType
typedef InputImageType::RegionType InputImageRegionType
typedef InputImageType::SizeType InputImageSizeType
typedef InputImageType::SizeValueType InputImageSizeValueType
typedef InputImageType::SpacingType InputImageSpacingType
typedef TInputImage InputImageType
typedef Superclass::MatrixPointer MatrixPointer
typedef Superclass::MatrixType MatrixType
enum NormalizationType {
NONE =0,
MIN_MAX,
UNIT_MAX,
UNIT_INTEGRAL
}
typedef Superclass::OutputMeshCellArrayType OutputMeshCellArrayType
typedef Superclass::OutputMeshPointsType OutputMeshPointsType
typedef Superclass::OutputMeshPolyDataPointer OutputMeshPolyDataPointer
typedef TOutputMesh OutputMeshPolyDataType
typedef Superclass::OutputMeshRGBType OutputMeshRGBType
typedef Superclass::OutputMeshScalarType OutputMeshScalarType
typedef SmartPointer< Self > Pointer
typedef MeshFromSphericalFunctionImageFilter Self
typedef SphereTessellatorType::Pointer SphereTessellatorPointer
typedef SphereTessellator< double > SphereTessellatorType
typedef Superclass::STDVectorPointer STDVectorPointer
typedef Superclass::STDVectorType STDVectorType
typedef MeshFromImageImageFilter< TInputImage, TOutputMesh > Superclass
typedef Superclass::VectorPointer VectorPointer
typedef Superclass::VectorType VectorType
Public Types inherited from itk::MeshFromImageImageFilter< TInputImage, TOutputMesh >
enum ColorSchemeType {
UNKNOWN =0,
FIXED,
DIRECTION,
MAGNITUDE
}
typedef SmartPointer< const Self > ConstPointer
typedef InputImageType::ConstPointer InputImageConstPointer
typedef InputImageType::IndexType InputImageIndexType
typedef InputImageType::PixelType InputImagePixelType
typedef InputImageType::Pointer InputImagePointer
typedef InputImageType::PointType InputImagePointType
typedef InputImageType::RegionType InputImageRegionType
typedef InputImageType::SizeType InputImageSizeType
typedef InputImageType::SizeValueType InputImageSizeValueType
typedef InputImageType::SpacingType InputImageSpacingType
typedef TInputImage InputImageType
typedef utl_shared_ptr< MatrixType > MatrixPointer
typedef utl::NDArray< double, 2 > MatrixType
typedef vtkCellArray OutputMeshCellArrayType
typedef vtkPoints OutputMeshPointsType
typedef vtkSmartPointer< OutputMeshPolyDataType > OutputMeshPolyDataPointer
typedef TOutputMesh OutputMeshPolyDataType
typedef vtkUnsignedCharArray OutputMeshRGBType
typedef vtkDoubleArray OutputMeshScalarType
typedef SmartPointer< Self > Pointer
typedef MeshFromImageImageFilter Self
typedef utl_shared_ptr< STDVectorType > STDVectorPointer
typedef std::vector< double > STDVectorType
typedef MaskedImageToImageFilter< TInputImage, TInputImage > Superclass
typedef utl_shared_ptr< VectorType > VectorPointer
typedef utl::NDArray< double, 1 > VectorType
Public Types inherited from itk::MaskedImageToImageFilter< TInputImage, TInputImage >
typedef SmartPointer< const Self > ConstPointer
typedef InputImageType::ConstPointer InputImageConstPointer
typedef InputImageType::IndexType InputImageIndexType
typedef InputImageType::PixelType InputImagePixelType
typedef InputImageType::Pointer InputImagePointer
typedef InputImageType::RegionType InputImageRegionType
typedef InputImageType::SizeType InputImageSizeType
typedef InputImageType::SpacingType InputImageSpacingType
typedef TInputImage InputImageType
typedef LoggerType::Pointer LoggerPointer
typedef ThreadLogger LoggerType
typedef utl_shared_ptr< LoggerVectorType > LoggerVectorPointer
typedef std::vector< LoggerPointer > LoggerVectorType
typedef MaskImageType::Pointer MaskImagePointer
typedef Image< double, 3 > MaskImageType
typedef OutputImageType::IndexType OutputImageIndexType
typedef OutputImageType::PixelType OutputImagePixelType
typedef OutputImageType::Pointer OutputImagePointer
typedef OutputImageType::RegionType OutputImageRegionType
typedef OutputImageType::SizeType OutputImageSizeType
typedef OutputImageType::SpacingType OutputImageSpacingType
typedef TInputImage OutputImageType
typedef SmartPointer< Self > Pointer
typedef MaskedImageToImageFilter Self
typedef ImageToImageFilter< TInputImage, TInputImage > Superclass
Public Member Functions
MatrixPointer ComputeBasisMatrix () ITK_OVERRIDE
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual int GetMaxOrder ()
virtual const char * GetNameOfClass () const
VectorType NormalizeUnitIntegral (const VectorType &x) const ITK_OVERRIDE
virtual void SetMaxOrder (int _arg)
Public Member Functions inherited from itk::MeshFromContinuousSphericalFunctionImageFilter< TInputImage, TOutputMesh >
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual BasicShapeType GetBasicShape ()
virtual MatrixPointer GetBasisMatrix ()
virtual unsigned int GetTessellationOrder ()
itkSetGetBooleanMacro (Stretch)
virtual void SetBasicShape (BasicShapeType _arg)
virtual void SetBasisMatrix (MatrixPointer _arg)
virtual void SetTessellationOrder (unsigned int _arg)
Public Member Functions inherited from itk::MeshFromSphericalFunctionImageFilter< TInputImage, TOutputMesh >
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual NormalizationType GetNormalization ()
unsigned int GetNumberOfOrientations () const
virtual MatrixPointer GetOrientations ()
virtual double GetPow ()
virtual bool GetRemoveNegativeValues ()
virtual void RemoveNegativeValuesOff ()
virtual void RemoveNegativeValuesOn ()
virtual void SetNormalization (NormalizationType _arg)
virtual void SetOrientations (MatrixPointer _arg)
virtual void SetPow (double _arg)
virtual void SetRemoveNegativeValues (bool _arg)
Public Member Functions inherited from itk::MeshFromImageImageFilter< TInputImage, TOutputMesh >
virtual ::itk::LightObject::Pointer CreateAnother (void) const
std::vector< int > GetBoxView () const
virtual ColorSchemeType GetColorScheme ()
std::vector< int > GetFlip () const
OutputMeshPolyDataPointer GetOutput ()
virtual double GetScale ()
std::vector< int > GetSliceView () const
void SetBoxView (const int x0, const int x1, const int y0, const int y1, const int z0, const int z1)
virtual void SetColorScheme (ColorSchemeType _arg)
void SetFlip (const int flipx, const int flipy, const int flipz)
virtual void SetScale (double _arg)
void SetSliceView (const int coronal, const int sagittal, const int transverse)
Public Member Functions inherited from itk::MaskedImageToImageFilter< TInputImage, TInputImage >
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual const LoggerType * GetLogger () const
virtual const MaskImageType * GetMaskImage () const
bool IsMaskUsed ()
itkGetObjectMacro (MaskImage, MaskImageType)
itkGetObjectMacro (Logger, LoggerType)
itkSetGetMacro (LogLevel, int)
virtual void SetLogger (LoggerType *_arg)
virtual void SetMaskImage (MaskImageType *_arg)
void SetMaskImage (const std::string &file)
Static Public Member Functions
static Pointer New ()
Static Public Member Functions inherited from itk::MeshFromContinuousSphericalFunctionImageFilter< TInputImage, TOutputMesh >
static Pointer New ()
Static Public Member Functions inherited from itk::MeshFromSphericalFunctionImageFilter< TInputImage, TOutputMesh >
static Pointer New ()
Static Public Member Functions inherited from itk::MeshFromImageImageFilter< TInputImage, TOutputMesh >
static Pointer New ()
Static Public Member Functions inherited from itk::MaskedImageToImageFilter< TInputImage, TInputImage >
static Pointer New ()
Protected Member Functions
LightObject::Pointer InternalClone () const ITK_OVERRIDE
MeshFromSHCoefficientsImageFilter ()
void PrintSelf (std::ostream &os, Indent indent) const ITK_OVERRIDE
~MeshFromSHCoefficientsImageFilter ()
Protected Member Functions inherited from itk::MeshFromContinuousSphericalFunctionImageFilter< TInputImage, TOutputMesh >
void BeforeThreadedGenerateData () ITK_OVERRIDE
LightObject::Pointer InternalClone () const ITK_OVERRIDE
MeshFromContinuousSphericalFunctionImageFilter ()
void ScaleSamples (VectorType &b) const
void ThreadedGenerateData (const typename TInputImage::RegionType &regionForThread, ThreadIdType threadId) ITK_OVERRIDE
void VerifyInputParameters () const ITK_OVERRIDE
~MeshFromContinuousSphericalFunctionImageFilter ()
Protected Member Functions inherited from itk::MeshFromSphericalFunctionImageFilter< TInputImage, TOutputMesh >
LightObject::Pointer InternalClone () const ITK_OVERRIDE
MeshFromSphericalFunctionImageFilter ()
void PrintSelf (std::ostream &os, Indent indent) const ITK_OVERRIDE
~MeshFromSphericalFunctionImageFilter ()
Protected Member Functions inherited from itk::MeshFromImageImageFilter< TInputImage, TOutputMesh >
virtual void AllocateOutputs () ITK_OVERRIDE
virtual void GenerateOutputInformation () ITK_OVERRIDE
LightObject::Pointer InternalClone () const ITK_OVERRIDE
virtual bool IsPixelIndexVisible (const InputImageIndexType &index)
MeshFromImageImageFilter ()
~MeshFromImageImageFilter ()
Protected Member Functions inherited from itk::MaskedImageToImageFilter< TInputImage, TInputImage >
void CreateLoggerVector ()
virtual void InitializeThreadedLibraries ()
LightObject::Pointer InternalClone () const ITK_OVERRIDE
MaskedImageToImageFilter ()
std::string ThreadIDToString () const
virtual void VerifyMaskInformation () const
void WriteLogger (const std::string &str, const LoggerBase::PriorityLevelType level=LoggerBase::DEBUG) const
virtual ~MaskedImageToImageFilter ()
Protected Attributes
int m_MaxOrder
Protected Attributes inherited from itk::MeshFromContinuousSphericalFunctionImageFilter< TInputImage, TOutputMesh >
BasicShapeType m_BasicShape
MatrixPointer m_BasisMatrix
SphereTessellatorPointer m_SphereTessellator
bool m_Stretch =true
unsigned int m_TessellationOrder
Protected Attributes inherited from itk::MeshFromSphericalFunctionImageFilter< TInputImage, TOutputMesh >
NormalizationType m_Normalization
MatrixPointer m_Orientations
double m_Pow
bool m_RemoveNegativeValues
Protected Attributes inherited from itk::MeshFromImageImageFilter< TInputImage, TOutputMesh >
std::vector< int > m_BoxView = std::vector<int>(6,-1)
ColorSchemeType m_ColorScheme =UNKNOWN
std::vector< int > m_Flip = std::vector<int>(3, 0)
OutputMeshPolyDataPointer m_Mesh = OutputMeshPolyDataType::New()
double m_Scale =1.0
std::vector< int > m_SliceView = std::vector<int>(3,-1)
Protected Attributes inherited from itk::MaskedImageToImageFilter< TInputImage, TInputImage >
LoggerPointer m_Logger
LoggerVectorPointer m_LoggerVector
int m_LogLevel
MaskImagePointer m_MaskImage
int m_ThreadID
Private Member Functions
MeshFromSHCoefficientsImageFilter (const Self &)
void operator= (const Self &)
Additional Inherited Members
Static Public Attributes inherited from itk::MeshFromImageImageFilter< TInputImage, TOutputMesh >
static const unsigned int OrientationDimension = 3
Static Public Attributes inherited from itk::MaskedImageToImageFilter< TInputImage, TInputImage >
static const unsigned int InputImageDimension
static const unsigned int OutputImageDimension
Member Typedef Documentation
template<class TInputImage , class TOutputMesh = vtkPolyData> typedef SphereTessellatorType::BasicShapeType itk::MeshFromSHCoefficientsImageFilter< TInputImage, TOutputMesh >::BasicShapeType
Definition at line 70 of file itkMeshFromSHCoefficientsImageFilter.h.
template<class TInputImage , class TOutputMesh = vtkPolyData> typedef SmartPointer<const Self> itk::MeshFromSHCoefficientsImageFilter< TInputImage, TOutputMesh >::ConstPointer
Definition at line 38 of file itkMeshFromSHCoefficientsImageFilter.h.
template<class TInputImage , class TOutputMesh = vtkPolyData> typedef InputImageType::ConstPointer itk::MeshFromSHCoefficientsImageFilter< TInputImage, TOutputMesh >::InputImageConstPointer
Definition at line 49 of file itkMeshFromSHCoefficientsImageFilter.h.
template<class TInputImage , class TOutputMesh = vtkPolyData> typedef InputImageType::IndexType itk::MeshFromSHCoefficientsImageFilter< TInputImage, TOutputMesh >::InputImageIndexType
Definition at line 50 of file itkMeshFromSHCoefficientsImageFilter.h.
template<class TInputImage , class TOutputMesh = vtkPolyData> typedef InputImageType::PixelType itk::MeshFromSHCoefficientsImageFilter< TInputImage, TOutputMesh >::InputImagePixelType
Definition at line 54 of file itkMeshFromSHCoefficientsImageFilter.h.
template<class TInputImage , class TOutputMesh = vtkPolyData> typedef InputImageType::Pointer itk::MeshFromSHCoefficientsImageFilter< TInputImage, TOutputMesh >::InputImagePointer
Definition at line 48 of file itkMeshFromSHCoefficientsImageFilter.h.
template<class TInputImage , class TOutputMesh = vtkPolyData> typedef InputImageType::PointType itk::MeshFromSHCoefficientsImageFilter< TInputImage, TOutputMesh >::InputImagePointType
Definition at line 56 of file itkMeshFromSHCoefficientsImageFilter.h.
template<class TInputImage , class TOutputMesh = vtkPolyData> typedef InputImageType::RegionType itk::MeshFromSHCoefficientsImageFilter< TInputImage, TOutputMesh >::InputImageRegionType
Definition at line 55 of file itkMeshFromSHCoefficientsImageFilter.h.
template<class TInputImage , class TOutputMesh = vtkPolyData> typedef InputImageType::SizeType itk::MeshFromSHCoefficientsImageFilter< TInputImage, TOutputMesh >::InputImageSizeType
Definition at line 51 of file itkMeshFromSHCoefficientsImageFilter.h.
template<class TInputImage , class TOutputMesh = vtkPolyData> typedef InputImageType::SizeValueType itk::MeshFromSHCoefficientsImageFilter< TInputImage, TOutputMesh >::InputImageSizeValueType
Definition at line 52 of file itkMeshFromSHCoefficientsImageFilter.h.
template<class TInputImage , class TOutputMesh = vtkPolyData> typedef InputImageType::SpacingType itk::MeshFromSHCoefficientsImageFilter< TInputImage, TOutputMesh >::InputImageSpacingType
Definition at line 53 of file itkMeshFromSHCoefficientsImageFilter.h.
template<class TInputImage , class TOutputMesh = vtkPolyData> typedef TInputImage itk::MeshFromSHCoefficientsImageFilter< TInputImage, TOutputMesh >::InputImageType
Definition at line 44 of file itkMeshFromSHCoefficientsImageFilter.h.
template<class TInputImage , class TOutputMesh = vtkPolyData> typedef Superclass::MatrixPointer itk::MeshFromSHCoefficientsImageFilter< TInputImage, TOutputMesh >::MatrixPointer
Definition at line 75 of file itkMeshFromSHCoefficientsImageFilter.h.
template<class TInputImage , class TOutputMesh = vtkPolyData> typedef Superclass::MatrixType itk::MeshFromSHCoefficientsImageFilter< TInputImage, TOutputMesh >::MatrixType
Orientation Matrices
Definition at line 74 of file itkMeshFromSHCoefficientsImageFilter.h.
template<class TInputImage , class TOutputMesh = vtkPolyData> typedef Superclass::OutputMeshCellArrayType itk::MeshFromSHCoefficientsImageFilter< TInputImage, TOutputMesh >::OutputMeshCellArrayType
Definition at line 61 of file itkMeshFromSHCoefficientsImageFilter.h.
template<class TInputImage , class TOutputMesh = vtkPolyData> typedef Superclass::OutputMeshPointsType itk::MeshFromSHCoefficientsImageFilter< TInputImage, TOutputMesh >::OutputMeshPointsType
Definition at line 60 of file itkMeshFromSHCoefficientsImageFilter.h.
template<class TInputImage , class TOutputMesh = vtkPolyData> typedef Superclass::OutputMeshPolyDataPointer itk::MeshFromSHCoefficientsImageFilter< TInputImage, TOutputMesh >::OutputMeshPolyDataPointer
Definition at line 62 of file itkMeshFromSHCoefficientsImageFilter.h.
template<class TInputImage , class TOutputMesh = vtkPolyData> typedef TOutputMesh itk::MeshFromSHCoefficientsImageFilter< TInputImage, TOutputMesh >::OutputMeshPolyDataType
Definition at line 58 of file itkMeshFromSHCoefficientsImageFilter.h.
template<class TInputImage , class TOutputMesh = vtkPolyData> typedef Superclass::OutputMeshRGBType itk::MeshFromSHCoefficientsImageFilter< TInputImage, TOutputMesh >::OutputMeshRGBType
Definition at line 64 of file itkMeshFromSHCoefficientsImageFilter.h.
template<class TInputImage , class TOutputMesh = vtkPolyData> typedef Superclass::OutputMeshScalarType itk::MeshFromSHCoefficientsImageFilter< TInputImage, TOutputMesh >::OutputMeshScalarType
Definition at line 63 of file itkMeshFromSHCoefficientsImageFilter.h.
template<class TInputImage , class TOutputMesh = vtkPolyData> typedef SmartPointer<Self> itk::MeshFromSHCoefficientsImageFilter< TInputImage, TOutputMesh >::Pointer
Definition at line 37 of file itkMeshFromSHCoefficientsImageFilter.h.
template<class TInputImage , class TOutputMesh = vtkPolyData> typedef MeshFromSHCoefficientsImageFilter itk::MeshFromSHCoefficientsImageFilter< TInputImage, TOutputMesh >::Self
Standard class typedefs.
Definition at line 35 of file itkMeshFromSHCoefficientsImageFilter.h.
template<class TInputImage , class TOutputMesh = vtkPolyData> typedef SphereTessellatorType::Pointer itk::MeshFromSHCoefficientsImageFilter< TInputImage, TOutputMesh >::SphereTessellatorPointer
Definition at line 69 of file itkMeshFromSHCoefficientsImageFilter.h.
template<class TInputImage , class TOutputMesh = vtkPolyData> typedef SphereTessellator<double> itk::MeshFromSHCoefficientsImageFilter< TInputImage, TOutputMesh >::SphereTessellatorType
Set/Get the min-max normalization
Definition at line 68 of file itkMeshFromSHCoefficientsImageFilter.h.
template<class TInputImage , class TOutputMesh = vtkPolyData> typedef Superclass::STDVectorPointer itk::MeshFromSHCoefficientsImageFilter< TInputImage, TOutputMesh >::STDVectorPointer
Definition at line 79 of file itkMeshFromSHCoefficientsImageFilter.h.
template<class TInputImage , class TOutputMesh = vtkPolyData> typedef Superclass::STDVectorType itk::MeshFromSHCoefficientsImageFilter< TInputImage, TOutputMesh >::STDVectorType
Definition at line 78 of file itkMeshFromSHCoefficientsImageFilter.h.
template<class TInputImage , class TOutputMesh = vtkPolyData> typedef MeshFromContinuousSphericalFunctionImageFilter<TInputImage, TOutputMesh> itk::MeshFromSHCoefficientsImageFilter< TInputImage, TOutputMesh >::Superclass
Definition at line 36 of file itkMeshFromSHCoefficientsImageFilter.h.
template<class TInputImage , class TOutputMesh = vtkPolyData> typedef Superclass::VectorPointer itk::MeshFromSHCoefficientsImageFilter< TInputImage, TOutputMesh >::VectorPointer
Definition at line 77 of file itkMeshFromSHCoefficientsImageFilter.h.
template<class TInputImage , class TOutputMesh = vtkPolyData> typedef Superclass::VectorType itk::MeshFromSHCoefficientsImageFilter< TInputImage, TOutputMesh >::VectorType
Definition at line 76 of file itkMeshFromSHCoefficientsImageFilter.h.
Constructor & Destructor Documentation
template<class TInputImage , class TOutputMesh = vtkPolyData> itk::MeshFromSHCoefficientsImageFilter< TInputImage, TOutputMesh >::MeshFromSHCoefficientsImageFilter () inline protected
Definition at line 111 of file itkMeshFromSHCoefficientsImageFilter.h.
template<class TInputImage , class TOutputMesh = vtkPolyData> itk::MeshFromSHCoefficientsImageFilter< TInputImage, TOutputMesh >::~MeshFromSHCoefficientsImageFilter () inline protected
Definition at line 115 of file itkMeshFromSHCoefficientsImageFilter.h.
template<class TInputImage , class TOutputMesh = vtkPolyData> itk::MeshFromSHCoefficientsImageFilter< TInputImage, TOutputMesh >::MeshFromSHCoefficientsImageFilter (const Self &) private
Member Function Documentation
template<class TInputImage , class TOutputMesh = vtkPolyData> MatrixPointer itk::MeshFromSHCoefficientsImageFilter< TInputImage, TOutputMesh >::ComputeBasisMatrix () inline virtual
Reimplemented from itk::MeshFromContinuousSphericalFunctionImageFilter< TInputImage, TOutputMesh >.
Definition at line 86 of file itkMeshFromSHCoefficientsImageFilter.h.
References CARTESIAN_TO_SPHERICAL, utl::ComputeSHMatrix(), utl::DimToRankSH(), utl::FlipOrientations(), utlGlobalException, and utlShowPosition.
template<class TInputImage , class TOutputMesh = vtkPolyData> virtual::itk::LightObject::Pointer itk::MeshFromSHCoefficientsImageFilter< TInputImage, TOutputMesh >::CreateAnother (void) const
template<class TInputImage , class TOutputMesh = vtkPolyData> virtual int itk::MeshFromSHCoefficientsImageFilter< TInputImage, TOutputMesh >::GetMaxOrder () virtual
template<class TInputImage , class TOutputMesh = vtkPolyData> virtual const char* itk::MeshFromSHCoefficientsImageFilter< TInputImage, TOutputMesh >::GetNameOfClass () const virtual
Run-time type information (and related methods)
Reimplemented from itk::MeshFromContinuousSphericalFunctionImageFilter< TInputImage, TOutputMesh >.
template<class TInputImage , class TOutputMesh = vtkPolyData> LightObject::Pointer itk::MeshFromSHCoefficientsImageFilter< TInputImage, TOutputMesh >::InternalClone () const inline protected
Definition at line 124 of file itkMeshFromSHCoefficientsImageFilter.h.
template<class TInputImage , class TOutputMesh = vtkPolyData> static Pointer itk::MeshFromSHCoefficientsImageFilter< TInputImage, TOutputMesh >::New () static
Method for creation through the object factory.
template<class TInputImage , class TOutputMesh = vtkPolyData> VectorType itk::MeshFromSHCoefficientsImageFilter< TInputImage, TOutputMesh >::NormalizeUnitIntegral (const VectorType & x) const inline virtual
Reimplemented from itk::MeshFromContinuousSphericalFunctionImageFilter< TInputImage, TOutputMesh >.
Definition at line 102 of file itkMeshFromSHCoefficientsImageFilter.h.
References M_PI.
template<class TInputImage , class TOutputMesh = vtkPolyData> void itk::MeshFromSHCoefficientsImageFilter< TInputImage, TOutputMesh >::operator= (const Self &) private
template<class TInputImage , class TOutputMesh = vtkPolyData> void itk::MeshFromSHCoefficientsImageFilter< TInputImage, TOutputMesh >::PrintSelf (std::ostream & os, Indent indent) const inline protected virtual
Standard PrintSelf method.
Reimplemented from itk::MeshFromContinuousSphericalFunctionImageFilter< TInputImage, TOutputMesh >.
Definition at line 118 of file itkMeshFromSHCoefficientsImageFilter.h.
References PrintVar1.
template<class TInputImage , class TOutputMesh = vtkPolyData> virtual void itk::MeshFromSHCoefficientsImageFilter< TInputImage, TOutputMesh >::SetMaxOrder (int _arg) virtual
It extracts the first m_MaxOrder SH basis, if m_MaxOrder < inputPixelDimension. If it is -1, use all SH coefficients.
Member Data Documentation
template<class TInputImage , class TOutputMesh = vtkPolyData> int itk::MeshFromSHCoefficientsImageFilter< TInputImage, TOutputMesh >::m_MaxOrder protected
Definition at line 144 of file itkMeshFromSHCoefficientsImageFilter.h.
The documentation for this class was generated from the following file:
Modules/Visualization/include/itkMeshFromSHCoefficientsImageFilter.h