DMRITool: itk::MultiVariableFunctorVectorImageFilter< TInputImage, TOutputImage, TFunction, TMaskImage > Class Template Reference
itk::MultiVariableFunctorVectorImageFilter< TInputImage, TOutputImage, TFunction, TMaskImage > Class Template Reference
#include <itkMultiVariableFunctorVectorImageFilter.h>
Detailed Description
template<typename TInputImage, typename TOutputImage, typename TFunction, class TMaskImage = Image<double,3>>
class itk::MultiVariableFunctorVectorImageFilter< TInputImage, TOutputImage, TFunction, TMaskImage >
Implements vector-valued generic operation on one image.
Calculation loops over image domain and extracts vectors along x/y/z/t-axis.
m_Functor is a functor with utl::Vector as input and utl::Vector as output. m_Functor needs to define GetOutputDimension to obtain the NumberOfComponentsPerPixel in output image.
Author
Jian Cheng
Definition at line 33 of file itkMultiVariableFunctorVectorImageFilter.h.
Public Types
typedef SmartPointer< const Self > ConstPointer
typedef TFunction FunctorType
typedef InputImageType::ConstPointer InputImageConstPointer
typedef InputImageType::IndexType InputImageIndexType
typedef InputImageType::PixelType InputImagePixelType
typedef InputImageType::Pointer InputImagePointer
typedef InputImageType::RegionType InputImageRegionType
typedef InputImageType::SizeType InputImageSizeType
typedef InputImageType::SpacingType InputImageSpacingType
typedef TInputImage InputImageType
typedef Superclass::MaskImageType MaskImageType
typedef OutputImageType::IndexType OutputImageIndexType
typedef OutputImageType::PixelType OutputImagePixelType
typedef OutputImageType::Pointer OutputImagePointer
typedef OutputImageType::RegionType OutputImageRegionType
typedef OutputImageType::SizeType OutputImageSizeType
typedef OutputImageType::SpacingType OutputImageSpacingType
typedef TOutputImage OutputImageType
typedef SmartPointer< Self > Pointer
typedef MultiVariableFunctorVectorImageFilter Self
typedef FunctorBaseVectorImageFilter< TInputImage, TOutputImage, TFunction, TMaskImage > Superclass
Public Types inherited from itk::FunctorBaseVectorImageFilter< TInputImage, TOutputImage, TFunction, TMaskImage >
typedef SmartPointer< const Self > ConstPointer
typedef TFunction FunctorType
typedef InputImageType::ConstPointer InputImageConstPointer
typedef InputImageType::IndexType InputImageIndexType
typedef InputImageType::PixelType InputImagePixelType
typedef InputImageType::Pointer InputImagePointer
typedef InputImageType::RegionType InputImageRegionType
typedef InputImageType::SizeType InputImageSizeType
typedef InputImageType::SpacingType InputImageSpacingType
typedef TInputImage InputImageType
typedef Superclass::MaskImageType MaskImageType
typedef OutputImageType::IndexType OutputImageIndexType
typedef OutputImageType::PixelType OutputImagePixelType
typedef OutputImageType::Pointer OutputImagePointer
typedef OutputImageType::RegionType OutputImageRegionType
typedef OutputImageType::SizeType OutputImageSizeType
typedef OutputImageType::SpacingType OutputImageSpacingType
typedef TOutputImage OutputImageType
typedef SmartPointer< Self > Pointer
typedef FunctorBaseVectorImageFilter Self
typedef MaskedImageToImageFilter< TInputImage, TOutputImage, TMaskImage > Superclass
Public Types inherited from itk::MaskedImageToImageFilter< TInputImage, TOutputImage, TMaskImage >
typedef SmartPointer< const Self > ConstPointer
typedef InputImageType::ConstPointer InputImageConstPointer
typedef InputImageType::IndexType InputImageIndexType
typedef InputImageType::PixelType InputImagePixelType
typedef InputImageType::Pointer InputImagePointer
typedef InputImageType::RegionType InputImageRegionType
typedef InputImageType::SizeType InputImageSizeType
typedef InputImageType::SpacingType InputImageSpacingType
typedef TInputImage InputImageType
typedef LoggerType::Pointer LoggerPointer
typedef ThreadLogger LoggerType
typedef utl_shared_ptr< LoggerVectorType > LoggerVectorPointer
typedef std::vector< LoggerPointer > LoggerVectorType
typedef MaskImageType::Pointer MaskImagePointer
typedef TMaskImage MaskImageType
typedef OutputImageType::IndexType OutputImageIndexType
typedef OutputImageType::PixelType OutputImagePixelType
typedef OutputImageType::Pointer OutputImagePointer
typedef OutputImageType::RegionType OutputImageRegionType
typedef OutputImageType::SizeType OutputImageSizeType
typedef OutputImageType::SpacingType OutputImageSpacingType
typedef TOutputImage OutputImageType
typedef SmartPointer< Self > Pointer
typedef MaskedImageToImageFilter Self
typedef ImageToImageFilter< TInputImage, TOutputImage > Superclass
Public Member Functions
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual const char * GetNameOfClass () const
Public Member Functions inherited from itk::FunctorBaseVectorImageFilter< TInputImage, TOutputImage, TFunction, TMaskImage >
virtual ::itk::LightObject::Pointer CreateAnother (void) const
FunctorType & GetFunctor ()
const FunctorType & GetFunctor () const
itkSetGetMacro (VectorAxis, int)
void SetFunctor (const FunctorType &functor)
Public Member Functions inherited from itk::MaskedImageToImageFilter< TInputImage, TOutputImage, TMaskImage >
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual const LoggerType * GetLogger () const
virtual const MaskImageType * GetMaskImage () const
bool IsMaskUsed ()
itkGetObjectMacro (MaskImage, MaskImageType)
itkGetObjectMacro (Logger, LoggerType)
itkSetGetMacro (LogLevel, int)
virtual void SetLogger (LoggerType *_arg)
virtual void SetMaskImage (MaskImageType *_arg)
void SetMaskImage (const std::string &file)
Static Public Member Functions
static Pointer New ()
Static Public Member Functions inherited from itk::FunctorBaseVectorImageFilter< TInputImage, TOutputImage, TFunction, TMaskImage >
static Pointer New ()
Static Public Member Functions inherited from itk::MaskedImageToImageFilter< TInputImage, TOutputImage, TMaskImage >
static Pointer New ()
Protected Member Functions
void BeforeThreadedGenerateData () ITK_OVERRIDE
virtual void GenerateOutputInformation () ITK_OVERRIDE
MultiVariableFunctorVectorImageFilter ()
virtual void PropagateRequestedRegion (DataObject *output) ITK_OVERRIDE
void ThreadedGenerateData (const OutputImageRegionType &outputRegionForThread, ThreadIdType threadId) ITK_OVERRIDE
virtual ~MultiVariableFunctorVectorImageFilter ()
Protected Member Functions inherited from itk::FunctorBaseVectorImageFilter< TInputImage, TOutputImage, TFunction, TMaskImage >
FunctorBaseVectorImageFilter ()
LightObject::Pointer InternalClone () const ITK_OVERRIDE
void PrintSelf (std::ostream &os, Indent indent) const ITK_OVERRIDE
virtual ~FunctorBaseVectorImageFilter ()
Protected Member Functions inherited from itk::MaskedImageToImageFilter< TInputImage, TOutputImage, TMaskImage >
void CreateLoggerVector ()
virtual void InitializeThreadedLibraries ()
LightObject::Pointer InternalClone () const ITK_OVERRIDE
MaskedImageToImageFilter ()
std::string ThreadIDToString () const
virtual void VerifyInputParameters () const
virtual void VerifyMaskInformation () const
void WriteLogger (const std::string &str, const LoggerBase::PriorityLevelType level=LoggerBase::DEBUG) const
virtual ~MaskedImageToImageFilter ()
Private Member Functions
MultiVariableFunctorVectorImageFilter (const Self &) ITK_DELETE_FUNCTION
void operator= (const Self &) ITK_DELETE_FUNCTION
Additional Inherited Members
Static Public Attributes inherited from itk::MaskedImageToImageFilter< TInputImage, TOutputImage, TMaskImage >
static const unsigned int InputImageDimension = TInputImage::ImageDimension
static const unsigned int OutputImageDimension = TOutputImage::ImageDimension
Protected Attributes inherited from itk::FunctorBaseVectorImageFilter< TInputImage, TOutputImage, TFunction, TMaskImage >
FunctorType m_Functor
int m_VectorAxis =3
Protected Attributes inherited from itk::MaskedImageToImageFilter< TInputImage, TOutputImage, TMaskImage >
LoggerPointer m_Logger
LoggerVectorPointer m_LoggerVector
int m_LogLevel
MaskImagePointer m_MaskImage
int m_ThreadID
Member Typedef Documentation
template<typename TInputImage , typename TOutputImage , typename TFunction , class TMaskImage = Image<double,3>> typedef SmartPointer< const Self > itk::MultiVariableFunctorVectorImageFilter< TInputImage, TOutputImage, TFunction, TMaskImage >::ConstPointer
Definition at line 41 of file itkMultiVariableFunctorVectorImageFilter.h.
template<typename TInputImage , typename TOutputImage , typename TFunction , class TMaskImage = Image<double,3>> typedef TFunction itk::MultiVariableFunctorVectorImageFilter< TInputImage, TOutputImage, TFunction, TMaskImage >::FunctorType
Some typedefs.
Definition at line 47 of file itkMultiVariableFunctorVectorImageFilter.h.
template<typename TInputImage , typename TOutputImage , typename TFunction , class TMaskImage = Image<double,3>> typedef InputImageType::ConstPointer itk::MultiVariableFunctorVectorImageFilter< TInputImage, TOutputImage, TFunction, TMaskImage >::InputImageConstPointer
Definition at line 54 of file itkMultiVariableFunctorVectorImageFilter.h.
template<typename TInputImage , typename TOutputImage , typename TFunction , class TMaskImage = Image<double,3>> typedef InputImageType::IndexType itk::MultiVariableFunctorVectorImageFilter< TInputImage, TOutputImage, TFunction, TMaskImage >::InputImageIndexType
Definition at line 55 of file itkMultiVariableFunctorVectorImageFilter.h.
template<typename TInputImage , typename TOutputImage , typename TFunction , class TMaskImage = Image<double,3>> typedef InputImageType::PixelType itk::MultiVariableFunctorVectorImageFilter< TInputImage, TOutputImage, TFunction, TMaskImage >::InputImagePixelType
Definition at line 58 of file itkMultiVariableFunctorVectorImageFilter.h.
template<typename TInputImage , typename TOutputImage , typename TFunction , class TMaskImage = Image<double,3>> typedef InputImageType::Pointer itk::MultiVariableFunctorVectorImageFilter< TInputImage, TOutputImage, TFunction, TMaskImage >::InputImagePointer
Definition at line 53 of file itkMultiVariableFunctorVectorImageFilter.h.
template<typename TInputImage , typename TOutputImage , typename TFunction , class TMaskImage = Image<double,3>> typedef InputImageType::RegionType itk::MultiVariableFunctorVectorImageFilter< TInputImage, TOutputImage, TFunction, TMaskImage >::InputImageRegionType
Definition at line 59 of file itkMultiVariableFunctorVectorImageFilter.h.
template<typename TInputImage , typename TOutputImage , typename TFunction , class TMaskImage = Image<double,3>> typedef InputImageType::SizeType itk::MultiVariableFunctorVectorImageFilter< TInputImage, TOutputImage, TFunction, TMaskImage >::InputImageSizeType
Definition at line 56 of file itkMultiVariableFunctorVectorImageFilter.h.
template<typename TInputImage , typename TOutputImage , typename TFunction , class TMaskImage = Image<double,3>> typedef InputImageType::SpacingType itk::MultiVariableFunctorVectorImageFilter< TInputImage, TOutputImage, TFunction, TMaskImage >::InputImageSpacingType
Definition at line 57 of file itkMultiVariableFunctorVectorImageFilter.h.
template<typename TInputImage , typename TOutputImage , typename TFunction , class TMaskImage = Image<double,3>> typedef TInputImage itk::MultiVariableFunctorVectorImageFilter< TInputImage, TOutputImage, TFunction, TMaskImage >::InputImageType
Definition at line 52 of file itkMultiVariableFunctorVectorImageFilter.h.
template<typename TInputImage , typename TOutputImage , typename TFunction , class TMaskImage = Image<double,3>> typedef Superclass::MaskImageType itk::MultiVariableFunctorVectorImageFilter< TInputImage, TOutputImage, TFunction, TMaskImage >::MaskImageType
Definition at line 69 of file itkMultiVariableFunctorVectorImageFilter.h.
template<typename TInputImage , typename TOutputImage , typename TFunction , class TMaskImage = Image<double,3>> typedef OutputImageType::IndexType itk::MultiVariableFunctorVectorImageFilter< TInputImage, TOutputImage, TFunction, TMaskImage >::OutputImageIndexType
Definition at line 63 of file itkMultiVariableFunctorVectorImageFilter.h.
template<typename TInputImage , typename TOutputImage , typename TFunction , class TMaskImage = Image<double,3>> typedef OutputImageType::PixelType itk::MultiVariableFunctorVectorImageFilter< TInputImage, TOutputImage, TFunction, TMaskImage >::OutputImagePixelType
Definition at line 66 of file itkMultiVariableFunctorVectorImageFilter.h.
template<typename TInputImage , typename TOutputImage , typename TFunction , class TMaskImage = Image<double,3>> typedef OutputImageType::Pointer itk::MultiVariableFunctorVectorImageFilter< TInputImage, TOutputImage, TFunction, TMaskImage >::OutputImagePointer
Definition at line 62 of file itkMultiVariableFunctorVectorImageFilter.h.
template<typename TInputImage , typename TOutputImage , typename TFunction , class TMaskImage = Image<double,3>> typedef OutputImageType::RegionType itk::MultiVariableFunctorVectorImageFilter< TInputImage, TOutputImage, TFunction, TMaskImage >::OutputImageRegionType
Definition at line 67 of file itkMultiVariableFunctorVectorImageFilter.h.
template<typename TInputImage , typename TOutputImage , typename TFunction , class TMaskImage = Image<double,3>> typedef OutputImageType::SizeType itk::MultiVariableFunctorVectorImageFilter< TInputImage, TOutputImage, TFunction, TMaskImage >::OutputImageSizeType
Definition at line 64 of file itkMultiVariableFunctorVectorImageFilter.h.
template<typename TInputImage , typename TOutputImage , typename TFunction , class TMaskImage = Image<double,3>> typedef OutputImageType::SpacingType itk::MultiVariableFunctorVectorImageFilter< TInputImage, TOutputImage, TFunction, TMaskImage >::OutputImageSpacingType
Definition at line 65 of file itkMultiVariableFunctorVectorImageFilter.h.
template<typename TInputImage , typename TOutputImage , typename TFunction , class TMaskImage = Image<double,3>> typedef TOutputImage itk::MultiVariableFunctorVectorImageFilter< TInputImage, TOutputImage, TFunction, TMaskImage >::OutputImageType
Definition at line 61 of file itkMultiVariableFunctorVectorImageFilter.h.
template<typename TInputImage , typename TOutputImage , typename TFunction , class TMaskImage = Image<double,3>> typedef SmartPointer< Self > itk::MultiVariableFunctorVectorImageFilter< TInputImage, TOutputImage, TFunction, TMaskImage >::Pointer
Definition at line 40 of file itkMultiVariableFunctorVectorImageFilter.h.
template<typename TInputImage , typename TOutputImage , typename TFunction , class TMaskImage = Image<double,3>> typedef MultiVariableFunctorVectorImageFilter itk::MultiVariableFunctorVectorImageFilter< TInputImage, TOutputImage, TFunction, TMaskImage >::Self
Standard class typedefs.
Definition at line 38 of file itkMultiVariableFunctorVectorImageFilter.h.
template<typename TInputImage , typename TOutputImage , typename TFunction , class TMaskImage = Image<double,3>> typedef FunctorBaseVectorImageFilter< TInputImage, TOutputImage, TFunction, TMaskImage > itk::MultiVariableFunctorVectorImageFilter< TInputImage, TOutputImage, TFunction, TMaskImage >::Superclass
Definition at line 39 of file itkMultiVariableFunctorVectorImageFilter.h.
Constructor & Destructor Documentation
template<typename TInputImage , typename TOutputImage , typename TFunction , class TMaskImage > itk::MultiVariableFunctorVectorImageFilter< TInputImage, TOutputImage, TFunction, TMaskImage >::MultiVariableFunctorVectorImageFilter () protected
Definition at line 25 of file itkMultiVariableFunctorVectorImageFilter.hxx.
References itk::MultiVariableFunctorVectorImageFilter< TInputImage, TOutputImage, TFunction, TMaskImage >::GenerateOutputInformation().
template<typename TInputImage , typename TOutputImage , typename TFunction , class TMaskImage = Image<double,3>> virtual itk::MultiVariableFunctorVectorImageFilter< TInputImage, TOutputImage, TFunction, TMaskImage >::~MultiVariableFunctorVectorImageFilter () inline protected virtual
Definition at line 73 of file itkMultiVariableFunctorVectorImageFilter.h.
References ITK_OVERRIDE.
template<typename TInputImage , typename TOutputImage , typename TFunction , class TMaskImage = Image<double,3>> itk::MultiVariableFunctorVectorImageFilter< TInputImage, TOutputImage, TFunction, TMaskImage >::MultiVariableFunctorVectorImageFilter (const Self &) private
Member Function Documentation
template<typename TInputImage , typename TOutputImage , typename TFunction , class TMaskImage > void itk::MultiVariableFunctorVectorImageFilter< TInputImage, TOutputImage, TFunction, TMaskImage >::BeforeThreadedGenerateData () protected
Definition at line 75 of file itkMultiVariableFunctorVectorImageFilter.hxx.
References itk::GetVectorImageFullSize(), utl::IsLogDebug(), itkShowPositionThreadedLogger, and itk::MultiVariableFunctorVectorImageFilter< TInputImage, TOutputImage, TFunction, TMaskImage >::ThreadedGenerateData().
Referenced by itk::MultiVariableFunctorVectorImageFilter< TInputImage, TOutputImage, TFunction, TMaskImage >::GenerateOutputInformation().
template<typename TInputImage , typename TOutputImage , typename TFunction , class TMaskImage = Image<double,3>> virtual::itk::LightObject::Pointer itk::MultiVariableFunctorVectorImageFilter< TInputImage, TOutputImage, TFunction, TMaskImage >::CreateAnother (void) const
template<typename TInputImage , typename TOutputImage , typename TFunction , class TMaskImage > void itk::MultiVariableFunctorVectorImageFilter< TInputImage, TOutputImage, TFunction, TMaskImage >::GenerateOutputInformation (void) protected virtual
Definition at line 34 of file itkMultiVariableFunctorVectorImageFilter.hxx.
References itk::MultiVariableFunctorVectorImageFilter< TInputImage, TOutputImage, TFunction, TMaskImage >::BeforeThreadedGenerateData(), itk::CopyImageInformation(), itk::GetVectorImageFullSize(), utl::IsLogDebug(), itkShowPositionThreadedLogger, itk::SetVectorImageFullSize(), utlException, and utlSAGlobalException.
Referenced by itk::MultiVariableFunctorVectorImageFilter< TInputImage, TOutputImage, TFunction, TMaskImage >::MultiVariableFunctorVectorImageFilter().
template<typename TInputImage , typename TOutputImage , typename TFunction , class TMaskImage = Image<double,3>> virtual const char* itk::MultiVariableFunctorVectorImageFilter< TInputImage, TOutputImage, TFunction, TMaskImage >::GetNameOfClass () const virtual
Run-time type information (and related methods).
Reimplemented from itk::FunctorBaseVectorImageFilter< TInputImage, TOutputImage, TFunction, TMaskImage >.
template<typename TInputImage , typename TOutputImage , typename TFunction , class TMaskImage = Image<double,3>> static Pointer itk::MultiVariableFunctorVectorImageFilter< TInputImage, TOutputImage, TFunction, TMaskImage >::New () static
Method for creation through the object factory.
template<typename TInputImage , typename TOutputImage , typename TFunction , class TMaskImage = Image<double,3>> void itk::MultiVariableFunctorVectorImageFilter< TInputImage, TOutputImage, TFunction, TMaskImage >::operator= (const Self &) private
template<typename TInputImage , typename TOutputImage , typename TFunction , class TMaskImage = Image<double,3>> virtual void itk::MultiVariableFunctorVectorImageFilter< TInputImage, TOutputImage, TFunction, TMaskImage >::PropagateRequestedRegion (DataObject * output) inline protected virtual
Override Superclass::PropagateRequestedRegion. Otherwise, it may have region outside error.
Definition at line 78 of file itkMultiVariableFunctorVectorImageFilter.h.
References ITK_DELETE_FUNCTION, and ITK_OVERRIDE.
template<typename TInputImage , typename TOutputImage , typename TFunction , class TMaskImage > void itk::MultiVariableFunctorVectorImageFilter< TInputImage, TOutputImage, TFunction, TMaskImage >::ThreadedGenerateData (const OutputImageRegionType & outputRegionForThread, ThreadIdType threadId) protected
ThreadedGenerateData Performs the pixel-wise addition
Definition at line 96 of file itkMultiVariableFunctorVectorImageFilter.hxx.
References itk::CopyImageRegion(), itk::VectorImageRegionIteratorWithIndex< TImage >::GetVector(), itk::GetVectorImageVectorSize(), utl::IsLogDebug(), itkShowPositionThreadedLogger, utl::PrintUtlVector(), itk::PrintVariableLengthVector(), itk::VectorImageRegionIteratorWithIndex< TImage >::SetVector(), utlSAGlobalException, utl::UtlVectorToVariableLengthVector(), and utl::VariableLengthVectorToUtlVector().
Referenced by itk::MultiVariableFunctorVectorImageFilter< TInputImage, TOutputImage, TFunction, TMaskImage >::BeforeThreadedGenerateData().
The documentation for this class was generated from the following files:
Modules/Common/include/itkMultiVariableFunctorVectorImageFilter.h
Modules/Common/include/itkMultiVariableFunctorVectorImageFilter.hxx