DMRITool: utl::GradientTable< T > Class Template Reference
utl::GradientTable< T > Class Template Reference
#include <utlDMRIStoredTables.h>
Detailed Description
template<class T = double>
class utl::GradientTable< T >
gradient table related functions and stored tables.
Author
Jian Cheng
Date
10-03-2016
Definition at line 74 of file utlDMRIStoredTables.h.
Public Types
typedef std::shared_ptr< MatrixType > MatrixPointer
typedef utl::NDArray< T, 2 > MatrixType
typedef std::shared_ptr< GradientTable< T > > Pointer
typedef GradientTable< T > Self
typedef utl::NDArray< T, 1 > VectorType
Public Member Functions
GradientTable ()
virtual ~GradientTable ()
Static Public Member Functions
static MatrixPointer GetGrad (const int tessorder, const int NoSymmetricDuple=DIRECTION_NODUPLICATE, const int mode=CARTESIAN_TO_SPHERICAL, const int flipx=DIRECTION_NOFLIP, const int flipy=DIRECTION_NOFLIP, const int flipz=DIRECTION_NOFLIP, const bool need_normalize=true)
static Pointer GetInstance ()
static void Initialize (const int tessorder)
Protected Member Functions
template<>
GradientTable< double >::Pointer m_Instance
Protected Attributes
std::vector< MatrixPointer > m_GradTable
Static Protected Attributes
static Pointer m_Instance
Private Member Functions
GradientTable (const GradientTable &other)
GradientTable & operator= (const GradientTable &other)
Member Typedef Documentation
template<class T = double> typedef std::shared_ptr<MatrixType> utl::GradientTable< T >::MatrixPointer
Definition at line 83 of file utlDMRIStoredTables.h.
template<class T = double> typedef utl::NDArray<T,2> utl::GradientTable< T >::MatrixType
Definition at line 82 of file utlDMRIStoredTables.h.
template<class T = double> typedef std::shared_ptr<GradientTable<T> > utl::GradientTable< T >::Pointer
Definition at line 79 of file utlDMRIStoredTables.h.
template<class T = double> typedef GradientTable<T> utl::GradientTable< T >::Self
Definition at line 78 of file utlDMRIStoredTables.h.
template<class T = double> typedef utl::NDArray<T,1> utl::GradientTable< T >::VectorType
Definition at line 81 of file utlDMRIStoredTables.h.
Constructor & Destructor Documentation
template<class T = double> utl::GradientTable< T >::GradientTable () inline
GradientTable constructor
Definition at line 86 of file utlDMRIStoredTables.h.
template<class T = double> virtual utl::GradientTable< T >::~GradientTable () inline virtual
GradientTable deconstructor
Definition at line 91 of file utlDMRIStoredTables.h.
template<class T = double> utl::GradientTable< T >::GradientTable (const GradientTable< T > & other) private
GradientTable constructor
Member Function Documentation
template<class T = double> static MatrixPointer utl::GradientTable< T >::GetGrad (const int tessorder, const int NoSymmetricDuple = DIRECTION_NODUPLICATE, const int mode = CARTESIAN_TO_SPHERICAL, const int flipx = DIRECTION_NOFLIP, const int flipy = DIRECTION_NOFLIP, const int flipz = DIRECTION_NOFLIP, const bool need_normalize = true) inline static
Get a copy of the stored gradient table, considering the output may be modified later.
Definition at line 132 of file utlDMRIStoredTables.h.
References CARTESIAN_TO_SPHERICAL, utl::CartesianToSpherical(), DIRECTION_DUPLICATE, DIRECTION_FLIP, SPHERICAL_TO_CARTESIAN, SPHERICAL_TO_SPHERICAL, utlException, utlSAException, and utlSAGlobalException.
Referenced by itk::SamplingScheme3D< TPixelType >::CalculateVoronoiEntropy(), itk::SamplingScheme3D< TPixelType >::CalculateVoronoiEntropyInShell(), itk::SHCoefficientsRotation< T >::Initialize(), and utl::ReadGrad().
template<class T = double> static Pointer utl::GradientTable< T >::GetInstance () inline static
Definition at line 94 of file utlDMRIStoredTables.h.
template<class T = double> static void utl::GradientTable< T >::Initialize (const int tessorder) inline static
Initially read stored gradient tables
Definition at line 111 of file utlDMRIStoredTables.h.
References CARTESIAN_TO_CARTESIAN, utl::CreateExpandedPath(), DIRECTION_NODUPLICATE, utl::DirectionsT1, utl::DirectionsT2, utl::DirectionsT3, utl::DirectionsT4, utl::DirectionsT5, utl::DirectionsT6, utl::DirectionsT7, and utlSAGlobalException.
Referenced by itk::SamplingScheme3D< TPixelType >::CalculateVoronoiEntropy(), itk::SamplingScheme3D< TPixelType >::CalculateVoronoiEntropyInShell(), itk::SHCoefficientsRotation< T >::Initialize(), and utl::ReadGrad().
template<> GradientTable< double >::Pointer utl::GradientTable< double >::m_Instance () protected
Definition at line 184 of file utlDMRIStoredTables.h.
template<class T = double> GradientTable& utl::GradientTable< T >::operator= (const GradientTable< T > & other) private
GradientTable operator = , assignment operator
Member Data Documentation
template<class T = double> std::vector<MatrixPointer> utl::GradientTable< T >::m_GradTable protected
Definition at line 171 of file utlDMRIStoredTables.h.
template<class T = double> Pointer utl::GradientTable< T >::m_Instance static protected
Definition at line 173 of file utlDMRIStoredTables.h.
The documentation for this class was generated from the following file:
Modules/HelperFunctions/include/utlDMRIStoredTables.h