DMRITool: spams::FISTA::GraphPathL0< T > Class Template Reference
spams::FISTA::GraphPathL0< T > Class Template Reference
#include <fista.h>
Detailed Description
template<typename T>
class spams::FISTA::GraphPathL0< T >
Definition at line 2064 of file fista.h.
Public Member Functions
T eval (const Vector< T > &x) const
T eval_paths (const Vector< T > &x, SpMatrix< T > &paths_mat) const
void fenchel (const Vector< T > &input, T &val, T &scal) const
GraphPathL0 (const ParamReg< T > &param)
virtual bool is_fenchel () const
void prox (const Vector< T > &x, Vector< T > &y, const T lambda)
virtual ~GraphPathL0 ()
Public Member Functions inherited from spams::FISTA::Regularizer< T >
virtual T eval_dual_norm (const Vector< T > &x) const
virtual T eval_dual_norm_paths (const Vector< T > &x, SpMatrix< T > &path) const
virtual bool is_intercept () const
virtual bool is_subgrad () const
Regularizer ()
Regularizer (const ParamReg< T > &param)
virtual void reset ()
virtual void sub_grad (const Vector< T > &input, Vector< T > &output) const
virtual ~Regularizer ()
Private Attributes
GraphPath< T > _graph
Additional Inherited Members
Protected Attributes inherited from spams::FISTA::Regularizer< T >
bool _intercept
bool _pos
Constructor & Destructor Documentation
template<typename T > spams::FISTA::GraphPathL0< T >::GraphPathL0 (const ParamReg< T > & param) inline
Definition at line 2066 of file fista.h.
References spams::FISTA::ParamReg< T >::graph_path_st.
template<typename T > virtual spams::FISTA::GraphPathL0< T >::~GraphPathL0 () inline virtual
Definition at line 2070 of file fista.h.
Member Function Documentation
template<typename T > T spams::FISTA::GraphPathL0< T >::eval (const Vector< T > & x) const inline virtual
Implements spams::FISTA::Regularizer< T >.
Definition at line 2078 of file fista.h.
References spams::Vector< T >::rawX().
template<typename T > T spams::FISTA::GraphPathL0< T >::eval_paths (const Vector< T > & x, SpMatrix< T > & paths_mat) const inline virtual
Reimplemented from spams::FISTA::Regularizer< T >.
Definition at line 2081 of file fista.h.
References spams::SpMatrix< T >::n(), and spams::Vector< T >::rawX().
template<typename T > void spams::FISTA::GraphPathL0< T >::fenchel (const Vector< T > & input, T & val, T & scal) const inline virtual
returns phi^star(input) and ouput=input if the fenchel is unconstrained returns 0 and scale input such that phi^star(output)=0 otherwise
Implements spams::FISTA::Regularizer< T >.
Definition at line 2091 of file fista.h.
template<typename T > virtual bool spams::FISTA::GraphPathL0< T >::is_fenchel () const inline virtual
Reimplemented from spams::FISTA::Regularizer< T >.
Definition at line 2090 of file fista.h.
template<typename T > void spams::FISTA::GraphPathL0< T >::prox (const Vector< T > & x, Vector< T > & y, const T lambda) inline virtual
Implements spams::FISTA::Regularizer< T >.
Definition at line 2072 of file fista.h.
References spams::Vector< T >::copy(), spams::FISTA::ParamFISTA< T >::lambda, spams::Vector< T >::rawX(), and spams::Vector< T >::thrsPos().
Member Data Documentation
template<typename T > GraphPath<T> spams::FISTA::GraphPathL0< T >::_graph private
Definition at line 2091 of file fista.h.
The documentation for this class was generated from the following file:
ThirdParty/Spams/include/fista.h