DMRITool: itk::DiffusionTensor< TPrecision > Class Template Reference
itk::DiffusionTensor< TPrecision > Class Template Reference
DiffusionModels
#include <itkDiffusionTensor.h>
Detailed Description
template<class TPrecision>
class itk::DiffusionTensor< TPrecision >
tensor with some useful functions
The elements is stored as a 6 dimentional array.
Author
Jian Cheng
Definition at line 46 of file itkDiffusionTensor.h.
Public Types
typedef Superclass::AccumulateValueType AccumulateValueType
typedef Superclass::ComponentType ComponentType
typedef Superclass::EigenValuesArrayType EigenValuesArrayType
typedef Superclass::EigenVectorsMatrixType EigenVectorsMatrixType
typedef Superclass::RealValueType RealValueType
typedef DiffusionTensor Self
typedef DiffusionTensor3D< TPrecision > Superclass
typedef Superclass::SymmetricEigenAnalysisType SymmetricEigenAnalysisType
typedef Superclass::ValueType ValueType
typedef Vector< TPrecision, NDimension > VectorType
Public Member Functions
DiffusionTensor ()
DiffusionTensor (const Self &r)
template<class TTensorValueType >
DiffusionTensor (const DiffusionTensor< TTensorValueType > &v)
TPrecision EuclideanDistance (const DiffusionTensor< TPrecision > &X) const
Self Exp () const
void Flip (const int flipx, const int flipy, const int flipz)
TPrecision GeodesicDistance (const DiffusionTensor< TPrecision > &X) const
RealValueType GetADC () const
double GetDeterminant () const
template<class TVectorType >
void GetDWISamples (TVectorType &vec, const utl::NDArray< TPrecision, 2 > &gradients, const std::vector< TPrecision > &bValues) const
template<class TVectorType >
void GetEAPSamples (TVectorType &vec, const utl::NDArray< TPrecision, 2 > &gradients, const std::vector< TPrecision > &rValues, const TPrecision &tau) const
void GetEigenValuesVectors (vnl_diag_matrix< TPrecision > &eigenValues, vnl_matrix< TPrecision > &eigenVectors) const
template<class TArrayType , class TMatrixType >
void GetEigenValuesVectorsAnalytic (TArrayType &eigenValues, TMatrixType &eigenVectors) const
RealValueType GetFA () const
RealValueType GetGA () const
RealValueType GetMD () const
RealValueType GetMeanSquaredDisplacement (const TPrecision tau) const
RealValueType GetMODE () const
double GetNorm () const
template<class TVectorType >
void GetODFSamples (TVectorType &vec, const utl::NDArray< TPrecision, 2 > &gradients, const int &odfOrder=2, const bool &isNormalize=false) const
double GetQuadraticForm (const double x, const double y, const double z) const
RealValueType GetRA () const
RealValueType GetReturnToOrigin (const TPrecision tau) const
Self GetRotate (const typename Self::MatrixType &mat) const
vnl_matrix< TPrecision > GetRotate (const vnl_matrix< TPrecision > &vec) const
template<class TVectorType >
void GetSphericalSamples (TVectorType &vec, const utl::NDArray< TPrecision, 2 > &gradients) const
vnl_matrix< TPrecision > GetVnlMatrix () const
bool HasNans () const
Self Inv () const
Self InvSqrt () const
bool IsDiagonal (const double eps=1e-10) const
bool IsFinite () const
bool IsPositive () const
bool IsSame (const Self &mat, const double eps=1e-8) const
bool IsZero (const double eps=1e-10) const
TPrecision KLDistance (const DiffusionTensor< TPrecision > &X) const
Self Log () const
TPrecision LogEucDistance (const DiffusionTensor< TPrecision > &X) const
bool operator!= (const Self &mat) const
ValueType & operator() (unsigned int row, unsigned int col)
const ValueType & operator() (unsigned int row, unsigned int col) const
Self operator* (const Self &A) const
vnl_matrix< TPrecision > operator* (const vnl_matrix< TPrecision > &A) const
VectorType operator* (const VectorType &v) const
Self operator+ (const Self &mat) const
Self operator- (const Self &mat) const
template<class TMatrixType >
Self & operator= (const TMatrixType &mat)
bool operator== (const Self &mat) const
void Positivize () const
Self Pow (const double &n) const
void Print (std::ostream &os, Indent indent=0) const
Self & Rotate (const typename Self::MatrixType &mat)
template<class TArrayType >
void SetEigenValues (const TArrayType &array)
template<class TMatrixType >
void SetEigenVectors (const TMatrixType &vectors)
void SetVnlMatrix (const vnl_matrix< TPrecision > &mat)
Self Sqrt () const
Static Public Attributes
static const unsigned int NDegreesOfFreedom = NDimension*(NDimension+1)/2
static const unsigned int NDimension = 3
Member Typedef Documentation
template<class TPrecision> typedef Superclass::AccumulateValueType itk::DiffusionTensor< TPrecision >::AccumulateValueType
Definition at line 63 of file itkDiffusionTensor.h.
template<class TPrecision> typedef Superclass::ComponentType itk::DiffusionTensor< TPrecision >::ComponentType
Definition at line 58 of file itkDiffusionTensor.h.
template<class TPrecision> typedef Superclass::EigenValuesArrayType itk::DiffusionTensor< TPrecision >::EigenValuesArrayType
Definition at line 60 of file itkDiffusionTensor.h.
template<class TPrecision> typedef Superclass::EigenVectorsMatrixType itk::DiffusionTensor< TPrecision >::EigenVectorsMatrixType
Definition at line 61 of file itkDiffusionTensor.h.
template<class TPrecision> typedef Superclass::RealValueType itk::DiffusionTensor< TPrecision >::RealValueType
Definition at line 64 of file itkDiffusionTensor.h.
template<class TPrecision> typedef DiffusionTensor itk::DiffusionTensor< TPrecision >::Self
Standard class typedefs.
Definition at line 51 of file itkDiffusionTensor.h.
template<class TPrecision> typedef DiffusionTensor3D<TPrecision> itk::DiffusionTensor< TPrecision >::Superclass
Definition at line 52 of file itkDiffusionTensor.h.
template<class TPrecision> typedef Superclass::SymmetricEigenAnalysisType itk::DiffusionTensor< TPrecision >::SymmetricEigenAnalysisType
Definition at line 66 of file itkDiffusionTensor.h.
template<class TPrecision> typedef Superclass::ValueType itk::DiffusionTensor< TPrecision >::ValueType
Definition at line 57 of file itkDiffusionTensor.h.
template<class TPrecision> typedef Vector<TPrecision, NDimension> itk::DiffusionTensor< TPrecision >::VectorType
Definition at line 68 of file itkDiffusionTensor.h.
Constructor & Destructor Documentation
template<class TPrecision> itk::DiffusionTensor< TPrecision >::DiffusionTensor () inline
Defaut constructor
Definition at line 71 of file itkDiffusionTensor.h.
template<class TPrecision> itk::DiffusionTensor< TPrecision >::DiffusionTensor (const Self & r) inline
copy constructors.
Definition at line 74 of file itkDiffusionTensor.h.
template<class TPrecision> template<class TTensorValueType > itk::DiffusionTensor< TPrecision >::DiffusionTensor (const DiffusionTensor< TTensorValueType > & v) inline
Definition at line 77 of file itkDiffusionTensor.h.
Member Function Documentation
template<typename TPrecision> TPrecision itk::DiffusionTensor< TPrecision >::EuclideanDistance (const DiffusionTensor< TPrecision > & X) const inline
Definition at line 675 of file itkDiffusionTensor.hxx.
References itk::DiffusionTensor< TPrecision >::KLDistance().
Referenced by itk::DiffusionTensor< TPrecision >::GetMD(), and itk::DiffusionTensor< TPrecision >::InvSqrt().
template<class TPrecision > DiffusionTensor< TPrecision > itk::DiffusionTensor< TPrecision >::Exp () const inline
Return the matrix exponential
Definition at line 589 of file itkDiffusionTensor.hxx.
References itk::DiffusionTensor< TPrecision >::Pow(), itk::DiffusionTensor< TPrecision >::SetVnlMatrix(), and utlAssert.
Referenced by itk::DiffusionTensor< TPrecision >::GetMD(), and itk::DiffusionTensor< TPrecision >::Log().
template<class TPrecision> void itk::DiffusionTensor< TPrecision >::Flip (const int flipx, const int flipy, const int flipz) inline
Definition at line 157 of file itkDiffusionTensor.h.
References itk::DiffusionTensor< TPrecision >::GetADC(), itk::DiffusionTensor< TPrecision >::GetDeterminant(), itk::DiffusionTensor< TPrecision >::GetDWISamples(), itk::DiffusionTensor< TPrecision >::GetEAPSamples(), itk::DiffusionTensor< TPrecision >::GetEigenValuesVectors(), itk::DiffusionTensor< TPrecision >::GetEigenValuesVectorsAnalytic(), itk::DiffusionTensor< TPrecision >::GetFA(), itk::DiffusionTensor< TPrecision >::GetGA(), itk::DiffusionTensor< TPrecision >::GetMeanSquaredDisplacement(), itk::DiffusionTensor< TPrecision >::GetMODE(), itk::DiffusionTensor< TPrecision >::GetNorm(), itk::DiffusionTensor< TPrecision >::GetODFSamples(), itk::DiffusionTensor< TPrecision >::GetQuadraticForm(), itk::DiffusionTensor< TPrecision >::GetRA(), itk::DiffusionTensor< TPrecision >::GetReturnToOrigin(), itk::DiffusionTensor< TPrecision >::GetRotate(), itk::DiffusionTensor< TPrecision >::GetSphericalSamples(), itk::DiffusionTensor< TPrecision >::GetVnlMatrix(), itk::DiffusionTensor< TPrecision >::Rotate(), itk::DiffusionTensor< TPrecision >::SetEigenValues(), itk::DiffusionTensor< TPrecision >::SetEigenVectors(), and itk::DiffusionTensor< TPrecision >::SetVnlMatrix().
Referenced by itk::MeshFromTensorImageFilter< TInputImage, TOutputMesh >::GenerateData().
template<typename TPrecision> TPrecision itk::DiffusionTensor< TPrecision >::GeodesicDistance (const DiffusionTensor< TPrecision > & X) const inline
Definition at line 694 of file itkDiffusionTensor.hxx.
References utl::Log(), and itk::DiffusionTensor< TPrecision >::LogEucDistance().
Referenced by itk::DiffusionTensor< TPrecision >::GetMD(), and itk::DiffusionTensor< TPrecision >::KLDistance().
template<class TPrecision > DiffusionTensor< TPrecision >::RealValueType itk::DiffusionTensor< TPrecision >::GetADC () const
Mean Diffusivity
Definition at line 441 of file itkDiffusionTensor.hxx.
References itk::DiffusionTensor< TPrecision >::GetRA().
Referenced by itk::DiffusionTensor< TPrecision >::Flip(), itk::DiffusionTensor< TPrecision >::GetFA(), and itk::DiffusionTensor< TPrecision >::GetMD().
template<class TPrecision > double itk::DiffusionTensor< TPrecision >::GetDeterminant () const inline
Definition at line 550 of file itkDiffusionTensor.hxx.
References itk::DiffusionTensor< TPrecision >::GetNorm().
Referenced by itk::DiffusionTensor< TPrecision >::Flip(), itk::DiffusionTensor< TPrecision >::GetMODE(), and itk::DiffusionTensor< TPrecision >::HasNans().
template<class TPrecision> template<class TVectorType > void itk::DiffusionTensor< TPrecision >::GetDWISamples (TVectorType & vec, const utl::NDArray< TPrecision, 2 > & gradients, const std::vector< TPrecision > & bValues) const
get the DWI samples based on given gradients (Cartesian form) and b values.
Note
No boundary checking. The size of the input vec should be the same as the gradients.rows(), and vec should have the operator[].
Definition at line 326 of file itkDiffusionTensor.hxx.
References itk::DiffusionTensor< TPrecision >::GetODFSamples(), and utlAssert.
Referenced by itk::TensorBasisMatrixGenerator< TElement >::ComputeBasisMatrix(), itk::DiffusionTensor< TPrecision >::Flip(), itk::DWIGenerator< TOutputImage, TScalarImage >::GenerateData(), itk::DWISingleVoxelGenerator< TOutputImage, TScalarImage >::GenerateData(), and itk::DiffusionTensor< TPrecision >::GetSphericalSamples().
template<class TPrecision> template<class TVectorType > void itk::DiffusionTensor< TPrecision >::GetEAPSamples (TVectorType & vec, const utl::NDArray< TPrecision, 2 > & gradients, const std::vector< TPrecision > & rValues, const TPrecision & tau) const
get the EAP samples based on given gradients (Cartesian form) and r values.
Note
No boundary checking. The size of the input vec should be the same as the gradients.rows(), and vec should have the operator[].
Definition at line 373 of file itkDiffusionTensor.hxx.
References itk::DiffusionTensor< TPrecision >::GetReturnToOrigin(), M_PI, and utlAssert.
Referenced by itk::TensorBasisMatrixGenerator< TElement >::ComputeBasisMatrix(), itk::DiffusionTensor< TPrecision >::Flip(), itk::DWIGenerator< TOutputImage, TScalarImage >::GenerateData(), itk::DWISingleVoxelGenerator< TOutputImage, TScalarImage >::GenerateData(), and itk::DiffusionTensor< TPrecision >::GetODFSamples().
template<class TPrecision> void itk::DiffusionTensor< TPrecision >::GetEigenValuesVectors (vnl_diag_matrix< TPrecision > & eigenValues, vnl_matrix< TPrecision > & eigenVectors) const
Return an array containing EigenValues in ascending order, and a matrix containing the corresponding Eigenvectors.
Parameters
eigenVectors eigenvectors stored in vnl_matrix<TPrecision>, where each column is an eigenvector.
Note
eigenvectors in itk::SymmetricSecondRankTensor::ComputeEigenAnalysis stored as rows of itk::Matrix
Definition at line 84 of file itkDiffusionTensor.hxx.
References itk::DiffusionTensor< TPrecision >::GetEigenValuesVectorsAnalytic().
Referenced by itk::DiffusionTensor< TPrecision >::Flip(), and itk::DiffusionTensor< TPrecision >::operator()().
template<class TPrecision > template<class TArrayType , class TMatrixType > void itk::DiffusionTensor< TPrecision >::GetEigenValuesVectorsAnalytic (TArrayType & eigenValues, TMatrixType & eigenVectors) const
analytic way to calculate eigenValues (in ascending order) and eigenVectors. In mathematica, Eigenvectors[({ {a, b, c}, {b, d, e}, {c, e, f} })]
Parameters
eigenVectors eigenvectors stored in vnl_matrix<TPrecision>, where each column is an eigenvector.
Note
: Eigenvalues can be obtained analytically. But there is a numerical issue when dividing a small number for calculating eigenvectors. In this case, use a numerical way for eigenvectors.
Definition at line 100 of file itkDiffusionTensor.hxx.
References utl::PolynomialRoot(), and itk::DiffusionTensor< TPrecision >::SetEigenValues().
Referenced by itk::DiffusionTensor< TPrecision >::Flip(), itk::DiffusionTensor< TPrecision >::GetEigenValuesVectors(), and itk::MeshFromTensorImageFilter< TInputImage, TOutputMesh >::GetScalarCodeFromTensor().
template<class TPrecision > DiffusionTensor< TPrecision >::RealValueType itk::DiffusionTensor< TPrecision >::GetFA () const
FA
Definition at line 433 of file itkDiffusionTensor.hxx.
References itk::DiffusionTensor< TPrecision >::GetADC().
Referenced by itk::DiffusionTensor< TPrecision >::Flip(), itk::DiffusionTensor< TPrecision >::GetGA(), and itk::MeshFromTensorImageFilter< TInputImage, TOutputMesh >::GetScalarCodeFromTensor().
template<class TPrecision > DiffusionTensor< TPrecision >::RealValueType itk::DiffusionTensor< TPrecision >::GetGA () const
GA
Definition at line 408 of file itkDiffusionTensor.hxx.
References itk::DiffusionTensor< TPrecision >::GetFA().
Referenced by itk::DiffusionTensor< TPrecision >::Flip(), and itk::DiffusionTensor< TPrecision >::GetMeanSquaredDisplacement().
template<class TPrecision> RealValueType itk::DiffusionTensor< TPrecision >::GetMD () const inline
Definition at line 250 of file itkDiffusionTensor.h.
References itk::DiffusionTensor< TPrecision >::EuclideanDistance(), itk::DiffusionTensor< TPrecision >::Exp(), itk::DiffusionTensor< TPrecision >::GeodesicDistance(), itk::DiffusionTensor< TPrecision >::GetADC(), itk::DiffusionTensor< TPrecision >::HasNans(), itk::DiffusionTensor< TPrecision >::Inv(), itk::DiffusionTensor< TPrecision >::InvSqrt(), itk::DiffusionTensor< TPrecision >::IsDiagonal(), itk::DiffusionTensor< TPrecision >::IsFinite(), itk::DiffusionTensor< TPrecision >::IsPositive(), itk::DiffusionTensor< TPrecision >::IsZero(), itk::DiffusionTensor< TPrecision >::KLDistance(), itk::DiffusionTensor< TPrecision >::Log(), itk::DiffusionTensor< TPrecision >::LogEucDistance(), itk::DiffusionTensor< TPrecision >::Positivize(), itk::DiffusionTensor< TPrecision >::Pow(), and itk::DiffusionTensor< TPrecision >::Sqrt().
Referenced by itk::MeshFromTensorImageFilter< TInputImage, TOutputMesh >::GetScalarCodeFromTensor().
template<class TPrecision> DiffusionTensor< TPrecision >::RealValueType itk::DiffusionTensor< TPrecision >::GetMeanSquaredDisplacement (const TPrecision tau) const
Mean Squared Displacement
Definition at line 400 of file itkDiffusionTensor.hxx.
References itk::DiffusionTensor< TPrecision >::GetGA().
Referenced by itk::DiffusionTensor< TPrecision >::Flip(), itk::DWIGenerator< TOutputImage, TScalarImage >::GenerateData(), itk::DWISingleVoxelGenerator< TOutputImage, TScalarImage >::GenerateData(), and itk::DiffusionTensor< TPrecision >::GetReturnToOrigin().
template<class TPrecision > DiffusionTensor< TPrecision >::RealValueType itk::DiffusionTensor< TPrecision >::GetMODE () const
Mode
Definition at line 457 of file itkDiffusionTensor.hxx.
References itk::DiffusionTensor< TPrecision >::GetDeterminant(), itk::DiffusionTensor< TPrecision >::GetNorm(), and itk::DiffusionTensor< TPrecision >::IsPositive().
Referenced by itk::DiffusionTensor< TPrecision >::Flip(), and itk::DiffusionTensor< TPrecision >::GetRA().
template<class TPrecision > double itk::DiffusionTensor< TPrecision >::GetNorm () const inline
Definition at line 559 of file itkDiffusionTensor.hxx.
References itk::DiffusionTensor< TPrecision >::Log().
Referenced by itk::DiffusionTensor< TPrecision >::Flip(), itk::DiffusionTensor< TPrecision >::GetDeterminant(), and itk::DiffusionTensor< TPrecision >::GetMODE().
template<class TPrecision> template<class TVectorType > void itk::DiffusionTensor< TPrecision >::GetODFSamples (TVectorType & vec, const utl::NDArray< TPrecision, 2 > & gradients, const int & odfOrder = 2, const bool & isNormalize = false) const
get the ODF samples based on given gradients (Cartesian form) and odf order. When gradients are evenly distributed in , the odf samples can be numerically normalized if isNormalize=true.
Note
No boundary checking. The size of the input vec should be the same as the gradients.rows(), and vec should have the operator[].
Definition at line 342 of file itkDiffusionTensor.hxx.
References itk::DiffusionTensor< TPrecision >::GetEAPSamples(), and M_PI.
Referenced by itk::TensorBasisMatrixGenerator< TElement >::ComputeBasisMatrix(), itk::DiffusionTensor< TPrecision >::Flip(), itk::DWIGenerator< TOutputImage, TScalarImage >::GenerateData(), itk::DWISingleVoxelGenerator< TOutputImage, TScalarImage >::GenerateData(), and itk::DiffusionTensor< TPrecision >::GetDWISamples().
template<class TPrecision > double itk::DiffusionTensor< TPrecision >::GetQuadraticForm (const double x, const double y, const double z) const
Definition at line 302 of file itkDiffusionTensor.hxx.
References itk::DiffusionTensor< TPrecision >::GetSphericalSamples().
Referenced by itk::DiffusionTensor< TPrecision >::Flip(), and itk::DiffusionTensor< TPrecision >::GetRotate().
template<class TPrecision > DiffusionTensor< TPrecision >::RealValueType itk::DiffusionTensor< TPrecision >::GetRA () const
RA
Definition at line 449 of file itkDiffusionTensor.hxx.
References itk::DiffusionTensor< TPrecision >::GetMODE().
Referenced by itk::DiffusionTensor< TPrecision >::Flip(), and itk::DiffusionTensor< TPrecision >::GetADC().
template<class TPrecision> DiffusionTensor< TPrecision >::RealValueType itk::DiffusionTensor< TPrecision >::GetReturnToOrigin (const TPrecision tau) const
Return-To-Origin probability
Definition at line 391 of file itkDiffusionTensor.hxx.
References itk::DiffusionTensor< TPrecision >::GetMeanSquaredDisplacement(), and M_PI.
Referenced by itk::DiffusionTensor< TPrecision >::Flip(), itk::DWIGenerator< TOutputImage, TScalarImage >::GenerateData(), itk::DWISingleVoxelGenerator< TOutputImage, TScalarImage >::GenerateData(), and itk::DiffusionTensor< TPrecision >::GetEAPSamples().
template<class TPrecision > DiffusionTensor< TPrecision > itk::DiffusionTensor< TPrecision >::GetRotate (const typename Self::MatrixType & mat) const inline
Transform the tensor with a matrix
Definition at line 281 of file itkDiffusionTensor.hxx.
References itk::DiffusionTensor< TPrecision >::SetVnlMatrix().
Referenced by itk::DiffusionTensor< TPrecision >::Flip(), and itk::DiffusionTensor< TPrecision >::Rotate().
template<class TPrecision> vnl_matrix< TPrecision > itk::DiffusionTensor< TPrecision >::GetRotate (const vnl_matrix< TPrecision > & vec) const inline
Transform the tensor with a matrix
Definition at line 292 of file itkDiffusionTensor.hxx.
References itk::DiffusionTensor< TPrecision >::GetQuadraticForm().
template<class TPrecision> template<class TVectorType > void itk::DiffusionTensor< TPrecision >::GetSphericalSamples (TVectorType & vec, const utl::NDArray< TPrecision, 2 > & gradients) const
get spherical samples based on given gradients (Cartesian form).
Note
No boundary checking. The size of the input vec should be the same as the gradients.rows(), and vec should have the operator[].
Definition at line 312 of file itkDiffusionTensor.hxx.
References itk::DiffusionTensor< TPrecision >::GetDWISamples().
Referenced by itk::DiffusionTensor< TPrecision >::Flip(), and itk::DiffusionTensor< TPrecision >::GetQuadraticForm().
template<class TPrecision > vnl_matrix< TPrecision > itk::DiffusionTensor< TPrecision >::GetVnlMatrix (void) const inline
Get a vnl_matrix with a copy of the internal memory block.
Definition at line 245 of file itkDiffusionTensor.hxx.
References itk::DiffusionTensor< TPrecision >::SetVnlMatrix().
Referenced by itk::DiffusionTensor< TPrecision >::Flip(), itk::DiffusionTensor< TPrecision >::operator*(), and itk::DiffusionTensor< TPrecision >::SetEigenVectors().
template<class TPrecision > bool itk::DiffusionTensor< TPrecision >::HasNans () const
Definition at line 542 of file itkDiffusionTensor.hxx.
References itk::DiffusionTensor< TPrecision >::GetDeterminant().
Referenced by itk::DiffusionTensor< TPrecision >::GetMD(), and itk::DiffusionTensor< TPrecision >::IsFinite().
template<class TPrecision > DiffusionTensor< TPrecision > itk::DiffusionTensor< TPrecision >::Inv (void) const inline
Definition at line 638 of file itkDiffusionTensor.hxx.
References itk::DiffusionTensor< TPrecision >::Sqrt(), and utlGlobalException.
Referenced by itk::DiffusionTensor< TPrecision >::GetMD(), itk::DiffusionTensor< TPrecision >::KLDistance(), and itk::DiffusionTensor< TPrecision >::Pow().
template<class TPrecision > DiffusionTensor< TPrecision > itk::DiffusionTensor< TPrecision >::InvSqrt () const inline
Definition at line 667 of file itkDiffusionTensor.hxx.
References itk::DiffusionTensor< TPrecision >::EuclideanDistance(), and utl::Pow().
Referenced by itk::DiffusionTensor< TPrecision >::GetMD(), and itk::DiffusionTensor< TPrecision >::Sqrt().
template<class TPrecision > bool itk::DiffusionTensor< TPrecision >::IsDiagonal (const double eps = 1e-10) const
Definition at line 520 of file itkDiffusionTensor.hxx.
References itk::DiffusionTensor< TPrecision >::IsFinite().
Referenced by itk::DiffusionTensor< TPrecision >::GetMD(), and itk::DiffusionTensor< TPrecision >::IsZero().
template<class TPrecision > bool itk::DiffusionTensor< TPrecision >::IsFinite () const
Definition at line 534 of file itkDiffusionTensor.hxx.
References itk::DiffusionTensor< TPrecision >::HasNans().
Referenced by itk::DiffusionTensor< TPrecision >::GetMD(), and itk::DiffusionTensor< TPrecision >::IsDiagonal().
template<class TPrecision > bool itk::DiffusionTensor< TPrecision >::IsPositive () const
Definition at line 474 of file itkDiffusionTensor.hxx.
References itk::DiffusionTensor< TPrecision >::Positivize(), and utlAssert.
Referenced by itk::DiffusionTensor< TPrecision >::GetMD(), and itk::DiffusionTensor< TPrecision >::GetMODE().
template<class TPrecision> bool itk::DiffusionTensor< TPrecision >::IsSame (const Self & mat, const double eps = 1e-8) const inline
Definition at line 93 of file itkDiffusionTensor.h.
References itk::DiffusionTensor< TPrecision >::NDegreesOfFreedom.
template<class TPrecision > bool itk::DiffusionTensor< TPrecision >::IsZero (const double eps = 1e-10) const
Definition at line 507 of file itkDiffusionTensor.hxx.
References itk::DiffusionTensor< TPrecision >::IsDiagonal().
Referenced by itk::DiffusionTensor< TPrecision >::GetMD(), and itk::DiffusionTensor< TPrecision >::Positivize().
template<typename TPrecision> TPrecision itk::DiffusionTensor< TPrecision >::KLDistance (const DiffusionTensor< TPrecision > & X) const inline
Definition at line 683 of file itkDiffusionTensor.hxx.
References itk::DiffusionTensor< TPrecision >::GeodesicDistance(), and itk::DiffusionTensor< TPrecision >::Inv().
Referenced by itk::DiffusionTensor< TPrecision >::EuclideanDistance(), and itk::DiffusionTensor< TPrecision >::GetMD().
template<class TPrecision > DiffusionTensor< TPrecision > itk::DiffusionTensor< TPrecision >::Log () const inline
Return the matrix logarithm
Definition at line 568 of file itkDiffusionTensor.hxx.
References itk::DiffusionTensor< TPrecision >::Exp(), itk::DiffusionTensor< TPrecision >::SetVnlMatrix(), and utlException.
Referenced by itk::DiffusionTensor< TPrecision >::GetMD(), itk::DiffusionTensor< TPrecision >::GetNorm(), and itk::DiffusionTensor< TPrecision >::LogEucDistance().
template<typename TPrecision> TPrecision itk::DiffusionTensor< TPrecision >::LogEucDistance (const DiffusionTensor< TPrecision > & X) const inline
Definition at line 704 of file itkDiffusionTensor.hxx.
References itk::DiffusionTensor< TPrecision >::Log(), and utl::Log().
Referenced by itk::DiffusionTensor< TPrecision >::GeodesicDistance(), and itk::DiffusionTensor< TPrecision >::GetMD().
template<class TPrecision> bool itk::DiffusionTensor< TPrecision >::operator!= (const Self & mat) const inline
Definition at line 88 of file itkDiffusionTensor.h.
References itk::DiffusionTensor< TPrecision >::operator==().
template<class TPrecision > DiffusionTensor< TPrecision >::ValueType & itk::DiffusionTensor< TPrecision >::operator() (unsigned int row, unsigned int col)
access matrix values, which is similar with the ones in DiffusionTensor3D, but with boundary check.
Matrix notation access to elements
Definition at line 64 of file itkDiffusionTensor.hxx.
References itk::DiffusionTensor< TPrecision >::GetEigenValuesVectors(), and utlAssert.
Referenced by itk::DiffusionTensor< TPrecision >::operator()(), and itk::DiffusionTensor< TPrecision >::operator*().
template<class TPrecision > const DiffusionTensor< TPrecision >::ValueType & itk::DiffusionTensor< TPrecision >::operator() (unsigned int row, unsigned int col) const
Matrix notation access to elements
Definition at line 40 of file itkDiffusionTensor.hxx.
References itk::DiffusionTensor< TPrecision >::operator()(), and utlAssert.
template<class TPrecision> Self itk::DiffusionTensor< TPrecision >::operator* (const Self & A) const inline
Definition at line 127 of file itkDiffusionTensor.h.
References itk::DiffusionTensor< TPrecision >::GetVnlMatrix(), and itk::DiffusionTensor< TPrecision >::SetVnlMatrix().
template<class TPrecision> vnl_matrix<TPrecision> itk::DiffusionTensor< TPrecision >::operator* (const vnl_matrix< TPrecision > & A) const inline
Definition at line 133 of file itkDiffusionTensor.h.
References itk::DiffusionTensor< TPrecision >::GetVnlMatrix().
template<class TPrecision> VectorType itk::DiffusionTensor< TPrecision >::operator* (const VectorType & v) const inline
Tensor multiplication by a vector - returns a vector
Definition at line 139 of file itkDiffusionTensor.h.
References itk::DiffusionTensor< TPrecision >::NDimension, and itk::DiffusionTensor< TPrecision >::operator()().
template<class TPrecision> Self itk::DiffusionTensor< TPrecision >::operator+ (const Self & mat) const inline
Definition at line 119 of file itkDiffusionTensor.h.
References itk::DiffusionTensor< TPrecision >::NDimension.
template<class TPrecision> Self itk::DiffusionTensor< TPrecision >::operator- (const Self & mat) const inline
Definition at line 112 of file itkDiffusionTensor.h.
References itk::DiffusionTensor< TPrecision >::NDimension.
template<class TPrecision> template<class TMatrixType > Self& itk::DiffusionTensor< TPrecision >::operator= (const TMatrixType & mat) inline
Definition at line 104 of file itkDiffusionTensor.h.
References itk::DiffusionTensor< TPrecision >::NDimension.
template<class TPrecision> bool itk::DiffusionTensor< TPrecision >::operator== (const Self & mat) const inline
Definition at line 79 of file itkDiffusionTensor.h.
References itk::DiffusionTensor< TPrecision >::NDegreesOfFreedom.
Referenced by itk::DiffusionTensor< TPrecision >::operator!=().
template<class TPrecision > void itk::DiffusionTensor< TPrecision >::Positivize () const
Definition at line 487 of file itkDiffusionTensor.hxx.
References itk::DiffusionTensor< TPrecision >::IsZero().
Referenced by itk::DiffusionTensor< TPrecision >::GetMD(), and itk::DiffusionTensor< TPrecision >::IsPositive().
template<class TPrecision > DiffusionTensor< TPrecision > itk::DiffusionTensor< TPrecision >::Pow (const double & n) const inline
Power of the tensor
Definition at line 607 of file itkDiffusionTensor.hxx.
References spams::abs(), itk::DiffusionTensor< TPrecision >::Inv(), itk::DiffusionTensor< TPrecision >::SetVnlMatrix(), utlAssert, and utlException.
Referenced by itk::DiffusionTensor< TPrecision >::Exp(), and itk::DiffusionTensor< TPrecision >::GetMD().
template<class TPrecision> void itk::DiffusionTensor< TPrecision >::Print (std::ostream & os, Indent indent = 0) const inline
Definition at line 279 of file itkDiffusionTensor.h.
References itk::DiffusionTensor< TPrecision >::NDimension.
template<class TPrecision > DiffusionTensor< TPrecision > & itk::DiffusionTensor< TPrecision >::Rotate (const typename Self::MatrixType & mat) inline
Definition at line 272 of file itkDiffusionTensor.hxx.
References itk::DiffusionTensor< TPrecision >::GetRotate().
Referenced by itk::TensorBasisMatrixGenerator< TElement >::ComputeBasisMatrix(), itk::DiffusionTensor< TPrecision >::Flip(), itk::DWIGenerator< TOutputImage, TScalarImage >::GenerateData(), itk::DWISingleVoxelGenerator< TOutputImage, TScalarImage >::GenerateData(), and itk::DiffusionTensor< TPrecision >::SetVnlMatrix().
template<class TPrecision > template<class TArrayType > void itk::DiffusionTensor< TPrecision >::SetEigenValues (const TArrayType & array)
Definition at line 203 of file itkDiffusionTensor.hxx.
References itk::DiffusionTensor< TPrecision >::SetEigenVectors().
Referenced by itk::TensorBasisMatrixGenerator< TElement >::ComputeBasisMatrix(), itk::DiffusionTensor< TPrecision >::Flip(), itk::DWIGenerator< TOutputImage, TScalarImage >::GenerateData(), itk::DWISingleVoxelGenerator< TOutputImage, TScalarImage >::GenerateData(), and itk::DiffusionTensor< TPrecision >::GetEigenValuesVectorsAnalytic().
template<class TPrecision > template<class TMatrixType > void itk::DiffusionTensor< TPrecision >::SetEigenVectors (const TMatrixType & vectors)
Definition at line 225 of file itkDiffusionTensor.hxx.
References itk::DiffusionTensor< TPrecision >::GetVnlMatrix().
Referenced by itk::DiffusionTensor< TPrecision >::Flip(), and itk::DiffusionTensor< TPrecision >::SetEigenValues().
template<class TPrecision> void itk::DiffusionTensor< TPrecision >::SetVnlMatrix (const vnl_matrix< TPrecision > & mat) inline
Set a vnl_matrix_ref referencing the same memory block.
Definition at line 260 of file itkDiffusionTensor.hxx.
References itk::DiffusionTensor< TPrecision >::Rotate().
Referenced by itk::DiffusionTensor< TPrecision >::Exp(), itk::DiffusionTensor< TPrecision >::Flip(), itk::DiffusionTensor< TPrecision >::GetRotate(), itk::DiffusionTensor< TPrecision >::GetVnlMatrix(), itk::DiffusionTensor< TPrecision >::Log(), itk::DiffusionTensor< TPrecision >::operator*(), and itk::DiffusionTensor< TPrecision >::Pow().
template<class TPrecision > DiffusionTensor< TPrecision > itk::DiffusionTensor< TPrecision >::Sqrt (void) const inline
Definition at line 658 of file itkDiffusionTensor.hxx.
References itk::DiffusionTensor< TPrecision >::InvSqrt(), and utl::Pow().
Referenced by itk::DiffusionTensor< TPrecision >::GetMD(), and itk::DiffusionTensor< TPrecision >::Inv().
Member Data Documentation
template<class TPrecision> const unsigned int itk::DiffusionTensor< TPrecision >::NDegreesOfFreedom = NDimension*(NDimension+1)/2 static
Definition at line 55 of file itkDiffusionTensor.h.
Referenced by itk::DiffusionTensor< TPrecision >::IsSame(), and itk::DiffusionTensor< TPrecision >::operator==().
template<class TPrecision> const unsigned int itk::DiffusionTensor< TPrecision >::NDimension = 3 static
Definition at line 54 of file itkDiffusionTensor.h.
Referenced by itk::DiffusionTensor< TPrecision >::operator*(), itk::DiffusionTensor< TPrecision >::operator+(), itk::DiffusionTensor< TPrecision >::operator-(), itk::DiffusionTensor< TPrecision >::operator=(), and itk::DiffusionTensor< TPrecision >::Print().
The documentation for this class was generated from the following files:
Modules/DiffusionModels/include/itkDiffusionTensor.h
Modules/DiffusionModels/include/itkDiffusionTensor.hxx