DMRITool: spams::FISTA::Loss< T, D, E > Class Template Reference
spams::FISTA::Loss< T, D, E > Class Template Reference abstract
#include <fista.h>
Detailed Description
template<typename T, typename D = Vector<T>, typename E = Vector<T>>
class spams::FISTA::Loss< T, D, E >
Definition at line 268 of file fista.h.
Public Member Functions
virtual T eval (const D &input) const =0
virtual T fenchel (const D &input) const =0
virtual void grad (const D &input, D &output) const =0
virtual void init (const E &input)=0
virtual bool is_fenchel () const
Loss ()
virtual bool test_backtracking (const D &y, const D &grad, const D &prox, const T L) const
virtual void var_fenchel (const D &x, D &grad1, D &grad2, const bool intercept=false) const =0
virtual ~Loss ()
Private Member Functions
Loss (const Loss< T, D, E > &dict)
Loss< T, D, E > & operator= (const Loss< T, D, E > &dict)
Constructor & Destructor Documentation
template<typename T, typename D = Vector<T>, typename E = Vector<T>> spams::FISTA::Loss< T, D, E >::Loss () inline
Definition at line 270 of file fista.h.
template<typename T, typename D = Vector<T>, typename E = Vector<T>> virtual spams::FISTA::Loss< T, D, E >::~Loss () inline virtual
Definition at line 271 of file fista.h.
template<typename T, typename D = Vector<T>, typename E = Vector<T>> spams::FISTA::Loss< T, D, E >::Loss (const Loss< T, D, E > & dict) explicit private
Member Function Documentation
template<typename T, typename D = Vector<T>, typename E = Vector<T>> virtual T spams::FISTA::Loss< T, D, E >::eval (const D & input) const pure virtual
Implemented in spams::FISTA::LossMatSup< T, L >, spams::FISTA::LossMatSup< T, LogLoss< T, weighted > >, spams::FISTA::LossMatSup< T, SqLossMissing< T > >, spams::FISTA::SqLossMat< T >, spams::FISTA::LossCur< T >, spams::FISTA::MultiLogLoss< T >, spams::FISTA::LogLoss< T, weighted >, spams::FISTA::SqLoss< T >, and spams::FISTA::SqLossMissing< T >.
Referenced by spams::FISTA::duality_gap(), spams::FISTA::FISTA_Generic(), spams::FISTA::ISTA_Generic(), and spams::FISTA::subGradientDescent_Generic().
template<typename T, typename D = Vector<T>, typename E = Vector<T>> virtual T spams::FISTA::Loss< T, D, E >::fenchel (const D & input) const pure virtual
Implemented in spams::FISTA::LossMatSup< T, L >, spams::FISTA::LossMatSup< T, LogLoss< T, weighted > >, spams::FISTA::LossMatSup< T, SqLossMissing< T > >, spams::FISTA::SqLossMat< T >, spams::FISTA::LossCur< T >, spams::FISTA::MultiLogLoss< T >, spams::FISTA::LogLoss< T, weighted >, spams::FISTA::SqLoss< T >, and spams::FISTA::SqLossMissing< T >.
Referenced by spams::FISTA::duality_gap().
template<typename T, typename D = Vector<T>, typename E = Vector<T>> virtual void spams::FISTA::Loss< T, D, E >::grad (const D & input, D & output) const pure virtual
Implemented in spams::FISTA::LossMatSup< T, L >, spams::FISTA::LossMatSup< T, LogLoss< T, weighted > >, spams::FISTA::LossMatSup< T, SqLossMissing< T > >, spams::FISTA::SqLossMat< T >, spams::FISTA::LossCur< T >, spams::FISTA::MultiLogLoss< T >, spams::FISTA::LogLoss< T, weighted >, spams::FISTA::SqLoss< T >, and spams::FISTA::SqLossMissing< T >.
Referenced by spams::FISTA::FISTA_Generic(), spams::FISTA::ISTA_Generic(), and spams::FISTA::subGradientDescent_Generic().
template<typename T, typename D = Vector<T>, typename E = Vector<T>> virtual void spams::FISTA::Loss< T, D, E >::init (const E & input) pure virtual
Implemented in spams::FISTA::LossMatSup< T, L >, spams::FISTA::LossMatSup< T, LogLoss< T, weighted > >, spams::FISTA::LossMatSup< T, SqLossMissing< T > >, spams::FISTA::SqLossMat< T >, spams::FISTA::LossCur< T >, spams::FISTA::MultiLogLoss< T >, spams::FISTA::LogLoss< T, weighted >, spams::FISTA::SqLoss< T >, and spams::FISTA::SqLossMissing< T >.
Referenced by spams::FISTA::solver().
template<typename T, typename D = Vector<T>, typename E = Vector<T>> virtual bool spams::FISTA::Loss< T, D, E >::is_fenchel () const inline virtual
Reimplemented in spams::FISTA::LossMatSup< T, L >, spams::FISTA::LossMatSup< T, LogLoss< T, weighted > >, spams::FISTA::LossMatSup< T, SqLossMissing< T > >, and spams::FISTA::LogLoss< T, weighted >.
Definition at line 283 of file fista.h.
Referenced by spams::FISTA::duality_gap(), spams::FISTA::FISTA_Generic(), spams::FISTA::ISTA_Generic(), spams::FISTA::solver(), and spams::FISTA::subGradientDescent_Generic().
template<typename T, typename D = Vector<T>, typename E = Vector<T>> Loss<T,D,E>& spams::FISTA::Loss< T, D, E >::operator= (const Loss< T, D, E > & dict) private
template<typename T, typename D = Vector<T>, typename E = Vector<T>> virtual bool spams::FISTA::Loss< T, D, E >::test_backtracking (const D & y, const D & grad, const D & prox, const T L) const inline virtual
Reimplemented in spams::FISTA::SqLossMat< T >, and spams::FISTA::SqLoss< T >.
Definition at line 276 of file fista.h.
Referenced by spams::FISTA::FISTA_Generic(), and spams::FISTA::ISTA_Generic().
template<typename T, typename D = Vector<T>, typename E = Vector<T>> virtual void spams::FISTA::Loss< T, D, E >::var_fenchel (const D & x, D & grad1, D & grad2, const bool intercept = false) const pure virtual
Implemented in spams::FISTA::LossMatSup< T, L >, spams::FISTA::LossMatSup< T, LogLoss< T, weighted > >, spams::FISTA::LossMatSup< T, SqLossMissing< T > >, spams::FISTA::SqLossMat< T >, spams::FISTA::LossCur< T >, spams::FISTA::MultiLogLoss< T >, spams::FISTA::LogLoss< T, weighted >, spams::FISTA::SqLoss< T >, and spams::FISTA::SqLossMissing< T >.
Referenced by spams::FISTA::duality_gap().
The documentation for this class was generated from the following file:
ThirdParty/Spams/include/fista.h