DMRITool: itk::SphericalPolarFourierImageFilter< TInputImage, TOutputImage > Class Template Reference
itk::SphericalPolarFourierImageFilter< TInputImage, TOutputImage > Class Template Reference
DiffusionModels
#include <itkSphericalPolarFourierImageFilter.h>
Detailed Description
template<class TInputImage, class TOutputImage>
class itk::SphericalPolarFourierImageFilter< TInputImage, TOutputImage >
estimate the coefficients in SPF model
Author
Jian Cheng (JC), jian..nosp@m.chen.nosp@m.g.198.nosp@m.3@gm.nosp@m.ail.c.nosp@m.om
Definition at line 36 of file itkSphericalPolarFourierImageFilter.h.
Public Types
typedef SmartPointer< const Self > ConstPointer
typedef Superclass::EstimationType EstimationType
typedef Superclass::L1FISTASolverType L1FISTASolverType
typedef Superclass::L2SolverType L2SolverType
typedef Superclass::MatrixPointer MatrixPointer
typedef Superclass::MatrixType MatrixType
typedef SmartPointer< Self > Pointer
typedef Superclass::SamplingSchemeQSpacePointer SamplingSchemeQSpacePointer
typedef Superclass::SamplingSchemeQSpaceType SamplingSchemeQSpaceType
typedef SphericalPolarFourierImageFilter Self
typedef SphericalPolarFourierRadialGenerator< double > SPFGenerator
typedef Superclass::STDVectorPointer STDVectorPointer
typedef Superclass::STDVectorType STDVectorType
typedef SphericalPolarFourierEstimationImageFilter< TInputImage, TOutputImage > Superclass
typedef Superclass::VectorPointer VectorPointer
typedef Superclass::VectorType VectorType
Public Types inherited from itk::SphericalPolarFourierEstimationImageFilter< TInputImage, TOutputImage >
typedef SmartPointer< const Self > ConstPointer
enum EstimationType {
LS =0,
L1_2,
L1_DL
}
typedef L1RegularizedLeastSquaresFISTASolver< double > L1FISTASolverType
enum L1SolverType {
FISTA_LS =0,
SPAMS
}
typedef SpamsWeightedLassoSolver< double > L1SpamsSolverType
typedef L2RegularizedLeastSquaresSolver< double > L2SolverType
typedef Superclass::MatrixPointer MatrixPointer
typedef Superclass::MatrixType MatrixType
typedef SmartPointer< Self > Pointer
typedef SphericalPolarFourierEstimationImageFilter Self
typedef Superclass::STDVectorPointer STDVectorPointer
typedef Superclass::STDVectorType STDVectorType
typedef DiffusionModelEstimationInSphericalCoordinateImageFilter< TInputImage, TOutputImage > Superclass
typedef Superclass::VectorPointer VectorPointer
typedef Superclass::VectorType VectorType
Public Types inherited from itk::DiffusionModelEstimationInSphericalCoordinateImageFilter< TInputImage, TOutputImage >
typedef SmartPointer< const Self > ConstPointer
typedef Superclass::InputImageConstPointer InputImageConstPointer
typedef Superclass::InputImageIndexType InputImageIndexType
typedef Superclass::InputImagePixelType InputImagePixelType
typedef Superclass::InputImagePointer InputImagePointer
typedef Superclass::InputImageRegionType InputImageRegionType
typedef Superclass::InputImageSizeType InputImageSizeType
typedef Superclass::InputImageSpacingType InputImageSpacingType
typedef Superclass::InputImageType InputImageType
typedef Superclass::MaskImageType MaskImageType
typedef Superclass::MatrixPointer MatrixPointer
typedef Superclass::MatrixType MatrixType
typedef Superclass::OutputImageIndexType OutputImageIndexType
typedef Superclass::OutputImagePixelType OutputImagePixelType
typedef Superclass::OutputImagePointer OutputImagePointer
typedef Superclass::OutputImageRegionType OutputImageRegionType
typedef Superclass::OutputImageSizeType OutputImageSizeType
typedef Superclass::OutputImageSpacingType OutputImageSpacingType
typedef Superclass::OutputImageType OutputImageType
typedef SmartPointer< Self > Pointer
typedef DiffusionModelEstimationInSphericalCoordinateImageFilter Self
typedef Superclass::STDVectorPointer STDVectorPointer
typedef Superclass::STDVectorType STDVectorType
typedef DiffusionModelEstimationImageFilter< TInputImage, TOutputImage > Superclass
typedef Superclass::VectorPointer VectorPointer
typedef Superclass::VectorType VectorType
Public Types inherited from itk::DiffusionModelEstimationImageFilter< TInputImage, TOutputImage >
typedef SmartPointer< const Self > ConstPointer
typedef utl_shared_ptr< MatrixType > MatrixPointer
typedef utl::NDArray< double, 2 > MatrixType
typedef SmartPointer< Self > Pointer
typedef SamplingSchemeQSpaceType::Pointer SamplingSchemeQSpacePointer
typedef SamplingSchemeQSpace< double > SamplingSchemeQSpaceType
typedef SamplingSchemeRSpaceType::Pointer SamplingSchemeRSpacePointer
typedef SamplingScheme3D< double > SamplingSchemeRSpaceType
typedef DiffusionModelEstimationImageFilter Self
typedef utl_shared_ptr< STDVectorType > STDVectorPointer
typedef std::vector< double > STDVectorType
typedef MaskedImageToImageFilter< TInputImage, TOutputImage > Superclass
typedef utl_shared_ptr< VectorType > VectorPointer
typedef utl::NDArray< double, 1 > VectorType
Public Types inherited from itk::MaskedImageToImageFilter< TInputImage, TOutputImage >
typedef SmartPointer< const Self > ConstPointer
typedef InputImageType::ConstPointer InputImageConstPointer
typedef InputImageType::IndexType InputImageIndexType
typedef InputImageType::PixelType InputImagePixelType
typedef InputImageType::Pointer InputImagePointer
typedef InputImageType::RegionType InputImageRegionType
typedef InputImageType::SizeType InputImageSizeType
typedef InputImageType::SpacingType InputImageSpacingType
typedef TInputImage InputImageType
typedef LoggerType::Pointer LoggerPointer
typedef ThreadLogger LoggerType
typedef utl_shared_ptr< LoggerVectorType > LoggerVectorPointer
typedef std::vector< LoggerPointer > LoggerVectorType
typedef MaskImageType::Pointer MaskImagePointer
typedef Image< double, 3 > MaskImageType
typedef OutputImageType::IndexType OutputImageIndexType
typedef OutputImageType::PixelType OutputImagePixelType
typedef OutputImageType::Pointer OutputImagePointer
typedef OutputImageType::RegionType OutputImageRegionType
typedef OutputImageType::SizeType OutputImageSizeType
typedef OutputImageType::SpacingType OutputImageSpacingType
typedef TOutputImage OutputImageType
typedef SmartPointer< Self > Pointer
typedef MaskedImageToImageFilter Self
typedef ImageToImageFilter< TInputImage, TOutputImage > Superclass
Public Member Functions
void ComputeBasisMatrix () ITK_OVERRIDE
void ComputeRadialMatrix () ITK_OVERRIDE
void ComputeRadialVectorForE0InBasis ()
void ComputeRadialVectorForE0InDWI ()
void ComputeRegularizationWeight () ITK_OVERRIDE
double ComputeScale (const bool setScale=true) ITK_OVERRIDE
virtual ::itk::LightObject::Pointer CreateAnother (void) const
std::vector< int > DimToRank (const int dimm) const ITK_OVERRIDE
virtual STDVectorPointer GetGn0 ()
int GetIndexJ (const int n, const int l, const int m) const ITK_OVERRIDE
std::vector< int > GetIndexNLM (const int index) const ITK_OVERRIDE
virtual const char * GetNameOfClass () const
itkTypedefMaskedImageToImageMacro (Superclass)
int RankToDim (const bool is_radial=false, const int radialRank=-1, const int shRank=-1) const ITK_OVERRIDE
void SetBasisScale (const double scale) ITK_OVERRIDE
Public Member Functions inherited from itk::SphericalPolarFourierEstimationImageFilter< TInputImage, TOutputImage >
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual double GetB0Weight ()
virtual MatrixPointer GetBasisCombinationMatrix ()
virtual VectorPointer GetBasisEnergyDL ()
virtual double GetBasisEnergyPowerDL ()
virtual double GetBasisScale ()
virtual EstimationType GetEstimationType ()
virtual bool GetIsOriginalBasis ()
virtual L1SolverType GetL1SolverType ()
virtual double GetLambdaL1 ()
virtual double GetLambdaRadial ()
virtual double GetLambdaSpherical ()
virtual const ScalarImageType * GetMDImage () const
virtual VectorPointer GetRegularizationWeight ()
virtual const ScalarImageType * GetScaleImage () const
bool IsAdaptiveScale () const
virtual void IsOriginalBasisOff ()
virtual void IsOriginalBasisOn ()
itkGetObjectMacro (MDImage, ScalarImageType)
itkGetObjectMacro (ScaleImage, ScalarImageType)
itkSetGetBooleanMacro (IsAnalyticalB0)
itkTypedefMaskedImageToImageMacro (Superclass)
virtual void SetB0Weight (double _arg)
virtual void SetBasisCombinationMatrix (MatrixPointer _arg)
virtual void SetBasisEnergyDL (VectorPointer _arg)
virtual void SetBasisEnergyPowerDL (double _arg)
virtual void SetEstimationType (EstimationType _arg)
virtual void SetIsOriginalBasis (bool _arg)
virtual void SetL1FISTASolver (typename L1FISTASolverType::Pointer _arg)
virtual void SetL1SolverType (L1SolverType _arg)
virtual void SetL1SpamsSolver (typename L1SpamsSolverType::Pointer _arg)
virtual void SetLambdaL1 (double _arg)
virtual void SetLambdaRadial (double _arg)
virtual void SetLambdaSpherical (double _arg)
virtual void SetMDImage (ScalarImageType *_arg)
virtual void SetScaleImage (ScalarImageType *_arg)
Public Member Functions inherited from itk::DiffusionModelEstimationInSphericalCoordinateImageFilter< TInputImage, TOutputImage >
virtual void ComputeSHMatrix ()
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual MatrixPointer GetBasisRadialMatrix ()
virtual MatrixPointer GetBasisSHMatrix ()
virtual int GetRadialRank ()
virtual int GetSHRank ()
virtual void SetRadialRank (int _arg)
virtual void SetSHRank (int _arg)
Public Member Functions inherited from itk::DiffusionModelEstimationImageFilter< TInputImage, TOutputImage >
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual MatrixPointer GetBasisMatrix ()
virtual double GetMD0 ()
itkGetObjectMacro (SamplingSchemeQSpace, SamplingSchemeQSpaceType)
itkTypedefMaskedImageToImageMacro (Superclass)
virtual void SetMD0 (double _arg)
virtual void SetSamplingSchemeQSpace (SamplingSchemeQSpaceType *_arg)
Public Member Functions inherited from itk::MaskedImageToImageFilter< TInputImage, TOutputImage >
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual const LoggerType * GetLogger () const
virtual const MaskImageType * GetMaskImage () const
bool IsMaskUsed ()
itkGetObjectMacro (MaskImage, MaskImageType)
itkGetObjectMacro (Logger, LoggerType)
itkSetGetMacro (LogLevel, int)
virtual void SetLogger (LoggerType *_arg)
virtual void SetMaskImage (MaskImageType *_arg)
void SetMaskImage (const std::string &file)
Static Public Member Functions
static Pointer New ()
Static Public Member Functions inherited from itk::SphericalPolarFourierEstimationImageFilter< TInputImage, TOutputImage >
static Pointer New ()
Static Public Member Functions inherited from itk::DiffusionModelEstimationInSphericalCoordinateImageFilter< TInputImage, TOutputImage >
static Pointer New ()
Static Public Member Functions inherited from itk::DiffusionModelEstimationImageFilter< TInputImage, TOutputImage >
static Pointer New ()
Static Public Member Functions inherited from itk::MaskedImageToImageFilter< TInputImage, TOutputImage >
static Pointer New ()
Protected Member Functions
void BeforeThreadedGenerateData () ITK_OVERRIDE
void ComputeBasisMatrixForB0 ()
LightObject::Pointer InternalClone () const ITK_OVERRIDE
void PrintSelf (std::ostream &os, Indent indent) const ITK_OVERRIDE
SphericalPolarFourierImageFilter ()
void ThreadedGenerateData (const OutputImageRegionType &outputRegionForThread, ThreadIdType threadId) ITK_OVERRIDE
virtual ~SphericalPolarFourierImageFilter ()
Protected Member Functions inherited from itk::SphericalPolarFourierEstimationImageFilter< TInputImage, TOutputImage >
void BeforeThreadedGenerateData () ITK_OVERRIDE
void GenerateOutputInformation () ITK_OVERRIDE
void InitializeThreadedLibraries () ITK_OVERRIDE
LightObject::Pointer InternalClone () const ITK_OVERRIDE
SphericalPolarFourierEstimationImageFilter ()
void VerifyInputParameters () const ITK_OVERRIDE
virtual ~SphericalPolarFourierEstimationImageFilter ()
Protected Member Functions inherited from itk::DiffusionModelEstimationInSphericalCoordinateImageFilter< TInputImage, TOutputImage >
DiffusionModelEstimationInSphericalCoordinateImageFilter ()
LightObject::Pointer InternalClone () const ITK_OVERRIDE
virtual ~DiffusionModelEstimationInSphericalCoordinateImageFilter ()
Protected Member Functions inherited from itk::DiffusionModelEstimationImageFilter< TInputImage, TOutputImage >
DiffusionModelEstimationImageFilter ()
LightObject::Pointer InternalClone () const ITK_OVERRIDE
virtual ~DiffusionModelEstimationImageFilter ()
Protected Member Functions inherited from itk::MaskedImageToImageFilter< TInputImage, TOutputImage >
void CreateLoggerVector ()
LightObject::Pointer InternalClone () const ITK_OVERRIDE
MaskedImageToImageFilter ()
std::string ThreadIDToString () const
virtual void VerifyMaskInformation () const
void WriteLogger (const std::string &str, const LoggerBase::PriorityLevelType level=LoggerBase::DEBUG) const
virtual ~MaskedImageToImageFilter ()
Protected Attributes
VectorPointer m_G0DWI
STDVectorPointer m_Gn0
Protected Attributes inherited from itk::SphericalPolarFourierEstimationImageFilter< TInputImage, TOutputImage >
double m_B0Weight
MatrixPointer m_BasisCombinationMatrix
VectorPointer m_BasisEnergyDL
double m_BasisEnergyPowerDL
MatrixPointer m_BasisMatrixForB0
double m_BasisScale
EstimationType m_EstimationType
bool m_IsAnalyticalB0
bool m_IsOriginalBasis
L1FISTASolverType::Pointer m_L1FISTASolver
L1SolverType m_L1SolverType
L1SpamsSolverType::Pointer m_L1SpamsSolver
L2SolverType::Pointer m_L2Solver
double m_LambdaL1
double m_LambdaL2
double m_LambdaRadial
double m_LambdaSpherical
ScalarImageType::Pointer m_MDImage
ScalarImageType::Pointer m_ScaleImage
Protected Attributes inherited from itk::DiffusionModelEstimationInSphericalCoordinateImageFilter< TInputImage, TOutputImage >
MatrixPointer m_BasisRadialMatrix
MatrixPointer m_BasisSHMatrix
int m_RadialRank
int m_SHRank
Protected Attributes inherited from itk::DiffusionModelEstimationImageFilter< TInputImage, TOutputImage >
MatrixPointer m_BasisMatrix
double m_MD0
VectorPointer m_RegularizationWeight
SamplingSchemeQSpacePointer m_SamplingSchemeQSpace
Protected Attributes inherited from itk::MaskedImageToImageFilter< TInputImage, TOutputImage >
LoggerPointer m_Logger
LoggerVectorPointer m_LoggerVector
int m_LogLevel
MaskImagePointer m_MaskImage
int m_ThreadID
Private Member Functions
void operator= (const Self &)
SphericalPolarFourierImageFilter (const Self &)
Additional Inherited Members
Static Public Attributes inherited from itk::MaskedImageToImageFilter< TInputImage, TOutputImage >
static const unsigned int InputImageDimension
static const unsigned int OutputImageDimension
Member Typedef Documentation
template<class TInputImage , class TOutputImage > typedef SmartPointer<const Self> itk::SphericalPolarFourierImageFilter< TInputImage, TOutputImage >::ConstPointer
Definition at line 44 of file itkSphericalPolarFourierImageFilter.h.
template<class TInputImage , class TOutputImage > typedef Superclass::EstimationType itk::SphericalPolarFourierImageFilter< TInputImage, TOutputImage >::EstimationType
Definition at line 63 of file itkSphericalPolarFourierImageFilter.h.
template<class TInputImage , class TOutputImage > typedef Superclass::L1FISTASolverType itk::SphericalPolarFourierImageFilter< TInputImage, TOutputImage >::L1FISTASolverType
Definition at line 62 of file itkSphericalPolarFourierImageFilter.h.
template<class TInputImage , class TOutputImage > typedef Superclass::L2SolverType itk::SphericalPolarFourierImageFilter< TInputImage, TOutputImage >::L2SolverType
Definition at line 61 of file itkSphericalPolarFourierImageFilter.h.
template<class TInputImage , class TOutputImage > typedef Superclass::MatrixPointer itk::SphericalPolarFourierImageFilter< TInputImage, TOutputImage >::MatrixPointer
Definition at line 56 of file itkSphericalPolarFourierImageFilter.h.
template<class TInputImage , class TOutputImage > typedef Superclass::MatrixType itk::SphericalPolarFourierImageFilter< TInputImage, TOutputImage >::MatrixType
Definition at line 54 of file itkSphericalPolarFourierImageFilter.h.
template<class TInputImage , class TOutputImage > typedef SmartPointer<Self> itk::SphericalPolarFourierImageFilter< TInputImage, TOutputImage >::Pointer
Definition at line 43 of file itkSphericalPolarFourierImageFilter.h.
template<class TInputImage , class TOutputImage > typedef Superclass::SamplingSchemeQSpacePointer itk::SphericalPolarFourierImageFilter< TInputImage, TOutputImage >::SamplingSchemeQSpacePointer
Definition at line 67 of file itkSphericalPolarFourierImageFilter.h.
template<class TInputImage , class TOutputImage > typedef Superclass::SamplingSchemeQSpaceType itk::SphericalPolarFourierImageFilter< TInputImage, TOutputImage >::SamplingSchemeQSpaceType
Definition at line 68 of file itkSphericalPolarFourierImageFilter.h.
template<class TInputImage , class TOutputImage > typedef SphericalPolarFourierImageFilter itk::SphericalPolarFourierImageFilter< TInputImage, TOutputImage >::Self
Standard class typedefs.
Definition at line 41 of file itkSphericalPolarFourierImageFilter.h.
template<class TInputImage , class TOutputImage > typedef SphericalPolarFourierRadialGenerator<double> itk::SphericalPolarFourierImageFilter< TInputImage, TOutputImage >::SPFGenerator
Definition at line 65 of file itkSphericalPolarFourierImageFilter.h.
template<class TInputImage , class TOutputImage > typedef Superclass::STDVectorPointer itk::SphericalPolarFourierImageFilter< TInputImage, TOutputImage >::STDVectorPointer
Definition at line 59 of file itkSphericalPolarFourierImageFilter.h.
template<class TInputImage , class TOutputImage > typedef Superclass::STDVectorType itk::SphericalPolarFourierImageFilter< TInputImage, TOutputImage >::STDVectorType
Definition at line 58 of file itkSphericalPolarFourierImageFilter.h.
template<class TInputImage , class TOutputImage > typedef SphericalPolarFourierEstimationImageFilter<TInputImage,TOutputImage> itk::SphericalPolarFourierImageFilter< TInputImage, TOutputImage >::Superclass
Definition at line 42 of file itkSphericalPolarFourierImageFilter.h.
template<class TInputImage , class TOutputImage > typedef Superclass::VectorPointer itk::SphericalPolarFourierImageFilter< TInputImage, TOutputImage >::VectorPointer
Definition at line 57 of file itkSphericalPolarFourierImageFilter.h.
template<class TInputImage , class TOutputImage > typedef Superclass::VectorType itk::SphericalPolarFourierImageFilter< TInputImage, TOutputImage >::VectorType
Definition at line 55 of file itkSphericalPolarFourierImageFilter.h.
Constructor & Destructor Documentation
template<class TInputImage , class TOutputImage > itk::SphericalPolarFourierImageFilter< TInputImage, TOutputImage >::SphericalPolarFourierImageFilter () protected
Definition at line 34 of file itkSphericalPolarFourierImageFilter.hxx.
References itk::SphericalPolarFourierImageFilter< TInputImage, TOutputImage >::SetBasisScale().
template<class TInputImage , class TOutputImage > virtual itk::SphericalPolarFourierImageFilter< TInputImage, TOutputImage >::~SphericalPolarFourierImageFilter () inline protected virtual
Definition at line 91 of file itkSphericalPolarFourierImageFilter.h.
References ITK_OVERRIDE.
template<class TInputImage , class TOutputImage > itk::SphericalPolarFourierImageFilter< TInputImage, TOutputImage >::SphericalPolarFourierImageFilter (const Self &) private
Member Function Documentation
template<class TInputImage , class TOutputImage > void itk::SphericalPolarFourierImageFilter< TInputImage, TOutputImage >::BeforeThreadedGenerateData () protected
Definition at line 575 of file itkSphericalPolarFourierImageFilter.hxx.
References utl::ConnectUtlMatrix(), utl::CreateExpandedPath(), utl::InitializeThreadedLibraries(), itkShowPositionThreadedLogger, utl::LearnedSPFDictionary_SH8_RA4_K250, utl::PrintUtlMatrix(), utl::PrintUtlVector(), utl::ProductUtlMM(), utl::ReadMatrix(), itk::SphericalPolarFourierImageFilter< TInputImage, TOutputImage >::ThreadedGenerateData(), utlException, and utlGlobalException.
Referenced by itk::SphericalPolarFourierImageFilter< TInputImage, TOutputImage >::ComputeRegularizationWeight().
template<class TInputImage , class TOutputImage > void itk::SphericalPolarFourierImageFilter< TInputImage, TOutputImage >::ComputeBasisMatrix () virtual
compute basis matrix which incorporates radial matrix and spherical matrix
Reimplemented from itk::DiffusionModelEstimationImageFilter< TInputImage, TOutputImage >.
Definition at line 330 of file itkSphericalPolarFourierImageFilter.hxx.
References itk::SphericalPolarFourierImageFilter< TInputImage, TOutputImage >::ComputeBasisMatrixForB0(), utl::ComputeSHMatrix(), itkShowPositionThreadedLogger, utl::PrintUtlMatrix(), and utlException.
Referenced by itk::SphericalPolarFourierImageFilter< TInputImage, TOutputImage >::ComputeRadialMatrix().
template<class TInputImage , class TOutputImage > void itk::SphericalPolarFourierImageFilter< TInputImage, TOutputImage >::ComputeBasisMatrixForB0 () protected
Definition at line 476 of file itkSphericalPolarFourierImageFilter.hxx.
References CARTESIAN_TO_CARTESIAN, itk::SphericalPolarFourierImageFilter< TInputImage, TOutputImage >::ComputeRegularizationWeight(), DIRECTION_NODUPLICATE, and itkShowPositionThreadedLogger.
Referenced by itk::SphericalPolarFourierImageFilter< TInputImage, TOutputImage >::ComputeBasisMatrix().
template<class TInputImage , class TOutputImage > void itk::SphericalPolarFourierImageFilter< TInputImage, TOutputImage >::ComputeRadialMatrix () virtual
compute radial matrix
Reimplemented from itk::DiffusionModelEstimationInSphericalCoordinateImageFilter< TInputImage, TOutputImage >.
Definition at line 221 of file itkSphericalPolarFourierImageFilter.hxx.
References itk::SphericalPolarFourierImageFilter< TInputImage, TOutputImage >::ComputeBasisMatrix(), itkShowPositionThreadedLogger, utl::PrintUtlMatrix(), and utlGlobalException.
Referenced by itk::SphericalPolarFourierImageFilter< TInputImage, TOutputImage >::ComputeRadialVectorForE0InDWI().
template<class TInputImage , class TOutputImage > void itk::SphericalPolarFourierImageFilter< TInputImage, TOutputImage >::ComputeRadialVectorForE0InBasis ()
Definition at line 173 of file itkSphericalPolarFourierImageFilter.hxx.
References itk::SphericalPolarFourierImageFilter< TInputImage, TOutputImage >::ComputeRadialVectorForE0InDWI(), and itkShowPositionThreadedLogger.
Referenced by itk::SphericalPolarFourierImageFilter< TInputImage, TOutputImage >::RankToDim().
template<class TInputImage , class TOutputImage > void itk::SphericalPolarFourierImageFilter< TInputImage, TOutputImage >::ComputeRadialVectorForE0InDWI ()
Definition at line 190 of file itkSphericalPolarFourierImageFilter.hxx.
References itk::SphericalPolarFourierImageFilter< TInputImage, TOutputImage >::ComputeRadialMatrix(), and itkShowPositionThreadedLogger.
Referenced by itk::SphericalPolarFourierImageFilter< TInputImage, TOutputImage >::ComputeRadialVectorForE0InBasis().
template<class TInputImage , class TOutputImage > void itk::SphericalPolarFourierImageFilter< TInputImage, TOutputImage >::ComputeRegularizationWeight () virtual
Reimplemented from itk::DiffusionModelEstimationImageFilter< TInputImage, TOutputImage >.
Definition at line 496 of file itkSphericalPolarFourierImageFilter.hxx.
References spams::abs(), itk::SphericalPolarFourierImageFilter< TInputImage, TOutputImage >::BeforeThreadedGenerateData(), utl::CreateExpandedPath(), itkShowPositionThreadedLogger, utl::LearnedSPFDictionary_SH8_RA4_K250, utl::LearnedSPFEnergy_SH8_RA4_K250, utl::PowerVector(), utl::PrintUtlMatrix(), utl::PrintUtlVector(), utl::ReadMatrix(), utl::ReadVector(), utl::StdVectorToUtlVector(), and utlException.
Referenced by itk::SphericalPolarFourierImageFilter< TInputImage, TOutputImage >::ComputeBasisMatrixForB0().
template<class TInputImage , class TOutputImage > double itk::SphericalPolarFourierImageFilter< TInputImage, TOutputImage >::ComputeScale (const bool setScale = true) virtual
need to be overidden by subclasses
Reimplemented from itk::SphericalPolarFourierEstimationImageFilter< TInputImage, TOutputImage >.
Definition at line 88 of file itkSphericalPolarFourierImageFilter.hxx.
References itk::SphericalPolarFourierImageFilter< TInputImage, TOutputImage >::GetIndexNLM(), itkShowPositionThreadedLogger, and M_PI.
Referenced by itk::SphericalPolarFourierImageFilter< TInputImage, TOutputImage >::InternalClone().
template<class TInputImage , class TOutputImage > virtual::itk::LightObject::Pointer itk::SphericalPolarFourierImageFilter< TInputImage, TOutputImage >::CreateAnother (void) const
template<class TInputImage , class TOutputImage > std::vector< int > itk::SphericalPolarFourierImageFilter< TInputImage, TOutputImage >::DimToRank (const int dimm) const virtual
from dimension to rank
Reimplemented from itk::SphericalPolarFourierEstimationImageFilter< TInputImage, TOutputImage >.
Definition at line 135 of file itkSphericalPolarFourierImageFilter.hxx.
References itk::SphericalPolarFourierImageFilter< TInputImage, TOutputImage >::RankToDim(), and utlException.
Referenced by itk::SphericalPolarFourierImageFilter< TInputImage, TOutputImage >::GetIndexJ().
template<class TInputImage , class TOutputImage > virtual STDVectorPointer itk::SphericalPolarFourierImageFilter< TInputImage, TOutputImage >::GetGn0 () virtual
template<class TInputImage , class TOutputImage > int itk::SphericalPolarFourierImageFilter< TInputImage, TOutputImage >::GetIndexJ (const int n, const int l, const int m) const virtual
Reimplemented from itk::SphericalPolarFourierEstimationImageFilter< TInputImage, TOutputImage >.
Definition at line 127 of file itkSphericalPolarFourierImageFilter.hxx.
References itk::SphericalPolarFourierImageFilter< TInputImage, TOutputImage >::DimToRank(), and utl::GetIndexSHj().
Referenced by itk::SphericalPolarFourierImageFilter< TInputImage, TOutputImage >::GetIndexNLM().
template<class TInputImage , class TOutputImage > std::vector< int > itk::SphericalPolarFourierImageFilter< TInputImage, TOutputImage >::GetIndexNLM (const int index) const virtual
Reimplemented from itk::SphericalPolarFourierEstimationImageFilter< TInputImage, TOutputImage >.
Definition at line 110 of file itkSphericalPolarFourierImageFilter.hxx.
References itk::SphericalPolarFourierImageFilter< TInputImage, TOutputImage >::GetIndexJ(), and utl::GetIndexSHlm().
Referenced by itk::SphericalPolarFourierImageFilter< TInputImage, TOutputImage >::ComputeScale().
template<class TInputImage , class TOutputImage > virtual const char* itk::SphericalPolarFourierImageFilter< TInputImage, TOutputImage >::GetNameOfClass () const virtual
Run-time type information (and related methods)
Reimplemented from itk::SphericalPolarFourierEstimationImageFilter< TInputImage, TOutputImage >.
template<class TInputImage , class TOutputImage > LightObject::Pointer itk::SphericalPolarFourierImageFilter< TInputImage, TOutputImage >::InternalClone () const protected
Definition at line 69 of file itkSphericalPolarFourierImageFilter.hxx.
References itk::SphericalPolarFourierImageFilter< TInputImage, TOutputImage >::ComputeScale(), and itkShowPositionThreadedLogger.
Referenced by itk::SphericalPolarFourierImageFilter< TInputImage, TOutputImage >::SetBasisScale().
template<class TInputImage , class TOutputImage > itk::SphericalPolarFourierImageFilter< TInputImage, TOutputImage >::itkTypedefMaskedImageToImageMacro (Superclass)
template<class TInputImage , class TOutputImage > static Pointer itk::SphericalPolarFourierImageFilter< TInputImage, TOutputImage >::New () static
Method for creation through the object factory.
template<class TInputImage , class TOutputImage > void itk::SphericalPolarFourierImageFilter< TInputImage, TOutputImage >::operator= (const Self &) private
template<class TInputImage , class TOutputImage > void itk::SphericalPolarFourierImageFilter< TInputImage, TOutputImage >::PrintSelf (std::ostream & os, Indent indent) const protected virtual
Reimplemented from itk::SphericalPolarFourierEstimationImageFilter< TInputImage, TOutputImage >.
Definition at line 1077 of file itkSphericalPolarFourierImageFilter.hxx.
Referenced by itk::SphericalPolarFourierImageFilter< TInputImage, TOutputImage >::ThreadedGenerateData().
template<class TInputImage , class TOutputImage > int itk::SphericalPolarFourierImageFilter< TInputImage, TOutputImage >::RankToDim (const bool is_radial = false, const int radialRank = -1, const int shRank = -1) const virtual
from rank to dimension
Reimplemented from itk::SphericalPolarFourierEstimationImageFilter< TInputImage, TOutputImage >.
Definition at line 159 of file itkSphericalPolarFourierImageFilter.hxx.
References itk::SphericalPolarFourierImageFilter< TInputImage, TOutputImage >::ComputeRadialVectorForE0InBasis(), and utlException.
Referenced by itk::SphericalPolarFourierImageFilter< TInputImage, TOutputImage >::DimToRank().
template<class TInputImage , class TOutputImage > void itk::SphericalPolarFourierImageFilter< TInputImage, TOutputImage >::SetBasisScale (const double scale) virtual
Reimplemented from itk::SphericalPolarFourierEstimationImageFilter< TInputImage, TOutputImage >.
Definition at line 45 of file itkSphericalPolarFourierImageFilter.hxx.
References itk::SphericalPolarFourierImageFilter< TInputImage, TOutputImage >::InternalClone(), and itkShowPositionThreadedLogger.
Referenced by itk::SphericalPolarFourierImageFilter< TInputImage, TOutputImage >::SphericalPolarFourierImageFilter().
template<class TInputImage , class TOutputImage > void itk::SphericalPolarFourierImageFilter< TInputImage, TOutputImage >::ThreadedGenerateData (const OutputImageRegionType & outputRegionForThread, ThreadIdType threadId) protected
Definition at line 727 of file itkSphericalPolarFourierImageFilter.hxx.
References utl::ConnectUtlMatrix(), utl::NDArrayBase< T, Dim >::ElementAbsolute(), itk::IsImageEmpty(), itkShowPositionThreadedLogger, M_PI, utl::NDArrayBase< T, Dim >::Print(), itk::SphericalPolarFourierImageFilter< TInputImage, TOutputImage >::PrintSelf(), utl::PrintUtlMatrix(), utl::PrintUtlVector(), utl::PrintVector(), utl::ProductUtlMM(), utl::ProductUtlMv(), utl::NDArrayBase< T, Dim >::Size(), and utlException.
Referenced by itk::SphericalPolarFourierImageFilter< TInputImage, TOutputImage >::BeforeThreadedGenerateData().
Member Data Documentation
template<class TInputImage , class TOutputImage > VectorPointer itk::SphericalPolarFourierImageFilter< TInputImage, TOutputImage >::m_G0DWI protected
Definition at line 104 of file itkSphericalPolarFourierImageFilter.h.
template<class TInputImage , class TOutputImage > STDVectorPointer itk::SphericalPolarFourierImageFilter< TInputImage, TOutputImage >::m_Gn0 protected
Definition at line 103 of file itkSphericalPolarFourierImageFilter.h.
The documentation for this class was generated from the following files:
Modules/DiffusionModels/include/itkSphericalPolarFourierImageFilter.h
Modules/DiffusionModels/include/itkSphericalPolarFourierImageFilter.hxx