DMRITool: itk::TensorBasisMatrixGenerator< TElement > Class Template Reference
itk::TensorBasisMatrixGenerator< TElement > Class Template Reference
DiffusionModels
#include <itkTensorBasisMatrixGenerator.h>
Detailed Description
template<typename TElement = double>
class itk::TensorBasisMatrixGenerator< TElement >
Generate basis matrix.
Author
Jian Cheng (jian..nosp@m.chen.nosp@m.g.198.nosp@m.3@gm.nosp@m.ail.c.nosp@m.om)
Definition at line 36 of file itkTensorBasisMatrixGenerator.h.
Public Types
typedef SmartPointer< const Self > ConstPointer
typedef Superclass::MatrixPointer MatrixPointer
typedef Superclass::MatrixType MatrixType
typedef SmartPointer< Self > Pointer
typedef TensorBasisMatrixGenerator Self
typedef Superclass::STDVectorPointer STDVectorPointer
typedef Superclass::STDVectorType STDVectorType
typedef DiscreteBasisMatrixGenerator< TElement > Superclass
typedef DiffusionTensor< double > TensorType
typedef Superclass::VectorPointer VectorPointer
typedef Superclass::VectorType VectorType
Public Types inherited from itk::DiscreteBasisMatrixGenerator< TElement >
typedef SmartPointer< const Self > ConstPointer
typedef Superclass::MatrixPointer MatrixPointer
typedef Superclass::MatrixType MatrixType
typedef SmartPointer< Self > Pointer
typedef DiscreteBasisMatrixGenerator Self
typedef Superclass::STDVectorPointer STDVectorPointer
typedef Superclass::STDVectorType STDVectorType
typedef BasisMatrixGenerator< TElement > Superclass
typedef Superclass::VectorPointer VectorPointer
typedef Superclass::VectorType VectorType
Public Types inherited from itk::BasisMatrixGenerator< TElement >
typedef SmartPointer< const Self > ConstPointer
typedef utl_shared_ptr< MatrixType > MatrixPointer
typedef utl::NDArray< double, 2 > MatrixType
enum OutputType {
DWI =0,
EAP,
ODF
}
typedef SmartPointer< Self > Pointer
typedef SamplingSchemeQSpaceType::Pointer SamplingSchemeQSpacePointer
typedef SamplingSchemeQSpace< double > SamplingSchemeQSpaceType
typedef SamplingSchemeRSpaceType::Pointer SamplingSchemeRSpacePointer
typedef SamplingScheme3D< double > SamplingSchemeRSpaceType
typedef BasisMatrixGenerator Self
typedef utl_shared_ptr< STDVectorType > STDVectorPointer
typedef std::vector< double > STDVectorType
typedef Object Superclass
typedef utl_shared_ptr< VectorType > VectorPointer
typedef utl::NDArray< double, 1 > VectorType
Public Member Functions
void ComputeBasisMatrix () ITK_OVERRIDE
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual double GetEigenValue1 ()
virtual double GetEigenValue2 ()
virtual double GetEigenValue3 ()
virtual double GetEigenValueISO ()
virtual const char * GetNameOfClass () const
virtual void SetEigenValue1 (double _arg)
virtual void SetEigenValue2 (double _arg)
virtual void SetEigenValue3 (double _arg)
virtual void SetEigenValueISO (double _arg)
Public Member Functions inherited from itk::DiscreteBasisMatrixGenerator< TElement >
virtual ::itk::LightObject::Pointer CreateAnother (void) const
void Flip (const int flipx, const int flipy, const int flipz) override
virtual MatrixPointer GetBasisOrientations ()
int GetNumberOfBasis () const override
virtual bool GetUseIsotropicTerm ()
virtual void SetBasisOrientations (MatrixPointer _arg)
virtual void SetUseIsotropicTerm (bool _arg)
virtual void UseIsotropicTermOff ()
virtual void UseIsotropicTermOn ()
Public Member Functions inherited from itk::BasisMatrixGenerator< TElement >
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual MatrixPointer GetBasisMatrix () const
virtual double GetMD0 ()
virtual int GetNumberOfSamples () const
virtual int GetODFOrder ()
virtual OutputType GetOutputType ()
virtual MatrixPointer GetQBasisMatrixForDWI ()
virtual MatrixPointer GetRBasisMatrixForEAP ()
virtual MatrixPointer GetRBasisMatrixForODF ()
itkGetObjectMacro (SamplingSchemeQSpace, SamplingSchemeQSpaceType)
itkGetObjectMacro (SamplingSchemeRSpace, SamplingSchemeRSpaceType)
virtual void SetMD0 (double _arg)
virtual void SetODFOrder (int _arg)
virtual void SetOutputType (OutputType _arg)
virtual void SetSamplingSchemeQSpace (SamplingSchemeQSpaceType *_arg)
virtual void SetSamplingSchemeRSpace (SamplingSchemeRSpaceType *_arg)
Static Public Member Functions
static Pointer New ()
Static Public Member Functions inherited from itk::DiscreteBasisMatrixGenerator< TElement >
static Pointer New ()
Static Public Member Functions inherited from itk::BasisMatrixGenerator< TElement >
static Pointer New ()
Protected Member Functions
LightObject::Pointer InternalClone () const ITK_OVERRIDE
void PrintSelf (std::ostream &os, Indent indent) const ITK_OVERRIDE
TensorBasisMatrixGenerator ()
virtual void VerifyInputParameters () const ITK_OVERRIDE
virtual ~TensorBasisMatrixGenerator ()
Protected Member Functions inherited from itk::DiscreteBasisMatrixGenerator< TElement >
DiscreteBasisMatrixGenerator ()
LightObject::Pointer InternalClone () const ITK_OVERRIDE
void PrintSelf (std::ostream &os, Indent indent) const ITK_OVERRIDE
virtual ~DiscreteBasisMatrixGenerator ()
Protected Member Functions inherited from itk::BasisMatrixGenerator< TElement >
BasisMatrixGenerator ()
LightObject::Pointer InternalClone () const ITK_OVERRIDE
void PrintSelf (std::ostream &os, Indent indent) const ITK_OVERRIDE
virtual ~BasisMatrixGenerator ()
Protected Attributes
double m_EigenValue1
double m_EigenValue2
double m_EigenValue3
double m_EigenValueISO
Protected Attributes inherited from itk::DiscreteBasisMatrixGenerator< TElement >
MatrixPointer m_BasisOrientations
bool m_UseIsotropicTerm
Protected Attributes inherited from itk::BasisMatrixGenerator< TElement >
double m_MD0
int m_ODFOrder
OutputType m_OutputType
MatrixPointer m_QBasisMatrixForDWI
MatrixPointer m_RBasisMatrixForEAP
MatrixPointer m_RBasisMatrixForODF
SamplingSchemeQSpacePointer m_SamplingSchemeQSpace
SamplingSchemeRSpacePointer m_SamplingSchemeRSpace
Private Member Functions
void operator= (const Self &)
TensorBasisMatrixGenerator (const Self &)
Member Typedef Documentation
template<typename TElement = double> typedef SmartPointer<const Self> itk::TensorBasisMatrixGenerator< TElement >::ConstPointer
Definition at line 44 of file itkTensorBasisMatrixGenerator.h.
template<typename TElement = double> typedef Superclass::MatrixPointer itk::TensorBasisMatrixGenerator< TElement >::MatrixPointer
Definition at line 55 of file itkTensorBasisMatrixGenerator.h.
template<typename TElement = double> typedef Superclass::MatrixType itk::TensorBasisMatrixGenerator< TElement >::MatrixType
Save the template parameters.
Definition at line 50 of file itkTensorBasisMatrixGenerator.h.
template<typename TElement = double> typedef SmartPointer<Self> itk::TensorBasisMatrixGenerator< TElement >::Pointer
Definition at line 43 of file itkTensorBasisMatrixGenerator.h.
template<typename TElement = double> typedef TensorBasisMatrixGenerator itk::TensorBasisMatrixGenerator< TElement >::Self
Standard class typedefs.
Definition at line 41 of file itkTensorBasisMatrixGenerator.h.
template<typename TElement = double> typedef Superclass::STDVectorPointer itk::TensorBasisMatrixGenerator< TElement >::STDVectorPointer
Definition at line 58 of file itkTensorBasisMatrixGenerator.h.
template<typename TElement = double> typedef Superclass::STDVectorType itk::TensorBasisMatrixGenerator< TElement >::STDVectorType
Definition at line 57 of file itkTensorBasisMatrixGenerator.h.
template<typename TElement = double> typedef DiscreteBasisMatrixGenerator<TElement> itk::TensorBasisMatrixGenerator< TElement >::Superclass
Definition at line 42 of file itkTensorBasisMatrixGenerator.h.
template<typename TElement = double> typedef DiffusionTensor<double> itk::TensorBasisMatrixGenerator< TElement >::TensorType
Definition at line 60 of file itkTensorBasisMatrixGenerator.h.
template<typename TElement = double> typedef Superclass::VectorPointer itk::TensorBasisMatrixGenerator< TElement >::VectorPointer
Definition at line 56 of file itkTensorBasisMatrixGenerator.h.
template<typename TElement = double> typedef Superclass::VectorType itk::TensorBasisMatrixGenerator< TElement >::VectorType
Definition at line 54 of file itkTensorBasisMatrixGenerator.h.
Constructor & Destructor Documentation
template<typename TElement > itk::TensorBasisMatrixGenerator< TElement >::TensorBasisMatrixGenerator () protected
Definition at line 29 of file itkTensorBasisMatrixGenerator.hxx.
References itk::TensorBasisMatrixGenerator< TElement >::InternalClone().
template<typename TElement = double> virtual itk::TensorBasisMatrixGenerator< TElement >::~TensorBasisMatrixGenerator () inline protected virtual
Definition at line 84 of file itkTensorBasisMatrixGenerator.h.
References ITK_OVERRIDE.
template<typename TElement = double> itk::TensorBasisMatrixGenerator< TElement >::TensorBasisMatrixGenerator (const Self &) private
Member Function Documentation
template<typename TElement > void itk::TensorBasisMatrixGenerator< TElement >::ComputeBasisMatrix () virtual
Reimplemented from itk::BasisMatrixGenerator< TElement >.
Definition at line 84 of file itkTensorBasisMatrixGenerator.hxx.
References itk::DiffusionTensor< TPrecision >::GetDWISamples(), itk::DiffusionTensor< TPrecision >::GetEAPSamples(), itk::DiffusionTensor< TPrecision >::GetODFSamples(), itk::DiffusionTensor< TPrecision >::Rotate(), itk::DiffusionTensor< TPrecision >::SetEigenValues(), and utlShowPosition.
Referenced by itk::TensorBasisMatrixGenerator< TElement >::VerifyInputParameters().
template<typename TElement = double> virtual::itk::LightObject::Pointer itk::TensorBasisMatrixGenerator< TElement >::CreateAnother (void) const
template<typename TElement = double> virtual double itk::TensorBasisMatrixGenerator< TElement >::GetEigenValue1 () virtual
template<typename TElement = double> virtual double itk::TensorBasisMatrixGenerator< TElement >::GetEigenValue2 () virtual
template<typename TElement = double> virtual double itk::TensorBasisMatrixGenerator< TElement >::GetEigenValue3 () virtual
template<typename TElement = double> virtual double itk::TensorBasisMatrixGenerator< TElement >::GetEigenValueISO () virtual
template<typename TElement = double> virtual const char* itk::TensorBasisMatrixGenerator< TElement >::GetNameOfClass () const virtual
Standard part of every itk Object.
Reimplemented from itk::DiscreteBasisMatrixGenerator< TElement >.
template<typename TElement > LightObject::Pointer itk::TensorBasisMatrixGenerator< TElement >::InternalClone () const protected
Definition at line 40 of file itkTensorBasisMatrixGenerator.hxx.
References itk::TensorBasisMatrixGenerator< TElement >::PrintSelf(), and utlShowPosition.
Referenced by itk::TensorBasisMatrixGenerator< TElement >::TensorBasisMatrixGenerator().
template<typename TElement = double> static Pointer itk::TensorBasisMatrixGenerator< TElement >::New () static
Method for creation through the object factory.
template<typename TElement = double> void itk::TensorBasisMatrixGenerator< TElement >::operator= (const Self &) private
template<typename TElement > void itk::TensorBasisMatrixGenerator< TElement >::PrintSelf (std::ostream & os, Indent indent) const protected
Definition at line 60 of file itkTensorBasisMatrixGenerator.hxx.
References PrintVar1, PrintVar3, and itk::TensorBasisMatrixGenerator< TElement >::VerifyInputParameters().
Referenced by itk::TensorBasisMatrixGenerator< TElement >::InternalClone().
template<typename TElement = double> virtual void itk::TensorBasisMatrixGenerator< TElement >::SetEigenValue1 (double _arg) virtual
tensor parameters
template<typename TElement = double> virtual void itk::TensorBasisMatrixGenerator< TElement >::SetEigenValue2 (double _arg) virtual
template<typename TElement = double> virtual void itk::TensorBasisMatrixGenerator< TElement >::SetEigenValue3 (double _arg) virtual
template<typename TElement = double> virtual void itk::TensorBasisMatrixGenerator< TElement >::SetEigenValueISO (double _arg) virtual
template<typename TElement > void itk::TensorBasisMatrixGenerator< TElement >::VerifyInputParameters () const protected virtual
Reimplemented from itk::DiscreteBasisMatrixGenerator< TElement >.
Definition at line 70 of file itkTensorBasisMatrixGenerator.hxx.
References itk::TensorBasisMatrixGenerator< TElement >::ComputeBasisMatrix(), utlGlobalException, and utlSAGlobalException.
Referenced by itk::TensorBasisMatrixGenerator< TElement >::PrintSelf().
Member Data Documentation
template<typename TElement = double> double itk::TensorBasisMatrixGenerator< TElement >::m_EigenValue1 protected
Definition at line 92 of file itkTensorBasisMatrixGenerator.h.
template<typename TElement = double> double itk::TensorBasisMatrixGenerator< TElement >::m_EigenValue2 protected
Definition at line 93 of file itkTensorBasisMatrixGenerator.h.
template<typename TElement = double> double itk::TensorBasisMatrixGenerator< TElement >::m_EigenValue3 protected
Definition at line 94 of file itkTensorBasisMatrixGenerator.h.
template<typename TElement = double> double itk::TensorBasisMatrixGenerator< TElement >::m_EigenValueISO protected
Definition at line 96 of file itkTensorBasisMatrixGenerator.h.
The documentation for this class was generated from the following files:
Modules/DiffusionModels/include/itkTensorBasisMatrixGenerator.h
Modules/DiffusionModels/include/itkTensorBasisMatrixGenerator.hxx