DMRITool: utl::Functor::VectorFunctorBase< TVector, TOutput > Class Template Reference
utl::Functor::VectorFunctorBase< TVector, TOutput > Class Template Reference
#include <utlFunctors.h>
Detailed Description
template<class TVector, class TOutput = TVector>
class utl::Functor::VectorFunctorBase< TVector, TOutput >
Definition at line 143 of file utlFunctors.h.
Public Types
typedef VectorFunctorBase Self
Public Member Functions
virtual int GetLogLevel () const
int GetOutputDimension (const int inputSize) const
int GetOutputDimension (const std::vector< int > &sizeVec) const
void Initialize ()
bool operator!= (const Self &other) const
Self & operator= (const Self &other)
bool operator== (const Self &other) const
void Print (std::ostream &os=std::cout) const
virtual void SetLogLevel (const int _arg)
void VerifyInputParameters (const int inputSize=-1) const
Protected Attributes
int m_LogLevel =1
Member Typedef Documentation
template<class TVector, class TOutput = TVector> typedef VectorFunctorBase utl::Functor::VectorFunctorBase< TVector, TOutput >::Self
Definition at line 146 of file utlFunctors.h.
Member Function Documentation
template<class TVector, class TOutput = TVector> virtual int utl::Functor::VectorFunctorBase< TVector, TOutput >::GetLogLevel () const inline virtual
Definition at line 169 of file utlFunctors.h.
template<class TVector, class TOutput = TVector> int utl::Functor::VectorFunctorBase< TVector, TOutput >::GetOutputDimension (const int inputSize) const inline
Definition at line 161 of file utlFunctors.h.
Referenced by utl::Functor::Shred< TVector, TOutput >::operator()(), utl::Functor::DotProduct< TVector, TOutput >::operator()(), and utl::Functor::Compose< TVector, TOutput >::operator()().
template<class TVector, class TOutput = TVector> int utl::Functor::VectorFunctorBase< TVector, TOutput >::GetOutputDimension (const std::vector< int > & sizeVec) const inline
Definition at line 163 of file utlFunctors.h.
template<class TVector, class TOutput = TVector> void utl::Functor::VectorFunctorBase< TVector, TOutput >::Initialize () inline
Definition at line 166 of file utlFunctors.h.
template<class TVector, class TOutput = TVector> bool utl::Functor::VectorFunctorBase< TVector, TOutput >::operator!= (const Self & other) const inline
Definition at line 149 of file utlFunctors.h.
template<class TVector, class TOutput = TVector> Self& utl::Functor::VectorFunctorBase< TVector, TOutput >::operator= (const Self & other) inline
Definition at line 152 of file utlFunctors.h.
template<class TVector, class TOutput = TVector> bool utl::Functor::VectorFunctorBase< TVector, TOutput >::operator== (const Self & other) const inline
Definition at line 147 of file utlFunctors.h.
template<class TVector, class TOutput = TVector> void utl::Functor::VectorFunctorBase< TVector, TOutput >::Print (std::ostream & os = std::cout) const inline
Definition at line 171 of file utlFunctors.h.
template<class TVector, class TOutput = TVector> virtual void utl::Functor::VectorFunctorBase< TVector, TOutput >::SetLogLevel (const int _arg) inline virtual
Definition at line 169 of file utlFunctors.h.
template<class TVector, class TOutput = TVector> void utl::Functor::VectorFunctorBase< TVector, TOutput >::VerifyInputParameters (const int inputSize = -1) const inline
Definition at line 167 of file utlFunctors.h.
Member Data Documentation
template<class TVector, class TOutput = TVector> int utl::Functor::VectorFunctorBase< TVector, TOutput >::m_LogLevel =1 protected
Definition at line 177 of file utlFunctors.h.
Referenced by utl::Functor::VectorFunctorBase< utl::NDArray< T, Dim >, utl::NDArray< T, Dim > >::operator=(), and utl::Functor::VectorFunctorBase< utl::NDArray< T, Dim >, utl::NDArray< T, Dim > >::Print().
The documentation for this class was generated from the following file:
Modules/HelperFunctions/include/utlFunctors.h