DMRITool: spams::FISTA::Regularizer< T, D > Class Template Reference
spams::FISTA::Regularizer< T, D > Class Template Reference abstract
#include <fista.h>
Detailed Description
template<typename T, typename D = Vector<T>>
class spams::FISTA::Regularizer< T, D >
Definition at line 1040 of file fista.h.
Public Member Functions
virtual T eval (const D &input) const =0
virtual T eval_dual_norm (const D &x) const
virtual T eval_dual_norm_paths (const D &x, SpMatrix< T > &path) const
virtual T eval_paths (const D &x, SpMatrix< T > &paths_mat) const
virtual void fenchel (const D &input, T &val, T &scal) const =0
virtual bool is_fenchel () const
virtual bool is_intercept () const
virtual bool is_subgrad () const
virtual void prox (const D &input, D &output, const T lambda)=0
Regularizer ()
Regularizer (const ParamReg< T > &param)
virtual void reset ()
virtual void sub_grad (const D &input, D &output) const
virtual ~Regularizer ()
Protected Attributes
bool _intercept
bool _pos
Private Member Functions
Regularizer< T, D > & operator= (const Regularizer< T, D > &reg)
Regularizer (const Regularizer< T, D > &reg)
Constructor & Destructor Documentation
template<typename T, typename D = Vector<T>> spams::FISTA::Regularizer< T, D >::Regularizer () inline
Definition at line 1042 of file fista.h.
template<typename T, typename D = Vector<T>> spams::FISTA::Regularizer< T, D >::Regularizer (const ParamReg< T > & param) inline
Definition at line 1043 of file fista.h.
template<typename T, typename D = Vector<T>> virtual spams::FISTA::Regularizer< T, D >::~Regularizer () inline virtual
Definition at line 1047 of file fista.h.
template<typename T, typename D = Vector<T>> spams::FISTA::Regularizer< T, D >::Regularizer (const Regularizer< T, D > & reg) explicit private
Member Function Documentation
template<typename T, typename D = Vector<T>> virtual T spams::FISTA::Regularizer< T, D >::eval (const D & input) const pure virtual
Implemented in spams::FISTA::SpecGraphMat< T >, spams::FISTA::RegMat< T, Reg >, spams::FISTA::GraphPathConv< T >, spams::FISTA::GraphPathL0< T >, spams::FISTA::Rank< T >, spams::FISTA::TraceNorm< T >, spams::FISTA::MixedL1LINF< T >, spams::FISTA::MixedL1L2< T >, spams::FISTA::GroupProx< T, Reg >, spams::FISTA::ProxMatToVec< T, ProxMat >, spams::FISTA::TreeLzero< T >, spams::FISTA::TreeLasso< T >, spams::FISTA::GraphLasso< T >, spams::FISTA::FusedLasso< T >, spams::FISTA::ComposeProx< T, D, RegA, RegB, order, scale_lambda >, spams::FISTA::normLINF< T >, spams::FISTA::normL2< T >, spams::FISTA::Ridge< T >, spams::FISTA::None< T >, spams::FISTA::Lzero< T >, spams::FISTA::LassoConstraint< T >, and spams::FISTA::Lasso< T >.
Referenced by spams::FISTA::duality_gap(), spams::FISTA::dualityGraph(), spams::FISTA::EvalGraphPath(), spams::FISTA::FISTA_Generic(), spams::FISTA::ISTA_Generic(), spams::FISTA::PROX(), and spams::FISTA::subGradientDescent_Generic().
template<typename T, typename D = Vector<T>> virtual T spams::FISTA::Regularizer< T, D >::eval_dual_norm (const D & x) const inline virtual
Reimplemented in spams::FISTA::GraphPathConv< T >.
Definition at line 1060 of file fista.h.
Referenced by spams::FISTA::EvalGraphPath().
template<typename T, typename D = Vector<T>> virtual T spams::FISTA::Regularizer< T, D >::eval_dual_norm_paths (const D & x, SpMatrix< T > & path) const inline virtual
Reimplemented in spams::FISTA::GraphPathConv< T >.
Definition at line 1062 of file fista.h.
Referenced by spams::FISTA::EvalGraphPath().
template<typename T, typename D = Vector<T>> virtual T spams::FISTA::Regularizer< T, D >::eval_paths (const D & x, SpMatrix< T > & paths_mat) const inline virtual
Reimplemented in spams::FISTA::GraphPathConv< T >, and spams::FISTA::GraphPathL0< T >.
Definition at line 1059 of file fista.h.
Referenced by spams::FISTA::EvalGraphPath().
template<typename T, typename D = Vector<T>> virtual void spams::FISTA::Regularizer< T, D >::fenchel (const D & input, T & val, T & scal) const pure virtual
returns phi^star(input) and ouput=input if the fenchel is unconstrained returns 0 and scale input such that phi^star(output)=0 otherwise
Implemented in spams::FISTA::SpecGraphMat< T >, spams::FISTA::RegMat< T, Reg >, spams::FISTA::GraphPathConv< T >, spams::FISTA::GraphPathL0< T >, spams::FISTA::Rank< T >, spams::FISTA::TraceNorm< T >, spams::FISTA::MixedL1LINF< T >, spams::FISTA::MixedL1L2< T >, spams::FISTA::GroupProx< T, Reg >, spams::FISTA::ProxMatToVec< T, ProxMat >, spams::FISTA::TreeLzero< T >, spams::FISTA::TreeLasso< T >, spams::FISTA::GraphLasso< T >, spams::FISTA::FusedLasso< T >, spams::FISTA::ComposeProx< T, D, RegA, RegB, order, scale_lambda >, spams::FISTA::normLINF< T >, spams::FISTA::normL2< T >, spams::FISTA::Ridge< T >, spams::FISTA::None< T >, spams::FISTA::Lzero< T >, spams::FISTA::LassoConstraint< T >, and spams::FISTA::Lasso< T >.
Referenced by spams::FISTA::duality_gap().
template<typename T, typename D = Vector<T>> virtual bool spams::FISTA::Regularizer< T, D >::is_fenchel () const inline virtual
Reimplemented in spams::FISTA::SpecGraphMat< T >, spams::FISTA::RegMat< T, Reg >, spams::FISTA::GraphPathConv< T >, spams::FISTA::GraphPathL0< T >, spams::FISTA::Rank< T >, spams::FISTA::GroupProx< T, Reg >, spams::FISTA::ProxMatToVec< T, ProxMat >, spams::FISTA::TreeLzero< T >, spams::FISTA::TreeLasso< T >, spams::FISTA::GraphLasso< T >, spams::FISTA::FusedLasso< T >, spams::FISTA::ComposeProx< T, D, RegA, RegB, order, scale_lambda >, spams::FISTA::None< T >, and spams::FISTA::Lzero< T >.
Definition at line 1055 of file fista.h.
Referenced by spams::FISTA::duality_gap(), spams::FISTA::FISTA_Generic(), spams::FISTA::ISTA_Generic(), spams::FISTA::solver(), and spams::FISTA::subGradientDescent_Generic().
template<typename T, typename D = Vector<T>> virtual bool spams::FISTA::Regularizer< T, D >::is_intercept () const inline virtual
Definition at line 1056 of file fista.h.
Referenced by spams::FISTA::duality_gap().
template<typename T, typename D = Vector<T>> virtual bool spams::FISTA::Regularizer< T, D >::is_subgrad () const inline virtual
Reimplemented in spams::FISTA::RegMat< T, Reg >, spams::FISTA::MixedL1LINF< T >, spams::FISTA::MixedL1L2< T >, spams::FISTA::TreeLasso< T >, spams::FISTA::ComposeProx< T, D, RegA, RegB, order, scale_lambda >, spams::FISTA::Ridge< T >, spams::FISTA::None< T >, spams::FISTA::LassoConstraint< T >, and spams::FISTA::Lasso< T >.
Definition at line 1057 of file fista.h.
template<typename T, typename D = Vector<T>> Regularizer<T,D>& spams::FISTA::Regularizer< T, D >::operator= (const Regularizer< T, D > & reg) private
template<typename T, typename D = Vector<T>> virtual void spams::FISTA::Regularizer< T, D >::prox (const D & input, D & output, const T lambda) pure virtual
Implemented in spams::FISTA::SpecGraphMat< T >, spams::FISTA::RegMat< T, Reg >, spams::FISTA::GraphPathConv< T >, spams::FISTA::GraphPathL0< T >, spams::FISTA::Rank< T >, spams::FISTA::TraceNorm< T >, spams::FISTA::MixedL1LINF< T >, spams::FISTA::MixedL1L2< T >, spams::FISTA::GroupProx< T, Reg >, spams::FISTA::ProxMatToVec< T, ProxMat >, spams::FISTA::TreeLzero< T >, spams::FISTA::TreeLasso< T >, spams::FISTA::GraphLasso< T >, spams::FISTA::FusedLasso< T >, spams::FISTA::ComposeProx< T, D, RegA, RegB, order, scale_lambda >, spams::FISTA::normLINF< T >, spams::FISTA::normL2< T >, spams::FISTA::Ridge< T >, spams::FISTA::None< T >, spams::FISTA::Lzero< T >, spams::FISTA::LassoConstraint< T >, and spams::FISTA::Lasso< T >.
Referenced by spams::FISTA::FISTA_Generic(), spams::FISTA::ISTA_Generic(), and spams::FISTA::PROX().
template<typename T, typename D = Vector<T>> virtual void spams::FISTA::Regularizer< T, D >::reset () inline virtual
Reimplemented in spams::FISTA::SpecGraphMat< T >, spams::FISTA::RegMat< T, Reg >, spams::FISTA::GraphLasso< T >, and spams::FISTA::None< T >.
Definition at line 1049 of file fista.h.
Referenced by spams::FISTA::dualityGraph(), spams::FISTA::EvalGraphPath(), and spams::FISTA::PROX().
template<typename T, typename D = Vector<T>> virtual void spams::FISTA::Regularizer< T, D >::sub_grad (const D & input, D & output) const inline virtual
Reimplemented in spams::FISTA::RegMat< T, Reg >, spams::FISTA::MixedL1LINF< T >, spams::FISTA::MixedL1L2< T >, spams::FISTA::TreeLasso< T >, spams::FISTA::ComposeProx< T, D, RegA, RegB, order, scale_lambda >, spams::FISTA::Ridge< T >, spams::FISTA::None< T >, and spams::FISTA::Lasso< T >.
Definition at line 1058 of file fista.h.
Referenced by spams::FISTA::subGradientDescent_Generic().
Member Data Documentation
template<typename T, typename D = Vector<T>> bool spams::FISTA::Regularizer< T, D >::_intercept protected
Definition at line 1066 of file fista.h.
template<typename T, typename D = Vector<T>> bool spams::FISTA::Regularizer< T, D >::_pos protected
Definition at line 1062 of file fista.h.
The documentation for this class was generated from the following file:
ThirdParty/Spams/include/fista.h