DMRITool: spams::FISTA::Lasso< T > Class Template Reference
spams::FISTA::Lasso< T > Class Template Reference
#include <fista.h>
Detailed Description
template<typename T>
class spams::FISTA::Lasso< T >
Definition at line 1075 of file fista.h.
Public Member Functions
T eval (const Vector< T > &x) const
void fenchel (const Vector< T > &input, T &val, T &scal) const
virtual bool is_subgrad () const
Lasso (const ParamReg< T > &param)
void prox (const Vector< T > &x, Vector< T > &y, const T lambda)
virtual void sub_grad (const Vector< T > &input, Vector< T > &output) const
virtual ~Lasso ()
Public Member Functions inherited from spams::FISTA::Regularizer< T >
virtual T eval_dual_norm (const Vector< T > &x) const
virtual T eval_dual_norm_paths (const Vector< T > &x, SpMatrix< T > &path) const
virtual T eval_paths (const Vector< T > &x, SpMatrix< T > &paths_mat) const
virtual bool is_fenchel () const
virtual bool is_intercept () const
Regularizer ()
Regularizer (const ParamReg< T > &param)
virtual void reset ()
virtual ~Regularizer ()
Additional Inherited Members
Protected Attributes inherited from spams::FISTA::Regularizer< T >
bool _intercept
bool _pos
Constructor & Destructor Documentation
template<typename T > spams::FISTA::Lasso< T >::Lasso (const ParamReg< T > & param) inline
Definition at line 1077 of file fista.h.
template<typename T > virtual spams::FISTA::Lasso< T >::~Lasso () inline virtual
Definition at line 1078 of file fista.h.
Member Function Documentation
template<typename T > T spams::FISTA::Lasso< T >::eval (const Vector< T > & x) const inline virtual
Implements spams::FISTA::Regularizer< T >.
Definition at line 1086 of file fista.h.
References spams::abs(), spams::Vector< T >::asum(), and spams::Vector< T >::n().
template<typename T > void spams::FISTA::Lasso< T >::fenchel (const Vector< T > & input, T & val, T & scal) const inline virtual
returns phi^star(input) and ouput=input if the fenchel is unconstrained returns 0 and scale input such that phi^star(output)=0 otherwise
Implements spams::FISTA::Regularizer< T >.
Definition at line 1089 of file fista.h.
References spams::Vector< T >::copy(), EPSILON, spams::Vector< T >::fmaxval(), INFINITY, spams::Vector< T >::n(), and spams::Vector< T >::thrsPos().
template<typename T > virtual bool spams::FISTA::Lasso< T >::is_subgrad () const inline virtual
Reimplemented from spams::FISTA::Regularizer< T >.
Definition at line 1098 of file fista.h.
template<typename T > void spams::FISTA::Lasso< T >::prox (const Vector< T > & x, Vector< T > & y, const T lambda) inline virtual
Implements spams::FISTA::Regularizer< T >.
Definition at line 1080 of file fista.h.
References spams::Vector< T >::copy(), spams::Vector< T >::n(), spams::Vector< T >::softThrshold(), and spams::Vector< T >::thrsPos().
template<typename T > virtual void spams::FISTA::Lasso< T >::sub_grad (const Vector< T > & input, Vector< T > & output) const inline virtual
Reimplemented from spams::FISTA::Regularizer< T >.
Definition at line 1099 of file fista.h.
References spams::Vector< T >::n(), and spams::Vector< T >::resize().
The documentation for this class was generated from the following file:
ThirdParty/Spams/include/fista.h