DMRITool: spams::FISTA::LossCur< T > Class Template Reference
spams::FISTA::LossCur< T > Class Template Reference
#include <fista.h>
Detailed Description
template<typename T>
class spams::FISTA::LossCur< T >
Definition at line 798 of file fista.h.
Public Member Functions
T eval (const Matrix< T > &A) const
virtual T fenchel (const Matrix< T > &input) const
void grad (const Matrix< T > &A, Matrix< T > &grad) const
void init (const Matrix< T > &y)
LossCur (const AbstractMatrixB< T > &X)
virtual void var_fenchel (const Matrix< T > &A, Matrix< T > &grad1, Matrix< T > &grad2, const bool intercept) const
virtual ~LossCur ()
Public Member Functions inherited from spams::FISTA::Loss< T, Matrix< T >, Matrix< T > >
virtual bool is_fenchel () const
Loss ()
virtual bool test_backtracking (const Matrix< T > &y, const Matrix< T > &grad, const Matrix< T > &prox, const T L) const
virtual ~Loss ()
Private Member Functions
LossCur (const LossCur< T > &dict)
LossCur< T > & operator= (const LossCur< T > &dict)
Private Attributes
const AbstractMatrixB< T > * _X
Constructor & Destructor Documentation
template<typename T> spams::FISTA::LossCur< T >::LossCur (const AbstractMatrixB< T > & X) inline
Definition at line 800 of file fista.h.
template<typename T> virtual spams::FISTA::LossCur< T >::~LossCur () inline virtual
Definition at line 802 of file fista.h.
template<typename T> spams::FISTA::LossCur< T >::LossCur (const LossCur< T > & dict) explicit private
Member Function Documentation
template<typename T> T spams::FISTA::LossCur< T >::eval (const Matrix< T > & A) const inline virtual
Implements spams::FISTA::Loss< T, Matrix< T >, Matrix< T > >.
Definition at line 806 of file fista.h.
References spams::Matrix< T >::copyTo(), spams::Matrix< T >::mult(), spams::Matrix< T >::n(), and spams::Matrix< T >::normFsq().
template<typename T> virtual T spams::FISTA::LossCur< T >::fenchel (const Matrix< T > & input) const inline virtual
Implements spams::FISTA::Loss< T, Matrix< T >, Matrix< T > >.
Definition at line 829 of file fista.h.
References spams::Matrix< T >::normFsq().
template<typename T> void spams::FISTA::LossCur< T >::grad (const Matrix< T > & A, Matrix< T > & grad) const inline virtual
Implements spams::FISTA::Loss< T, Matrix< T >, Matrix< T > >.
Definition at line 816 of file fista.h.
References spams::Matrix< T >::copyTo(), spams::Matrix< T >::m(), spams::Matrix< T >::mult(), spams::Matrix< T >::n(), and spams::Matrix< T >::resize().
template<typename T> void spams::FISTA::LossCur< T >::init (const Matrix< T > & y) inline virtual
Implements spams::FISTA::Loss< T, Matrix< T >, Matrix< T > >.
Definition at line 804 of file fista.h.
template<typename T> LossCur<T>& spams::FISTA::LossCur< T >::operator= (const LossCur< T > & dict) private
template<typename T> virtual void spams::FISTA::LossCur< T >::var_fenchel (const Matrix< T > & A, Matrix< T > & grad1, Matrix< T > & grad2, const bool intercept) const inline virtual
Implements spams::FISTA::Loss< T, Matrix< T >, Matrix< T > >.
Definition at line 832 of file fista.h.
References spams::Matrix< T >::m(), spams::Matrix< T >::mult(), spams::Matrix< T >::n(), and spams::Matrix< T >::resize().
Member Data Documentation
template<typename T> const AbstractMatrixB<T>* spams::FISTA::LossCur< T >::_X private
Definition at line 848 of file fista.h.
The documentation for this class was generated from the following file:
ThirdParty/Spams/include/fista.h