DMRITool: itk::StructureTensorImageFilter< TInputImage, TOutputImage > Class Template Reference
itk::StructureTensorImageFilter< TInputImage, TOutputImage > Class Template Reference
#include <itkStructureTensorImageFilter.h>
Detailed Description
template<class TInputImage, class TOutputImage>
class itk::StructureTensorImageFilter< TInputImage, TOutputImage >
Computes the structure tensor.
Implementation of the structure tensor, defined by
where denotes the gaussian kernel of standard deviation , and .
Definition at line 36 of file itkStructureTensorImageFilter.h.
Public Types
typedef SmartPointer< const Self > ConstPointer
typedef itk::GradientImageFilter< InputImageType, double, double, OutputImageType > GradientFilterType
typedef TInputImage InputImageType
typedef TOutputImage OutputImageType
typedef SmartPointer< Self > Pointer
typedef StructureTensorImageFilter Self
typedef ImageToImageFilter< TInputImage, TOutputImage > Superclass
Public Member Functions
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual double GetIntensityScale ()
virtual const char * GetNameOfClass () const
virtual void SetIntensityScale (double _arg)
Static Public Member Functions
static Pointer New ()
Protected Member Functions
virtual void GenerateData () ITK_OVERRIDE
LightObject::Pointer InternalClone () const ITK_OVERRIDE
void PrintSelf (std::ostream &os, Indent indent) const ITK_OVERRIDE
StructureTensorImageFilter ()
Protected Attributes
double m_IntensityScale
Private Member Functions
void operator= (const Self &)
StructureTensorImageFilter (const Self &)
Member Typedef Documentation
template<class TInputImage , class TOutputImage > typedef SmartPointer<const Self> itk::StructureTensorImageFilter< TInputImage, TOutputImage >::ConstPointer
Definition at line 43 of file itkStructureTensorImageFilter.h.
template<class TInputImage , class TOutputImage > typedef itk::GradientImageFilter<InputImageType, double, double, OutputImageType> itk::StructureTensorImageFilter< TInputImage, TOutputImage >::GradientFilterType
Definition at line 53 of file itkStructureTensorImageFilter.h.
template<class TInputImage , class TOutputImage > typedef TInputImage itk::StructureTensorImageFilter< TInputImage, TOutputImage >::InputImageType
Definition at line 48 of file itkStructureTensorImageFilter.h.
template<class TInputImage , class TOutputImage > typedef TOutputImage itk::StructureTensorImageFilter< TInputImage, TOutputImage >::OutputImageType
Definition at line 51 of file itkStructureTensorImageFilter.h.
template<class TInputImage , class TOutputImage > typedef SmartPointer<Self> itk::StructureTensorImageFilter< TInputImage, TOutputImage >::Pointer
Definition at line 42 of file itkStructureTensorImageFilter.h.
template<class TInputImage , class TOutputImage > typedef StructureTensorImageFilter itk::StructureTensorImageFilter< TInputImage, TOutputImage >::Self
Definition at line 40 of file itkStructureTensorImageFilter.h.
template<class TInputImage , class TOutputImage > typedef ImageToImageFilter< TInputImage, TOutputImage> itk::StructureTensorImageFilter< TInputImage, TOutputImage >::Superclass
Definition at line 41 of file itkStructureTensorImageFilter.h.
Constructor & Destructor Documentation
template<class TInputImage , class TOutputImage > itk::StructureTensorImageFilter< TInputImage, TOutputImage >::StructureTensorImageFilter () protected
Definition at line 25 of file itkStructureTensorImageFilter.hxx.
References itk::StructureTensorImageFilter< TInputImage, TOutputImage >::InternalClone(), and itk::StructureTensorImageFilter< TInputImage, TOutputImage >::m_IntensityScale.
template<class TInputImage , class TOutputImage > itk::StructureTensorImageFilter< TInputImage, TOutputImage >::StructureTensorImageFilter (const Self &) private
Member Function Documentation
template<class TInputImage , class TOutputImage > virtual::itk::LightObject::Pointer itk::StructureTensorImageFilter< TInputImage, TOutputImage >::CreateAnother (void) const
template<class TInputImage , class TOutputImage > void itk::StructureTensorImageFilter< TInputImage, TOutputImage >::GenerateData (void) protected virtual
Definition at line 49 of file itkStructureTensorImageFilter.hxx.
References itk::StructureTensorImageFilter< TInputImage, TOutputImage >::m_IntensityScale.
template<class TInputImage , class TOutputImage > virtual double itk::StructureTensorImageFilter< TInputImage, TOutputImage >::GetIntensityScale () virtual
template<class TInputImage , class TOutputImage > virtual const char* itk::StructureTensorImageFilter< TInputImage, TOutputImage >::GetNameOfClass () const virtual
Run-time type information (and related methods).
Referenced by itk::StructureTensorImageFilter< TInputImage, TOutputImage >::InternalClone().
template<class TInputImage , class TOutputImage > LightObject::Pointer itk::StructureTensorImageFilter< TInputImage, TOutputImage >::InternalClone () const protected
Definition at line 33 of file itkStructureTensorImageFilter.hxx.
References itk::StructureTensorImageFilter< TInputImage, TOutputImage >::GetNameOfClass(), and itk::StructureTensorImageFilter< TInputImage, TOutputImage >::m_IntensityScale.
Referenced by itk::StructureTensorImageFilter< TInputImage, TOutputImage >::StructureTensorImageFilter().
template<class TInputImage , class TOutputImage > static Pointer itk::StructureTensorImageFilter< TInputImage, TOutputImage >::New () static
Method for creation through the object factory.
template<class TInputImage , class TOutputImage > void itk::StructureTensorImageFilter< TInputImage, TOutputImage >::operator= (const Self &) private
template<class TInputImage , class TOutputImage > void itk::StructureTensorImageFilter< TInputImage, TOutputImage >::PrintSelf (std::ostream & os, Indent indent) const inline protected
Definition at line 66 of file itkStructureTensorImageFilter.h.
References itk::StructureTensorImageFilter< TInputImage, TOutputImage >::m_IntensityScale.
template<class TInputImage , class TOutputImage > virtual void itk::StructureTensorImageFilter< TInputImage, TOutputImage >::SetIntensityScale (double _arg) virtual
Member Data Documentation
template<class TInputImage , class TOutputImage > double itk::StructureTensorImageFilter< TInputImage, TOutputImage >::m_IntensityScale protected
scale the gradient.
Definition at line 73 of file itkStructureTensorImageFilter.h.
Referenced by itk::StructureTensorImageFilter< TInputImage, TOutputImage >::GenerateData(), itk::StructureTensorImageFilter< TInputImage, TOutputImage >::InternalClone(), itk::StructureTensorImageFilter< TInputImage, TOutputImage >::PrintSelf(), and itk::StructureTensorImageFilter< TInputImage, TOutputImage >::StructureTensorImageFilter().
The documentation for this class was generated from the following files:
Modules/Common/include/itkStructureTensorImageFilter.h
Modules/Common/include/itkStructureTensorImageFilter.hxx