DMRITool: itk::VectorImageChannelFilter< TInputImage, TOutputImage, TFilter > Class Template Reference
itk::VectorImageChannelFilter< TInputImage, TOutputImage, TFilter > Class Template Reference
#include <itkVectorImageChannelFilter.h>
Detailed Description
template<class TInputImage, class TOutputImage, class TFilter = ImageToImageFilter< Image<typename TInputImage::InternalPixelType, TInputImage::ImageDimension>, TOutputImage>>
class itk::VectorImageChannelFilter< TInputImage, TOutputImage, TFilter >
TInputImage and TOutputImage are VectorImage, TFilter is an image filter which works for itk::Image. This class performs TFilter on each channel of TInputImage, then compose results into output.
Author
Jian Cheng (JC), jian..nosp@m.chen.nosp@m.g.198.nosp@m.3@gm.nosp@m.ail.c.nosp@m.om
Definition at line 29 of file itkVectorImageChannelFilter.h.
Public Types
typedef SmartPointer< const Self > ConstPointer
typedef InputImageType::ConstPointer InputImageConstPointer
typedef InputImageType::IndexType InputImageIndexType
typedef InputImageType::PixelType InputImagePixelType
typedef InputImageType::Pointer InputImagePointer
typedef InputImageType::RegionType InputImageRegionType
typedef InputImageType::SizeType InputImageSizeType
typedef InputImageType::SpacingType InputImageSpacingType
typedef TInputImage InputImageType
typedef OutputImageType::IndexType OutputImageIndexType
typedef OutputImageType::PixelType OutputImagePixelType
typedef OutputImageType::Pointer OutputImagePointer
typedef OutputImageType::RegionType OutputImageRegionType
typedef OutputImageType::SizeType OutputImageSizeType
typedef OutputImageType::SpacingType OutputImageSpacingType
typedef TOutputImage OutputImageType
typedef SmartPointer< Self > Pointer
typedef VectorImageChannelFilter Self
typedef ImageToImageFilter< TInputImage, TOutputImage > Superclass
Public Member Functions
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual TFilter::Pointer GetFilter ()
virtual const char * GetNameOfClass () const
virtual void SetFilter (typename TFilter::Pointer _arg)
Static Public Member Functions
static Pointer New ()
Static Public Attributes
static const unsigned int InputImageDimension = TInputImage::ImageDimension
static const unsigned int OutputImageDimension = TOutputImage::ImageDimension
Protected Member Functions
void GenerateData () ITK_OVERRIDE
LightObject::Pointer InternalClone () const ITK_OVERRIDE
virtual void PrintSelf (std::ostream &os, Indent indent) const ITK_OVERRIDE
VectorImageChannelFilter ()
virtual ~VectorImageChannelFilter ()
Protected Attributes
TFilter::Pointer m_Filter
Private Member Functions
void operator= (const Self &)
VectorImageChannelFilter (const Self &)
Member Typedef Documentation
template<class TInputImage , class TOutputImage , class TFilter = ImageToImageFilter< Image<typename TInputImage::InternalPixelType, TInputImage::ImageDimension>, TOutputImage>> typedef SmartPointer< const Self > itk::VectorImageChannelFilter< TInputImage, TOutputImage, TFilter >::ConstPointer
Definition at line 37 of file itkVectorImageChannelFilter.h.
template<class TInputImage , class TOutputImage , class TFilter = ImageToImageFilter< Image<typename TInputImage::InternalPixelType, TInputImage::ImageDimension>, TOutputImage>> typedef InputImageType::ConstPointer itk::VectorImageChannelFilter< TInputImage, TOutputImage, TFilter >::InputImageConstPointer
Definition at line 47 of file itkVectorImageChannelFilter.h.
template<class TInputImage , class TOutputImage , class TFilter = ImageToImageFilter< Image<typename TInputImage::InternalPixelType, TInputImage::ImageDimension>, TOutputImage>> typedef InputImageType::IndexType itk::VectorImageChannelFilter< TInputImage, TOutputImage, TFilter >::InputImageIndexType
Definition at line 48 of file itkVectorImageChannelFilter.h.
template<class TInputImage , class TOutputImage , class TFilter = ImageToImageFilter< Image<typename TInputImage::InternalPixelType, TInputImage::ImageDimension>, TOutputImage>> typedef InputImageType::PixelType itk::VectorImageChannelFilter< TInputImage, TOutputImage, TFilter >::InputImagePixelType
Definition at line 51 of file itkVectorImageChannelFilter.h.
template<class TInputImage , class TOutputImage , class TFilter = ImageToImageFilter< Image<typename TInputImage::InternalPixelType, TInputImage::ImageDimension>, TOutputImage>> typedef InputImageType::Pointer itk::VectorImageChannelFilter< TInputImage, TOutputImage, TFilter >::InputImagePointer
Definition at line 46 of file itkVectorImageChannelFilter.h.
template<class TInputImage , class TOutputImage , class TFilter = ImageToImageFilter< Image<typename TInputImage::InternalPixelType, TInputImage::ImageDimension>, TOutputImage>> typedef InputImageType::RegionType itk::VectorImageChannelFilter< TInputImage, TOutputImage, TFilter >::InputImageRegionType
Definition at line 52 of file itkVectorImageChannelFilter.h.
template<class TInputImage , class TOutputImage , class TFilter = ImageToImageFilter< Image<typename TInputImage::InternalPixelType, TInputImage::ImageDimension>, TOutputImage>> typedef InputImageType::SizeType itk::VectorImageChannelFilter< TInputImage, TOutputImage, TFilter >::InputImageSizeType
Definition at line 49 of file itkVectorImageChannelFilter.h.
template<class TInputImage , class TOutputImage , class TFilter = ImageToImageFilter< Image<typename TInputImage::InternalPixelType, TInputImage::ImageDimension>, TOutputImage>> typedef InputImageType::SpacingType itk::VectorImageChannelFilter< TInputImage, TOutputImage, TFilter >::InputImageSpacingType
Definition at line 50 of file itkVectorImageChannelFilter.h.
template<class TInputImage , class TOutputImage , class TFilter = ImageToImageFilter< Image<typename TInputImage::InternalPixelType, TInputImage::ImageDimension>, TOutputImage>> typedef TInputImage itk::VectorImageChannelFilter< TInputImage, TOutputImage, TFilter >::InputImageType
Definition at line 43 of file itkVectorImageChannelFilter.h.
template<class TInputImage , class TOutputImage , class TFilter = ImageToImageFilter< Image<typename TInputImage::InternalPixelType, TInputImage::ImageDimension>, TOutputImage>> typedef OutputImageType::IndexType itk::VectorImageChannelFilter< TInputImage, TOutputImage, TFilter >::OutputImageIndexType
Definition at line 56 of file itkVectorImageChannelFilter.h.
template<class TInputImage , class TOutputImage , class TFilter = ImageToImageFilter< Image<typename TInputImage::InternalPixelType, TInputImage::ImageDimension>, TOutputImage>> typedef OutputImageType::PixelType itk::VectorImageChannelFilter< TInputImage, TOutputImage, TFilter >::OutputImagePixelType
Definition at line 59 of file itkVectorImageChannelFilter.h.
template<class TInputImage , class TOutputImage , class TFilter = ImageToImageFilter< Image<typename TInputImage::InternalPixelType, TInputImage::ImageDimension>, TOutputImage>> typedef OutputImageType::Pointer itk::VectorImageChannelFilter< TInputImage, TOutputImage, TFilter >::OutputImagePointer
Definition at line 55 of file itkVectorImageChannelFilter.h.
template<class TInputImage , class TOutputImage , class TFilter = ImageToImageFilter< Image<typename TInputImage::InternalPixelType, TInputImage::ImageDimension>, TOutputImage>> typedef OutputImageType::RegionType itk::VectorImageChannelFilter< TInputImage, TOutputImage, TFilter >::OutputImageRegionType
Definition at line 60 of file itkVectorImageChannelFilter.h.
template<class TInputImage , class TOutputImage , class TFilter = ImageToImageFilter< Image<typename TInputImage::InternalPixelType, TInputImage::ImageDimension>, TOutputImage>> typedef OutputImageType::SizeType itk::VectorImageChannelFilter< TInputImage, TOutputImage, TFilter >::OutputImageSizeType
Definition at line 57 of file itkVectorImageChannelFilter.h.
template<class TInputImage , class TOutputImage , class TFilter = ImageToImageFilter< Image<typename TInputImage::InternalPixelType, TInputImage::ImageDimension>, TOutputImage>> typedef OutputImageType::SpacingType itk::VectorImageChannelFilter< TInputImage, TOutputImage, TFilter >::OutputImageSpacingType
Definition at line 58 of file itkVectorImageChannelFilter.h.
template<class TInputImage , class TOutputImage , class TFilter = ImageToImageFilter< Image<typename TInputImage::InternalPixelType, TInputImage::ImageDimension>, TOutputImage>> typedef TOutputImage itk::VectorImageChannelFilter< TInputImage, TOutputImage, TFilter >::OutputImageType
Definition at line 54 of file itkVectorImageChannelFilter.h.
template<class TInputImage , class TOutputImage , class TFilter = ImageToImageFilter< Image<typename TInputImage::InternalPixelType, TInputImage::ImageDimension>, TOutputImage>> typedef SmartPointer< Self > itk::VectorImageChannelFilter< TInputImage, TOutputImage, TFilter >::Pointer
Definition at line 36 of file itkVectorImageChannelFilter.h.
template<class TInputImage , class TOutputImage , class TFilter = ImageToImageFilter< Image<typename TInputImage::InternalPixelType, TInputImage::ImageDimension>, TOutputImage>> typedef VectorImageChannelFilter itk::VectorImageChannelFilter< TInputImage, TOutputImage, TFilter >::Self
Standard class typedefs.
Definition at line 34 of file itkVectorImageChannelFilter.h.
template<class TInputImage , class TOutputImage , class TFilter = ImageToImageFilter< Image<typename TInputImage::InternalPixelType, TInputImage::ImageDimension>, TOutputImage>> typedef ImageToImageFilter< TInputImage, TOutputImage > itk::VectorImageChannelFilter< TInputImage, TOutputImage, TFilter >::Superclass
Definition at line 35 of file itkVectorImageChannelFilter.h.
Constructor & Destructor Documentation
template<class TInputImage , class TOutputImage , class TFilter > itk::VectorImageChannelFilter< TInputImage, TOutputImage, TFilter >::VectorImageChannelFilter () protected
Definition at line 24 of file itkVectorImageChannelFilter.hxx.
References itk::VectorImageChannelFilter< TInputImage, TOutputImage, TFilter >::InternalClone().
template<class TInputImage , class TOutputImage , class TFilter = ImageToImageFilter< Image<typename TInputImage::InternalPixelType, TInputImage::ImageDimension>, TOutputImage>> virtual itk::VectorImageChannelFilter< TInputImage, TOutputImage, TFilter >::~VectorImageChannelFilter () inline protected virtual
Definition at line 70 of file itkVectorImageChannelFilter.h.
References ITK_OVERRIDE.
template<class TInputImage , class TOutputImage , class TFilter = ImageToImageFilter< Image<typename TInputImage::InternalPixelType, TInputImage::ImageDimension>, TOutputImage>> itk::VectorImageChannelFilter< TInputImage, TOutputImage, TFilter >::VectorImageChannelFilter (const Self &) private
Member Function Documentation
template<class TInputImage , class TOutputImage , class TFilter = ImageToImageFilter< Image<typename TInputImage::InternalPixelType, TInputImage::ImageDimension>, TOutputImage>> virtual::itk::LightObject::Pointer itk::VectorImageChannelFilter< TInputImage, TOutputImage, TFilter >::CreateAnother (void) const
template<class TInputImage , class TOutputImage , class TFilter > void itk::VectorImageChannelFilter< TInputImage, TOutputImage, TFilter >::GenerateData (void) protected
Definition at line 58 of file itkVectorImageChannelFilter.hxx.
References utlException.
Referenced by itk::VectorImageChannelFilter< TInputImage, TOutputImage, TFilter >::PrintSelf().
template<class TInputImage , class TOutputImage , class TFilter = ImageToImageFilter< Image<typename TInputImage::InternalPixelType, TInputImage::ImageDimension>, TOutputImage>> virtual TFilter::Pointer itk::VectorImageChannelFilter< TInputImage, TOutputImage, TFilter >::GetFilter () virtual
template<class TInputImage , class TOutputImage , class TFilter = ImageToImageFilter< Image<typename TInputImage::InternalPixelType, TInputImage::ImageDimension>, TOutputImage>> virtual const char* itk::VectorImageChannelFilter< TInputImage, TOutputImage, TFilter >::GetNameOfClass () const virtual
Run-time type information (and related methods).
template<class TInputImage , class TOutputImage , class TFilter > LightObject::Pointer itk::VectorImageChannelFilter< TInputImage, TOutputImage, TFilter >::InternalClone () const protected
Definition at line 32 of file itkVectorImageChannelFilter.hxx.
References itk::VectorImageChannelFilter< TInputImage, TOutputImage, TFilter >::PrintSelf().
Referenced by itk::VectorImageChannelFilter< TInputImage, TOutputImage, TFilter >::VectorImageChannelFilter().
template<class TInputImage , class TOutputImage , class TFilter = ImageToImageFilter< Image<typename TInputImage::InternalPixelType, TInputImage::ImageDimension>, TOutputImage>> static Pointer itk::VectorImageChannelFilter< TInputImage, TOutputImage, TFilter >::New () static
Method for creation through the object factory.
template<class TInputImage , class TOutputImage , class TFilter = ImageToImageFilter< Image<typename TInputImage::InternalPixelType, TInputImage::ImageDimension>, TOutputImage>> void itk::VectorImageChannelFilter< TInputImage, TOutputImage, TFilter >::operator= (const Self &) private
template<class TInputImage , class TOutputImage , class TFilter > void itk::VectorImageChannelFilter< TInputImage, TOutputImage, TFilter >::PrintSelf (std::ostream & os, Indent indent) const protected virtual
Definition at line 48 of file itkVectorImageChannelFilter.hxx.
References itk::VectorImageChannelFilter< TInputImage, TOutputImage, TFilter >::GenerateData().
Referenced by itk::VectorImageChannelFilter< TInputImage, TOutputImage, TFilter >::InternalClone().
template<class TInputImage , class TOutputImage , class TFilter = ImageToImageFilter< Image<typename TInputImage::InternalPixelType, TInputImage::ImageDimension>, TOutputImage>> virtual void itk::VectorImageChannelFilter< TInputImage, TOutputImage, TFilter >::SetFilter (typename TFilter::Pointer _arg) virtual
Member Data Documentation
template<class TInputImage , class TOutputImage , class TFilter = ImageToImageFilter< Image<typename TInputImage::InternalPixelType, TInputImage::ImageDimension>, TOutputImage>> const unsigned int itk::VectorImageChannelFilter< TInputImage, TOutputImage, TFilter >::InputImageDimension = TInputImage::ImageDimension static
Definition at line 62 of file itkVectorImageChannelFilter.h.
template<class TInputImage , class TOutputImage , class TFilter = ImageToImageFilter< Image<typename TInputImage::InternalPixelType, TInputImage::ImageDimension>, TOutputImage>> TFilter::Pointer itk::VectorImageChannelFilter< TInputImage, TOutputImage, TFilter >::m_Filter protected
Definition at line 78 of file itkVectorImageChannelFilter.h.
template<class TInputImage , class TOutputImage , class TFilter = ImageToImageFilter< Image<typename TInputImage::InternalPixelType, TInputImage::ImageDimension>, TOutputImage>> const unsigned int itk::VectorImageChannelFilter< TInputImage, TOutputImage, TFilter >::OutputImageDimension = TOutputImage::ImageDimension static
Definition at line 63 of file itkVectorImageChannelFilter.h.
The documentation for this class was generated from the following files:
Modules/Common/include/itkVectorImageChannelFilter.h
Modules/Common/include/itkVectorImageChannelFilter.hxx