DMRITool: Applications/DiffusionModels/ComputeSHCoefficientsOfDWIFromSymmetricTensor.cxx File Reference
ComputeSHCoefficientsOfDWIFromSymmetricTensor.cxx File Reference
#include "ComputeSHCoefficientsOfDWIFromSymmetricTensorCLP.h"
#include "itkSpecialFunctionGenerator.h"
#include "utlCore.h"
Functions
void DoMain (std::vector< double > &e1e2, std::vector< double > &bvec, const int shOrder, std::ostream &os, const bool outputAll, const bool nob)
int main (int argc, char const *argv[])
Detailed Description
Author
Dr. Jian Cheng (JC), jian..nosp@m.chen.nosp@m.g.198.nosp@m.3@gm.nosp@m.ail.c.nosp@m.om
Definition in file ComputeSHCoefficientsOfDWIFromSymmetricTensor.cxx.
Function Documentation
void DoMain (std::vector< double > & e1e2, std::vector< double > & bvec, const int shOrder, std::ostream & os, const bool outputAll, const bool nob)
Definition at line 23 of file ComputeSHCoefficientsOfDWIFromSymmetricTensor.cxx.
References utl::GetIndexSHj().
Referenced by main().
int main (int argc, char const * argv[])
Compute SH coefficients of DWI signal in DTI with symmetric tensor (along z-axis).
Author
Jian Cheng (jian..nosp@m.chen.nosp@m.g.198.nosp@m.3@gm.nosp@m.ail.c.nosp@m.om)
Definition at line 54 of file ComputeSHCoefficientsOfDWIFromSymmetricTensor.cxx.
References DoMain(), utl::GetE1E2FromFAMD(), itk::InitializeLUTExp(), and utlGlobalException.