DMRITool: Applications/DWIProcessing/DWIMultipleShellSplit.cxx File Reference
DWIMultipleShellSplit.cxx File Reference
#include "utl.h"
#include "DWIMultipleShellSplitCLP.h"
Functions
int main (int argc, char const *argv[])
Detailed Description
Author
Dr. Jian Cheng (JC), jian..nosp@m.chen.nosp@m.g.198.nosp@m.3@gm.nosp@m.ail.c.nosp@m.om
Definition in file DWIMultipleShellSplit.cxx.
Function Documentation
int main (int argc, char const * argv[])
Split mutiple shell DWI data into several single shell data.
Definition at line 26 of file DWIMultipleShellSplit.cxx.
References utl::ConvertNumberToString(), utl::GetFileExtension(), utl::ReadLinesFirstlineCheck(), utl::ReadVector(), utl::Save2DVector(), utl::SaveVector(), utl::SelectVector(), utl::SeparateVector(), and utlException.