DMRITool: Applications/DWIProcessing/DWISingleVoxelSimulator.cxx File Reference
DWISingleVoxelSimulator.cxx File Reference
#include "itkDWISingleVoxelGenerator.h"
#include "DWISingleVoxelSimulatorCLP.h"
#include "itkDWIWriter.h"
Functions
int main (int argc, char const *argv[])
Detailed Description
Author
Dr. Jian Cheng (JC), jian..nosp@m.chen.nosp@m.g.198.nosp@m.3@gm.nosp@m.ail.c.nosp@m.om
Definition in file DWISingleVoxelSimulator.cxx.
Function Documentation
int main (int argc, char const * argv[])
Simulate DWI data with fixed single voxel configuration.
Author
Jian Cheng (jian..nosp@m.chen.nosp@m.g.198.nosp@m.3@gm.nosp@m.ail.c.nosp@m.om)
Definition at line 27 of file DWISingleVoxelSimulator.cxx.
References CARTESIAN_TO_CARTESIAN, DIRECTION_NODUPLICATE, utl::GetFileExtension(), itk::PeakContainerHelper::GetPeakType(), itk::IsImageEmpty(), utl::MatchBVectorAndGradientMatrix(), utl::ReadVector(), utlException, utlGlobalException, and utlSAGlobalException.