DMRITool: Applications/DWIProcessing/DWISimulator.cxx File Reference
DWISimulator.cxx File Reference
#include <iostream>
#include <fstream>
#include "DWISimulatorCLP.h"
#include "itkImageFileWriter.h"
#include "itkVectorImage.h"
#include "itkDWIGenerator.h"
#include "itkDWIWriter.h"
#include "utl.h"
Functions
int main (int argc, char *argv[])
Function Documentation
int main (int argc, char * argv[])
Definition at line 32 of file DWISimulator.cxx.
References CARTESIAN_TO_CARTESIAN, DIRECTION_NODUPLICATE, utl::GetFileExtension(), itk::PeakContainerHelper::GetPeakType(), itk::IsImageEmpty(), utl::MatchBVectorAndGradientMatrix(), utl::ReadVector(), utlException, utlGlobalException, and utlSAGlobalException.