DMRITool: UtlNDArray
UtlNDArray
Utl
Namespaces
utl
Classes
class utl::BinaryOpExpr< OP, TLeft, TRight >
class utl::BinaryOpExpr< OP, ScalarExprBase< ValueT >, TRight >
class utl::BinaryOpExpr< OP, ScalarExprBase< ValueT1 >, ScalarExprBase< ValueT2 > >
class utl::BinaryOpExpr< OP, TLeft, ScalarExprBase< ValueT > >
class utl::Expr< SubType, ValueT >
class utl::NDArray< T, Dim >
class utl::NDArray< T, 1 >
class utl::NDArray< T, 2 >
class utl::NDArray< T, 4 >
class utl::NDArrayBase< T, Dim >
class utl::ScalarExprBase< ValueT >
class utl::UnaryOpExpr< OP, EType >
Macros
#define __BinaryOpExpr_Op(name, op)
#define __UnaryOpExpr_Op(name, op)
Typedefs
template<class TExpr >
using utl::Expr1ValueType = typename TExpr::ValueType
template<class TLeft , class TRight >
using utl::Expr2ValueType = typename SuperFloatType< typename TLeft::ValueType, typename TRight::ValueType >::type
typedef ScalarExprBase< std::complex< double > > utl::ScalarComplexExpr
typedef ScalarExprBase< double > utl::ScalarExpr
template<class T1 , class T2 >
using utl::SuperType = typename SuperFloatType< T1, T2 >::type
Functions
template<typename OP , typename TLeft , typename TRight >
BinaryOpExpr< OP, TLeft, TRight > utl::F (const Expr< TLeft, typename TLeft::ValueType > &lhs, const Expr< TRight, typename TRight::ValueType > &rhs)
template<typename OP , typename TA >
BinaryOpExpr< OP, TA, ScalarExpr > utl::F (const Expr< TA, typename TA::ValueType > &lhs, const ScalarExpr &rhs)
template<typename OP , typename TB >
BinaryOpExpr< OP, ScalarExpr, TB > utl::F (const ScalarExpr &lhs, const Expr< TB, typename TB::ValueType > &rhs)
template<typename OP , typename TA >
BinaryOpExpr< OP, TA, ScalarComplexExpr > utl::F (const Expr< TA, typename TA::ValueType > &lhs, const ScalarComplexExpr &rhs)
template<typename OP , typename TB >
BinaryOpExpr< OP, ScalarComplexExpr, TB > utl::F (const ScalarComplexExpr &lhs, const Expr< TB, typename TB::ValueType > &rhs)
template<typename OP , typename EType >
UnaryOpExpr< OP, EType > utl::F (const Expr< EType, typename EType::ValueType > &expr)
template<typename OP , typename TA , typename TB >
BinaryOpExpr< OP, TA, TB > utl::MakeExpr (const Expr< TA, typename TA::ValueType > &lhs, const Expr< TB, typename TB::ValueType > &rhs)
template<typename OP , typename EType >
UnaryOpExpr< OP, EType > utl::MakeExpr (const Expr< EType, typename EType::ValueType > &expr)
template<typename TLeft , typename TRight >
BinaryOpExpr< std::multiplies< Expr2ValueType< TLeft, TRight > >, TLeft, TRight > utl::operator% (const Expr< TLeft, typename TLeft::ValueType > &lhs, const Expr< TRight, typename TRight::ValueType > &rhs)
template<typename TRight >
BinaryOpExpr< std::multiplies< Expr2ValueType< ScalarExpr, TRight > >, ScalarExpr, TRight > utl::operator% (const ScalarExpr &lhs, const Expr< TRight, typename TRight::ValueType > &rhs)
template<typename TLeft >
BinaryOpExpr< std::multiplies< Expr2ValueType< TLeft, ScalarExpr > >, TLeft, ScalarExpr > utl::operator% (const Expr< TLeft, typename TLeft::ValueType > &lhs, const ScalarExpr &rhs)
template<typename TLeft >
BinaryOpExpr< std::multiplies< Expr2ValueType< TLeft, ScalarComplexExpr > >, TLeft, ScalarComplexExpr > utl::operator% (const Expr< TLeft, typename TLeft::ValueType > &lhs, const std::complex< double > rhs)
template<typename TRight >
BinaryOpExpr< std::multiplies< Expr2ValueType< ScalarExpr, TRight > >, ScalarExpr, TRight > utl::operator% (const double lhs, const Expr< TRight, typename TRight::ValueType > &rhs)
template<typename TLeft >
BinaryOpExpr< std::multiplies< Expr2ValueType< TLeft, ScalarExpr > >, TLeft, ScalarExpr > utl::operator% (const Expr< TLeft, typename TLeft::ValueType > &lhs, const double rhs)
template<typename TRight >
BinaryOpExpr< std::multiplies< Expr2ValueType< ScalarComplexExpr, TRight > >, ScalarComplexExpr, TRight > utl::operator% (const std::complex< double > lhs, const Expr< TRight, typename TRight::ValueType > &rhs)
template<typename TRight >
BinaryOpExpr< std::plus< Expr2ValueType< ScalarExpr, TRight > >, ScalarExpr, TRight > utl::operator+ (const ScalarExpr &lhs, const Expr< TRight, typename TRight::ValueType > &rhs)
template<typename TLeft >
BinaryOpExpr< std::plus< Expr2ValueType< TLeft, ScalarExpr > >, TLeft, ScalarExpr > utl::operator+ (const Expr< TLeft, typename TLeft::ValueType > &lhs, const ScalarExpr &rhs)
template<typename TRight >
BinaryOpExpr< std::plus< Expr2ValueType< ScalarExpr, TRight > >, ScalarExpr, TRight > utl::operator+ (const double lhs, const Expr< TRight, typename TRight::ValueType > &rhs)
template<typename TLeft >
BinaryOpExpr< std::plus< Expr2ValueType< TLeft, ScalarExpr > >, TLeft, ScalarExpr > utl::operator+ (const Expr< TLeft, typename TLeft::ValueType > &lhs, const double rhs)
template<typename TRight >
BinaryOpExpr< std::plus< Expr2ValueType< ScalarComplexExpr, TRight > >, ScalarComplexExpr, TRight > utl::operator+ (const std::complex< double > lhs, const Expr< TRight, typename TRight::ValueType > &rhs)
template<typename TLeft >
BinaryOpExpr< std::plus< Expr2ValueType< TLeft, ScalarComplexExpr > >, TLeft, ScalarComplexExpr > utl::operator+ (const Expr< TLeft, typename TLeft::ValueType > &lhs, const std::complex< double > rhs)
template<typename TLeft , typename TRight >
BinaryOpExpr< std::plus< Expr2ValueType< TLeft, TRight > >, TLeft, TRight > utl::operator+ (const Expr< TLeft, typename TLeft::ValueType > &lhs, const Expr< TRight, typename TRight::ValueType > &rhs)
template<typename TLeft >
BinaryOpExpr< std::minus< Expr2ValueType< TLeft, ScalarExpr > >, TLeft, ScalarExpr > utl::operator- (const Expr< TLeft, typename TLeft::ValueType > &lhs, const ScalarExpr &rhs)
template<typename TRight >
BinaryOpExpr< std::minus< Expr2ValueType< ScalarExpr, TRight > >, ScalarExpr, TRight > utl::operator- (const double lhs, const Expr< TRight, typename TRight::ValueType > &rhs)
template<typename TRight >
BinaryOpExpr< std::minus< Expr2ValueType< ScalarComplexExpr, TRight > >, ScalarComplexExpr, TRight > utl::operator- (const std::complex< double > lhs, const Expr< TRight, typename TRight::ValueType > &rhs)
template<typename TLeft >
BinaryOpExpr< std::minus< Expr2ValueType< TLeft, ScalarExpr > >, TLeft, ScalarExpr > utl::operator- (const Expr< TLeft, typename TLeft::ValueType > &lhs, const double rhs)
template<typename TLeft >
BinaryOpExpr< std::minus< Expr2ValueType< TLeft, ScalarComplexExpr > >, TLeft, ScalarComplexExpr > utl::operator- (const Expr< TLeft, typename TLeft::ValueType > &lhs, const std::complex< double > rhs)
template<typename TLeft , typename TRight >
BinaryOpExpr< std::minus< Expr2ValueType< TLeft, TRight > >, TLeft, TRight > utl::operator- (const Expr< TLeft, typename TLeft::ValueType > &lhs, const Expr< TRight, typename TRight::ValueType > &rhs)
template<typename TRight >
BinaryOpExpr< std::minus< Expr2ValueType< ScalarExpr, TRight > >, ScalarExpr, TRight > utl::operator- (const ScalarExpr &lhs, const Expr< TRight, typename TRight::ValueType > &rhs)
template<typename TExpr >
UnaryOpExpr< std::negate< typename TExpr::ValueType >, TExpr > utl::operator- (const Expr< TExpr, typename TExpr::ValueType > &lhs)
template<typename TRight >
BinaryOpExpr< std::divides< Expr2ValueType< ScalarExpr, TRight > >, ScalarExpr, TRight > utl::operator/ (const double lhs, const Expr< TRight, typename TRight::ValueType > &rhs)
template<typename TLeft >
BinaryOpExpr< std::divides< Expr2ValueType< TLeft, ScalarExpr > >, TLeft, ScalarExpr > utl::operator/ (const Expr< TLeft, typename TLeft::ValueType > &lhs, const ScalarExpr &rhs)
template<typename TLeft , typename TRight >
BinaryOpExpr< std::divides< Expr2ValueType< TLeft, TRight > >, TLeft, TRight > utl::operator/ (const Expr< TLeft, typename TLeft::ValueType > &lhs, const Expr< TRight, typename TRight::ValueType > &rhs)
template<typename TLeft >
BinaryOpExpr< std::divides< Expr2ValueType< TLeft, ScalarComplexExpr > >, TLeft, ScalarComplexExpr > utl::operator/ (const Expr< TLeft, typename TLeft::ValueType > &lhs, const std::complex< double > rhs)
template<typename TRight >
BinaryOpExpr< std::divides< Expr2ValueType< ScalarComplexExpr, TRight > >, ScalarComplexExpr, TRight > utl::operator/ (const std::complex< double > lhs, const Expr< TRight, typename TRight::ValueType > &rhs)
template<typename TLeft >
BinaryOpExpr< std::divides< Expr2ValueType< TLeft, ScalarExpr > >, TLeft, ScalarExpr > utl::operator/ (const Expr< TLeft, typename TLeft::ValueType > &lhs, const double rhs)
template<typename TRight >
BinaryOpExpr< std::divides< Expr2ValueType< ScalarExpr, TRight > >, ScalarExpr, TRight > utl::operator/ (const ScalarExpr &lhs, const Expr< TRight, typename TRight::ValueType > &rhs)
template<class T >
using utl::Vector = NDArray< T, 1 >
template<class T >
using utl::Matrix = NDArray< T, 2 >
#define __utl_ndarray_alloc_blah(shape)
Detailed Description
utl::NDArray with supports for expression template, blas, mkl.
Macro Definition Documentation
#define __BinaryOpExpr_Op (name, op)
define expressions for binary math operators
Definition at line 366 of file utlExpression.h.
#define __UnaryOpExpr_Op (name, op)
Value:
template<typename TExpr>                                                  \
inline UnaryOpExpr<name<typename TExpr::ValueType>,TExpr>                 \
operator op (const Expr<TExpr, typename TExpr::ValueType>& lhs){          \
    return MakeExpr<name<typename TExpr::ValueType>>(lhs);                \
}                                                                         \
define expressions for unary math operators
Definition at line 457 of file utlExpression.h.
#define __utl_ndarray_alloc_blah (shape)
Value:
do {                                                                                      \
  for ( int i = 0; i < this->Dimension; ++i )                                             \
    this->m_Shape[i] = shape[i];                                                          \
  this->ComputeOffSetTable();                                                             \
  SizeType size = this->GetSize();                                                        \
  this->m_Data = (size>0) ? (new T[size]) : NULL;                                         \
  this->m_IsShared = false;                                                               \
} while (false)
Definition at line 30 of file utlNDArray.h.
Referenced by utl::NDArray< T, 2 >::NDArray(), utl::NDArray< T, 4 >::NDArray(), utl::NDArray< T, 1 >::NDArray(), and utl::NDArrayBase< T, 4 >::NDArrayBase().
Typedef Documentation
template<class TExpr > using utl::Expr1ValueType = typedef typename TExpr::ValueType
Definition at line 31 of file utlExpression.h.
template<class TLeft , class TRight > using utl::Expr2ValueType = typedef typename SuperFloatType<typename TLeft::ValueType, typename TRight::ValueType>::type
Definition at line 34 of file utlExpression.h.
template<class T > using utl::Matrix = typedef NDArray<T,2>
Definition at line 45 of file utlNDArray.h.
utl::ScalarComplexExpr
ScalarExprBase<std::complex<double> >
Definition at line 48 of file utlExpression.h.
utl::ScalarExpr
ScalarExprBase<double>
Definition at line 43 of file utlExpression.h.
template<class T1 , class T2 > using utl::SuperType = typedef typename SuperFloatType<T1, T2>::type
Definition at line 28 of file utlExpression.h.
template<class T > using utl::Vector = typedef NDArray<T,1>
Definition at line 44 of file utlNDArray.h.
Function Documentation
template<typename OP , typename TLeft , typename TRight > BinaryOpExpr<OP,TLeft,TRight> utl::F (const Expr< TLeft, typename TLeft::ValueType > & lhs, const Expr< TRight, typename TRight::ValueType > & rhs) inline
Generate a BinaryOpExpr object from two general expressions
Definition at line 332 of file utlExpression.h.
References utl::Expr< SubType, ValueT >::ConstRef().
Referenced by spams::FISTA::SplittingFunction< T >::eval_weighted(), and spams::FISTA::SplittingFunction< T >::reset().
template<typename OP , typename TA > BinaryOpExpr<OP,TA,ScalarExpr > utl::F (const Expr< TA, typename TA::ValueType > & lhs, const ScalarExpr & rhs) inline
Generate a BinaryOpExpr object
Definition at line 340 of file utlExpression.h.
template<typename OP , typename TB > BinaryOpExpr<OP,ScalarExpr,TB> utl::F (const ScalarExpr & lhs, const Expr< TB, typename TB::ValueType > & rhs) inline
Generate a BinaryOpExpr object
Definition at line 346 of file utlExpression.h.
template<typename OP , typename TA > BinaryOpExpr<OP,TA,ScalarComplexExpr > utl::F (const Expr< TA, typename TA::ValueType > & lhs, const ScalarComplexExpr & rhs) inline
Definition at line 351 of file utlExpression.h.
template<typename OP , typename TB > BinaryOpExpr<OP,ScalarComplexExpr,TB> utl::F (const ScalarComplexExpr & lhs, const Expr< TB, typename TB::ValueType > & rhs) inline
Generate a BinaryOpExpr object
Definition at line 357 of file utlExpression.h.
template<typename OP , typename EType > UnaryOpExpr<OP,EType> utl::F (const Expr< EType, typename EType::ValueType > & expr) inline
make unary expression
Definition at line 451 of file utlExpression.h.
template<typename OP , typename TA , typename TB > BinaryOpExpr<OP,TA,TB> utl::MakeExpr (const Expr< TA, typename TA::ValueType > & lhs, const Expr< TB, typename TB::ValueType > & rhs) inline
Generate a BinaryOpExpr object
Definition at line 322 of file utlExpression.h.
References utl::Expr< SubType, ValueT >::ConstRef().
template<typename OP , typename EType > UnaryOpExpr<OP,EType > utl::MakeExpr (const Expr< EType, typename EType::ValueType > & expr) inline
make unary expression
Definition at line 445 of file utlExpression.h.
References utl::Expr< SubType, ValueT >::ConstRef().
template<typename TLeft , typename TRight > BinaryOpExpr< std::multiplies <Expr2ValueType<TLeft,TRight> >,TLeft,TRight> utl::operator% (const Expr< TLeft, typename TLeft::ValueType > & lhs, const Expr< TRight, typename TRight::ValueType > & rhs) inline
Definition at line 406 of file utlExpression.h.
template<typename TRight > BinaryOpExpr< std::multiplies <Expr2ValueType<ScalarExpr,TRight> >,ScalarExpr,TRight> utl::operator% (const ScalarExpr & lhs, const Expr< TRight, typename TRight::ValueType > & rhs) inline
Definition at line 406 of file utlExpression.h.
template<typename TLeft > BinaryOpExpr< std::multiplies <Expr2ValueType<TLeft,ScalarExpr> >, TLeft,ScalarExpr > utl::operator% (const Expr< TLeft, typename TLeft::ValueType > & lhs, const ScalarExpr & rhs) inline
Definition at line 406 of file utlExpression.h.
template<typename TLeft > BinaryOpExpr< std::multiplies <Expr2ValueType<TLeft,ScalarComplexExpr> >, TLeft,ScalarComplexExpr > utl::operator% (const Expr< TLeft, typename TLeft::ValueType > & lhs, const std::complex< double > rhs) inline
Definition at line 406 of file utlExpression.h.
template<typename TRight > BinaryOpExpr< std::multiplies <Expr2ValueType<ScalarExpr,TRight> >,ScalarExpr,TRight> utl::operator% (const double lhs, const Expr< TRight, typename TRight::ValueType > & rhs) inline
Definition at line 406 of file utlExpression.h.
template<typename TLeft > BinaryOpExpr< std::multiplies <Expr2ValueType<TLeft,ScalarExpr> >, TLeft,ScalarExpr > utl::operator% (const Expr< TLeft, typename TLeft::ValueType > & lhs, const double rhs) inline
Definition at line 406 of file utlExpression.h.
template<typename TRight > BinaryOpExpr< std::multiplies <Expr2ValueType<ScalarComplexExpr,TRight> >,ScalarComplexExpr,TRight> utl::operator% (const std::complex< double > lhs, const Expr< TRight, typename TRight::ValueType > & rhs) inline
Definition at line 406 of file utlExpression.h.
template<typename TRight > BinaryOpExpr< std::plus <Expr2ValueType<ScalarExpr,TRight> >,ScalarExpr,TRight> utl::operator+ (const ScalarExpr & lhs, const Expr< TRight, typename TRight::ValueType > & rhs) inline
Definition at line 404 of file utlExpression.h.
template<typename TLeft > BinaryOpExpr< std::plus <Expr2ValueType<TLeft,ScalarExpr> >, TLeft,ScalarExpr > utl::operator+ (const Expr< TLeft, typename TLeft::ValueType > & lhs, const ScalarExpr & rhs) inline
Definition at line 404 of file utlExpression.h.
template<typename TRight > BinaryOpExpr< std::plus <Expr2ValueType<ScalarExpr,TRight> >,ScalarExpr,TRight> utl::operator+ (const double lhs, const Expr< TRight, typename TRight::ValueType > & rhs) inline
Definition at line 404 of file utlExpression.h.
template<typename TLeft > BinaryOpExpr< std::plus <Expr2ValueType<TLeft,ScalarExpr> >, TLeft,ScalarExpr > utl::operator+ (const Expr< TLeft, typename TLeft::ValueType > & lhs, const double rhs) inline
Definition at line 404 of file utlExpression.h.
template<typename TRight > BinaryOpExpr< std::plus <Expr2ValueType<ScalarComplexExpr,TRight> >,ScalarComplexExpr,TRight> utl::operator+ (const std::complex< double > lhs, const Expr< TRight, typename TRight::ValueType > & rhs) inline
Definition at line 404 of file utlExpression.h.
template<typename TLeft > BinaryOpExpr< std::plus <Expr2ValueType<TLeft,ScalarComplexExpr> >, TLeft,ScalarComplexExpr > utl::operator+ (const Expr< TLeft, typename TLeft::ValueType > & lhs, const std::complex< double > rhs) inline
Definition at line 404 of file utlExpression.h.
template<typename TLeft , typename TRight > BinaryOpExpr< std::plus <Expr2ValueType<TLeft,TRight> >,TLeft,TRight> utl::operator+ (const Expr< TLeft, typename TLeft::ValueType > & lhs, const Expr< TRight, typename TRight::ValueType > & rhs) inline
Definition at line 404 of file utlExpression.h.
template<typename TLeft > BinaryOpExpr< std::minus <Expr2ValueType<TLeft,ScalarExpr> >, TLeft,ScalarExpr > utl::operator- (const Expr< TLeft, typename TLeft::ValueType > & lhs, const ScalarExpr & rhs) inline
Definition at line 405 of file utlExpression.h.
template<typename TRight > BinaryOpExpr< std::minus <Expr2ValueType<ScalarExpr,TRight> >,ScalarExpr,TRight> utl::operator- (const double lhs, const Expr< TRight, typename TRight::ValueType > & rhs) inline
Definition at line 405 of file utlExpression.h.
template<typename TRight > BinaryOpExpr< std::minus <Expr2ValueType<ScalarComplexExpr,TRight> >,ScalarComplexExpr,TRight> utl::operator- (const std::complex< double > lhs, const Expr< TRight, typename TRight::ValueType > & rhs) inline
Definition at line 405 of file utlExpression.h.
template<typename TLeft > BinaryOpExpr< std::minus <Expr2ValueType<TLeft,ScalarExpr> >, TLeft,ScalarExpr > utl::operator- (const Expr< TLeft, typename TLeft::ValueType > & lhs, const double rhs) inline
Definition at line 405 of file utlExpression.h.
template<typename TLeft > BinaryOpExpr< std::minus <Expr2ValueType<TLeft,ScalarComplexExpr> >, TLeft,ScalarComplexExpr > utl::operator- (const Expr< TLeft, typename TLeft::ValueType > & lhs, const std::complex< double > rhs) inline
Definition at line 405 of file utlExpression.h.
template<typename TLeft , typename TRight > BinaryOpExpr< std::minus <Expr2ValueType<TLeft,TRight> >,TLeft,TRight> utl::operator- (const Expr< TLeft, typename TLeft::ValueType > & lhs, const Expr< TRight, typename TRight::ValueType > & rhs) inline
Definition at line 405 of file utlExpression.h.
template<typename TRight > BinaryOpExpr< std::minus <Expr2ValueType<ScalarExpr,TRight> >,ScalarExpr,TRight> utl::operator- (const ScalarExpr & lhs, const Expr< TRight, typename TRight::ValueType > & rhs) inline
Definition at line 405 of file utlExpression.h.
template<typename TExpr > UnaryOpExpr< std::negate <typename TExpr::ValueType>,TExpr> utl::operator- (const Expr< TExpr, typename TExpr::ValueType > & lhs) inline
Definition at line 465 of file utlExpression.h.
template<typename TRight > BinaryOpExpr< std::divides <Expr2ValueType<ScalarExpr,TRight> >,ScalarExpr,TRight> utl::operator/ (const double lhs, const Expr< TRight, typename TRight::ValueType > & rhs) inline
Definition at line 407 of file utlExpression.h.
template<typename TLeft > BinaryOpExpr< std::divides <Expr2ValueType<TLeft,ScalarExpr> >, TLeft,ScalarExpr > utl::operator/ (const Expr< TLeft, typename TLeft::ValueType > & lhs, const ScalarExpr & rhs) inline
Definition at line 407 of file utlExpression.h.
template<typename TLeft , typename TRight > BinaryOpExpr< std::divides <Expr2ValueType<TLeft,TRight> >,TLeft,TRight> utl::operator/ (const Expr< TLeft, typename TLeft::ValueType > & lhs, const Expr< TRight, typename TRight::ValueType > & rhs) inline
Definition at line 407 of file utlExpression.h.
template<typename TLeft > BinaryOpExpr< std::divides <Expr2ValueType<TLeft,ScalarComplexExpr> >, TLeft,ScalarComplexExpr > utl::operator/ (const Expr< TLeft, typename TLeft::ValueType > & lhs, const std::complex< double > rhs) inline
Definition at line 407 of file utlExpression.h.
template<typename TRight > BinaryOpExpr< std::divides <Expr2ValueType<ScalarComplexExpr,TRight> >,ScalarComplexExpr,TRight> utl::operator/ (const std::complex< double > lhs, const Expr< TRight, typename TRight::ValueType > & rhs) inline
Definition at line 407 of file utlExpression.h.
template<typename TLeft > BinaryOpExpr< std::divides <Expr2ValueType<TLeft,ScalarExpr> >, TLeft,ScalarExpr > utl::operator/ (const Expr< TLeft, typename TLeft::ValueType > & lhs, const double rhs) inline
Definition at line 407 of file utlExpression.h.
template<typename TRight > BinaryOpExpr< std::divides <Expr2ValueType<ScalarExpr,TRight> >,ScalarExpr,TRight> utl::operator/ (const ScalarExpr & lhs, const Expr< TRight, typename TRight::ValueType > & rhs) inline
Definition at line 407 of file utlExpression.h.