DMRITool: Applications/Utilities/ImageInfo.cxx File Reference
ImageInfo.cxx File Reference
#include <iostream>
#include <stdio.h>
#include <vector>
#include "itkImage.h"
#include "itkImageFileReader.h"
#include "itkMetaDataDictionary.h"
#include "itkMetaDataObject.h"
#include <ImageInfoCLP.h>
#include "utlITK.h"
Enumerations
enum {
OP_NULL,
OP_DIMENSION,
OP_SPACING,
OP_COMPONENT_TYPE,
OP_PIXEL_TYPE,
OP_NUMBER_OF_COMPONENTS,
OP_ENDIANNESS,
OP_SIZE_IN_BYTES,
OP_SIZE_IN_COMPONENTS,
OP_SIZE_IN_PIXELS,
OP_ORIGIN,
OP_META_DATA,
OP_GRADIENTS,
OP_BVALUE,
OP_BVALUES
}
Functions
void IntRangeCheck (int x, int LowerLimit, int UpperLimit)
int main (int argc, char *argv[])
void SetOperationWithChecking (int &operation, int value)
int show_file (const std::string &file)
Enumeration Type Documentation
anonymous enum
Todo:
Report data filename (as in .mhd file)
Enumerator
OP_NULL
OP_DIMENSION
OP_SPACING
OP_COMPONENT_TYPE
OP_PIXEL_TYPE
OP_NUMBER_OF_COMPONENTS
OP_ENDIANNESS
OP_SIZE_IN_BYTES
OP_SIZE_IN_COMPONENTS
OP_SIZE_IN_PIXELS
OP_ORIGIN
OP_META_DATA
OP_GRADIENTS
OP_BVALUE
OP_BVALUES
Definition at line 38 of file ImageInfo.cxx.
Function Documentation
void IntRangeCheck (int x, int LowerLimit, int UpperLimit)
Definition at line 72 of file ImageInfo.cxx.
Referenced by main().
int main (int argc, char * argv[])
Definition at line 98 of file ImageInfo.cxx.
References itk::GetImageType(), IMAGE_SPARSE, IMAGE_VARIABLELENGTH, IntRangeCheck(), OP_BVALUE, OP_BVALUES, OP_COMPONENT_TYPE, OP_DIMENSION, OP_GRADIENTS, OP_META_DATA, OP_NULL, OP_NUMBER_OF_COMPONENTS, OP_ORIGIN, OP_PIXEL_TYPE, OP_SIZE_IN_BYTES, OP_SIZE_IN_COMPONENTS, OP_SIZE_IN_PIXELS, OP_SPACING, SetOperationWithChecking(), and show_file().
void SetOperationWithChecking (int & operation, int value)
Definition at line 58 of file ImageInfo.cxx.
References OP_NULL.
Referenced by main().
int show_file (const std::string & file)
Definition at line 82 of file ImageInfo.cxx.
Referenced by main().