DMRITool: Applications/DiffusionModels/MeanDiffusivityEstimator.cxx File Reference
MeanDiffusivityEstimator.cxx File Reference
#include "MeanDiffusivityEstimatorCLP.h"
#include "utl.h"
#include "itkGeneralizedHighOrderTensorImageFilter.h"
#include "itkDWIReader.h"
#include "itkMeanDiffusivityFromGHOTImageFilter.h"
#include "itkCommandProgressUpdate.h"
Functions
int main (int argc, char const *argv[])
Detailed Description
Author
Dr. Jian Cheng (JC), jian..nosp@m.chen.nosp@m.g.198.nosp@m.3@gm.nosp@m.ail.c.nosp@m.om
Definition in file MeanDiffusivityEstimator.cxx.
Function Documentation
int main (int argc, char const * argv[])
estimate mean diffusivity in each voxel
Definition at line 33 of file MeanDiffusivityEstimator.cxx.
References itk::CommandProgressUpdate::New(), itk::ReadImage(), and itk::SaveImage().