DMRITool: Applications/Visualization/MeshFromPeaks.cxx File Reference
MeshFromPeaks.cxx File Reference
#include "itkMeshFromPeaksImageFilter.h"
#include "MeshFromPeaksCLP.h"
#include "vtkPolyDataWriter.h"
#include "itkCommandProgressUpdate.h"
#include "utl.h"
#include "utlVTK.h"
#include "vtkPolyDataViewer.h"
Functions
int main (int argc, char const *argv[])
Detailed Description
Created "08-29-2016.
Author
Jian Cheng (JC), jian..nosp@m.chen.nosp@m.g.198.nosp@m.3@gm.nosp@m.ail.c.nosp@m.om
Definition in file MeshFromPeaks.cxx.
Function Documentation
int main (int argc, char const * argv[])
Gnerate mesh from peaks.
Definition at line 27 of file MeshFromPeaks.cxx.
References itk::PeakContainerHelper::GetPeakType(), itk::CommandProgressUpdate::New(), itk::ReadVectorImage(), utlGlobalException, vtk::VisualizePolyData(), and utl::WriteVtkPolyData().