DMRITool: Applications/Visualization/MeshFromTracts.cxx File Reference
MeshFromTracts.cxx File Reference
#include "MeshFromTractsCLP.h"
#include "vtkPolyDataWriter.h"
#include "itkCommandProgressUpdate.h"
#include "utl.h"
#include "utlVTK.h"
#include "itkFiberTractsReader.h"
#include "itkMeshFromFiberTractsFilter.h"
#include "vtkPolyDataViewer.h"
Functions
int main (int argc, char const *argv[])
Detailed Description
Created "08-23-2017.
Author
Jian Cheng (JC), jian..nosp@m.chen.nosp@m.g.198.nosp@m.3@gm.nosp@m.ail.c.nosp@m.om
Definition in file MeshFromTracts.cxx.
Function Documentation
int main (int argc, char const * argv[])
Gnerate mesh from peaks.
Definition at line 29 of file MeshFromTracts.cxx.
References itk::FiberTractsReader::New(), utlGlobalException, vtk::VisualizePolyDataWithScalarRange(), and utl::WriteVtkPolyData().