DMRITool: Applications/Visualization/MeshFromSHCoefficients.cxx File Reference
MeshFromSHCoefficients.cxx File Reference
#include "itkMeshFromSHCoefficientsImageFilter.h"
#include "MeshFromSHCoefficientsCLP.h"
#include "vtkPolyDataWriter.h"
#include "itkCommandProgressUpdate.h"
#include "utl.h"
#include "utlVTK.h"
#include "vtkPolyDataViewer.h"
Functions
int main (int argc, char *argv[])
Function Documentation
int main (int argc, char * argv[])
Definition at line 28 of file MeshFromSHCoefficients.cxx.
References utl::DimToRankSH(), utl::GetIndexSHj(), utl::IsEndingWith(), itk::CommandProgressUpdate::New(), spams::FISTA::NONE, utl::PrintVector(), utl::RankToDimSH(), utl::ReadVector(), itk::ReadVectorImage(), utlGlobalException, utl::VectorToVector(), vtk::VisualizePolyData(), and utl::WriteVtkPolyData().