DMRITool: Applications/Visualization/MeshFromTensors.cxx File Reference
MeshFromTensors.cxx File Reference
#include "itkMeshFromTensorImageFilter.h"
#include "MeshFromTensorsCLP.h"
#include "vtkPolyDataWriter.h"
#include "itkCommandProgressUpdate.h"
#include "utl.h"
#include "utlVTK.h"
#include "vtkPolyDataViewer.h"
Functions
int main (int argc, char const *argv[])
Detailed Description
Created "06-19-2017.
Author
Jian Cheng (JC), jian..nosp@m.chen.nosp@m.g.198.nosp@m.3@gm.nosp@m.ail.c.nosp@m.om
Definition in file MeshFromTensors.cxx.
Function Documentation
int main (int argc, char const * argv[])
Gnerate mesh from peaks.
Definition at line 28 of file MeshFromTensors.cxx.
References utl::ConvertTensor6DTo9D(), utl::ConvertTensor9DTo6D(), utl::IsEndingWith(), utl::IsFileExist(), utl::PrintVector(), itk::ReadImage(), utl::ReadVector(), itk::ReadVectorImage(), utl::SetVector(), TENSOR_UPPER_TRIANGULAR, utlGlobalException, utl::VectorToVector(), vtk::VisualizePolyDataWithScalarRange(), and utl::WriteVtkPolyData().