DMRITool: Applications/Visualization/MeshFromSphericalFunctionTessellatedSamples.cxx File Reference
MeshFromSphericalFunctionTessellatedSamples.cxx File Reference
#include "itkMeshFromSphericalFunctionTessellatedSamplesImageFilter.h"
#include "MeshFromSphericalFunctionTessellatedSamplesCLP.h"
#include "vtkPolyDataWriter.h"
#include "utl.h"
#include "utlVTK.h"
#include "vtkPolyDataViewer.h"
#include "itkSpatiallyDenseSparseVectorImage.h"
#include "itkSpatiallyDenseSparseVectorImageFileReader.h"
Functions
int main (int argc, char *argv[])
Detailed Description
Author
Dr. Jian Cheng (JC), jian..nosp@m.chen.nosp@m.g.198.nosp@m.3@gm.nosp@m.ail.c.nosp@m.om
Definition in file MeshFromSphericalFunctionTessellatedSamples.cxx.
Function Documentation
int main (int argc, char * argv[])
Mesh From spherical samples using a given tessellation Create mesh (a spherical function) from discrete samples using tessellation.
Author
Jian Cheng (jian..nosp@m.chen.nosp@m.g.198.nosp@m.3@gm.nosp@m.ail.c.nosp@m.om)
Definition at line 37 of file MeshFromSphericalFunctionTessellatedSamples.cxx.
References CARTESIAN_TO_CARTESIAN, DIRECTION_NODUPLICATE, itk::IsSparseImage(), spams::FISTA::NONE, itk::ReadVectorImage(), utlGlobalException, vtk::VisualizePolyData(), and utl::WriteVtkPolyData().