DMRITool: Applications/Visualization/MeshFromDiscreteFiberODF.cxx File Reference
MeshFromDiscreteFiberODF.cxx File Reference
#include "vtkPolyDataWriter.h"
#include "MeshFromDiscreteFiberODFCLP.h"
#include "itkMeshFromDiscreteFiberODFImageFilter.h"
#include "itkTensorBasisMatrixGenerator.h"
#include "itkSpatiallyDenseSparseVectorImageFileReader.h"
#include "itkSpatiallyDenseSparseVectorImage.h"
#include "itkCommandProgressUpdate.h"
#include "utl.h"
#include "utlVTK.h"
#include "vtkPolyDataViewer.h"
Functions
int main (int argc, char const *argv[])
Detailed Description
Author
Dr. Jian Cheng (JC), jian..nosp@m.chen.nosp@m.g.198.nosp@m.3@gm.nosp@m.ail.c.nosp@m.om
Definition in file MeshFromDiscreteFiberODF.cxx.
Function Documentation
int main (int argc, char const * argv[])
Mesh From Discrete Fiber ODF Create mesh (a spherical profile of DWI/EAP/ODF) from discrete fiber ODF for visualization.
Author
Jian Cheng (jian..nosp@m.chen.nosp@m.g.198.nosp@m.3@gm.nosp@m.ail.c.nosp@m.om)
Definition at line 39 of file MeshFromDiscreteFiberODF.cxx.
References CARTESIAN_TO_CARTESIAN, DIRECTION_NODUPLICATE, itk::CommandProgressUpdate::New(), spams::FISTA::NONE, utlGlobalException, vtk::VisualizePolyData(), and utl::WriteVtkPolyData().