DMRITool: Wrapping/Matlab/DiffusionModels/mexGetSamplesFromSPFCoefficients.cxx File Reference
mexGetSamplesFromSPFCoefficients.cxx File Reference
#include "mex.h"
#include "utl.h"
#include "utlMEX.h"
#include "itkProfileFromSPFImageFilter.h"
#include "itkSPFScaleFromMeanDiffusivityImageFilter.h"
Functions
template<typename T >
void callFunction (mxArray *plhs[], const mxArray *prhs[], const int nlhs, const int nrhs)
void mexFunction (int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[])
Function Documentation
template<typename T > void callFunction (mxArray * plhs[], const mxArray * prhs[], const int nlhs, const int nrhs) inline
Definition at line 27 of file mexGetSamplesFromSPFCoefficients.cxx.
References utl::CartesianToSpherical(), utl::GetArrayStruct(), itk::GetITKImageFromMXArray(), itk::GetITKVectorImageFromMXArray(), itk::GetMXArrayFromITKVectorImage(), utl::GetSTDVectorFromMXArray(), utl::GetUtlMatrixFromMXArray(), utl::InitializeThreadedLibraries(), utl::IsLogDebug(), utl::LogLevel, ONE_OVER_4_PI_2, and utlGlobalException.
void mexFunction (int nlhs, mxArray * plhs[], int nrhs, const mxArray * prhs[])
Definition at line 147 of file mexGetSamplesFromSPFCoefficients.cxx.
References utlGlobalException.