DMRITool: Wrapping/Matlab/DiffusionModels/mexGetSPFBasisMatrix.cxx File Reference
mexGetSPFBasisMatrix.cxx File Reference
#include <cstdio>
#include <iostream>
#include <cstdlib>
#include "mex.h"
#include "utl.h"
#include "mexutils.h"
#include "mexSTD.h"
#include "utlMEX.h"
#include "itkSphericalPolarFourierImageFilter.h"
Functions
template<typename T >
void callFunction (mxArray *plhs[], const mxArray *prhs[], const int nlhs, const int nrhs)
void mexFunction (int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[])
Function Documentation
template<typename T > void callFunction (mxArray * plhs[], const mxArray * prhs[], const int nlhs, const int nrhs) inline
Definition at line 34 of file mexGetSPFBasisMatrix.cxx.
References utl::CartesianToSpherical(), utl::GetMXArrayFromUtlMatrix(), utl::GetSTDVectorFromMXArray(), utl::GetUtlMatrixFromMXArray(), ONE_OVER_4_PI_2, utlException, and utlGlobalException.
void mexFunction (int nlhs, mxArray * plhs[], int nrhs, const mxArray * prhs[])
Definition at line 133 of file mexGetSPFBasisMatrix.cxx.
References utlGlobalException.