DMRITool: Wrapping/Matlab/DiffusionModels/mexGetSHBasisMatrix.cxx File Reference
mexGetSHBasisMatrix.cxx File Reference
#include <cstdio>
#include <iostream>
#include <cstdlib>
#include "mex.h"
#include "utl.h"
#include "mexutils.h"
#include "utlMEX.h"
Functions
template<typename T >
void callFunction (mxArray *plhs[], const mxArray *prhs[], const int nlhs, const int nrhs)
void mexFunction (int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[])
Function Documentation
template<typename T > void callFunction (mxArray * plhs[], const mxArray * prhs[], const int nlhs, const int nrhs) inline
Definition at line 29 of file mexGetSHBasisMatrix.cxx.
References CARTESIAN_TO_SPHERICAL, utl::ComputeSHMatrix(), utl::GetMXArrayFromUtlMatrix(), utl::GetString(), utl::GetUtlMatrixFromMXArray(), SPHERICAL_TO_SPHERICAL, utlException, and utlGlobalException.
void mexFunction (int nlhs, mxArray * plhs[], int nrhs, const mxArray * prhs[])
Definition at line 68 of file mexGetSHBasisMatrix.cxx.
References utlGlobalException.