DMRITool: Wrapping/Matlab/Common/mexITKImageRead.cxx File Reference
mexITKImageRead.cxx File Reference
#include "mex.h"
#include "utlMEX.h"
#include "itkImageFileReader.h"
Functions
template<typename T , unsigned int dim, bool isVectorImage>
void callFunction (mxArray *plhs[], const mxArray *prhs[], const int nlhs, const int nrhs)
void mexFunction (int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[])
Function Documentation
template<typename T , unsigned int dim, bool isVectorImage> void callFunction (mxArray * plhs[], const mxArray * prhs[], const int nlhs, const int nrhs) inline
Definition at line 25 of file mexITKImageRead.cxx.
References itk::GetMXArrayFromITKImage(), itk::GetMXArrayFromITKVectorImage(), utl::GetString(), and itk::ReadImage().
void mexFunction (int nlhs, mxArray * plhs[], int nrhs, const mxArray * prhs[])
Definition at line 79 of file mexITKImageRead.cxx.
References utl::GetString(), and utlGlobalException.