DMRITool: Wrapping/Matlab/Common/mexITKImageWrite.cxx File Reference
mexITKImageWrite.cxx File Reference
#include "mex.h"
#include "utlMEX.h"
Functions
template<typename T >
void callFunction (mxArray *plhs[], const mxArray *prhs[], const int nlhs, const int nrhs, const bool isVectorImage)
void mexFunction (int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[])
template<class ImageType >
void SetITKImageInformation (itk::SmartPointer< ImageType > &image, const mxArray *originArray, const mxArray *spacingArray)
Function Documentation
template<typename T > void callFunction (mxArray * plhs[], const mxArray * prhs[], const int nlhs, const int nrhs, const bool isVectorImage) inline
Definition at line 51 of file mexITKImageWrite.cxx.
References utl::GetArrayStruct(), itk::GetITKImageFromMXArray(), itk::GetITKVectorImageFromMXArray(), utl::GetString(), itk::SaveImage(), SetITKImageInformation(), and utlGlobalException.
void mexFunction (int nlhs, mxArray * plhs[], int nrhs, const mxArray * prhs[])
Definition at line 88 of file mexITKImageWrite.cxx.
References utlGlobalException.
template<class ImageType > void SetITKImageInformation (itk::SmartPointer< ImageType > & image, const mxArray * originArray, const mxArray * spacingArray)
Definition at line 24 of file mexITKImageWrite.cxx.
References utl::min().
Referenced by callFunction().