DMRITool: Wrapping/Matlab/DWIProcessing/mexReadDWIList.cxx File Reference
mexReadDWIList.cxx File Reference
#include "utl.h"
#include "utlMEX.h"
#include "itkDWIReader.h"
Functions
template<typename T >
void callFunction (mxArray *plhs[], const mxArray *prhs[], const int nlhs, const int nrhs)
void mexFunction (int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[])
Function Documentation
template<typename T > void callFunction (mxArray * plhs[], const mxArray * prhs[], const int nlhs, const int nrhs) inline
Definition at line 24 of file mexReadDWIList.cxx.
References utl::GetArrayStruct(), itk::GetITKImageFromMXArray(), itk::GetMXArrayFromITKImage(), itk::GetMXArrayFromITKVectorImage(), utl::GetString(), and utlGlobalException.
void mexFunction (int nlhs, mxArray * plhs[], int nrhs, const mxArray * prhs[])
Definition at line 83 of file mexReadDWIList.cxx.
References utlGlobalException.