DMRITool: Wrapping/Matlab/SamplingScheme/mexReadGrad.cxx File Reference
mexReadGrad.cxx File Reference
#include "utl.h"
#include "mex.h"
#include "mexutils.h"
#include "utlMEX.h"
#include "itkSphericalPolarFourierGenerator.h"
Functions
template<typename T >
void callFunction (mxArray *plhs[], const mxArray *prhs[], const int nlhs, const int nrhs)
void mexFunction (int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[])
Function Documentation
template<typename T > void callFunction (mxArray * plhs[], const mxArray * prhs[], const int nlhs, const int nrhs) inline
Definition at line 27 of file mexReadGrad.cxx.
References CARTESIAN_TO_CARTESIAN, utl::ConvertNumberToString(), DIRECTION_NODUPLICATE, utl::GetFileExtension(), utl::GetMXArrayFromUtlMatrix(), utl::GetString(), utl::StringCompareCaseIgnored(), and utlGlobalException.
void mexFunction (int nlhs, mxArray * plhs[], int nrhs, const mxArray * prhs[])
Definition at line 78 of file mexReadGrad.cxx.
References utlGlobalException.