DMRITool: Wrapping/Matlab/DiffusionModels/mexSphericalPolarFourierImaging.cxx File Reference
mexSphericalPolarFourierImaging.cxx File Reference
#include "mex.h"
#include "utl.h"
#include "utlMEX.h"
#include "itkSphericalPolarFourierImageFilter.h"
#include "itkDWIReader.h"
#include "itkGeneralizedHighOrderTensorImageFilter.h"
#include "itkFeaturesFromSPFImageFilter.h"
#include "itkProfileFromSPFImageFilter.h"
#include "itkODFFromSPFImageFilter.h"
#include "itkL1RegularizedLeastSquaresFISTASolver.h"
Functions
template<typename T >
void callFunction (mxArray *plhs[], const mxArray *prhs[], const int nlhs, const int nrhs)
void mexFunction (int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[])
Function Documentation
template<typename T > void callFunction (mxArray * plhs[], const mxArray * prhs[], const int nlhs, const int nrhs) inline
Definition at line 31 of file mexSphericalPolarFourierImaging.cxx.
References utl::CartesianToSpherical(), utl::GetArrayStruct(), itk::GetITKImageFromMXArray(), itk::GetITKVectorImageFromMXArray(), itk::GetMXArrayFromITKVectorImage(), utl::GetSTDVectorFromMXArray(), utl::GetUtlMatrixFromMXArray(), utl::InitializeThreadedLibraries(), LOG_DEBUG, utl::LogLevel, ONE_OVER_4_PI_2, spams::FISTA::solver(), utlException, and utlGlobalException.
void mexFunction (int nlhs, mxArray * plhs[], int nrhs, const mxArray * prhs[])
Definition at line 197 of file mexSphericalPolarFourierImaging.cxx.
References utlGlobalException.