DMRITool: vtk Namespace Reference
vtk Namespace Reference
Classes
class vtkPolyDataViewer
Functions
void VisualizePolyData (vtkPolyData *mesh, const std::vector< double > &angle={0.0, 0.0}, const std::vector< int > &windowSize={600, 600}, const bool useNormal=true, const bool lighting=true, const double zoom=1.0, const std::string &pngfile="", const std::vector< double > &bgColor={0, 0, 0})
void VisualizePolyDataWithScalarRange (const std::vector< vtkPolyData * > &meshes, const std::vector< double > &opacity, const std::vector< double > &scalarRange={-1.0,-1.0}, const std::vector< double > &hueRange={0.6667, 0.0}, const std::vector< double > &angle={0.0, 0.0}, const std::vector< int > &windowSize={600, 600}, const bool useNormal=true, const bool lighting=true, const double zoom=1.0, const std::string &pngfile="", const std::vector< double > &bgColor={0, 0, 0})
void VisualizePolyDataWithScalarRange (vtkPolyData *mesh, const std::vector< double > &scalarRange={-1.0,-1.0}, const std::vector< double > &hueRange={0.6667, 0.0}, const std::vector< double > &angle={0.0, 0.0}, const std::vector< int > &windowSize={600, 600}, const bool useNormal=true, const bool lighting=true, const double zoom=1.0, const std::string &pngfile="", const std::vector< double > &bgColor={0, 0, 0})
vtkSmartPointer< vtkLODActor > vtkPolyDataToActor (const vtkSmartPointer< vtkPolyData > &mesh, const double opacity=1.0, const std::vector< double > &hueRange={0.6667, 0.0}, bool useNormal=true, const std::vector< double > &scalarRange={-1.0,-1.0}, bool lighting=true)
vtkStandardNewMacro (vtkPolyDataViewer)
Function Documentation
void vtk::VisualizePolyData (vtkPolyData * mesh, const std::vector< double > & angle = {0.0,0.0}, const std::vector< int > & windowSize = {600,600}, const bool useNormal = true, const bool lighting = true, const double zoom = 1.0, const std::string & pngfile = "", const std::vector< double > & bgColor = {0,0,0}) inline
helper function to visualize vtkPolyData
Definition at line 224 of file vtkPolyDataViewer.h.
Referenced by main().
void vtk::VisualizePolyDataWithScalarRange (const std::vector< vtkPolyData * > & meshes, const std::vector< double > & opacity, const std::vector< double > & scalarRange = {-1.0,-1.0}, const std::vector< double > & hueRange = {0.6667,0.0}, const std::vector< double > & angle = {0.0,0.0}, const std::vector< int > & windowSize = {600,600}, const bool useNormal = true, const bool lighting = true, const double zoom = 1.0, const std::string & pngfile = "", const std::vector< double > & bgColor = {0,0,0}) inline
helper function to visualize vtkPolyData
Definition at line 172 of file vtkPolyDataViewer.h.
Referenced by main().
void vtk::VisualizePolyDataWithScalarRange (vtkPolyData * mesh, const std::vector< double > & scalarRange = {-1.0,-1.0}, const std::vector< double > & hueRange = {0.6667,0.0}, const std::vector< double > & angle = {0.0,0.0}, const std::vector< int > & windowSize = {600,600}, const bool useNormal = true, const bool lighting = true, const double zoom = 1.0, const std::string & pngfile = "", const std::vector< double > & bgColor = {0,0,0}) inline
helper function to visualize vtkPolyData
Definition at line 201 of file vtkPolyDataViewer.h.
vtkSmartPointer<vtkLODActor> vtk::vtkPolyDataToActor (const vtkSmartPointer< vtkPolyData > & mesh, const double opacity = 1.0, const std::vector< double > & hueRange = {0.6667,0.0}, bool useNormal = true, const std::vector< double > & scalarRange = {-1.0,-1.0}, bool lighting = true) inline
helper function from vtkPolyData to vtkLODActor
Definition at line 43 of file vtkPolyDataViewer.h.
Referenced by vtk::vtkPolyDataViewer::Add().
vtk::vtkStandardNewMacro (vtkPolyDataViewer)