DMRITool: itk Namespace Reference
itk Namespace Reference
Utl » UtlHelperFunctions
Namespaces
Concept
Detail
Functor
Classes
class AddNoiseToDWIImageFilter
class BasisMatrixGenerator
class CastImageFileWriter
class CastVectorImageFileWriter
class CommandProgressUpdate
class ComposeVectorImageFilter
class CylinderModelGenerator
class DiffusionModelEstimationImageFilter
class DiffusionModelEstimationInSphericalCoordinateImageFilter
class DiffusionModelGenerator
class DiffusionTensor
class DiscreteBasisMatrixGenerator
class DWIGenerator
class DWIGeneratorBase
class DWIReader
class DWISingleVoxelGenerator
class DWIWriter
class FeaturesFromSPFImageFilter
class Fiber
class FiberTracts
class FiberTractsReader
class FiberTractsWriter
class FunctorBaseVectorImageFilter
class FunctorFromStringImageFilter
class FunctorHashTable
class FunctorTableBase
class GeneralizedHighOrderTensorImageFilter
class ImageToVTKImageDataFilter
class IterativeSolverBase
class L1RegularizedLeastSquaresFISTASolver
class L2RegularizedLeastSquaresSolver
class MaskedImageToImageFilter
class MeanDiffusivityFromGHOTImageFilter
class MeshFromContinuousSphericalFunctionImageFilter
class MeshFromDiscreteFiberODFImageFilter
class MeshFromFiberTractsFilter
class MeshFromImageImageFilter
class MeshFromPeaksImageFilter
class MeshFromSHCoefficientsImageFilter
class MeshFromSphericalFunctionImageFilter
class MeshFromSphericalFunctionTessellatedSamplesImageFilter
class MeshFromTensorImageFilter
class MultiplyByConstantMatrixVectorImageFilter
class MultiplyByConstantVectorImageFilter
class MultiVariableFunctorVectorImageFilter
class MultiVolumeImageToVectorImageFilter
class NormalizeODFImageFilter
class NormalizeVectorImageFilter
class ODFFromSPFImageFilter
class OuterProductVectorImageFilter
class PeakContainerHelper
class ProfileFromSPFImageFilter
class RGBImageToVTKImageDataFilter
class RotateSHCoefficientsImageFilter
class SamplingScheme3D
class SamplingSchemeQSpace
class SamplingSchemeQSpace1OptEstimationFilter
class SamplingSchemeQSpaceEstimationFilter
class SamplingSchemeQSpaceIMOCEstimationFilter
class SamplingSchemeQSpaceIncrementalEstimationFilter
class SamplingSchemeQSpaceWriter
class ScalarMapFromSPFImageFilter
class SHCoefficientsPowerImageFilter
class SHCoefficientsRotation
class SHCoefficientsToGFAImageFilter
class SlowPolyLineParametricPath
class SolverBase
class SpamsWeightedLassoSolver
class SparseVector
class SpatiallyDenseSparseVectorImage
class SpatiallyDenseSparseVectorImageFileReader
class SpatiallyDenseSparseVectorImageFileReaderException
class SpatiallyDenseSparseVectorImageFileWriter
class SpatiallyDenseSparseVectorImageNeighborhoodAccessorFunctor
class SpatiallyDenseSparseVectorImagePixelAccessor
class SpatiallyDenseSparseVectorImagePixelAccessorFunctor
class SPFScaleFromMeanDiffusivityImageFilter
class SphereTessellator
class SphericalHarmonicsGenerator
class SphericalPolarFourierEstimationImageFilter
class SphericalPolarFourierGenerator
class SphericalPolarFourierImageFilter
class SphericalPolarFourierRadialGenerator
class StructureTensorImageFilter
class TensorBasisMatrixGenerator
struct TrackVisHeaderType
class UnaryFunctorLookUpTable
class UnaryFunctorVectorImageFilter
class VariableLengthVectorImageFileReader
class VariableLengthVectorImageFileReaderException
class VariableLengthVectorImageFileWriter
class VectorImageChannelFilter
class VectorImageRegionIterator
class VectorImageRegionIterator< Image< TPixel, VImageDimension > >
class VectorImageRegionIteratorWithIndex
class VectorImageRegionIteratorWithIndex< Image< TPixel, VImageDimension > >
class VectorImageRegionIteratorWithIndex< Image< VariableLengthVector< TPixel >, 3 > >
class VectorImageRegionIteratorWithIndex< SpatiallyDenseSparseVectorImage< TPixel, VImageDimension > >
class VectorImageToMultiVolumeImageFilter
class VTKImageDataToImageFilter
Typedefs
typedef LUTExpType::Pointer LUTExpPointer
typedef UnaryFunctorLookUpTable< utl::Functor::Exp< double > > LUTExpType
Enumerations
enum PeakType {
XYZV =0,
XYZ,
NXYZV,
NXYZ
}
Functions
template<class ImageWithInfoType , class ImageType >
void CopyImageInformation (const SmartPointer< ImageWithInfoType > &imageFrom, SmartPointer< ImageType > &imageTo)
template<unsigned dimIn, unsigned dimOut>
void CopyImageRegion (const ImageRegion< dimIn > &regionIn, ImageRegion< dimOut > &regionOut, const int numberOfComponens=-1)
void CopyTrackvisHeader (const TrackVisHeaderType &hFrom, TrackVisHeaderType &hTo)
template<class ImageType , class ImageOutType , class MaskImageType = Image<double,4>>
void FunctorFromStringOPImage (const std::vector< itk::SmartPointer< ImageType > > &images, itk::SmartPointer< ImageOutType > &outImage, const std::string &funcStr, const itk::SmartPointer< MaskImageType > &mask=nullptr, int numberOfThreads=-1)
template<class ImageType >
ImageType::Pointer GenerateImage (const typename ImageType::SizeType &size, const int vectorLength=1)
template<class ImageType >
ImageType::Pointer GenerateImageFromSingleVoxel (const typename ImageType::PixelType &pixel)
int GetDimensionOfProperties (const TrackVisHeaderType &header)
int GetDimensionOfScalars (const TrackVisHeaderType &header)
int GetImageType (const std::string &filename)
template<class ImageType >
int GetImageType (const SmartPointer< ImageType > &image)
template<class T , unsigned int VImageDimension>
void GetITKImageFromMXArray (const mxArray *pr, SmartPointer< Image< T, VImageDimension > > &image)
template<class T >
void GetITKVectorImageFromMXArray (const mxArray *pr, SmartPointer< VectorImage< T, 3 > > &image)
template<class T , unsigned int VImageDimension>
void GetMXArrayFromITKImage (const SmartPointer< Image< T, VImageDimension > > &image, mxArray *&pr)
template<class T , unsigned int VImageDimension>
void GetMXArrayFromITKVectorImage (const SmartPointer< VectorImage< T, VImageDimension > > &image, mxArray *&pr)
std::vector< std::string > GetPropertyNames (const TrackVisHeaderType &header)
std::vector< std::string > GetScalarNames (const TrackVisHeaderType &header)
template<class ImageType >
std::vector< int > GetVectorImage3DVolumeSize (const SmartPointer< ImageType > &image)
template<class ImageType >
std::vector< int > GetVectorImageFullSize (const SmartPointer< ImageType > &image)
template<class ImageType >
int GetVectorImageVectorSize (const SmartPointer< ImageType > &image, const int axis=-1)
bool HasPropertyName (const TrackVisHeaderType &header, const std::string &name)
bool HasScalarName (const TrackVisHeaderType &header, const std::string &name)
template<class Image1Type , class Image2Type >
void ImageToImage (const SmartPointer< Image1Type > &image1, SmartPointer< Image2Type > &image2)
template<class Image1Type , class Image2Type >
SmartPointer< Image2Type > ImageToImage (const SmartPointer< Image1Type > &image1)
void InitializeLUTExp ()
void InitializeSHRotation (const int rank, const int tess)
bool Is3DImage (const std::string &filename)
template<class ImageType >
bool IsImageEmpty (const SmartPointer< ImageType > &image)
bool IsSameStructure (const TrackVisHeaderType &h1, const TrackVisHeaderType &h2)
bool IsSparseImage (const std::string &filename)
bool IsVectorImage (const std::string &filename)
double lutExpValue (const double x)
template<class ImageType , class ImageOutType , class OpFunctor , class MaskImageType = Image<double,4>>
void MultiVariableVectorOPImage (const std::vector< itk::SmartPointer< ImageType > > &images, itk::SmartPointer< ImageOutType > &outImage, const OpFunctor &func, const itk::SmartPointer< MaskImageType > &mask=nullptr, int numberOfThreads=-1, int vectorAxis=3)
template<class ScalarType , unsigned Dim>
void MultiVolumeToVectorImage (const SmartPointer< Image< ScalarType, Dim+1 > > &image1, SmartPointer< VectorImage< ScalarType, Dim > > &image2)
template<class PointsContainer , class VnlValueType >
void PointsContainerToVnlMatrix (const PointsContainer &points, vnl_matrix< VnlValueType > &matrix)
template<class TPixelType , unsigned int VImageDimension>
void PrintImage (const SmartPointer< Image< TPixelType, VImageDimension > > image, const std::string &mse="", std::ostream &os=std::cout, bool isPrintHeader=false)
template<class TPixelType , unsigned int VImageDimension>
void PrintImage3D (const SmartPointer< Image< TPixelType, VImageDimension > > &image, const std::string &mse="", std::ostream &os=std::cout, bool isPrintHeader=false)
template<class TPixelType , unsigned int VImageDimension>
void PrintImage4D (const SmartPointer< Image< TPixelType, VImageDimension > > &image, const std::string &mse="", std::ostream &os=std::cout, bool isPrintHeader=false)
void PrintTractVisHeader (const TrackVisHeaderType &header, std::ostream &os=std::cout)
template<class T >
void PrintVariableLengthVector (const VariableLengthVector< T >vec, const std::string &str="", const char *separate=" ", std::ostream &os=std::cout)
template<class TPixelType , unsigned int VImageDimension>
void PrintVectorImage (const SmartPointer< VectorImage< TPixelType, VImageDimension > > &image, const std::string &mse="", std::ostream &os=std::cout, bool isPrintHeader=false)
bool ReadFibers (const std::string &filename, SmartPointer< FiberTracts< double > > &fibers, const std::string &printInfo="Reading fibers:")
template<class ImageType >
bool ReadImage (const std::string &filename, SmartPointer< ImageType > &image, const std::string &printInfo="Reading Image:")
template<class ImageType , class ReaderType >
bool ReadImage (const std::string &filename, SmartPointer< ImageType > &image, const std::string &printInfo="Reading Image:")
template<class ImageType >
bool ReadImageInformation (const std::string &filename, SmartPointer< ImageType > &image)
void ReadTrackVisHeader (const std::string &filename, TrackVisHeaderType &header)
template<class PixelType >
void ReadVectorImage (const std::string &filename, SmartPointer< VectorImage< PixelType, 3 > > &image, const std::string &printInfo="Reading Image:")
void RemovePropertyName (TrackVisHeaderType &header, const std::string &name)
void RemoveScalarName (TrackVisHeaderType &header, const std::string &name)
bool SaveFibers (const SmartPointer< FiberTracts< double > > &fibers, const std::string &filename, const std::string &printInfo="Writing fibers:")
template<class ImageType >
bool SaveImage (const SmartPointer< ImageType > &image, const std::string &filename, const std::string &printInfo="Writing Image:")
template<class ImageType , class WriterType >
bool SaveImage (const SmartPointer< ImageType > &image, const std::string &filename, const std::string &printInfo="Writing Image:")
template<class ImageType >
void SetVectorImage3DVolumeSize (SmartPointer< ImageType > &image, const std::vector< int > &size)
template<class ImageType >
void SetVectorImageFullSize (SmartPointer< ImageType > &image, const std::vector< int > &size)
template<class ImageType >
void SetVectorImageVectorSize (const SmartPointer< ImageType > &image, const int vecsize)
template<class ImageType , class ImageOutType , class OpFunctor , class MaskImageType = Image<double,4>>
void UnaryVectorOPImage (const itk::SmartPointer< ImageType > &image, itk::SmartPointer< ImageOutType > &outImage, const OpFunctor &func, const itk::SmartPointer< MaskImageType > &mask=nullptr, int numberOfThreads=-1, int vectorAxis=3)
template<class T >
vnl_vector< T > VariableLengthVectorToVnlVector (const VariableLengthVector< T > &vec)
template<class ScalarType , unsigned Dim>
void VectorToMultiVolumeImage (const SmartPointer< VectorImage< ScalarType, Dim > > &image1, SmartPointer< Image< ScalarType, Dim+1 > > &image2)
template<class Image1Type , class Image2Type >
bool VerifyImageInformation (const SmartPointer< Image1Type > &image1, const SmartPointer< Image2Type > &image2, const bool isMinimalDimension=false)
template<class Image1Type >
bool VerifyImageInformation (const SmartPointer< Image1Type > &image1, const std::string &file2, const bool isMinimalDimension=false)
bool VerifyImageInformation (const std::string &file1, const std::string &file2, const bool isMinimalDimension=false)
template<class Image1Type , class Image2Type >
bool VerifyImageSize (const SmartPointer< Image1Type > &image1, const SmartPointer< Image2Type > &image2, const bool isMinimalDimension=false)
template<class Image1Type >
bool VerifyImageSize (const SmartPointer< Image1Type > &image1, const std::string &file2, const bool isMinimalDimension=false)
bool VerifyImageSize (const std::string &file1, const std::string &file2, const bool isMinimalDimension=false)
template<class VnlValueType , class PointsContainer >
void VnlMatrixToPointsContainer (const vnl_matrix< VnlValueType > &matrix, PointsContainer &points)
template<class T >
VariableLengthVector< T > VnlVectorToVariableLengthVector (const vnl_vector< T > &vec)
void WriteTrackVisHeader (const TrackVisHeaderType &header, FILE *file)
Variables
static LUTExpPointer lutExp = LUTExpType::New()
Typedef Documentation
typedef LUTExpType::Pointer itk::LUTExpPointer
Definition at line 32 of file utlDMRIStoredTables.h.
typedef UnaryFunctorLookUpTable<utl::Functor::Exp<double> > itk::LUTExpType
Definition at line 31 of file utlDMRIStoredTables.h.
Enumeration Type Documentation
enum itk::PeakType
Enumerator
XYZV
peaks peaks stored in x,y,z,value, without the number of peaks
XYZ
peaks peaks stored in x,y,z, without the number of peaks
NXYZV
peaks peaks stored in x,y,z,value with the number of peaks in the first value
NXYZ
peaks peaks stored in x,y,z,value with the number of peaks in the first value
Definition at line 28 of file itkPeakContainerHelper.h.
Function Documentation
void itk::CopyTrackvisHeader (const TrackVisHeaderType & hFrom, TrackVisHeaderType & hTo)
Definition at line 57 of file itkTrackvisHeader.h.
Referenced by itk::FiberTracts< TValue >::DeepClone(), itk::FiberTracts< TValue >::SelectByBallROI(), and itk::FiberTracts< TValue >::SelectByIndicesOfTracts().
template<class ImageType , class ImageOutType , class MaskImageType = Image<double,4>> void itk::FunctorFromStringOPImage (const std::vector< itk::SmartPointer< ImageType > > & images, itk::SmartPointer< ImageOutType > & outImage, const std::string & funcStr, const itk::SmartPointer< MaskImageType > & mask = nullptr, int numberOfThreads = -1)
By defining a functor which maps multiple vectors to another vector, this function perform the functor on a set of images (VectorImage or NDImage).
Definition at line 109 of file itkFunctorFromStringImageFilter.h.
References IsImageEmpty(), utl::IsLogDebug(), and utl::LogLevel.
int itk::GetDimensionOfProperties (const TrackVisHeaderType & header) inline
Get total dimension of properties
Definition at line 141 of file itkTrackvisHeader.h.
References utl::GetScalarsDimentionByName(), itk::TrackVisHeaderType::n_properties, and itk::TrackVisHeaderType::property_name.
Referenced by itk::Fiber< TValue >::PrintSelf(), PrintTractVisHeader(), ReadTrackVisHeader(), itk::FiberTractsReader::ReadTractsTRK(), and itk::FiberTractsWriter::WriteTractsTRK().
int itk::GetDimensionOfScalars (const TrackVisHeaderType & header) inline
Get total dimension of scalars
Definition at line 125 of file itkTrackvisHeader.h.
References utl::GetScalarsDimentionByName(), itk::TrackVisHeaderType::n_scalars, and itk::TrackVisHeaderType::scalar_name.
Referenced by PrintTractVisHeader(), ReadTrackVisHeader(), itk::FiberTractsReader::ReadTractsTRK(), and itk::FiberTractsWriter::WriteTractsTRK().
template<class T , unsigned int VImageDimension> void itk::GetITKImageFromMXArray (const mxArray * pr, SmartPointer< Image< T, VImageDimension > > & image) inline
Definition at line 55 of file mexITK.h.
References utlException.
Referenced by callFunction().
template<class T > void itk::GetITKVectorImageFromMXArray (const mxArray * pr, SmartPointer< VectorImage< T, 3 > > & image) inline
Definition at line 128 of file mexITK.h.
References utl::min(), and utlException.
Referenced by callFunction().
template<class T , unsigned int VImageDimension> void itk::GetMXArrayFromITKImage (const SmartPointer< Image< T, VImageDimension > > & image, mxArray *& pr) inline
Definition at line 32 of file mexITK.h.
References utlException.
Referenced by callFunction().
template<class T , unsigned int VImageDimension> void itk::GetMXArrayFromITKVectorImage (const SmartPointer< VectorImage< T, VImageDimension > > & image, mxArray *& pr) inline
Definition at line 96 of file mexITK.h.
References utlException.
Referenced by callFunction().
std::vector<std::string> itk::GetPropertyNames (const TrackVisHeaderType & header) inline
Definition at line 96 of file itkTrackvisHeader.h.
References utl::CovertChar2DArrayToStringArray(), and itk::TrackVisHeaderType::property_name.
std::vector<std::string> itk::GetScalarNames (const TrackVisHeaderType & header) inline
Definition at line 90 of file itkTrackvisHeader.h.
References utl::CovertChar2DArrayToStringArray(), and itk::TrackVisHeaderType::scalar_name.
bool itk::HasPropertyName (const TrackVisHeaderType & header, const std::string & name) inline
Definition at line 102 of file itkTrackvisHeader.h.
References itk::TrackVisHeaderType::n_properties, and itk::TrackVisHeaderType::property_name.
Referenced by itk::FiberTracts< TValue >::HasPropertyName().
bool itk::HasScalarName (const TrackVisHeaderType & header, const std::string & name) inline
Definition at line 113 of file itkTrackvisHeader.h.
References itk::TrackVisHeaderType::n_scalars, and itk::TrackVisHeaderType::scalar_name.
Referenced by itk::FiberTracts< TValue >::HasScalarName().
void itk::InitializeLUTExp () inline
Definition at line 37 of file utlDMRIStoredTables.h.
References itk::UnaryFunctorLookUpTable< TFunctor >::New().
Referenced by main().
void itk::InitializeSHRotation (const int rank, const int tess) inline
Definition at line 176 of file itkSHCoefficientsRotation.h.
bool itk::IsSameStructure (const TrackVisHeaderType & h1, const TrackVisHeaderType & h2)
test if two fibers can be merged
Definition at line 64 of file itkTrackvisHeader.h.
References itk::TrackVisHeaderType::dim, itk::TrackVisHeaderType::n_properties, itk::TrackVisHeaderType::n_scalars, itk::TrackVisHeaderType::property_name, itk::TrackVisHeaderType::scalar_name, and itk::TrackVisHeaderType::voxel_size.
Referenced by itk::FiberTracts< TValue >::AppendFibers().
double itk::lutExpValue (const double x) inline
Definition at line 50 of file utlDMRIStoredTables.h.
References utl::SH3IntegralTable().
Referenced by utl::ComputeDWISHCoefficientsForGPDCylinder(), utl::GetExpProductLegendreCoef(), utl::GetSymmetricTensorSHCoef(), and utl::GetSymmetricTensorSHCoefDerivative().
template<class ImageType , class ImageOutType , class OpFunctor , class MaskImageType = Image<double,4>> void itk::MultiVariableVectorOPImage (const std::vector< itk::SmartPointer< ImageType > > & images, itk::SmartPointer< ImageOutType > & outImage, const OpFunctor & func, const itk::SmartPointer< MaskImageType > & mask = nullptr, int numberOfThreads = -1, int vectorAxis = 3)
By defining a functor which maps multiple vectors to another vector, this function perform the functor on a set of images (VectorImage or NDImage, along axis).
Definition at line 103 of file itkMultiVariableFunctorVectorImageFilter.h.
References IsImageEmpty(), utl::IsLogDebug(), and utl::LogLevel.
template<class ScalarType , unsigned Dim> void itk::MultiVolumeToVectorImage (const SmartPointer< Image< ScalarType, Dim+1 > > & image1, SmartPointer< VectorImage< ScalarType, Dim > > & image2)
Definition at line 88 of file itkMultiVolumeImageToVectorImageFilter.hxx.
Referenced by ConvertImage< NDImageType, VectorImageType >().
void itk::PrintTractVisHeader (const TrackVisHeaderType & header, std::ostream & os = std::cout) inline
print trackvis header
Definition at line 247 of file itkTrackvisHeader.h.
References itk::TrackVisHeaderType::dim, GetDimensionOfProperties(), GetDimensionOfScalars(), itk::TrackVisHeaderType::id_string, itk::TrackVisHeaderType::image_orientation_patient, itk::TrackVisHeaderType::n_count, itk::TrackVisHeaderType::n_properties, itk::TrackVisHeaderType::n_scalars, itk::TrackVisHeaderType::origin, itk::TrackVisHeaderType::property_name, itk::TrackVisHeaderType::scalar_name, itk::TrackVisHeaderType::version, itk::TrackVisHeaderType::vox_to_ras, itk::TrackVisHeaderType::voxel_order, and itk::TrackVisHeaderType::voxel_size.
Referenced by itk::FiberTracts< TValue >::PrintFibersHeader().
bool itk::ReadFibers (const std::string & filename, SmartPointer< FiberTracts< double > > & fibers, const std::string & printInfo = "Reading fibers:") inline
Definition at line 83 of file itkFiberTractsReader.h.
References utl::IsLogNormal(), and itk::FiberTractsReader::New().
void itk::ReadTrackVisHeader (const std::string & filename, TrackVisHeaderType & header) inline
read trackvis header
Definition at line 194 of file itkTrackvisHeader.h.
References GetDimensionOfProperties(), GetDimensionOfScalars(), itk::TrackVisHeaderType::id_string, itk::TrackVisHeaderType::n_count, utlGlobalException, and utlSAGlobalWarning.
Referenced by itk::FiberTractsReader::ReadTractsTRK().
template<class PixelType > void itk::ReadVectorImage (const std::string & filename, SmartPointer< VectorImage< PixelType, 3 > > & image, const std::string & printInfo = "Reading Image:") inline
if it is a VectorImage, directly read it. If it is a 4D image, read it as Image, then convert it to a VectorImage
Definition at line 66 of file utl.h.
References utl::IsFileExist(), IsVectorImage(), and utlGlobalException.
Referenced by main().
void itk::RemovePropertyName (TrackVisHeaderType & header, const std::string & name) inline
remove properties by its name
Definition at line 175 of file itkTrackvisHeader.h.
References itk::TrackVisHeaderType::n_properties, and itk::TrackVisHeaderType::property_name.
Referenced by itk::FiberTracts< TValue >::RemovePropertiesByName().
void itk::RemoveScalarName (TrackVisHeaderType & header, const std::string & name) inline
remove scalars by its name
Definition at line 157 of file itkTrackvisHeader.h.
References itk::TrackVisHeaderType::n_scalars, and itk::TrackVisHeaderType::scalar_name.
Referenced by itk::FiberTracts< TValue >::RemoveScalarsByName().
bool itk::SaveFibers (const SmartPointer< FiberTracts< double > > & fibers, const std::string & filename, const std::string & printInfo = "Writing fibers:") inline
Definition at line 79 of file itkFiberTractsWriter.h.
References utl::IsLogNormal(), and itk::FiberTractsWriter::New().
template<class ImageType , class ImageOutType , class OpFunctor , class MaskImageType = Image<double,4>> void itk::UnaryVectorOPImage (const itk::SmartPointer< ImageType > & image, itk::SmartPointer< ImageOutType > & outImage, const OpFunctor & func, const itk::SmartPointer< MaskImageType > & mask = nullptr, int numberOfThreads = -1, int vectorAxis = 3)
By defining a functor which maps a vector to another vector, this function perform the functor on an image (VectorImage or NDImage, along axis).
Definition at line 116 of file itkUnaryFunctorVectorImageFilter.h.
References IsImageEmpty(), utl::IsLogDebug(), and utl::LogLevel.
template<class ScalarType , unsigned Dim> void itk::VectorToMultiVolumeImage (const SmartPointer< VectorImage< ScalarType, Dim > > & image1, SmartPointer< Image< ScalarType, Dim+1 > > & image2)
Definition at line 97 of file itkVectorImageToMultiVolumeImageFilter.hxx.
Referenced by ConvertImage< VectorImageType, NDImageType >().
void itk::WriteTrackVisHeader (const TrackVisHeaderType & header, FILE * file) inline
write trackvis header
Definition at line 236 of file itkTrackvisHeader.h.
References utlGlobalException.
Referenced by itk::FiberTractsWriter::WriteTractsTRK().
Variable Documentation
LUTExpPointer itk::lutExp = LUTExpType::New() static
use lookup table to approximate exp(-x)
Definition at line 34 of file utlDMRIStoredTables.h.