DMRITool: Applications/SamplingScheme/OrientationStatistics.cxx File Reference
OrientationStatistics.cxx File Reference
#include "OrientationStatisticsCLP.h"
#include "itkSamplingScheme3D.h"
#include "utl.h"
Functions
int main (int argc, char const *argv[])
double processOrientation (const itk::SamplingScheme3D< double >::Pointer scheme, const bool _Asymmetric)
Detailed Description
Author
Dr. Jian Cheng (JC), jian..nosp@m.chen.nosp@m.g.198.nosp@m.3@gm.nosp@m.ail.c.nosp@m.om
Definition in file OrientationStatistics.cxx.
Function Documentation
int main (int argc, char const * argv[])
obtain energies, minimal angles from a given set of orientations
Author
Jian Cheng (jian..nosp@m.chen.nosp@m.g.198.nosp@m.3@gm.nosp@m.ail.c.nosp@m.om)
Definition at line 70 of file OrientationStatistics.cxx.
References processOrientation().
double processOrientation (const itk::SamplingScheme3D< double >::Pointer scheme, const bool _Asymmetric) inline
Definition at line 24 of file OrientationStatistics.cxx.
References itk::SamplingScheme3D< TPixelType >::CalculateElectrostaticEnergy(), itk::SamplingScheme3D< TPixelType >::CalculateMinDistance(), itk::SamplingScheme3D< TPixelType >::CalculatePackingDensity(), utl::GetContainerStats(), itk::SamplingScheme3D< TPixelType >::GetNumberOfSamples(), itk::SamplingScheme3D< TPixelType >::GetNumbers(), and M_PI.
Referenced by main().