DMRITool: Applications/Utilities/PrintImage.cxx File Reference
PrintImage.cxx File Reference
#include "PrintImageCLP.h"
#include "itkImageRegionIteratorWithIndex.h"
#include "itkVectorImageRegionIterator.h"
#include "itkVectorImageRegionIteratorWithIndex.h"
#include "itkVectorImageRegionIteratorWithIndexSpecial.h"
#include "itkSpatiallyDenseSparseVectorImage.h"
#include "itkSpatiallyDenseSparseVectorImageFileReader.h"
#include "itkSpatiallyDenseSparseVectorImageFileWriter.h"
#include "itkVariableLengthVectorImageFileReader.h"
#include "itkVariableLengthVectorImageFileWriter.h"
#include "utl.h"
#include "itkMultiVolumeImageToVectorImageFilter.h"
#include "itkVectorImageToMultiVolumeImageFilter.h"
Typedefs
typedef itk::Image< ScalarType, 4 > NDImageType
typedef double ScalarType
typedef itk::SpatiallyDenseSparseVectorImage< ScalarType, 3 > SparseImageType
typedef itk::Image< itk::VariableLengthVector< ScalarType >, 3 > VariableLengthImageType
typedef itk::VectorImage< ScalarType, 3 > VectorImageType
Functions
template<class ImageType , class Image2Type >
void ConvertImage (const itk::SmartPointer< ImageType > &image, itk::SmartPointer< Image2Type > &imageOut)
template<>
void ConvertImage< NDImageType, VectorImageType > (const itk::SmartPointer< NDImageType > &image, itk::SmartPointer< VectorImageType > &imageOut)
template<>
void ConvertImage< VectorImageType, NDImageType > (const itk::SmartPointer< VectorImageType > &image, itk::SmartPointer< NDImageType > &imageOut)
template<class IndexType >
bool IsOutsideBox (const IndexType &index, const std::vector< int > &box)
int main (int argc, char const *argv[])
template<class ImageType , class ReaderType , class Image0Type = ImageType, class Reader0Type = ReaderType>
int PrintImage (int argc, char const *argv[])
Detailed Description
Created "10-11-2013.
Author
Jian Cheng (JC), jian..nosp@m.chen.nosp@m.g.198.nosp@m.3@gm.nosp@m.ail.c.nosp@m.om
Definition in file PrintImage.cxx.
Typedef Documentation
typedef itk::Image<ScalarType, 4> NDImageType
Definition at line 28 of file PrintImage.cxx.
typedef double ScalarType
Definition at line 26 of file PrintImage.cxx.
typedef itk::SpatiallyDenseSparseVectorImage<ScalarType, 3> SparseImageType
Definition at line 29 of file PrintImage.cxx.
typedef itk::Image<itk::VariableLengthVector<ScalarType>, 3> VariableLengthImageType
Definition at line 30 of file PrintImage.cxx.
typedef itk::VectorImage<ScalarType, 3> VectorImageType
Definition at line 27 of file PrintImage.cxx.
Function Documentation
template<class ImageType , class Image2Type > void ConvertImage (const itk::SmartPointer< ImageType > & image, itk::SmartPointer< Image2Type > & imageOut)
Definition at line 34 of file PrintImage.cxx.
Referenced by PrintImage().
template<> void ConvertImage< NDImageType, VectorImageType > (const itk::SmartPointer< NDImageType > & image, itk::SmartPointer< VectorImageType > & imageOut)
Definition at line 42 of file PrintImage.cxx.
References itk::MultiVolumeToVectorImage().
template<> void ConvertImage< VectorImageType, NDImageType > (const itk::SmartPointer< VectorImageType > & image, itk::SmartPointer< NDImageType > & imageOut)
Definition at line 49 of file PrintImage.cxx.
References itk::VectorToMultiVolumeImage().
template<class IndexType > bool IsOutsideBox (const IndexType & index, const std::vector< int > & box)
Definition at line 57 of file PrintImage.cxx.
Referenced by PrintImage().
int main (int argc, char const * argv[])
Print image.
Definition at line 340 of file PrintImage.cxx.
References itk::GetImageType(), IMAGE_ND, IMAGE_SPARSE, IMAGE_VARIABLELENGTH, and IMAGE_VECTOR.
template<class ImageType , class ReaderType , class Image0Type = ImageType, class Reader0Type = ReaderType> int PrintImage (int argc, char const * argv[])
Definition at line 64 of file PrintImage.cxx.
References CARTESIAN_TO_SPHERICAL, utl::ComputeSHMatrix(), ConvertImage(), utl::ConvertTensor6DTo9D(), utl::DimToRankSH(), DIRECTION_NODUPLICATE, itk::GetImageType(), itk::VectorImageRegionIteratorWithIndex< TImage >::GetVector(), itk::GetVectorImage3DVolumeSize(), itk::GetVectorImageVectorSize(), IMAGE_ND, IMAGE_VECTOR, IsOutsideBox(), utl::IsSameVector(), utl::PrintVector(), SPHERICAL_TO_SPHERICAL, TENSOR_DIAGONAL_FIRST, TENSOR_EMBED6D, TENSOR_LOWER_TRIANGULAR, TENSOR_UPPER_TRIANGULAR, utlGlobalException, utlPrintVar2, and utl::VectorToVector().