DMRITool: Applications/SamplingScheme/SamplingSchemeDistance.cxx File Reference
SamplingSchemeDistance.cxx File Reference
#include "SamplingSchemeDistanceCLP.h"
#include "utl.h"
#include <vnl/vnl_matrix.h>
Functions
int main (int argc, char const *argv[])
Detailed Description
Author
Dr. Jian Cheng (JC), jian..nosp@m.chen.nosp@m.g.198.nosp@m.3@gm.nosp@m.ail.c.nosp@m.om
Definition in file SamplingSchemeDistance.cxx.
Function Documentation
int main (int argc, char const * argv[])
calculate the distances between to sampling schemes
Definition at line 27 of file SamplingSchemeDistance.cxx.
References CARTESIAN_TO_CARTESIAN, DIRECTION_NODUPLICATE, M_PI, utl::max(), utl::min(), utlGlobalException, utlPrintVar2, utlPrintVar3, and utl::UtlVectorToStdVector().