DMRITool: Applications/DiffusionModels/SHCoefficientsRotate.cxx File Reference
SHCoefficientsRotate.cxx File Reference
#include "utl.h"
#include "itkRotateSHCoefficientsImageFilter.h"
#include "utlRotationMatrixFromVectors.h"
#include "SHCoefficientsRotateCLP.h"
Functions
int main (int argc, char *argv[])
Detailed Description
Author
Dr. Jian Cheng (JC), jian..nosp@m.chen.nosp@m.g.198.nosp@m.3@gm.nosp@m.ail.c.nosp@m.om
Definition in file SHCoefficientsRotate.cxx.
Function Documentation
int main (int argc, char * argv[])
Definition at line 26 of file SHCoefficientsRotate.cxx.
References M_PI, utl::PrintUtlMatrix(), utl::PrintUtlVector(), utl::spherical2Cartesian(), and utlException.