DMRITool: Applications/DiffusionModels/SHCoefficientsToGFA.cxx File Reference
SHCoefficientsToGFA.cxx File Reference
#include "SHCoefficientsToGFACLP.h"
#include "utl.h"
#include "itkSHCoefficientsToGFAImageFilter.h"
#include "itkSHCoefficientsPowerImageFilter.h"
Functions
int main (int argc, char const *argv[])
Function Documentation
int main (int argc, char const * argv[])
Calculate GFA from SH coefficients.
Definition at line 21 of file SHCoefficientsToGFA.cxx.
References utl::DimToRankSH(), itk::ReadVectorImage(), and itk::SaveImage().