DMRITool: Applications/DiffusionModels/SHCoefficientsToSphericalFunctionSamples.cxx File Reference
SHCoefficientsToSphericalFunctionSamples.cxx File Reference
#include "utl.h"
#include "itkMultiplyByConstantMatrixVectorImageFilter.h"
#include "SHCoefficientsToSphericalFunctionSamplesCLP.h"
#include "itkFunctors.h"
#include "itkUnaryFunctorVectorImageFilter.h"
Functions
int main (int argc, char const *argv[])
Detailed Description
Created "05-11-2013.
Author
Jian Cheng (JC), jian..nosp@m.chen.nosp@m.g.198.nosp@m.3@gm.nosp@m.ail.c.nosp@m.om
Definition in file SHCoefficientsToSphericalFunctionSamples.cxx.
Function Documentation
int main (int argc, char const * argv[])
calculate samples of a spherical function from its SH coefficients
Definition at line 22 of file SHCoefficientsToSphericalFunctionSamples.cxx.
References CARTESIAN_TO_CARTESIAN, CARTESIAN_TO_SPHERICAL, utl::ComputeSHMatrix(), utl::DimToRankSH(), DIRECTION_NODUPLICATE, itk::ReadVectorImage(), itk::SaveImage(), and itk::Functor::RPOWER< TInput, TArgument, TOutput >::SetArgument().