DMRITool: smart_assert::Assert Struct Reference
smart_assert::Assert Struct Reference
#include <utlSmartAssert.h>
Detailed Description
Definition at line 216 of file utlSmartAssert.h.
Public Types
typedef smart_assert::assert_func assert_func
Public Member Functions
Assert (const char *expr)
Assert (const Assert &other)
Assert & debug (const char *strMsg=0)
Assert & error (const char *strMsg=0)
Assert & fatal (const char *strMsg=0)
Assert & level (int nLevel, const char *strMsg=0)
Assert & log (const char *strMsg=0)
Assert & msg (const char *strMsg)
Assert & print_context (const char *file, int line)
Assert & print_context (const char *file, int line, const char *func, int cond)
template<class type >
Assert & print_current_val (const type &val, const char *msg)
Assert & warn (const char *strMsg=0)
~Assert ()
Static Public Member Functions
static void set_handler (int nLevel, assert_func handler)
static void set_log (const char *strFileName)
static void set_log (std::ostream &out)
static void set_log (assert_func log)
Public Attributes
Assert & SMART_ASSERT_A
Assert & SMART_ASSERT_B
Private Types
typedef std::map< int, assert_func > handlers_collection
Private Member Functions
void handle_assert ()
Static Private Member Functions
static assert_func get_handler (int nLevel)
static handlers_collection & handlers ()
static assert_func & logger ()
Private Attributes
assert_context context_
bool needs_handling_
Member Typedef Documentation
typedef smart_assert::assert_func smart_assert::Assert::assert_func
Definition at line 217 of file utlSmartAssert.h.
typedef std::map< int, assert_func> smart_assert::Assert::handlers_collection private
Definition at line 349 of file utlSmartAssert.h.
Constructor & Destructor Documentation
smart_assert::Assert::Assert (const char * expr) inline
Definition at line 223 of file utlSmartAssert.h.
References smart_assert::init_assert().
smart_assert::Assert::Assert (const Assert & other) inline
Definition at line 235 of file utlSmartAssert.h.
References needs_handling_.
smart_assert::Assert::~Assert () inline
Definition at line 243 of file utlSmartAssert.h.
Member Function Documentation
Assert& smart_assert::Assert::debug (const char * strMsg = 0) inline
Definition at line 291 of file utlSmartAssert.h.
References smart_assert::lvl_debug.
Assert& smart_assert::Assert::error (const char * strMsg = 0) inline
Definition at line 295 of file utlSmartAssert.h.
References smart_assert::lvl_error.
Assert& smart_assert::Assert::fatal (const char * strMsg = 0) inline
Definition at line 299 of file utlSmartAssert.h.
References smart_assert::lvl_fatal.
static assert_func smart_assert::Assert::get_handler (int nLevel) inline static private
Definition at line 355 of file utlSmartAssert.h.
References smart_assert::lvl_debug.
void smart_assert::Assert::handle_assert () inline private
Definition at line 327 of file utlSmartAssert.h.
static handlers_collection& smart_assert::Assert::handlers () inline static private
Definition at line 350 of file utlSmartAssert.h.
Assert& smart_assert::Assert::level (int nLevel, const char * strMsg = 0) inline
Definition at line 277 of file utlSmartAssert.h.
Assert& smart_assert::Assert::log (const char * strMsg = 0) inline
Definition at line 283 of file utlSmartAssert.h.
References smart_assert::lvl_log.
static assert_func& smart_assert::Assert::logger () inline static private
Definition at line 343 of file utlSmartAssert.h.
Assert& smart_assert::Assert::msg (const char * strMsg) inline
Definition at line 272 of file utlSmartAssert.h.
Assert& smart_assert::Assert::print_context (const char * file, int line) inline
Definition at line 263 of file utlSmartAssert.h.
Assert& smart_assert::Assert::print_context (const char * file, int line, const char * func, int cond) inline
Definition at line 267 of file utlSmartAssert.h.
template<class type > Assert& smart_assert::Assert::print_current_val (const type & val, const char * msg) inline
Definition at line 249 of file utlSmartAssert.h.
References smart_assert::is_null_finder< T >::is().
static void smart_assert::Assert::set_handler (int nLevel, assert_func handler) inline static
Definition at line 321 of file utlSmartAssert.h.
Referenced by smart_assert::init_assert().
static void smart_assert::Assert::set_log (const char * strFileName) inline static
Definition at line 305 of file utlSmartAssert.h.
References smart_assert::default_logger(), and smart_assert::set_default_log_name().
Referenced by smart_assert::init_assert().
static void smart_assert::Assert::set_log (std::ostream & out) inline static
Definition at line 312 of file utlSmartAssert.h.
References smart_assert::default_logger(), and smart_assert::set_default_log_stream().
static void smart_assert::Assert::set_log (assert_func log) inline static
Definition at line 317 of file utlSmartAssert.h.
Assert& smart_assert::Assert::warn (const char * strMsg = 0) inline
Definition at line 287 of file utlSmartAssert.h.
References smart_assert::lvl_warn.
Member Data Documentation
assert_context smart_assert::Assert::context_ private
Definition at line 365 of file utlSmartAssert.h.
bool smart_assert::Assert::needs_handling_ mutable private
Definition at line 366 of file utlSmartAssert.h.
Referenced by Assert().
Assert& smart_assert::Assert::SMART_ASSERT_A
Definition at line 220 of file utlSmartAssert.h.
Assert& smart_assert::Assert::SMART_ASSERT_B
Definition at line 221 of file utlSmartAssert.h.
The documentation for this struct was generated from the following file:
Modules/HelperFunctions/include/utlSmartAssert.h