DMRITool: Applications/DiffusionModels/TensorFormatConverter.cxx File Reference
TensorFormatConverter.cxx File Reference
#include "TensorFormatConverterCLP.h"
#include "itkImageRegionIteratorWithIndex.h"
#include "utl.h"
Functions
int main (int argc, char const *argv[])
Detailed Description
Created "06-27-2016.
Author
Jian Cheng (JC), jian..nosp@m.chen.nosp@m.g.198.nosp@m.3@gm.nosp@m.ail.c.nosp@m.om
Definition in file TensorFormatConverter.cxx.
Function Documentation
int main (int argc, char const * argv[])
Convert different tensor format.
Definition at line 19 of file TensorFormatConverter.cxx.
References utl::ConvertTensor6DTo6D(), utl::ConvertTensor6DTo9D(), utl::ConvertTensor9DTo6D(), itk::CopyImageInformation(), itk::ReadVectorImage(), itk::SaveImage(), TENSOR_DIAGONAL_FIRST, TENSOR_EMBED6D, TENSOR_LOWER_TRIANGULAR, TENSOR_UPPER_TRIANGULAR, and utlGlobalException.