DMRITool: Applications/Utilities/TextFileOperator.cxx File Reference
TextFileOperator.cxx File Reference
#include "utlCore.h"
#include "TextFileOperatorCLP.h"
Enumerations
enum {
OP_NULL,
OP_INFO,
OP_TRANSPOSE,
OP_EXTRACT,
OP_CONNECT_ROW,
OP_CONNECT_COLUMN,
OP_INDEX_ROW,
OP_SCALE
}
Functions
int main (int argc, char const *argv[])
void SetOperationWithChecking (int &operation, int value)
Detailed Description
Author
Dr. Jian Cheng (JC), jian..nosp@m.chen.nosp@m.g.198.nosp@m.3@gm.nosp@m.ail.c.nosp@m.om
Definition in file TextFileOperator.cxx.
Enumeration Type Documentation
anonymous enum
Enumerator
OP_NULL
OP_INFO
OP_TRANSPOSE
OP_EXTRACT
OP_CONNECT_ROW
OP_CONNECT_COLUMN
OP_INDEX_ROW
OP_SCALE
Definition at line 22 of file TextFileOperator.cxx.
Function Documentation
int main (int argc, char const * argv[])
operators for text file
Definition at line 53 of file TextFileOperator.cxx.
References utl::ConvertNumberToString(), utl::IsNumber(), utl::max(), utl::min(), OP_CONNECT_COLUMN, OP_CONNECT_ROW, OP_EXTRACT, OP_INDEX_ROW, OP_INFO, OP_NULL, OP_SCALE, OP_TRANSPOSE, utl::ReadLines(), utl::ReadVector(), utl::Save2DVector(), utl::SelectVector(), SetOperationWithChecking(), and utlException.
void SetOperationWithChecking (int & operation, int value)
Definition at line 35 of file TextFileOperator.cxx.
References OP_NULL.
Referenced by main().