DMRITool: Applications/Utilities/VectorImageNormalization.cxx File Reference
VectorImageNormalization.cxx File Reference
#include "itkNormalizeVectorImageFilter.h"
#include "utlITK.h"
#include "VectorImageNormalizationCLP.h"
#include "itkSpatiallyDenseSparseVectorImage.h"
#include "itkSpatiallyDenseSparseVectorImageFileReader.h"
#include "itkSpatiallyDenseSparseVectorImageFileWriter.h"
Functions
int main (int argc, char const *argv[])
Detailed Description
Author
Dr. Jian Cheng (JC), jian..nosp@m.chen.nosp@m.g.198.nosp@m.3@gm.nosp@m.ail.c.nosp@m.om
Definition in file VectorImageNormalization.cxx.
Function Documentation
int main (int argc, char const * argv[])
Normalize each voxel in a VectorImage or SparseVectorImage.
Author
Jian Cheng (jian..nosp@m.chen.nosp@m.g.198.nosp@m.3@gm.nosp@m.ail.c.nosp@m.om)
Definition at line 32 of file VectorImageNormalization.cxx.
References itk::IsSparseImage(), itk::ReadImage(), itk::SaveImage(), and utlGlobalException.