DMRITool: QTApplications/vtkviewer/VTKViewer.cxx File Reference
VTKViewer.cxx File Reference
#include <iostream>
#include <vtkAppendPolyData.h>
#include <vtkCamera.h>
#include <vtkColorTransferFunction.h>
#include <vtkDataSetReader.h>
#include <vtkDataSetSurfaceFilter.h>
#include <vtkFloatArray.h>
#include <vtkGlyph3D.h>
#include <vtkOBJReader.h>
#include <vtkPDBReader.h>
#include <vtkPLYReader.h>
#include <vtkPNGWriter.h>
#include <vtkPointData.h>
#include <vtkPolyData.h>
#include <vtkPolyDataMapper.h>
#include <vtkPolyDataNormals.h>
#include <vtkPolyDataReader.h>
#include <vtkProperty.h>
#include <vtkRenderWindow.h>
#include <vtkSphereSource.h>
#include <vtkSTLReader.h>
#include <vtkTubeFilter.h>
#include <vtkVersion.h>
#include <vtkWindowToImageFilter.h>
#include <vtkXMLImageDataReader.h>
#include <vtkXMLPolyDataReader.h>
#include <vtkXMLRectilinearGridReader.h>
#include <vtkXMLStructuredGridReader.h>
#include <vtkXMLUnstructuredGridReader.h>
#include "VTKViewer.h"
Macros
#define addInputData(x, y) ((x)->AddInput(y))
#define setInputData(x, y) ((x)->SetInput(y))
Functions
static vtkSmartPointer< vtkPolyData > ConvertDataSetToSurface (vtkAlgorithmOutput *outputPort)
int GetVTKStereoType (const QByteArray &stereoType)
template<typename T >
static vtkSmartPointer< vtkPolyData > read (const char *file_name)
template<typename T >
static vtkSmartPointer< vtkPolyData > readDataSet (const char *file_name)
static vtkSmartPointer< vtkPolyData > ReadLegacyVTK (const char *file_name)
static vtkSmartPointer< vtkPolyData > ReadPDB (const char *file_name)
Macro Definition Documentation
#define addInputData (x, y) ((x)->AddInput(y))
Definition at line 50 of file VTKViewer.cxx.
Referenced by ReadPDB().
#define setInputData (x, y) ((x)->SetInput(y))
Definition at line 49 of file VTKViewer.cxx.
Referenced by VTKViewer::add().
Function Documentation
static vtkSmartPointer< vtkPolyData > ConvertDataSetToSurface (vtkAlgorithmOutput * outputPort) static
Definition at line 118 of file VTKViewer.cxx.
Referenced by VTKViewer::add(), readDataSet(), and ReadLegacyVTK().
int GetVTKStereoType (const QByteArray & stereoType)
Definition at line 177 of file VTKViewer.cxx.
Referenced by VTKViewer::VTKViewer().
template<typename T > static vtkSmartPointer< vtkPolyData > read (const char * file_name) static
Definition at line 131 of file VTKViewer.cxx.
template<typename T > static vtkSmartPointer< vtkPolyData > readDataSet (const char * file_name) static
Definition at line 142 of file VTKViewer.cxx.
References ConvertDataSetToSurface().
static vtkSmartPointer< vtkPolyData > ReadLegacyVTK (const char * file_name) static
Definition at line 150 of file VTKViewer.cxx.
References ConvertDataSetToSurface().
Referenced by VTKViewer::add().
static vtkSmartPointer< vtkPolyData > ReadPDB (const char * file_name) static
Definition at line 60 of file VTKViewer.cxx.
References addInputData.
Referenced by VTKViewer::add().